### ISSUE TITLE
Synapse and PostgreSQL 12.6 issue

### ISSUE THREAD

**Issue by Justinzobel** [matrix-org/synapse#10031]
### Description

Synapse 1.34.0+focal1 will not start with PostgreSQL 12.6 on Ubuntu 20.04.

### Steps to reproduce

- Upgraded OS
- Upgraded Synapse (via Matrix apt repository)
- Issue occurred during upgrade of Synapse
- 
```
2021-05-21 01:56:48,947 - twisted - 258 - ERROR - sentinel - Traceback (most recent call last):
2021-05-21 01:56:48,947 - twisted - 258 - ERROR - sentinel -   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-05-21 01:56:48,948 - twisted - 258 - ERROR - sentinel -     return _run_code(code, main_globals, None,
2021-05-21 01:56:48,949 - twisted - 258 - ERROR - sentinel -   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-05-21 01:56:48,949 - twisted - 258 - ERROR - sentinel -     exec(code, run_globals)
2021-05-21 01:56:48,949 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 507, in <module>
2021-05-21 01:56:48,950 - twisted - 258 - ERROR - sentinel -     main()
2021-05-21 01:56:48,950 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 502, in main
2021-05-21 01:56:48,950 - twisted - 258 - ERROR - sentinel -     hs = setup(sys.argv[1:])
2021-05-21 01:56:48,951 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 360, in setup
2021-05-21 01:56:48,951 - twisted - 258 - ERROR - sentinel -     hs.setup()
2021-05-21 01:56:48,951 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/server.py", line 280, in setup
2021-05-21 01:56:48,952 - twisted - 258 - ERROR - sentinel -     self.datastores = Databases(self.DATASTORE_CLASS, self)
2021-05-21 01:56:48,952 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 50, in __init__
2021-05-21 01:56:48,952 - twisted - 258 - ERROR - sentinel -     engine.check_database(db_conn)
2021-05-21 01:56:48,953 - twisted - 258 - ERROR - sentinel -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/engines/postgres.py", line 50, in check_database
2021-05-21 01:56:48,953 - twisted - 258 - ERROR - sentinel -     raise RuntimeError("Synapse requires PostgreSQL 9.6 or above.")
2021-05-21 01:56:48,953 - twisted - 258 - ERROR - sentinel - RuntimeError: Synapse requires PostgreSQL 9.6 or above.
```

**Comment by Justinzobel** [comment]
```
psql --version
psql (PostgreSQL) 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1)
```

**Comment by 4nd3r** [comment]
can you check this?

```
$ python3
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> c = psycopg2.connect(host='127.0.0.1', user='synapse', password='secret')
>>> c.server_version
110012
```

because that check is rather trivial:
https://github.com/matrix-org/synapse/blob/develop/synapse/storage/engines/postgres.py#L49

**Comment by Justinzobel** [comment]
After c = psycopg2.connect(host='127.0.0.1', user='mymatrixusername', password='mymatrixsecret')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "matrix" does not exist
```

**Comment by Justinzobel** [comment]
OK so my package version says 12.6 but psycopg2 says 90525 which I'm guessing is 9.something...

I guess I need to update the database or migrate it.

**Comment by Half-Shot** [comment]
Worth mentioning that `psql --version` is not the version of your postgresql server but the version of the `psql` client.

**Comment by Justinzobel** [comment]
Worked it out in the end, took a lot of digging but I got there in the end, thanks everyone.
