### ISSUE TITLE
Sync fails on v1.35.0rc1/develop with M_UNKNOWN

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#10060]
### Description
After the v1.35.0rc1 release I updated develop branch and now sync returns error 500 with M_UNKNOWN. Log is attached below

### Steps to reproduce

- Install develop branch

```
2021-05-25 12:19:38,364 - synapse.replication.tcp.handler - 276 - ERROR - process-replication-data-6239753 - Failed to handle command <synapse.replication.tcp.commands.RdataCommand object at 0x7f7bf766b198>
Traceback (most recent call last):
  File "/opt/synapse/synapse_git/synapse/replication/tcp/handler.py", line 274, in _unsafe_process_queue
    await self._process_command(cmd, conn, stream_name)
  File "/opt/synapse/synapse_git/synapse/replication/tcp/handler.py", line 289, in _process_command
    await self._process_rdata(stream_name, conn, cmd)
  File "/opt/synapse/synapse_git/synapse/replication/tcp/handler.py", line 485, in _process_rdata
    await self.on_rdata(stream_name, cmd.instance_name, cmd.token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/tcp/handler.py", line 501, in on_rdata
    stream_name, instance_name, token, rows
  File "/opt/synapse/synapse_git/synapse/replication/tcp/client.py", line 146, in on_rdata
    self.store.process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/presence.py", line 306, in process_replication_rows
    "state",
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/deviceinbox.py", line 110, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/slave/storage/devices.py", line 61, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/slave/storage/push_rule.py", line 37, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/slave/storage/groups.py", line 46, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/account_data.py", line 372, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/slave/storage/pushers.py", line 44, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/replication/slave/storage/room.py", line 37, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/receipts.py", line 479, in process_replication_rows
    return super().process_replication_rows(stream_name, instance_name, token, rows)
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/events_worker.py", line 189, in process_replication_rows
  File "/opt/synapse/synapse_git/synapse/storage/databases/main/cache.py", line 129, in process_replication_rows
    self._attempt_to_invalidate_cache(row.cache_func, row.keys)
  File "/opt/synapse/synapse_git/synapse/storage/_base.py", line 97, in _attempt_to_invalidate_cache
    cache.invalidate(tuple(key))
AttributeError: 'function' object has no attribute 'invalidate'
```

I am using workers

### Version information

- **Homeserver**: matrix.nordgedanken.dev

If not matrix.org:

- **Version**: `{"server_version":"1.35.0rc1 (b=develop,t=v1.35.0rc1,557635f69)","python_version":"3.7.3"}`

- **Install method**: PIP via git

- **Platform**: Debian 10

**Comment by erikjohnston** [comment]
I think this is because you only update half the workers? It should stop happening once all workers are updated?

**Comment by MTRNord** [comment]
Oh does systemctl default to service instead of target? Oo That would be the problem. It works again. Sorry for the noise
