### ISSUE TITLE
1.35.0rc3 (and rc2) fail tests

### ISSUE THREAD

**Issue by Bubu** [matrix-org/synapse#10100]
### Description

I part of building synapse packages for my server I run the synapse test suite. Everything was fine for 1.35.0rc1 (I just retested that this *still* works, to rule out dependency upgrades.)

When trying to build 1.35.0rc3 (and lates also tested rc2) I get the following test failures, I retried a few times to rule out flaky tests as well. I have not yet had time to investigate what is going on:
```
tests.test_visibility.FilterEventsForServerTestCase.test_large_room
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/events/test_presence_router.py", line 284, in test_send_local_online_presence_to_with_module
    self.assertEqual(len(presence_updates), 3)
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 3

tests.events.test_presence_router.PresenceRouterTestCase.test_send_local_online_presence_to_with_module
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/events/test_presence_router.py", line 187, in test_receiving_all_presence
    self.assertEqual(len(presence_updates), 3)
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 3

tests.events.test_presence_router.PresenceRouterTestCase.test_receiving_all_presence
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/module_api/test_api.py", line 226, in test_send_local_online_presence_to
    _test_sending_local_online_presence_to_local_user(self, test_with_workers=False)
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/module_api/test_api.py", line 407, in _test_sending_local_online_presence_to_local_user
    test_case.assertEqual(len(presence_updates), 0)
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 1 != 0

tests.module_api.test_api.ModuleApiTestCase.test_send_local_online_presence_to
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/rest/client/v2_alpha/test_sync.py", line 305, in test_sync_backwards_typing
    self.make_request("GET", sync_url % (access_token, next_batch))
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 313, in __exit__
    self._testCase.fail(
twisted.trial.unittest.FailTest: TimedOutException not raised (None returned)

tests.rest.client.v2_alpha.test_sync.SyncTypingTests.test_sync_backwards_typing
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/storage/test_client_ips.py", line 133, in test_insert_new_client_ip_none_device_id
    self.assertEqual(
  File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 424, in assertEqual
    super().assertEqual(first, second, msg)
  File "/usr/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.9/unittest/case.py", line 1037, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python3.9/unittest/case.py", line 1019, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [{'ac[51 chars]t': 'user_agent', 'device_id': None, 'last_seen': 12345678000}] != [{'ac[51 chars]t': 'user_agent', 'device_id': None, 'last_seen': 12345878000}]

First differing element 0:
{'acc[49 chars]nt': 'user_agent', 'device_id': None, 'last_seen': 12345678000}
{'acc[49 chars]nt': 'user_agent', 'device_id': None, 'last_seen': 12345878000}

  [{'access_token': 'access_token',
    'device_id': None,
    'ip': 'ip',
-   'last_seen': 12345678000,
?                     ^

+   'last_seen': 12345878000,
?                     ^

    'user_agent': 'user_agent'}]

tests.storage.test_client_ips.ClientIpStoreTestCase.test_insert_new_client_ip_none_device_id
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/server_notices/test_consent.py", line 95, in test_get_sync_message
    room = channel.json_body["rooms"]["join"][room_id]
builtins.KeyError: '!ydntBywsJiUjNbThUR:test'

tests.server_notices.test_consent.ConsentNoticesTests.test_get_sync_message
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/bubu/build/community/matrix-synapse/trunk/src/synapse-1.35.0rc3/tests/server_notices/test_resource_limits_server_notices.py", line 324, in test_invite_with_notice
    events = channel.json_body["rooms"]["join"][room_id]["timeline"]["events"]
builtins.KeyError: '!qBUbkfeEhNibJInepK:test'

tests.server_notices.test_resource_limits_server_notices.TestResourceLimitsServerNoticesWithRealRooms.test_invite_with_notice
-------------------------------------------------------------------------------
Ran 1640 tests in 211.214s

FAILED (skips=17, failures=5, errors=2, successes=1616)
```
### Version information

- **Install method**:
archlinux package build

- **Platform**:
Arch

**Comment by anoadragon453** [comment]
Thank you for the report!

It turns out we accidentally cut the tag from `matrix-org-hotfixes` instead of the `release-v1.35` branch. `matrix-org-hotfixes` still contain the commits from `release-v1.35`, but lots of other matrix.org-specific changes as well. Tests do pass if you run them on the `release-v1.35` branch. The full release will be cut from the `release-v1.35` branch instead.

Thanks again for catching!
