### ISSUE TITLE
Synapse crash

### ISSUE THREAD

**Issue by Jental** [matrix-org/synapse#1014]
Synapse crashes. After about 4 hours of work.
Not exactly crashes, in fact. There's an error in the log, but it still hangs in the memory, eating around 100% of CPU. No responses on any requests.

Synapse version: v0.17.0  Haven't seen such behaviour on older versions.
OS: Linux (Linux 4.6.1-2-ARCH x86_64)

Synapse was run with the following command:
`/usr/bin/python2.7 -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml --verbose`

Crash dump:

```
2016-08-16 14:15:20,063 - twisted - 154 - INFO - - Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f7ecbc8d650>
Unhandled error in Deferred:
2016-08-16 14:15:20,141 - twisted - 154 - CRITICAL - - Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop

  File "/usr/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 201, in f

  File "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent

  File "/usr/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__

--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred

  File "/usr/lib/python2.7/site-packages/synapse/metrics/metric.py", line 178, in _update_curr_values

  File "/usr/lib/python2.7/site-packages/psutil/__init__.py", line 993, in memory_info

  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 962, in wrapper

  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 1130, in memory_info

  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 180, in open_binary

exceptions.IOError: [Errno 24] Too many open files: '/proc/28412/statm'
2016-08-16 14:15:20,161 - twisted - 154 - CRITICAL - -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
  File "/usr/lib/python2.7/site-packages/synapse/metrics/metric.py", line 178, in _update_curr_values
  File "/usr/lib/python2.7/site-packages/psutil/__init__.py", line 993, in memory_info
  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 962, in wrapper
  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 1130, in memory_info
  File "/usr/lib/python2.7/site-packages/psutil/_pslinux.py", line 180, in open_binary
IOError: [Errno 24] Too many open files: '/proc/28412/statm'
2016-08-16 14:15:20,303 - synapse.handlers.presence - 286 - INFO - - Handling presence timeouts
```

**Comment by Half-Shot** [comment]
Looks like it's getting stuck: ``Too many open files: '/proc/28412/statm'``

**Comment by Jental** [comment]
Synapse hang up and stopped responding to anything.
Now absolutely quietly.
Have seen such behaviour for the first time

Synapse was run with the following command:
`/usr/bin/python2.7 -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml --verbose`

Here's a log (log parts). It contains previous error too.
[homeserver.log.4.txt](https://github.com/matrix-org/synapse/files/420620/homeserver.log.4.txt)
[homeserver.log.3.txt](https://github.com/matrix-org/synapse/files/420621/homeserver.log.3.txt)
[homeserver.log.2.txt](https://github.com/matrix-org/synapse/files/420623/homeserver.log.2.txt)
[homeserver.log.1.txt](https://github.com/matrix-org/synapse/files/420622/homeserver.log.1.txt)
[homeserver.log.0.txt](https://github.com/matrix-org/synapse/files/420624/homeserver.log.0.txt)

**Comment by Jental** [comment]
Maybe the second problem caused the first one.

I've commented a register_memory_metrics call in app/homeserver.py
so the first problem described should not happen. And it really doesn't.
Synapse just hangs now, as it was described in the previous comment, without errors in log.

**Comment by Half-Shot** [comment]
Heh, I appear to be getting symptoms of this too now. Hanging (and in some cases, hanging the whole system due to pushing the load averages to the point of no return). I also seem to have the ``Too many open files`` error.

**Comment by richvdh** [comment]
There have been various bugs which caused FD leaks over the months - #1778 and #1991 for example. Either way I'd expect this to be better now.
