### ISSUE TITLE
HTTP GET ./sync - NotImplementedError

### ISSUE THREAD

**Issue by parsifallo** [matrix-org/synapse#10174]
### Description

Hey! I've got a problem with synapse. My log is getting full with the following ERROR Message and I don't know where this comes from:

```
2021-06-14 10:56:33,065 - synapse.http.server - 93 - ERROR - GET-53740 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7fde83acbf40 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=30000' clientproto='HTTP/1.0' site='8008'>

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 446, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v2_alpha/sync.py", line 180, in on_GET
    sync_result = await self.sync_handler.wait_for_sync_for_user(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 289, in wait_for_sync_for_user
    res = await self.response_cache.wrap(
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 321, in _wait_for_sync_for_user
    result = await self.current_sync_for_user(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 354, in current_sync_for_user
    sync_result = await self.generate_sync_result(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 999, in generate_sync_result
    raise NotImplementedError()
NotImplementedError
```

### Steps to reproduce

- Can't tell. After an upgrade this came up.

### Version information

- **Homeserver**: p3a.io
- **Version**: 1.35.1
- **Install method**: docker-compose
- **Platform**: hosted virtual machine

**Comment by clokep** [comment]
It looks like this is coming from an appservice trying to call sync. Are you using any appservices?

**Comment by parsifallo** [comment]
Hey! Sorry for my late response - hadn't had the time for looking into it. Yes, I am using appservices: mautrix signal, whatsapp and telegram as well as mx-puppet-discord. All dockerized with latest version.

If I look inside logs of the whatsapp bridge I see these errors:
`[Jun 22, 2021 08:03:19] [Crypto/ERROR] Error /syncing, waiting 10 seconds: failed to GET /_matrix/client/r0/sync: M_UNKNOWN (HTTP 500): Internal server error`

Looks like a problem with mautrix-whatsapp :(

**Comment by clokep** [comment]
> Looks like a problem with mautrix-whatsapp :(

Looks like tulir/mautrix-whatsapp#196.
