### ISSUE TITLE
Exception While Login

### ISSUE THREAD

**Issue by sameerjagtap** [matrix-org/synapse#10181]
### Description
Hey! I've got a problem with synapse. My log is getting full with the following ERROR Message while log in:

2021-06-15 09:16:15,820 - synapse.rest.client.v1.login - 217 - INFO - POST-28554 - Got login request with identifier: {'type': 'm.id.user', 'user': 'sameer.jagtap'}, medium: None, address: None, user: None
2021-06-15 09:16:15,821 - rest_auth_provider - 46 - INFO - POST-28554 - Got password check for @sameer.jagtap:connect.zzz.com
2021-06-15 09:16:16,609 - synapse.http.server - 98 - ERROR - POST-28554 - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f9e6ca523c8 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 259, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 447, in _async_render
    callback_return = await raw_callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 158, in on_POST
    result = await self._do_other_login(login_submission)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 220, in _do_other_login
    login_submission, ratelimit=True
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/auth.py", line 1047, in validate_login
    return await self._validate_userid_login(username, login_submission)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/auth.py", line 1114, in _validate_userid_login
    result = await provider.check_auth(username, login_type, login_dict)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/auth.py", line 1731, in check_auth
    qualified_user_id, login_dict["password"]
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
    result = current_context.run(g.send, result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/rest_auth_provider.py", line 49, in check_password
    r.raise_for_status()
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://connect.zzz.com:8090/_matrix-internal/identity/v1/check_credentials

### Steps to reproduce

- Trying to login from the Element app or Element web.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

- **Version**:
"server_version":"1.31.0","python_version":"3.6.9"
- Hosted Virtual Machine

**Comment by erikjohnston** [comment]
You have configured an external service to check the passwords, which is returning a 500 error:

> `500 Server Error: Internal Server Error for url: http://connect.zzz.com:8090/_matrix-internal/identity/v1/check_credentials`

So the issue is likely in that service rather than in Synapse.
