### ISSUE TITLE
Incomplete database migration after upgrading to 1.37.1rc1 from 1.37.0

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#10278]
I have two Synapse processes: one main process and one synchrotron. After upgrading from v1.37.0 to v1.37.1rc1 I restarted both, and noticed that the synchrotron was failing to start. It was waiting for the main process to complete a database migration.

Waiting a few moments, I then proceeded to try restarting the synchrotron again, but accidentally restarted the main process as well. The synchrotron still complained about the database migration, whereas the main process was up and running, but now complaining about the `federation_inbound_events_staging` table being missing.

The synchrotron, although on v1.37.1rc1, seems to be expecting database schema `59`:

```
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,714 - root - 323 - WARNING - main- ***** STARTING SERVER *****
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,714 - root - 324 - WARNING - main- Server /home/synapse/synapse/env/lib/python3.8/site-packages/synapse/app/generic_worker.py version 1.37.1rc1
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,714 - root - 325 - INFO - main- Server hostname: amorgan.xyz
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,714 - root - 326 - INFO - main- Instance name: synapse.app.synchrotron
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,714 - synapse.server - 309 - INFO - main- Setting up.
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,734 - synapse.storage.databases - 49 - INFO - main- [database config 'master']: Checking database server
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,736 - synapse.storage.engines.postgres - 66 - WARNING - main- Database has incorrect collation of 'en_US.UTF-8'. Should be 'C'
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: See docs/postgres.md for more information.
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,736 - synapse.storage.engines.postgres - 73 - WARNING - main- Database has incorrect ctype of 'en_US.UTF-8'. Should be 'C'
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: See docs/postgres.md for more information.
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,736 - synapse.storage.databases - 52 - INFO - main- [database config 'master']: Preparing for databases ['main', 'state']
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,736 - synapse.storage.prepare_database - 116 - INFO - main- ['main', 'state']: Checking existing schema version
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,739 - synapse.storage.prepare_database - 120 - INFO - main- ['main', 'state']: Existing schema is 60 (+1 deltas)
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: 2021-06-30 11:36:54,740 - synapse.app._base - 155 - ERROR - main- Exception during startup
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: Traceback (most recent call last):
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:   File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/app/generic_worker.py", line 480, in start
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:     hs.setup()
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:   File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/server.py", line 311, in setup
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:     self.datastores = Databases(self.DATASTORE_CLASS, self)
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:   File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/databases/__init__.py", line 57, in __init__
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:     prepare_database(
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:   File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/prepare_database.py", line 140, in prepare_database
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:     raise UpgradeDatabaseException(
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: synapse.storage.prepare_database.UpgradeDatabaseException: Expected database schema version 59 but got 60: run the main synapse process to upgrade the database schema before st>
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: **********************************************************************************
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:  Error during initialisation:
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:     Expected database schema version 59 but got 60: run the main synapse process to upgrade the database schema before starting worker processes.
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]:  There may be more information in the logs.
Jun 30 11:36:54 synapse matrix-synapse-synchrotron1[644830]: **********************************************************************************
```

I've tried running the contents of [`federation_inbound_events_staging`'s create and index statements](https://github.com/matrix-org/synapse/blob/785bceef726789e6969c98be89b073f2e1c10a92/synapse/storage/schema/main/delta/59/16federation_inbound_staging.sql#L31) manually, which has made the main process happy (at least not spewing errors), but done little for the synchrotron.

**Comment by erikjohnston** [comment]
It looks like you have run a branch (develop?) that added a schema 60 version?

**Comment by callahad** [comment]
From chat:

@anoadragon453 had previously run `develop` which has schema version 60.

Setting `schema_version.version=59` and restarting will run the missed migrations

**Comment by anoadragon453** [comment]
And indeed it did.
