### ISSUE TITLE
Traceback when fetching remote media

### ISSUE THREAD

**Issue by moritzdietz** [matrix-org/synapse#10318]
### Description

When I was watching the homeserver.log file I noticed the following lines going by.
```text
2021-07-05 22:56:01,678 - synapse.http.server - 93 - ERROR - GET-114720 - Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x7f74e7313400 method='GET' uri='/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 286, in _async_render
    callback_return = await raw_callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 83, in _async_render_GET
    await self._respond_remote_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 265, in _respond_remote_thumbnail
    await self._select_and_respond_with_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 306, in _select_and_respond_with_thumbnail
    file_info = self._select_thumbnail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 481, in _select_thumbnail
    thumbnail_info = min(info_list)[-1]
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
I couldn't find an open or closed issue regarding this error so I thought I'd open an issue for it.

### Steps to reproduce

I can reproduce it with curl
```
curl "https://matrix.moritzdietz.com/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale"
```
which results in the error above.
I can fetch the media just fine via matrix.org:
```bash
curl -L "https://matrix-federation.matrix.org/_matrix/media/r0/thumbnail/matrix.org/dOhWUOiqfTEPQASnYCLKLINu?width=800&height=600&method=scale" -o somemedia.png
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: `matrix.moritzdietz.com`

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: `1.37.1`

- **Install method**: `package manager`
<!-- examples: package manager/git clone/pip  -->

- **Platform**: `Ubuntu 20.04 Server`
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
I have `dynamic_thumbnails` set to false (as it's the default).

**Comment by erikjohnston** [comment]
What is your `thumbnail_sizes` config? I think you might hit this if it has duplicate values in it?

**Comment by moritzdietz** [comment]
I checked my yaml file and in neither the one shipped with my package manager nor the drop in yaml file in `.conf.d/` has an activated yaml hash for that configuration.
Meaning: everything is commented out which controls the setting you mentioned.

My reasoning was that there must be some default and I can leave it like it is unless I really need to change or adapt it.

**Comment by erikjohnston** [comment]
The issue is here: https://github.com/matrix-org/synapse/blob/4b965c862dc66c0da5d3240add70e9b5f0aa720b/synapse/rest/media/v1/thumbnail_resource.py#L481, `info_list` is a list of tuples, where the last entry is a dict. I think what is happening is we're getting entries in there where all the numbers match, and so it tries and compares by the last entry in the tuple, which then fails. The fix would be to either a) deduplicate the list before sorting or b) using the `key` param to `min` to make the comparisons ignore the dict part.
