### ISSUE TITLE
matrix-synapse can't be purged completly and can't be reinstalled.

### ISSUE THREAD

**Issue by JokerGermany** [matrix-org/synapse#10387]
### Description
Ubuntu Server 18.04
Repo: https://matrix.org/packages/debian/

I wanted to start again from the scratch, because i made a url mistake. The server wasn't registered or had any contact to other matrix servers.

Therefore I tried to purge it
`sudo apt-get purge matrix-synapse`

The directories /var/lib/matrix-synapse and /etc/matrix-synapse wasn't deleted, therefore I deleted them manual.
Then i had to disable it, too 
`sudo systemctl disable matrix-synapse`

Then i tried to reinstall it, but i wasn't asked for a configuration like at the first time.
Therefore i reconfigured it:
`sudo dpkg-reconfigure matrix-synapse`

After this i tried to start it:
`sudo systemctl start matrix-synapse`

But i got this error:
journalctl -xe
```
-- 
-- Unit matrix-synapse.service has failed.
-- 
-- The result is RESULT.
Jul 13 21:09:29 nas systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Jul 13 21:09:29 nas systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 234.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit matrix-synapse.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Jul 13 21:09:29 nas systemd[1]: Stopped Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit matrix-synapse.service has finished shutting down.
Jul 13 21:09:29 nas systemd[1]: Starting Synapse Matrix homeserver...
-- Subject: Unit matrix-synapse.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit matrix-synapse.service has begun starting up.
Jul 13 21:09:29 nas python[27388]: Traceback (most recent call last):
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Jul 13 21:09:29 nas python[27388]:     "__main__", fname, loader, pkg_name)
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Jul 13 21:09:29 nas python[27388]:     exec code in run_globals
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 449, in <module>
Jul 13 21:09:29 nas python[27388]:     main()
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 444, in main
Jul 13 21:09:29 nas python[27388]:     hs = setup(sys.argv[1:])
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 264, in setup
Jul 13 21:09:29 nas python[27388]:     config_options,
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 338, in load_or_generate_config
Jul 13 21:09:29 nas python[27388]:     generate_keys=generate_keys,
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 357, in read_config_files
Jul 13 21:09:29 nas python[27388]:     yaml_config = self.read_config_file(config_file)
Jul 13 21:09:29 nas python[27388]:   File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 155, in read_config_file
Jul 13 21:09:29 nas python[27388]:     with open(file_path) as file_stream:
Jul 13 21:09:29 nas python[27388]: IOError: [Errno 2] No such file or directory: '/etc/matrix-synapse/homeserver.yaml'
Jul 13 21:09:29 nas systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Jul 13 21:09:29 nas systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jul 13 21:09:29 nas systemd[1]: Failed to start Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit matrix-synapse.service has failed.
-- 
-- The result is RESULT.
```

It looks like the directory aren't created anymore.

I just want to use mx-puppet-discord...

**Comment by Akkowicz** [comment]
Hi, I've tried several scenarios on 18.04 with installing and purging the package, but the installer asked me for config every time.   
You may want to use find to check if there are any synapse files left after purge.   

I'm normally not using the apt package, but it seems like you are using an old synapse version from Debian repos instead of the official matrix.org repository.

Please check: https://matrix-org.github.io/synapse/latest/setup/installation.html#debianubuntu

For easier maintenance and configuration, you may want to check:
https://github.com/spantaleev/matrix-docker-ansible-deploy

**Comment by richvdh** [comment]
> Therefore I tried to purge it
> `sudo apt-get purge matrix-synapse`

`matrix-synapse` is a dummy package. If you want to purge it properly, you want `matrix-synapse-py3` (see also #5215).

**Comment by ShadowJonathan** [comment]
You could do `apt autovaccuum` after removing the package, to remove all packages that were pinned by that

**Comment by richvdh** [comment]
I'm assuming this is user error, due to purging the wrong package.
