### ISSUE TITLE
Database error: no such table: federation_inbound_events_staging

### ISSUE THREAD

**Issue by Imaskiller** [matrix-org/synapse#10522]
### Steps to reproduce

- restart synapse and the error happens after a few seconds

``` 
2021-08-04 07:12:41,333 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 0/5
2021-08-04 07:12:41,335 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 1/5
2021-08-04 07:12:41,337 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 2/5
2021-08-04 07:12:41,338 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 3/5
2021-08-04 07:12:41,339 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 4/5
2021-08-04 07:12:41,340 - synapse.storage.txn - 561 - WARNING - _get_stats_for_federation_staging-0 - [TXN OPERROR] {_get_stats_for_federation_staging-39} no such table: federation_inbound_events_staging 5/5
2021-08-04 07:12:41,342 - synapse.metrics.background_process_metrics - 217 - ERROR - _get_stats_for_federation_staging-0 - Background process '_get_stats_for_federation_staging' threw an exception
Traceback (most recent call last):
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 213, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/databases/main/event_federation.py", line 1240, in _get_stats_for_federation_staging
    "_get_stats_for_federation_staging", _get_stats_for_federation_staging_txn
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 689, in runInteraction
    **kwargs,
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 771, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 255, in <lambda>
    ctx, func, *args, **kw
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
    return function(*args, **kwargs)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/python/compat.py", line 403, in reraise
    raise exception.with_traceback(traceback)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 765, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 549, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/databases/main/event_federation.py", line 1225, in _get_stats_for_federation_staging_txn
    "SELECT coalesce(count(*), 0) FROM federation_inbound_events_staging"
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 297, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/pi/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 330, in _do_execute
    return func(sql, *args)
sqlite3.OperationalError: no such table: federation_inbound_events_staging
```

### Version information

- **Homeserver**:
selfhosted homeserver

- **Version**:
1.39

- **Install method**:
pip

- **Platform**:
Raspbian 32 bit on rpi 4b 4gb

**Comment by babolivier** [comment]
Could you do paste the output of `SELECT * FROM applied_schema_deltas;` please?

**Comment by Imaskiller** [comment]
Here you go:
```
55|55/access_token_expiry.sql
55|55/track_threepid_validations.sql
55|55/users_alter_deactivated.sql
56|56/add_spans_to_device_lists.sql
56|56/current_state_events_membership.sql
56|56/current_state_events_membership_mk2.sql
56|56/delete_keys_from_deleted_backups.sql
56|56/destinations_failure_ts.sql
56|56/device_stream_id_insert.sql
56|56/devices_last_seen.sql
56|56/drop_unused_event_tables.sql
56|56/event_expiry.sql
56|56/event_labels.sql
56|56/event_labels_background_update.sql
56|56/fix_room_keys_index.sql
56|56/hidden_devices.sql
56|56/hidden_devices_fix.sql.sqlite
56|56/nuke_empty_communities_from_db.sql
56|56/public_room_list_idx.sql
56|56/redaction_censor.sql
56|56/redaction_censor2.sql
56|56/redaction_censor4.sql
56|56/remove_tombstoned_rooms_from_directory.sql
56|56/room_key_etag.sql
56|56/room_membership_idx.sql
56|56/room_retention.sql
56|56/signing_keys.sql
56|56/signing_keys_nonunique_signatures.sql
56|56/state_group_room_idx.sql
56|56/stats_separated.sql
56|56/unique_user_filter_index.py
56|56/user_external_ids.sql
56|56/users_in_public_rooms_idx.sql
57|57/delete_old_current_state_events.sql
57|57/device_list_remote_cache_stale.sql
57|57/local_current_membership.py
57|57/remove_sent_outbound_pokes.sql
57|57/rooms_version_column.sql
57|57/rooms_version_column_2.sql.sqlite
57|57/rooms_version_column_3.sql.sqlite
58|58/00background_update_ordering.sql
58|58/02remove_dup_outbound_pokes.sql
58|58/03persist_ui_auth.sql
58|58/06dlols_unique_idx.py
58|58/07add_method_to_thumbnail_constraint.sql.sqlite
58|58/07persist_ui_auth_ips.sql
58|58/08_media_safe_from_quarantine.sql.sqlite
58|58/09shadow_ban.sql
58|58/10_pushrules_enabled_delete_obsolete.sql
58|58/10drop_local_rejections_stream.sql
58|58/10federation_pos_instance_name.sql
58|58/11dehydration.sql
58|58/11fallback.sql
58|58/11user_id_seq.py
58|58/12room_stats.sql
58|58/13remove_presence_allow_inbound.sql
58|58/14events_instance_name.sql
58|58/15_catchup_destination_rooms.sql
58|58/15unread_count.sql
58|58/16populate_stats_process_rooms_fix.sql
58|58/17_catchup_last_successful.sql
58|58/18stream_positions.sql
58|58/19txn_id.sql
58|58/20instance_name_event_tables.sql
58|58/20user_daily_visits.sql
58|58/21as_device_stream.sql
58|58/21drop_device_max_stream_id.sql
58|58/22puppet_token.sql
58|58/22users_have_local_media.sql
58|58/23e2e_cross_signing_keys_idx.sql
58|58/24drop_event_json_index.sql
58|58/25user_external_ids_user_id_idx.sql
58|58/26access_token_last_validated.sql
58|58/27local_invites.sql
58|58/28drop_last_used_column.sql.sqlite
59|59/01ignored_user.py
59|59/02shard_send_to_device.sql
59|59/04_event_auth_chains.sql
59|59/04drop_account_data.sql
59|59/05cache_invalidation.sql
59|59/06chain_cover_index.sql
59|59/06shard_account_data.sql
59|59/07shard_account_data_fix.sql
59|59/08delete_pushers_for_deactivated_accounts.sql
59|59/08delete_stale_pushers.sql
59|59/09rejected_events_metadata.sql
59|59/10delete_purged_chain_cover.sql
59|59/12account_validity_token_used_ts_ms.sql
59|59/12presence_stream_instance.sql
59|59/13users_to_send_full_presence_to.sql
59|59/11add_knock_members_to_stats.sql
59|59/14refresh_tokens.sql
61|61/01insertion_event_lookups.sql
61|61/02drop_redundant_room_depth_index.sql
61|61/03recreate_min_depth.py
62|62/01insertion_event_extremities.sql
```

**Comment by babolivier** [comment]
Thanks. It looks like Synapse didn't correctly apply some of the database updates. Have you been running only stable versions of Synapse? Or e.g. the `develop` branch as well?

**Comment by babolivier** [comment]
Also, do you still have logs from upgrading from 1.37.0 (or older) to 1.37.1 (or later), or from Synapse's first start if you've set up your homeserver after 1.37.1 landed (June 30th)? If so, could you search for `16federation_inbound_staging.sql` in those logs please?

**Comment by Imaskiller** [comment]
ye i also used the develop branch - so it is probably because of that 

unfortunately i only keep logs for 3 days so I do not have them anymore
