### ISSUE TITLE
check_registration_for_spam() takes 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#10625]
The documentation for the module API claims this function takes 4 parameters in https://matrix-org.github.io/synapse/latest/modules.html#writing-a-module, however synapse passes 5 parameters to it in `register_user`. Perhaps there is a missing `self`?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 446, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.8/site-packages/synapse/rest/admin/users.py", line 468, in on_POST
    user_id = await register.registration_handler.register_user(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/register.py", line 220, in register_user
    result = await self.spam_checker.check_registration_for_spam(
  File "/usr/local/lib/python3.8/site-packages/synapse/events/spamcheck.py", line 371, in check_registration_for_spam
    callback(email_threepid, username, request_info, auth_provider_id)
TypeError: check_registration_for_spam() takes 4 positional arguments but 5 were given
```

**Comment by anoadragon453** [comment]
Which Synapse version are you running, out of interest?

**Comment by Half-Shot** [comment]
1.40

**Comment by babolivier** [comment]
Weird, I've just tried with this dummy module:

```python
class MySuperModule:
    def __init__(self, config: dict, api: ModuleApi):
        self.api = api

        self.api.register_spam_checker_callbacks(
            check_registration_for_spam=self.check_registration_for_spam,
        )

    async def check_registration_for_spam(self, email_threepid, username, request_info, auth_provider_id):
        return RegistrationBehaviour.ALLOW
```

And I was able to register a user just fine.

**Comment by babolivier** [comment]
We discussed this in DM, the bug was with the module.

**Comment by anoadragon453** [comment]
It sounds like a function was passed, rather than a method.

**Comment by babolivier** [comment]
fwiw note that passing a function that's not a method works just as well with the module interface, e.g.

```python
class MySuperModule:
    def __init__(self, config: dict, api: ModuleApi):
        self.api = api

        self.api.register_spam_checker_callbacks(
            check_registration_for_spam=check_registration_for_spam,
        )

async def check_registration_for_spam(email_threepid, username, request_info, auth_provider_id):
    return RegistrationBehaviour.DENY
```

works
