### ISSUE TITLE
Can't accept invite to a room on matrix.org from lant.uk

### ISSUE THREAD

**Issue by lampholder** [matrix-org/synapse#10656]
I can't accept an invite to join a room on matrix.org from lant.uk (running Synapse 1.39 - I'll update later and retry)
```
Aug 19 11:51:11 thor matrix-synapse[14411]: 2021-08-19 09:51:11,858 - synapse.federation.federation_client - 575 - WARNING - POST-2003290 - Failed to make_join via matrix.org
Aug 19 11:51:11 thor matrix-synapse[14411]: Traceback (most recent call last):
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 575, in _send_request
Aug 19 11:51:11 thor matrix-synapse[14411]:     response = await request_deferred
Aug 19 11:51:11 thor matrix-synapse[14411]: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
Aug 19 11:51:11 thor matrix-synapse[14411]: The above exception was the direct cause of the following exception:
Aug 19 11:51:11 thor matrix-synapse[14411]: Traceback (most recent call last):
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 545, in _try_destination_list
Aug 19 11:51:11 thor matrix-synapse[14411]:     return await callback(destination)
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 632, in send_request
Aug 19 11:51:11 thor matrix-synapse[14411]:     ret = await self.transport_layer.make_membership_event(
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 243, in make_membership_event
Aug 19 11:51:11 thor matrix-synapse[14411]:     content = await self.client.get_json(
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 1007, in get_json
Aug 19 11:51:11 thor matrix-synapse[14411]:     response = await self._send_request_with_optional_trailing_slash(
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 391, in _send_request_with_optional_trailing_slash
Aug 19 11:51:11 thor matrix-synapse[14411]:     response = await self._send_request(request, **send_request_args)
Aug 19 11:51:11 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 579, in _send_request
Aug 19 11:51:11 thor matrix-synapse[14411]:     raise RequestSendFailed(e, can_retry=True) from e
Aug 19 11:51:11 thor matrix-synapse[14411]: synapse.api.errors.RequestSendFailed: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
Aug 19 11:51:27 thor matrix-synapse[14411]: 2021-08-19 09:51:27,207 - synapse.handlers.device - 858 - WARNING - _maybe_retry_device_resync-27373 - Failed to handle device list update for @joosth:matrix.org: Failed to send request: HttpResponseException: 520: Origin Error
Aug 19 11:51:28 thor matrix-synapse[14411]: 2021-08-19 09:51:28,941 - synapse.federation.federation_client - 575 - WARNING - POST-2003415 - Failed to make_join via matrix.org
Aug 19 11:51:28 thor matrix-synapse[14411]: Traceback (most recent call last):
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
Aug 19 11:51:28 thor matrix-synapse[14411]:     result = current_context.run(gen.send, result)
Aug 19 11:51:28 thor matrix-synapse[14411]: StopIteration: DestinationRetryTimings(failure_ts=1629366687207, retry_last_ts=1629366687207, retry_interval=600000)
Aug 19 11:51:28 thor matrix-synapse[14411]: During handling of the above exception, another exception occurred:
Aug 19 11:51:28 thor matrix-synapse[14411]: Traceback (most recent call last):
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 545, in _try_destination_list
Aug 19 11:51:28 thor matrix-synapse[14411]:     return await callback(destination)
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 632, in send_request
Aug 19 11:51:28 thor matrix-synapse[14411]:     ret = await self.transport_layer.make_membership_event(
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 243, in make_membership_event
Aug 19 11:51:28 thor matrix-synapse[14411]:     content = await self.client.get_json(
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 1007, in get_json
Aug 19 11:51:28 thor matrix-synapse[14411]:     response = await self._send_request_with_optional_trailing_slash(
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 391, in _send_request_with_optional_trailing_slash
Aug 19 11:51:28 thor matrix-synapse[14411]:     response = await self._send_request(request, **send_request_args)
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 479, in _send_request
Aug 19 11:51:28 thor matrix-synapse[14411]:     limiter = await synapse.util.retryutils.get_retry_limiter(
Aug 19 11:51:28 thor matrix-synapse[14411]:   File "/usr/local/lib/python3.8/site-packages/synapse/util/retryutils.py", line 92, in get_retry_limiter
Aug 19 11:51:28 thor matrix-synapse[14411]:     raise NotRetryingDestination(
Aug 19 11:51:28 thor matrix-synapse[14411]: synapse.util.retryutils.NotRetryingDestination: Not retrying server matrix.org.
```

**Comment by erikjohnston** [comment]
This looks like matrix.org was down from the PoV of lant.uk, likely one of the federation readers was pinned at 100% CPU.
