### ISSUE TITLE
can't create rooms with with an alias when createRoom is on a worker

### ISSUE THREAD

**Issue by cremesk** [matrix-org/synapse#10716]
### Description

Hello,

i can not create new rooms with the new generic_worker location `^/_matrix/client/(api/v1|r0|unstable)/createRoom$`.

### Steps to reproduce

- add the new location to the reserve proxy config:  
https://git.envs.net/envs/matrix-conf/src/branch/master/etc/nginx/include.d/generic_worker.conf#L145-L149

### Version information

- **Homeserver**: envs.net
- **Version**: 1.41.0
- **Install method**: apt
- **Platform**: Debian 11 / VM

### Log:
```
2021-08-28 18:31:05,066 - synapse.http.server - 93 - ERROR - POST-192338 - Failed handle request via 'RoomCreateRestServlet': <XForwardedForRequest at 0x7f907639c550 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8513>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/http/server.py", line 446, in _async_render
    callback_return = await raw_callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/rest/client/room.py", line 84, in on_POST
    info, _ = await self._room_creation_handler.create_room(
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/room.py", line 726, in create_room
    await directory_handler.create_association(
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/directory.py", line 162, in create_association
    await self._create_association(room_alias, room_id, servers, creator=user_id)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/directory.py", line 88, in _create_association
    await self.store.create_room_alias_association(
AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'create_room_alias_association'
```

**Comment by clokep** [comment]
Seems this was added in #10564, I wonder if creating a room with an alias wasn't taken into account. (Does it work if you don't create an alias at the same time?)

**Comment by cremesk** [comment]
yes i had tried to create a public room.

**Comment by cremesk** [comment]
@clokep yes i works without an alias!

**Comment by clokep** [comment]
> @clokep yes i works without an alias!

Thanks! I guess the workaround for now is to still run that on the main process. 👍

**Comment by cremesk** [comment]
> > @clokep yes i works without an alias!
> 
> Thanks! I guess the workaround for now is to still run that on the main process. +1

yes, thank you! that's how I do it already. ;)

i just wanted to let you know the bug! Unfortunately, I lack the programming skills as Sysadmin to fix the problem with a PR.

**Comment by clokep** [comment]
> i just wanted to let you know the bug! Unfortunately, I lack the programming skills as Sysadmin to fix the problem with a PR.

Definitely, thank you for filing!
