### ISSUE TITLE
SSL error when trying to login

### ISSUE THREAD

**Issue by Sr-Preet** [matrix-org/synapse#10722]
![Screenshot (39)](https://user-images.githubusercontent.com/55445693/131481467-bb01479e-13ce-4ee3-84fd-dc7fb05af0b3.png)

I've checked the certificates even generated new ones.
Am I missing something?

**Comment by reivilibre** [comment]
It would be useful to have a few more lines of logs (and pasted as text in code blocks, please — not as images) to really see what's going on here.

It seems to me like this is Synapse making a HTTPS request to another server.

If this happens during login, is it possibly the case that you're using OpenID Connect login or something like that, where the OIDC server has an expired certificate?

**Comment by Sr-Preet** [comment]
@reivilibre Thanks for replying.

Here's the log data.

```
2021-09-01` 18:52:33,869 - synapse.http.site - 451 - WARNING - sentinel - forwarded request lacks an x-forwarded-proto header: assuming https
2021-09-01 18:52:33,908 - synapse.http.site - 451 - WARNING - sentinel - forwarded request lacks an x-forwarded-proto header: assuming https
2021-09-01 18:52:33,943 - synapse.http.client - 448 - INFO - POST-11 - Error sending request to  POST https://10.10.1.82:9443/cas/v1/tickets: RequestTransmissionFailed [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
2021-09-01 18:52:33,944 - synapse.http.server - 93 - ERROR - POST-11 - Failed handle request via 'CasCustomLoginServlet': <XForwardedForRequest at 0x7f5ced697040 method='POST' uri='/_matrix/client/r0/caslogin' clientproto='HTTP/1.0' site='8008'>
Traceback (most recent call last):
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/rest/client/v1/login.py", line 478, in on_POST
    body = await self._http_client.post_raw(uri, args)
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/client.py", line 490, in post_raw
    response = await self.request(
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/client.py", line 436, in request
    response = await make_deferred_yieldable(request_deferred)
twisted.web._newclient.RequestTransmissionFailed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/server.py", line 258, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/server.py", line 446, in _async_render
    callback_return = await raw_callback_return
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/rest/client/v1/login.py", line 480, in on_POST
    except PartialDownloadError as pde:
NameError: name 'PartialDownloadError' is not defined

```

Can you please look into it.

**Comment by reivilibre** [comment]
What version of Synapse are you using? I don't think this is v1.41 as the line in question ("/root/matrix-backend-repo/riot-matrix/synapse/synapse/rest/client/v1/login.py", line 480) does not exist.

In future, it would be useful if you could fill out the issue template since it asks for this information and would save having to go back and forth so much (as well as providing the full log excerpt since some of the crucial information was hidden before). Thanks!

**Comment by reivilibre** [comment]
As a note: I'm afraid it's very difficult to support old versions especially if they have been customised a lot. Indeed, there's no way for us to know whether this is an issue that your customisations have introduced (we would need the source code at minimum, but even then it's difficult to support — you would need to reproduce this issue and .

v1.41 does not make mention of `PartialDownloadError` in `login.py`, so you can already start to see how things diverge.

We have a module API nowadays which may be more suitable for making customisations (so long as you can fit them in to the structure of a module): https://matrix-org.github.io/synapse/latest/modules.html .

However, since you seem comfortable enough customising the code, it doesn't seem like it should be too difficult to resolve `NameError: name 'PartialDownloadError' is not defined`.

But the root cause seems to be that connecting to `https://10.10.1.82:9443/` is failing because of an untrusted TLS certificate.

Try `curl https://10.10.1.82:9443/` from the same machine as Synapse, you'll probably find that it also fails with a TLS error.
A likely issue is that you need to add your CA to Ubuntu's trust store.

Until the `curl` command above works, it seems like this is not a Synapse issue.

**Comment by Sr-Preet** [comment]
@reivilibre 
Thanks for being so helpful.
Yes did ran the curl command on my machine and I've got the following response

`root@SVM-REGALDEV-VM1:~# curl https://10.10.1.82:9443/
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.`

**Comment by Sr-Preet** [comment]
@reivilibre 
I've managed to resolve the issue. It was certificates related.
Thanks for you help and support you provided.
