### ISSUE TITLE
Export all data of a single user (GDPR Art. 15)

### ISSUE THREAD

**Issue by samuel-p** [matrix-org/synapse#10900]
**Description:**

To fulfil data requests according to Art 15 GDPR it would be good to have a function to export all data of a user. I think there are 2 possibilities here: Either an API endpoint or a custom script.

Beside that it would be great to know which data are relevant for this.

**Comment by erikjohnston** [comment]
I think `python -m synapse.app.admin_cmd -c <config_file> export-data <user_id>`  should do you want? We should probably document that somewhere if it isn't already....

**Comment by samuel-p** [comment]
I could not test this, because running this in my docker setup in the main Synapse container I get the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/synapse/app/admin_cmd.py", line 236, in <module>
    start(sys.argv[1:])
  File "/usr/local/lib/python3.8/site-packages/synapse/app/admin_cmd.py", line 190, in start
    and not config.worker_log_file
  File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 340, in __getattr__
    return self._get_unclassed_config(None, item)
  File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 363, in _get_unclassed_config
    raise AttributeError(item, "not found in %s" % (list(self._configs.keys()),))
AttributeError: ('worker_log_file', "not found in ['modules', 'server', 'tls', 'federation', 'caches', 'database', 'logging', 'ratelimiting', 'media', 'oembed', 'captcha', 'voip', 'registration', 'account_validity', 'metrics', 'api', 'appservice', 'key', 'saml2', 'oidc', 'cas', 'sso', 'jwt', 'auth', 'email', 'authproviders', 'push', 'spamchecker', 'room', 'groups', 'userdirectory', 'consent', 'stats', 'servernotices', 'roomdirectory', 'thirdpartyrules', 'tracing', 'worker', 'redis', 'experimental']")
```

Maybe I missed something to run this command or do I need to change something my config? I'm using the latest version of Synapse v1.43.0.

**Comment by erikjohnston** [comment]
Ah, looks like we've broken it and haven't noticed :(

**Comment by erikjohnston** [comment]
I'm going to close this in favour of #10908, as I think the admin command is exactly what you want.
