### ISSUE TITLE
Federation tester says okay but federation and mail sending fails - OpenSSL/TLS cert CA issue

### ISSUE THREAD

**Issue by vmario89** [matrix-org/synapse#10976]
Hi,
i have serious issue and i dont know how to fix. i invested a lot of time but get no clue about. 
https://federationtester.matrix.org/api/report?server_name=matrix.fablabchemnitz.de says our server is fine, but i cannot federate from external matrix servers.
the users on same instance can chat properly.
there is some problem with TLS/SSL and certificate but the cert is fine so far, i think. We use Lets Encrypt

i already posted at closed issue but i started this as a new one because i think its a different issue

related issues are:

- https://github.com/matrix-org/synapse/issues/6211
- https://github.com/matrix-org/synapse/issues/9599

postfix log:

- SSL3 alert read:fatal:unknown CA
- Okt 02 00:17:05 <redacted> postfix/smtpd[3054606]: SSL_accept:error in error
- Okt 02 00:17:05  <redacted> postfix/smtpd[3054606]: SSL_accept error from localhost[127.0.0.1]: -1
- Okt 02 00:17:05  <redacted> postfix/smtpd[3054606]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1543:SSL alert number 48:
- Okt 02 00:17:05  <redacted> postfix/smtpd[3054606]: lost connection after STARTTLS from localhost[127.0.0.1]
- 

the log /var/log/matrix-synapse/homeserver.log says issue about sending mails
```

2021-10-02 00:49:25,542 - twisted - 271 - INFO - sentinel - SMTP Client retrying server. Retry: 5
2021-10-02 00:49:25,562 - twisted - 271 - INFO - sentinel - SMTP Client retrying server. Retry: 4
2021-10-02 00:49:25,582 - twisted - 271 - INFO - sentinel - SMTP Client retrying server. Retry: 3
2021-10-02 00:49:25,593 - twisted - 271 - INFO - sentinel - SMTP Client retrying server. Retry: 2
2021-10-02 00:49:25,613 - twisted - 271 - INFO - sentinel - SMTP Client retrying server. Retry: 1
2021-10-02 00:49:25,733 - synapse.handlers.identity - 415 - ERROR - POST-145 - Error sending threepid validation email to <redacted>@<redacted>.de
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/identity.py", line 413, in send_threepid_validation
    await send_email_func(email_address, token, client_secret, session_id)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/push/mailer.py", line 201, in send_add_threepid_mail
    await self.send_email(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/push/mailer.py", line 318, in send_email
    await self.send_email_handler.send_email(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/send_email.py", line 175, in send_email
    await self._sendmail(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/send_email.py", line 111, in _sendmail
    await make_deferred_yieldable(d)
twisted.mail._except.SMTPConnectError: Unable to connect to server.
2021-10-02 00:49:25,734 - synapse.http.server - 88 - INFO - POST-145 - <XForwardedForRequest at 0x7fb2743e2130 method='POST' uri='/_matrix/client/r0/account/3pid/email/requestToken' clientproto='HTTP/1.0' site='8008'> SynapseError: 500 - An error was encountered when sending the email
```

and it also says about external room joins:

```
2021-10-02 11:15:18,162 - synapse.crypto.keyring - 633 - INFO - PerspectivesKeyFetcher-24 - Requesting keys [_FetchKeyRequest(server_name='matrix.org', minimum_valid_until_ts=1633166118161, key_ids=['ed25519:a_RXGa'])] from notary server matrix.org
2021-10-02 11:15:18,162 - synapse.crypto.keyring - 588 - WARNING - PerspectivesKeyFetcher-24 - Key lookup failed from 'matrix.org': Not retrying server matrix.org.
2021-10-02 11:15:18,193 - synapse.http.matrixfederationclient - 635 - INFO - ServerKeyFetcher-24 - {GET-O-54} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/key/v2/server/ed25519%3Aa_RXGa: ResponseNeverReceived:[Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])]
2021-10-02 11:15:18,193 - synapse.crypto.keyring - 786 - WARNING - ServerKeyFetcher-24 - Error looking up keys ['ed25519:a_RXGa'] from matrix.org: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
2021-10-02 11:15:18,193 - synapse.federation.transport.server._base - 267 - WARNING - GET-1222 - authenticate_request failed: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='matrix.org', minimum_valid_until_ts=1633166118161, key_ids=['ed25519:a_RXGa'])
2021-10-02 11:15:18,193 - synapse.http.server - 88 - INFO - GET-1222 - <XForwardedForRequest at 0x7f5db0102b50 method='GET' uri='/_matrix/federation/v1/query/profile?user_id=%40vmario89%3Amatrix.fablabchemnitz.de&field=displayname' clientproto='HTTP/1.1' site='8448'> SynapseError: 401 - Failed to find any key to satisfy: _FetchKeyRequest(server_name='matrix.org', minimum_valid_until_ts=1633166118161, key_ids=['ed25519:a_RXGa'])
2021-10-02 11:15:18,194 - synapse.access.https.8448 - 389 - INFO - GET-1222 - 176.126.240.158 - 8448 - {None} Processed request: 0.033sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 182B 401 "GET /_matrix/federation/v1/query/profile?user_id=%40vmario89%3Amatrix.fablabchemnitz.de&field=displayname HTTP/1.1" "Synapse/1.44.0rc1 (b=matrix-org-hotfixes,4cb6ffdf4)" [0 dbevts]
2021-10-02 11:15:18,374 - synapse.crypto.keyring - 633 - INFO - PerspectivesKeyFetcher-25 - Requesting keys [_FetchKeyRequest(server_name='matrix.org', minimum_valid_until_ts=1633166118373, key_ids=['ed25519:a_RXGa'])] from notary server matrix.org
2021-10-02 11:15:18,374 - synapse.crypto.keyring - 588 - WARNING - PerspectivesKeyFetcher-25 - Key lookup failed from 'matrix.org': Not retrying server matrix.org.
2021-10-02 11:15:18,398 - synapse.http.matrixfederationclient - 635 - INFO - ServerKeyFetcher-25 - {GET-O-56} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/key/v2/server/ed25519%3Aa_RXGa: ResponseNeverReceived:[Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])]
2021-10-02 11:15:18,398 - synapse.crypto.keyring - 786 - WARNING - ServerKeyFetcher-25 - Error looking up keys ['ed25519:a_RXGa'] from matrix.org: Failed to send request: ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]>]
2021-10-02 11:15:18,398 - synapse.federation.transport.server._base - 267 - WARNING - PUT-1223 - authenticate_request failed: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='matrix.org', minimum_valid_until_ts=1633166118373, key_ids=['ed25519:a_RXGa'])
```

i checked CA cert which is fine. All things with mail clients work properly, like thunderbird or roundcube or other services which connect to the mail server from exernal or localhost

my mail server only supports TLS 1.2 and TLS 1.3. SSLv2/v3 is completely disabled for smtp/smtpd. I already tried to tie down to TLS 1.0

i updated twisted[tls] und removed the older apt package too python3-twisted

also tried synapse connecting to mail server locally or by public mail server address

some infos about versions:

- ii openssl 1.1.1f-1ubuntu2.8 amd64 Secure Sockets Layer toolkit - cryptographic utility
- ii postfix 3.4.13-0ubuntu1.2 amd64 High-performance mail transport agent
- ii matrix-synapse-py3 1.43.0+focal1 amd64 Open federated Instant Messaging and VoIP server
- twisted 21.7.0
- recent version of 21.5.0

some more stuff i tried which also looks good, but without solving or modifying the problem:

```
update-ca-certificates

openssl verify -CAfile /etc/ssl/certs/ISRG_Root_X1.pem /etc/letsencrypt/live/mymailserver.de/chain.pem

openssl s_client -showcerts -servername mail.mymailserver.org -connect smtp.mymailserver.org:587
openssl s_client -starttls smtp -showcerts -servername mymailserver.org -connect smtp.mymailserver.org:587
openssl s_client -CApath /etc/ssl/certs -CAfile /etc/ssl/certs/ca-certificates.crt -starttls smtp -showcerts -servername mail.mymailserver.org -connect smtp.mymailserver.org:587
openssl s_client -CAfile /etc/ssl/certs/ca-certificates.crt -starttls smtp -showcerts -servername mail.mymailserver.org -connect mail.mymailserver.org:25

apt remove python3-openssl
apt remove python3-twisted
pip3 install --upgrade twisted[tls]
pip3 install --upgrade treq
pip3 install --upgrade cryptography
pip3 install --upgrade secretstorage
pip3 install --upgrade pyOpenSSL

```
```
openssl s_client -connect matrix.fablabchemnitz.de:443

```
gives "Verify return code: 2 (unable to get issuer certificate)"

**Comment by davehayes** [comment]
Does this possibly have to do with the Let's Encrypt root certificate expiring?

**Comment by vmario89** [comment]
Hi. Maybe. Letsencrypt has new root cert ISRG root X1. It expired at 30.09. But i already renewed all certs and restarted all services/services mulitple times.

**Comment by babolivier** [comment]
This sounds like there's an issue with your setup rather than a bug in Synapse. We only use GitHub issues for bug reports, not for support requests. For support requests, please use the room `#synapse:matrix.org` on Matrix.

**Comment by hasanihunter** [comment]
> This sounds like there's an issue with your setup rather than a bug in Synapse. We only use GitHub issues for bug reports, not for support requests. For support requests, please use the room `#synapse:matrix.org` on Matrix.

I'm having the same issue as the OP, but I cannot join the #synapse:matrix.org room because my homeserver cannot connect to matrix.org (because of the expired root cert)

**Comment by vmario89** [comment]
finally the fix was to run
`openssl s_client -connect matrix.org:443 -showcerts -verify_return_error`

that returned "verify error:num=2:unable to get issuer certificate"

i removed an old cert file from /etc/ssl/certs and it immediately started to work again
