### ISSUE TITLE
Failed to send_join via any server due to "Object of type Decimal is not JSON serializable"

### ISSUE THREAD

**Issue by nightred** [matrix-org/synapse#11135]
### Description
 When trying to join the channel #nextcloud:matrix.org an error is shown that reads 'Failed to send_join via matrix.org'
The issue persists on every join attempt.

### Steps to reproduce

Join the channel #nextcloud:matrix.org
Review Logs and get the following error.
```
2021-10-20 09:17:35,911 - synapse.federation.federation_client - 616 - WARNING - POST-61221 - Failed to send_join via matrix.org

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)

ation: {'ed25519:auto': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x151c2e943f70>, valid_until_ts=1576767829750), 'ed25519:a_RXGa': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x151be8e8f790>, valid_until_ts=1634773315345)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 576, in _try_destination_list
return await callback(destination)
File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 825, in send_request
await concurrently_execute(
File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
result = current_context.run(gen.send, result)
File "/usr/local/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 192, in _concurrently_execute_inner
await maybe_awaitable(func(value))
File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 815, in _execute
valid_pdu = await self._check_sigs_and_hash_and_fetch_one(
File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 458, in _check_sigs_and_hash_and_fetch_one
res = await self._check_sigs_and_hash(room_version, pdu)
File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_base.py", line 65, in _check_sigs_and_hash
if not check_event_content_hash(pdu):
File "/usr/local/lib/python3.8/site-packages/synapse/crypto/event_signing.py", line 42, in check_event_content_hash
name, expected_hash = compute_content_hash(event.get_pdu_json(), hash_algorithm)
File "/usr/local/lib/python3.8/site-packages/synapse/crypto/event_signing.py", line 96, in compute_content_hash
event_json_bytes = encode_canonical_json(event_dict)
File "/usr/local/lib/python3.8/site-packages/canonicaljson.py", line 73, in encode_canonical_json
s = _canonical_encoder.encode(json_object)
File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/local/lib/python3.8/site-packages/canonicaljson.py", line 30, in _default
raise TypeError(
TypeError: Object of type Decimal is not JSON serializable
2021-10-20 09:17:35,911 - synapse.http.server - 88 - INFO - POST-61221 - <XForwardedForRequest at 0x151c15df5370 method='POST' uri='/_matrix/client/r0/join/!TEwfEWdDwdaFazXmwD%3Amatrix.org?server_name=matrix.org' clientproto='HTTP/1.1' site='8008'> SynapseError: 502 - Failed to send_join via any server
```
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.jenovarain.com

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.45.0","python_version":"3.8.12"}

- **Install method**: Docker
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Docker
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by squahtx** [comment]
The good news is that the hashes for both the above events match, as long as the trailing `.0`s are included

**Comment by BBaoVanC** [comment]
Weird, I don't have this issue on v1.45.1 in Docker, and my server hasn't joined the room before.

**Comment by squahtx** [comment]
> Weird, I don't have this issue on v1.45.1 in Docker, and my server hasn't joined the room before.

Room names are case sensitive. It's `#NextCloud:matrix.org` that's broken, not `#nextcloud:matrix.org`.

**Comment by BBaoVanC** [comment]
> > Weird, I don't have this issue on v1.45.1 in Docker, and my server hasn't joined the room before.
> 
> Room aliases are case sensitive. It's `#NextCloud:matrix.org` that's broken, not `#nextcloud:matrix.org`.

Oh, I misread it then. I'll test it when I get home
