### ISSUE TITLE
OSError Read-only file system: `/etc/synapse/homeserver.log' after upgrading to 1.44.0

### ISSUE THREAD

**Issue by MarcelRobitaille** [matrix-org/synapse#11141]
### Description

After upgrading from 1.41.1 to 1.44.0, I got `OSError: [Errno 30] Read-only file system: '/etc/synapse/homeserver.log'` even though that file is owned by `synapse` and has 644 permissions. I confirmed that I could open the file from Python with:
```
sudo -u synapse python
Python 3.9.7 (default, Oct 10 2021, 15:13:22)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('/etc/synapse/homeserver.log')
<_io.TextIOWrapper name='/etc/synapse/homeserver.log' mode='r' encoding='UTF-8'>
```

I downgraded to 1.41.1 (latest working version in pacman cache) and everything is working again.

Full error message:
```
Oct 20 23:59:48 systemd[1]: Starting Synapse Matrix homeserver (master)...
Oct 20 23:59:52 synapse[34628]: Traceback (most recent call last):
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/config.py", line 564, in configure
Oct 20 23:59:52 synapse[34628]:     handler = self.configure_handler(handlers[name])
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/config.py", line 745, in configure_handler
Oct 20 23:59:52 synapse[34628]:     result = factory(**kwargs)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/handlers.py", line 208, in __init__
Oct 20 23:59:52 synapse[34628]:     BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/handlers.py", line 58, in __init__
Oct 20 23:59:52 synapse[34628]:     logging.FileHandler.__init__(self, filename, mode=mode,
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/__init__.py", line 1146, in __init__
Oct 20 23:59:52 synapse[34628]:     StreamHandler.__init__(self, self._open())
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/__init__.py", line 1175, in _open
Oct 20 23:59:52 synapse[34628]:     return open(self.baseFilename, self.mode, encoding=self.encoding,
Oct 20 23:59:52 synapse[34628]: OSError: [Errno 30] Read-only file system: '/etc/synapse/homeserver.log'
Oct 20 23:59:52 synapse[34628]: The above exception was the direct cause of the following exception:
Oct 20 23:59:52 synapse[34628]: Traceback (most recent call last):
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Oct 20 23:59:52 synapse[34628]:     return _run_code(code, main_globals, None,
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
Oct 20 23:59:52 synapse[34628]:     exec(code, run_globals)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/app/homeserver.py", line 465, in <module>
Oct 20 23:59:52 synapse[34628]:     main()
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/app/homeserver.py", line 455, in main
Oct 20 23:59:52 synapse[34628]:     hs = setup(sys.argv[1:])
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/app/homeserver.py", line 358, in setup
Oct 20 23:59:52 synapse[34628]:     synapse.config.logger.setup_logging(hs, config, use_worker_options=False)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/config/logger.py", line 331, in setup_logging
Oct 20 23:59:52 synapse[34628]:     _setup_stdlib_logging(config, log_config_path, logBeginner=logBeginner)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/config/logger.py", line 217, in _setup_stdlib_logging
Oct 20 23:59:52 synapse[34628]:     _load_logging_config(log_config_path)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/site-packages/synapse/config/logger.py", line 293, in _load_logging_config
Oct 20 23:59:52 synapse[34628]:     logging.config.dictConfig(log_config)
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/config.py", line 809, in dictConfig
Oct 20 23:59:52 synapse[34628]:     dictConfigClass(config).configure()
Oct 20 23:59:52 synapse[34628]:   File "/usr/lib/python3.9/logging/config.py", line 571, in configure
Oct 20 23:59:52 synapse[34628]:     raise ValueError('Unable to configure handler '
Oct 20 23:59:52 synapse[34628]: ValueError: Unable to configure handler 'file'
Oct 20 23:59:52 systemd[1]: synapse.service: Main process exited, code=exited, status=1/FAILURE
```

### Steps to reproduce

- Upgrade to 1.44.0
- Restart synapse

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org: my homeserver

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.44.0-2

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
```
pacman -S matrix-synapse
```

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Arch linux on x86 from pacman package

**Comment by MarcelRobitaille** [comment]
I am an idiot. I did not consider that the default mode for open would be read.

I get the same thing opening with append or write:
```
sudo -u synapse python
Python 3.9.7 (default, Oct 10 2021, 15:13:22)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> open('/etc/synapse/homeserver.log', 'a')
<_io.TextIOWrapper name='/etc/synapse/homeserver.log' mode='a' encoding='UTF-8'>
```

I am getting new messages in `homeserver.log` on 1.41.1.

**Comment by squahtx** [comment]
I did some digging and it seems like sandboxing was added in a recent release of `matrix-synapse` on Arch:
https://github.com/archlinux/svntogit-community/commit/a2221c8b1b54f3f971dee694bc59a5d93ec211e5

Going off the comments there, `/etc` is read-only from the perspective of Synapse.
`/var/log/synapse` seems to be the log directory they're encouraging admins to use.
