### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by chagai95** [matrix-org/synapse#11464]
### Description
Exception:

```

Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: 2021-11-30 15:25:05,626 - synapse.http.server - 93 - ERROR - PUT-652 - Failed handle request via 'AccountDataServlet': <XForwardedForRequest at 0x7f528e9548e0 method='PUT' uri='/_matrix/client/r0/user/%40me%3Achagai.website/account_data/im.vector.web.settings' clientproto='HTTP/1.0' site='8008'>
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: Traceback (most recent call last):
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: callback_return = await self._async_render(request)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 446, in _async_render
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: callback_return = await raw_callback_return
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/account_data.py", line 57, in on_PUT
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: await self.handler.add_account_data_for_user(user_id, account_data_type, body)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/handlers/account_data.py", line 92, in add_account_data_for_user
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: max_stream_id = await self._store.add_account_data_for_user(
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/account_data.py", line 433, in add_account_data_for_user
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: await self.db_pool.runInteraction(
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 686, in runInteraction
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: result = await self.runWithConnection(
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 791, in runWithConnection
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: return await make_deferred_yieldable(
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: result = inContext.theWork()  # type: ignore[attr-defined]
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: return func(*args, **kw)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: compat.reraise(excValue, excTraceback)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: return function(*args, **kwargs)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: raise exception.with_traceback(traceback)
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
Nov 30 16:25:07 localhost.localdomain matrix-synapse[8853]: result = func(conn, *args, **kw)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 786, in inner_func
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return func(db_conn, *args, **kwargs)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 554, in new_transaction
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: r = func(cursor, *args, **kwargs)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/account_data.py", line 463, in _add_account_data_for_user
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: self.db_pool.simple_upsert_txn(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1033, in simple_upsert_txn
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return self.simple_upsert_txn_native_upsert(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1159, in simple_upsert_txn_native_upsert
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: txn.execute(sql, list(allvalues.values()))
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 298, in execute
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: self._do_execute(self.txn.execute, sql, *args)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 331, in _do_execute
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return func(sql, *args)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: 2021-11-30 15:25:07,984 - synapse.http.server - 93 - ERROR - PUT-653 - Failed handle request via 'AccountDataServlet': <XForwardedForRequest at 0x7f528e956c40 method='PUT' uri='/_matrix/client/r0/user/%40me%3Achagai.website/account_data/im.vector.web.settings' clientproto='HTTP/1.0' site='8008'>
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: Traceback (most recent call last):
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 258, in _async_render_wrapper
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: callback_return = await self._async_render(request)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 446, in _async_render
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: callback_return = await raw_callback_return
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/account_data.py", line 57, in on_PUT
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: await self.handler.add_account_data_for_user(user_id, account_data_type, body)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/handlers/account_data.py", line 92, in add_account_data_for_user
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: max_stream_id = await self._store.add_account_data_for_user(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/account_data.py", line 433, in add_account_data_for_user
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: await self.db_pool.runInteraction(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 686, in runInteraction
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: result = await self.runWithConnection(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 791, in runWithConnection
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return await make_deferred_yieldable(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: result = inContext.theWork()  # type: ignore[attr-defined]
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return func(*args, **kw)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 293, in _runWithConnection
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: compat.reraise(excValue, excTraceback)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/deprecate.py", line 298, in deprecatedFunction
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return function(*args, **kwargs)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 404, in reraise
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: raise exception.with_traceback(traceback)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 284, in _runWithConnection
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: result = func(conn, *args, **kw)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 786, in inner_func
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return func(db_conn, *args, **kwargs)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 554, in new_transaction
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: r = func(cursor, *args, **kwargs)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/account_data.py", line 463, in _add_account_data_for_user
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: self.db_pool.simple_upsert_txn(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1033, in simple_upsert_txn
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return self.simple_upsert_txn_native_upsert(
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 1159, in simple_upsert_txn_native_upsert
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: txn.execute(sql, list(allvalues.values()))
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 298, in execute
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: self._do_execute(self.txn.execute, sql, *args)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 331, in _do_execute
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: return func(sql, *args)
Nov 30 16:25:08 localhost.localdomain matrix-synapse[8853]: psycopg2.errors.SerializationFailure: could not serialize access due to concurrent update
```

### Steps to reproduce

- no idea

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:
chagai.website

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
{"server_version":"1.45.1","python_version":"3.8.12"}
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
Ansible playbook - official docker image
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
centOS

**Comment by squahtx** [comment]
A SerializationFailure here should imply that two `add_account_data_for_user` calls for the same user and `account_data_type` raced, and one succeeded. ie. some data was saved and the outcome was as if the successful call was run last.

Transactions are supposed to be retried up to 5 times in the event of a SerializationFailure, so it's a bit suspicious this is happening, considering that the transaction is a single upsert.

There are errors with the same stack trace on matrix.org, https://sentry.matrix.org/sentry/synapse-matrixorg/issues/227973/ ,
where `account_data_type` is mostly `im.vector.web.settings`
