### ISSUE TITLE
OpenID S-S API crashes when trying to verify a token

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#11814]
### Description

OpenID token verification fails with workers enabled. (Discovered using FOSDEM jitsi in the test session)

```
AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'get_user_id_for_open_id_token'
2022-01-24 19:09:56,077 - synapse.federation.federation_server - 1340 - WARNING - POST-26380 - No handler registered for query type client_keys
2022-01-24 19:10:00,026 - synapse.http.server - 100 - ERROR - GET-21972 - Failed handle request via 'OpenIdUserInfo': <SynapseRequest at 0x7f5a5c2003a0 method='GET' uri='/_matrix/federation/v1/openid/userinfo?access_token=<redacted>' clientproto='HTTP/1.1' site='2123'>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 269, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/lib/python3.9/site-packages/synapse/http/server.py", line 471, in _async_render
    callback_return = await raw_callback_return
  File "/usr/lib/python3.9/site-packages/synapse/federation/transport/server/_base.py", line 306, in new_func
    response = await func(
  File "/usr/lib/python3.9/site-packages/synapse/federation/transport/server/__init__.py", line 275, in on_GET
    user_id = await self.handler.on_openid_userinfo(token)
  File "/usr/lib/python3.9/site-packages/synapse/federation/federation_server.py", line 943, in on_openid_userinfo
    return await self.store.get_user_id_for_open_id_token(token, ts_now_ms)
AttributeError: 'GenericWorkerSlavedStore' object has no attribute 'get_user_id_for_open_id_token'
```

### Steps to reproduce

- Enable workers
- Get a clientside openid token
- Try to verify it on the S-S API
- Above error is happening.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: nordgedanken.dev

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.51.0rc2","python_version":"3.9.9"}

- **Install method**: Gentoo packages (Basically install from source using the tags.)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Gentoo, Baremetal on a Hetzner server running on zfs.
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by MTRNord** [comment]
Possibly relevant information: To the account in question a SSO login was added after creation. So this has both SSO and password login.

**Comment by MTRNord** [comment]
This was caused by a misconfigured reverse-proxy. I used a catch-all regex by accident. After fixing the config it works.

**Comment by squahtx** [comment]
I'm going to keep the issue open since @clokep says we ought to either support this endpoint on workers, or 400.

We probably won't get around to fixing this before FOSDEM since it arises from a config issue.

**Comment by clokep** [comment]
> I'm going to keep the issue open since @clokep says we ought to either support this endpoint on workers, or 400.

Pretty much -- it is weird that the worker even responds to this if it isn't supported!
