### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'edu_type'

### ISSUE THREAD

**Issue by frlan** [matrix-org/synapse#11924]
### Description

I think it's related to federation between two 1.51.0 servers:

I'm getting

```
synapse.federation.transport.server.federation: [PUT-35751] 'dict' object has no attribute 'edu_type'
Traceback (most recent call last):
File "/nix/store/xld8k8dik34zamx3f66biz13gqbz8ccw-python3-3.9.6-env/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
  result = current_context.run(gen.send, result)
StopIteration: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/nix/store/xld8k8dik34zamx3f66biz13gqbz8ccw-python3-3.9.6-env/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
  result = current_context.run(gen.send, result)
StopIteration: {'ed25519:a_xQGB': FetchKeyResult(verify_key=<nacl.signing.VerifyKey object at 0x7f5ba059d460>, valid_until_ts=1644247789683)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/nix/store/si27f6ipgvymxxkxmw117d4nnp603fvv-matrix-synapse-1.51.0/lib/python3.9/site-packages/synapse/federation/transport/server/federation.py", line 101, in on_PUT
  device_list_updates = [
File "/nix/store/si27f6ipgvymxxkxmw117d4nnp603fvv-matrix-synapse-1.51.0/lib/python3.9/site-packages/synapse/federation/transport/server/federation.py", line 104, in <listcomp>
  if edu.edu_type in DEVICE_UPDATE_EDUS
AttributeError: 'dict' object has no attribute 'edu_type'
```

On the sending server I see: 

```
synapse.federation.sender.transaction_manager: [federation_transaction_transmission_loop-12069] TX [xxxxx] {1643929599955} got 400 response
synapse.http.matrixfederationclient: [federation_transaction_transmission_loop-12069] {PUT-O-12769} [xxxxx] Request failed: PUT matrix://xxxxx/_matrix/federation/v1/send/1643929599955: HttpResponseException('400: Bad Request')
synapse.http.matrixfederationclient: [federation_transaction_transmission_loop-12069] {PUT-O-12769} [xxxxx] Got response headers: 400 Bad Request```
```

### Steps to reproduce

Unfortuantely I wasn't able to figure these out so far

### Version information

- **Version**:
On both  systems:

{"server_version":"1.51.0","python_version":"3.9.6"}

- **Install method**:

via NixOS package

- **Platform**:

NixOS 21.11 based

**Comment by frlan** [comment]
Might related to https://github.com/matrix-org/synapse/commit/dd7f825118f1b8f2789eee9498912ce362a79224 -- currently checking

**Comment by frlan** [comment]
Verified. Turn Log level DEBUG -> INFO seems to have worked here

**Comment by DMRobertson** [comment]
For cross-referencing: #11890 #11889
