### ISSUE TITLE
Getting this invalid_claim: Invalid claim "iss" when integrating hydra OIDC

### ISSUE THREAD

**Issue by bilalsha** [matrix-org/synapse#12075]
I am getting ` invalid_claim: Invalid claim "iss"` when synapse is decoding jwt. Its a valid thing why its giving issue?

```
2022-02-24 14:58:50,661 - synapse.handlers.oidc - 715 - DEBUG - GET-8 - Decoded id_token JWT {'acr': '0', 'at_hash': 'guTsya3DbKuZ7PR56rbnjA', 'aud': ['asaasss'], 'auth_time': 1645714723, 'exp': 1645718330, 'iat': 1645714730, 'iss': 'https://aaaa/', 'jti': '8669bd5d-eb5d-4f60-acb1-3c9a1eda3850', 'nonce': 'wf9Iyq9rvGu3GmJdU7YbwKXVFZOCrs', 'rat': 1645714713, 'sid': '4c797df2-f19f-4309-a245-f3a31688c9b6', 'sub': 'foo@bar.com'}; validating
2022-02-24 14:58:50,662 - synapse.handlers.oidc - 842 - ERROR - GET-8 - Invalid id_token
Traceback (most recent call last):
  File "/home/ubuntu/synapse/env/lib/python3.8/site-packages/synapse/handlers/oidc.py", line 839, in handle_oidc_callback
    id_token = await self._parse_id_token(token, nonce=session_data.nonce)
  File "/home/ubuntu/synapse/env/lib/python3.8/site-packages/synapse/handlers/oidc.py", line 717, in _parse_id_token
    claims.validate(leeway=120)  # allows 2 min of clock skew
  File "/home/ubuntu/synapse/env/lib/python3.8/site-packages/authlib/oidc/core/claims.py", line 35, in validate
    self.validate_iss()
  File "/home/ubuntu/synapse/env/lib/python3.8/site-packages/authlib/jose/rfc7519/claims.py", line 109, in validate_iss
    self._validate_claim_value('iss')
  File "/home/ubuntu/synapse/env/lib/python3.8/site-packages/authlib/jose/rfc7519/claims.py", line 71, in _validate_claim_value
    raise InvalidClaimError(claim_name)
authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"
```

**Comment by bilalsha** [comment]
I missed `/` in homerserver.yml  issuer config. Its fixed and working

**Comment by aceArt-GmbH** [comment]
we had a trailing `/` in keycloak issuer url
