### ISSUE TITLE
keycloak OIDC trying to connect to invalid address

### ISSUE THREAD

**Issue by lgwapnitsky** [matrix-org/synapse#12226]
Wondering if this is a bug or not, but I've configured OIDC to use keycloak. My configuration looks solid, but the server fails to start. The error seems to be with this:

```
2022-03-15 09:25:44,106 - synapse.http.client - 446 - INFO - sentinel - Received response to GET https://auth.mydomain.com/realms/master/.well-known/openid-configuration: 200
2022-03-15 09:25:44,410 - synapse.http.client - 455 - INFO - sentinel - Error sending request to  GET https://0.0.0.0/realms/master/protocol/openid-connect/certs: ConnectionRefusedErro
r Connection refused
2022-03-15 09:25:44,410 - synapse.app._base - 242 - CRITICAL - sentinel - Error during startup
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/oidc.py", line 121, in load_metadata
    await p.load_jwks()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/oidc.py", line 499, in load_jwks
    return await self._jwks.get()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/caches/cached_call.py", line 136, in get
    return await self._cachedcall.get()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/caches/cached_call.py", line 106, in get
    self._result.raiseException()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/failure.py", line 475, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1657, in _inlineCallbacks
    result = current_context.run(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/caches/cached_call.py", line 126, in _wrapper
    return await f()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/oidc.py", line 511, in _load_jwks
    jwk_set = await self._http_client.get_json(uri)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/client.py", line 591, in get_json
    body = await self.get_raw(uri, args, headers=actual_headers)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/client.py", line 676, in get_raw
    response = await self.request("GET", uri, headers=Headers(actual_headers))
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/client.py", line 443, in request
    response = await make_deferred_yieldable(request_deferred)
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

Why is synapse attempting to connect to 0.0.0.0 when it's not defined anywhere?

**Comment by DMRobertson** [comment]
Can you double check the config for keycloak? Is there anywhere that 0.0.0.0 is in that file by accident?

**Comment by DMRobertson** [comment]
I'd also double-check
- what `auth.mydomain.com` resolves to
- what the response to `https://auth.mydomain.com/realms/master/.well-known/openid-configuration` is --- perhaps that contains `0.0.0.0`?

**Comment by lgwapnitsky** [comment]
my keycloak config (and I also changed realms for testing):

```
oidc_providers:
  - idp_id: keycloak
    idp_name: "Keycloak"
    issuer: "https://auth.mydomain.com/realms/myrealm"
    client_id: "synapse"
    client_secret: "B0mqv8ED0dCxRcSwn0JGvcJtEdsKevvm"
    scopes: ["openid", "profile"]
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username }}"
        display_name_template: "{{ user.name }}"
    allow_existing_users: true

```

and my openid-configuration response:

```
{"issuer":"https://auth.mydomain.com/realms/myrealm","authorization_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/auth","token_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/token","introspection_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/userinfo","end_session_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/logout","frontchannel_logout_session_supported":true,"frontchannel_logout_supported":true,"jwks_uri":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/certs","check_session_iframe":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials","urn:ietf:params:oauth:grant-type:device_code","urn:openid:params:grant-type:ciba"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"id_token_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"id_token_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"userinfo_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"],"request_object_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"request_object_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"response_modes_supported":["query","fragment","form_post","query.jwt","fragment.jwt","form_post.jwt","jwt"],"registration_endpoint":"https://auth.mydomain.com/realms/myrealm/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"token_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"introspection_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"introspection_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"authorization_encryption_alg_values_supported":["RSA-OAEP","RSA-OAEP-256","RSA1_5"],"authorization_encryption_enc_values_supported":["A256GCM","A192GCM","A128GCM","A128CBC-HS256","A192CBC-HS384","A256CBC-HS512"],"claims_supported":["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"],"claim_types_supported":["normal"],"claims_parameter_supported":true,"scopes_supported":["openid","phone","offline_access","microprofile-jwt","web-origins","email","roles","address","profile"],"request_parameter_supported":true,"request_uri_parameter_supported":true,"require_request_uri_registration":true,"code_challenge_methods_supported":["plain","S256"],"tls_client_certificate_bound_access_tokens":true,"revocation_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/revoke","revocation_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"],"revocation_endpoint_auth_signing_alg_values_supported":["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"],"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"device_authorization_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/auth/device","backchannel_token_delivery_modes_supported":["poll","ping"],"backchannel_authentication_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/ext/ciba/auth","backchannel_authentication_request_signing_alg_values_supported":["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512"],"require_pushed_authorization_requests":false,"pushed_authorization_request_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/ext/par/request","mtls_endpoint_aliases":{"token_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/token","revocation_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/revoke","introspection_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/token/introspect","device_authorization_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/auth/device","registration_endpoint":"https://auth.mydomain.com/realms/myrealm/clients-registrations/openid-connect","userinfo_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/userinfo","pushed_authorization_request_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/ext/par/request","backchannel_authentication_endpoint":"https://auth.mydomain.com/realms/myrealm/protocol/openid-connect/ext/ciba/auth"}}
```

**Comment by lgwapnitsky** [comment]
running a 'dig' on the fqdn gives me the proper address

**Comment by lgwapnitsky** [comment]
all my other apps work fine

**Comment by DMRobertson** [comment]
Not sure what to suggest. Which version of Synapse are you running and how is it installed? If you've installed via `pip`, what version of authlib are you using? (`pip show authlib`)

**Comment by lgwapnitsky** [comment]
clean install, same issue. created homeserver.yaml and other config files from scratch, new database, etc.

used debian installation on ubuntu - both 20.04 and 21.10 instances, neither worked

python3-oauthlib is installed on both. Synapse works without the keycloak oicd config on both

**Comment by lgwapnitsky** [comment]
well, this is interesting...

```
root@matrix:/opt/venvs/matrix-synapse# source bin/activate
(matrix-synapse) root@matrix:/opt/venvs/matrix-synapse# pip show authlib
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

this is in the folder created by the debian/ubuntu install...

**Comment by lgwapnitsky** [comment]
temporary workaround - disabled discovery, manually put in jwks, token, and auth endpoints, and it's working. This shouldn't be, as my oidc xml returns the proper info...

**Comment by lgwapnitsky** [comment]
ok.  it started, but not working properly, yet

**Comment by DMRobertson** [comment]
Can you try turning on debug logging to see if that provides any clues? In your [logging configuration](https://matrix-org.github.io/synapse/latest/usage/configuration/logging_sample_config.html), set the `root` to level `DEBUG` rather than the default `INFO`.

From looking at the source code (assuming you're running the latest release _of Synapse_, i.e. 1.54), I can't see any reason why `0.0.0.0` would crop up. You could try looking out for a single `0` in the config (which is `0.0.0.0` expressed as an integer). It's also worth a check that the yaml indentation and key names are all correct.

> ok. it started, but not working properly, yet

Otherwise, I don't think I'll be able to help much more without a way to reproduce this, or more information about how things aren't working properly.

**Comment by lgwapnitsky** [comment]
Will do. Right now it's working with manual entries rather than discovery.
Keycloak provides the proper information in its initial response, but
somehow it's not using that information. I will disable it later and try to
provide

**Comment by squahtx** [comment]
Thank you for filing an issue. Unfortunately we haven't got enough information to reproduce the problem or diagnose the issue. If you have additional info to provide, please add a comment and reopen the issue.
