### ISSUE TITLE
porting sqlite to postgres

### ISSUE THREAD

**Issue by jon-bit** [matrix-org/synapse#12299]
I don't know if this is a buf but I was migrating fro sqlite to postgres. 
I ran `sudo synapse_port_db --sqlite-database homeserver.db.snapshot --postgres-config /etc/matrix-synapse/homeserver-postgres.yaml -v` and in return I got

`Preparing sqlite3...
2022-03-24 15:57:22,413 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} BEGIN TRANSACTION
2022-03-24 15:57:22,414 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.000101 sec
2022-03-24 15:57:22,414 - synapse.storage.prepare_database - 95 - INFO - ('main', 'state'): Checking existing schema version
2022-03-24 15:57:22,416 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} CREATE TABLE IF NOT EXISTS schema_version( Lock CHAR(1) NOT NULL DEFAULT 'X' UNIQUE, version INTEGER NOT NULL, upgraded BOOL NOT NULL, CHECK (Lock='X') )
2022-03-24 15:57:22,423 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.006934 sec
2022-03-24 15:57:22,424 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} CREATE TABLE IF NOT EXISTS applied_schema_deltas( version INTEGER NOT NULL, file TEXT NOT NULL, UNIQUE(version, file) )
2022-03-24 15:57:22,424 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.000086 sec
2022-03-24 15:57:22,424 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} CREATE TABLE IF NOT EXISTS applied_module_schemas( module_name TEXT NOT NULL, file TEXT NOT NULL, UNIQUE(module_name, file) )
2022-03-24 15:57:22,425 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.000122 sec
2022-03-24 15:57:22,425 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} SELECT version, upgraded FROM schema_version
2022-03-24 15:57:22,426 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.000193 sec
2022-03-24 15:57:22,426 - synapse.storage.SQL - 310 - DEBUG - [SQL] {prepare_database} SELECT file FROM applied_schema_deltas WHERE version >= ?
2022-03-24 15:57:22,427 - synapse.storage.SQL - 315 - DEBUG - [SQL values] {prepare_database} (68,)
2022-03-24 15:57:22,427 - synapse.storage.SQL - 336 - DEBUG - [SQL time] {prepare_database} 0.000222 sec
2022-03-24 15:57:22,427 - synapse.storage.prepare_database - 100 - INFO - ('main', 'state'): Existing schema is 68 (+3 deltas)
2022-03-24 15:57:22,431 - synapse_port_db - 716 - ERROR - 
Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 564, in run
    self.sqlite_store = self.build_db_store(
  File "/usr/local/bin/synapse_port_db", line 530, in build_db_store
    prepare_database(db_conn, engine, config=self.hs_config)
  File "/usr/local/lib/python3.8/dist-packages/synapse/storage/prepare_database.py", line 121, in prepare_database
    _upgrade_existing_database(
  File "/usr/local/lib/python3.8/dist-packages/synapse/storage/prepare_database.py", line 347, in _upgrade_existing_database
    raise ValueError(
ValueError: Cannot use this database as it is too new for the server to understand
2022-03-24 15:57:22,434 - synapse.metrics - 596 - DEBUG - Collecting gc 0
Traceback (most recent call last):
  File "/usr/local/bin/synapse_port_db", line 564, in run
    self.sqlite_store = self.build_db_store(
  File "/usr/local/bin/synapse_port_db", line 530, in build_db_store
    prepare_database(db_conn, engine, config=self.hs_config)
  File "/usr/local/lib/python3.8/dist-packages/synapse/storage/prepare_database.py", line 121, in prepare_database
    _upgrade_existing_database(
  File "/usr/local/lib/python3.8/dist-packages/synapse/storage/prepare_database.py", line 347, in _upgrade_existing_database
    raise ValueError(
ValueError: Cannot use this database as it is too new for the server to understand`

I don't know how to fix this and my service is down at this time. If someone can help that would be great. Thanks in advance

**Comment by jon-bit** [comment]
@anoadragon453 Thank you for the response. to start 1. The output was `/usr/local/bin/synapse_port_db`. I'm not sure what you mean but but I hope it helps. 2. the PostgreSQL install in 100% clean. I installed it just so I can migrate and do other things with PostgreSQL. and finally 3. the version is `3.31.1`. I installed matrix with apt so I don't know how to update it, if apt update and upgrade will do it, or check the version so I'll just look into that while I'm waiting for your response, and once again thank you so much for you help.

**Comment by H-Shay** [comment]
Closing due to inaction.
