### ISSUE TITLE
OpenID Connect: UserInfo fetching fails if returned as jwt (using endpoint)

### ISSUE THREAD

**Issue by jweko** [matrix-org/synapse#12530]
### Description

I’m trying to use openid connect with synapse. The configured openid connect provider uses the user info endpoint to provide the user info (not the id token). The user info response contains a jwt (which contains the user info) and not a json directly.  Requesting such a user info fails with an "Could not fetch userinfo" error (see below).

### Steps to reproduce

- configure oidc_provider with property "user_profile_method: "userinfo_endpoint"" and "scopes: ["openid",...]"
- use an oidc provider which returns the a jwt as response to the call of the user info endpoint 
- Login with the configured oidc provider
- Home Server logs the following error:

`    2022-04-22 16:46:12,004 - synapse.handlers.oidc - 856 - ERROR - GET-3 - Could not fetch userinfo
    Traceback (most recent call last):
     File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 854, in handle_oidc_callback
        userinfo = await self._fetch_userinfo(token)
      File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 655, in _fetch_userinfo
        resp = await self._http_client.get_json(
      File "/usr/local/lib/python3.9/site-packages/synapse/http/client.py", line 589, in get_json
        return json_decoder.decode(body.decode("utf-8"))
      File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
     json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

The OpenID Connect spec defines (https://openid.net/specs/openid-connect-core-1_0.html#UserInfo):
_"If the UserInfo Response is signed and/or encrypted, then the Claims are returned in a JWT and the content-type MUST be application/jwt"_ which is the case for the respone. 

Did I miss something or is this a bug/missing feature? 


### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:
locally running
<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
{"server_version":"1.57.1","python_version":"3.9.12"}
- **Install method**:
<!-- examples: package manager/git clone/pip  -->
git clone, locally build docker image
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
docker image on wsl ubuntu 20.04

**Comment by richvdh** [comment]
Yes, it's a missing feature.

It's worth noting that Synapse *does* support userinfo being returned in a JWT when it is part of the id token, so I think we probably have everything we need here; it's just a matter of wiring it up.
