### ISSUE TITLE
this happens with 1.57 onward. 1.56 is ok.

### ISSUE THREAD

**Issue by MparkG** [matrix-org/synapse#12561]
### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
the query returns no rows when ran on the db. i have federation on in general, i couldnt find the event id in question in the db.  not manually in the tables, nor per pg_dump and grep of that. no idea what room the error came from. retention has been on for the last weeks, i have now turned it off, because i suspect it to be the origin. however the error remains after restarting synapse. db maintenance is pg_dump, compress_states_large_rooms, vaccum.
its the initial sync that is broken for me.
for at least two users.
this is the apache (proxy) log line:
```
"GET /_matrix/client/r0/sync?filter=5&timeout=0&_cacheBuster=1650918641901 HTTP/2.0" 500 719 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
```
synapse error:
```
2022-04-25 22:33:25,682 - synapse.access.http.8008 - 427 - INFO - GET-2- 10.0.0.223 - 8008 - {@asd:masd.asd} Processed request: 0.002sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 55B 500 "GET /_matrix/client/r0/sync?filter=5&timeout=0&_cacheBuster=1650918805656 HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0" [0 dbevts]
2022-04-25 22:33:32,459 - synapse.util.caches.response_cache - 254 - INFO - GET-3- [sync]: using completed cached result for [(@asd:masd.asd, 0, None, '5', False, 'noideawhatthisis')]
2022-04-25 22:33:32,459 - synapse.http.server - 100 - ERROR - GET-3- Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f5f145ad8b0 method='GET' uri='/_matrix/client/r0/sync?filter=5&timeout=0&_cacheBuster=1650918812445' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 268, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 470, in _async_render
    callback_return = await raw_callback_return
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/rest/client/sync.py", line 192, in on_GET
    sync_result = await self.sync_handler.wait_for_sync_for_user(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 297, in wait_for_sync_for_user
    res = await self.response_cache.wrap(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/util/caches/response_cache.py", line 265, in wrap
    return await make_deferred_yieldable(result)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/util/caches/response_cache.py", line 246, in cb
    return await callback(*args, **kwargs)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 355, in _wait_for_sync_for_user
    result: SyncResult = await self.current_sync_for_user(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 406, in current_sync_for_user
    sync_result = await self.generate_sync_result(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1114, in generate_sync_result
    res = await self._generate_sync_entry_for_rooms(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1625, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 233, in concurrently_execute
    await yieldable_gather_results(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 274, in yieldable_gather_results
    raise dfe.subFailure.value from None
  File "/home/server/.synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 225, in _concurrently_execute_inner
    await maybe_awaitable(func(value))
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1614, in handle_room_entries
    await self._generate_room_entry(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 2060, in _generate_room_entry
    batch = await self._load_filtered_recents(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/handlers/sync.py", line 592, in _load_filtered_recents
    loaded_recents = await filter_events_for_client(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/visibility.py", line 85, in filter_events_for_client
    event_id_to_state = await storage.state.get_state_for_events(
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/storage/state.py", line 671, in get_state_for_events
    event_to_groups = await self.stores.main._get_state_group_for_events(event_ids)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/server/.synapse/env/lib/python3.8/site-packages/synapse/storage/databases/main/state.py", line 331, in _get_state_group_for_events
    raise RuntimeError("No state group for unknown or outlier event %s" % e)
RuntimeError: No state group for unknown or outlier event $4C1ulcbO5gZeV2t0sc5GASD2G09VvFm0bTGWIZDBlIw
```

**Comment by H-Shay** [comment]
This appears to be #12549, closing in favor of that issue.
