### ISSUE TITLE
Upgrade to 1.58.0 from 1.57.0 failed

### ISSUE THREAD

**Issue by pixel8383** [matrix-org/synapse#12628]
### Description

I tried to install the latest upgrade on a debian machine using a postgresql database for matrix-synapse.

As usual I just did "sudo apt update && sudo apt upgrade" and I was prompted with 1.58.0+bullseye1 update

The upgrade process failed and inside homeserver.log I can see:

```
2022-05-04 10:59:44,329 - root - 355 - WARNING - main - ***** STARTING SERVER *****
2022-05-04 10:59:44,376 - root - 356 - WARNING - main - Server /opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py version 1.58.0
2022-05-04 10:59:44,377 - root - 361 - INFO - main - Server hostname: myhomeserver.com
2022-05-04 10:59:44,377 - root - 362 - INFO - main - Instance name: master
2022-05-04 10:59:44,377 - synapse.app.homeserver - 379 - INFO - main - Setting up server
2022-05-04 10:59:44,377 - synapse.server - 315 - INFO - main - Setting up.
2022-05-04 10:59:44,442 - synapse.storage.databases - 66 - INFO - main - [database config 'master']: Checking database server
2022-05-04 10:59:44,443 - synapse.storage.databases - 69 - INFO - main - [database config 'master']: Preparing for databases ['main', 'state']
2022-05-04 10:59:44,443 - synapse.storage.prepare_database - 116 - INFO - main - ['main', 'state']: Checking existing schema version
2022-05-04 10:59:44,954 - synapse.storage.prepare_database - 146 - INFO - main - ['main', 'state']: Initialising new database
2022-05-04 10:59:44,956 - synapse.app._base - 196 - ERROR - main - Exception during startup
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py", line 382, in setup
    hs.setup()
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/server.py", line 317, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 74, in __init__
    prepare_database(
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 153, in prepare_database
    _setup_new_database(cur, database_engine, databases=databases)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 270, in _setup_new_database
    executescript(cur, entry.absolute_path)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 657, in executescript
    execute_statements_from_stream(txn, f)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 662, in execute_statements_from_stream
    cur.execute(statement)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 333, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 366, in _do_execute
    return func(sql, *args)
sqlite3.OperationalError: table background_updates already exists
2022-05-04 10:59:51,753 - root - 355 - WARNING - main - ***** STARTING SERVER *****
2022-05-04 10:59:51,753 - root - 356 - WARNING - main - Server /opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/app/homeserver.py version 1.58.0
2022-05-04 10:59:51,753 - root - 361 - INFO - main - Server hostname: myhomeserver.com
2022-05-04 10:59:51,753 - root - 362 - INFO - main - Instance name: master
2022-05-04 10:59:51,753 - synapse.app.homeserver - 379 - INFO - main - Setting up server
2022-05-04 10:59:51,753 - synapse.server - 315 - INFO - main - Setting up.
```

I can't find no way to install the package and I am not able to restore the previous install so my server right now is down.

I am not using an sqlite db for matrix so I don't get why the logs points to it (could it be relevant to understand the issue?).

**Comment by pixel8383** [comment]
My fault: the homeserver.yaml was reset to default.
