### ISSUE TITLE
Attempting to call `/messages` on a room that doesn't exist results in a 500

### ISSUE THREAD

**Issue by bradtgmurray** [matrix-org/synapse#12678]
### Description
Requesting messages for a nonsense room id should probably return a 404 or a 403, but instead it just blows up in Sentry with a 500 here: https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/pagination.py#L451

Interestingly the spec only says 200 or 403 (You're not a member of this room) are valid responses.
https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3roomsroomidmessages

### Steps to reproduce
Throw this in your javascript console for your element web login

```
await fetch("https://matrix-client.matrix.org/_matrix/client/r0/rooms/!doesnotexist%3Amatrix.org/messages?limit=20&dir=b", {
  "headers": {
    "authorization": "Bearer <your access token here>",
  },
  "method": "GET",
}).then(r => r.json());
```

### Version information

Beeper's fork of 1.57.1 (haven't gotten to 1.58 yet) but reproduced as well on matrix.org (above)

**Comment by bradtgmurray** [comment]
Ah, new in 1.57 I think

https://github.com/matrix-org/synapse/commit/793d03e2c5c8e688380b8070d53a7e500b7734af

@MadLittleMods

**Comment by clokep** [comment]
Sentry link: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/247053/

**Comment by MadLittleMods** [comment]
Here is the traceback:

```
2022-05-09 15:31:37,607 - synapse.http.server - 120 - ERROR - GET-95853 - Failed handle request via 'RoomMessageListRestServlet': <XForwardedForRequest at 0x112643fd0 method='GET' uri='/_matrix/client/v3/rooms/!dne:my.synapse.server/messages?dir=b' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/Users/eric/Documents/github/element/synapse/env/lib/python3.9/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eric/Documents/github/element/synapse/synapse/http/server.py", line 298, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/Users/eric/Documents/github/element/synapse/synapse/http/server.py", line 500, in _async_render
    callback_return = await raw_callback_return
  File "/Users/eric/Documents/github/element/synapse/synapse/rest/client/room.py", line 585, in on_GET
    msgs = await self.pagination_handler.get_messages(
  File "/Users/eric/Documents/github/element/synapse/synapse/handlers/pagination.py", line 451, in get_messages
    assert from_token.room_key.topological
AssertionError
```


Before https://github.com/matrix-org/synapse/pull/12370, `/messages` would return a `403` forbidden for a non-existent room:

```json
{
    "errcode": "M_FORBIDDEN",
    "error": "User @test:my.synapse.server not in room !dne:my.synapse.server, and room previews are disabled"
}
```
