### ISSUE TITLE
Cannot load appservice

### ISSUE THREAD

**Issue by Longtianmu** [matrix-org/synapse#13108]
### Description

Try to load appservice of https://github.com/dylhack/matrix-appservice-minecraft
Synapse throw "No such file or directory" even if the file exists

### Steps to reproduce

- Download the project and follow it steps
- set Synapse's config file "app_service_config_files: []" to the value in the appservice project config.yaml
- systemctl restart matrix-synapse

### Homeserver

mchat.ltm.ink

### Synapse Version

1.61.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Debian 11.1 with 4G ram

### Relevant log output

```shell
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]:   File "/usr/local/lib/python3.9/site-packages/synapse/config/appservice.py", line 70, in load_appservices
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]:     with open(config_file) as f:
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]: FileNotFoundError: [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]: ***********************************************************
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]:  Error during initialisation:
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]:     [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]:  There may be more information in the logs.
Jun 20 20:01:00 VM-8-11-debian matrix-synapse[3814468]: ***********************************************************
Jun 20 20:01:01 VM-8-11-debian systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 20:01:01 VM-8-11-debian systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 20 20:01:31 VM-8-11-debian systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 14.
Jun 20 20:01:31 VM-8-11-debian systemd[1]: Stopped Synapse server.
Jun 20 20:01:31 VM-8-11-debian systemd[1]: Starting Synapse server...
Jun 20 20:01:31 VM-8-11-debian systemd[1]: Started Synapse server.
Jun 20 20:01:32 VM-8-11-debian matrix-synapse[3847195]: Starting synapse with args -m synapse.app.homeserver -c /data/homeserver.yaml
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: This server is configured to use 'matrix.org' as its trusted key server via the
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: server since it is long-lived, stable and trusted. However, some admins may
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: wish to use another server for this purpose.
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: To suppress this warning and continue using 'matrix.org', admins should set
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: --------------------------------------------------------------------------------
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 2022-06-20 12:01:35,655 - root - 348 - WARNING - main - ***** STARTING SERVER *****
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 2022-06-20 12:01:35,655 - root - 349 - WARNING - main - Server /usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py version 1.61.0
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 2022-06-20 12:01:35,692 - synapse.config.appservice - 93 - ERROR - main - Failed to load appservice from 'appservice.yaml'
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 2022-06-20 12:01:35,692 - synapse.config.appservice - 94 - ERROR - main - [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: Traceback (most recent call last):
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/config/appservice.py", line 70, in load_appservices
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     with open(config_file) as f:
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: FileNotFoundError: [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: 2022-06-20 12:01:35,693 - synapse.app._base - 203 - ERROR - main - Exception during startup
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: Traceback (most recent call last):
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 382, in setup
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     hs.setup()
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 306, in setup
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     self.datastores = Databases(self.DATASTORE_CLASS, self)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 93, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     main = main_store_class(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/__init__.py", line 179, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/events_bg_updates.py", line 93, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/roommember.py", line 1354, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/room.py", line 1578, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/room.py", line 1184, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/room.py", line 101, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/registration.py", line 1937, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/stream.py", line 366, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/presence.py", line 67, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/presence.py", line 48, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/transactions.py", line 73, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/state.py", line 659, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/state.py", line 80, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/state.py", line 463, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/event_federation.py", line 1702, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/media_repository.py", line 158, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/media_repository.py", line 71, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/push_rule.py", line 337, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/end_to_end_keys.py", line 1112, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/end_to_end_keys.py", line 94, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/end_to_end_keys.py", line 76, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/search.py", line 416, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/search.py", line 126, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/account_data.py", line 65, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/push_rule.py", line 130, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     super().__init__(database, db_conn, hs)
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/appservice.py", line 76, in __init__
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     self.services_cache = load_appservices(
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:   File "/usr/local/lib/python3.9/site-packages/synapse/config/appservice.py", line 70, in load_appservices
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     with open(config_file) as f:
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: FileNotFoundError: [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: ***********************************************************
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:  Error during initialisation:
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:     [Errno 2] No such file or directory: 'appservice.yaml'
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]:  There may be more information in the logs.
Jun 20 20:01:35 VM-8-11-debian matrix-synapse[3847195]: ***********************************************************
Jun 20 20:01:36 VM-8-11-debian systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jun 20 20:01:36 VM-8-11-debian systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 20 20:02:06 VM-8-11-debian systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 15.
```

**Comment by DMRobertson** [comment]
It's tricky to advise without knowing more about how your setup is configured. How are you running the synapse container? How are you making the appservice configuration file accessible inside the docker container?
