### ISSUE TITLE
JWT authentication fails with invalid format  error when using RS256 algorithm

### ISSUE THREAD

**Issue by jpschw** [matrix-org/synapse#13250]
### Description
RSA public key format is not accepted by openSSL when using org.matrix.login.jwt login type.

Error from openSSL is this:
PEM routines:get_name:no start line'

**homeserver.yaml**
```
jwt_config:
    # Uncomment the following to enable authorization using JSON web
    # tokens. Defaults to false.
    #
    enabled: true

    # This is either the private shared secret or the public key used to
    # decode the contents of the JSON web token.
    #
    # Required if 'enabled' is true.
    #
    secret: |-
      -----BEGIN CERTIFICATE-----
      MIIDETCCAfmgAwIBAgIJRwa6F9tTiRW3MA0GCSqGSIb3DQEBCwUAMCYxJDAiBgNV
      BAMTG2VmZmljaWVudHN1aXRlLnVzLmF1dGgwLmNvbTAeFw0yMjA0MTYwMDU4MTFa
      Fw0zNTEyMjQwMDU4MTFaMCYxJDAiBgNVBAMTG2VmZmljaWVudHN1aXRlLnVzLmF1
      dGgwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL+8OXcoAwLz
      h1yPw2wYE3tfbzGR1jTVcS4BEPe824MevzMLG8kM0HB57wUw/krlvvadRvPEwn8b
      KoBTbTvuqjd8nK9xK3ELc9Vsj2KbWCxM78FHClLdSAQ2jaTon3XM6jJroVzxCKNQ
      uPWUYskDOfmvwFfh0zQKcBziGJGQ1J49hhp3wuzBJsGPoF4QGgqVPdOJ5omxr37N
      YRJ5iNS90blphUma75T6zgQEjnPvcTK+c1w+EqhZHV9pQRHZViU/WJGd244C3KBL
      vmhHbA8MPDWTQlRppmhW4Buw3g6ih7NcoKwDlihE2hHh7mAHJDhsiyY7fZksWeDc
      li/U/ahsDZMCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU7R8r
      KrZYGG3+TweG6I+cFLfhGTgwDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUA
      A4IBAQB8dDpbzvt9Iz366z3pnlKXVvOp0mpf3ObDzTRnOeZhwdi85o+VBX1bOoO/
      UH1b2FLucw26zLoUNeCwILzwvJ1Dm8aOxG5fZ+9GETgx+hitwlj9YVl7gaD+DBLm
      Dq1SQCT1eB2C5FpogibaBe9g9ho8eGncx1nQjD6cbSWBF63UIqvGk+bxMNDb0xMA
      KOtzL29xqPsIKZp1MllkXOz+7URL2X84xwJut4ZCwUELSRLmxmhhigA+i/USkAKL
      5qdO0y3dzkJnWN6ICM4e6tNBtrfCBaSHteOCnxWJB0edx6dMQqe1zGW4J+vB8TxJ
      WjKrSmDYSBCIhR7E7Zpe0DtL1ZNx
      -----END CERTIFICATE-----

    # The algorithm used to sign the JSON web token.
    #
    # Supported algorithms are listed at
    # https://pyjwt.readthedocs.io/en/latest/algorithms.html
    #
    # Required if 'enabled' is true.
    #
    algorithm: "RS256"

    # Name of the claim containing a unique identifier for the user.
    #
    # Optional, defaults to `sub`.
    #
    subject_claim: "sub"

    # The issuer to validate the "iss" claim against.
    #
    # Optional, if provided the "iss" claim will be required and
    # validated for all JSON web tokens.
    #
    issuer: "https://<companyname>.us.auth0.com/"

    # A list of audiences to validate the "aud" claim against.
    #
    # Optional, if provided the "aud" claim will be required and
    # validated for all JSON web tokens.
    #
    # Note that if the "aud" claim is included in a JSON web token then
    # validation will fail without configuring audiences.
    #
    audiences:
        - "https://<companyname>.us.auth0.com/api/v2/"

```

### Steps to reproduce

- Send JWT token to /login endpoint of homeserver:
```
const res = await axios.post(`<server_address>/login`, {
          type: "org.matrix.login.jwt",
          token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
});
```

### Homeserver

private homeserver

### Synapse Version

{"server_version":"1.61.0","python_version":"3.8.10"}

### Installation Method

pip (from PyPI)

### Platform

Ubuntu VM

### Relevant log output

```shell
2022-07-12 05:34:05,321 - synapse.http.server - 183 - ERROR - POST-1 - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f1c8c0bac40 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/jwt/algorithms.py", line 257, in prepare_key
    key = load_pem_private_key(key, password=None)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 22, in load_pem_private_key
    return ossl.load_pem_private_key(data, password)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 823, in load_pem_private_key
    return self._load_key(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1070, in _load_key
    self._handle_key_loading_error()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1129, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])
```

### Anything else that would be useful to know?
- I'm using Auth0.
- I tried removing the newlines and defining the key on a single line too but no luck.
- /_matrix/client/r0/login shows that the jwt flow is available: {"type":"org.matrix.login.jwt"}
- synapse[jwt] package was installed with pip

**Comment by clokep** [comment]
The underlying implementation for JWT login was updated in Synapse v1.62.0 (from PyJWT to authlib). I think the first thing to try is upgrading Synapse to 1.62.0 and seeing if this is still an issue.

**Comment by jpschw** [comment]
Hey, thanks for the quick reply. I upgraded to {"server_version":"1.62.0","python_version":"3.8.10"}. Still having the issue though...
I'm going to dig a bit deeper and come back within a day or so with what I find. I want to make sure I didn't miss anything stupid on my end.

2022-07-13 03:12:07,401 - synapse.http.server - 183 - ERROR - POST-8 - Failed handle request via 'LoginRestServlet': <XForwardedForRequest at 0x7f4f483e9220 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7517/_cryptography_key.py", line 32, in load_pem_key
    return load_pem_private_key(raw, password=password, backend=default_backend())
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 22, in load_pem_private_key
    return ossl.load_pem_private_key(data, password)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 823, in load_pem_private_key
    return self._load_key(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1070, in _load_key
    self._handle_key_loading_error()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1129, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 366, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/http/server.py", line 572, in _async_render
    callback_return = await raw_callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/login.py", line 194, in on_POST
    result = await self._do_jwt_login(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/rest/client/login.py", line 434, in _do_jwt_login
    claims = jwt.decode(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7519/jwt.py", line 99, in decode
    data = self._jws.deserialize_compact(s, load_key, decode_payload)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7515/jws.py", line 102, in deserialize_compact
    algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7515/jws.py", line 258, in _prepare_algorithm_key
    key = algorithm.prepare_key(key)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7518/_cryptography_backends/_jws.py", line 41, in prepare_key
    return RSAKey.import_key(raw_data)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7518/_cryptography_backends/_keys.py", line 114, in import_key
    return import_key(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7518/_cryptography_backends/_keys.py", line 258, in import_key
    raw_key = load_pem_key(raw, ssh_type, password=password)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/authlib/jose/rfc7517/_cryptography_key.py", line 34, in load_pem_key
    return load_pem_public_key(raw, backend=default_backend())
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 30, in load_pem_public_key
    return ossl.load_pem_public_key(data)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 853, in load_pem_public_key
    self._handle_key_loading_error()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1129, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])
2022-07-13 03:12:07,404 - synapse.access.http.8008 - 450 - INFO - POST-8 - 24.87.154.113 - 8008 - {None} Processed request: 0.003sec/0.001sec (0.003sec, 0.000sec) (0.000sec/0.000sec/0) 55B 500 "POST /_matrix/client/r0/login HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" [0 dbevts]
2022-07-13 03:12:10,367 - synapse.access.http.8008 - 450 - INFO - GET-9 - 178.174.175.70 - 8008 - {None} Processed request: 0.000sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 208B 302 "GET / HTTP/1.0" "Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36" [0 dbevts]
2022-07-13 03:12:10,615 - synapse.access.http.8008 - 450 - INFO - GET-10 - 178.174.175.70 - 8008 - {None} Processed request: 0.001sec/-0.000sec (0.002sec, 0.000sec) (0.000sec/0.000sec/0) 210B 302 "GET /_matrix/static HTTP/1.0" "Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36" [0 dbevts]
2022-07-13 03:12:10,727 - synapse.access.http.8008 - 450 - INFO - GET-11 - 178.174.175.70 - 8008 - {None} Processed request: 0.002sec/-0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 10168B 200 "GET /_matrix/static/ HTTP/1.0" "Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36" [0 dbevts]

**Comment by jpschw** [comment]
I believe it might be because I pasted a certificate rather than the public key embedded in it.

**Comment by jpschw** [comment]
For anyone who finds themselves in the same situation...
Auth0 provides a public certificate that you need to extract the public key from. I used the following command to get it:
curl -s https://<site>.us.auth0.com/pem | openssl x509 -pubkey -noout

**Comment by clokep** [comment]
Thanks for providing your solution to help the next person! 👍
