### ISSUE TITLE
Account validation with e-mail does not work

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [matrix-org/synapse#13609]
I want to use account validation using e-mail but it doesn't work correctly. I'm using synapse in docker with a reverse proxy (nginx) switched in front of it.
This is my config:

####################################################################

 email:
  smtp_host: localhost
  smtp_port: 587
  smtp_user: "user"
  smtp_pass: "password"
  force_tls: true
  require_transport_security: true
  enable_tls: true
  notif_from: "Matrix Server <noreply@matrix.mail.com>"
  app_name: a_matrix_server
  enable_notifs: true
  notif_for_new_users: false
  client_base_url: "http://localhost/riot"
  validation_token_lifetime: 15m
  invite_client_location: https://app.element.io

  subjects:
    message_from_person_in_room: "[%(app)s] You have a message on %(app)s from %(person)s in the %(room)s room..."
    message_from_person: "[%(app)s] You have a message on %(app)s from %(person)s..."
    messages_from_person: "[%(app)s] You have messages on %(app)s from %(person)s..."
    messages_in_room: "[%(app)s] You have messages on %(app)s in the %(room)s room..."
    messages_in_room_and_others: "[%(app)s] You have messages on %(app)s in the %(room)s room and others..."
    messages_from_person_and_others: "[%(app)s] You have messages on %(app)s from %(person)s and others..."
    invite_from_person_to_room: "[%(app)s] %(person)s has invited you to join the %(room)s room on %(app)s..."
    invite_from_person: "[%(app)s] %(person)s has invited you to chat on %(app)s..."
    password_reset: "[%(server_name)s] Password reset"
    email_validation: "[%(server_name)s] Validate your email"

####################################################################

But every time I want to register a new user I get this error in the docker logs:

####################################################################

2022-08-23 13:52:49,908 - synapse.handlers.send_email - 193 - INFO - POST-19 - Sending email to example@mail.com
2022-08-23 13:52:49,931 - twisted - 274 - INFO - sentinel - SMTP Client retrying server. Retry: 5
2022-08-23 13:52:49,933 - twisted - 274 - INFO - sentinel - SMTP Client retrying server. Retry: 4
2022-08-23 13:52:49,934 - twisted - 274 - INFO - sentinel - SMTP Client retrying server. Retry: 3
2022-08-23 13:52:49,935 - twisted - 274 - INFO - sentinel - SMTP Client retrying server. Retry: 2
2022-08-23 13:52:49,936 - twisted - 274 - INFO - sentinel - SMTP Client retrying server. Retry: 1
2022-08-23 13:52:49,937 - synapse.handlers.identity - 396 - ERROR - POST-19 - Error sending threepid validation email to example@mail.com
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/identity.py", line 394, in send_threepid_validation
    await send_email_func(email_address, token, client_secret, session_id)
  File "/usr/local/lib/python3.9/site-packages/synapse/push/mailer.py", line 179, in send_registration_mail
    await self.send_email(
  File "/usr/local/lib/python3.9/site-packages/synapse/push/mailer.py", line 327, in send_email
    await self.send_email_handler.send_email(
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/send_email.py", line 195, in send_email
    await self._sendmail(
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/send_email.py", line 130, in _sendmail
    await make_deferred_yieldable(d)
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
2022-08-23 13:52:49,938 - synapse.http.server - 169 - INFO - POST-19 - <XForwardedForRequest at 0x7f216cab87f0 method='POST' uri='/_matrix/client/r0/register/email/requestToken' clientproto='HTTP/1.1' site='8008'> SynapseError: 500 - An error was encountered when sending the email
2022-08-23 13:52:49,939 - synapse.access.http.8008 - 450 - INFO - POST-19 - 172.68.110.128 - 8008 - {None} Processed request: 0.040sec/0.000sec (0.023sec, 0.003sec) (0.001sec/0.004sec/2) 81B 500 "POST /_matrix/client/r0/register/email/requestToken HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44" [0 dbevts]
2022-08-23 13:52:51,688 - synapse.access.http.8008 - 450 - INFO - GET-20 - 172.68.110.128 - 8008 - {None} Processed request: 0.003sec/0.001sec (0.002sec, 0.001sec) (0.001sec/0.001sec/1) 18B 200 "GET /_matrix/client/r0/register/available?username=testuser HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44" [0 dbevts]

####################################################################

Does somebody has any idea?

**Comment by richvdh** [comment]
Looks like it can't talk to your SMTP server. I would expect there to be more exceptions in the log about it somewhere.

However, I see you're requiring TLS on a connection to `localhost`. It seems unlikely that you would have a valid TLS certificate for `localhost`. What do you hope to gain by using TLS here?

**Comment by richvdh** [comment]
oh, also: if you're using synapse in docker, then `localhost` is going to point *inside* the docker container. Unless you are using a custom docker container that starts synapse *and* an SMTP server, that's not going to work.

I'm going to close this as it looks like a configuration issue rather than a bug, and we can't provide support via this issue tracker.
