### ISSUE TITLE
`allow_unsafe_locale` fails a few steps down the road

### ISSUE THREAD

**Issue by erkinalp** [matrix-org/synapse#13709]
### Description

`allow_unsafe_locale` still fails to work when a non-C locale is supplied.

### Steps to reproduce

- Run Synapse with YugabyteDB as the database
- Observe it fails to work because Yugabyte storage actually does not support `C` collation

### Homeserver

local test setup

### Synapse Version

1.66.0

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Yugabyte is also from the latest docker.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 382, in setup
    hs.setup()
  File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 308, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 74, in __init__
    prepare_database(
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 152, in prepare_database
    _setup_new_database(cur, database_engine, databases=databases)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 213, in _setup_new_database
    database_engine.check_new_database(cur)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/engines/postgres.py", line 137, in check_new_database
    raise IncorrectDatabaseSetup(
synapse.storage.engines._base.IncorrectDatabaseSetup: Database is incorrectly configured:

    - 'CTYPE' is set to 'en_US.UTF-8'. Should be 'C'

See docs/postgres.md for more information.
******************************************************
 Error during initialisation:
    Database is incorrectly configured:
 
     - 'CTYPE' is set to 'en_US.UTF-8'. Should be 'C'
 
 See docs/postgres.md for more information.
 There may be more information in the logs.
******************************************************
```

**Comment by erkinalp** [comment]
Corresponding yugabyte issue: https://github.com/yugabyte/yugabyte-db/issues/13863

**Comment by erkinalp** [comment]
![image](https://user-images.githubusercontent.com/5833034/188331895-97ca23ec-c523-4584-b6da-c846fc4244ca.png)

**Comment by DMRobertson** [comment]
See #12055 for motivation. I think most people would expect there to be a single `i_know_what_im_doing_and_accept_possible_data_corruption` flag, and so we'd probably accept a PR which

- made this flag also disable the check on `SERVER_ENCODING`
- updated docs accordingly.

Note that we have no plans to support databases other than Postgres and Sqlite, not even those which aim to be wire-compatible with Postgres.
