### ISSUE TITLE
Update authlib to 1.x.x in Debian packages and Docker images

### ISSUE THREAD

**Issue by etkecc** [matrix-org/synapse#13747]
**Description:**

Currently authlib v0.15.5 is required, but it's outdated for a while

The latest release is [v1.0.1](https://github.com/lepture/authlib/releases/tag/v1.0.1) that has fixes for different things and thus allow integrations of other identity provider, like [Drupal Oauth2 server](https://www.drupal.org/project/oauth2_server)

**Comment by DMRobertson** [comment]
If anyone wants to do this:

1. Investigate the authlib changelog to check that authlib 1.0.1 is backwards compatible with 0.15.5 (the version currently in the [lockfile](https://github.com/matrix-org/synapse/blob/4fee4a339d3bb1a90487a86ccbcca50a36b0ea74/poetry.lock#L15-L21)) and 0.14.0 ([our lower bound for source installations](https://github.com/matrix-org/synapse/blob/cdf7fb737b12cc06cc5693806ee8fa21ade9723d/pyproject.toml#L173))
2. If so, `poetry update authlib`

**Comment by natecovington** [comment]
I've got a Drupal / PHP programmer looking into this issue with me and I'm having trouble updating Authlib on my Synapse server - `poetry update "authlib==1.0.1"`

Gives me this error:
  RuntimeError
  Poetry could not find a pyproject.toml file in /root or its parents

```
  at /usr/lib/python3/dist-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
```

Can someone point me in the right direction?  I am using the ansible playbook if it matters

**Comment by etkecc** [comment]
You're using docker container, thus you have to:
1. Fork synapse repo (this one)
2. Adjust authlib version in the requirements file
3. Build docker image
4. Push it to any registry
5. Switch synapse image to your fork

**Comment by ffaex** [comment]
Hi, I would like to work on this issue. :)

**Comment by DMRobertson** [comment]
> Hi, I would like to work on this issue. :)

We'd gladly accept a PR.

**Comment by natecovington** [comment]
Here's where I've gotten with this so far:

I forked the Synapse github repo here, renaming it synapse-authlib:
https://github.com/natecovington/synapse-authlib

Github Project -> Settings -> Secrets (added Docker hub info)

https://github.com/natecovington/synapse-authlib/blob/develop/.github/workflows/docker.yml
`          images: natecovington/synapse-authlib`

In the Python configuration, I updated authlib to 1.0.1:
https://github.com/natecovington/synapse-authlib/blob/develop/pyproject.toml

`authlib = { version = ">=1.0.1", optional = true }`

In the dockerfile, I referenced my synapse-authlib fork instead of the standard matrix-org/synapse:
https://github.com/natecovington/synapse-authlib/blob/develop/docker/Dockerfile

`LABEL org.opencontainers.image.source='https://github.com/natecovington/synapse-authlib.git'`

Then I ran these commands to build the image and push it back to docker hub:

> docker tag matrixdotorg/synapse natecovington/synapse-authlib
> 
> docker build -t natecovington/synapse-authlib -f docker/Dockerfile .
> 
> docker build -t matrixdotorg/synapse -f docker/Dockerfile .
> 
> docker push natecovington/synapse-authlib


Then I cloned the playbook itself:
https://github.com/natecovington/matrix-docker-ansible-deploy-authlib/

Modified:
https://github.com/natecovington/matrix-docker-ansible-deploy-authlib/blob/master/roles/matrix-synapse/defaults/main.yml

```
matrix_synapse_container_image_self_build_repo: "https://github.com/natecovington/synapse.git"
matrix_synapse_docker_image: "{{ matrix_synapse_docker_image_name_prefix }}natecovington/synapse-authlib:{{ matrix_synapse_docker_image_tag }}"

```

And ran the playbook again, now I'm getting this error, I don't think Authlib is being installed properly?

> root@localhost:~/matrix-docker-ansible-deploy-authlib# journalctl -fu matrix-synapse.service
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
> Sep 29 19:19:35 localhost matrix-synapse[48112]:   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 21, in <module>
> Sep 29 19:19:35 localhost matrix-synapse[48112]:     from authlib.common.security import generate_token
> Sep 29 19:19:35 localhost matrix-synapse[48112]: ModuleNotFoundError: No module named 'authlib'
> 





Can someone please walk me through this?

**Comment by clokep** [comment]
@natecovington Would you be willing to make a PR instead and it will be updated in the next version of Synapse? @DMRobertson gave steps above of what to do to update the lock file.

**Comment by natecovington** [comment]
> @natecovington Would you be willing to make a PR instead and it will be updated in the next version of Synapse? @DMRobertson gave steps above of what to do to update the lock file.

If i knew how...

**Comment by natecovington** [comment]
I see that there is a PR submitted for this now, but I'm hoping to compare notes because I don't think I understand this fully.

Instead of using Ansible playbook I figured out how to install the Synapse docker container manually and configure Nginx, e.g:

```
docker pull natecovington/synapse-authlib:v1.68.0
docker build natecovington/synapse-authlib:v1.68.0
docker run -it --rm -v /var/docker_data/matrix:/data -e SYNAPSE_SERVER_NAME=matrix.example.com -e SYNAPSE_REPORT_STATS=yes natecovington/synapse-authlib:v1.68.0 generate
docker-compose up -d
```

That gave me a running matrix server - so I updated my Synapse configuration to use OIDC -> Drupal SSO:

```
enable_registration: true
enable_registration_without_verification: true
disable_msisdn_registration: yes
oidc_providers:
- idp_id: drupal
  idp_name: Drupal
  idp_brand: "drupal"
  discover: false
  authorization_endpoint: "https://example.com/oauth2/authorize"
  token_endpoint: "https://example.com/oauth2/token"
  userinfo_endpoint: "https://example.com/oauth2/userinfo"
  jwks_uri: "https://example.com/oauth2/certificates?jwkUri"
  issuer: "https://example.com/"
  client_id: "drupal_sso_client"
  client_secret: "secret"
  scopes: ["openid", "profile", "email", "offline_access"]
  user_mapping_provider:
    config:
      localpart_template: "{% raw %}{{ user.preferred_username }}{% endraw %}"
      display_name_template: "{% raw %}{{ user.name }}{% endraw %}"
```

However, now I'm getting this:

`2022-10-03T12:05:12.137987640Z 2022-10-03 12:05:12,137 - synapse.rest.client.login - 591 - INFO - GET-646 - Requested URI http://localhost:8008/_matrix/client/r0/login/sso/redirect/oidc-drupal?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F is not canonical: redirecting to https://matrix.example.com/_matrix/client/r0/login/sso/redirect/oidc-drupal?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F`


It seems there is some "canonical mismatch" because it's using "localhost:8008" - does this indicate I have something configured wrong in Nginx?  FWIW, I have a dedicated URL, matrix Linode VPS, and Drupal SSO demo site, all sandboxes... to test and get this working.  If I can help with testing, etc, please advise.  And if there's some change to my configuration that I should try, I'd be happy.  

Thanks!
-Nate

**Comment by squahtx** [comment]
> However, now I'm getting this:
> 
> `2022-10-03T12:05:12.137987640Z 2022-10-03 12:05:12,137 - synapse.rest.client.login - 591 - INFO - GET-646 - Requested URI http://localhost:8008/_matrix/client/r0/login/sso/redirect/oidc-drupal?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F is not canonical: redirecting to https://matrix.example.com/_matrix/client/r0/login/sso/redirect/oidc-drupal?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F`
> 
> It seems there is some "canonical mismatch" because it's using "localhost:8008" - does this indicate I have something configured wrong in Nginx?

That can happen when Nginx does not forward the `Host: ` header to Synapse. You may want to ensure that the `proxy_set_header` directives in the [example nginx config](https://matrix-org.github.io/synapse/v1.69/reverse_proxy.html#nginx) are in place.
```
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
```

If you're using matrix-docker-ansible-deploy, there may be two layers of nginx reverse proxies to check.

**Comment by natecovington** [comment]
> That can happen when Nginx does not forward the `Host: ` header to Synapse. You may want to ensure that the `proxy_set_header` directives in the [example nginx config](https://matrix-org.github.io/synapse/v1.69/reverse_proxy.html#nginx) are in place.

Thanks, I was able to configure nginx to forward the Host: header to Synapse, now, I'm getting that same "Missing $kid" error again:

```
2022-10-04T18:45:17.895487549Z 2022-10-04 18:45:17,894 - synapse.rest.client.login - 607 - INFO - GET-9264 - Redirecting to https://dev-lppa-sso.pantheonsite.io/oauth2/authorize?response_type=code&client_id=drupal_sso_client&redirect_uri=https%3A%2F%2Fmatrix.lppamonroe.com%2F_synapse%2Fclient%2Foidc%2Fcallback&scope=openid+profile+email+offline_access&state=3l0ZkcYbK4w222JR9ZTXLUTLiY1PGr&nonce=eG2J0bpVi0SkVKIAHlkvDGuqDXufNb
2022-10-04T18:45:17.898810370Z 2022-10-04 18:45:17,898 - synapse.access.http.8008 - 459 - INFO - GET-9264 - 50.29.133.7 - 8008 - {None} Processed request: 0.006sec/-0.001sec (0.006sec, 0.000sec) (0.000sec/0.000sec/0) 0B 302 "GET /_matrix/client/r0/login/sso/redirect/oidc-drupal?redirectUrl=https%3A%2F%2Fapp.element.io%2F%23%2F HTTP/1.0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" [0 dbevts]
2022-10-04T18:45:21.384039761Z 2022-10-04 18:45:21,379 - synapse.handlers.oidc - 231 - INFO - GET-9265 - Received OIDC callback for IdP oidc-drupal
2022-10-04T18:45:21.754423754Z 2022-10-04 18:45:21,749 - synapse.http.client - 446 - INFO - GET-9265 - Received response to POST https://dev-lppa-sso.pantheonsite.io/oauth2/token: 200
2022-10-04T18:45:21.765444979Z 2022-10-04 18:45:21,758 - synapse.handlers.oidc - 843 - ERROR - GET-9265 - Invalid id_token
2022-10-04T18:45:21.765681359Z Traceback (most recent call last):
2022-10-04T18:45:21.765921900Z   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 840, in handle_oidc_callback
2022-10-04T18:45:21.766019940Z     id_token = await self._parse_id_token(token, nonce=session_data.nonce)
2022-10-04T18:45:21.766161401Z   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 698, in _parse_id_token
2022-10-04T18:45:21.766202941Z     claims = jwt.decode(
2022-10-04T18:45:21.766356321Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
2022-10-04T18:45:21.766402141Z     data = self._jws.deserialize_compact(s, load_key, decode_payload)
2022-10-04T18:45:21.766633283Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
2022-10-04T18:45:21.766781063Z     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
2022-10-04T18:45:21.766937104Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
2022-10-04T18:45:21.767031434Z     key = key(header, payload)
2022-10-04T18:45:21.767175814Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 171, in load_key
2022-10-04T18:45:21.767225415Z     if k.get('kid') == kid:
2022-10-04T18:45:21.767415425Z AttributeError: 'str' object has no attribute 'get'
2022-10-04T18:45:21.791414533Z 2022-10-04 18:45:21,790 - synapse.access.http.8008 - 459 - INFO - GET-9265 - 50.29.133.7 - 8008 - {None} Processed request: 0.414sec/-0.000sec (0.029sec, 0.011sec) (0.000sec/0.000sec/0) 13500B 400 "GET /_synapse/client/oidc/callback?code=708f848f86f7dc2f89e49602699a1009c7338eb8&state=3l0ZkcYbK4w222JR9ZTXLUTLiY1PGr HTTP/1.0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" [0 dbevts]

```

Also, below are screenshots of my Drupal -> oauth2_server configuration:

Server:
![Screenshot from 2022-10-04 14-50-01](https://user-images.githubusercontent.com/4930859/193901723-6247d84d-f829-4228-8637-86be2cefa30b.png)

Client:
![Screenshot from 2022-10-04 14-50-13](https://user-images.githubusercontent.com/4930859/193901729-a9ed5921-6ef6-4f2e-bcae-120b2ed14190.png)

**Comment by natecovington** [comment]
> What's serving https://dev-lppa-sso.pantheonsite.io/oauth2/certificates and can you try removing the square brackets, so that it returns just `"-----BEGIN CERTIFICATE-----\nMIIDE...TRkU=\n-----END CERTIFICATE-----\n"`?

I created a new repo for the Drupal module, here is the PHP file in question where it generates the BEGIN CERTIFICATE / END CERTIFICATE:
https://github.com/natecovington/drupal_oauth2_server/blob/main/src/Controller/OAuth2Controller.php

Lines 265-281:
```

  /**
   * Certificates.
   *
   * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
   *   The route match object.
   * @param \Symfony\Component\HttpFoundation\Request $request
   *   The request object.
   *
   * @return \Symfony\Component\HttpFoundation\JsonResponse
   *   The response object.
   */
  public function certificates(RouteMatchInterface $route_match, Request $request) {
    $keys = Utility::getKeys();
    $certificates = [];
    $certificates[] = $keys['public_key'];
    return new JsonResponse($certificates);
  }
```
  
  
  
  Lines 299-318:
```
    public function jwk(RouteMatchInterface $route_match, Request $request) {
    $keys = Utility::getKeys();

    $cert = openssl_x509_read($keys['public_key']);
    $publicKey = openssl_get_publickey($cert);
    openssl_x509_free($cert);
    $keyDetails = openssl_pkey_get_details($publicKey);
    openssl_pkey_free($publicKey);
    $jwk['e'] = base64_encode($keyDetails['rsa']['e']);
    $jwk['n'] = base64_encode($keyDetails['rsa']['n']);
    $jwk['mod'] = self::base64urlEncode($keyDetails['rsa']['n']);
    $jwk['exp'] = self::base64urlEncode($keyDetails['rsa']['e']);
    $jwk['x5c'][] = self::base64urlEncode(self::pem2der($keys['public_key']));
    $jwk['kty'] = 'RSA';
    $jwk['use'] = "sig";
    $jwk['alg'] = "RS256";
    $jwk['kid'] = Crypt::hmacbase64(
      \Drupal::state()->get('oauth2_server.next_certificate_id', 0),
      Settings::getHashSalt()
    );
``
    
    Lines 350-368:
```
/**
   * Convert a PEM encoded to DER encoded certificate.
   *
   * @param string $pem
   *   The PEM encoded certificate.
   *
   * @return string|bool
   *   The DER encoded certificate or false.
   *
   * @see http://php.net/manual/en/ref.openssl.php#74188
*/
  public static function pem2der($pem) {
    $begin = "CERTIFICATE-----";
    $end = "-----END";
    $pem = substr($pem, strpos($pem, $begin) + strlen($begin));
    $pem = substr($pem, 0, strpos($pem, $end));
    $der = base64_decode($pem);
    return $der;
  }
```

It looks like we need Drupal to output `/oauth2/certificates ` in JSON format, instead of `$der = base64_decode($pem);` ?

**Comment by squahtx** [comment]
Thanks for digging out the code.

> I'm looking for the part where it specifically adds the `[ ]` brackets in here, I'm not seeing it?

```php
  public function certificates(RouteMatchInterface $route_match, Request $request) {
    $keys = Utility::getKeys();
    $certificates = [];
    $certificates[] = $keys['public_key'];
    return new JsonResponse($certificates);
  }
```
The `/certificates` response is already JSON. Since `$certificates` is an array, that gets turned into `["MII..."]` in the response.

I believe that `/certificates` is the wrong endpoint to be using. `public function jwk(RouteMatchInterface $route_match, Request $request)` appears to output a response in the expected format. Can you try changing `jwks_uri` in the Synapse-side config to `"https://dev-lppa-sso.pantheonsite.io/oauth2/jwk"`?

There's an error in that endpoint that needs fixing first.

**Comment by squahtx** [comment]
Getting the Drupal OAuth2 `/jwk` endpoint working is beyond the scope of what the Synapse team is able to help with unfortunately.

**Comment by natecovington** [comment]
> Getting the Drupal OAuth2 `/jwk` endpoint working is beyond the scope of what the Synapse team is able to help with unfortunately.

I'll keep picking away at this - I really appreciate your help!

**Comment by natecovington** [comment]
I updated the drupal oauth2_server module to "dev" version, that fixed the JWK url:
https://dev-lppa-sso.pantheonsite.io/oauth2/jwk

So in Synapse -> homeserver.yaml, I updated jwks_uri:
`  jwks_uri: "https://dev-lppa-sso.pantheonsite.io/oauth2/jwk"`

That gives a different result now, e.g:
https://matrix.lppamonroe.com/_synapse/client/oidc/callback?code=62b0f6860a80c87fdc7d89a7b043bf7246d05f7d&state=xbW1gddrWnCEap9WHXc7NvOPteWkvU

Invalid JSON Web Key Set
invalid_token


Full error:
```
2022-10-05T15:22:26.939925218Z 2022-10-05 15:22:26,939 - synapse.handlers.oidc - 231 - INFO - GET-10 - Received OIDC callback for IdP oidc-drupal
2022-10-05T15:22:27.246783075Z 2022-10-05 15:22:27,246 - synapse.http.client - 446 - INFO - GET-10 - Received response to POST https://dev-lppa-sso.pantheonsite.io/oauth2/token: 200
2022-10-05T15:22:27.249309823Z 2022-10-05 15:22:27,248 - synapse.handlers.oidc - 706 - INFO - GET-10 - Reloading JWKS after decode error
2022-10-05T15:22:27.331214240Z 2022-10-05 15:22:27,330 - synapse.http.client - 446 - INFO - GET-10 - Received response to GET https://dev-lppa-sso.pantheonsite.io/oauth2/jwk: 200
2022-10-05T15:22:27.384264636Z 2022-10-05 15:22:27,333 - synapse.handlers.oidc - 843 - ERROR - GET-10 - Invalid id_token
2022-10-05T15:22:27.384347157Z Traceback (most recent call last):
2022-10-05T15:22:27.384354797Z   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 698, in _parse_id_token
2022-10-05T15:22:27.384360797Z     claims = jwt.decode(
2022-10-05T15:22:27.384366107Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
2022-10-05T15:22:27.384371457Z     data = self._jws.deserialize_compact(s, load_key, decode_payload)
2022-10-05T15:22:27.384376387Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
2022-10-05T15:22:27.384381407Z     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
2022-10-05T15:22:27.384386467Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
2022-10-05T15:22:27.384445887Z     key = key(header, payload)
2022-10-05T15:22:27.384451867Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 173, in load_key
2022-10-05T15:22:27.384458377Z     raise ValueError('Invalid JSON Web Key Set')
2022-10-05T15:22:27.384463417Z ValueError: Invalid JSON Web Key Set
2022-10-05T15:22:27.384467817Z 
2022-10-05T15:22:27.384472057Z During handling of the above exception, another exception occurred:
2022-10-05T15:22:27.384498617Z 
2022-10-05T15:22:27.384543668Z Traceback (most recent call last):
2022-10-05T15:22:27.384548808Z   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 840, in handle_oidc_callback
2022-10-05T15:22:27.384553608Z     id_token = await self._parse_id_token(token, nonce=session_data.nonce)
2022-10-05T15:22:27.384579908Z   File "/usr/local/lib/python3.9/site-packages/synapse/handlers/oidc.py", line 708, in _parse_id_token
2022-10-05T15:22:27.384585638Z     claims = jwt.decode(
2022-10-05T15:22:27.384590038Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 96, in decode
2022-10-05T15:22:27.384594798Z     data = self._jws.deserialize_compact(s, load_key, decode_payload)
2022-10-05T15:22:27.384599308Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 101, in deserialize_compact
2022-10-05T15:22:27.384604278Z     algorithm, key = self._prepare_algorithm_key(jws_header, payload, key)
2022-10-05T15:22:27.384608898Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7515/jws.py", line 254, in _prepare_algorithm_key
2022-10-05T15:22:27.384614178Z     key = key(header, payload)
2022-10-05T15:22:27.384618788Z   File "/usr/local/lib/python3.9/site-packages/authlib/jose/rfc7519/jwt.py", line 173, in load_key
2022-10-05T15:22:27.384624098Z     raise ValueError('Invalid JSON Web Key Set')
2022-10-05T15:22:27.384628878Z ValueError: Invalid JSON Web Key Set
2022-10-05T15:22:27.387096266Z 2022-10-05 15:22:27,386 - synapse.access.http.8008 - 459 - INFO - GET-10 - REDACTED:MY:IP - 8008 - {None} Processed request: 0.449sec/-0.000sec (0.025sec, 0.000sec) (0.000sec/0.000sec/0) 13473B 400 "GET /_synapse/client/oidc/callback?code=62b0f6860a80c87fdc7d89a7b043bf7246d05f7d&state=xbW1gddrWnCEap9WHXc7NvOPteWkvU HTTP/1.0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" [0 dbevts]
```

**Comment by squahtx** [comment]
That'll be because the JWT has a missing or mismatching `kid` (key ID) field.
which corresponds to this issue you've found https://www.drupal.org/project/oauth2_server/issues/2288237, which is blocked on https://github.com/bshaffer/oauth2-server-php/issues/363 upstream.

Can you modify the `/jwk` endpoint as follows and see what happens?
```diff
-     $response = ["keys" => [$jwk]];
-     ...
-     return new JsonResponse($response, 200);
+     return new JsonResponse($jwk, 200);
```

**Comment by natecovington** [comment]
That worked!!!  I updated the github project accordingly:
https://github.com/natecovington/drupal_oauth2_server/blob/main/src/Controller/OAuth2Controller.php

However, it's logging me into Synapse and saying this:
Welcome {{ user.name }}

Display name:
{{ user.name }}

Full name:
@=7b=7b=20user.preferred_username=20=7d=7d:matrix.lppamonroe.com

Any pointers for this?

**Comment by natecovington** [comment]
I wanted to document some more hints I found, do I need to add something like `subject_claim: "id"` to my `user_mapping_provider`?

Another tip, it looks like the NextCloud OIDC integration uses some sort of custom python module:
https://github.com/matrix-org/synapse/issues/8511#issuecomment-720526849

They reference it like this:
```
     user_mapping_provider:
       module: nextcloud_oicd_mapping_provider.NextcloudOidcMappingProvider
       config: {}
```

I also found a reference in Oauth2Storage.php
https://github.com/natecovington/drupal_oauth2_server/blob/a44bdac3b9eed8ac6d2661b9e1e119d3731d5dc5/src/OAuth2Storage.php

```
if (in_array('profile', $requested_scopes)) {
      if (!empty($account->label())) {
        $claims['name'] = $account->getDisplayName();
        $claims['preferred_username'] = $account->getAccountName();
      }
```

It looks like "name" and "preferred_username" are already being passed by the oauth2_server module.  It feels like everything is here, I just need the right Synapse configuration...
