### ISSUE TITLE
Test Synapse against Python 3.11 in CI

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#13790]
CPython [3.11.0rc2](https://www.python.org/downloads/release/python-3110rc2/) was released yesterday. A final release is scheduled for 2022-10-24.

We support all upstream-supported versions of CPython, so at some point we'll want to include 3.11 in CI. It would be good to do this ahead of a release if possible.

- [x] Run trial tests against 3.11 in CI
  - #13812 
- [ ] Run sytest against 3.11 in CI
- AFAIK Sytest is only testing against the Python versions that happen to come with the Debian/ubuntu distros we test against. Currently there is no distro shipping 3.11 ([debian](https://packages.debian.org/search?keywords=python3&searchon=names&exact=1&suite=all&section=all), [ubuntu](https://packages.ubuntu.com/search?keywords=python3))
- [ ] Run complement against 3.11 in CI
  - Tests against whatever's in the docker image---currently 3.9.

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/pull/13812 had a go at this. `poetry install` failed:

<details>

```
Processing /home/runner/.cache/pypoetry/artifacts/34/4b/97/827f011ee5f21eaf8dc466228cf827c4a447b1721d25442bfc9bb48a7a/wrapt-1.13.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [89 lines of output]
        Traceback (most recent call last):
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 81, in __getattr__
            return next(
                   ^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 82, in <genexpr>
            ast.literal_eval(value)
          File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ast.py", line 108, in literal_eval
            return _convert(node_or_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ast.py", line 107, in _convert
            return _convert_signed_num(node)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ast.py", line 81, in _convert_signed_num
            return _convert_num(node)
                   ^^^^^^^^^^^^^^^^^^
          File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ast.py", line 72, in _convert_num
            _raise_malformed_node(node)
          File "/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/ast.py", line 69, in _raise_malformed_node
            raise ValueError(msg + f': {node!r}')
        ValueError: malformed node or string on line 2: <ast.Call object at 0x7f77e4975870>
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 191, in read_attr
            return getattr(StaticModule(module_name, spec), attr_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 87, in __getattr__
            raise AttributeError(f"{self.name} has no attribute {attr}") from e
        AttributeError: wrapt has no attribute __version__
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/tmp/tmpyq44clqd_in_process.py", line 363, in <module>
            main()
          File "/tmp/tmpyq44clqd_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/tmpyq44clqd_in_process.py", line 164, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 483, in run_setup
            self).run_setup(setup_script=setup_script)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 41, in <module>
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
            dist.parse_config_files()
          File "/home/runner/.cache/pypoetry/virtualenvs/matrix-synapse-pswDeSvb-py3.11/lib/python3.11/site-packages/_virtualenv.py", line 21, in parse_config_files
            result = old_parse_config_files(self, *args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 864, in parse_config_files
            setupcfg.parse_configuration(
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
            meta.parse()
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 496, in parse
            section_parser_method(section_options)
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 470, in parse_section
            self[name] = value
            ~~~~^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 278, in __setitem__
            value = parser(value)
                    ^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 602, in _parse_version
            return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py", line 412, in _parse_attr
            return expand.read_attr(attr_desc, package_dir, root_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 194, in read_attr
            module = _load_spec(spec, module_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/tmp/pip-build-env-8sia0pm3/overlay/lib/python3.11/site-packages/setuptools/config/expand.py", line 214, in _load_spec
            spec.loader.exec_module(module)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "<frozen importlib._bootstrap_external>", line 940, in exec_module
          File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
          File "/tmp/pip-req-build-zfjpovd6/src/wrapt/__init__.py", line 10, in <module>
            from .decorators import (adapter_factory, AdapterFactory, decorator,
          File "/tmp/pip-req-build-zfjpovd6/src/wrapt/decorators.py", line 34, in <module>
            from inspect import ismethod, isclass, formatargspec
        ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.0-rc.2/x64/lib/python3.11/inspect.py)
        [end of output]
```
</details>

Guessing that wrapt 1.13.3 isn't 3.11-compatible?

**Comment by DMRobertson** [comment]
https://github.com/GrahamDumpleton/wrapt/issues/196

**Comment by DMRobertson** [comment]
There are test failures to handle, see https://github.com/matrix-org/synapse/pull/13812#issuecomment-1247070601

**Comment by DMRobertson** [comment]
My current understanding is that we are blocked waiting on a release of `automat` ([1](https://github.com/glyph/automat/issues/139#issuecomment-1273146975), [2](https://github.com/glyph/automat/pull/138), [3](https://github.com/twisted/twisted/pull/1723#issuecomment-1107654772)).

**Comment by DMRobertson** [comment]
SITREP: CI looks like it should be happy

- [x] with a sufficiently new twisted, Pillow and wrapt,
- [x] a minor fix to one unit test, and
- [ ] a new automat release (https://github.com/twisted/twisted/issues/10343)

**Comment by DMRobertson** [comment]
From triage: this is good enough as it is.
