### ISSUE TITLE
Complement `TestPartialStateJoin/joined_members_blocks_during_partial_state_join` is flakey

### ISSUE THREAD

**Issue by squahtx** [matrix-org/synapse#13989]
eg. https://github.com/matrix-org/synapse/actions/runs/3155155132/jobs/5133560136

```
TestPartialStateJoin/joined_members_blocks_during_partial_state_join (0s)
      client.go:604: [CSAPI] POST hs1/_matrix/client/v3/register => 200 OK (34.412248ms)
      client.go:604: [CSAPI] GET hs1/_matrix/client/v3/capabilities => 200 OK (5.248592ms)
      server.go:165: Creating room !0:host.docker.internal:37051 with version 9
      federation_room_join_partial_state_test.go:2697: Registered state_ids handler for event $4tSrit43m-GqqgoYz3efGvu-a8fHY7f_vQ_qra0V6iE
      federation_room_join_partial_state_test.go:2738: Registered /state handler for event $4tSrit43m-GqqgoYz3efGvu-a8fHY7f_vQ_qra0V6iE
      client.go:604: [CSAPI] POST hs1/_matrix/client/v3/join/!0:host.docker.internal:37051 => 200 OK (43.623833ms)
      federation_room_join_partial_state_test.go:2610: /join request completed
      client.go:604: [CSAPI] GET hs1/_matrix/client/v3/rooms/!0:host.docker.internal:37051/joined_members => 200 OK (11.792982ms)
      federation_room_join_partial_state_test.go:2652: Waiting for /state_ids request: timed out after 5.000000 seconds.
  panic: send on closed channel
  
  goroutine 3280 [running]:
  github.com/matrix-org/complement/tests.TestPartialStateJoin.func28.1()
  	/home/runner/work/synapse/synapse/complement/tests/federation_room_join_partial_state_test.go:1340 +0x12b
  created by github.com/matrix-org/complement/tests.TestPartialStateJoin.func28
  	/home/runner/work/synapse/synapse/complement/tests/federation_room_join_partial_state_test.go:1338 +0x27d
```

**Comment by squahtx** [comment]
The room ID `!0:host.docker.internal:37051` appears to be reused across tests, with the same Synapse deployment.

For now, let's assume that this has the same cause as https://github.com/matrix-org/synapse/issues/13975.
