### ISSUE TITLE
Run Sytest and Complement with the Twisted asyncioreactor enabled in CI

### ISSUE THREAD

**Issue by sandhose** [matrix-org/synapse#14091]
I'd like to start running the test suites with the asyncioreactor enabled to see what breaks. This issue tracks the changes in Synapse, Sytest and Complement to achieve this.

Related: #8642, #12135

**Comment by realtyem** [comment]
Not sure if it's welcome(or relevant) but when I enable this and SYNAPSE_USE_EXPERIMENTAL_FORKING_LAUNCHER at the same time, I get this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/synapse/app/complement_fork_starter.py", line 218, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/synapse/app/complement_fork_starter.py", line 152, in main
    installReactor(proxy_reactor)
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/main.py", line 32, in installReactor
    raise error.ReactorAlreadyInstalledError("reactor already installed")
twisted.internet.error.ReactorAlreadyInstalledError: reactor already installed
```

**Comment by DMRobertson** [comment]
This is both welcome and relevant. It needs discussing on #14099.
