### ISSUE TITLE
Strange behavior from Event Persistent sharded workers in Dockerfile-workers.

### ISSUE THREAD

**Issue by realtyem** [matrix-org/synapse#14238]
### Description

I noticed unusual activity from my two sharded `event_persister`'s a few days ago. `Event_persister1` seems to have no activity, while `event_persister2` seems to be doing whatever it's supposed to be doing. 

What I'm not sure of is if this is behavior stemming from having an existing active database, or if it wouldn't happen with a fresh database? Would it therefore be expected behavior.

If it matters, the workers I usually have declared:
```
account_data, 
background_worker, 
client_reader, 
client_reader, 
event_creator, 
event_persister, 
event_persister, 
federation_inbound, 
federation_reader, 
federation_reader, 
federation_sender, 
federation_sender, 
federation_sender, 
frontend_proxy, 
media_repository, 
presence, 
pusher, 
pusher, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
synchrotron, 
to_device, 
typing, 
user_dir
```

But for the purposes of this issue, I removed all of them except the two `event_persisters` to cut down on excessive log spam. The issue remained.

I'm putting the logs into a comment below this issue, as they are quite large(especially `event_persister2`).

### Steps to reproduce

- Have an existing database with several rooms and be federated with matrix.org.
- Use Dockerfile-workers to create the synapse container. Make sure it's collecting metrics however required.
- Declare `WORKER_TYPES="event_persister, event_persister"` in the environment passed into the `docker run` command to start the container.
- Observe CPU and other values showing one `event_persister` having activity while the other is idle.

### Homeserver

Mine

### Synapse Version

{"server_version":"1.69.0","python_version":"3.10.8"}

### Installation Method

Other (please mention below)

### Platform

Distro: unRAID
Hardware: dual Intel® Xeon® CPU E5-2651 v2, 128Gb Ram

Synapse Dockerfile-workers as the base for my custom Dockerfile setup where I run with about 30 workers. While it is customized, the only things I changed were in `configure_workers_and_start.py` and the Dockerfile itself.

### Relevant log output

```shell
See below for attached files.
```

### Anything else that would be useful to know?

The instance and logs were started over at DEBUG at 19:34:00. No unusual activity until 19:40:45. Then event_persister2 spiked in activity and the logs grew by almost 2 Megabytes in size. Nearly nothing happened at the same time(or afterwards) in event_persister1. I terminated instance to grab the logs at 19:56:00 or just after.

**Comment by realtyem** [comment]
Would a `psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete` causing the `event_persister2` to restart mean that they fell out of sync? As I remember correctly, they have to be stopped and started together. Would that cause this?

**Comment by H-Shay** [comment]
I'm a little unclear on what the issue is here. Are you experiencing a performance degradation as a end user or what exactly is the suspected problem?

**Comment by realtyem** [comment]
> I'm a little unclear on what the issue is here. Are you experiencing a performance degradation as a end user or what exactly is the suspected problem?

I think it might be because of my last comment. I'm not an expert on interpreting these things, but if _feels_ like it was caused by a database locking race. Event persister1 log wasn't particularly exciting(since nothing ever seems to happen) but there is an exception occurs at line 47 in event_persister2.log. I snipped it out:
```log
2022-10-19 19:34:04,971 - synapse.storage.util.id_generators - 88 - INFO - main - Initialising stream generator for pushers(id): 616
2022-10-19 19:34:04,972 - synapse.storage.util.id_generators - 88 - INFO - main - Initialising stream generator for deleted_pushers(stream_id): 310
2022-10-19 19:34:04,974 - synapse.storage.util.id_generators - 88 - INFO - main - Initialising stream generator for push_rules_stream(stream_id): 150
2022-10-19 19:34:04,981 - synapse.storage.util.id_generators - 88 - INFO - main - Initialising stream generator for pushers(id): 616
2022-10-19 19:34:04,982 - synapse.storage.util.id_generators - 88 - INFO - main - Initialising stream generator for deleted_pushers(stream_id): 310
2022-10-19 19:34:05,127 - synapse.app._base - 205 - ERROR - main - Exception during startup
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/synapse/app/generic_worker.py", line 472, in start
    hs.setup()
  File "/usr/local/lib/python3.10/site-packages/synapse/server.py", line 309, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/__init__.py", line 93, in __init__
    main = main_store_class(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/user_directory.py", line 618, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/user_directory.py", line 70, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/stats.py", line 109, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/presence.py", line 67, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/presence.py", line 48, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/deviceinbox.py", line 63, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/replication/slave/storage/devices.py", line 46, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/devices.py", line 81, in __init__
    super().__init__(database, db_conn, hs)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/databases/main/account_data.py", line 77, in __init__
    self._account_data_id_gen = MultiWriterIdGenerator(
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/util/id_generators.py", line 368, in __init__
    self._load_current_ids(db_conn, tables)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/util/id_generators.py", line 393, in _load_current_ids
    cur.execute(sql, (self._stream_name, self._writers))
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/database.py", line 388, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/usr/local/lib/python3.10/site-packages/synapse/storage/database.py", line 436, in _do_execute
    return func(sql, *args, **kwargs)
psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete

2022-10-19 19:34:08,902 - root - 345 - WARNING - main - ***** STARTING SERVER *****
```
Then it looks like it restarts, I guess as a process? Since at that point they are no longer in sync, event_persister2 takes over and thinks it's the only one so it does all the work. I think.

**Comment by realtyem** [comment]
Looks like this.

![Screenshot (3)](https://user-images.githubusercontent.com/1582365/197275825-94974c4c-b4e5-40d8-b5ea-cea26f9f46ae.png)

**Comment by realtyem** [comment]
> Would a `psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete` causing the `event_persister2` to restart mean that they fell out of sync? As I remember correctly, they have to be stopped and started together. Would that cause this?

https://matrix-org.github.io/synapse/latest/workers.html#the-events-stream is where I got that info about having to be stopped and started together.

**Comment by realtyem** [comment]
I think I follow you. I'm still experiencing this behavior though, even after several restarts. Just now I checked the size of the log files, `event_persister1` is about 53Mb and `event_persister2` is 2.9Gb. This is just since midnight(they rotate once a day) and it's currently 3:15pm for me.

**Comment by reivilibre** [comment]
Talked out of band and came to the conclusion that the large rooms @realtyem is in coincidentally mapped onto the same event persister, because the sha256 of their room IDs all had the same oddness. We did eventually find a room that mapped to the other event persister.

It could be argued that we could balance rooms in a smarter way than by sha256 or perhaps let the admin tweak a seed to rebalance a few times until they were happy with the balance, but on larger servers this should not matter because `sha256(room IDs)` should be uniformly distributed and in aggregate they will balance out.
