### ISSUE TITLE
Outbound federation broken on Python 3.7

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#14267]
When there should be outbound federation traffic:

```
2022-10-21 23:33:28,436 - synapse.metrics.background_process_metrics - 244 - ERROR - process_event_queue_for_federation-6 - Background process 'process_event_queue_for_federation' threw an exception
...
Traceback (most recent call last):
  File "/home/synapse/src/synapse/synapse/metrics/background_process_metrics.py", line 240, in run
    return await func(*args, **kwargs)
  File "/home/synapse/src/synapse/synapse/federation/sender/__init__.py", line 539, in _process_event_queue_loop
    last_id = next(reversed(event_ids))
TypeError: 'dict_keys' object is not reversible
```

Turns out that `dict.keys` is, as the error says, not reversible on Python 3.7.

I think this was introduced by #13813 (and I think it was my rubbish suggestion).

**Comment by babolivier** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/14280

**Comment by DMRobertson** [comment]
@richvdh how did you notice this? (c.f.  #14281)

**Comment by richvdh** [comment]
I attempted to upgrade Synapse on my personal homeserver, which runs python 3.7, and noticed the errors in the log.

Having looked more closely at the logs, it seems that there were at least *some* `/send` requests going out, so it seems the situation is a bit more complicated than "outbound federation is broken".
