### ISSUE TITLE
Can't read SSL Certificate private key inside docker container

### ISSUE THREAD

**Issue by TafkaMax** [matrix-org/synapse#14288]
# Getting the Cert

I get my cert with certbot -> save it to /etc/letsencrypt. It gets the 0640 treatment and ```chown root:ssl-cert``` with a post-hook.

Create symlink to /etc/ssl/certs and /etc/ssl/private (644 and 640) respectivaly.

I mount them to /etc/ssl/cert and /etc/ssl/private inside the synapse docker container.

I create a matrix user to /opt/matrix (home dir). I launch the Docker container per instructions with $UID and $GID pointing to host machine matrix user so when i mount /opt/matrix/synapse to /data it has the same permissions to RW. 

Now when I launch the container it cant read the /etc/ssl/private/key.pem when I specify it under the homeserver.yaml (permission denied)

When I launch the docker container and go inside the container I can see it with root, ofcousre. But then I find out that /etc/passwd and /etc/group does not contain the UID and GID I have created and launched the docker container with. 

How can I make the privatekey readable without 0644?

**Comment by reivilibre** [comment]
> But then I find out that /etc/passwd and /etc/group does not contain the UID and GID I have created and launched the docker container with.

I think this is normal: you don't need an entry in there in order to be able to use the UID or GID, the user and group just won't have a name.

What do you see if you look at the owner, group and permissions of the files with e.g.

```
ls -lah /etc/ssl/{certs,private}
```
(from within the container)?

What UID and GID are you using?

**Comment by Sid127** [comment]
I'm not OP, but here's what I have for `ls -lah` on my certs
```lrwxrwxrwx 1 root root 50 Nov 25 10:57 certs/cert.pem -> /etc/letsencrypt/live/my.domain/cert.pem
lrwxrwxrwx 1 root root 51 Nov 25 10:57 certs/chain.pem -> /etc/letsencrypt/live/my.domain/chain.pem
lrwxrwxrwx 1 root root 55 Nov 25 10:57 certs/fullchain.pem -> /etc/letsencrypt/live/my.domain/fullchain.pem
lrwxrwxrwx 1 root root 53 Nov 25 10:57 certs/privkey.pem -> /etc/letsencrypt/live/my.domain/privkey.pem
lrwxrwxrwx 1 root root 48 Nov 25 10:57 certs/README -> /etc/letsencrypt/live/my.domain/README```

docker is also running as root.

I'm following the instructions as seen [here](https://hub.docker.com/r/matrixdotorg/synapse)

**Comment by Sid127** [comment]
Not op, but here's my output for `ls -lah`
```
[root@archlinux _data]# ls -lah certs
total 8.0K
drwxr-xr-x 2 root    root    4.0K Nov 25 11:02 .
drwxr-xr-x 4 botuser botuser 4.0K Nov 25 11:25 ..
lrwxrwxrwx 1 root    root      50 Nov 25 10:57 cert.pem -> /etc/letsencrypt/live/chat.sloughland.dev/cert.pem
lrwxrwxrwx 1 root    root      51 Nov 25 10:57 chain.pem -> /etc/letsencrypt/live/chat.sloughland.dev/chain.pem
lrwxrwxrwx 1 root    root      55 Nov 25 10:57 fullchain.pem -> /etc/letsencrypt/live/chat.sloughland.dev/fullchain.pem
lrwxrwxrwx 1 root    root      53 Nov 25 10:57 privkey.pem -> /etc/letsencrypt/live/chat.sloughland.dev/privkey.pem
lrwxrwxrwx 1 root    root      48 Nov 25 10:57 README -> /etc/letsencrypt/live/chat.sloughland.dev/README
```

tried with both default UID and GID (991), as well as 1000, just for the sake of testing.

Here's the output of `docker logs synapse`
```2022-11-25 11:28:57,041 - synapse.app.homeserver - 167 - INFO - sentinel - Running
2022-11-25 11:28:57,044 - synapse.app.homeserver - 29 - INFO - sentinel - Set file limit to: 1048576
2022-11-25 11:28:57,047 - synapse.handlers.deactivate_account - 230 - INFO - user_parter_loop-0 - Starting user parter
2022-11-25 11:28:57,061 - synapse.config.tls - 185 - INFO - sentinel - Loading TLS key from /data/certs/privkey.pem
2022-11-25 11:28:57,062 - synapse.app._base - 257 - CRITICAL - sentinel - Error during startup
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 992, in read_file
    os.stat(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/certs/privkey.pem'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 242, in wrapper
    await cb(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 352, in start
    await _base.start(hs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 530, in start
    refresh_certificate(hs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 448, in refresh_certificate
    hs.config.tls.read_certificate_from_disk()
  File "/usr/local/lib/python3.9/site-packages/synapse/config/tls.py", line 140, in read_certificate_from_disk
    self.tls_private_key = self.read_tls_private_key()
  File "/usr/local/lib/python3.9/site-packages/synapse/config/tls.py", line 186, in read_tls_private_key
    private_key_pem = self.read_file(private_key_path, "tls_private_key_path")
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 250, in read_file
    return read_file(file_path, (config_name,))
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 996, in read_file
    raise ConfigError("Error accessing file %r" % (file_path,), config_path) from e
synapse.config._base.ConfigError: ("Error accessing file '/data/certs/privkey.pem'", ('tls_private_key_path',))
Error during startup:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 992, in read_file
    os.stat(file_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/certs/privkey.pem'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 242, in wrapper
    await cb(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 352, in start
    await _base.start(hs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 530, in start
    refresh_certificate(hs)
  File "/usr/local/lib/python3.9/site-packages/synapse/app/_base.py", line 448, in refresh_certificate
    hs.config.tls.read_certificate_from_disk()
  File "/usr/local/lib/python3.9/site-packages/synapse/config/tls.py", line 140, in read_certificate_from_disk
    self.tls_private_key = self.read_tls_private_key()
  File "/usr/local/lib/python3.9/site-packages/synapse/config/tls.py", line 186, in read_tls_private_key
    private_key_pem = self.read_file(private_key_path, "tls_private_key_path")
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 250, in read_file
    return read_file(file_path, (config_name,))
  File "/usr/local/lib/python3.9/site-packages/synapse/config/_base.py", line 996, in read_file
    raise ConfigError("Error accessing file %r" % (file_path,), config_path) from e
synapse.config._base.ConfigError: ("Error accessing file '/data/certs/privkey.pem'", ('tls_private_key_path',))
```

**Comment by H-Shay** [comment]
Is this still a problem?

**Comment by TafkaMax** [comment]
Hi, inside the container:
```bash
ls -lah /etc/ssl/certs/
-rw-r--r-- 1 1000 1000 6.8K Dec  9 09:03  matrix.domain.pem

ls -lah /etc/ssl/private/
-rw-r----- 1 1000 1000 3.2K Dec  9 09:03 matrix.domain.pem
```

**Comment by TafkaMax** [comment]
Currently I have set env variables for synapse container:

```
UID=1000
GID=1000
```

**Comment by reivilibre** [comment]
I don't think env variables will work to set the user of the container. Try using the `--user` parameter to Docker instead, `--user 1000:1000` (`1000:1000` will set both uid and gid).

```
rei@lithium ~$ docker run --rm -it --entrypoint bash -e UID=4242 matrixdotorg/synapse
root@2690c59ccb87:/# id
uid=0(root) gid=0(root) groups=0(root)
root@2690c59ccb87:/# 
exit

took 22s rei@lithium ~$ docker run --rm -it --entrypoint bash --user 4242 matrixdotorg/synapse
I have no name!@e761b41f1334:/$ id
uid=4242 gid=0(root) groups=0(root)
I have no name!@e761b41f1334:/$ 
```

**Comment by H-Shay** [comment]
Did above comment help, or is this issue persisting?

**Comment by DMRobertson** [comment]
Going to assume this was sorted out in the end. If not, @TafkaMax please re-open and keep us updated.
