### ISSUE TITLE
Failing migrations after update

### ISSUE THREAD

**Issue by soupdiver** [matrix-org/synapse#14423]
### Description

I regualry pull the latest image of synapse. I did this recently but my server won't come up again.
It seems there are a bunch of related issues regarding db migrations recently. It seems I'm affected by this too but could not find my specific error here.

Coming from https://github.com/matrix-org/synapse/issues/13193#issuecomment-1191847014 I already tried to execute the command manually but it seems I have somewhat corrupted data.

### Steps to reproduce

start synapse (in Docker container)

### Homeserver

private homeserver

### Synapse Version

latest

### Installation Method

Docker (matrixdotorg/synapse)

### Platform

Linux

### Relevant log output

```shell
update_synapse_database --database-config /data/homeserver.yaml
2022-11-13 09:50:20,903 - synapse.config.key - 169 - WARNING - Config is missing macaroon_secret_key
2022-11-13 09:50:20,935 - synapse.server - 307 - INFO - Setting up.
2022-11-13 09:50:20,937 - synapse.storage.databases - 66 - INFO - [database config 'master']: Checking database server
2022-11-13 09:50:20,937 - synapse.storage.databases - 69 - INFO - [database config 'master']: Preparing for databases ['main', 'state']
2022-11-13 09:50:20,937 - synapse.storage.prepare_database - 115 - INFO - ['main', 'state']: Checking existing schema version
2022-11-13 09:50:20,938 - synapse.storage.prepare_database - 119 - INFO - ['main', 'state']: Existing schema is 73 (+11 deltas)
2022-11-13 09:50:20,938 - synapse.storage.databases.main - 320 - INFO - Checking database for consistency with configuration...
2022-11-13 09:50:20,938 - synapse.storage.prepare_database - 411 - INFO - Applying schema deltas for v73
2022-11-13 09:50:20,939 - synapse.storage.prepare_database - 519 - INFO - Applying schema 73/09threads_table.sql
Traceback (most recent call last):
  File "/usr/local/bin/update_synapse_database", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/synapse/_scripts/update_synapse_database.py", line 110, in main
    hs.setup()
  File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 309, in setup
    self.datastores = Databases(self.DATASTORE_CLASS, self)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 74, in __init__
    prepare_database(
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 136, in prepare_database
    _upgrade_existing_database(
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/prepare_database.py", line 520, in _upgrade_existing_database
    database_engine.execute_script_file(cur, absolute_path)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/engines/_base.py", line 145, in execute_script_file
    cls.executescript(cursor, f.read())
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/engines/sqlite.py", line 144, in executescript
    cursor.executescript(script)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/database.py", line 395, in executescript
    self._do_execute(self.txn.executescript, sql)  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/database.py", line 436, in _do_execute
    return func(sql, *args, **kwargs)
sqlite3.IntegrityError: UNIQUE constraint failed: background_updates.update_name
```

**Comment by DMRobertson** [comment]
Presumably this INSERT failed: https://github.com/matrix-org/synapse/blob/3bbe532abb7bfc41467597731ac1a18c0331f539/synapse/storage/schema/main/delta/73/09threads_table.sql#L29-L30 

from https://github.com/matrix-org/synapse/blob/0a38c7ec6d46b6e51bfa53ff44e51637d3c63f5c/synapse/storage/prepare_database.py#L519-L520

But it's odd that we retry applying the delta. Did we not hit this?

https://github.com/matrix-org/synapse/blob/0a38c7ec6d46b6e51bfa53ff44e51637d3c63f5c/synapse/storage/prepare_database.py#L540-L544

Can you share the result of the following queries?

```sql
SELECT * from background_updates;
SELECT * from applied_schema_deltas;
```

**Comment by soupdiver** [comment]
```
SELECT * from background_updates;
event_push_actions_thread_id_null|{}|event_push_backfill_thread_id|7306
event_push_summary_thread_id_null|{}|event_push_backfill_thread_id|7306
receipts_linearized_unique_index|{}||7308
receipts_graph_unique_index|{}||7308
threads_backfill|{}||7309
```

and

```
SELECT * from applied_schema_deltas;
55|55/access_token_expiry.sql
55|55/track_threepid_validations.sql
55|55/users_alter_deactivated.sql
56|56/add_spans_to_device_lists.sql
56|56/current_state_events_membership.sql
56|56/current_state_events_membership_mk2.sql
56|56/delete_keys_from_deleted_backups.sql
56|56/destinations_failure_ts.sql
56|56/device_stream_id_insert.sql
56|56/devices_last_seen.sql
56|56/drop_unused_event_tables.sql
56|56/event_expiry.sql
56|56/event_labels.sql
56|56/event_labels_background_update.sql
56|56/fix_room_keys_index.sql
56|56/hidden_devices.sql
56|56/hidden_devices_fix.sql.sqlite
56|56/nuke_empty_communities_from_db.sql
56|56/public_room_list_idx.sql
56|56/redaction_censor.sql
56|56/redaction_censor2.sql
56|56/redaction_censor4.sql
56|56/remove_tombstoned_rooms_from_directory.sql
56|56/room_key_etag.sql
56|56/room_membership_idx.sql
56|56/room_retention.sql
56|56/signing_keys.sql
56|56/signing_keys_nonunique_signatures.sql
56|56/state_group_room_idx.sql
56|56/stats_separated.sql
56|56/unique_user_filter_index.py
56|56/user_external_ids.sql
56|56/users_in_public_rooms_idx.sql
57|57/delete_old_current_state_events.sql
57|57/device_list_remote_cache_stale.sql
57|57/local_current_membership.py
57|57/remove_sent_outbound_pokes.sql
57|57/rooms_version_column.sql
57|57/rooms_version_column_2.sql.sqlite
57|57/rooms_version_column_3.sql.sqlite
58|58/00background_update_ordering.sql
58|58/02remove_dup_outbound_pokes.sql
58|58/03persist_ui_auth.sql
58|58/06dlols_unique_idx.py
58|58/07add_method_to_thumbnail_constraint.sql.sqlite
58|58/07persist_ui_auth_ips.sql
58|58/08_media_safe_from_quarantine.sql.sqlite
58|58/09shadow_ban.sql
58|58/10_pushrules_enabled_delete_obsolete.sql
58|58/10drop_local_rejections_stream.sql
58|58/10federation_pos_instance_name.sql
58|58/11dehydration.sql
58|58/11fallback.sql
58|58/11user_id_seq.py
58|58/12room_stats.sql
58|58/13remove_presence_allow_inbound.sql
58|58/14events_instance_name.sql
58|58/15_catchup_destination_rooms.sql
58|58/15unread_count.sql
58|58/16populate_stats_process_rooms_fix.sql
58|58/17_catchup_last_successful.sql
58|58/18stream_positions.sql
58|58/19txn_id.sql
58|58/20instance_name_event_tables.sql
58|58/20user_daily_visits.sql
58|58/21as_device_stream.sql
58|58/21drop_device_max_stream_id.sql
58|58/22puppet_token.sql
58|58/22users_have_local_media.sql
58|58/23e2e_cross_signing_keys_idx.sql
58|58/24drop_event_json_index.sql
58|58/25user_external_ids_user_id_idx.sql
58|58/26access_token_last_validated.sql
58|58/27local_invites.sql
58|58/28drop_last_used_column.sql.sqlite
59|59/01ignored_user.py
59|59/02shard_send_to_device.sql
59|59/04_event_auth_chains.sql
59|59/04drop_account_data.sql
59|59/05cache_invalidation.sql
59|59/06chain_cover_index.sql
59|59/06shard_account_data.sql
59|59/07shard_account_data_fix.sql
59|59/08delete_pushers_for_deactivated_accounts.sql
59|59/08delete_stale_pushers.sql
59|59/09rejected_events_metadata.sql
59|59/10delete_purged_chain_cover.sql
59|59/11add_knock_members_to_stats.sql
59|59/12account_validity_token_used_ts_ms.sql
59|59/12presence_stream_instance.sql
59|59/13users_to_send_full_presence_to.sql
59|59/14refresh_tokens.sql
59|59/15locks.sql
59|59/16federation_inbound_staging.sql
61|61/01insertion_event_lookups.sql
61|61/02drop_redundant_room_depth_index.sql
61|61/03recreate_min_depth.py
62|62/01insertion_event_extremities.sql
63|63/01create_registration_tokens.sql
63|63/02delete_unlinked_email_pushers.sql
63|63/02populate-rooms-creator.sql
63|63/03session_store.sql
63|63/04add_presence_stream_not_offline_index.sql
64|64/01msc2716_chunk_to_batch_rename.sql.sqlite
65|65/01msc2716_insertion_event_edges.sql
65|65/02_thread_relations.sql
65|65/03remove_hidden_devices_from_device_inbox.sql
65|65/04_local_group_updates.sql
65|65/05_remove_room_stats_historical_and_user_stats_historical.sql
65|65/06remove_deleted_devices_from_device_inbox.sql
65|65/07_arbitrary_relations.sql
65|65/08_device_inbox_background_updates.sql
65|65/10_expirable_refresh_tokens.sql
65|65/11_devices_auth_provider_session.sql
67|67/01drop_public_room_list_stream.sql
68|68/01event_columns.sql
68|68/02_msc2409_add_device_id_appservice_stream_type.sql
68|68/03_delete_account_data_for_deactivated_accounts.sql
68|68/04_refresh_tokens_index_next_token_id.sql
68|68/04partial_state_rooms.sql
68|68/05_delete_non_strings_from_event_search.sql.sqlite
68|68/05partial_state_rooms_triggers.py
68|68/06_msc3202_add_device_list_appservice_stream_type.sql
69|69/01as_txn_seq.py
69|69/01device_list_oubound_by_room.sql
69|69/02cache_invalidation_index.sql
70|70/01clean_table_purged_rooms.sql
70|70/08_state_group_edges_unique.sql
71|71/01rebuild_event_edges.sql.sqlite
71|71/01remove_noop_background_updates.sql
71|71/02event_push_summary_unique.sql
72|72/01add_room_type_to_state_stats.sql
72|72/01event_push_summary_receipt.sql
72|72/02event_push_actions_index.sql
72|72/03bg_populate_events_columns.py
72|72/03drop_event_reference_hashes.sql
72|72/03remove_groups.sql
72|72/04drop_column_application_services_state_last_txn.sql.sqlite
72|72/05remove_unstable_private_read_receipts.sql
72|72/05receipts_event_stream_ordering.sql
72|72/06add_consent_ts_to_users.sql
72|72/06thread_notifications.sql
72|72/07force_update_current_state_events_membership.py
72|72/07thread_receipts.sql.sqlite
72|72/08thread_receipts.sql
72|72/09partial_indices.sql.sqlite
73|73/01event_failed_pull_attempts.sql
73|73/02room_id_indexes_for_purging.sql
73|73/02add_pusher_enabled.sql
73|73/03pusher_device_id.sql
73|73/03users_approved_column.sql
73|73/04partial_join_details.sql
73|73/04pending_device_list_updates.sql
73|73/05old_push_actions.sql.sqlite
73|73/06thread_notifications_thread_id_idx.sql
73|73/08thread_receipts_non_null.sql.sqlite
73|73/09partial_joined_via_destination.sql
```

**Comment by DMRobertson** [comment]
It looks like you've run the migration but failed to record that fact in your database. To confirm this, can you run `.schema threads` and share its output?

Assuming that diagnosis is correct, I have no idea how you ended up in that state! Do you have any logs from Synapse that can help? We'd want to see the logs from the first run after you upgraded the Synapse image.

**Comment by soupdiver** [comment]
> Assuming that diagnosis is correct, I have no idea how you ended up in that state! Do you have any logs from Synapse that can help? We'd want to see the logs from the first run after you upgraded the Synapse image.

Hmm I run Synapse in a container... sounds to me that a crash during startup could cause this but I'm not 100% sure.
I can't provide the logs of the previous deployments :/

```
.schema threads
CREATE TABLE threads (
    room_id TEXT NOT NULL,
    -- The event ID of the root event in the thread.
    thread_id TEXT NOT NULL,
    -- The latest event ID and corresponding topo / stream ordering.
    latest_event_id TEXT NOT NULL,
    topological_ordering BIGINT NOT NULL,
    stream_ordering BIGINT NOT NULL,
    CONSTRAINT threads_uniqueness UNIQUE (room_id, thread_id)
);
CREATE INDEX threads_ordering_idx ON threads(room_id, topological_ordering, stream_ordering);
```

**Comment by soupdiver** [comment]
@DMRobertson thanks, seems my server is running again :)
The query you posted made it startup again
