### ISSUE TITLE
Constant reboot of Synapse due to postgresSQL incorrect collation.

### ISSUE THREAD

**Issue by GravaTharg** [matrix-org/synapse#14566]
**I was installing matrix homeserver by this guide: https://cyberhost.uk/element-matrix-setup/**
Postgres and element are functioning, but synapse container is constantly rebooting.
I did `docker logs --tail 50 --follow --timestamps matrix_synapse_1`
## output:
```
2022-11-28T07:35:27.268375630Z 2022-11-28 07:35:27,267 - synapse.app._base - 207 - ERROR - main - Exception during startup
2022-11-28T07:35:27.268388735Z Traceback (most recent call last):
2022-11-28T07:35:27.268392271Z   File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 341, in setup
2022-11-28T07:35:27.268395807Z     hs.setup()
2022-11-28T07:35:27.268398523Z   File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 310, in setup
2022-11-28T07:35:27.268401387Z     self.datastores = Databases(self.DATASTORE_CLASS, self)
2022-11-28T07:35:27.268404123Z   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 67, in __init__
2022-11-28T07:35:27.268407049Z     engine.check_database(db_conn)
2022-11-28T07:35:27.268410004Z   File "/usr/local/lib/python3.9/site-packages/synapse/storage/engines/postgres.py", line 103, in check_database
2022-11-28T07:35:27.268412900Z     raise IncorrectDatabaseSetup(
2022-11-28T07:35:27.268429571Z synapse.storage.engines._base.IncorrectDatabaseSetup: ("Database has incorrect collation of %r. Should be 'C'\nSee docs/postgres.md for more information. You can override this check bysetting 'allow_unsafe_locale' to true in the database config.", 'en_US.utf8')
2022-11-28T07:35:27.268433038Z **********************************************************************************
2022-11-28T07:35:27.268435453Z  Error during initialisation:
2022-11-28T07:35:27.268438307Z     ("Database has incorrect collation of %r. Should be 'C'\nSee docs/postgres.md for more information. You can override this check bysetting 'allow_unsafe_locale' to true in the database config.", 'en_US.utf8')
2022-11-28T07:35:27.268441003Z  There may be more information in the logs.
2022-11-28T07:35:27.268443277Z **********************************************************************************
2022-11-28T07:36:27.977194036Z Starting synapse with args -m synapse.app.homeserver --config-path /data/homeserver.yaml
2022-11-28T07:36:30.250387426Z This server is configured to use 'matrix.org' as its trusted key server via the
2022-11-28T07:36:30.250417732Z 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
2022-11-28T07:36:30.250421379Z server since it is long-lived, stable and trusted. However, some admins may
2022-11-28T07:36:30.250424796Z wish to use another server for this purpose.
2022-11-28T07:36:30.250433212Z 
2022-11-28T07:36:30.250436278Z To suppress this warning and continue using 'matrix.org', admins should set
2022-11-28T07:36:30.250439263Z 'suppress_key_server_warning' to 'true' in homeserver.yaml.
2022-11-28T07:36:30.250442028Z --------------------------------------------------------------------------------
2022-11-28T07:36:30.302693798Z 2022-11-28 07:36:30,302 - root - 345 - WARNING - main - ***** STARTING SERVER *****
2022-11-28T07:36:30.302745616Z 2022-11-28 07:36:30,302 - root - 346 - WARNING - main - Server /usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py version 1.72.0
2022-11-28T07:36:30.302750725Z 2022-11-28 07:36:30,302 - root - 351 - INFO - main - Server hostname: matrix.example.com
2022-11-28T07:36:30.302759882Z 2022-11-28 07:36:30,302 - root - 352 - INFO - main - Instance name: master
2022-11-28T07:36:30.302763489Z 2022-11-28 07:36:30,302 - root - 353 - INFO - main - Twisted reactor: EPollReactor
2022-11-28T07:36:30.302868507Z 2022-11-28 07:36:30,302 - synapse.app.homeserver - 338 - INFO - main - Setting up server
2022-11-28T07:36:30.302899525Z 2022-11-28 07:36:30,302 - synapse.server - 308 - INFO - main - Setting up.
2022-11-28T07:36:30.309149256Z 2022-11-28 07:36:30,308 - synapse.storage.databases - 66 - INFO - main - [database config 'master']: Checking database server
2022-11-28T07:36:30.310340240Z 2022-11-28 07:36:30,310 - synapse.storage.engines.postgres - 98 - WARNING - main - Database has incorrect collation of 'en_US.utf8'. Should be 'C'
2022-11-28T07:36:30.311294509Z 2022-11-28 07:36:30,310 - synapse.app._base - 207 - ERROR - main - Exception during startup
2022-11-28T07:36:30.311318344Z Traceback (most recent call last):
2022-11-28T07:36:30.311321961Z   File "/usr/local/lib/python3.9/site-packages/synapse/app/homeserver.py", line 341, in setup
2022-11-28T07:36:30.311324726Z     hs.setup()
2022-11-28T07:36:30.311327992Z   File "/usr/local/lib/python3.9/site-packages/synapse/server.py", line 310, in setup
2022-11-28T07:36:30.311330897Z     self.datastores = Databases(self.DATASTORE_CLASS, self)
2022-11-28T07:36:30.311333993Z   File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/__init__.py", line 67, in __init__
2022-11-28T07:36:30.311336899Z     engine.check_database(db_conn)
2022-11-28T07:36:30.311339634Z   File "/usr/local/lib/python3.9/site-packages/synapse/storage/engines/postgres.py", line 103, in check_database
2022-11-28T07:36:30.311342720Z     raise IncorrectDatabaseSetup(
2022-11-28T07:36:30.311345736Z synapse.storage.engines._base.IncorrectDatabaseSetup: ("Database has incorrect collation of %r. Should be 'C'\nSee docs/postgres.md for more information. You can override this check bysetting 'allow_unsafe_locale' to true in the database config.", 'en_US.utf8')
2022-11-28T07:36:30.311352809Z **********************************************************************************
2022-11-28T07:36:30.311355554Z  Error during initialisation:
2022-11-28T07:36:30.311358069Z     ("Database has incorrect collation of %r. Should be 'C'\nSee docs/postgres.md for more information. You can override this check bysetting 'allow_unsafe_locale' to true in the database config.", 'en_US.utf8')
2022-11-28T07:36:30.311360995Z  There may be more information in the logs.
```
---
I also tried editing postgresql.conf like this:
```
# These settings are initialized by initdb, but they can be changed.
lc_messages = 'C'                      # locale for system error message
                                        # strings
lc_monetary = 'C'                      # locale for monetary formatting
lc_numeric = 'C'                       # locale for number formatting
lc_time = 'C'                          # locale for time formatting
```
Also tried C.UTF-8.

**Comment by DMRobertson** [comment]
We're using Github's issue tracker for bug reports and feature requests. For this kind of support request, please ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.

With that said, see https://github.com/matrix-org/synapse/blob/7013e06e2f60e1401349fd054372808376facc87/contrib/docker/docker-compose.yml#L54-L61 for an example of configuring https://hub.docker.com/_/postgres to create a DB with the correct locale and encoding..

I would also encourage you to contact the author of that guide, to point them to this issue and let them know their guide is out-of-date.
