### ISSUE TITLE
Join failing with internal server error

### ISSUE THREAD

**Issue by MTRNord** [matrix-org/synapse#14581]
### Description

Joining [#gnome-design:gnome.org](https://matrix.to/#/#gnome-design:gnome.org) results in

```
{"errcode":"M_UNKNOWN","error":"Internal server error"}
```

### Steps to reproduce

Not clear but maybe:

- Setup a synapse with workers (I got appservice, 1x fed reader, 3x fed senders, 1x frontent proxy, 1x generic worker, 1x pusher, 1x synchrotron, 1x user-dir)
- Try to join [#gnome-design:gnome.org](https://matrix.to/#/#gnome-design:gnome.org)  using the alias

### Homeserver

matrix.midnightthoughts.space

### Synapse Version

{"server_version":"1.72.0","python_version":"3.9.15"}

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Using a single pg db from the start. PG version 13

### Workers

Multiple workers

### Platform

It's running within kubernetes using https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse

### Relevant log output

```shell
2022-11-29 14:23:19	AssertionError
2022-11-29 14:23:19	    assert room_id not in self._federation_event_handler.room_queues
2022-11-29 14:23:19	  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/federation.py", line 584, in do_invite_join
2022-11-29 14:23:19	    event_id, stream_id = await self.federation_handler.do_invite_join(
2022-11-29 14:23:19	  File "/usr/local/lib/python3.9/site-packages/synapse/replication/http/membership.py", line 94, in _handle_request
2022-11-29 14:23:19	    return await callback(*args, **kwargs)
2022-11-29 14:23:19	  File "/usr/local/lib/python3.9/site-packages/synapse/util/caches/response_cache.py", line 246, in cb
2022-11-29 14:23:19	    result = context.run(gen.send, result)
2022-11-29 14:23:19	  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
2022-11-29 14:23:19	Traceback (most recent call last):
2022-11-29 14:23:19	2022-11-29 13:23:19,868 - synapse.http.server - 124 - ERROR - POST-18670- Failed handle request via 'ReplicationRemoteJoinRestServlet': <SynapseRequest at 0x7fba576ea5b0 method='POST' uri='/_synapse/replication/remote_join/%21ncJLAqMDnjJVydzEdu%3Amatrix.org/%40mtrnord%3Amidnightthoughts.space/SzUDsqnMDM' clientproto='HTTP/1.1' site='9093'>
```

**Comment by MTRNord** [comment]
It seems like even though this happened the join did complete in the background.

**Comment by MTRNord** [comment]
Also I did not active the faster joins experiment

**Comment by DMRobertson** [comment]
Sounds like this was just a slow remote join.

Can you find logs corresponding to `/_synapse/replication/remote_join/%21ncJLAqMDnjJVydzEdu%3Amatrix.org/%40mtrnord%3Amidnightthoughts.space/SzUDsqnMDM`?

**Comment by MTRNord** [comment]
> Can you find logs corresponding to `/_synapse/replication/remote_join/%21ncJLAqMDnjJVydzEdu%3Amatrix.org/%40mtrnord%3Amidnightthoughts.space/SzUDsqnMDM`?

The generic worker also has:

```
2022-11-29 13:23:19,872 - synapse.http.client - 460 - INFO - POST-2397- Received response to POST http://matrix-synapse-replication:9093/_synapse/replication/remote_join/%21ncJLAqMDnjJVydzEdu%3Amatrix.org/%40mtrnord%3Amidnightthoughts.space/SzUDsqnMDM: 500
2022-11-29 13:23:19,873 - synapse.http.server - 108 - INFO - POST-2397- <XForwardedForRequest at 0x7fa4b9a42670 method='POST' uri='/_matrix/client/r0/join/%23gnome-design%3Agnome.org' clientproto='HTTP/1.1' site='8083'> SynapseError: 500 - Internal server error
```

 but that seems to be all there is.

> Sounds like this was just a slow remote join.

The error seems to have been printed within less than 10s in element-web which is why I thought that this is unusual compared to other slow joins.

**Comment by DMRobertson** [comment]
Odd. The relevant source is

https://github.com/matrix-org/synapse/blob/1526ff389f02d14d0df729bd6ea35836e758c449/synapse/handlers/federation.py#L582-L585

so it sounds like that assumption is incorrect. Odder still that you ended up joined to the room anyway.

**Comment by squahtx** [comment]
@anoadragon453 and I have managed to reproduce this while doing load testing with lots of concurrent joins across federation.

@anoadragon453 hypothesises that it's a race:
> I wonder if the problem is that 2+ users are trying to join a remote room simultaneously, and the second attempt hits this assertion

Our setup is `client -> event_creator (x8) -> master -> remote`, where `master` is the worker that hits the assert.
We aren't load balancing based to the event_creators based on room ID.

**Comment by squahtx** [comment]
Also reported in #14728.

**Comment by Heidistein** [comment]
Hi, from the duplicate bug. I do not need a high load or lots of concurrent jobs. It happens for every user, on every join-attempt.

**Comment by MTRNord** [comment]
seems like I am seeing it on every join as well now. It seems to have gotten worse since initial reporting.

**Comment by erikjohnston** [comment]
It would be useful to see the logs the next time this happens. Specifically, I'm wondering if either:

1. We're handling multiple requests of `/_synapse/replication/remote_join/` at the same time; or
2. Whether at some point one of these functions raised an exception, meaning we didn't remove the room ID from the room queue: https://github.com/matrix-org/synapse/blob/8a6e0434889ea94893119775b6f56904cbc575c2/synapse/handlers/federation.py#L607-L623

**Comment by H-Shay** [comment]
Any update on this?

**Comment by Heidistein** [comment]
> It would be useful to see the logs the next time this happens. Specifically, I'm wondering if either:
> 
>     1. We're handling multiple requests of `/_synapse/replication/remote_join/` at the same time; or
> 
>     2. Whether at some point one of these functions raised an exception, meaning we didn't remove the room ID from the room queue: https://github.com/matrix-org/synapse/blob/8a6e0434889ea94893119775b6f56904cbc575c2/synapse/handlers/federation.py#L607-L623

Hi. I will provide this for you. However I am very busy with $life. Is my logs in  #14728 helpful by chance?

**Comment by H-Shay** [comment]
The logs in #14728 are from quite a few versions ago, is anyone able to provide more recent logs for this issue?

**Comment by H-Shay** [comment]
Given that we don't have logs to investigate this I am closing the issue for now - we will happily re-open it if someone comes back with logs.
