### ISSUE TITLE
synapse.metrics.background_process_metrics - 244 - ERROR - update_client_ips-0- Background process 'update_client_ips' threw an exception

### ISSUE THREAD

**Issue by sunnyevening** [matrix-org/synapse#14647]
### Description

I am seeing lots of these messages. The instance appears to be running fine.

```
Dec 09 06:33:23 matrix-synapse[203749]: 2022-12-09 06:33:23,499 - synapse.metrics.background_process_metrics - 244 - ERROR - update_client_ips-0- Background process 'update_client_ips' threw an exception
Dec 09 06:33:23 matrix-synapse[203749]: Traceback (most recent call last):
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/metrics/background_process_metrics.py", line 242, in run
Dec 09 06:33:23 matrix-synapse[203749]:     return await func(*args, **kwargs)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/databases/main/client_ips.py", line 620, in _update_client_ips_batch
Dec 09 06:33:23 matrix-synapse[203749]:     await self.db_pool.runInteraction(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 881, in runInteraction
Dec 09 06:33:23 matrix-synapse[203749]:     return await delay_cancellation(_runInteraction())
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
Dec 09 06:33:23 matrix-synapse[203749]:     result = context.run(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
Dec 09 06:33:23 matrix-synapse[203749]:     return g.throw(self.type, self.value, self.tb)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 848, in _runInteraction
Dec 09 06:33:23 matrix-synapse[203749]:     result = await self.runWithConnection(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 976, in runWithConnection
Dec 09 06:33:23 matrix-synapse[203749]:     return await make_deferred_yieldable(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/python/threadpool.py", line 244, in inContext
Dec 09 06:33:23 matrix-synapse[203749]:     result = inContext.theWork()  # type: ignore[attr-defined]
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
Dec 09 06:33:23 matrix-synapse[203749]:     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/python/context.py", line 117, in callWithContext
Dec 09 06:33:23 matrix-synapse[203749]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/python/context.py", line 82, in callWithContext
Dec 09 06:33:23 matrix-synapse[203749]:     return func(*args, **kw)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
Dec 09 06:33:23 matrix-synapse[203749]:     result = func(conn, *args, **kw)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 969, in inner_func
Dec 09 06:33:23 matrix-synapse[203749]:     return func(db_conn, *args, **kwargs)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 710, in new_transaction
Dec 09 06:33:23 matrix-synapse[203749]:     r = func(cursor, *args, **kwargs)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/databases/main/client_ips.py", line 652, in _update_client_ips_batch_txn
Dec 09 06:33:23 matrix-synapse[203749]:     self.db_pool.simple_upsert_many_txn(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 1442, in simple_upsert_many_txn
Dec 09 06:33:23 matrix-synapse[203749]:     return self.simple_upsert_many_txn_native_upsert(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 1540, in simple_upsert_many_txn_native_upsert
Dec 09 06:33:23 matrix-synapse[203749]:     txn.execute_values(sql, args, fetch=False)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 382, in execute_values
Dec 09 06:33:23 matrix-synapse[203749]:     return self._do_execute(
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 436, in _do_execute
Dec 09 06:33:23 matrix-synapse[203749]:     return func(sql, *args, **kwargs)
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/synapse/storage/database.py", line 383, in <lambda>
Dec 09 06:33:23 matrix-synapse[203749]:     lambda the_sql: execute_values(self.txn, the_sql, values, fetch=fetch),
Dec 09 06:33:23 matrix-synapse[203749]:   File "/opt/venvs/matrix-synapse/lib/python3.9/site-packages/psycopg2/extras.py", line 1299, in execute_values
Dec 09 06:33:23 matrix-synapse[203749]:     cur.execute(b''.join(parts))
Dec 09 06:33:23 matrix-synapse[203749]: psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

### Steps to reproduce

- standard matrix-synapse installation (using .deb) running on Debian 11 
- the system has been running for several years, updated regularly with `apt-get update` `apt-get upgrade`

### Homeserver

another homeserver

### Synapse Version

{"server_version":"1.73.0","python_version":"3.9.2"}

### Installation Method

Debian packages from packages.matrix.org

### Database

previously ported from SQLite to PostgreSQL some years ago; not done with portdb script (be before the script was available)

### Workers

Single process

### Platform

Debian 11

### Configuration

None

### Relevant log output

```shell
(as shown in description above)
```

### Anything else that would be useful to know?

None

**Comment by reivilibre** [comment]
> previously ported from SQLite to PostgreSQL some years ago; not done with portdb script (be before the script was available)

How did you port your database? I guess that it's likely you've missed off some constraints, one of which is manifesting itself as this error.

It would be useful to see
```sql
SELECT * FROM applied_schema_deltas ORDER BY file;
```
to see what deltas have been applied to your database.

Looking at `_update_client_ips_batch_txn` (the function mentioned in the error), we see this upsert:

```python
        self.db_pool.simple_upsert_many_txn(
            txn,
            table="user_ips",
            key_names=("user_id", "access_token", "ip"),
            key_values=user_ips_keys,
            value_names=("user_agent", "device_id", "last_seen"),
            value_values=user_ips_values,
        )
```

Notable is `key_names=("user_id", "access_token", "ip")`. This means that you'll need a unique index on those columns.

I find this line in one of the schema deltas:
```sql
CREATE UNIQUE INDEX user_ips_user_token_ip_unique_index ON user_ips (user_id, access_token, ip);
```

If you run `\d user_ips` on your Postgres database using `psql`, it should describe the structure of the table to you and you will likely notice part of it to be missing:

```sql
=> \d user_ips
                Table "public.user_ips"
    Column    |  Type  | Collation | Nullable | Default 
--------------+--------+-----------+----------+---------
 user_id      | text   |           | not null | 
 access_token | text   |           | not null | 
 device_id    | text   |           |          | 
 ip           | text   |           | not null | 
 user_agent   | text   |           | not null | 
 last_seen    | bigint |           | not null | 
Indexes:
    "user_ips_device_id" btree (user_id, device_id, last_seen)
    "user_ips_last_seen" btree (user_id, last_seen)
    "user_ips_last_seen_only" btree (last_seen)
    "user_ips_user_token_ip_unique_index" UNIQUE, btree (user_id, access_token, ip)
```

If you don't find `"user_ips_user_token_ip_unique_index" UNIQUE, btree (user_id, access_token, ip)` in your database, you *could* recreate it with
```
CREATE UNIQUE INDEX user_ips_user_token_ip_unique_index ON user_ips (user_id, access_token, ip);
```
But it's fairly recent and I'm surprised if it's not present in your database; after all, you say that you've been running since before the portdb script existed...

**Comment by sunnyevening** [comment]
This is the output of `SELECT * FROM applied_schema_deltas ORDER BY file;`

```
 version |                               file                                
---------+-------------------------------------------------------------------
      17 | 17/drop_indexes.sql
      17 | 17/server_keys.sql
      17 | 17/user_threepids.sql
      18 | 18/server_keys_bigger_ints.sql
      19 | 19/event_index.sql
      20 | 20/dummy.sql
      20 | 20/pushers.py
      20 | 20/pushers.pyc
      21 | 21/end_to_end_keys.sql
      21 | 21/receipts.sql
      22 | 22/receipts_index.sql
      22 | 22/user_threepids_unique.sql
      23 | 23/drop_state_index.sql
      24 | 24/stats_reporting.sql
      25 | 25/00background_updates.sql
      25 | 25/fts.py
      25 | 25/fts.pyc
      25 | 25/guest_access.sql
      25 | 25/history_visibility.sql
      25 | 25/tags.sql
      26 | 26/account_data.sql
      27 | 27/account_data.sql
      27 | 27/forgotten_memberships.sql
      27 | 27/ts.py
      27 | 27/ts.pyc
      28 | 28/event_push_actions.sql
      28 | 28/events_room_stream.sql
      28 | 28/public_roms_index.sql
      28 | 28/receipts_user_id_index.sql
      28 | 28/upgrade_times.sql
      28 | 28/users_is_guest.sql
      29 | 29/push_actions.sql
      30 | 30/alias_creator.sql
      30 | 30/as_users.py
      30 | 30/as_users.pyc
      30 | 30/deleted_pushers.sql
      30 | 30/presence_stream.sql
      30 | 30/public_rooms.sql
      30 | 30/push_rule_stream.sql
      30 | 30/state_stream.sql
      30 | 30/threepid_guest_access_tokens.sql
      31 | 31/invites.sql
      31 | 31/local_media_repository_url_cache.sql
      31 | 31/pushers.py
      31 | 31/pushers.pyc
      31 | 31/pushers_index.sql
      31 | 31/search_update.py
      31 | 31/search_update.pyc
      32 | 32/events.sql
      32 | 32/openid.sql
      32 | 32/pusher_throttle.sql
      32 | 32/remove_indices.sql
      32 | 32/reports.sql
      33 | 33/access_tokens_device_index.sql
      33 | 33/devices.sql
      33 | 33/devices_for_e2e_keys.sql
      33 | 33/devices_for_e2e_keys_clear_unknown_device.sql
      33 | 33/event_fields.py
      33 | 33/event_fields.pyc
      33 | 33/remote_media_ts.py
      33 | 33/remote_media_ts.pyc
      33 | 33/user_ips_index.sql
      34 | 34/appservice_stream.sql
      34 | 34/cache_stream.py
      34 | 34/cache_stream.pyc
      34 | 34/device_inbox.sql
      34 | 34/push_display_name_rename.sql
      34 | 34/received_txn_purge.py
      34 | 34/received_txn_purge.pyc
      34 | 34/sent_txn_purge.py
      34 | 34/sent_txn_purge.pyc
      35 | 35/add_state_index.sql
      35 | 35/contains_url.sql
      35 | 35/device_outbox.sql
      35 | 35/device_stream_id.sql
      35 | 35/event_push_actions_index.sql
      35 | 35/public_room_list_change_stream.sql
      35 | 35/state.sql
      35 | 35/state_dedupe.sql
      35 | 35/stream_order_to_extrem.sql
      36 | 36/readd_public_rooms.sql
      37 | 37/remove_auth_idx.py
      37 | 37/remove_auth_idx.pyc
      37 | 37/user_threepids.sql
      38 | 38/postgres_fts_gist.sql
      39 | 39/appservice_room_list.sql
      39 | 39/device_federation_stream_idx.sql
      39 | 39/event_push_index.sql
      39 | 39/federation_out_position.sql
      39 | 39/membership_profile.sql
      40 | 40/current_state_idx.sql
      40 | 40/device_inbox.sql
      40 | 40/device_list_streams.sql
      40 | 40/event_push_summary.sql
      40 | 40/pushers.sql
      41 | 41/device_list_stream_idx.sql
      41 | 41/device_outbound_index.sql
      41 | 41/event_search_event_id_idx.sql
      41 | 41/ratelimit.sql
      42 | 42/current_state_delta.sql
      42 | 42/device_list_last_id.sql
      42 | 42/event_auth_state_only.sql
      42 | 42/user_dir.py
      42 | 42/user_dir.pyc
      43 | 43/blocked_rooms.sql
      43 | 43/quarantine_media.sql
      43 | 43/url_cache.sql
      43 | 43/user_share.sql
      44 | 44/expire_url_cache.sql
      45 | 45/group_server.sql
      45 | 45/profile_cache.sql
      46 | 46/drop_refresh_tokens.sql
      46 | 46/drop_unique_deleted_pushers.sql
      46 | 46/group_server.sql
      46 | 46/local_media_repository_url_idx.sql
      46 | 46/user_dir_null_room_ids.sql
      46 | 46/user_dir_typos.sql
      47 | 47/last_access_media.sql
      47 | 47/postgres_fts_gin.sql
      47 | 47/push_actions_staging.sql
      47 | 47/state_group_seq.py
      47 | 47/state_group_seq.pyc
      48 | 48/add_user_consent.sql
      48 | 48/add_user_ips_last_seen_index.sql
      48 | 48/deactivated_users.sql
      48 | 48/group_unique_indexes.py
      48 | 48/group_unique_indexes.pyc
      48 | 48/groups_joinable.sql
      49 | 49/add_user_consent_server_notice_sent.sql
      49 | 49/add_user_daily_visits.sql
      49 | 49/add_user_ips_last_seen_only_index.sql
      50 | 50/add_creation_ts_users_index.sql
      50 | 50/erasure_store.sql
      50 | 50/make_event_content_nullable.py
      50 | 50/make_event_content_nullable.pyc
      51 | 51/e2e_room_keys.sql
      51 | 51/monthly_active_users.sql
      52 | 52/add_event_to_state_group_index.sql
      52 | 52/device_list_streams_unique_idx.sql
      52 | 52/e2e_room_keys.sql
      53 | 53/add_user_type_to_users.sql
      53 | 53/drop_sent_transactions.sql
      53 | 53/event_format_version.sql
      53 | 53/user_dir_populate.sql
      53 | 53/user_ips_index.sql
      53 | 53/user_share.sql
      53 | 53/user_threepid_id.sql
      53 | 53/users_in_public_rooms.sql
      54 | 54/account_validity.sql
      54 | 54/account_validity_with_renewal.sql
      54 | 54/add_validity_to_server_keys.sql
      54 | 54/delete_forward_extremities.sql
      54 | 54/drop_legacy_tables.sql
      54 | 54/drop_presence_list.sql
      54 | 54/relations.sql
      54 | 54/stats.sql
      54 | 54/stats2.sql
      55 | 55/access_token_expiry.sql
      55 | 55/track_threepid_validations.sql
      55 | 55/users_alter_deactivated.sql
      56 | 56/add_spans_to_device_lists.sql
      56 | 56/current_state_events_membership.sql
      56 | 56/delete_keys_from_deleted_backups.sql
      56 | 56/destinations_failure_ts.sql
      56 | 56/destinations_retry_interval_type.sql.postgres
      56 | 56/device_stream_id_insert.sql
      56 | 56/devices_last_seen.sql
      56 | 56/drop_unused_event_tables.sql
      56 | 56/event_expiry.sql
      56 | 56/event_labels.sql
      56 | 56/event_labels_background_update.sql
      56 | 56/fix_room_keys_index.sql
      56 | 56/hidden_devices.sql
      56 | 56/nuke_empty_communities_from_db.sql
      56 | 56/public_room_list_idx.sql
      56 | 56/redaction_censor.sql
      56 | 56/redaction_censor2.sql
      56 | 56/redaction_censor3_fix_update.sql.postgres
      56 | 56/redaction_censor4.sql
      56 | 56/remove_tombstoned_rooms_from_directory.sql
      56 | 56/room_key_etag.sql
      56 | 56/room_membership_idx.sql
      56 | 56/room_retention.sql
      56 | 56/signing_keys.sql
      56 | 56/signing_keys_nonunique_signatures.sql
      56 | 56/state_group_room_idx.sql
      56 | 56/stats_separated.sql
      56 | 56/unique_user_filter_index.py
      56 | 56/user_external_ids.sql
      56 | 56/users_in_public_rooms_idx.sql
      57 | 57/delete_old_current_state_events.sql
      57 | 57/device_list_remote_cache_stale.sql
      57 | 57/local_current_membership.py
      57 | 57/remove_sent_outbound_pokes.sql
      57 | 57/rooms_version_column.sql
      57 | 57/rooms_version_column_2.sql.postgres
      57 | 57/rooms_version_column_3.sql.postgres
      58 | 58/00background_update_ordering.sql
      58 | 58/02remove_dup_outbound_pokes.sql
      58 | 58/03persist_ui_auth.sql
      58 | 58/05cache_instance.sql.postgres
      58 | 58/06dlols_unique_idx.py
      58 | 58/07add_method_to_thumbnail_constraint.sql.postgres
      58 | 58/07persist_ui_auth_ips.sql
      58 | 58/08_media_safe_from_quarantine.sql.postgres
      58 | 58/09shadow_ban.sql
      58 | 58/10_pushrules_enabled_delete_obsolete.sql
      58 | 58/10drop_local_rejections_stream.sql
      58 | 58/10federation_pos_instance_name.sql
      58 | 58/11dehydration.sql
      58 | 58/11fallback.sql
      58 | 58/11user_id_seq.py
      58 | 58/12room_stats.sql
      58 | 58/13remove_presence_allow_inbound.sql
      58 | 58/14events_instance_name.sql
      58 | 58/14events_instance_name.sql.postgres
      58 | 58/15_catchup_destination_rooms.sql
      58 | 58/15unread_count.sql
      58 | 58/16populate_stats_process_rooms_fix.sql
      58 | 58/17_catchup_last_successful.sql
      58 | 58/18stream_positions.sql
      58 | 58/19instance_map.sql.postgres
      58 | 58/19txn_id.sql
      58 | 58/20instance_name_event_tables.sql
      58 | 58/20user_daily_visits.sql
      58 | 58/21as_device_stream.sql
      58 | 58/21drop_device_max_stream_id.sql
      58 | 58/22puppet_token.sql
      58 | 58/22users_have_local_media.sql
      58 | 58/23e2e_cross_signing_keys_idx.sql
      58 | 58/24drop_event_json_index.sql
      58 | 58/25user_external_ids_user_id_idx.sql
      58 | 58/26access_token_last_validated.sql
      58 | 58/27local_invites.sql
      58 | 58/28drop_last_used_column.sql.postgres
      58 | 58/28rejected_events_metadata.sql
      59 | 59/01ignored_user.py
      59 | 59/02shard_send_to_device.sql
      59 | 59/03shard_send_to_device_sequence.sql.postgres
      59 | 59/04_event_auth_chains.sql
      59 | 59/04_event_auth_chains.sql.postgres
      59 | 59/04drop_account_data.sql
      59 | 59/05cache_invalidation.sql
      59 | 59/06chain_cover_index.sql
      59 | 59/06shard_account_data.sql
      59 | 59/06shard_account_data.sql.postgres
      59 | 59/07shard_account_data_fix.sql
      59 | 59/08delete_pushers_for_deactivated_accounts.sql
      59 | 59/08delete_stale_pushers.sql
      59 | 59/09rejected_events_metadata.sql
      59 | 59/10delete_purged_chain_cover.sql
      59 | 59/11add_knock_members_to_stats.sql
      59 | 59/11drop_thumbnail_constraint.sql.postgres
      59 | 59/12account_validity_token_used_ts_ms.sql
      59 | 59/12presence_stream_instance.sql
      59 | 59/12presence_stream_instance_seq.sql.postgres
      59 | 59/13users_to_send_full_presence_to.sql
      59 | 59/14refresh_tokens.sql
      59 | 59/15locks.sql
      59 | 59/16federation_inbound_staging.sql
      60 | 60/01recreate_stream_ordering.sql.postgres
      60 | 60/02change_stream_ordering_columns.sql.postgres
      61 | 61/01change_appservices_txns.sql.postgres
      61 | 61/01insertion_event_lookups.sql
      61 | 61/02drop_redundant_room_depth_index.sql
      61 | 61/02state_groups_state_n_distinct.sql.postgres
      61 | 61/03recreate_min_depth.py
      62 | 62/01insertion_event_extremities.sql
      63 | 63/01create_registration_tokens.sql
      63 | 63/02delete_unlinked_email_pushers.sql
      63 | 63/02populate-rooms-creator.sql
      63 | 63/03session_store.sql
      63 | 63/04add_presence_stream_not_offline_index.sql
      64 | 64/01msc2716_chunk_to_batch_rename.sql.postgres
      65 | 65/01msc2716_insertion_event_edges.sql
      65 | 65/02_thread_relations.sql
      65 | 65/03remove_hidden_devices_from_device_inbox.sql
      65 | 65/04_local_group_updates.sql
      65 | 65/05_remove_room_stats_historical_and_user_stats_historical.sql
      65 | 65/06remove_deleted_devices_from_device_inbox.sql
      65 | 65/07_arbitrary_relations.sql
      65 | 65/08_device_inbox_background_updates.sql
      65 | 65/10_expirable_refresh_tokens.sql
      65 | 65/11_devices_auth_provider_session.sql
      67 | 67/01drop_public_room_list_stream.sql
      68 | 68/01event_columns.sql
      68 | 68/02_msc2409_add_device_id_appservice_stream_type.sql
      68 | 68/03_delete_account_data_for_deactivated_accounts.sql
      68 | 68/04_refresh_tokens_index_next_token_id.sql
      68 | 68/04partial_state_rooms.sql
      68 | 68/05partial_state_rooms_triggers.py
      68 | 68/06_msc3202_add_device_list_appservice_stream_type.sql
      69 | 69/01as_txn_seq.py
      69 | 69/01device_list_oubound_by_room.sql
      69 | 69/02cache_invalidation_index.sql
      70 | 70/01clean_table_purged_rooms.sql
      70 | 70/08_state_group_edges_unique.sql
      71 | 71/01rebuild_event_edges.sql.postgres
      71 | 71/01remove_noop_background_updates.sql
      71 | 71/02event_push_summary_unique.sql
      72 | 72/01add_room_type_to_state_stats.sql
      72 | 72/01event_push_summary_receipt.sql
      72 | 72/02event_push_actions_index.sql
      72 | 72/03bg_populate_events_columns.py
      72 | 72/03drop_event_reference_hashes.sql
      72 | 72/03remove_groups.sql
      72 | 72/04drop_column_application_services_state_last_txn.sql.postgres
      72 | 72/05receipts_event_stream_ordering.sql
      72 | 72/05remove_unstable_private_read_receipts.sql
      72 | 72/06add_consent_ts_to_users.sql
      72 | 72/06thread_notifications.sql
      72 | 72/07force_update_current_state_events_membership.py
      72 | 72/07thread_receipts.sql.postgres
      72 | 72/08begin_cache_invalidation_seq_at_2.sql.postgres
      72 | 72/08thread_receipts.sql
      73 | 73/01event_failed_pull_attempts.sql
      73 | 73/02add_pusher_enabled.sql
      73 | 73/02room_id_indexes_for_purging.sql
      73 | 73/03pusher_device_id.sql
      73 | 73/03users_approved_column.sql
      73 | 73/04partial_join_details.sql
      73 | 73/04pending_device_list_updates.sql
      73 | 73/05old_push_actions.sql.postgres
      73 | 73/06thread_notifications_thread_id_idx.sql
      73 | 73/08thread_receipts_non_null.sql.postgres
      73 | 73/09partial_joined_via_destination.sql
      73 | 73/09threads_table.sql
      73 | 73/10_update_sqlite_fts4_tokenizer.py
      73 | 73/10login_tokens.sql
      73 | 73/11event_search_room_id_n_distinct.sql.postgres
      73 | 73/12refactor_device_list_outbound_pokes.sql
      73 | 73/13add_device_lists_index.sql
(333 rows)
```

This is the output of `\d user_ips`:

```
                Table "public.user_ips"
    Column    |  Type  | Collation | Nullable | Default 
--------------+--------+-----------+----------+---------
 user_id      | text   |           | not null | 
 access_token | text   |           | not null | 
 device_id    | text   |           |          | 
 ip           | text   |           | not null | 
 user_agent   | text   |           | not null | 
 last_seen    | bigint |           | not null | 

```

When I tried running `CREATE UNIQUE INDEX user_ips_user_token_ip_unique_index ON user_ips (user_id, access_token, ip);`, I got this: 
```
synapse=# CREATE UNIQUE INDEX user_ips_user_token_ip_unique_index ON user_ips (user_id, access_token, ip);
ERROR:  could not create unique index "user_ips_user_token_ip_unique_index"
DETAIL:  Key (user_id, access_token, ip)=(@XXX:XXX.com, syt_b2xvZ2lub3Y_UaSTodwfYwIDodDyJaIY_2vfGjX, XXX.XXX.XXX.XXX) is duplicated.
synapse=# 
```

**Comment by DMRobertson** [comment]
@sunnyevening your last message included a Synapse access token, (`syt_.....` which can be used to fully control its corresponding account. I have edited your message to redact the token, but you should assume it has been compromised and logout the corresponding device.

**Comment by sunnyevening** [comment]
After manually deleting the duplicated entries in `user_ips` table, and then ran:
```
CREATE UNIQUE INDEX user_ips_user_token_ip_unique_index ON user_ips (user_id, access_token, ip);
CREATE INDEX user_ips_device_id ON user_ips (user_id, device_id, last_seen);
CREATE INDEX user_ips_last_seen ON user_ips (user_id, last_seen);
CREATE INDEX user_ips_last_seen_only ON user_ips (last_seen);
```
the problem appears to have been resolved.
