### ISSUE TITLE
join fail to federation room

### ISSUE THREAD

**Issue by rosbeef** [matrix-org/synapse#14654]
### Description

i have noway to join some public room in federation.

### Steps to reproduce

try to join #nextcloud:matrix.org or #yunohost:matrix.org
wait 60 s 
failed to join.

### Homeserver

homeserver

### Synapse Version

{"server":{"name":"Synapse","version":"1.71.0"}}

### Installation Method

Other (please mention below)

### Database

postgreSQL ~~sqlite3~~

### Workers

Single process

### Platform

debian 11
odroid xu4
lxc container

### Relevant log output

```shell
2022-12-11 11:21:13,711 - synapse.storage.databases.main.event_push_actions - 1720 - INFO - rotate_notifs-1299- Rotating notifications, deleted 0 push actions
2022-12-11 11:21:14,129 - synapse.http.server - 124 - ERROR - PUT-10375- Failed handle request via 'RoomSendEventRestServlet': <XForwardedForRequest at 0xac2c7328 method='PUT' uri='/_matrix/client/r0/rooms/!GevpWevrsZKluNMXsY:pijean.ovh/send/m.room.message/$local.3d0a035b-fece-4ed7-a011-ff475fbcff0b' clientproto='HTTP/1.0' site='8008'>
Traceback (most recent call last):
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/synapse/rest/client/room.py", line 353, in on_POST
    ) = await self.event_creation_handler.create_and_send_nonmember_event(
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/message.py", line 972, in create_and_send_nonmember_event
    event, context = await self.create_event(
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/message.py", line 711, in create_event
    event, context = await self.create_new_client_event(
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/synapse/util/metrics.py", line 113, in measured_func
    r = await func(self, *args, **kwargs)
  File "/opt/yunohost/matrix-synapse/lib/python3.9/site-packages/synapse/handlers/message.py", line 1139, in create_new_client_event
    assert (
AssertionError: Attempting to create a non-m.room.create event with no prev_events
2022-12-11 11:21:14,133 - twisted - 274 - INFO - sentinel- Timing out client: IPv6Address(type='TCP', host='2a01:cb04:4ab:ec00:e9d0:6ba7:5a67:9a5b', port=45442, flowInfo=0, scopeID=0)
2022-12-11 11:21:14,612 - synapse.access.http.8008 - 460 - INFO - PUT-10375- 181.202.86.45 - 8008 - {@rosbeefandino:3cmr.fr} Processed request: 0.934sec/0.481sec (0.017sec, 0.009sec) (0.014sec/0.041sec/2) 55B 500 "PUT /_matrix/client/r0/rooms/!GevpWevrsZKluNMXsY:pijean.ovh/send/m.room.message/$local.3d0a035b-fece-4ed7-a011-ff475fbcff0b HTTP/1.0" "Element/1.5.11 (Motorola Moto X Play; Android 10; e_lux-user 10 QQ3A.200805.001 eng.root.20221204.052201 dev-keys,dev-release; Flavour FDroid; MatrixAndroidSdk2 1.5.11)" [0 dbevts]
2022-12-11 11:21:16,387 - synapse.http.federation.well_known_resolver - 253 - INFO - federation_transaction_transmission_loop-7105- Fetching https://darkweb.one/.well-known/matrix/server
2022-12-11 11:21:19,000 - synapse.metrics._gc - 120 - INFO - sentinel- Collecting gc 1
2022-12-11 11:21:19,464 - synapse.http.site - 372 - INFO - POST-10368- Connection from client lost before response was sent
2022-12-11 11:21:26,351 - synapse.federation.transport.server.federation - 103 - INFO - PUT-10376- Received txn 1665946478970 from laura.pm. (PDUs: 0, EDUs: 1)
2022-12-11 11:21:27,261 - synapse.federation.transport.server.federation - 103 - INFO - PUT-10377- Received txn 1667456593527 from acsl.team. (PDUs: 0, EDUs: 1)
2022-12-11 11:21:28,621 - synapse.access.https.8448 - 460 - INFO - PUT-10377- ::ffff:73.145.145.118 - 8448 - {acsl.team} Processed request: 1.319sec/0.483sec (0.021sec, 0.003sec) (0.007sec/0.064sec/2) 11B 200 "PUT /_matrix/federation/v1/send/1667456593527 HTTP/1.1" "Synapse/1.70.1" [0 dbevts]
2022-12-11 11:21:29,081 - synapse.access.https.8448 - 460 - INFO - PUT-10376- ::ffff:185.236.240.130 - 8448 - {laura.pm} Processed request: 2.731sec/0.457sec (0.033sec, 0.001sec) (0.023sec/0.103sec/5) 11B 200 "PUT /_matrix/federation/v1/send/1665946478970 HTTP/1.1" "Synapse/1.68.0" [0 dbevts]
2022-12-11 11:21:30,459 - synapse.federation.transport.server.federation - 103 - INFO - PUT-10378- Received txn 1670254071999 from bitweise-eskapaden.de. (PDUs: 0, EDUs: 1)
2022-12-11 11:21:30,461 - twisted - 274 - INFO - sentinel- Timing out client: IPv6Address(type='TCP', host='::ffff:37.247.57.95', port=36582, flowInfo=0, scopeID=0)
2022-12-11 11:21:31,830 - synapse.access.https.8448 - 460 - INFO - PUT-10378- ::ffff:78.46.202.250 - 8448 - {bitweise-eskapaden.de} Processed request: 1.358sec/0.457sec (0.011sec, 0.004sec) (0.006sec/0.035sec/2) 11B 200 "PUT /_matrix/federation/v1/send/1670254071999 HTTP/1.1" "Synapse/1.72.0" [0 dbevts]
```

### Anything else that would be useful to know?

install thrue yunohost think its installed thrue python
https://github.com/YunoHost-Apps/synapse_ynh/blob/master/scripts/_common.sh

**Comment by rosbeef** [comment]
[homeserver.log](https://github.com/matrix-org/synapse/files/10203208/homeserver.log)

**Comment by DMRobertson** [comment]
> ##  Homeserver
>
> homeserver

It sounds like you're self hosting and your homeserver has no-one else joined to this room. If so, this is https://github.com/matrix-org/synapse/issues/1211.

**Comment by rosbeef** [comment]
i thougth that it was that, but i joined rooms with more peoples (800+) like #mobian:matrix.org (Room version: 9)
i i would like to join #freenode_#yunohost:matrix.org (150+ users) or #yunohost-dev:matrix.org (don't know the room version)

**Comment by bahur142** [comment]
This is not helpful, but. If your database is SQLite3, how is even possible to make federation? I thought PostgreSQL is a prerequisite to federate.

**Comment by rosbeef** [comment]
sorry reading more carfully the installation files database is postgresql :
https://github.com/YunoHost-Apps/synapse_ynh/blob/master/conf/homeserver.yaml

**Comment by DMRobertson** [comment]
Federation is possible when using both SQLite and Postgres. (Postgres is required to use multiple workers, however.)

**Comment by rosbeef** [comment]
sorry reading more carfully the installation files database is postgresql :
https://github.com/YunoHost-Apps/synapse_ynh/blob/master/conf/homeserver.yaml

**Comment by rosbeef** [comment]
peoples on yunohost told me that #freenode_#yunohost:matrix.org doesn t exist anymore but apear in the public room search list and the new one "#yunohost:matrix.org" doesnot apear.

so i tried the command you toldme :
$curl 'https://matrx.3cmr.fr:8448/_synapse/admin/v2/rooms/!GevpWevrsZKluNMXsY:pijean.ovh' -X 'DELETE' --header "Authorization: Bearer xxxxxxx" --data-raw '{"purge": true}'
${"delete_id":"XXXXXXXXXXXXXXXXXXX"}

Then i tried to joined and same error appear.

How can i send you a password in private to open the homeserver.log[homeserver.log](https://paste.3cmr.fr/lufi/r/qB87AECMT0#9EPJ9DyplzNAhroVqRxKlsU6p9TfCEZda558aV+ZUNE=) 
(just to say,it should be good to think to an anonymized log)

**Comment by squahtx** [comment]
As noted in https://matrix-org.github.io/synapse/v1.73/admin_api/rooms.html#version-2-new-version, deletions run in the background. It is necessary to wait for the deletion to complete by checking `/delete_status`. Until then, the room should not be joined.

You can send the password to `@squah:matrix.org`

**Comment by rosbeef** [comment]
{"results":[{"delete_id":"puqKNGmWXkaaJIVg","status":"complete","shutdown_room":{"kicked_users":[],"failed_to_kick_users":[],"local_aliases":[],"new_room_id":null}}]}
and joining keepfailling

**Comment by DMRobertson** [comment]
> and joining keepfailling

Please provide logs from a join attempt that failed _after_ the deletion was completed.

**Comment by H-Shay** [comment]
I am going to close this for now due to lack of activity, we can re-open if it's still an issue and logs are provided - otherwise we have no way of diagnosing what's happening.

**Comment by rosbeef** [comment]
@H-Shay problem persist. logs are here https://paste.3cmr.fr/lufi/r/qB87AECMT0#9EPJ9DyplzNAhroVqRxKlsU6p9TfCEZda558aV+ZUNE= but if you can help me please share me a way to share you the password to access it. It seems @squahtx had no time to see my log.

**Comment by H-Shay** [comment]
I've re-opened, you can send me logs at @shayshay:matrix.org

**Comment by rosbeef** [comment]
problem corrected, and don't know how, thanks for your time.
