### ISSUE TITLE
`/sync` failing with `KeyError` in `get_state_for_events`

### ISSUE THREAD

**Issue by Fenisu** [matrix-org/synapse#14813]
### Description

"Recent" Element desktop and Element web clients cannot connect to synapse. It worked with older clients from ~ 2 months ago.
Desktop and Web client, if they were logged in before, the old view is shown and a bottom banner says that the connection is lost.
New login just gets stuck at loading, with the spinning loading icon in the middle of the screen. 

Element Android after upgrading from 1.5.11 to 1.5.18 stopped being able to connect. It started a new "sync" after upgrade and it got stuck on it.

The servers throws an error seen on the log and the clients are stuck connecting / loading.

### Steps to reproduce

- Start server
- Open Element client
- Client gets stuck loading

### Homeserver

matrix.plong.eu

### Synapse Version

1.74.0

### Installation Method

Debian packages from packages.matrix.org

### Database

official docker image for postgres:11

### Workers

Single process

### Platform

VM with Ubuntu 20.04.

### Configuration

I have a standard minimal configuration. Currently 10 users on server.

### Relevant log output

```shell
2023-01-10 22:25:31,854 - synapse.http.server - 124 - ERROR - GET-16 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f2778156e80 method='GET' uri='/_matrix/client/r0/sync?filter=4&timeout=0&since=s1504436_18432451_1065_5032966_48740_52_81132_2019785_0' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/caches/response_cache.py", line 246, in cb
    return await callback(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 365, in _wait_for_sync_for_user
    result: SyncResult = await self.current_sync_for_user(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 416, in current_sync_for_user
    sync_result = await self.generate_sync_result(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1405, in generate_sync_result
    res = await self._generate_sync_entry_for_rooms(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1855, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 236, in concurrently_execute
    await yieldable_gather_results(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 292, in yieldable_gather_results
    raise dfe.subFailure.value from None
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 228, in _concurrently_execute_inner
    await maybe_awaitable(func(value))
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1844, in handle_room_entries
    await self._generate_room_entry(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 2289, in _generate_room_entry
    batch = await self._load_filtered_recents(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/handlers/sync.py", line 545, in _load_filtered_recents
    recents = await filter_events_for_client(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 896, in _wrapper
    return await func(*args, **kwargs)  # type: ignore[misc]
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/visibility.py", line 100, in filter_events_for_client
    event_id_to_state = await storage.state.get_state_for_events(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/logging/opentracing.py", line 896, in _wrapper
    return await func(*args, **kwargs)  # type: ignore[misc]
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/controllers/state.py", line 230, in get_state_for_events
    return {event: event_to_state[event] for event in event_ids}
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/controllers/state.py", line 230, in <dictcomp>
    return {event: event_to_state[event] for event in event_ids}
KeyError: '$zqbvdmHXFOK5gmQxEA-Hr-8K4aaszIu-0HtC0E82k6A'
```

**Comment by DMRobertson** [comment]
> ### Database
> 
> official docker image for postgres:11

Can you please provide answers to the following from the issue form:

> are you using a single PostgreSQL server
> or [separate servers for main and state](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#databases)?
>  have you previously ported from SQLite using the Synapse "portdb" script?
>  have you previously restored from a backup?

> Element Android after upgrading from 1.5.11 to 1.5.18 stopped being able to connect. It started a new "sync" after upgrade and it got stuck on it.

If you downgrade to Element Android 1.5.11, does the sync work correctly again?

**Comment by Fenisu** [comment]
My bad, I thought it was implied. It is a single postgresql instance, no separate databases. 

The database was ported from SQLite, to postresql 10 and then, backed up and restored to postgresql 11 when v10 got deprecated. 

Some testing:
A new clean user on latest Element web client works. Old users still don't. 

Working user on Element Android 1.5.11, after resetting app and login in again, it gets stuck syncing and same KeyErrors come up. 

Apparently it has nothing to do with the new clients.

**Comment by DMRobertson** [comment]
Hmm. Any idea when you ported from SQLite? There were some bugs in the portdb script (#13426) and I'm wondering if you might've been affected by that.

**Comment by Fenisu** [comment]
I see.

I did it around 2021-02. I don't know what synapse or portdb version it was.

Any easy way of checking if that, is the problem?
It has been running fine at least until November 2022 I wouldsay, (1y 10months). What triggered the issue now?

**Comment by DMRobertson** [comment]
> What triggered the issue now?

Good question. Do you have [retention](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#retention) enabled on your HS? That has been known to cause inconsistencies in the database in the past.

What do the following DB queries produce?

```sql
SELECT * FROM background_updates;
SELECT * FROM events WHERE event_id = '$zqbvdmHXFOK5gmQxEA-Hr-8K4aaszIu-0HtC0E82k6A';
```

**Comment by H-Shay** [comment]
Is this still an issue?

**Comment by H-Shay** [comment]
I am going to close this for now due to lack of activity, we can reopen if the issue persists.
