### ISSUE TITLE
Internal server error when calling /relations with a token from /sync

### ISSUE THREAD

**Issue by clokep** [matrix-org/synapse#14830]
```
2023-01-12 16:41:20,025 - synapse.http.server - 124 - ERROR - GET-832933- Failed handle request via 'RelationPaginationServlet': <XForwardedForRequest at 0x7f5a7a2c98c0 method='GET' uri='/_matrix/client/v1/rooms/!test%3Amatrix.org/relations/%24foo/m.thread?dir=b&limit=20&from=sXXXX_1_YYY_ZZZ_AAA_BBB_CCC_DDD_0' clientproto='HTTP/1.1' site='8008'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/util/caches/descriptors.py", line 243, in _wrapped
    ret = cache.get(cache_key, callback=invalidate_callback)
  File "/usr/local/lib/python3.9/site-packages/synapse/util/caches/deferred_cache.py", line 180, in get
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 307, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.9/site-packages/synapse/http/server.py", line 513, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.9/site-packages/synapse/rest/client/relations.py", line 71, in on_GET
    result = await self._relations_handler.get_relations(
  File "/usr/local/lib/python3.9/site-packages/synapse/handlers/relations.py", line 125, in get_relations
    related_events, next_token = await self._main_store.get_relations_for_event(
  File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1697, in _inlineCallbacks
    result = context.run(gen.send, result)
  File "/usr/local/lib/python3.9/site-packages/synapse/storage/databases/main/relations.py", line 213, in get_relations_for_event
    from_token=from_token.room_key.as_historical_tuple()
  File "/usr/local/lib/python3.9/site-packages/synapse/types.py", line 569, in as_historical_tuple
    raise Exception(
Exception: Cannot call `RoomStreamToken.as_historical_tuple` on live token
```

https://sentry.tools.element.io/organizations/element/issues/58936/

**Comment by clokep** [comment]
Reported by @justjanne, trying to use a token from `/sync` when paginating `/relations`, which should be allowed (df36945ff0e4a293a9dac0da07e2c94256835b32).

**Comment by clokep** [comment]
Related to #13862, I think.

**Comment by clokep** [comment]
The way the pagination clause is generated is slightly incorrect, as #13862 kind of talks about. We need to abstract / port from `/messages`, something like this:

https://github.com/matrix-org/synapse/blob/84ce93c12f921063bb6c59400fcf95649a1b7f45/synapse/storage/databases/main/stream.py#L1284-L1315

I have a branch that attempts to do this but is *very* bitrotted. I need to recreate it (or rebase it).
