### ISSUE TITLE
Assertion error on startup in 1.76

### ISSUE THREAD

**Issue by msirringhaus** [matrix-org/synapse#15010]
### Description

I've updated from 1.74 to 1.76 and now on startup get
```
2023-02-07 09:40:49,117 - root - 344 - WARNING - main - ***** STARTING SERVER *****
2023-02-07 09:40:49,118 - root - 348 - WARNING - main - Server /home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.76.0
2023-02-07 09:40:51,594 - synapse.metrics.background_process_metrics - 246 - ERROR - _handle_new_device_update_async-0 - Background process '_handle_new_device_update_async' threw an exception
Traceback (most recent call last):
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 242, in run
    return await func(*args, **kwargs)
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/handlers/device.py", line 726, in _handle_new_device_update_async
    assert max_stream_id == stream_id
AssertionError
```

Restarting yields the same error.

Otherwise, the server seems to work fine.

### Steps to reproduce

- Upgrade synapse
- and just start it

### Homeserver

self-hosted

### Synapse Version

1.76

### Installation Method

pip (from PyPI)

### Database

Postgresql

### Workers

Single process

### Platform

Raspberry Pi, Rasbian 10

### Relevant log output

```shell
2023-02-07 09:40:49,117 - root - 344 - WARNING - main - ***** STARTING SERVER *****
2023-02-07 09:40:49,118 - root - 348 - WARNING - main - Server /home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.76.0
2023-02-07 09:40:51,594 - synapse.metrics.background_process_metrics - 246 - ERROR - _handle_new_device_update_async-0 - Background process '_handle_new_device_update_async' threw an exception
Traceback (most recent call last):
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 242, in run
    return await func(*args, **kwargs)
  File "/home/matrix/synapse/env37/lib/python3.7/site-packages/synapse/handlers/device.py", line 726, in _handle_new_device_update_async
    assert max_stream_id == stream_id
AssertionError
```

**Comment by erikjohnston** [comment]
I think this is due to us inserting a stream ID into `device_lists_changes_converted_stream_position` which wasn't persisted in any of the other tables (which is valid, though I'm a bit surprised anyone has hit that case).
