### ISSUE TITLE
twisted.python.failure.Failure OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by nishant378** [matrix-org/synapse#15058]
**Required logs**
Traceback (most recent call last):
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/[server.py](http://server.py/)", line 368, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/[server.py](http://server.py/)", line 574, in _async_render
    callback_return = await raw_callback_return
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/rest/client/[login.py](http://login.py/)", line 653, in on_POST
    body = await self._http_client.post_raw(uri, args)
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/[client.py](http://client.py/)", line 499, in post_raw
    response = await self.request(
  File "/root/matrix-backend-repo/riot-matrix/synapse/synapse/http/[client.py](http://client.py/)", line 444, in request
    response = await make_deferred_yieldable(request_deferred)
twisted.web._newclient.RequestTransmissionFailed: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('STORE routines', '', 'unregistered scheme'), ('system library', '', ''), ('SSL routines', '', 'certificate verify failed')]>]

**Comment by DMRobertson** [comment]
> certificate verify failed

I would guess that either there is something wrong with your certificates, or else you Synapse cannot see your certificates.

In the future, please:
- Ask in the [Synapse Admins](https://matrix.to/#/#synapse:matrix.org) room for support requests. If your homeserver is inoperable at the moment, you can sign up for an account on the Matrix.org homeserver in order to reach the support room.
- If you believe you have found a bug,  use the bug report template to report it.

I suggest we leave this open as an enhancement request to have a user-friendly certificate check on startup.
