### ISSUE TITLE
Complement flake: `TestRoomCanonicalAlias/Parallel/m.room.canonical_alias_accepts_present_aliases`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/synapse#15106]
https://github.com/matrix-org/synapse/actions/runs/4215073441/jobs/7315978852

```
      apidoc_room_alias_test.go:53: SendEventSynced waiting for event ID $DsKjBLrDBTjIVQB25Ymwtnlg9UhNRCi_UttWeDGkIPE
      apidoc_room_alias_test.go:53: CSAPI.MustDoFunc GET http://127.0.0.1:32902/_matrix/client/v3/sync?timeout=1000 returned non-2xx code: 500 Internal Server Error - body: {"errcode":"M_UNKNOWN","error":"Internal server error"}
```

**Comment by DMRobertson** [comment]
Logs: https://github.com/matrix-org/synapse/actions/runs/4215073441/jobs/7315978852#step:6:5157

```
synapse_main | 2023-02-19 07:20:03,619 - synapse.http.server - 123 - ERROR - GET-19 - Failed handle request via 'SyncRestServlet': <SynapseRequest at 0x7ff71fda8f50 method='GET' uri='/_matrix/client/v3/sync?timeout=1000' clientproto='HTTP/1.0' site='8080'>
  synapse_main | Traceback (most recent call last):
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
  synapse_main |     result = context.run(
  synapse_main |              ^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
  synapse_main |     return g.throw(self.type, self.value, self.tb)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/util/caches/response_cache.py", line 252, in cb
  synapse_main |     return await callback(*args, **kwargs)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 373, in _wait_for_sync_for_user
  synapse_main |     result: SyncResult = await self.current_sync_for_user(
  synapse_main |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 424, in current_sync_for_user
  synapse_main |     sync_result = await self.generate_sync_result(
  synapse_main |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 1488, in generate_sync_result
  synapse_main |     ) = await self._generate_sync_entry_for_rooms(sync_result_builder)
  synapse_main |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 1957, in _generate_sync_entry_for_rooms
  synapse_main |     await concurrently_execute(handle_room_entries, room_entries, 10)
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/util/async_helpers.py", line 247, in concurrently_execute
  synapse_main |     await yieldable_gather_results(
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/util/async_helpers.py", line 304, in yieldable_gather_results
  synapse_main |     raise dfe.subFailure.value from None
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
  synapse_main |     result = context.run(
  synapse_main |              ^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
  synapse_main |     return g.throw(self.type, self.value, self.tb)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/util/async_helpers.py", line 233, in _concurrently_execute_inner
  synapse_main |     await maybe_awaitable(func(value))
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 1946, in handle_room_entries
  synapse_main |     await self._generate_room_entry(
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 2498, in _generate_room_entry
  synapse_main |     notifs = await self.unread_notifs_for_room_id(room_id, sync_config)
  synapse_main |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/handlers/sync.py", line 1301, in unread_notifs_for_room_id
  synapse_main |     return await self.store.get_unread_event_push_actions_by_room_for_user(
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
  synapse_main |     result = context.run(
  synapse_main |              ^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
  synapse_main |     return g.throw(self.type, self.value, self.tb)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_push_actions.py", line 635, in get_unread_event_push_actions_by_room_for_user
  synapse_main |     return await self.db_pool.runInteraction(
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 883, in runInteraction
  synapse_main |     return await delay_cancellation(_runInteraction())
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
  synapse_main |     result = context.run(
  synapse_main |              ^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
  synapse_main |     return g.throw(self.type, self.value, self.tb)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 850, in _runInteraction
  synapse_main |     result = await self.runWithConnection(
  synapse_main |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 978, in runWithConnection
  synapse_main |     return await make_deferred_yieldable(
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext
  synapse_main |     result = inContext.theWork()  # type: ignore[attr-defined]
  synapse_main |              ^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
  synapse_main |     inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  synapse_main |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
  synapse_main |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
  synapse_main |     return func(*args, **kw)
  synapse_main |            ^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
  synapse_main |     result = func(conn, *args, **kw)
  synapse_main |              ^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 971, in inner_func
  synapse_main |     return func(db_conn, *args, **kwargs)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 712, in new_transaction
  synapse_main |     r = func(cursor, *args, **kwargs)
  synapse_main |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_push_actions.py", line 672, in _get_unread_counts_by_receipt_txn
  synapse_main |     return self._get_unread_counts_by_pos_txn(
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/event_push_actions.py", line 809, in _get_unread_counts_by_pos_txn
  synapse_main |     txn.execute(
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 388, in execute
  synapse_main |     self._do_execute(self.txn.execute, sql, *args)
  synapse_main |   File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 436, in _do_execute
  synapse_main |     return func(sql, *args, **kwargs)
  synapse_main |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  synapse_main | psycopg2.errors.InternalError_: could not open file "base/13444/17474": Interrupted system call
  synapse_main | 

```

In particular `Interrupted system call` doesn't sound very happy. Have we tried to shut down the postgres container maybe?

**Comment by squahtx** [comment]
From memory, `Interrupted system call` is the description for `EINTR`, which is sometimes returned from syscalls. When an application sees it, it's generally supposed to retry the syscall ([`open`](https://man7.org/linux/man-pages/man2/open.2.html) in this case?).

There is a mailing list thread about a similar postgres issue on macOS, where
[a postgres developer says that it's _very unusual_ for `open` to return `EINTR`](https://www.postgresql.org/message-id/20210115210548.zfbnulfeanmffmet%40alap3.anarazel.de)
and [it sounds like they're reluctant to wrap every instance of `open` in retry loops](https://www.postgresql.org/message-id/20210122172400.eiao4kgzhhpmtb5y%40alap3.anarazel.de).

So this sounds like a) a bug in postgres sounds and b) it just shouldn't happen on Linux?

Relatedly, when registering a signal handler, there is an `SA_RESTART` flag for controlling whether the syscall it interrupts returns `EINTR` or automatically retries: https://www.gnu.org/software/libc/manual/html_node/Flags-for-Sigaction.html

**Comment by DMRobertson** [comment]
Thanks for your thorough digging. Sounds like this is rare enough and not something we can easily workaround. Suggest closing as WONTFIX?

**Comment by DMRobertson** [comment]
Saw this again --- odd. https://github.com/matrix-org/synapse/actions/runs/4404737932/jobs/7714825849
