### ISSUE TITLE
matrix.org can't join #libera:libera.chat

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#15115]
### Description

The CS API /join times out with a 524.  The serverside doesn't seem to log anything sensible (looking at the event_creator_users worker).

It looks like we're not logging a response due to the client having disconnected (which seems strange; i thought we logged the response whatever).  Meanwhile, something is silently wedging solid after looking up the alias - perhaps getting stuck on a lineariser lock for the room or something?

### Steps to reproduce

- try to join #libera:libera.chat from a matrix.org account.

### Homeserver

matrix.org

### Synapse Version

{"server_version":"1.77.0rc1 (b=matrix-org-hotfixes,19bb342763)","python_version":"3.8.12"}

### Installation Method

pip (from PyPI)

### Database

postgres

### Workers

Multiple workers

### Platform

linux

### Relevant log output

```shell
$ cat event_creator_users*.log | grep POST-79cb5c3c0a0d06b6-LHR
2023-02-21 00:28:08,977 - synapse.http.federation.well_known_resolver - 253 - INFO - POST-79cb5c3c0a0d06b6-LHR- - Fetching https://libera.chat/.well-known/matrix/server
2023-02-21 00:28:08,988 - synapse.http.federation.well_known_resolver - 190 - INFO - POST-79cb5c3c0a0d06b6-LHR- - Response from .well-known: {'m.server': 'libera.ems.host:443'}
2023-02-21 00:28:09,061 - synapse.http.matrixfederationclient - 299 - INFO - POST-79cb5c3c0a0d06b6-LHR - {GET-O-961343} [libera.chat] Completed request: 200 OK in 0.08 secs, got 71 bytes - GET matrix://libera.chat/_matrix/federation/v1/query/directory?room_alias=%23libera%3Alibera.chat
2023-02-21 00:31:08,975 - synapse.http.site - 372 - INFO - POST-79cb5c3c0a0d06b6-LHR - Connection from client lost before response was sent
```

### Anything else that would be useful to know?

This is causing avoidable drama with Libera.

**Comment by reivilibre** [comment]
> It looks like we're not logging a response due to the client having disconnected (which seems strange; i thought we logged the response whatever).

You're right, we do log nonetheless, so the lack of a processed line is suspicious. Maybe the request is still ongoing, maybe the log context has been eaten, or quite possibly something else I haven't thought of.

**Comment by reivilibre** [comment]
Since the last message, it's pretty clear that the requests were just getting stuck in a lineariser because there were earlier joins stuck in the critical section waiting for full-state (and the room is stuck in partial-state!). That has likely been fixed by upgrading Matrix.org to what has now been marked as v1.78.0rc1 (m.org was on an old version of Synapse that did not support joins during partial state, at the time of this issue).

However the room is **still** stuck in partial state. This seems to be because:

* libera.chat is timing out whilst answering `/state/`
* other resident servers are returning 403 (possibly: they are not aware of our join or they are only partially resident themselves. I don't know what the situation is and don't have access to their databases, to be able to answer.)

We don't retry `/state/`, or at least not often enough to maybe take advantage of a potential response cache.

Some logs from the startup today:

```
2023-02-21 15:15:02,379 - synapse.handlers.federation - 1886 - INFO - sync_partial_state_room-24 - Syncing state for room !fuzEIyMtiFYSFEjRCI:libera.chat via libera.chat
2023-02-21 15:15:03,683 - synapse.handlers.federation_event - 627 - INFO - sync_partial_state_room-24 - Updating state for $0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4
2023-02-21 15:15:04,740 - synapse.handlers.federation_event - 1068 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4- - Event $0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4 is missing prev_events ['$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE']: calculating state for a backwards extremity
2023-02-21 15:15:04,741 - synapse.handlers.federation_event - 1098 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4- - Requesting state after missing prev_event $-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE
2023-02-21 15:15:04,742 - synapse.http.federation.well_known_resolver - 253 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE--- - Fetching https://libera.chat/.well-known/matrix/server
2023-02-21 15:15:08,103 - synapse.http.federation.well_known_resolver - 190 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE--- - Response from .well-known: {'m.server': 'libera.ems.host:443'}
2023-02-21 15:15:56,594 - synapse.http.matrixfederationclient - 299 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE-- - {GET-O-32} [libera.chat] Completed request: 200 OK in 51.85 secs, got 32615447 bytes - GET matrix://libera.chat/_matrix/federation/v1/state_ids/%21fuzEIyMtiFYSFEjRCI%3Alibera.chat?event_id=%24-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE
2023-02-21 15:19:15,208 - synapse.http.matrixfederationclient - 629 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE---- - {GET-O-24018} [libera.chat] Got response headers: 502 Bad Gateway
2023-02-21 15:19:15,208 - synapse.http.matrixfederationclient - 672 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE---- - {GET-O-24018} [libera.chat] Request failed: GET matrix://libera.chat/_matrix/federation/v1/state/%21fuzEIyMtiFYSFEjRCI%3Alibera.chat?event_id=%24-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE: HttpResponseException('502: Bad Gateway')
2023-02-21 15:19:15,208 - synapse.util.retryutils - 231 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4--$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE--- - Connection to libera.chat was unsuccessful (<class 'synapse.api.errors.RequestSendFailed'>(Failed to send request: HttpResponseException: 502: Bad Gateway)); backoff now 600000
2023-02-21 15:19:15,209 - synapse.handlers.federation_event - 1122 - WARNING - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4- - Error attempting to resolve state at missing prev_events: Failed to send request: HttpResponseException: 502: Bad Gateway
2023-02-21 15:19:15,209 - synapse.handlers.federation - 1973 - INFO - sync_partial_state_room-24 - Failed to get state for !fuzEIyMtiFYSFEjRCI:libera.chat at <FrozenEventV3 event_id=$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4, type=m.room.member, state_key=@diskdance:matrix.org, outlier=False> from libera.chat because ERROR 403: We can't get valid state history.
2023-02-21 15:19:15,209 - synapse.handlers.federation - 1981 - INFO - sync_partial_state_room-24 - Syncing state for room !fuzEIyMtiFYSFEjRCI:libera.chat via matrix.org instead
2023-02-21 15:19:15,209 - synapse.handlers.federation_event - 627 - INFO - sync_partial_state_room-24 - Updating state for $0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4
2023-02-21 15:19:15,750 - synapse.handlers.federation_event - 1068 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4- - Event $0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4 is missing prev_events ['$-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE']: calculating state for a backwards extremity
2023-02-21 15:19:15,751 - synapse.handlers.federation_event - 1098 - INFO - sync_partial_state_room-24-$0IdYaOlZVqiCRRb1EF4jXCsxIsE4eW1KPm_etjY8FM4- - Requesting state after missing prev_event $-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE
2023-02-21 15:19:15,752 - synapse.http.federation.well_known_resolver - 253 - INFO - sync_partial_state_room-
...
```

502 Bad Gateway sounds like it's the loadbalancer or Cloudflare (if applicable) cutting us off after some time.

I can't actually find that exact request — `federation/v1/state/%21fuzEIyMtiFYSFEjRCI%3Alibera.chat?event_id=%24-aFRBQqhtO1GtE_mNaZLVm6cCcoQriQANKshvF8ZQaE` — in the Libera logs (?!?!) but I can find some similar ones and note that some of them take roughly ~1800 seconds (30 min).

I'm not sure what FRRJ is buying us here: it's requesting the full state at a point in the room. This returns the same amount of data as a non-FRRJ `/send_join` would have — I think?

I will look at the situation on Libera further to see whether there's any real reason for it taking so long.

**Comment by reivilibre** [comment]
Possibly because of my conveniently-timed restart, the initial part of the resync went through earlier and it moved on to doing further `/state` requests.

However, there's a problem: the room state is too big (the response > 500 MiB) and it's hitting a response body size limit:

```
federation_inbound4.log:2023-02-21 16:02:34,329 - synapse.http.matrixfederationclient - 240 - WARNING - _process_incoming_pdus_in_room_inner-41-$9smLiG7QFK54RlCkbKxtv3fP51S9Fpof7gx34bhvVdI---$inr3_5AH_4CTwJyBza-ZrWP4Qo3i_QvMEilMW_E9pBU---$_M55QrVpzz9THIgUgngswj99-Z6JPa5XGBQ-xr7q1h4--- - {GET-O-22420} [libera.chat] JSON response exceeded max size 524288000 - GET matrix://libera.chat/_matrix/federation/v1/state/%21fuzEIyMtiFYSFEjRCI%3Alibera.chat?event_id=%24_M55QrVpzz9THIgUgngswj99-Z6JPa5XGBQ-xr7q1h4
```

```python
    # As with /send_join, /state responses can be huge.
    MAX_RESPONSE_SIZE = 500 * 1024 * 1024
```

**Comment by JeanPaulLucien** [comment]
> * try to join #libera:libera.chat from a matrix.org account.

I have joined.

**Comment by JeanPaulLucien** [comment]
> 524


```
Access to fetch at 'https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fuzEIyMtiFYSFEjRCI%3Alibera.chat/members?not_membership=leave&at=...' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
fetch.ts:62          

GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!fuzEIyMtiFYSFEjRCI%3Alibera.chat/members?not_membership=leave&at=... net::ERR_FAILED 524
fetch @ fetch.ts:62
requestOtherUrl @ fetch.ts:264
request @ fetch.ts:205
authedRequest @ fetch.ts:156
members @ client.ts:7868
loadMembersFromServer @ room.ts:887
loadMembers @ room.ts:902
await in loadMembers (async)
loadMembersIfNeeded @ room.ts:941
loadMembersIfJoined @ RoomView.tsx:1269
(anonymous) @ RoomView.tsx:1392
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:153
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1439
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1290
await in processSyncResponse (async)
doSync @ sync.ts:918
rageshake.ts:73 

Fetching room members for !fuzEIyMtiFYSFEjRCI:libera.chat failed. Room members will appear incomplete.
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
loadMembersIfJoined @ RoomView.tsx:1276
rageshake.ts:73 

ConnectionError: fetch failed: Failed to fetch
    at p.requestOtherUrl (fetch.ts:281:19)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
loadMembersIfJoined @ RoomView.tsx:1277
rageshake.ts:73 

Fetching room members for !fuzEIyMtiFYSFEjRCI:libera.chat failed. Room members will appear incomplete.
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
loadMembersIfJoined @ RoomView.tsx:1276
rageshake.ts:73 

ConnectionError: fetch failed: Failed to fetch
    at p.requestOtherUrl (fetch.ts:281:19)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
loadMembersIfJoined @ RoomView.tsx:1277
rageshake.ts:73 

ConnectionError: fetch failed: Failed to fetch
    at p.requestOtherUrl (fetch.ts:281:19)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
(anonymous) @ room.ts:976
rageshake.ts:73 

error after clearing loaded members from room !fuzEIyMtiFYSFEjRCI:libera.chat after leaving
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
(anonymous) @ room.ts:1002
rageshake.ts:73 

/sync error AbortError: The user aborted a request.
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
onSyncError @ sync.ts:1040
doSync @ sync.ts:888
EmZNCyyjUslQyYTpmKFNvJgK:1          

GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/EmZNCyyjUslQyYTpmKFNvJgK?width=32&height=32&method=crop 404
Image (async)
y @ react-dom.production.min.js:23
ss @ react-dom.production.min.js:208
Al @ react-dom.production.min.js:251
Ol @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Fl @ react-dom.production.min.js:250
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
Aa @ react-dom.production.min.js:170
(anonymous) @ BaseAvatar.tsx:93
n @ useEventEmitter.ts:50
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
onSyncError @ sync.ts:1061
doSync @ sync.ts:888
ZvxTGVUiEaKYNHvdQMXBpRrz:1          

GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/ZvxTGVUiEaKYNHvdQMXBpRrz?width=32&height=32&method=crop 400
Image (async)
y @ react-dom.production.min.js:23
ss @ react-dom.production.min.js:208
Al @ react-dom.production.min.js:251
Ol @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Fl @ react-dom.production.min.js:250
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
Aa @ react-dom.production.min.js:170
(anonymous) @ BaseAvatar.tsx:93
n @ useEventEmitter.ts:50
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
onSyncError @ sync.ts:1061
doSync @ sync.ts:888
ZvxTGVUiEaKYNHvdQMXBpRrz:1          GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/ZvxTGVUiEaKYNHvdQMXBpRrz?width=32&height=32&method=crop 400
EmZNCyyjUslQyYTpmKFNvJgK:1          GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/EmZNCyyjUslQyYTpmKFNvJgK?width=32&height=32&method=crop 404
EmZNCyyjUslQyYTpmKFNvJgK:1          GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/EmZNCyyjUslQyYTpmKFNvJgK?width=32&height=32&method=crop 404
Image (async)
y @ react-dom.production.min.js:23
ss @ react-dom.production.min.js:208
Al @ react-dom.production.min.js:251
Ol @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Fl @ react-dom.production.min.js:250
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
Aa @ react-dom.production.min.js:170
(anonymous) @ BaseAvatar.tsx:93
n @ useEventEmitter.ts:50
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
doSync @ sync.ts:944
ZvxTGVUiEaKYNHvdQMXBpRrz:1          GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/ZvxTGVUiEaKYNHvdQMXBpRrz?width=32&height=32&method=crop 400
Image (async)
y @ react-dom.production.min.js:23
ss @ react-dom.production.min.js:208
Al @ react-dom.production.min.js:251
Ol @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Fl @ react-dom.production.min.js:250
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
Aa @ react-dom.production.min.js:170
(anonymous) @ BaseAvatar.tsx:93
n @ useEventEmitter.ts:50
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
doSync @ sync.ts:944
rageshake.ts:73 !QVGzddUWpPdvanbeBp:libera.chat is reportedly new but is already known - assuming TagChange instead
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
handleRoomUpdate @ Algorithm.ts:619
handleRoomUpdate @ RoomListStore.ts:362
onDispatchMyMembership @ RoomListStore.ts:322
onDispatchAsync @ RoomListStore.ts:287
(anonymous) @ RoomListStore.ts:187
(anonymous) @ setImmediate.js:40
y @ setImmediate.js:69
a @ setImmediate.js:109
postMessage (async)
r @ setImmediate.js:120
p.setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:187
onDispatch @ AsyncStoreWithClient.ts:66
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
r @ MatrixActionCreators.ts:327
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1439
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1290
await in processSyncResponse (async)
doSync @ sync.ts:918
ab89297ea4e20c10d9b9d4c435400243c2516b48:1          GET https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/kde.org/ab89297ea4e20c10d9b9d4c435400243c2516b48?width=24&height=24&method=crop 400
Image (async)
y @ react-dom.production.min.js:23
ss @ react-dom.production.min.js:208
Al @ react-dom.production.min.js:251
Ol @ react-dom.production.min.js:250
Dl @ react-dom.production.min.js:250
Fl @ react-dom.production.min.js:250
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
(anonymous) @ react-dom.production.min.js:244
Me @ react-dom.production.min.js:292
Ue @ react-dom.production.min.js:49
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Jt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Ne @ react-dom.production.min.js:292
Qt @ react-dom.production.min.js:73
rageshake.ts:73 !QVGzddUWpPdvanbeBp:libera.chat is reportedly new but is already known - assuming TagChange instead
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
handleRoomUpdate @ Algorithm.ts:619
handleRoomUpdate @ RoomListStore.ts:362
onDispatchMyMembership @ RoomListStore.ts:322
onDispatchAsync @ RoomListStore.ts:287
(anonymous) @ RoomListStore.ts:187
(anonymous) @ setImmediate.js:40
y @ setImmediate.js:69
a @ setImmediate.js:109
postMessage (async)
r @ setImmediate.js:120
p.setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:187
onDispatch @ AsyncStoreWithClient.ts:66
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
r @ MatrixActionCreators.ts:327
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1439
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1290
await in processSyncResponse (async)
doSync @ sync.ts:918
rageshake.ts:73 Degrading performance to find missing room in "im.vector.fake.archived": !QVGzddUWpPdvanbeBp:libera.chat
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
getRoomIndex @ OrderingAlgorithm.ts:77
handleSplice @ ImportanceAlgorithm.ts:133
handleRoomUpdate @ ImportanceAlgorithm.ts:151
handleRoomUpdate @ Algorithm.ts:664
handleRoomUpdate @ RoomListStore.ts:362
onDispatchMyMembership @ RoomListStore.ts:322
onDispatchAsync @ RoomListStore.ts:287
(anonymous) @ RoomListStore.ts:187
(anonymous) @ setImmediate.js:40
y @ setImmediate.js:69
a @ setImmediate.js:109
postMessage (async)
r @ setImmediate.js:120
p.setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:187
onDispatch @ AsyncStoreWithClient.ts:66
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
r @ MatrixActionCreators.ts:327
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1439
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1290
await in processSyncResponse (async)
doSync @ sync.ts:918
rageshake.ts:73 Tried to remove unknown room from im.vector.fake.archived: !QVGzddUWpPdvanbeBp:libera.chat
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
handleSplice @ ImportanceAlgorithm.ts:135
handleRoomUpdate @ ImportanceAlgorithm.ts:151
handleRoomUpdate @ Algorithm.ts:664
handleRoomUpdate @ RoomListStore.ts:362
onDispatchMyMembership @ RoomListStore.ts:322
onDispatchAsync @ RoomListStore.ts:287
(anonymous) @ RoomListStore.ts:187
(anonymous) @ setImmediate.js:40
y @ setImmediate.js:69
a @ setImmediate.js:109
postMessage (async)
r @ setImmediate.js:120
p.setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:187
onDispatch @ AsyncStoreWithClient.ts:66
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
r @ MatrixActionCreators.ts:327
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1439
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1290
await in processSyncResponse (async)
doSync @ sync.ts:918
rageshake.ts:73 Degrading performance to find missing room in "im.vector.fake.recent": !QVGzddUWpPdvanbeBp:libera.chat
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
getRoomIndex @ OrderingAlgorithm.ts:77
handleSplice @ ImportanceAlgorithm.ts:133
handleRoomUpdate @ ImportanceAlgorithm.ts:151
handleRoomUpdate @ Algorithm.ts:664
handleRoomUpdate @ RoomListStore.ts:362
onDispatchMyMembership @ RoomListStore.ts:335
onDispatchAsync @ RoomListStore.ts:287
(anonymous) @ RoomListStore.ts:187
(anonymous) @ setImmediate.js:40
y @ setImmediate.js:69
a @ setImmediate.js:109
postMessage (async)
r @ setImmediate.js:120
p.setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:187
onDispatch @ AsyncStoreWithClient.ts:66
t._invokeCallback @ Dispatcher.js:214
t.dispatch @ Dispatcher.js:189
setTimeout (async)
dispatch @ dispatcher.ts:52
r @ MatrixActionCreators.ts:327
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
t @ ReEmitter.ts:53
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateMyMembership @ room.ts:881
recalculate @ room.ts:2853
(anonymous) @ sync.ts:1469
await in (anonymous) (async)
I @ utils.ts:438
await in I (async)
processSyncResponse @ sync.ts:1460
await in processSyncResponse (async)
doSync @ sync.ts:918
rageshake.ts:73 

Tried to remove unknown room from im.vector.fake.recent: !QVGzddUWpPdvanbeBp:libera.chat



```

**Comment by JeanPaulLucien** [comment]
```
GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!QVGzddUWpPdvanbeBp%3Alibera.chat/members?not_membership=leave&at=... 403
fetch @ fetch.ts:62

rageshake.ts:73 
Fetching room members for !QVGzddUWpPdvanbeBp:libera.chat failed. Room members will appear incomplete.
e.<computed> @ rageshake.ts:73

rageshake.ts:73 
M_FORBIDDEN: MatrixError: [403] User ... not allowed to view events in room !QVGzddUWpPdvanbeBp:libera.chat at token StreamToken(room_key=

rageshake.ts:73 
M_FORBIDDEN: MatrixError: [403] User ... not allowed to view events in room !QVGzddUWpPdvanbeBp:libera.chat at token StreamToken(room_key=

rageshake.ts:73 
error after clearing loaded members from room !QVGzddUWpPdvanbeBp:libera.chat after leaving
e.<computed> @ rageshake.ts:73

://vector/webapp/#/room/!QVGzddUWpPdvanbeBp:libera.chat:1 
Access to fetch at 'https://matrix-client.matrix.org/_matrix/client/r0/rooms/!yVrWGxdEhxMmOroYWW%3Alibera.chat/members?not_membership=leave&at=...' from origin 'vector://vector' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

fetch.ts:62          
GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!yVrWGxdEhxMmOroYWW%3Alibera.chat/members?not_membership=leave&at=... net::ERR_FAILED 502
```

**Comment by progval** [comment]
@JeanPaulLucien This is not a client issue, no need to provide client logs

**Comment by JeanPaulLucien** [comment]
@progval I know that this is not client issue. Element Desktop shows logs from server.
