### ISSUE TITLE
Debian Buster: Exception: Error while initialising OIDC provider 'oidc-microsoft'

### ISSUE THREAD

**Issue by linuxmail** [matrix-org/synapse#15267]
### Description

We had with matrix-synapse-py3 (1.71.0+buster1) the issue, that we were not able anymore to login with Microsoft Azure and got the error:

```
2023-03-14 14:21:51,541 - synapse.http.client - 474 - INFO - GET-31697272- Error sending request to  POST https://login.microsoftonline.com/9e................................/oauth2/v2.0/token: RequestTransmissionFailed [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'certificate verify failed')]>]
```

So we upgraded to 1.78.0+buster1 and now, Synpase is not starting anymore, with:

```
Mar 14 15:00:35 ina-chat matrix-synapse[17417]: 2023-03-14 15:00:35,387 - root - 345 - WARNING - main- ***** STARTING SERVER *****
Mar 14 15:00:35 ina-chat matrix-synapse[17417]: 2023-03-14 15:00:35,387 - root - 349 - WARNING - main- Server /opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.71.0
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: 2023-03-14 15:00:36,000 - synapse.app._base - 255 - CRITICAL - sentinel- Error during startup
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: Traceback (most recent call last):
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 139, in load_metadata
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     await p.load_metadata()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 577, in load_metadata
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     return await self._provider_metadata.get()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 136, in get
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     return await self._cachedcall.get()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 106, in get
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     self._result.raiseException()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 504, in raiseException
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     raise self.value.with_traceback(self.tb)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     cast(Failure, result).throwExceptionIntoGenerator, gen
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     return g.throw(self.type, self.value, self.tb)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 126, in _wrapper
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     return await f()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 589, in _load_metadata
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     metadata_response = await self._http_client.get_json(url)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 605, in get_json
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     body = await self.get_raw(uri, args, headers=actual_headers)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 690, in get_raw
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     response = await self.request("GET", uri, headers=Headers(actual_headers))
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 457, in request
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     response = await make_deferred_yieldable(request_deferred)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     current.result, *args, **kwargs
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 803, in _timeout_to_request_timed_out_error
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     raise RequestTimedOutError("Timeout waiting for response from remote server")
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: The above exception was the direct cause of the following exception:
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: Traceback (most recent call last):
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 240, in wrapper
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     await cb(*args, **kwargs)
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 376, in start
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     await oidc.load_metadata()
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 145, in load_metadata
Mar 14 15:00:36 ina-chat matrix-synapse[17417]:     ) from e
Mar 14 15:00:36 ina-chat matrix-synapse[17417]: Exception: Error while initialising OIDC provider 'oidc-microsoft'
Mar 14 15:00:36 ina-chat systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 15:00:36 ina-chat systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
```

### Steps to reproduce

- Have Debian Buster  10.13
- Have  oidc-microsoft confugred
-  Upgrade Synapse from 1.71 to 1.78
- Have Azur as OpenID configured:

```
oidc_providers:
  - idp_id: microsoft
    idp_name: Microsoft
    issuer: "https://login.microsoftonline.com/9......................................./v2.0"
    client_id: "bb405ee9-977e-4788-b4e0-b13bf69b1042"
    client_secret: '<REDACTED>'
    scopes: ["openid", "profile"]
    authorization_endpoint: "https://login.microsoftonline.com/9................../oauth2/v2.0/authorize"
    token_endpoint: "https://login.microsoftonline.com/9......................................a/oauth2/v2.0/token"
    userinfo_endpoint: "https://graph.microsoft.com/oidc/userinfo"
    user_mapping_provider:
      config:
        localpart_template: "{{ user.preferred_username.split('@')[0] }}"
        display_name_template: "{{ user.name }}"
```

### Homeserver

another homeserver

### Synapse Version

{"server_version":"1.78.0","python_version":"3.7.3"}

### Installation Method

Debian packages from packages.matrix.org

### Database

Single PostgreSQL

### Workers

Single process

### Platform

VM Proxmox /  Debian Buster

### Relevant log output

```shell
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: --------------------------------------------------------------------------------
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: This server is configured to use 'matrix.org' as its trusted key server via the
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: server since it is long-lived, stable and trusted. However, some admins may
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: wish to use another server for this purpose.
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: To suppress this warning and continue using 'matrix.org', admins should set
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: --------------------------------------------------------------------------------
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: 2023-03-14 14:56:16,767 - root - 350 - WARNING - main- ***** STARTING SERVER *****
Mar 14 14:56:16 ina-chat matrix-synapse[14071]: 2023-03-14 14:56:16,768 - root - 354 - WARNING - main- Server /opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.78.0
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: 2023-03-14 14:56:17,376 - synapse.app._base - 257 - CRITICAL - sentinel- Error during startup
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: Traceback (most recent call last):
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 140, in load_metadata
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     await p.load_metadata()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 588, in load_metadata
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     return await self._provider_metadata.get()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 136, in get
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     return await self._cachedcall.get()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 106, in get
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     self._result.raiseException()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 504, in raiseException
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     raise self.value.with_traceback(self.tb)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1694, in _inlineCallbacks
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     cast(Failure, result).throwExceptionIntoGenerator, gen
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     return g.throw(self.type, self.value, self.tb)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/cached_call.py", line 126, in _wrapper
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     return await f()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 600, in _load_metadata
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     metadata_response = await self._http_client.get_json(url)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 608, in get_json
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     body = await self.get_raw(uri, args, headers=actual_headers)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 693, in get_raw
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     response = await self.request("GET", uri, headers=Headers(actual_headers))
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 460, in request
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     response = await make_deferred_yieldable(request_deferred)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 893, in _runCallbacks
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     current.result, *args, **kwargs
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/client.py", line 806, in _timeout_to_request_timed_out_error
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     raise RequestTimedOutError("Timeout waiting for response from remote server")
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: The above exception was the direct cause of the following exception:
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: Traceback (most recent call last):
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 242, in wrapper
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     await cb(*args, **kwargs)
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 352, in start
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     await oidc.load_metadata()
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/oidc.py", line 146, in load_metadata
Mar 14 14:56:17 ina-chat matrix-synapse[14071]:     ) from e
Mar 14 14:56:17 ina-chat matrix-synapse[14071]: Exception: Error while initialising OIDC provider 'oidc-microsoft'
Mar 14 14:56:17 ina-chat systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by DMRobertson** [comment]
@linuxmail you have publicly posted your `client_secret`. I have edited your post to redact it and deleted the previous copies, but you should consider the secret compromised and rotate it.

**Comment by linuxmail** [comment]
Hi @DMRobertson 

thanks, but it was uuid-gen generated values 😊, not the real ones.

**Comment by MatMaul** [comment]
It is failing to get info from the metadata discovery endpoint [here](https://github.com/matrix-org/synapse/blob/release-v1.78/synapse/handlers/oidc.py#L600).

It is highly probable that this is related to your problem regarding certificate that you had before.
I can't really tell you much more, you should try to understand why synapse can't do a proper TLS request to `https://login.microsoftonline.com`, by trying with curl and a small python script using `requests` for example.

It doesn't look like a synapse bug.

**Comment by linuxmail** [comment]
@MatMaul,

you are right .. it was realy an certificate issue: the Digicerts which are used by Microsoft:

```
...
 openssl s_client -servername  login.microsoftonline.com -connect  login.microsoftonline.com:443
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify error:num=10:certificate has expired
notAfter=Mar  8 12:00:00 2023 GMT
verify return:1
....
```

Unfortunately, this certificate was deploy from us with Puppet, because it was required, before Debian added it to ca-certificates package. So, we removed the files and after a cleanup, it worked again.

Only pain was to get the idea, what is going wrong as the Exception from Python wasn't very helpful :-)
