### ISSUE TITLE
InvalidColumnReference on m.device_list_update

### ISSUE THREAD

**Issue by krombel** [matrix-org/synapse#15822]
### Description

I get several errors like the following and am wondering
1. if others might have the same and
2. how to resolve this

### Steps to reproduce

sadly I cannot tell...
It seems to be occuring when another server sends and `m.device_list_update`

### Homeserver

msg-net.de

### Synapse Version

1.86.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgresql 13

### Workers

Single process

### Platform

docker

### Configuration

-

### Relevant log output

```shell
2023-06-23 12:49:45,574 - synapse.federation.transport.server.federation - 105 - INFO - PUT-39414 - Received txn 1687509776961 from matrix.org. (PDUs: 0, EDUs: 3)
2023-06-23 12:49:45,578 - synapse.handlers.e2e_keys - 1623 - INFO - PUT-39414 - pending updates: [({'keys': {'ed25519:sNTlrUA8EsjalIKmYIAESeO/l6K2lq27EaHIzVr0SZA': 'sNTlrUA8EsjalIKmYIAESeO/l6K2lq27EaHIzVr0SZA'}, 'signatures': {}, 'usage': ['master'], 'user_id': '@user:matrix.org'}, None)]
2023-06-23 12:49:45,584 - synapse.handlers.device - 1119 - INFO - PUT-39414 - Received device list update for @n1ks:matrix.org, requiring resync: True. Devices: XFIIRUHJUU
2023-06-23 12:49:45,645 - synapse.handlers.e2e_keys - 1623 - INFO - PUT-39414 - pending updates: [({'keys': {'ed25519:sNTlrUA8EsjalIKmYIAESeO/l6K2lq27EaHIzVr0SZA': 'sNTlrUA8EsjalIKmYIAESeO/l6K2lq27EaHIzVr0SZA'}, 'signatures': {}, 'usage': ['master'], 'user_id': '@user:matrix.org'}, None)]
2023-06-23 12:49:46,434 - synapse.http.matrixfederationclient - 341 - INFO - PUT-39414 - {GET-O-50549} [matrix.org] Completed request: 200 OK in 0.85 secs, got 6556 bytes - GET matrix://matrix.org/_matrix/federation/v1/user/devices/%40user%3Amatrix.org
2023-06-23 12:49:46,441 - synapse.federation.federation_server - 1468 - ERROR - PUT-39414 - Failed to handle edu 'm.device_list_update'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/synapse/federation/federation_server.py", line 1464, in on_edu
    await handler(origin, content)
  File "/usr/local/lib/python3.11/site-packages/synapse/logging/opentracing.py", line 916, in _wrapper
    return await func(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/handlers/device.py", line 1093, in incoming_device_list_update
    await self._handle_device_updates(user_id)
  File "/usr/local/lib/python3.11/site-packages/synapse/util/metrics.py", line 113, in measured_func
    r = await func(self, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/handlers/device.py", line 1127, in _handle_device_updates
    await self.multi_user_device_resync([user_id])
  File "/usr/local/lib/python3.11/site-packages/synapse/handlers/device.py", line 1243, in multi_user_device_resync
    user_result, user_failed = await self._user_device_resync_returning_failed(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/handlers/device.py", line 1363, in _user_device_resync_returning_failed
    await self.store.update_remote_device_list_cache(
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/devices.py", line 1839, in update_remote_device_list_cache
    await self.db_pool.runInteraction(
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 930, in runInteraction
    return await delay_cancellation(_runInteraction())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    result = context.run(
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 896, in _runInteraction
    result = await self.runWithConnection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1025, in runWithConnection
    return await make_deferred_yieldable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    result = func(conn, *args, **kw)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1018, in inner_func
    return func(db_conn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 758, in new_transaction
    r = func(cursor, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/databases/main/devices.py", line 1871, in _update_remote_device_list_cache_txn
    self.db_pool.simple_upsert_txn(
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1291, in simple_upsert_txn
    return self.simple_upsert_txn_native_upsert(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 1431, in simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 417, in execute
    self._do_execute(self.txn.execute, sql, parameters)
  File "/usr/local/lib/python3.11/site-packages/synapse/storage/database.py", line 469, in _do_execute
    return func(sql, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

2023-06-23 12:49:46,498 - synapse.access.http.8009 - 461 - INFO - PUT-39414 - 2a00:1098:84:1c8::158 - 8009 - {matrix.org} Processed request: 0.930sec/0.001sec (0.044sec, 0.005sec) (0.015sec/0.076sec/6) 11B 200 "PUT /_matrix/federation/v1/send/1687509776961 HTTP/1.1" "Synapse/1.86.0 (b=matrix-org-hotfixes,fb8d629dcd)" [0 dbevts]
```

### Anything else that would be useful to know?

concerning numbers this might help:
```
# head logs/homeserver.log -n 1 | cut -d' ' -f -2; tail logs/homeserver.log -n 1 | cut -d' ' -f -2 ; grep InvalidColumnReference logs/homeserver.log | wc -l
2023-06-23 07:05:03,476
2023-06-23 13:22:04,045
239
```
=> 239 occurences in a little bit more than 6 hours

**Comment by erikjohnston** [comment]
This looks like the background update to add the index hasn't finished yet. Can you confirm if the following SQL returns anything?

```sql
SELECT * FROM background_updates WHERE update_name = 'device_lists_remote_extremeties_unique_idx'
```

I think the fix to this is to add this to background update to the following list:

https://github.com/matrix-org/synapse/blob/78cfa55dad911e667b5a9b613e232eb72410382f/synapse/storage/database.py#L84-L101

**Comment by krombel** [comment]
The `SELECT` does not return anything. Even without the `WHERE` clause there is no response.

It might be, that the update did not run successfully in the past (that homeserver got some time already).

Does recreating the index might work? How to add it? Like this?
```sql
INSERT into background_updates (update_name, progress_json)
    VALUES ('device_lists_remote_extremeties_unique_idx', '{}');
```
or directly with
```sql
CREATE UNIQUE INDEX device_lists_remote_extremeties_unique_idx ON device_lists_remote_extremeties USING btree (user_id);
```

**Comment by krombel** [comment]
I found out, that the index was not there. I could not create the index as well, as there were multiple duplicates in that table

`SELECT count(*) as c, user_id FROM device_lists_remote_extremeties GROUP BY user_id ORDER BY c DESC LIMIT 10;`

**Comment by krombel** [comment]
Since I deleted the duplicate entries manually and created the index that error did not appear anymore.

So thanks @erikjohnston for the hint with `device_lists_remote_extremeties_unique_idx`!
Helped a lot to solve this issue.

As I assume that is some sporadic failure I will close this issue now 🙂
