### ISSUE TITLE
Build fails with "AttributeError: cython_sources"

### ISSUE THREAD

**Issue by hacktivista** [matrix-org/synapse#15996]
### Description

I'm building Synapse on a Debian 11 machine with an armv7 architecture by using the [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) project.

The build process fails with the error "AttributeError: cython_sources".

I'm not aware of the details, but it [is a known bug](https://github.com/yaml/pyyaml/issues/601) in the build process of PyYAML versions greater than 5.3.1 up to 6.0.0 (inclusive) while compiling against recent versions of Cython. Fortunately [a new version of PyYAML](https://github.com/yaml/pyyaml/commit/c42fa3bff1eabdb64763bb1526d9ea1ccb708479) that [works around the issue](https://github.com/yaml/pyyaml/pull/702) has been recently released (6.0.1).

### Steps to reproduce

I used the [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) instructions.

- First I did [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook.md)
- Then [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/installing.md) up to the point of actually running ansible-playbook.

I run the Ansible recipe with `ansible-playbook -i inventory/hosts setup.yml --tags=install-all,ensure-matrix-users-created,start`.

I am sorry I cannot be more specific regarding the instructions concerning this project.

### Homeserver

-

### Synapse Version

-

### Installation Method

Docker (matrixdotorg/synapse)

### Database

SQLite

### Workers

Single process

### Platform

Debian 11 armv7 (A20-OLinuXino-LIME2)

### Relevant log output

```shell
ok: [matrix.anything.org]
 ___________________________________________________________ 
/ TASK [custom/matrix-synapse : Ensure Synapse Docker image \
\ is built]                                                 /
 ----------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [matrix.anything.org]: FAILED! => changed=true 
  cmd: |-
    /usr/bin/env docker build \
    -t "localhost/matrix-org/synapse:v1.88.0" \
    -f docker/Dockerfile \
    .
  delta: '0:05:47.895659'
  end: '2023-07-25 03:22:08.153445'
  msg: non-zero return code
  rc: 1
  start: '2023-07-25 03:16:20.257786'
  stderr: |-
    #0 building with "default" instance using docker driver
  
    #1 [internal] load .dockerignore
    #1 transferring context:
    #1 transferring context: 241B 0.1s done
    #1 DONE 0.1s
  
    #2 [internal] load build definition from Dockerfile
    #2 transferring dockerfile: 7.00kB 0.0s done
    #2 DONE 0.1s
  
    #3 resolve image config for docker.io/docker/dockerfile:1
    #3 DONE 2.4s
  
    #4 docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14
    #4 CACHED
  
    #5 [internal] load metadata for docker.io/library/python:3.11-slim-bullseye
    #5 DONE 1.3s
  
    #6 [requirements 1/8] FROM docker.io/library/python:3.11-slim-bullseye@sha256:9b4d90af2003eef5d862f8118d8645d37d170402645a09e48241a3e492a0d4dc
    #6 DONE 0.0s
  
    #7 [stage-2 2/5] RUN   --mount=type=cache,target=/var/cache/apt,sharing=locked   --mount=type=cache,target=/var/lib/apt,sharing=locked   apt-get update -qq && apt-get install -yqq   curl   gosu   libjpeg62-turbo   libpq5   libwebp6   xmlsec1   libjemalloc2   libicu67   libssl-dev   openssl   && rm -rf /var/lib/apt/lists/*
    #7 CACHED
  
    #8 [internal] load build context
    #8 transferring context: 30B 0.0s
    #8 transferring context: 71.71kB 1.4s done
    #8 DONE 1.5s
  
    #9 [requirements 6/8] WORKDIR /synapse
    #9 CACHED
  
    #10 [requirements 5/8] RUN --mount=type=cache,target=/root/.cache/pip   pip install --user "poetry==1.3.2"
    #10 CACHED
  
    #11 [requirements 2/8] RUN   --mount=type=cache,target=/var/cache/apt,sharing=locked   --mount=type=cache,target=/var/lib/apt,sharing=locked   apt-get update -qq && apt-get install -yqq   build-essential curl git libffi-dev libssl-dev pkg-config   && rm -rf /var/lib/apt/lists/*
    #11 CACHED
  
    #12 [builder  2/10] RUN   --mount=type=cache,target=/var/cache/apt,sharing=locked   --mount=type=cache,target=/var/lib/apt,sharing=locked   apt-get update -qq && apt-get install -yqq   build-essential   libffi-dev   libjpeg-dev   libpq-dev   libssl-dev   libwebp-dev   libxml++2.6-dev   libxslt1-dev   openssl   zlib1g-dev   git   curl   libicu-dev   pkg-config   && rm -rf /var/lib/apt/lists/*
    #12 CACHED
  
    #13 [builder  3/10] RUN mkdir /rust /cargo
    #13 CACHED
  
    #14 [builder  4/10] RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain stable --profile minimal
    #14 CACHED
  
    #15 [requirements 8/8] RUN if [ -z "$TEST_ONLY_IGNORE_POETRY_LOCKFILE" ]; then   /root/.local/bin/poetry export --extras all -o /synapse/requirements.txt ${TEST_ONLY_SKIP_DEP_HASH_VERIFICATION:+--without-hashes};   else   touch /synapse/requirements.txt;   fi
    #15 CACHED
  
    #16 [requirements 3/8] RUN mkdir /rust /cargo
    #16 CACHED
  
    #17 [requirements 4/8] RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain stable --profile minimal
    #17 CACHED
  
    #18 [requirements 7/8] COPY pyproject.toml poetry.lock /synapse/
    #18 CACHED
  
    #19 [builder  5/10] COPY --from=requirements /synapse/requirements.txt /synapse/
    #19 CACHED
  
    #20 [builder  6/10] RUN --mount=type=cache,target=/root/.cache/pip   pip install --prefix="/install" --no-deps --no-warn-script-location -r /synapse/requirements.txt
    #20 30.08 Ignoring importlib-resources: markers 'python_full_version >= "3.8.0" and python_version < "3.9"' don't match your environment
    #20 30.11 Ignoring pkgutil-resolve-name: markers 'python_full_version >= "3.8.0" and python_version < "3.9"' don't match your environment
    #20 30.13 Ignoring psycopg2cffi-compat: markers 'python_full_version >= "3.8.0" and python_full_version < "4.0.0" and platform_python_implementation == "PyPy"' don't match your environment
    #20 30.13 Ignoring psycopg2cffi: markers 'python_full_version >= "3.8.0" and python_full_version < "4.0.0" and platform_python_implementation == "PyPy"' don't match your environment
    #20 30.18 Ignoring twisted-iocpsupport: markers 'python_full_version >= "3.8.0" and python_full_version < "4.0.0" and platform_system == "Windows"' don't match your environment
    #20 30.19 Ignoring zipp: markers 'python_full_version >= "3.8.0" and python_version < "3.9"' don't match your environment
    #20 30.95 Collecting attrs==23.1.0 (from -r /synapse/requirements.txt (line 1))
    #20 31.01   Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
    #20 31.69 Collecting authlib==1.2.1 (from -r /synapse/requirements.txt (line 4))
    #20 32.16   Using cached Authlib-1.2.1-py2.py3-none-any.whl (215 kB)
    #20 32.57 Collecting automat==22.10.0 (from -r /synapse/requirements.txt (line 7))
    #20 32.61   Using cached Automat-22.10.0-py2.py3-none-any.whl (26 kB)
    #20 33.42 Collecting bcrypt==4.0.1 (from -r /synapse/requirements.txt (line 10))
    #20 33.45   Using cached bcrypt-4.0.1.tar.gz (25 kB)
    #20 33.63   Installing build dependencies: started
    #20 58.45   Installing build dependencies: finished with status 'done'
    #20 58.47   Getting requirements to build wheel: started
    #20 62.44   Getting requirements to build wheel: finished with status 'done'
    #20 62.49   Preparing metadata (pyproject.toml): started
    #20 65.79   Preparing metadata (pyproject.toml): finished with status 'done'
    #20 66.28 Collecting bleach==6.0.0 (from -r /synapse/requirements.txt (line 32))
    #20 66.32   Using cached bleach-6.0.0-py3-none-any.whl (162 kB)
    #20 66.63 Collecting canonicaljson==2.0.0 (from -r /synapse/requirements.txt (line 35))
    #20 66.66   Using cached canonicaljson-2.0.0-py3-none-any.whl (7.9 kB)
    #20 67.04 Collecting certifi==2022.12.7 (from -r /synapse/requirements.txt (line 38))
    #20 67.09   Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
    #20 69.61 Collecting cffi==1.15.1 (from -r /synapse/requirements.txt (line 41))
    #20 69.62   Using cached cffi-1.15.1-cp311-cp311-linux_armv7l.whl
    #20 71.03 Collecting charset-normalizer==3.1.0 (from -r /synapse/requirements.txt (line 106))
    #20 71.07   Using cached charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
    #20 71.27 Collecting constantly==15.1.0 (from -r /synapse/requirements.txt (line 182))
    #20 71.30   Using cached constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
    #20 75.11 Collecting cryptography==41.0.1 (from -r /synapse/requirements.txt (line 185))
    #20 75.18   Using cached cryptography-41.0.1.tar.gz (629 kB)
    #20 77.24   Installing build dependencies: started
    #20 106.9   Installing build dependencies: finished with status 'done'
    #20 106.9   Getting requirements to build wheel: started
    #20 111.9   Getting requirements to build wheel: finished with status 'done'
    #20 112.0   Preparing metadata (pyproject.toml): started
    #20 116.1   Preparing metadata (pyproject.toml): finished with status 'done'
    #20 116.4 Collecting defusedxml==0.7.1 (from -r /synapse/requirements.txt (line 205))
    #20 116.4   Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
    #20 117.3 Collecting elementpath==4.1.0 (from -r /synapse/requirements.txt (line 208))
    #20 117.4   Using cached elementpath-4.1.0-py3-none-any.whl (216 kB)
    #20 118.8 Collecting hiredis==2.2.3 (from -r /synapse/requirements.txt (line 211))
    #20 118.8   Using cached hiredis-2.2.3.tar.gz (84 kB)
    #20 119.1   Preparing metadata (setup.py): started
    #20 127.0   Preparing metadata (setup.py): finished with status 'done'
    #20 127.3 Collecting hyperlink==21.0.0 (from -r /synapse/requirements.txt (line 301))
    #20 127.3   Using cached hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
    #20 127.6 Collecting idna==3.4 (from -r /synapse/requirements.txt (line 304))
    #20 127.7   Using cached idna-3.4-py3-none-any.whl (61 kB)
    #20 129.4 Collecting ijson==3.2.1 (from -r /synapse/requirements.txt (line 307))
    #20 129.4   Using cached ijson-3.2.1.tar.gz (56 kB)
    #20 129.7   Preparing metadata (setup.py): started
    #20 134.1   Preparing metadata (setup.py): finished with status 'done'
    #20 134.5 Collecting immutabledict==2.2.4 (from -r /synapse/requirements.txt (line 386))
    #20 134.6   Using cached immutabledict-2.2.4-py3-none-any.whl (4.1 kB)
    #20 134.8 Collecting incremental==22.10.0 (from -r /synapse/requirements.txt (line 392))
    #20 134.8   Using cached incremental-22.10.0-py2.py3-none-any.whl (16 kB)
    #20 135.0 Collecting jaeger-client==4.8.0 (from -r /synapse/requirements.txt (line 395))
    #20 135.1   Using cached jaeger-client-4.8.0.tar.gz (87 kB)
    #20 135.6   Preparing metadata (setup.py): started
    #20 139.7   Preparing metadata (setup.py): finished with status 'done'
    #20 140.1 Collecting jinja2==3.1.2 (from -r /synapse/requirements.txt (line 397))
    #20 140.1   Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
    #20 140.8 Collecting jsonschema==4.17.3 (from -r /synapse/requirements.txt (line 400))
    #20 140.8   Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
    #20 141.2 Collecting ldap3==2.9.1 (from -r /synapse/requirements.txt (line 403))
    #20 141.3   Using cached ldap3-2.9.1-py2.py3-none-any.whl (432 kB)
    #20 144.8 Collecting lxml==4.9.3 (from -r /synapse/requirements.txt (line 406))
    #20 145.1   Using cached lxml-4.9.3.tar.gz (3.6 MB)
    #20 149.6   Preparing metadata (setup.py): started
    #20 154.9   Preparing metadata (setup.py): finished with status 'done'
    #20 155.9 Collecting markupsafe==2.1.2 (from -r /synapse/requirements.txt (line 497))
    #20 155.9   Using cached MarkupSafe-2.1.2.tar.gz (19 kB)
    #20 156.1   Preparing metadata (setup.py): started
    #20 160.3   Preparing metadata (setup.py): finished with status 'done'
    #20 160.5 Collecting matrix-common==1.3.0 (from -r /synapse/requirements.txt (line 548))
    #20 160.5   Using cached matrix_common-1.3.0-py3-none-any.whl (11 kB)
    #20 160.7 Collecting matrix-synapse-ldap3==0.2.2 (from -r /synapse/requirements.txt (line 551))
    #20 160.8   Using cached matrix_synapse_ldap3-0.2.2-py3-none-any.whl (13 kB)
    #20 161.9 Collecting msgpack==1.0.5 (from -r /synapse/requirements.txt (line 554))
    #20 161.9   Using cached msgpack-1.0.5-cp311-cp311-linux_armv7l.whl
    #20 162.4 Collecting netaddr==0.8.0 (from -r /synapse/requirements.txt (line 618))
    #20 162.5   Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
    #20 163.0 Collecting opentracing==2.4.0 (from -r /synapse/requirements.txt (line 621))
    #20 163.0   Using cached opentracing-2.4.0.tar.gz (46 kB)
    #20 163.4   Preparing metadata (setup.py): started
    #20 167.1   Preparing metadata (setup.py): finished with status 'done'
    #20 167.6 Collecting packaging==23.1 (from -r /synapse/requirements.txt (line 623))
    #20 167.6   Using cached packaging-23.1-py3-none-any.whl (48 kB)
    #20 168.0 Collecting parameterized==0.9.0 (from -r /synapse/requirements.txt (line 626))
    #20 168.0   Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
    #20 168.9 Collecting phonenumbers==8.13.14 (from -r /synapse/requirements.txt (line 629))
    #20 169.1   Using cached phonenumbers-8.13.14-py2.py3-none-any.whl (2.6 MB)
    #20 173.5 Collecting pillow==9.4.0 (from -r /synapse/requirements.txt (line 632))
    #20 176.6   Using cached Pillow-9.4.0.tar.gz (50.4 MB)
    #20 195.8   Preparing metadata (setup.py): started
    #20 200.5   Preparing metadata (setup.py): finished with status 'done'
    #20 200.9 Collecting prometheus-client==0.17.0 (from -r /synapse/requirements.txt (line 713))
    #20 200.9   Using cached prometheus_client-0.17.0-py3-none-any.whl (60 kB)
    #20 202.0 Collecting psycopg2==2.9.6 (from -r /synapse/requirements.txt (line 716))
    #20 202.1   Using cached psycopg2-2.9.6.tar.gz (383 kB)
    #20 203.3   Preparing metadata (setup.py): started
    #20 207.7   Preparing metadata (setup.py): finished with status 'done'
    #20 208.1 Collecting pyasn1-modules==0.3.0 (from -r /synapse/requirements.txt (line 734))
    #20 208.2   Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
    #20 209.1 Collecting pyasn1==0.5.0 (from -r /synapse/requirements.txt (line 737))
    #20 209.1   Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
    #20 209.4 Collecting pycparser==2.21 (from -r /synapse/requirements.txt (line 740))
    #20 209.4   Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
    #20 212.1 Collecting pydantic==1.10.10 (from -r /synapse/requirements.txt (line 743))
    #20 212.1   Using cached pydantic-1.10.10-py3-none-any.whl (158 kB)
    #20 212.5 Collecting pyicu==2.11 (from -r /synapse/requirements.txt (line 780))
    #20 212.6   Using cached PyICU-2.11.tar.gz (257 kB)
    #20 213.2   Installing build dependencies: started
    #20 235.9   Installing build dependencies: finished with status 'done'
    #20 236.0   Getting requirements to build wheel: started
    #20 238.5   Getting requirements to build wheel: finished with status 'done'
    #20 238.5   Preparing metadata (pyproject.toml): started
    #20 241.3   Preparing metadata (pyproject.toml): finished with status 'done'
    #20 241.7 Collecting pymacaroons==0.13.0 (from -r /synapse/requirements.txt (line 782))
    #20 241.7   Using cached pymacaroons-0.13.0-py2.py3-none-any.whl (19 kB)
    #20 242.0 Collecting pympler==1.0.1 (from -r /synapse/requirements.txt (line 785))
    #20 242.1   Using cached Pympler-1.0.1-py3-none-any.whl (164 kB)
    #20 242.6 Collecting pynacl==1.5.0 (from -r /synapse/requirements.txt (line 788))
    #20 242.9   Using cached PyNaCl-1.5.0.tar.gz (3.4 MB)
    #20 247.6   Installing build dependencies: started
    #20 274.0   Installing build dependencies: finished with status 'done'
    #20 274.0   Getting requirements to build wheel: started
    #20 276.1   Getting requirements to build wheel: finished with status 'done'
    #20 276.2   Preparing metadata (pyproject.toml): started
    #20 283.3   Preparing metadata (pyproject.toml): finished with status 'done'
    #20 283.7 Collecting pyopenssl==23.2.0 (from -r /synapse/requirements.txt (line 799))
    #20 283.7   Using cached pyOpenSSL-23.2.0-py3-none-any.whl (59 kB)
    #20 284.2 Collecting pyrsistent==0.19.3 (from -r /synapse/requirements.txt (line 802))
    #20 284.3   Using cached pyrsistent-0.19.3-py3-none-any.whl (57 kB)
    #20 284.8 Collecting pysaml2==7.3.1 (from -r /synapse/requirements.txt (line 830))
    #20 284.9   Using cached pysaml2-7.3.1-py3-none-any.whl (419 kB)
    #20 285.2 Collecting python-dateutil==2.8.2 (from -r /synapse/requirements.txt (line 833))
    #20 285.3   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
    #20 286.3 Collecting pytz==2022.7.1 (from -r /synapse/requirements.txt (line 836))
    #20 286.3   Using cached pytz-2022.7.1-py2.py3-none-any.whl (499 kB)
    #20 287.3 Collecting pyyaml==6.0 (from -r /synapse/requirements.txt (line 839))
    #20 287.3   Using cached PyYAML-6.0.tar.gz (124 kB)
    #20 289.8   Installing build dependencies: started
    #20 325.0   Installing build dependencies: finished with status 'done'
    #20 325.0   Getting requirements to build wheel: started
    #20 328.3   Getting requirements to build wheel: finished with status 'error'
    #20 328.4   error: subprocess-exited-with-error
    #20 328.4
    #20 328.4   × Getting requirements to build wheel did not run successfully.
    #20 328.4   │ exit code: 1
    #20 328.4   ╰─> [54 lines of output]
    #20 328.4       running egg_info
    #20 328.4       writing lib/PyYAML.egg-info/PKG-INFO
    #20 328.4       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
    #20 328.4       writing top-level names to lib/PyYAML.egg-info/top_level.txt
    #20 328.4       Traceback (most recent call last):
    #20 328.4         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    #20 328.4           main()
    #20 328.4         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    #20 328.4           json_out['return_val'] = hook(**hook_input['kwargs'])
    #20 328.4                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #20 328.4         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    #20 328.4           return hook(config_settings)
    #20 328.4                  ^^^^^^^^^^^^^^^^^^^^^
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    #20 328.4           return self._get_build_requires(config_settings, requirements=['wheel'])
    #20 328.4                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    #20 328.4           self.run_setup()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
    #20 328.4           exec(code, locals())
    #20 328.4         File "<string>", line 288, in <module>
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
    #20 328.4           return distutils.core.setup(**attrs)
    #20 328.4                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    #20 328.4           return run_commands(dist)
    #20 328.4                  ^^^^^^^^^^^^^^^^^^
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    #20 328.4           dist.run_commands()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    #20 328.4           self.run_command(cmd)
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
    #20 328.4           super().run_command(command)
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    #20 328.4           cmd_obj.run()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
    #20 328.4           self.find_sources()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
    #20 328.4           mm.run()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
    #20 328.4           self.add_defaults()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
    #20 328.4           sdist.add_defaults(self)
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
    #20 328.4           super().add_defaults()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
    #20 328.4           self._add_defaults_ext()
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
    #20 328.4           self.filelist.extend(build_ext.get_source_files())
    #20 328.4                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    #20 328.4         File "<string>", line 204, in get_source_files
    #20 328.4         File "/tmp/pip-build-env-waucu04d/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    #20 328.4           raise AttributeError(attr)
    #20 328.4       AttributeError: cython_sources
    #20 328.4       [end of output]
    #20 328.4
    #20 328.4   note: This error originates from a subprocess, and is likely not a problem with pip.
    #20 328.5 error: subprocess-exited-with-error
    #20 328.5
    #20 328.5 × Getting requirements to build wheel did not run successfully.
    #20 328.5 │ exit code: 1
    #20 328.5 ╰─> See above for output.
    #20 328.5
    #20 328.5 note: This error originates from a subprocess, and is likely not a problem with pip.
    #20 329.1
    #20 329.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1
    #20 329.1 [notice] To update, run: pip install --upgrade pip
    #20 ERROR: process "/bin/sh -c pip install --prefix=\"/install\" --no-deps --no-warn-script-location -r /synapse/requirements.txt" did not complete successfully: exit code: 1
    ------
     > [builder  6/10] RUN --mount=type=cache,target=/root/.cache/pip   pip install --prefix="/install" --no-deps --no-warn-script-location -r /synapse/requirements.txt:
    328.5 error: subprocess-exited-with-error
    328.5
    328.5 × Getting requirements to build wheel did not run successfully.
    328.5 │ exit code: 1
    328.5 ╰─> See above for output.
    328.5
    328.5 note: This error originates from a subprocess, and is likely not a problem with pip.
    329.1
    329.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1
    329.1 [notice] To update, run: pip install --upgrade pip
    ------
    WARNING: buildx: failed to read current commit information with git rev-parse --is-inside-work-tree
    Dockerfile:134
    --------------------
     133 |     COPY --from=requirements /synapse/requirements.txt /synapse/
     134 | >>> RUN --mount=type=cache,target=/root/.cache/pip \
     135 | >>>   pip install --prefix="/install" --no-deps --no-warn-script-location -r /synapse/requirements.txt
     136 |
    --------------------
    ERROR: failed to solve: process "/bin/sh -c pip install --prefix=\"/install\" --no-deps --no-warn-script-location -r /synapse/requirements.txt" did not complete successfully: exit code: 1
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
 ____________ 
< PLAY RECAP >
 ------------ 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

matrix.anything.org : ok=98   changed=5    unreachable=0    failed=1    skipped=187  rescued=0    ignored=0
```

**Comment by MatMaul** [comment]
@hacktivista PyYAML has just been updated to 6.0.1, the fix should be available in Synapse 1.90.
