### ISSUE TITLE
Unable to join a room via server if the main homeserver is offline

### ISSUE THREAD

**Issue by x48115** [matrix-org/synapse#16024]
### Description

I'm trying to use matrix as a messaging bus for a decentralized RFQ (request for quote system).

My requirement is that all homeservers share the same rooms, where each room will be used as a topic for sending and receiving quotes.

The requirement is that users should be able to join the room even if the main homeserver is offline, because otherwise, the main homeserver is a centralized point of failure.

I can join rooms using `viaServer` (js SDK) and `server_name` (API request), but, only if the main homeserver is online.

I'm getting the following error message when trying to join when the main homeserver that owns the room is offline: `No create event in state`

Is it possible to sync room state from another homeserver, so I can join the room even if the main homeserver is offline?

### Steps to reproduce

- Create 3 homeservers
- Create a public room in homeserver1
- User from homeserver 2 joins homeserver 1
- Homeserver 1 goes offline
- User from homeserver 3 attempts to join room in homeserver 1 via homeserver 2
- Receive error message: `No create event in state`

### Homeserver

localhost

### Synapse Version

{"server_version":"1.89.0rc1 (b=develop,68b261178,dirty)","python_version":"3.9.6"}

### Installation Method

pip (from PyPI)

### Database

demo

### Workers

Single process

### Platform

OSX

### Relevant log output

```shell
/Users/user/src/matrix/node_modules/matrix-js-sdk/lib/http-api/utils.js:81
    return new _errors.MatrixError(JSON.parse(body), response.status, isXhr(response) ? response.responseURL : response.url);
           ^

M_UNKNOWN: MatrixError: [400] No create event in state (http://localhost:8088/_matrix/client/r0/join/!HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480?server_name=localhost%3A8482)
    at parseErrorResponse (/Users/user/src/matrix/node_modules/matrix-js-sdk/lib/http-api/utils.js:81:12)
    at MatrixHttpApi.requestOtherUrl (/Users/user/src/matrix/node_modules/matrix-js-sdk/lib/http-api/fetch.js:244:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  httpStatus: 400,
  url: 'http://localhost:8088/_matrix/client/r0/join/!HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480?server_name=localhost%3A8482',
  event: undefined,
  errcode: 'M_UNKNOWN',
  data: { errcode: 'M_UNKNOWN', error: 'No create event in state' }
}
```

**Comment by x48115** [comment]
It looks like this may have to do with missing signatures somehow
```
2023-07-28 15:25:40,762 - synapse.http.matrixfederationclient - 348 - INFO - POST-100 - {GET-O-103} [localhost:8482] Completed request: 200 OK in 0.01 secs, got 536 bytes - GET matrix-federation://localhost:8482/_matrix/federation/v1/make_join/%21HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480/%40x48%3Alocalhost%3A8490?ver=1&ver=2&ver=3&ver=4&ver=5&ver=6&ver=7&ver=8&ver=9&ver=10&ver=11
2023-07-28 15:25:40,779 - synapse.http.matrixfederationclient - 348 - INFO - POST-100 - {PUT-O-104} [localhost:8482] Completed request: 200 OK in 0.02 secs, got 11428 bytes - PUT matrix-federation://localhost:8482/_matrix/federation/v2/send_join/%21HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480/%24g457xZNaW7uMGoCMcOokrESNmNAucFW5DCS6uuiNImk?omit_members=true
2023-07-28 15:25:40,780 - synapse.federation.federation_client - 1112 - INFO - POST-100 - Processing from send_join 13 events
2023-07-28 15:25:40,839 - synapse.federation.sender.transaction_manager - 121 - INFO - federation_transaction_transmission_loop-25 - TX [localhost:8489] {1690573261178} Sending transaction [1690573261178], (PDUs: 0, EDUs: 1)
2023-07-28 15:25:40,844 - synapse.http.matrixfederationclient - 348 - INFO - federation_transaction_transmission_loop-25 - {PUT-O-106} [localhost:8489] Completed request: 200 OK in 0.01 secs, got 11 bytes - PUT matrix-federation://localhost:8489/_matrix/federation/v1/send/1690573261178
2023-07-28 15:25:40,844 - synapse.federation.sender.transaction_manager - 174 - INFO - federation_transaction_transmission_loop-25 - TX [localhost:8489] {1690573261178} got 200 response
2023-07-28 15:25:40,844 - synapse.federation.sender.per_destination_queue - 820 - INFO - federation_transaction_transmission_loop-25 - Marking as sent 'localhost:8489' 47
2023-07-28 15:25:41,384 - synapse.http.federation.matrix_federation_agent - 365 - INFO - ServerKeyFetcher-13 - Failed to connect to localhost:8480: Connection was refused by other side: 61: Connection refused.
2023-07-28 15:25:41,390 - synapse.http.matrixfederationclient - 758 - INFO - ServerKeyFetcher-13 - {GET-O-105} [localhost:8480] Request failed: GET matrix-federation://localhost:8480/_matrix/key/v2/server: ConnectionRefusedError('Connection refused')
2023-07-28 15:25:41,390 - synapse.crypto.keyring - 865 - WARNING - ServerKeyFetcher-13 - Error looking up keys from localhost:8480: Failed to send request: ConnectionRefusedError: Connection was refused by other side: 61: Connection refused.
2023-07-28 15:25:41,391 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $7dcGK_AbjKuxQpEpKpUfmeh3SdEyZsoSJL1OAB-S4f0 was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554221979, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,392 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $0hWoWq1I1NZIcPxqoyxdYtKsxKZpxsKk5Od4I_W0soY was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554221952, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,393 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $GXVQ7ELDTglW-PFkFKlUP3HXMRrVakcaFHQEYtdWLWY was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690561296287, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,394 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $BiSG-YtCwiF0AB1y-X325QlvjvfXVS1XCIDMeglCJR8 was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554993648, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,395 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $Jhq83u3vKMzDLwvP-IiTb-JTn9UQ17QteD7cZxLmLBg was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554221984, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,395 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $I6KH2fURoI_6vo6ZvSpXUNvG1QTCUKhV5dCMlynNT7U was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690561293453, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,396 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $dNm8-66Q80OCqnVh30foSj3PENce3Dp0doSgKnKsxE0 was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554221983, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,396 - synapse.federation.federation_client - 752 - WARNING - POST-100 - Signature on retrieved event $kU8ly5c4Rj8np_-DsPyihJyPHJwmdVedNHzIpZdbNcI was invalid (unable to verify signature for sender domain localhost:8480: 401: Failed to find any key to satisfy: _FetchKeyRequest(server_name='localhost:8480', minimum_valid_until_ts=1690554221972, key_ids=['ed25519:a_etnn'])). Checking local store/origin server
2023-07-28 15:25:41,397 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$7dcGK_AbjKuxQpEpKpUfmeh3SdEyZsoSJL1OAB-S4f0): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,397 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $7dcGK_AbjKuxQpEpKpUfmeh3SdEyZsoSJL1OAB-S4f0 with valid signature
2023-07-28 15:25:41,399 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$0hWoWq1I1NZIcPxqoyxdYtKsxKZpxsKk5Od4I_W0soY): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,399 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $0hWoWq1I1NZIcPxqoyxdYtKsxKZpxsKk5Od4I_W0soY with valid signature
2023-07-28 15:25:41,400 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$GXVQ7ELDTglW-PFkFKlUP3HXMRrVakcaFHQEYtdWLWY): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,400 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $GXVQ7ELDTglW-PFkFKlUP3HXMRrVakcaFHQEYtdWLWY with valid signature
2023-07-28 15:25:41,400 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$BiSG-YtCwiF0AB1y-X325QlvjvfXVS1XCIDMeglCJR8): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,400 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $BiSG-YtCwiF0AB1y-X325QlvjvfXVS1XCIDMeglCJR8 with valid signature
2023-07-28 15:25:41,400 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$Jhq83u3vKMzDLwvP-IiTb-JTn9UQ17QteD7cZxLmLBg): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,401 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $Jhq83u3vKMzDLwvP-IiTb-JTn9UQ17QteD7cZxLmLBg with valid signature
2023-07-28 15:25:41,401 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$I6KH2fURoI_6vo6ZvSpXUNvG1QTCUKhV5dCMlynNT7U): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,401 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $I6KH2fURoI_6vo6ZvSpXUNvG1QTCUKhV5dCMlynNT7U with valid signature
2023-07-28 15:25:41,402 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$dNm8-66Q80OCqnVh30foSj3PENce3Dp0doSgKnKsxE0): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,402 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $dNm8-66Q80OCqnVh30foSj3PENce3Dp0doSgKnKsxE0 with valid signature
2023-07-28 15:25:41,402 - synapse.federation.federation_client - 498 - INFO - POST-100 - get_pdu(event_id=$kU8ly5c4Rj8np_-DsPyihJyPHJwmdVedNHzIpZdbNcI): Not retrying server localhost:8480 because we tried it recently retry_last_ts=1690573996683 and we won't check for another retry_interval=3998319ms.
2023-07-28 15:25:41,402 - synapse.federation.federation_client - 790 - WARNING - POST-100 - Failed to find copy of $kU8ly5c4Rj8np_-DsPyihJyPHJwmdVedNHzIpZdbNcI with valid signature
2023-07-28 15:25:41,403 - synapse.http.server - 118 - INFO - POST-100 - <XForwardedForRequest at 0x10a37b130 method='POST' uri='/_matrix/client/r0/join/!HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480?server_name=localhost%3A8482' clientproto='HTTP/1.1' site='8090'> SynapseError: 400 - No create event in state2
2023-07-28 15:25:41,403 - synapse.access.http.8090 - 465 - INFO - POST-100 - ::1 - 8090 - {@x48:localhost:8490} Processed request: 0.656sec/0.000sec (0.000sec, 0.000sec) (0.001sec/0.000sec/7) 59B 400 "POST /_matrix/client/r0/join/!HDeaoLJXcZKHnoBylA%3Alocalhost%3A8480?server_name=localhost%3A8482 HTTP/1.1" "undici" [8 dbevts]
2023-07-28 15:25:41,409 - synapse.http.site - 377 - INFO - GET-103 - Connection from client lost before response was sent
2023-07-28 15:25:49,762 - synapse.access.http.8090 - 465 - INFO - POST-104 - ::1 - 8090 - {None} Processed request: 0.004sec/0.000sec (0.000sec, 0.000sec) (0.001sec/0.001sec/5) 406B 200 "POST /_matrix/client/r0/register?kind=guest HTTP/1.1" "undici" [0 dbevts]
2023-07-28 15:25:49,769 - synapse.rest.client.login - 335 - INFO - POST-105 - Got login request with identifier: None, medium: None, address: None, user: 'x48'
2023-07-28 15:25:50,008 - synapse.handlers.auth - 999 - INFO - POST-105 - Logging in user @x48:localhost:8490 on device GAWICEXJCN
2023-07-28 15:25:50,010 - synapse.access.http.8090 - 465 - INFO - POST-105 - ::1 - 8090 - {None} Processed request: 0.241sec/0.000sec (0.000sec, 0.000sec) (0.001sec/0.001sec/5) 211B 200 "POST /_matrix/client/r0/login HTTP/1.1" "undici" [0 dbevts]
2023-07-28 15:25:50,010 - synapse.handlers.device - 810 - INFO - _handle_new_device_update_async-24 - Sending device list update notif for '@x48:localhost:8490' to: {'localhost:8482', 'localhost:8489'}
2023-07-28 15:25:50,011 - synapse.rest.client.sync - 223 - INFO - GET-103 - Client has disconnected; not serializing response.
2023-07-28 15:25:50,011 - synapse.http.server - 770 - WARNING - GET-103 - Not sending response to request <XForwardedForRequest at 0x10a3b08e0 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=30000&since=s3_26_0_2_1_1_1_47_0_2' clientproto='HTTP/1.1' site='8090'>, already disconnected.
2023-07-28 15:25:50,013 - synapse.access.http.8090 - 465 - INFO - GET-103 - ::1 - 8090 - {@x48:localhost:8490} Processed request: 9.245sec/-8.605sec (0.000sec, 0.000sec) (0.001sec/0.001sec/9) 0B 200! "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s3_26_0_2_1_1_1_47_0_2 HTTP/1.1" "undici" [0 dbevts]
2023-07-28 15:25:50,014 - synapse.access.http.8090 - 465 - INFO - GET-106 - ::1 - 8090 - {None} Processed request: 0.000sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 857B 200 "GET /_matrix/client/versions HTTP/1.1" "undici" [0 dbevts]
2023-07-28 15:25:50,015 - synapse.federation.sender.transaction_manager - 121 - INFO - federation_transaction_transmission_loop-26 - TX [localhost:8482] {1690573261179} Sending transaction [1690573261179], (PDUs: 0, EDUs: 1)
2023-07-28 15:25:50,020 - synapse.http.matrixfederationclient - 348 - INFO - federation_transaction_transmission_loop-26 - {PUT-O-115} [localhost:8482] Completed request: 200 OK in 0.01 secs, got 11 bytes - PUT matrix-federation://localhost:8482/_matrix/federation/v1/send/1690573261179
2023-07-28 15:25:50,020 - synapse.federation.sender.transaction_manager - 174 - INFO - federation_transaction_transmission_loop-26 - TX [localhost:8482] {1690573261179} got 200 response
2023-07-28 15:25:50,020 - synapse.federation.sender.per_destination_queue - 820 - INFO - federation_transaction_transmission_loop-26 - Marking as sent 'localhost:8482' 50
2023-07-28 15:25:50,021 - synapse.access.http.8090 - 465 - INFO - GET-107 - ::1 - 8090 - {@x48:localhost:8490} Processed request: 0.001sec/0.002sec (0.000sec, 0.000sec) (0.000sec/0.000sec/2) 4177B 200 "GET /_matrix/client/r0/pushrules/ HTTP/1.1" "undici" [0 dbevts]
2023-07-28 15:25:50,022 - synapse.access.https.8490 - 465 - INFO - GET-108 - ::1 - 8490 - {localhost:8482} Processed request: 0.002sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.001sec/1) 103B 200 "GET /_matrix/federation/v1/user/devices/%40x48%3Alocalhost%3A8490 HTTP/1.1" "Synapse/1.89.0rc1" [0 dbevts]
2023-07-28 15:25:50,024 - synapse.http.matrixfederationclient - 348 - INFO - POST-109 - {GET-O-116} [localhost:8482] Completed request: 200 OK in 0.00 secs, got 179 bytes - GET matrix-federation://localhost:8482/_matrix/federation/v1/query/directory?room_alias=%23testoor%3Alocalhost%3A8482
2023-07-28 15:25:50,027 - synapse.access.http.8090 - 465 - INFO - POST-110 - ::1 - 8090 - {@x48:localhost:8490} Processed request: 0.002sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/1) 17B 200 "POST /_matrix/client/r0/user/%40x48%3Alocalhost%3A8490/filter HTTP/1.1" "undici" [0 dbevts]
```

**Comment by x48115** [comment]
Note: I also did extensive testing with aliases and I always receive the same error (missing event). It appears the client is attempting to backfill data but there is a signature mismatch, presumably because the data isn't coming from the originating server.

**Comment by clokep** [comment]
> The requirement is that users should be able to join the room even if the main homeserver is offline, because otherwise, the main homeserver is a centralized point of failure.

In order to validate events from the offline homeserver then you'll need to get the server's key from an online homeserver. See the [`trusted_key_servers`](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#trusted_key_servers) setting.

This is working as expected though (and as required by the Matrix spec, AFAIK) so I'm going to close this. In the future please ask support questions in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org).
