### ISSUE TITLE
MA1SD Error M_UNAUTHORIZED: Supplied credentials are invalid

### ISSUE THREAD

**Issue by AnassDriate** [matrix-org/synapse#16203]
### Description

Hello,

I am runing synapse version 1.87 multi-worker mode, the ma1sd is one of them, the ma1sd version is 2.5.0

When trying to invite someone by mail, I receive 504 on the following end-point : /_matrix/identity/v2/account/register.

The logs of ma1sd are the following : 
```

Aug 28 16:57:23 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-3] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://private.chat.lu/_matrix/identity/v2/account/register - Error M_UNAUTHORIZED: Supplied credentials are invalid
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-1] ERROR io.kamax.mxisd.auth.AccountManager - Wrong response status: 500
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-1] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Unauthorized:
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: io.kamax.mxisd.exception.InvalidCredentialsException: Supplied credentials are invalid
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:86)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

install synapse
install ma1sd
redirect the identity end-points to ma1sd 
invite someone by mail 

### Homeserver

another

### Synapse Version

1.87

### Installation Method

Docker (matrixdotorg/synapse)

### Database

postgres

### Workers

Multiple workers

### Platform

containers

### Relevant log output

```shell
Aug 28 16:57:23 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-3] INFO io.kamax.mxisd.http.undertow.handler.BasicHttpHandler - Request POST http://u-01.luxchat.lu/_matrix/identity/v2/account/register - Error M_UNAUTHORIZED: Supplied credentials are invalid
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-1] ERROR io.kamax.mxisd.auth.AccountManager - Wrong response status: 500
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: [XNIO-1 task-1] ERROR io.kamax.mxisd.http.undertow.handler.SaneHandler - Unauthorized:
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]: io.kamax.mxisd.exception.InvalidCredentialsException: Supplied credentials are invalid
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.auth.AccountManager.getUserId(AccountManager.java:86)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.auth.AccountManager.register(AccountManager.java:53)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.http.undertow.handler.auth.v2.AccountRegisterHandler.handleRequest(AccountRegisterHandler.java:54)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.kamax.mxisd.http.undertow.handler.SaneHandler.handleRequest(SaneHandler.java:71)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
Aug 28 16:58:14 u-sm2-gpe matrix-ma1sd[2229402]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by clokep** [comment]
This sounds like an issue with ma1sd, you'll need to [report it there](https://github.com/ma1uta/ma1sd).

**Comment by clokep** [comment]
(And it looks like you did already: ma1uta/ma1sd#125.)
