### ISSUE TITLE
Got into a room I didn't join

### ISSUE THREAD

**Issue by xyzz** [matrix-org/synapse#1629]
So yesterday this happened again - on my account `@xyz:xyz.is` I got put into a room I didn't join myself, the room is #matrix:matrix.org.

Now I receive messages from it but cannot send any messages to it, or leave. Trying to leave results in a `Failed to leave room M_UNKNOWN: Not a known room` error (using Riot client).

Last time the issue went away after a few days, I was able to leave it.

This happened while running synapse 0.18.1 but now I've updated to 0.18.3 and the issue is still here.

**Comment by xyzz** [comment]
Now I stopped receiving messages from that room, the last received message is https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$14792907687JzRAX:krtdex.com

It also appears that my `@xyz:xyz.is` account is not in the channel anymore (it used to be present in userlist)

However, I still cannot leave the room, getting same error, so it's just hanging there without receiving any messages. I think last time that happened I was able to first rejoin the room normally and then leave it, but not sure.

**Comment by xyzz** [comment]
Seems to keep happening erratically.

I've noticed these errors in my log: (happened before upgrade to 0.18.5, on 0.18.3)

```
2016-12-16 23:15:55,448 - synapse.federation.federation_server - 154 - ERROR - PUT-124- Failed to handle PDU
Traceback (most recent call last):
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 147, in on_incoming_transaction
    yield self._handle_new_pdu(transaction.origin, pdu)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 578, in _handle_new_pdu
    get_missing=False
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 612, in _handle_new_pdu
    auth_chain=auth_chain,
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 174, in on_receive_pdu
    state=state,
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 1173, in _handle_new_event
    auth_events=auth_events,
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 1351, in _prep_event
    origin, event, context, auth_events=auth_events
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 1637, in do_auth
    self.auth.check(event, auth_events=auth_events)
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/api/auth.py", line 130, in check
    "Room %r does not exist" % (event.room_id,)
SynapseError: 403: Room '!cURbafjkfsMDVwdRDQ:matrix.org' does not exist
```

after upgrade there's no more exceptions, however there's still errors:

```
2016-12-16 23:40:11,956 - synapse.federation.transaction_queue - 459 - WARNING - - Transaction returned error for $1481931607248453kSbjx:matrix.org: {'error': "403: Room '!cURbafjkfsMDVwdRDQ:matrix.org' does not exist"}
```

receiving messages from the room works fine

trying to send a message:

```
2016-12-16 23:49:18,765 - synapse.http.server - 123 - INFO - PUT-3946- <SynapseRequest at 0x7f11cc313320 method=PUT uri=/_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/typing/%40xyz%3Axyz.is?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 403 - User @xyz:xyz.is not in room !cURbafjkfsMDVwdRDQ:matrix.org (<FrozenEvent event_id='$14814898074751Ncrap:xyz.is', type='m.room.member', state_key='@xyz:xyz.is'>)
2016-12-16 23:49:18,830 - synapse.http.server - 123 - INFO - PUT-3948- <SynapseRequest at 0x7f11bf1a18c0 method=PUT uri=/_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/typing/%40xyz%3Axyz.is?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 403 - User @xyz:xyz.is not in room !cURbafjkfsMDVwdRDQ:matrix.org (<FrozenEvent event_id='$14814898074751Ncrap:xyz.is', type='m.room.member', state_key='@xyz:xyz.is'>)
2016-12-16 23:49:19,130 - synapse.handlers.message - 497 - WARNING - PUT-3947- Denying new event <FrozenEvent event_id='$14819321587etCMC:xyz.is', type='m.room.message', state_key='None'> because 403: User @xyz:xyz.is not in room !cURbafjkfsMDVwdRDQ:matrix.org (None)
2016-12-16 23:49:19,132 - synapse.http.server - 123 - INFO - PUT-3947- <SynapseRequest at 0x7f11c45303b0 method=PUT uri=/_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/send/m.room.message/m1481932157240.1?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 403 - User @xyz:xyz.is not in room !cURbafjkfsMDVwdRDQ:matrix.org (None)
```

trying to leave the room:

```
2016-12-16 23:50:23,804 - synapse.access.http.8008 - 59 - INFO - POST-4181- 127.0.0.1 - 8008 - Received request: POST /_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/leave?access_token=<redacted>
2016-12-16 23:50:23,913 - synapse.http.server - 123 - INFO - POST-4181- <SynapseRequest at 0x7f11d562af38 method=POST uri=/_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/leave?access_token=<redacted> clientproto=HTTP/1.0 site=8008> SynapseError: 404 - Not a known room
2016-12-16 23:50:23,915 - synapse.access.http.8008 - 91 - INFO - POST-4181- 127.0.0.1 - 8008 - {@xyz:xyz.is} Processed request: 110ms (110ms, 0ms) (0ms/0) 66B 404 "POST /_matrix/client/r0/rooms/!cURbafjkfsMDVwdRDQ%3Amatrix.org/leave?access_token=<redacted> HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36"
```

trying to join the room using riot web client does not work - nothing happens at all, it's like it sees we're already in the room and does not send the request to the homeserver

trying to join the room using the legacy web client worked fine, after that I was able to leave it via riot web

**Comment by snevas** [comment]
Pitching in to say I have exact same issue, with the same room #matrix:matrix.org a.k.a. !cURbafjkfsMDVwdRDQ:matrix.org

**Comment by richvdh** [comment]
>  I got put into a room I didn't join myself, 

I think you did join it (at least) once, so I think what has happened here is that you got spuriously re-joined to the room, which I think makes this the same as the issue I'm investigating at #1933 .

**Comment by richvdh** [comment]
#1940 rather than #1933

**Comment by n0rc** [comment]
I had the same issue with room `!cURbafjkfsMDVwdRDQ:matrix.org` which I never joined.
The solution mentioned [here](https://github.com/matrix-org/synapse/issues/1933#issuecomment-282027852) fixed it for me now.

**Comment by richvdh** [comment]
> I had the same issue with room !cURbafjkfsMDVwdRDQ:matrix.org which I never joined.

Are you absolutely sure? If it is true, that is a serious issue. Please make yourself known on Matrix to clarify.

**Comment by luto** [comment]
@richvdh I got the same issue with the same room id. When I try to leave it comes back a couple of days later. When I try to post something, it says I am not in that room.

**Comment by richvdh** [comment]
Spontaneous *re*-joining of rooms you have *previously been in* is #1940.
