### ISSUE TITLE
MSC3861 token introspection sometimes fails when running inside a docker container 

### ISSUE THREAD

**Issue by hughns** [matrix-org/synapse#16319]
For example:

```
ex-full-stack-docker-synapse-1             | 2023-09-12 20:42:31,326 - synapse.http.client - 414 - INFO - GET-3 - Received response to GET http://mas:8080/.well-known/openid-configuration: 200
ex-full-stack-docker-synapse-1             | 2023-09-12 20:42:31,327 - synapse.http.client - 423 - INFO - GET-3 - Error sending request to  POST http://mas:8080/oauth2/introspect: RequestTimedOutError 504: Timeout waiting for response from remote server
ex-full-stack-docker-synapse-1             | 2023-09-12 20:42:31,327 - synapse.api.auth.msc3861_delegated - 259 - ERROR - GET-3 - Failed to introspect token
ex-full-stack-docker-synapse-1             | Traceback (most recent call last):
ex-full-stack-docker-synapse-1             |   File "/usr/local/lib/python3.11/site-packages/synapse/api/auth/msc3861_delegated.py", line 257, in get_user_by_access_token
ex-full-stack-docker-synapse-1             |     introspection_result = await self._introspect_token(token)
ex-full-stack-docker-synapse-1             |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ex-full-stack-docker-synapse-1             |   File "/usr/local/lib/python3.11/site-packages/synapse/api/auth/msc3861_delegated.py", line 178, in _introspect_token
ex-full-stack-docker-synapse-1             |     response = await self._http_client.request(
ex-full-stack-docker-synapse-1             |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ex-full-stack-docker-synapse-1             |   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 411, in request
ex-full-stack-docker-synapse-1             |     response = await make_deferred_yieldable(request_deferred)
ex-full-stack-docker-synapse-1             |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ex-full-stack-docker-synapse-1             |   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
ex-full-stack-docker-synapse-1             |     current.result = callback(  # type: ignore[misc]
ex-full-stack-docker-synapse-1             |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ex-full-stack-docker-synapse-1             |   File "/usr/local/lib/python3.11/site-packages/synapse/http/client.py", line 952, in _timeout_to_request_timed_out_error
ex-full-stack-docker-synapse-1             |     raise RequestTimedOutError("Timeout waiting for response from remote server")
ex-full-stack-docker-synapse-1             | synapse.http.RequestTimedOutError: 504: Timeout waiting for response from remote server
ex-full-stack-docker-synapse-1             | 2023-09-12 20:42:31,329 - synapse.http.server - 124 - INFO - GET-3 - <XForwardedForRequest at 0xffff7e49f810 method='GET' uri='/_matrix/client/r0/account/whoami' clientproto='HTTP/1.1' site='8008'> SynapseError: 503 - Unable to introspect the access token
ex-full-stack-docker-synapse-1             | 2023-09-12 20:42:31,329 - synapse.access.http.8008 - 465 - INFO - GET-3 - ::ffff:192.168.48.4 - 8008 - {None} Processed request: 0.010sec/0.000sec (0.005sec, 0.001sec) (0.000sec/0.000sec/0) 71B 503 "GET /_matrix/client/r0/account/whoami HTTP/1.1" "sync-v3-proxy-0.99.9" [0 dbevts]
```

CC @kegsay @erikjohnston

**Comment by sandhose** [comment]
This is a sample trace of what's happening when the SS proxy does the /whoami request:

<img width="1739" alt="image" src="https://github.com/matrix-org/synapse/assets/1549952/943b0463-0bda-4bb9-8d1e-f1e1d3d98716">

You can see that for introspecting the token, Synapse does two requests:

 - one to the OP .well-known/openid-configuration, because it never loaded it. This is then cached ([here](https://github.com/matrix-org/synapse/blob/954921736b88de25c775c519a206449e46b3bf07/synapse/api/auth/msc3861_delegated.py#L134))
 - one for the actually introspection request ([here](https://github.com/matrix-org/synapse/blob/954921736b88de25c775c519a206449e46b3bf07/synapse/api/auth/msc3861_delegated.py#L178))

Problem is that the introspection request is actually never done! I captured network trafic using tcpdump, and there is no trace of any packet going out for this request.

This only happens when Synapse has to do the metadata loading first. If it's already cached, the request works fine. I suspect then that there is some low-level twisted shenanigans going on

**Comment by erikjohnston** [comment]
This was due to MAS turning off `keep-alive` (i.e. closing the connection immediately after sending a response) without correctly setting `Connection: Close` as a response header.

https://github.com/matrix-org/matrix-authentication-service/blob/792d3c793b4e8e101ae0393a182f0b2fc10d5868/crates/listener/src/server.rs#L179

**Comment by sandhose** [comment]
That (https://github.com/matrix-org/matrix-authentication-service/pull/1775) fixed it. Thanks a lot @erikjohnston
