### ISSUE TITLE
500 on thumbnail fetch 

### ISSUE THREAD

**Issue by penguin42** [matrix-org/synapse#1634]
I'm trying to write the thumbnail fetch code for pidgin (for when the image is too big) and I'm reliably triggering a 500 on both matrix.org and my own server;  it's not clear to me what's different about my requests from the ones that work, originally I just had method=scale and width=640 so I assumed it was getting spooked at the missing height, but that doesn't help, neither does crop - so I'm not sure what it's annoyed at.
Note the client-server API example for thumbnail doesn't show the use of either the width or height.
Riot uses v1 instead of r0, but that doesn't seem to help.

wget https://matrix.penguin42.com//_matrix/media/r0/thumbnail/matrix.org/WaJRCcWmCxNHzRRhiAFCiSdG?method=scale&width=640&height=480&access_token=RedactedForPrivacy

from my logs:
2016-11-20 02:07:25,498 - synapse.http.server - 139 - ERROR - GET-13382- Failed handle request synapse.rest.media.v1.thumbnail_resource._async_render_GET on <synapse.rest.media.v1.thumbnail_resource.ThumbnailResource instance at 0x7f5459a31fc8>: <XForwardedForRequest at 0x7f542664ed88 method=GET uri=//_matrix/media/r0/thumbnail/matrix.org/WaJRCcWmCxNHzRRhiAFCiSdG?method=scale clientproto=HTTP/1.0 site=8008>
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/matrix_synapse-0.18.1-py2.7.egg/synapse/http/server.py", line 118, in wrapped_request_handler
    yield request_handler(self, request)
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/Twisted-16.4.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/Twisted-16.4.1-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/matrix_synapse-0.18.1-py2.7.egg/synapse/rest/media/v1/thumbnail_resource.py", line 75, in _async_render_GET
    width, height, method, m_type
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/Twisted-16.4.1-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/matrix_synapse-0.18.1-py2.7.egg/synapse/rest/media/v1/thumbnail_resource.py", line 222, in _respond_remote_thumbnail
    width, height, method, m_type, thumbnail_infos
  File "/home/matrix/.synapse/local/lib/python2.7/dist-packages/matrix_synapse-0.18.1-py2.7.egg/synapse/rest/media/v1/thumbnail_resource.py", line 317, in _select_thumbnail
    size_quality = abs((d_w - t_w) * (d_h - t_h))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by penguin42** [comment]
I now have it working, specifying the height and remembering not to specify the access key, e.g.

https://matrix.org/_matrix/media/r0/thumbnail/matrix.penguin42.com/thdkvTtQHTIiVStHRhlraXpF?width=640&height=480&method=scale

**Comment by richvdh** [comment]
@penguin42: looks like you were specifying the height before, so that would imply the difference is the absence of an access token? Are you sure? Could this actually be https://github.com/matrix-org/synapse/issues/1401?

**Comment by penguin42** [comment]
Something is still not right - thumbnail fetches are working for me, but not full size images at the moment.

**Comment by penguin42** [comment]
I've just merged a fix for the non-thumbnail problem

**Comment by richvdh** [comment]
It's unclear what the problem is here. If you can provide a URL that gives a 500, we can investigate.
