### ISSUE TITLE
URL previewer traceback while extracting page metadata

### ISSUE THREAD

**Issue by aperezdc** [matrix-org/synapse#1639]
Every now and then I am getting the following traceback in the Synapse log:

```
2016-11-22 15:32:35,704 - synapse.http.server - 139 - ERROR - GET-100- Failed handle request synapse.rest.media.v1.preview_url_resource._async_render_GET on <synapse.rest.media.v1.preview_url_resource.PreviewUrlResource instance at 0x7f2e965c0758>: <XForwardedForRequest at 0x7f2e62b163f8 method=GET uri=/_matrix/media/r0/preview_url?url=https%3A%2F%2Fcs.chromium.org%2Fchromium%2Fsrc%2Fservices%2Fui%2Fws%2Faccelerator.h%3Fq%3Daccelerator.h%26sq%3Dpackage%3Achromium%26dr%3DCSs%26l%3D5&ts=1479487655796&access_token=<redacted> clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 118, in wrapped_request_handler
    yield request_handler(self, request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 199, in _async_render_GET
    og = decode_and_calc_og(body, media_info['uri'], encoding)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 337, in decode_and_calc_og
    og = _calc_og(tree, media_uri)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 384, in _calc_og
    og['og:title'] = title[0].text.strip() if title else None
AttributeError: 'NoneType' object has no attribute 'strip'
```

[This particular URL](https://cs.chromium.org/chromium/src/services/ui/ws/accelerator.h?q=accelerator.h&sq=package:chromium&dr=CSs&l=5&ts=1479487655796) of the Chromium code search website seems to always trigger the issue.

**Comment by smgoller** [comment]
I'm currently having a problem with 0.18.5, running on centos 7. With URL Preview turned on, I get this crash shortly after starting (I believe it's try to parse a url in our room history):

 [  116.606994] traps: python2.7[9269] trap invalid opcode ip:7f09f2b16bee sp:7ffc6c1bd658 error:0 in etree.so[7f09f28f8000+4b7000]"

After mentioning this in #matrix-dev, I was asked to post a comment here.

**Comment by reivilibre** [comment]
The URL previewer has changed a lot in the last few years, I wouldn't expect this issue to still exist — please reopen if it does.
