### ISSUE TITLE
`register_new_matrix_user` can't deal with unix socket listeners

### ISSUE THREAD

**Issue by Sir-Photch** [matrix-org/synapse#16390]
### Description

I have configured an unix-socket as a listener in homeserver.yaml, without listening on ports, on a newly configured synapse instance.

This way, `register_new_matrix_user` crashes.

### Steps to reproduce

- setup only unix socket listener with `path`
- use `sudo -u synapse -- register_new_matrix_user -c [config path] --admin`
- observe crash

### Homeserver

self-hosted synapse

### Synapse Version

1.92.1

### Installation Method

Other (please mention below)

### Database

single pgsql 15.4, fresh setup

### Workers

Single process

### Platform

archlinux arm

### Configuration

```yaml
listeners:
  - path: /run/synapse/homeserver.sock
    mode: 660
    type: http
    resources:
      - names: [client, federation]
```

### Relevant log output

```shell
not relevant
```

### Anything else that would be useful to know?

Error Traceback:

```python
Traceback (most recent call last):
  File "/usr/bin/register_new_matrix_user", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/_scripts/register_new_matrix_user.py", line 247, in main
    server_url = _find_client_listener(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/synapse/_scripts/register_new_matrix_user.py", line 309, in _find_client_listener
    return f"http://localhost:{listener['port']}"
                               ~~~~~~~~^^^^^^^^
KeyError: 'port'
```

**Comment by Sir-Photch** [comment]
This script obviously expects listening to happen on a port, which is not the case for sockets. But also, the `requests`-library does not seem to support unix sockets.

**Comment by aceArt-GmbH** [comment]
I resolved this by giving the script the reverse proxy address
