### ISSUE TITLE
Can't back-paginate in #matrix-dev

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#1648]
For some reason matrix.org's synapse doesn't seem to be able to back-paginate past 2016/11/18 19:20. Start at https://matrix.to/#/!XqBunHwQIXUiqCaoxq:matrix.org/$1479592369333796MrSlT:matrix.org and work back to observe

**Comment by richvdh** [comment]
The pagination request (`https://matrix.org/_matrix/client/r0/rooms/!XqBunHwQIXUiqCaoxq%3Amatrix.org/messages?from=t84649-58189869_83662686_533697_7129147_48871_22742_79637&limit=20&dir=b&access_token=...`) gives a 401.

It appears to be attempting to backfill (from itself) and getting a rejection:

```
2016-11-24 09:56:08,078 - synapse.access.http.8080 - 59 - INFO - GET-21759394 - 83.166.71.13 - 8080 - Received request: GET /_matrix/client/r0/rooms/!XqBunHwQIXUiqCaoxq%3Amatrix.org/messages?from=t84452-56988928_80666331_105075_6492258_42512_20549_49740&limit=20&dir=b&access_token=<redacted>
2016-11-24 09:56:08,100 - synapse.http.outbound - 122 - INFO - GET-21759394 - {GET-O-36010242} [perlsite.co.uk] Sending request: GET matrix://perlsite.co.uk/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458Xz
HkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de
2016-11-24 09:56:08,226 - synapse.http.matrixfederationclient - 181 - WARNING - GET-21759394 - {GET-O-36010242} Sending request failed to perlsite.co.uk: GET matrix://perlsite.co.uk/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458XzHkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de: ConnectionRefusedError - ConnectionRefusedError: Connection refused
2016-11-24 09:56:09,136 - synapse.http.matrixfederationclient - 181 - WARNING - GET-21759394 - {GET-O-36010242} Sending request failed to perlsite.co.uk: GET matrix://perlsite.co.uk/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458XzHkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de: ConnectionRefusedError - ConnectionRefusedError: Connection refused
2016-11-24 09:56:09,981 - synapse.http.matrixfederationclient - 181 - WARNING - GET-21759394 - {GET-O-36010242} Sending request failed to perlsite.co.uk: GET matrix://perlsite.co.uk/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458XzHkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de: ConnectionRefusedError - ConnectionRefusedError: Connection refused
2016-11-24 09:56:12,646 - synapse.http.matrixfederationclient - 181 - WARNING - GET-21759394 - {GET-O-36010242} Sending request failed to perlsite.co.uk: GET matrix://perlsite.co.uk/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458XzHkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de: ConnectionRefusedError - ConnectionRefusedError: Connection refused
2016-11-24 09:56:12,646 - synapse.http.outbound - 207 - INFO - GET-21759394 - {GET-O-36010242} [perlsite.co.uk] Result: ConnectionRefusedError - ConnectionRefusedError: Connection refused
2016-11-24 09:56:12,646 - synapse.handlers.federation - 589 - ERROR - GET-21759394 - Failed to backfill from perlsite.co.uk because Connection was refused by other side: 111: Connection refused.
Traceback (most recent call last):
  File "synapse/handlers/federation.py", line 562, in try_backfill
    extremities=[e for e in extremities.keys()]
ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
2016-11-24 09:56:12,646 - synapse.http.outbound - 122 - INFO - GET-21759394 - {GET-O-36010648} [localhost] Sending request: GET matrix://localhost/_matrix/federation/v1/backfill/!XqBunHwQIXUiqCaoxq:matrix.org/?limit=100&v=%24144706665122FHIxp%3Aoddvar.org&v=%24141875666110yGiSq%3Ajki.re&v=%24146889759458XzHkK%3Akentshikama.com&v=%2414396814951757TifFF%3Amatrix.sipgate.net&v=%2414794849711587VZxnv%3Aldbco.de
016-11-24 09:56:13,164 - synapse.http.outbound - 207 - INFO - GET-21759394 - {GET-O-36010648} [localhost] Result: 401 Unauthorized
2016-11-24 09:56:13,165 - synapse.http.server - 126 - ERROR - GET-21759394 - 401: Unauthorized
Traceback (most recent call last):
  File "synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "synapse/rest/client/v1/room.py", line 399, in on_GET
    event_filter=event_filter,
  File "synapse/handlers/message.py", line 127, in get_messages
    room_id, max_topo
  File "synapse/handlers/federation.py", line 595, in maybe_backfill
    success = yield try_backfill(likely_domains)
  File "synapse/handlers/federation.py", line 562, in try_backfill
    extremities=[e for e in extremities.keys()]
  File "synapse/handlers/federation.py", line 341, in backfill
    extremities=extremities,
  File "synapse/federation/federation_client.py", line 232, in backfill
    dest, context, extremities, limit)
  File "synapse/http/matrixfederationclient.py", line 398, in get_json
    timeout=timeout,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "synapse/http/matrixfederationclient.py", line 217, in _create_request
    response.code, response.phrase, body
HttpResponseException: 401: Unauthorized
2016-11-24 09:56:13,165 - synapse.access.http.8080 - 91 - INFO - GET-21759394 - 83.166.71.13 - 8080 - {@dave:matrix.org} Processed request: 5087ms (40ms, 0ms) (1ms/1) 46B 401 "GET /_matrix/client/r0/rooms/!XqBunHwQIXUiqCaoxq%3Amatrix.org/messages?from=t84452-56988928_80666331_105075_6492258_42512_20549_49740&limit=2
```

**Comment by richvdh** [comment]
@erikjohnston any idea what is going on here?

**Comment by kyrias** [comment]
I'm getting the following:

```
2016-11-29 08:46:52,266 - synapse.http.server - 126 - ERROR - GET-146558- 401: Unauthorized
Traceback (most recent call last):
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/rest/client/v1/room.py", line 399, in on_GET
    event_filter=event_filter,
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/handlers/message.py", line 127, in get_messages
    room_id, max_topo
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/handlers/federation.py", line 595, in maybe_backfill
    success = yield try_backfill(likely_domains)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/handlers/federation.py", line 562, in try_backfill
    extremities=[e for e in extremities.keys()]
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/handlers/federation.py", line 341, in backfill
    extremities=extremities,
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/federation/federation_client.py", line 232, in backfill
    dest, context, extremities, limit)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 398, in get_json
    timeout=timeout,
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 1260, in _inlineCallbacks
    result = g.send(result)
  File "/home/kyrias/code/matrix/env/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 217, in _create_request
    response.code, response.phrase, body
HttpResponseException: 401: Unauthorized
```

**Comment by kyrias** [comment]
On my own HS

**Comment by richvdh** [comment]
oh, this is a dup of https://github.com/matrix-org/synapse/issues/1451
