### ISSUE TITLE
ERROR:root:Can't import 'blist' which is part of 'blist'

### ISSUE THREAD

**Issue by SiNaPsEr0x** [matrix-org/synapse#1715]
why this error?

2016-12-23 08:38:07,986 - synapse.storage.prepare_database - 212 - INFO - - Upgrading schema to v25
2016-12-23 08:38:07,987 - synapse.storage.prepare_database - 245 - INFO - - Running script 25/fts.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 485, in <module>
    main()
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 480, in main
    hs = setup(sys.argv[1:])
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 313, in setup
    prepare_database(db_conn, database_engine, config=config)
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 62, in prepare_database
    cur, user_version, delta_files, upgraded, database_engine, config
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 246, in _upgrade_existing_database
    module.run_create(cur, database_engine)
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/schema/delta/25/fts.py", line 51, in run_create
    cur.execute(SQLITE_TABLE)
sqlite3.OperationalError: no such module: fts4
error starting (exit code: 1); see above for logs

**Comment by ara4n** [comment]
It looks like you haven't installed the python dependencies in your 
virtualenv, possibly because the install script crashed out halfway. 
Try running it again.

**Comment by SiNaPsEr0x** [comment]
If possibile i remove .cache for recompile totally?

**Comment by SiNaPsEr0x** [comment]
thank you working fine I delete .cache .pip .pki and recompile

**Comment by richvdh** [comment]
issue doesn't match description? probably a dup of #1717 anyway
