### ISSUE TITLE
sqlite3.OperationalError: no such module: fts4

### ISSUE THREAD

**Issue by SiNaPsEr0x** [matrix-org/synapse#1717]
SQLite version 3.15.2 2016-11-28 19:13:37
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> WITH opts(n, opt) AS (
   ...>   VALUES(0, NULL)
   ...>   UNION ALL
   ...>   SELECT n + 1,
   ...>          sqlite_compileoption_get(n)
   ...>   FROM opts
   ...>   WHERE sqlite_compileoption_get(n) IS NOT NULL
   ...> )
   ...> SELECT opt
   ...> FROM opts
   ...> WHERE opt LIKE '%FTS%';
ENABLE_FTS3
ENABLE_FTS5
sqlite> ^C^C^C(.synapse) [x0n3@mail .synapse]$ 

I installed sqlite with fts4... but

2016-12-23 08:38:07,986 - synapse.storage.prepare_database - 212 - INFO - - Upgrading schema to v25
2016-12-23 08:38:07,987 - synapse.storage.prepare_database - 245 - INFO - - Running script 25/fts.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 485, in <module>
    main()
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 480, in main
    hs = setup(sys.argv[1:])
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 313, in setup
    prepare_database(db_conn, database_engine, config=config)
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 62, in prepare_database
    cur, user_version, delta_files, upgraded, database_engine, config
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 246, in _upgrade_existing_database
    module.run_create(cur, database_engine)
  File "/home/x0n3/.synapse/lib/python2.7/site-packages/synapse/storage/schema/delta/25/fts.py", line 51, in run_create
    cur.execute(SQLITE_TABLE)
sqlite3.OperationalError: no such module: fts4
error starting (exit code: 1); see above for logs

in the fts.py the error is here:
SQLITE_TABLE = (
    "CREATE VIRTUAL TABLE event_search"
    " USING fts ( event_id, room_id, sender, key, value )"
)

**Comment by SiNaPsEr0x** [comment]
Is a centos

**Comment by richvdh** [comment]
dup #2696
