### ISSUE TITLE
psycopg2.IntegrityError / sqlite3.IntegrityError: NOT NULL constraint failed: stream_ordering_to_exterm.stream_ordering

### ISSUE THREAD

**Issue by rubo77** [matrix-org/synapse#1726]
On update from 0.18.0 we get this errors and synapse wont start again:

```
synapse.storage.prepare_database - 256 - INFO - - Applying schema 36/readd_public_rooms.sql
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/irc-bridge/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 485, in <module>
    main()
  File "/home/irc-bridge/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 480, in main
    hs = setup(sys.argv[1:])
  File "/home/irc-bridge/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 313, in setup
    prepare_database(db_conn, database_engine, config=config)
  File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 62, in prepare_database
    cur, user_version, delta_files, upgraded, database_engine, config
  File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 257, in _upgrade_existing_database
    executescript(cur, absolute_path)
  File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 337, in executescript
    txn.execute(statement)
sqlite3.IntegrityError: NOT NULL constraint failed: stream_ordering_to_exterm.stream_ordering
error starting (exit code: 1); see above for logs
```

**Comment by rubo77** [comment]
Maybe the bug is caused by a minutely purge script, we use for one of our rooms, that started during the upgrade process:


```
#!/bin/bash
# crontab -e
# * *  *   *   *     bash /home/irc-bridge/.synapse/EIGENE_purge_history_minuntely > /dev/null 2>&1

cd /home/irc-bridge/.synapse/

DOMAIN="matrix.ourserver"
TIME='1 minute ago'

#ADMIN="@rubo77:matrix.ourserver"
TOKEN=$(sqlite3 homeserver.db "select token from access_tokens where user_id like '$ADMIN' order by id desc limit 1;")

ROOM='!LPRsNFBlKAAaaamFed:matrix.ourserver' # #whisper:matrix.ourserver

# creates a timestamp from the given time string:
UNIX_TIMESTAMP=$(date +%s%3N --date='TZ="UTC+2" '"$TIME")

EVENT_ID=$(sqlite3 homeserver.db "select event_id from events where type='m.room.message' and received_ts<'$UNIX_TIMESTAMP' and room_id='$ROOM' order by received_ts desc limit 1;")
sleep 1
curl -v -X POST $DOMAIN':8008/_matrix/client/r0/admin/purge_history/'$ROOM'/'$EVENT_ID'?access_token='$TOKEN
```

**Comment by rubo77** [comment]
We migrated successfully to Postgress database now within the 0.18.0 version.

We will try to upgrade synapse to the latest release again now.

What do we have to backup, before we start the upgrade process again, in case it goes wrong again?  
I guess `/var/lib/postgresql/`

**Comment by rubo77** [comment]
With Postrges as database, we get this error:

```
2017-01-17 19:49:04,821 - twisted - 131 - ERROR - -     prepare_database(db_conn, database_engine, config=config)                                             │
2017-01-17 19:49:04,821 - twisted - 131 - ERROR - -   File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", │
line 62, in prepare_database                                                                                                                                  │
2017-01-17 19:49:04,821 - twisted - 131 - ERROR - -     cur, user_version, delta_files, upgraded, database_engine, config                                     │
2017-01-17 19:49:04,821 - twisted - 131 - ERROR - -   File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", │
line 257, in _upgrade_existing_database                                                                                                                       │
2017-01-17 19:49:04,822 - twisted - 131 - ERROR - -     executescript(cur, absolute_path)                                                                     │
2017-01-17 19:49:04,822 - twisted - 131 - ERROR - -   File "/home/irc-bridge/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", │
line 337, in executescript                                                                                                                                    │
2017-01-17 19:49:04,822 - twisted - 131 - ERROR - -     txn.execute(statement)                                                                                │
2017-01-17 19:49:04,822 - twisted - 131 - ERROR - - psycopg2.IntegrityError: FEHLER:  NULL-Wert in Spalte »stream_ordering« verletzt Not-Null-Constraint      │
2017-01-17 19:49:04,822 - twisted - 131 - ERROR - - DETAIL:  Fehlgeschlagene Zeile enthält (null, !BKNbWEQVVcTnyvnPQb:matrix.eclabs.de, $14701711513637mreQT:m│
atrix.eclabs.de).                                                                                                                                             │
```

**Comment by rubo77** [comment]
Now I tried to remove the `NOT NULL` in the database table with:

    ALTER TABLE stream_ordering_to_exterm ALTER COLUMN stream_ordering DROP NOT NULL;        

Then I had to delete the pidfile:

    rm ~/.synapse/homeserver.pid

And it works.

# Now the question:

The database table `stream_ordering_to_exterm` has the field `stream_ordering` without `NOT NULL` now, is this correct? Or do we have to edit it back and delete all rows that are NULL?

**Comment by richvdh** [comment]
I'm confused about this, but suspect it has gone away.
