### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'content' in _update_membership

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/synapse#1796]
https://github.com/matrix-org/synapse/blob/772b8ebe5419bc1ee32644d0a099bad89b9f7588/synapse/handlers/room_member.py#L235

```
2017-01-10 19:15:27,181 - synapse.http.server - 139 - ERROR - POST-873438 - Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x4fe6510>: <XForwardedForRequest at 0x39185518 method=POST uri=/_matrix/client/r0/join/!ZZCkJvNTraceback (most recent call last):
  File "synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/rest/client/v1/room.py", line 269, in on_POST
    third_party_signed=content.get("third_party_signed", None),
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room_member.py", line 174, in update_membership
    content=content,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "synapse/handlers/room_member.py", line 235, in _update_membership
    same_content = content == old_state.content
AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by richvdh** [comment]
this was fixed by 7b62d0b
