### ISSUE TITLE
ValueError: Attempted to iterate a UserID

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/synapse#1797]
```
2017-01-10 19:26:15,726 - twisted - 131 - CRITICAL -  - Unhandled error in Deferred:
2017-01-10 19:26:15,726 - twisted - 131 - CRITICAL -  - 
Traceback (most recent call last):
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room_member.py", line 174, in update_membership
    content=content,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room_member.py", line 212, in _update_membership
    latest_event_ids = yield self.store.get_latest_event_ids_in_room(room_id)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/storage/_base.py", line 311, in runInteraction
    inner_func, *args, **kwargs
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "synapse/storage/_base.py", line 305, in inner_func
    func, *args, **kwargs
  File "synapse/storage/_base.py", line 234, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "synapse/storage/_base.py", line 577, in _simple_select_onecol_txn
    txn.execute(sql, keyvalues.values())
  File "synapse/storage/_base.py", line 78, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "synapse/storage/_base.py", line 102, in _do_execute
    sql, *args
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
  File "synapse/types.py", line 81, in __iter__
    raise ValueError("Attempted to iterate a %s" % (type(self).__name__,))
ValueError: Attempted to iterate a UserID
```

**Comment by NegativeMjark** [comment]
Turned to be @erikjohnston typoing repeatedly while fiddling in the manhole shell.
