### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment in get_avatar_url

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/synapse#1798]
```
Traceback (most recent call last):
  File "synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionInto    return g.throw(self.type, self.value, self.tb)
  File "synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionInto    return g.throw(self.type, self.value, self.tb)
  File "synapse/rest/client/v1/profile.py", line 122, in on_GET
    user,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionInto    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/profile.py", line 111, in get_avatar_url
    defer.returnValue(result["avatar_url"])
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by richvdh** [comment]
lacks repro steps
