### ISSUE TITLE
Channel out-of-sync on different homeservers

### ISSUE THREAD

**Issue by benhylau** [matrix-org/synapse#1854]
`#tomesh:tomesh.net` and `#tomesh:matrix.org` are the same channel, federated to `freenode/#tomesh` through the Matrix Freenode bridge. The three places have become out-of-sync after [this message](https://chat.tomesh.net/#/room/#tomesh:tomesh.net/$1485293421519wwQtn:tomesh.net). These are the Synapse server log `ERROR` on https://chat.tomesh.net:

```
2017-01-24 08:30:04,883 - synapse.http.client - 299 - ERROR - GET-374273- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 09:08:14,489 - synapse.http.client - 299 - ERROR - GET-377685- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 09:46:41,646 - synapse.http.client - 299 - ERROR - GET-382038- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 10:36:08,943 - synapse.http.client - 299 - ERROR - GET-388168- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 12:47:56,691 - synapse.http.client - 299 - ERROR - GET-408696- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 12:49:36,266 - synapse.federation.federation_server - 175 - ERROR - PUT-412779- Failed to handle PDU
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 168, in on_incoming_transaction
    yield self._handle_new_pdu(transaction.origin, pdu)
CancelledError
--
2017-01-24 13:38:53,625 - synapse.http.client - 299 - ERROR - GET-414945- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 14:12:06,701 - synapse.federation.federation_server - 175 - ERROR - PUT-422360- Failed to handle PDU
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 168, in on_incoming_transaction
    yield self._handle_new_pdu(transaction.origin, pdu)
CancelledError
--
2017-01-24 14:16:10,985 - synapse.federation.federation_server - 175 - ERROR - PUT-422813- Failed to handle PDU
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 168, in on_incoming_transaction
    yield self._handle_new_pdu(transaction.origin, pdu)
CancelledError
--
2017-01-24 14:41:23,976 - synapse.http.client - 299 - ERROR - GET-422292- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 15:24:48,973 - synapse.http.client - 299 - ERROR - GET-427328- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 16:23:57,939 - synapse.http.client - 299 - ERROR - GET-434362- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 17:28:31,892 - synapse.http.client - 299 - ERROR - GET-443355- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 17:50:26,157 - synapse.http.client - 299 - ERROR - GET-448414- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 18:25:06,783 - synapse.http.client - 299 - ERROR - GET-450638- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 19:43:24,994 - synapse.http.client - 299 - ERROR - GET-459561- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
2017-01-24 20:25:33,187 - synapse.http.client - 299 - ERROR - GET-463659- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 20:59:22,093 - synapse.http.client - 299 - ERROR - GET-467033- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 22:32:30,023 - synapse.http.client - 299 - ERROR - GET-476377- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 23:11:44,392 - synapse.http.client - 299 - ERROR - GET-80- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-24 23:42:21,860 - synapse.http.client - 299 - ERROR - GET-3570- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
--
2017-01-25 00:26:42,063 - synapse.http.client - 299 - ERROR - GET-7913- Failed to download body
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/http/client.py", line 296, in get_file
    response, output_stream, max_size
ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
```

**Comment by benhylau** [comment]
Everything is back in sync now. The two Synapse hs were out for sync for about 12 hours, and then bridge came back about another 4.

**Comment by benhylau** [comment]
@richvdh Any idea what may have caused this federation breakage for 12 hours? Was there anything special going on at the Matrix hs? I was hoping we'd find something in its logs.

**Comment by richvdh** [comment]
Yes, matrix.org had problems last night: https://matrix.org/blog/2017/01/25/matrix-org-homeserver-outage-25th-jan-2017/
