### ISSUE TITLE
sqlite3.OperationalError: index user_ips_user 

### ISSUE THREAD

**Issue by itree** [matrix-org/synapse#1856]
Debian Package for Stretchy. Has this error
```
/usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/
2017-01-26 14:12:39,493 - twisted - 131 - ERROR - - Traceback (most recent call last):
2017-01-26 14:12:39,494 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
2017-01-26 14:12:39,494 - twisted - 131 - ERROR - -     "__main__", fname, loader, pkg_name)
2017-01-26 14:12:39,495 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
2017-01-26 14:12:39,495 - twisted - 131 - ERROR - -     exec code in run_globals
2017-01-26 14:12:39,496 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 484, in <module>
2017-01-26 14:12:39,496 - twisted - 131 - ERROR - -     main()
2017-01-26 14:12:39,496 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 479, in main
2017-01-26 14:12:39,497 - twisted - 131 - ERROR - -     hs = setup(sys.argv[1:])
2017-01-26 14:12:39,497 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 312, in setup
2017-01-26 14:12:39,498 - twisted - 131 - ERROR - -     prepare_database(db_conn, database_engine, config=config)
2017-01-26 14:12:39,498 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 65, in prepare_database
2017-01-26 14:12:39,499 - twisted - 131 - ERROR - -     _setup_new_database(cur, database_engine)
2017-01-26 14:12:39,499 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 131, in _setup_new_database
2017-01-26 14:12:39,500 - twisted - 131 - ERROR - -     executescript(cur, sql_loc)
2017-01-26 14:12:39,500 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 337, in executescript
2017-01-26 14:12:39,501 - twisted - 131 - ERROR - -     txn.execute(statement)
2017-01-26 14:12:39,501 - twisted - 131 - ERROR - - sqlite3.OperationalError: index user_ips_user 
```

**Comment by richvdh** [comment]
which version of synapse? were you trying to create a new database? is it still a problem in synapse 0.20.0?
