### ISSUE TITLE
Can not start after upgrade: AttributeError: 'MultiBackend' object has no attribute 'elliptic_curve_exchange_algorithm_supported'

### ISSUE THREAD

**Issue by KlausHans** [matrix-org/synapse#1918]
Hello,

today i upgraded Synapse from the Matrix repository on Debian via apt.

At first i got the message:

Missing Requirement: Version of 'Twisted>=16.0.0' in '/usr/local/lib/python2.7/dist-packages/twisted/__init__.pyc' is too old. '15.5.0' < '16.0.0'
To install run:
    pip install --upgrade --force "Twisted>=16.0.0"
error starting (exit code: 1); see above for logs

The suggested solution solved this. Now i am getting:

Starting
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 62, in <module>
    from synapse.util.manhole import manhole
  File "/usr/lib/python2.7/dist-packages/synapse/util/manhole.py", line 17, in <module>
    from twisted.conch import manhole_ssh
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/manhole_ssh.py", line 14, in <module>
    from twisted.conch.ssh import factory, session
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/factory.py", line 18, in <module>
    from twisted.conch.ssh import (_kex, transport, userauth, connection)
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 345, in <module>
    class SSHTransportBase(protocol.Protocol):
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/transport.py", line 479, in SSHTransportBase
    supportedKeyExchanges = _kex.getSupportedKeyExchanges()
  File "/usr/local/lib/python2.7/dist-packages/twisted/conch/ssh/_kex.py", line 289, in getSupportedKeyExchanges
    supported = backend.elliptic_curve_exchange_algorithm_supported(
AttributeError: 'MultiBackend' object has no attribute 'elliptic_curve_exchange_algorithm_supported'
error starting (exit code: 1); see above for logs

Synapse version: 0.19.1-1

What does this mean? Went something wrong on my side or is this a bug? Can i revert to the previous version?
Thanks

**Comment by KlausHans** [comment]
Ok, i got it. I need Twisted 16.0.0.. But
pip install --upgrade --force "Twisted>=16.0.0" 
installed Twisted 17.1.0.

With a 
pip install --upgrade "Twisted==16.0.0"
i solved this issue.
