### ISSUE TITLE
synapse.push.httppusher - 135 - ERROR - - Exception processing notifs

### ISSUE THREAD

**Issue by ndarilek** [matrix-org/synapse#1938]
Using Synapse 3346a213241544faa48b1243906452a646f93a4a from the Docker image. I've been seeing the following odd behaviors, and I'm not sure which (if any) are related to me getting lots and lots and lots of the included tracebacks in my log:

 * Android push notifications seem to stop after a time, then resume when I relaunch Riot. This makes me wonder if what I'm seeing aren't in fact Google push notifications, but the result of polling the server, which stops when the app is killed (Background sync is on.)
 * Getting CORS errors on initial sync when attempting to use riot.im or riot.im/develop, which I'm told is a red herring.

The error:

```
2017-02-22 22:02:51,494 - synapse.push.httppusher - 135 - ERROR - - Exception processing notifs
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 133, in _process
    yield self._unsafe_process()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 155, in _unsafe_process
    processed = yield self._process_one(push_action)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 222, in _process_one
    rejected = yield self.dispatch_push(event, tweaks, badge)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 292, in dispatch_push
    notification_dict = yield self._build_notification_dict(event, tweaks, badge)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 248, in _build_notification_dict
    self.store, self.state_handler, event, self.user_id
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/synapse/push/push_tools.py", line 66, in get_context_for_event
    sender_state_event_id = room_state_ids[("m.room.member", ev.sender)]
KeyError: ('m.room.member', u'@sniffy:unixpimps.net')
```

**Comment by ndarilek** [comment]
Still getting a ton of these in my logs.

1. Could this be preventing Riot from working? Every instance I've tried, from riot.im to riot.im/develop to my own self-hosted instance no longer works.
2. Even if there is no code fix forthcoming, it looks like this is due to a single piece of bad data. Can I somehow purge this bad data so I can at least get rid of these errors?

Thanks.

**Comment by richvdh** [comment]
This seems to imply that you are being sent a push for a room you're not a member of, which is very odd.

(It's unlikey it will stop riot-web working. The exception is affecting the code that sends out push notifications).

**Comment by zymptomLabs** [comment]
I solved this by upgrading the service_identity package to 18.1.0

pip install service_identity==18.1.0

all of my notifications are working again.

**Comment by richvdh** [comment]
> I solved this by upgrading the service_identity package to 18.1.0

That sounds like a coincidence.

**Comment by richvdh** [comment]
I'm going to assume this is no longer a problem. if anyone is still seeing it, we can reopen.
