### ISSUE TITLE
sqlite3 > postgresql migration

### ISSUE THREAD

**Issue by myobfee** [matrix-org/synapse#1944]
Attempting to migrate, receive this set of errors while running migration script following instructions from https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst

.synapse$ synapse_port_db --sqlite-database homeserver.db.snapshot --postgres-config homeserver.yaml.postgresql
Traceback (most recent call last):
  File "/home/cw/.synapse/bin/synapse_port_db", line 897, in <module>
    postgres_config = yaml.safe_load(args.postgres_config)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/composer.py", line 64, in compose_node
    if self.check_event(AliasEvent):
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/parser.py", line 449, in parse_block_mapping_value
    if not self.check_token(KeyToken, ValueToken, BlockEndToken):
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/cw/.synapse/local/lib/python2.7/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "homeserver.yaml.postgresql", line 144, column 1
(.synapse) cw@matrix:~/.synapse$

**Comment by myobfee** [comment]
Figured out my problem and believe it should be communicated within the documentation.  

Be sure to use spaces, not tabs when adjusting the homeserver.yaml file for the postgresql configuration options.  Replacing the tabs (hence the \t error) with spaces resolved my errors and I am now working.  -cw
