### ISSUE TITLE
Hello I get the following when starting the serves on mac

### ISSUE THREAD

**Issue by trisimix** [matrix-org/synapse#2006]
I get the following on Mac, just following the setup on the readme.

```
(.synapse) trisimix:.synapse trisimix$ synctl start
Starting ...
2017-03-15 01:06:47,837 - synapse.python_dependencies - 115 - INFO - - Using 'bcrypt' version None from '/Users/trisimix/.synapse/lib/python2.7/site-packages/bcrypt/__init__.pyc' to satisfy 'py-bcrypt'
2017-03-15 01:06:47,838 - synapse.python_dependencies - 115 - INFO - - Using 'msgpack' version None from '/Users/trisimix/.synapse/lib/python2.7/site-packages/msgpack/__init__.pyc' to satisfy 'msgpack-python>=0.3.0'
2017-03-15 01:06:47,838 - synapse.python_dependencies - 115 - INFO - - Using 'frozendict' version None from '/Users/trisimix/.synapse/lib/python2.7/site-packages/frozendict/__init__.pyc' to satisfy 'frozendict>=0.4'
2017-03-15 01:06:47,838 - synapse.python_dependencies - 115 - INFO - - Using 'OpenSSL' version '16.2.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/OpenSSL/__init__.pyc' to satisfy 'pyopenssl>=0.14'
2017-03-15 01:06:47,839 - synapse.python_dependencies - 115 - INFO - - Using 'pydenticon' version None from '/Users/trisimix/.synapse/lib/python2.7/site-packages/pydenticon/__init__.pyc' to satisfy 'pydenticon'
2017-03-15 01:06:47,839 - synapse.python_dependencies - 115 - INFO - - Using 'pymacaroons' version '0.9.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/pymacaroons/__init__.pyc' to satisfy 'pymacaroons-pynacl'
2017-03-15 01:06:47,839 - synapse.python_dependencies - 115 - INFO - - Using 'service_identity' version '16.0.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/service_identity/__init__.pyc' to satisfy 'service_identity>=1.0.0'
2017-03-15 01:06:47,840 - synapse.python_dependencies - 115 - INFO - - Using 'signedjson' version '1.0.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/signedjson/__init__.pyc' to satisfy 'signedjson>=1.0.0'
2017-03-15 01:06:47,840 - synapse.python_dependencies - 115 - INFO - - Using 'blist' version '1.3.6' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/blist/__init__.pyc' to satisfy 'blist'
2017-03-15 01:06:47,840 - synapse.python_dependencies - 115 - INFO - - Using 'yaml' version '3.12' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/yaml/__init__.pyc' to satisfy 'pyyaml'
2017-03-15 01:06:47,841 - synapse.python_dependencies - 115 - INFO - - Using 'twisted' version '17.1.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/twisted/__init__.pyc' to satisfy 'Twisted>=16.0.0'
2017-03-15 01:06:47,841 - synapse.python_dependencies - 115 - INFO - - Using 'unpaddedbase64' version '1.1.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/unpaddedbase64.pyc' to satisfy 'unpaddedbase64>=1.1.0'
2017-03-15 01:06:47,842 - synapse.python_dependencies - 115 - INFO - - Using 'ujson' version '1.35' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/ujson.so' to satisfy 'ujson'
2017-03-15 01:06:47,842 - synapse.python_dependencies - 115 - INFO - - Using 'nacl' version '0.3.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
2017-03-15 01:06:47,842 - synapse.python_dependencies - 115 - INFO - - Using 'nacl.bindings' version '0.3.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
2017-03-15 01:06:47,842 - synapse.python_dependencies - 115 - INFO - - Using 'daemonize' version '2.4.7' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/daemonize.pyc' to satisfy 'daemonize'
2017-03-15 01:06:47,843 - synapse.python_dependencies - 115 - INFO - - Using 'canonicaljson' version '1.0.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/canonicaljson.pyc' to satisfy 'canonicaljson>=1.0.0'
2017-03-15 01:06:47,843 - synapse.python_dependencies - 115 - INFO - - Using 'saml2' version '3.0.2' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/saml2/__init__.pyc' to satisfy 'pysaml2>=3.0.0,<4.0.0'
2017-03-15 01:06:47,844 - synapse.python_dependencies - 115 - INFO - - Using 'pyasn1' version '0.2.3' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/pyasn1/__init__.pyc' to satisfy 'pyasn1'
2017-03-15 01:06:47,844 - synapse.python_dependencies - 115 - INFO - - Using 'PIL' version '4.0.0' from '/Users/trisimix/.synapse/lib/python2.7/site-packages/PIL/__init__.pyc' to satisfy 'pillow'
2017-03-15 01:06:47,902 - synapse.app.homeserver - 296 - INFO - - Server hostname: compulsive.ga
2017-03-15 01:06:47,904 - synapse.app.homeserver - 297 - INFO - - Server version: Synapse/0.19.2
2017-03-15 01:06:47,909 - synapse.app.homeserver - 315 - INFO - - Preparing database: sqlite3...
2017-03-15 01:06:47,925 - synapse.storage.prepare_database - 212 - INFO - - Upgrading schema to v40
2017-03-15 01:06:47,926 - synapse.app.homeserver - 333 - INFO - - Database prepared in sqlite3.
2017-03-15 01:06:47,927 - synapse.server - 154 - INFO - - Setting up.
2017-03-15 01:06:47,934 - synapse.storage.event_push_actions - 490 - INFO - - Searching for stream ordering 1 month ago
2017-03-15 01:06:47,934 - synapse.storage.event_push_actions - 496 - INFO - - Found stream ordering 1 month ago: it's 0
2017-03-15 01:06:47,943 - synapse.server - 156 - INFO - - Finished setting up.
2017-03-15 01:06:47,971 - synapse.handlers.auth - 64 - INFO - - Extra password_providers: []
2017-03-15 01:06:47,993 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x1040bb690> to path /_matrix/client/r0
2017-03-15 01:06:47,994 - synapse.util.httpresourcetree - 43 - INFO - - Attaching FilePath('/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/static') to path /_matrix/static
2017-03-15 01:06:47,995 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x1040bb690> to path /_matrix/client/versions
2017-03-15 01:06:47,995 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x1040bb690> to path /_matrix/client/unstable
2017-03-15 01:06:47,996 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource instance at 0x103e9fa70> to path /_matrix/media/v1
2017-03-15 01:06:47,996 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x1040bb690> to path /_matrix/client/api/v1
2017-03-15 01:06:47,996 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource instance at 0x103e9f128> to path /_matrix/content
2017-03-15 01:06:47,997 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.key.v2.KeyApiV2Resource instance at 0x103e9fe60> to path /_matrix/key/v2
2017-03-15 01:06:47,997 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x1040bb690> to path /_matrix/client/v2_alpha
2017-03-15 01:06:47,997 - synapse.util.httpresourcetree - 43 - INFO - - Attaching FilePath('/Users/trisimix/.synapse/lib/python2.7/site-packages/syweb/webclient') to path /_matrix/client
2017-03-15 01:06:47,998 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.key.v1.server_key_resource.LocalKey instance at 0x103e9fd40> to path /_matrix/key/v1
2017-03-15 01:06:47,998 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource instance at 0x103e9fa70> to path /_matrix/media/r0
2017-03-15 01:06:47,998 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x1040bb790> to path /_matrix/federation/v1
2017-03-15 01:06:48,001 - twisted - 131 - INFO - - SynapseSite (TLS) starting on 8448
2017-03-15 01:06:48,001 - twisted - 131 - INFO - - Starting factory <synapse.http.site.SynapseSite instance at 0x103ef97e8>
2017-03-15 01:06:48,002 - synapse.app.homeserver - 202 - INFO - - Synapse now listening on port 8448
2017-03-15 01:06:48,040 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x104117750> to path /_matrix/client/r0
2017-03-15 01:06:48,041 - synapse.util.httpresourcetree - 43 - INFO - - Attaching FilePath('/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/static') to path /_matrix/static
2017-03-15 01:06:48,041 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x104117750> to path /_matrix/client/versions
2017-03-15 01:06:48,042 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x104117750> to path /_matrix/client/unstable
2017-03-15 01:06:48,042 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource instance at 0x10411e170> to path /_matrix/media/v1
2017-03-15 01:06:48,042 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x104117750> to path /_matrix/client/api/v1
2017-03-15 01:06:48,043 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource instance at 0x10411e488> to path /_matrix/content
2017-03-15 01:06:48,044 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.key.v2.KeyApiV2Resource instance at 0x104109f80> to path /_matrix/key/v2
2017-03-15 01:06:48,044 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <twisted.web.resource.EncodingResourceWrapper object at 0x104117750> to path /_matrix/client/v2_alpha
2017-03-15 01:06:48,045 - synapse.util.httpresourcetree - 43 - INFO - - Attaching FilePath('/Users/trisimix/.synapse/lib/python2.7/site-packages/syweb/webclient') to path /_matrix/client
2017-03-15 01:06:48,045 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.key.v1.server_key_resource.LocalKey instance at 0x104109ea8> to path /_matrix/key/v1
2017-03-15 01:06:48,045 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource instance at 0x10411e170> to path /_matrix/media/r0
2017-03-15 01:06:48,046 - synapse.util.httpresourcetree - 43 - INFO - - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x104117850> to path /_matrix/federation/v1
2017-03-15 01:06:48,047 - twisted - 131 - ERROR - - Traceback (most recent call last):
2017-03-15 01:06:48,047 - twisted - 131 - ERROR - -   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
2017-03-15 01:06:48,048 - twisted - 131 - ERROR - -     "__main__", fname, loader, pkg_name)
2017-03-15 01:06:48,048 - twisted - 131 - ERROR - -   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
2017-03-15 01:06:48,048 - twisted - 131 - ERROR - -     exec code in run_globals
2017-03-15 01:06:48,049 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 491, in <module>
2017-03-15 01:06:48,049 - twisted - 131 - ERROR - -     main()
2017-03-15 01:06:48,050 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 486, in main
2017-03-15 01:06:48,051 - twisted - 131 - ERROR - -     hs = setup(sys.argv[1:])
2017-03-15 01:06:48,051 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 336, in setup
2017-03-15 01:06:48,052 - twisted - 131 - ERROR - -     hs.start_listening()
2017-03-15 01:06:48,052 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 209, in start_listening
2017-03-15 01:06:48,052 - twisted - 131 - ERROR - -     self._listener_http(config, listener)
2017-03-15 01:06:48,053 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 200, in _listener_http
2017-03-15 01:06:48,053 - twisted - 131 - ERROR - -     interface=address
2017-03-15 01:06:48,054 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 478, in listenTCP
2017-03-15 01:06:48,054 - twisted - 131 - ERROR - -     p.startListening()
2017-03-15 01:06:48,055 - twisted - 131 - ERROR - -   File "/Users/trisimix/.synapse/lib/python2.7/site-packages/twisted/internet/tcp.py", line 983, in startListening
2017-03-15 01:06:48,056 - twisted - 131 - ERROR - -     raise CannotListenError(self.interface, self.port, le)
2017-03-15 01:06:48,057 - twisted - 131 - ERROR - - twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:8008: [Errno 48] Address already in use.
error starting (exit code: 1); see above for logs
(.synapse) trisimix:.synapse trisimix$ 

```

**Comment by richvdh** [comment]
this is not a support forum
