### ISSUE TITLE
synapse returns 500 error on HEAD requests

### ISSUE THREAD

**Issue by majewsky** [matrix-org/synapse#2029]
I set up Synapse **0.19.2** on my server ([here's the configuration that I use](https://github.com/majewsky/system-configuration/blob/92ade06411497848c3c5b94f29628ae57428386c/hologram-bethselamin-synapse.pkg.toml)). Once I got it to start, the first check that I did was:

```
$ curl https://bethselamin.de/_matrix      

<html>
  <head><title>405 - Method Not Allowed</title></head>
  <body>
    <h1>Method Not Allowed</h1>
    <p>Your browser approached me (at /_matrix) with the method "GET".  I only allow the method HEAD here.</p>
  </body>
</html>
```

So I did:

```
$ curl --head https://bethselamin.de/_matrix
HTTP/1.1 500 Internal Server Error
...
```

And there's a stacktrace in the systemd journal:
```
Mär 18 21:46:04 bethselamin synapse[28239]: twisted: [] Unhandled Error
                                             Traceback (most recent call last):
                                               File "/usr/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
                                                 why = self.lineReceived(line)
                                               File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1752, in lineReceived
                                                 self.allContentReceived()
                                               File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 1845, in allContentReceived
                                                 req.requestReceived(command, path, version)
                                               File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 766, in requestReceived
                                                 self.process()
                                             --- <exception caught here> ---
                                               File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 190, in process
                                                 self.render(resrc)
                                               File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
                                                 body = resrc.render(self)
                                               File "/usr/lib/python2.7/site-packages/twisted/web/resource.py", line 250, in render
                                                 return m(request)
                                               File "/usr/lib/python2.7/site-packages/twisted/web/resource.py", line 260, in render_HEAD
                                                 return self.render_GET(request)
                                             exceptions.AttributeError: Resource instance has no attribute 'render_GET'
```

**Comment by daltonfury42** [comment]
I am not a developer, but https://bethselamin.de/_matrix/client/# worked in my case.

**Comment by jhdulaney** [comment]
Beuler

**Comment by ara4n** [comment]
a) it's bueller; b) this is a really superficial/cosmetic error and it really shouldn't be surprising that we prioritised it way below actually making synapse work reliably & performantly...
