### ISSUE TITLE
synapse claims to require a HEAD request on /_matrix

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#2043]
https://matrix.org/_matrix says:

```
Your browser approached me (at /_matrix) with the method "GET".  I only allow the method HEAD here.
```

... which is a lie. (HEAD gives a 500, per #2029 )

**Comment by jhdulaney** [comment]
Beuler

**Comment by jhdulaney** [comment]
2018-03-22 22:58:30,412 - synapse.storage.TIME - 213 - INFO - - Total database time: 0.001% {_update_client_ips_batch(2): 0.001%, update_user_directory_stream_pos(0): 0.000%, update_cached_last_access_time(0): 0.000%} {}                                                               
2018-03-22 22:58:30,434 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived                                            
    why = self.lineReceived(line)
  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 1752, in lineReceived                                                  
    self.allContentReceived()
  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 1845, in allContentReceived                                            
    req.requestReceived(command, path, version)
  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 766, in requestReceived                                                
    self.process()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 190, in process                                                      
    self.render(resrc)
  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 241, in render                                                       
    body = resrc.render(self)
  File "/usr/lib64/python2.7/site-packages/twisted/web/resource.py", line 250, in render                                                     
    return m(request)
  File "/usr/lib64/python2.7/site-packages/twisted/web/resource.py", line 260, in render_HEAD                                                
    return self.render_GET(request)
exceptions.AttributeError: Resource instance has no attribute 'render_GET'
