### ISSUE TITLE
user registration refused - synapse server

### ISSUE THREAD

**Issue by k-sathireddy** [matrix-org/synapse#2051]
i used the following commands:

$ synctl start

$ register_new_matrix_user -c homeserver.yaml https://localhost:8448
New user localpart [company]: user1
Password: 
Confirm password: 
Make admin [no]: no

error:

Sending registration request...
Traceback (most recent call last):
  File "/Users/company/.synapse/bin/register_new_matrix_user", line 174, in <module>
    register_new_user(args.user, args.password, args.server_url, secret, args.admin)
  File "/Users/company/.synapse/bin/register_new_matrix_user", line 117, in register_new_user
    request_registration(user, password, server_location, shared_secret, bool(admin))
  File "/Users/company/.synapse/bin/register_new_matrix_user", line 63, in request_registration
    f = urllib2.urlopen(req, context=ssl.SSLContext(ssl.PROTOCOL_SSLv23))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>

**Comment by richvdh** [comment]
sounds like your homeserver server wasn't running (check the logs). Or you'd configured it not to listen on  https://localhost:8448

**Comment by Sifungurux** [comment]
Try to take a look at the syslog or message log. And see if you get an error saying the DB is read-only. I stumble onto this a few times. A fix may be to chmod the DB and redo the cmd
