### ISSUE TITLE
Sporadic metrics error

### ISSUE THREAD

**Issue by VShell** [matrix-org/synapse#2092]
```
2017-04-01 10:39:41,105 - synapse.metrics - 107 - ERROR - - Failed to render metric
Traceback (most recent call last):
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 104, in render_all
    strs += metric.render()
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/metrics/metric.py", line 147, in render
    size = self.size_callback()
  File "/home/synapse/.synapse/local/lib/python2.7/site-packages/synapse/util/caches/__init__.py", line 38, in <lambda>
    lambda: len(cache),
ValueError: __len__() should return >= 0
```

This appears to happen a few times in a row, then stop happening.

**Comment by enckse** [comment]
we're getting these, I assume after we enabled metrics for #2114

**Comment by logic** [comment]
Seeing this regularly here as well, figured I'd mention it:

```
Dec 18 01:56:16 matrix.sfo2.do.logic.net synapse[16929]: synapse.metrics: [] Failed to render metric                                                                                                                              
                                                         Traceback (most recent call last):                                                                                                                                       
                                                           File "/srv/matrix.logic.net/venv/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 104, in render_all                                                     
                                                             strs += metric.render()                                                                                                                                              
                                                           File "/srv/matrix.logic.net/venv/lib/python2.7/site-packages/synapse/metrics/metric.py", line 147, in render                                                           
                                                             size = self.size_callback()                         
                                                           File "/srv/matrix.logic.net/venv/lib/python2.7/site-packages/synapse/util/caches/__init__.py", line 35, in <lambda>                                                    
                                                             lambda: len(cache),                                 
                                                         ValueError: __len__() should return >= 0
```

A quick bit of debugging showed that the metric in question is named `synapse_util_caches_cache`, at least for my situation. I haven't dug any farther into it than that, though, since it isn't actually impacting anything other than making my error logs a little noisy.

**Comment by richvdh** [comment]
I guess not.
