### ISSUE TITLE
twisted error - unsupported operand type(s) for -: 'str' and 'int'

### ISSUE THREAD

**Issue by pokrface** [matrix-org/synapse#2194]
New install from the matrix Ubuntu Xenial repo.

On starting Synapse, I get this in my logs:

```
2017-05-05 11:24:36,393 - twisted - 131 - INFO - - SynapseSite starting on 8008
2017-05-05 11:24:36,393 - twisted - 131 - INFO - - Starting factory <synapse.http.site.SynapseSite instance at 0x7f080c7bd128>
2017-05-05 11:24:36,393 - synapse.app.homeserver - 203 - INFO - - Synapse now listening on port 8008
2017-05-05 11:24:36,393 - synapse.app.homeserver - 31 - INFO - - Set file limit to: 65536
2017-05-05 11:24:36,394 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 417, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 317, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallbacks
    self._runCallbacks()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 430, in _continueFiring
    callable(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 238, in _start
    return self.start()
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 249, in start
    self.threadpool.start()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 153, in start
    self.adjustPoolsize()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 306, in adjustPoolsize
    self._team.grow(self.min - self.workers)
exceptions.TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Synapse appears to otherwise start normally—i see it running and it appears to be working.

Is this Twisted error significant, or is it just informational?

**Comment by richvdh** [comment]
presumably a config issue
