### ISSUE TITLE
131 - CRITICAL and synapse.http.server - 139 - ERROR

### ISSUE THREAD

**Issue by hamber-dick** [matrix-org/synapse#2197]
I got an error in my Synapse homeserver and have no idea were this camte from. Since 2 Days I'm not able to login to my homeserver via riot clients. And have much Errors and Criticals in my homserver.log. For me it seems the Database is broken, and the sync over federation is not possible anymore.
```
2017-05-06 20:05:46,651 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-05-06 20:05:46,652 - twisted - 131 - CRITICAL - -
Traceback (most recent call last):
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/presence.py", line 170, in get_presence_for_users
    desc="get_presence_for_users",
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 684, in _simple_select_many_batch
    table, column, chunk, keyvalues, retcols
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 319, in runInteraction
    inner_func, *args, **kwargs
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/root/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 313, in inner_func
    func, *args, **kwargs
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 242, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 729, in _simple_select_many_txn
    return cls.cursor_to_dict(txn)
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 363, in cursor_to_dict
    dict(zip(col_headers, row)) for row in cursor
  File "/root/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 363, in <genexpr>
    dict(zip(col_headers, row)) for row in cursor
DatabaseError: database disk image is malformed
``` 

`:~/.synapse# tail -f homeserver.log|grep ERROR
2017-05-06 21:01:18,148 - synapse.http.server - 139 - ERROR - GET-2249- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f802f5365d0>: <XForwardedForRequest at 0x7f802dbdfd88 method=GET uri=/_matrix/client/r0/sync?filter=7&timeout=0&_cacheBuster=1494097271993&access_token=<redacted> clientproto=HTTP/1.0 site=8008>:`

Has anybody an Idea what could be the Problem? At the moment it is not possible to use my homeserver for anything :-(

[edited by @richvdh: please use \``` for logs to make them readable]

**Comment by ara4n** [comment]
I've seen this too on my personal HS; somewhat worrying that it seems to be biting a lot of people.

To fix, turn off synapse, and:

echo .dump | sqlite homeserver.db > homeserver.sql
mv homeserver.db homeserver.db.old
sqlite homeserver.db < homeserver.sql

and then turn on synapse again. i recommend upgrading to postgres afterwards.

it will take a while to run, so you may want to run it in a `screen`

-- 
Matthew Hodgson
Matrix.org

**Comment by hamber-dick** [comment]
Thx for fast answer, this solved it for the Moment. 

But after I restart the synapse HS. It crasched several times and stoped working, so that I have to kill it with kill -9 and restart it. The only way to run the server without crashing was to leave all Big-fedarated rooms. I think there musst be a possibillity to resync the rooms whthout crashing the whole server.

**Comment by ara4n** [comment]
What spec is the server?

-- 
Matthew Hodgson
Matrix.org

**Comment by hamber-dick** [comment]
The synapse runs with the Default homserver.yaml Settings. And I start the synapse with SYNAPSE_CACHE_FACTOR between 0.01 and 0.09.

The vserver Specs are:
CPU vCores 	2 vCores 	
RAM garanty 	2 GB 	
Maxx-RAM 	4 GB 	
HP 3PAR Disk-Memory 	300 GB SSD/HDD

I heard a lot of people are using a raspberry-Pi as Hs, so I thought the system should be fast enough.

**Comment by MacLemon** [comment]
Sounds like a similar problem to #2395. I did try dumping and recreating the sqlite database as suggested. Problem of lockups still persists, I also have to `kill -9` synapse to being able to start it again.

**Comment by richvdh** [comment]
sounds like the original problem was sqlite corruption and is now fixed; sadly we're not going to be able to do anything about that.

**Comment by skylord123** [comment]
I've received this issue twice this month. First when I upgraded near the beginning of this month and again when I just upgraded today to `v0.33.3`. My server has randomly rebooted a couple times without this happening. It only happens on upgrades. Anyone else having this issue?
