### ISSUE TITLE
Meaning of: Failed to handle edu 'm.device_list_update'?

### ISSUE THREAD

**Issue by enckse** [matrix-org/synapse#2210]
These seem to be a fairly regular occurrence in our sys logs, is this indicative of a problem or something else?

```
May 08 03:53:29 synapse synapse[30878]: synapse.federation.federation_server: [PUT-37046] Failed to handle edu 'm.device_list_update'
                                        Traceback (most recent call last):
                                          File "/usr/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 211, in received_edu
                                            yield self.edu_handlers[edu_type](origin, content)
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/usr/lib/python2.7/site-packages/synapse/handlers/device.py", line 415, in incoming_device_list_update
                                            yield self._handle_device_updates(user_id)
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/usr/lib/python2.7/site-packages/synapse/util/metrics.py", line 58, in measured_func
                                            r = yield func(self, *args, **kwargs)
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/usr/lib/python2.7/site-packages/synapse/handlers/device.py", line 433, in _handle_device_updates
                                            result = yield self.federation.query_user_devices(origin, user_id)
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/usr/lib/python2.7/site-packages/synapse/federation/transport/client.py", line 376, in query_user_devices
                                            timeout=timeout,
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/usr/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 444, in get_json
                                            ignore_backoff=ignore_backoff,
                                          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
                                            result = g.send(result)
                                          File "/usr/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 248, in _request
                                            response.code, response.phrase, body
                                        HttpResponseException: 401: Unauthorized
May 08 04:02:41 synapse synapse[30878]: synapse.federation.federation_server: [PUT-38331] Failed to handle edu 'm.device_list_update'
                                        Traceback (most recent call last):
                                          File "/usr/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 211, in received_edu
                                            yield self.edu_handlers[edu_type](origin, content)
                                        ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

**Comment by richvdh** [comment]
is this still a problem?

**Comment by Sharparam** [comment]
@richvdh Yes, I see these popping up in my logs as well.

```
2019-03-18 16:58:41,449 - synapse.federation.federation_server - 857 - ERROR - PUT-33- Failed to handle edu 'm.device_list_update'
Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 853, in on_edu
    yield handler(origin, content)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/handlers/device.py", line 489, in incoming_device_list_update
    yield self._handle_device_updates(user_id)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/util/metrics.py", line 63, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/handlers/device.py", line 559, in _handle_device_updates
    user_id, devices, stream_id,
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 408, in runInteraction
    *args, **kwargs
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 457, in runWithConnection
    inner_func, *args, **kwargs
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 453, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 329, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/devices.py", line 405, in _update_remote_device_list_cache_txn
    lock=False,
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 672, in _simple_upsert_txn
    insertion_values=insertion_values,
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 783, in _simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 119, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 149, in _do_execute
    sql, *args
psycopg2.ProgrammingError: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

I've seen various other similar errors about invalid `ON CONFLICT` statements. It seems that some tables in the schema are missing proper `UNIQUE` while the code using `ON CONFLICT` expects such unique indices to exist.

See also: https://github.com/matrix-org/synapse/issues/4628#issuecomment-473119656

**Comment by richvdh** [comment]
the `no unique or exclusion constraint` error  is a separate problem; see #4877.

It looks like the OP's problem was that his server received an `m.device_list_update` EDU from a server which then did not accept the `/_matrix/federation/v1//user/devices/{userId}` request. That sounds specific to a particular environment, so I am going to close it.
