### ISSUE TITLE
"CRITICAL" errors when attempting to get history for a room amidst federation issues

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2289]
At the time of writing this, matrix.org is having some federation difficulties. A new user to tang.ents.ca joined matrix HQ and sent tang.ents.ca into a slow spiral.

The error snippet below occurred *after* the server appeared to have been able to get information from matrix.org, however the error appears to have caused synapse to go get history from other sources, repeating the error every once and a while.

**Synapse version**: 0.21.1

*All log times are MDT (GMT-6)*

Here's a snippet of the log:
```
2017-06-18 03:43:39,814 - twisted - 131 - CRITICAL - GET-375311- Unhandled error in Deferred:
2017-06-18 03:43:39,815 - twisted - 131 - CRITICAL - GET-375311- 
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 1861, in do_auth
    self.auth.check(event, auth_events=auth_events)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/api/auth.py", line 77, in check
    event_auth.check(event, auth_events, do_sig_check=do_sig_check)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/event_auth.py", line 91, in check
    "Room %r does not exist" % (event.room_id,)
SynapseError: 403: Room '!cURbafjkfsMDVwdRDQ:matrix.org' does not exist
2017-06-18 03:43:39,821 - synapse.handlers.federation - 767 - ERROR - GET-375311- Failed to backfill from matrix.org because FirstError[#123, [Failure instance: Traceback: <class 'synapse.api.errors.SynapseError'>: 403: Room '!cURbafjkfsMDVwdRDQ:matrix.org' does not exist
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1532:unwindGenerator
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1386:_inlineCallbacks
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py:1575:_prep_event
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1532:unwindGenerator
--- <exception caught here> ---
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1386:_inlineCallbacks
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py:1861:do_auth
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/api/auth.py:77:check
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/event_auth.py:91:check
]]
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py", line 740, in try_backfill
    extremities=[e for e in extremities.keys()]
FirstError: FirstError[#123, [Failure instance: Traceback: <class 'synapse.api.errors.SynapseError'>: 403: Room '!cURbafjkfsMDVwdRDQ:matrix.org' does not exist
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1532:unwindGenerator
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1386:_inlineCallbacks
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py:1575:_prep_event
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1532:unwindGenerator
--- <exception caught here> ---
/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1386:_inlineCallbacks
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/federation.py:1861:do_auth
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/api/auth.py:77:check
/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/event_auth.py:91:check
]]
```

For full logs, including everything related to `GET-375311`, please contact me (`@travis:t2l.io`). They're too large to post here and contain too much potentially sensitive information.

**Comment by turt2live** [comment]
Note: The user who joined, and users who followed, were able to participate in matrix HQ (ignoring the obvious federation issues with matrix.org).

**Comment by turt2live** [comment]
Even more information: The synapse server suffered an out of member error after the join was initiated and after the above error was encountered.

**Comment by turt2live** [comment]
I'm closing this as I no longer have the logs available, and it was likely complaining because federation was broken. If it comes up again, I'd encourage people to store their logs ;)
