### ISSUE TITLE
Receiving a 429 is considered 'unknown' and ends up filling the logs

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2322]
Logs below. This is from t2bot.io after issuing ~200,000 (possibly more) web requests in the span of ~5 minutes (sorry).

This is a minor issue, but it seems like receiving a 429 should very much be a handled case and not print 2 stack traces to the logs.

```
2017-06-30 07:25:16,235 - synapse.access.http.8008 - 59 - INFO - GET-11730508- 138.197.141.99 - 8008 - Received request: GET /_matrix/client/r0/profile/@freenode_REDACTED:matrix.org?access_token=<redacted>
2017-06-30 07:25:22,783 - synapse.http.outbound - 154 - INFO - GET-11730508- {GET-O-29413219} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/profile?field=displayname&user_id=%40freenode_REDACTED%3Amatrix.org
2017-06-30 07:25:23,469 - synapse.http.outbound - 239 - INFO - GET-11730508- {GET-O-29413219} [matrix.org] Result: 200 OK
2017-06-30 07:25:28,706 - synapse.http.outbound - 154 - INFO - GET-11730508- {GET-O-29413445} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/profile?field=avatar_url&user_id=%40freenode_REDACTED%3Amatrix.org
2017-06-30 07:25:29,044 - synapse.http.outbound - 239 - INFO - GET-11730508- {GET-O-29413445} [matrix.org] Result: 429 Unknown Status
2017-06-30 07:25:29,045 - synapse.handlers.profile - 108 - ERROR - GET-11730508- Failed to get avatar_url
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/handlers/profile.py", line 104, in get_avatar_url
    ignore_backoff=True,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/federation/transport/client.py", line 188, in make_query
    ignore_backoff=ignore_backoff,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 451, in get_json
    ignore_backoff=ignore_backoff,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 250, in _request
    response.code, response.phrase, body
HttpResponseException: 429: Unknown Status
2017-06-30 07:25:29,045 - synapse.http.server - 126 - ERROR - GET-11730508- 429: Unknown Status
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/profile.py", line 124, in on_GET
    user,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/handlers/profile.py", line 104, in get_avatar_url
    ignore_backoff=True,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/federation/transport/client.py", line 188, in make_query
    ignore_backoff=ignore_backoff,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 451, in get_json
    ignore_backoff=ignore_backoff,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 250, in _request
    response.code, response.phrase, body
HttpResponseException: 429: Unknown Status
2017-06-30 07:25:29,046 - synapse.access.http.8008 - 91 - INFO - GET-11730508- 138.197.141.99 - 8008 - {None} Processed request: 12811ms (3ms, 0ms) (0ms/0) 48B 429 "GET /_matrix/client/r0/profile/@freenode_REDACTED:matrix.org?access_token=<redacted> HTTP/1.0" "None"
```

**Comment by ShadowJonathan** [comment]
This seems to be fixed?

https://github.com/matrix-org/synapse/blob/9d1e4942ab728ebfe09ff9a63c66708ceaaf7591/synapse/federation/sender/transaction_manager.py#L143-L147
