### ISSUE TITLE
Receipts processing error after upgrading to 0.22.0 and inability to federate properly

### ISSUE THREAD

**Issue by pztrn** [matrix-org/synapse#2341]
After updating to 0.22.0 I have this backtrace flooded all over synapse's log:

```
2017-07-06 18:34:55,961 - synapse.federation.federation_server - 215 - ERROR - PUT-816- Failed to handle edu 'm.receipt'
Traceback (most recent call last):
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/synapse/federation/federation_server.py", line 211, in received_edu
    yield self.edu_handlers[edu_type](origin, content)
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/synapse/handlers/receipts.py", line 81, in _received_remote_receipt
    yield self._handle_new_receipts(receipts)
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1260, in _inlineCallbacks
    result = g.send(result)
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/synapse/handlers/receipts.py", line 123, in _handle_new_receipts
    self.hs.get_pusherpool().on_new_receipts(
  File "/data/programs/matrix/synapse/lib/python2.7/site-packages/synapse/server.py", line 339, in _get
    depname,
ValueError: Cyclic dependency while building pusherpool
```

Also, after updating I'm unable to federate properly, e.g. I can receive messages fine (but with big delay acually), but cannot send them - they're always grey in Riot.

**Comment by richvdh** [comment]
I'm guessing this is no longer relevant.
