### ISSUE TITLE
Postgres migration error

### ISSUE THREAD

**Issue by igbjnI05bF** [matrix-org/synapse#2346]
`(.synapse) synapseuser@synapse:~/.synapse$ synapse_port_db --sqlite-database homeserver.db.snapshot --postgres-config homeserver-postgres.yaml
2017-07-08 13:21:07,671 - synapse.metrics - 162 - INFO - Collecting gc 1
2017-07-08 13:21:07,682 - synapse.metrics - 162 - INFO - Collecting gc 0
Preparing SQLite3...
Preparing PostgreSQL...
Fetching tables...
Creating tables...
2017-07-08 13:21:07,709 - synapse_port_db - 459 - INFO - Found 110 tables
2017-07-08 13:21:07,710 - synapse_port_db - 489 - INFO - Failed to create port table: column "rowid" does not exist

2017-07-08 13:21:07,711 - synapse_port_db - 496 - INFO - Failed to create port table: relation "port_from_sqlite3" already exists

Setting up...
2017-07-08 13:21:07,715 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,803 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,832 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,856 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,907 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,934 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:07,962 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,010 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,021 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,032 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,056 - synapse.metrics - 162 - INFO - Collecting gc 1
2017-07-08 13:21:08,079 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,166 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,179 - synapse.metrics - 162 - INFO - Collecting gc 0
history_visibility: 100% (65/65)
local_media_repository_thumbnails: 100% (345/345)
2017-07-08 13:21:08,194 - synapse.metrics - 162 - INFO - Collecting gc 0
2017-07-08 13:21:08,213 - synapse_port_db - 163 - ERROR - Failed to insert: user_directory_search
Traceback (most recent call last):
  File "/home/synapseuser/.synapse/bin/synapse_port_db", line 159, in insert_many_txn
    txn.executemany(sql, rows)
  File "/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 87, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 114, in _do_execute
    sql, *args
ProgrammingError: column "value" of relation "user_directory_search" does not exist
LINE 1: INSERT INTO user_directory_search (user_id, value) VALUES ('...
                                                    ^

2017-07-08 13:21:08,219 - synapse.metrics - 162 - INFO - Collecting gc 0
user_directory_stream_pos: 100% (1/1)
push_rules: 100% (5/5)
room_tags: 100% (14/14)
e2e_device_keys_json: 100% (8/8)
2017-07-08 13:21:08,224 - synapse_port_db - 524 - ERROR - 
Traceback (most recent call last):
  File "/home/synapseuser/.synapse/bin/synapse_port_db", line 517, in run
    consumeErrors=True,
FirstError: FirstError[#12, [Failure instance: Traceback: <class 'psycopg2.ProgrammingError'>: column "value" of relation "user_directory_search" does not exist
LINE 1: INSERT INTO user_directory_search (user_id, value) VALUES ('...
                                                    ^

/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:500:errback
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:567:_startRunCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:653:_runCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1442:gotResult
--- <exception caught here> ---
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1384:_inlineCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py:393:throwExceptionIntoGenerator
/home/synapseuser/.synapse/bin/synapse_port_db:319:handle_table
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:307:_runWithConnection
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:298:_runWithConnection
/home/synapseuser/.synapse/bin/synapse_port_db:126:r
/home/synapseuser/.synapse/bin/synapse_port_db:306:insert
/home/synapseuser/.synapse/bin/synapse_port_db:159:insert_many_txn
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py:87:executemany
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py:114:_do_execute
]]
2017-07-08 13:21:08,469 - synapse.metrics - 162 - INFO - Collecting gc 0
Traceback (most recent call last):
  File "/home/synapseuser/.synapse/bin/synapse_port_db", line 517, in run
    consumeErrors=True,
FirstError: FirstError[#12, [Failure instance: Traceback: <class 'psycopg2.ProgrammingError'>: column "value" of relation "user_directory_search" does not exist
LINE 1: INSERT INTO user_directory_search (user_id, value) VALUES ('...
                                                    ^

/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:500:errback
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:567:_startRunCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:653:_runCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1442:gotResult
--- <exception caught here> ---
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py:1384:_inlineCallbacks
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py:393:throwExceptionIntoGenerator
/home/synapseuser/.synapse/bin/synapse_port_db:319:handle_table
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:307:_runWithConnection
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py:298:_runWithConnection
/home/synapseuser/.synapse/bin/synapse_port_db:126:r
/home/synapseuser/.synapse/bin/synapse_port_db:306:insert
/home/synapseuser/.synapse/bin/synapse_port_db:159:insert_many_txn
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py:87:executemany
/home/synapseuser/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py:114:_do_execute
]]
`

Any help is appreciated, thanks!

**Comment by richvdh** [comment]
dup #2287
