### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters after login in Matrix synapse logs

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#2356]
After each login (successful or with bad password) - I see those error in logs:
- on successful login:
```
2017-07-11 09:50:10,674 - synapse.access.http.8008 - 59 - INFO - POST-8- 127.0.0.1 - 8008 - Received request: POST /_matrix/client/r0/login?
2017-07-11 09:50:10,841 - twisted - 131 - ERROR - POST-8- Traceback (most recent call last):
2017-07-11 09:50:10,841 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
2017-07-11 09:50:10,841 - twisted - 131 - ERROR - POST-8-     if self.shouldRollover(record):
2017-07-11 09:50:10,842 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
2017-07-11 09:50:10,842 - twisted - 131 - ERROR - POST-8-     msg = "%s\n" % self.format(record)
2017-07-11 09:50:10,843 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-07-11 09:50:10,843 - twisted - 131 - ERROR - POST-8-     return fmt.format(record)
2017-07-11 09:50:10,843 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
2017-07-11 09:50:10,844 - twisted - 131 - ERROR - POST-8-     record.message = record.getMessage()
2017-07-11 09:50:10,844 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
2017-07-11 09:50:10,845 - twisted - 131 - ERROR - POST-8-     msg = msg % self.args
2017-07-11 09:50:10,845 - twisted - 131 - ERROR - POST-8-   File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 308, in __str__
2017-07-11 09:50:10,846 - twisted - 131 - ERROR - POST-8-     'user: ' + str(self.user),
2017-07-11 09:50:10,846 - twisted - 131 - ERROR - POST-8- UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-9: ordinal not in range(128)
2017-07-11 09:50:10,846 - twisted - 131 - ERROR - POST-8- Logged from file ldap_auth_provider.py, line 134
2017-07-11 09:50:10,852 - synapse.handlers.sync - 517 - INFO - GET-7- Calculating sync response for DomainSpecificString(localpart=u'korepov', domain=u'homeserver.ru')
2017-07-11 09:50:10,854 - synapse.access.http.8008 - 91 - INFO - GET-7- 127.0.0.1 - 8008 - {@korepov:homeserver.ru} Processed request: 26826ms (0ms, 0ms) (0ms/0) 194B 200 "GET /_matrix/client/r0/sync?filter=7&timeout=30000&since=s249_9533_0_41_97_1_22_56&access_token=<redacted> HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/0.11.4 Chrome/56.0.2924.87 Electron/1.6.8 Safari/537.36"
2017-07-11 09:50:10,855 - synapse.handlers.device - 259 - INFO - POST-8- Sending device list update notif to: set(['matrix.org'])
2017-07-11 09:50:10,856 - synapse.handlers.auth - 442 - INFO - POST-8- Logging in user @korepov:homeserver.ru on device XXXXX
```

- on failed login:
```
2017-07-11 09:49:33,635 - synapse.handlers.presence - 327 - INFO - - Handling presence timeouts
2017-07-11 09:49:33,636 - synapse.handlers.typing - 78 - INFO - - Checking for typing timeouts
2017-07-11 09:49:36,564 - synapse.access.http.8008 - 59 - INFO - POST-5- 127.0.0.1 - 8008 - Received request: POST /_matrix/client/r0/login?
2017-07-11 09:49:36,697 - synapse.metrics - 162 - INFO - POST-5- Collecting gc 0
2017-07-11 09:49:36,946 - twisted - 131 - ERROR - POST-5- Traceback (most recent call last):
2017-07-11 09:49:36,947 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
2017-07-11 09:49:36,948 - twisted - 131 - ERROR - POST-5-     if self.shouldRollover(record):
2017-07-11 09:49:36,948 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
2017-07-11 09:49:36,949 - twisted - 131 - ERROR - POST-5-     msg = "%s\n" % self.format(record)
2017-07-11 09:49:36,949 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2017-07-11 09:49:36,950 - twisted - 131 - ERROR - POST-5-     return fmt.format(record)
2017-07-11 09:49:36,951 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
2017-07-11 09:49:36,951 - twisted - 131 - ERROR - POST-5-     record.message = record.getMessage()
2017-07-11 09:49:36,952 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
2017-07-11 09:49:36,952 - twisted - 131 - ERROR - POST-5-     msg = msg % self.args
2017-07-11 09:49:36,953 - twisted - 131 - ERROR - POST-5-   File "/usr/lib/python2.7/dist-packages/ldap3/core/connection.py", line 308, in __str__
2017-07-11 09:49:36,953 - twisted - 131 - ERROR - POST-5-     'user: ' + str(self.user),
2017-07-11 09:49:36,954 - twisted - 131 - ERROR - POST-5- UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-6: ordinal not in range(128)
2017-07-11 09:49:36,955 - twisted - 131 - ERROR - POST-5- Logged from file ldap_auth_provider.py, line 134
2017-07-11 09:49:36,956 - synapse.handlers.auth - 488 - WARNING - POST-5- Attempted to login as @korepov2:homeserver.ru but they do not exist
2017-07-11 09:49:36,969 - synapse.http.server - 123 - INFO - POST-5- <SynapseRequest at 0x7f9ff11ba7a0 method=POST uri=/_matrix/client/r0/login? clientproto=HTTP/1.0 site=8008> SynapseError: 400 - Missing JSON keys.
2017-07-11 09:49:36,970 - synapse.access.http.8008 - 91 - INFO - POST-5- 127.0.0.1 - 8008 - {None} Processed request: 406ms (16ms, 0ms) (0ms/1) 67B 400 "POST /_matrix/client/r0/login? HTTP/1.0" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

What does this error mean and how to fix it?

**Comment by MurzNN** [comment]
Same bug report I have found at #1814 but in that issue there are another file with this error, but fix maybe the same.

**Comment by jkolo** [comment]
This is bug in ldap3 https://github.com/cannatag/ldap3/issues/434

**Comment by hawkowl** [comment]
This should be fixed upstream in ldap3.
