### ISSUE TITLE
Twisted AlreadyCalled error spamming the log since update

### ISSUE THREAD

**Issue by Linuxine** [matrix-org/synapse#2387]
I have just updated my self hosted homeserver from 0.20.0 to 0.22.1. I have proceed as described in https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst, but maybe I have done something wrong. During the update, I had several Riot client connected, I don't know if this is related, but since, my homeserver.log keeps increasing, being spammed several times by second by the following error 

`
2017-07-26 16:29:42,216 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "~/synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 461, in in_thread
    reactor.run()
  File "~/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1247, in run
    self.mainLoop()
  File "~/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1256, in mainLoop
    self.runUntilCurrent()
  File "~/synapse/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 151, in f
    ret = func(*args, **kwargs)
--- <exception caught here> ---
  File "~/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 882, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "~/synapse/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
    protocol.connectionLost(reason)
  File "~/synapse/lib/python2.7/site-packages/twisted/protocols/tls.py", line 403, in connectionLost
    ProtocolWrapper.connectionLost(self, reason)
  File "~/synapse/lib/python2.7/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "~/synapse/lib/python2.7/site-packages/twisted/web/http.py", line 2190, in connectionLost
    self._abortingCall.cancel()
  File "~/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 101, in cancel
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
`

The log file size is really increasing, so I would like to get rid of this error. Everything seems to work fine, so I don't understand what the issue is... Any help would be really welcomed !

**Comment by fekle** [comment]
I'm experiencing the same issue - everything works fine, but the logs are a bit annoying.

Log excerpt:
```
2017-07-27 14:32:24,847 - twisted - 131 - CRITICAL - - Unhandled Error
 Traceback (most recent call last):
   File "/synapse/synapse/app/homeserver.py", line 461, in in_thread
     reactor.run()
   File "/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
     self.mainLoop()
   File "/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
     self.runUntilCurrent()
   File "synapse/metrics/__init__.py", line 151, in f
     ret = func(*args, **kwargs)
 --- <exception caught here> ---
   File "/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
     call.func(*call.args, **call.kw)
   File "/synapse/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
     protocol.connectionLost(reason)
   File "/synapse/lib/python2.7/site-packages/twisted/protocols/tls.py", line 403, in connectionLost
     ProtocolWrapper.connectionLost(self, reason)
   File "/synapse/lib/python2.7/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
     self.wrappedProtocol.connectionLost(reason)
   File "/synapse/lib/python2.7/site-packages/twisted/web/http.py", line 2190, in connectionLost
     self._abortingCall.cancel()
   File "/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 99, in cancel
     raise error.AlreadyCalled
 twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
```

I'm using Synapse 0.22.1 running in a docker container.

**Comment by henryjuan** [comment]
I am experiencing the same issue on Synapse/0.23.1

**Comment by LouisKottmann** [comment]
I am experiencing the same issue on Synapse 0.22.1

**Comment by ara4n** [comment]
Apparently this happens if the synapse is making an outbound connection which doesn't terminate cleanly.  Is it possible that your network or docker environments are silently discarding outbound HTTP connections after N seconds?

**Comment by richvdh** [comment]
I'm assuming this has been fixed ad some point in the last two years.
