### ISSUE TITLE
Cannot run a federation_reader worker

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2436]
### Description

Here's a sample request. Every single request that comes in outputs the same error:
```
2017-09-02 04:46:59,013 - synapse.access.http.8449 - 59 - INFO - PUT-0- 91.194.60.121 - 8449 - Received request: PUT /_matrix/federation/v1/send/1503534893405/
2017-09-02 04:46:59,015 - synapse.metrics - 162 - INFO - PUT-0- Collecting gc 0
2017-09-02 04:46:59,023 - synapse.federation.transport.server - 140 - INFO - PUT-0- Request from jaccu.se
2017-09-02 04:46:59,025 - synapse.federation.transport.server - 253 - INFO - PUT-0- Received txn 1503534893405 from jaccu.se. (PDUs: 0, EDUs: 1, failures: 0)
2017-09-02 04:46:59,025 - synapse.federation.transport.server - 276 - ERROR - PUT-0- on_incoming_transaction failed
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/federation/transport/server.py", line 273, in on_PUT
    transaction_data
AttributeError: 'FederationReaderSlavedStore' object has no attribute 'get_received_txn_response'
2017-09-02 04:46:59,026 - synapse.http.server - 139 - ERROR - PUT-0- Failed handle request synapse.http.server._async_render on <synapse.federation.transport.server.TransportLayerServer object at 0x7f00b98ffc90>: <XForwardedForRequest at 0x7f00b98e52d8 method=PUT uri=/_matrix/federation/v1/send/1503534893405/ clientproto=HTTP/1.0 site=8449>
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
AttributeError: 'FederationReaderSlavedStore' object has no attribute 'get_received_txn_response'
2017-09-02 04:46:59,026 - synapse.access.http.8449 - 91 - INFO - PUT-0- 91.194.60.121 - 8449 - {jaccu.se} Processed request: 12ms (3ms, 0ms) (0ms/1) 55B 500 "PUT /_matrix/federation/v1/send/1503534893405/ HTTP/1.0" "Synapse/0.18.4"
```

Here's the worker configuration:
```
worker_app: synapse.app.federation_reader
worker_replication_host: 127.0.0.1
worker_replication_port: 9092
worker_replication_url: http://localhost:9091/_synapse/replication
worker_daemonize: true
worker_pid_file: /home/synapse/.synapse/federation_reader.pid
worker_log_config: /home/synapse/.synapse/federation_reader.log.config

worker_listeners:
  - port: 8449
    tls: true
    bind_address: '127.0.0.1'
    type: http
    x_forwarded: true
    resources:
      - names: [federation]
        compress: false
  - port: 8009
    tls: false
    bind_address: '127.0.0.1'
    type: http
    x_forwarded: true
    resources:
      - names: [federation]
        compress: false
```

The reverse proxy for 8448 is set up like this (nginx):
```
server {
        listen 8448 ssl;
        listen [::]:8448 ssl;
        server_name t2bot.io;
        ssl_certificate /home/synapse/.synapse/t2bot.io.tls.crt;
        ssl_certificate_key /home/synapse/.synapse/t2bot.io.tls.key;
        ssl_dhparam /home/synapse/.synapse/t2bot.io.tls.dh;

        location / {
                proxy_read_timeout 600;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_pass http://localhost:8449;
        }
}
```

Port 8008 (the federation APIs) is set up the same way, with the exception of the TLS/SSL parts.

### Version information

- **Homeserver**: t2bot.io
- **Version**:        0.22.1
- **Install method**: pip
- **Platform**:  Ubuntu 16.04, worker running on the same host as the main proc. Other workers are installed in containers on the host, and have no issues.

**Comment by krombel** [comment]
@turt2live Why do you reverse proxy to `http://localhost:8449` (`http` and not `https` although tls is enabled on that port). I think you might want to use port `8009` there :)

**Comment by turt2live** [comment]
Because in the logs I wanted the visibility of which port the requests are coming in on. In the end, both ports work and it doesn't matter that much.

**Comment by krombel** [comment]
I wanted to test the federation_reader as well and get now the same error.

**Comment by richvdh** [comment]
The federation_reader can only handle a subset of the calls which might land on the federation port - and `/_matrix/federation/v1/send` isn't one of them.

Here's the list of things it can support:

```
^/_matrix/federation/v1/event/                  federation_reader
^/_matrix/federation/v1/state/                  federation_reader
^/_matrix/federation/v1/state_ids/              federation_reader
^/_matrix/federation/v1/backfill/               federation_reader
^/_matrix/federation/v1/get_missing_events/     federation_reader
^/_matrix/federation/v1/publicRooms             federation_reader
```

You'll need to get your reverse-proxy to send everything else to the main synapse.

(You might ask why this isn't documented. PRs to the workers doc welcomed, I guess :/ )

**Comment by richvdh** [comment]
(You might also ask why the federation_reader 500s these requests rather than 404ing them)

**Comment by richvdh** [comment]
(see #2554 about documenting the workers)
