### ISSUE TITLE
I get this Synapse error when inputting new guest username with polish characters

### ISSUE THREAD

**Issue by lolownia** [matrix-org/synapse#2441]
### Description

I get this Synapse error when inputting new guest username with polish characters

### Steps to reproduce

- Do not be logged in to Riot-web. 
- Open link to the room 
- click join the room
- enter your nickname with polish characters (or any other utf-8): "mątwa" for example
- you  will see internal server error

Describe how what happens differs from what you expected.

I'd like a validation error (no non-latin characters allowed) or be able to have nickname with utf-8.

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

```
2017-09-06 15:08:42,901 - synapse.http.server - 139 - ERROR - GET-240003- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f3fb292dad0>: <SynapseRequest at 0x7f3f767f1998 method=GET uri=/_matrix/client/r0/register/available?username=a%C3%B3%C3%B3&access_token=<redacted> clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/rest/client/v2_alpha/register.py", line 152, in on_GET
    yield self.registration_handler.check_username(username)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/register.py", line 50, in check_username
    if urllib.quote(localpart.encode('utf-8')) != localpart:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

our hosted server: https://hs.naszademokracja.org for naszademokracja.org domain

If not matrix.org:
- **Version**:        What version of Synapse is running?  Synapse/0.22.1
 
- **Install method**: package manager/git clone/pip      
- **Platform**:       Tell us about the environment in which your homeserver is operating
                      - distro, hardware, if it's running in a vm/container, etc.

Docker image based on debian:jessie image

**Comment by richvdh** [comment]
I think we fixed this
