### ISSUE TITLE
(PostgreSQL 9.6) Cannot change display name or send messages from a homeserver identity user: 404 No Row Found

### ISSUE THREAD

**Issue by antonizoon** [matrix-org/synapse#2444]
### Description

In a Synapse server self hosted on CentOS 7 with python2.7 and PostgreSQL 9.6, I am running a some matrix channels which work fine in chat, encryption, etc. for all our matrix.org identified users. 

However, the main admin of the synapse server itself `myuser:matrix.example.com` _is unable to change their display name_ as it returns the following error. 

`404: No row found`

The commit used is 59de2c7.

```
2017-09-07 18:15:05,324 - synapse.util.async - 206 - INFO - PUT-914- Acquired linearizer lock 'rules_for_room' for key ()
2017-09-07 18:15:05,325 - synapse.util.async - 213 - INFO - PUT-914- Releasing linearizer lock 'rules_for_room' for key ()
2017-09-07 18:15:05,330 - synapse.state - 495 - INFO - PUT-914- Asking for 0 conflicted events
2017-09-07 18:15:05,330 - synapse.state - 506 - INFO - PUT-914- Asking for 0 auth events
2017-09-07 18:15:05,348 - synapse.handlers.user_directory - 131 - INFO - - Handling 1 state deltas
2017-09-07 18:15:05,351 - synapse.handlers.sync - 517 - INFO - GET-906- Calculating sync response for DomainSpecificString(localpart=u'myuser', domain=u'matrix.example.com')
2017-09-07 18:15:05,359 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-09-07 18:15:05,359 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 162, in notify_new_events
    last_token = yield self.store.get_federation_out_pos("events")
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 325, in runInteraction
    inner_func, *args, **kwargs
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 319, in inner_func
    func, *args, **kwargs
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 247, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 581, in _simple_select_one_onecol_txn
    raise StoreError(404, "No row found")
StoreError: 404: No row found
```

Synapse otherwise worked fine without such issues when it was using sqlite.

A possibly related issue is that the main admin or any matrix.example.org _users are unable to have their chats read by matrix.org users_, it is recorded in the matrix client chat history but not sent to the other matrix.org users.

```
2017-09-07 18:32:44,450 - synapse.federation.transport.server - 140 - INFO - PUT-1010- Request from matrix.org
2017-09-07 18:32:44,450 - synapse.federation.transport.server - 253 - INFO - PUT-1010- Received txn 1504523703358 from matrix.org. (PDUs: 1, EDUs: 0, failures: 0)
2017-09-07 18:32:44,452 - synapse.metrics - 162 - INFO - - Collecting gc 0
2017-09-07 18:32:44,461 - synapse.access.https.8448 - 91 - INFO - PUT-1010- 83.136.250.51 - 8448 - {matrix.org} Processed request: 15ms (0ms, 0ms) (3ms/2) 50B 200 "PUT /_matrix/federation/v1/send/1504523703358/ HTTP/1.1" "Synapse/0.22.1 (b=matrix-org-hotfixes,88185fe)"
2017-09-07 18:32:44,605 - synapse.access.https.8448 - 59 - INFO - PUT-1011- 83.136.250.51 - 8448 - Received request: PUT /_matrix/federation/v1/send/1504523703378/
2017-09-07 18:32:44,608 - synapse.federation.transport.server - 140 - INFO - PUT-1011- Request from matrix.org
2017-09-07 18:32:44,609 - synapse.federation.transport.server - 253 - INFO - PUT-1011- Received txn 1504523703378 from matrix.org. (PDUs: 1, EDUs: 0, failures: 0)
2017-09-07 18:32:44,622 - synapse.util.async - 206 - INFO - PUT-1011- Acquired linearizer lock 'rules_for_room' for key ()
2017-09-07 18:32:44,623 - synapse.util.async - 213 - INFO - PUT-1011- Releasing linearizer lock 'rules_for_room' for key ()
2017-09-07 18:32:44,645 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-09-07 18:32:44,646 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 162, in notify_new_events
    last_token = yield self.store.get_federation_out_pos("events")
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 325, in runInteraction
    inner_func, *args, **kwargs
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 319, in inner_func
    func, *args, **kwargs
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 247, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/synapse/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 581, in _simple_select_one_onecol_txn
    raise StoreError(404, "No row found")
```

I was able to send an email confirmation for the main admin though.

### Steps to reproduce

1. Install Synapse through pip in a virtualenv on it's own user in CentOS 7.
2. Set up the Synapse homeserver to use a PostgreSQL database.
3. Run the Synapse homeserver.
4. Create a main admin user for synapse, which will use the identity server of the homeserver.
5. Go to the matrix client of the homeserver at http://matrix.example.com:8448 and log in as the main admin user created.
6. Try to set the main admin user's display name.
  * display name fails to change, 404 No Row Found
7. Invite some matrix.org users and allow them to join.
8. Send a PM to the user or write a message on the homeserver hosted group.
  * Message is not seen, homeserver.log shows 404 No Row Found
9. Allow the matrix.org users to chat among themselves.
  * The matrix.example.org users can see these chats fine, but still cannot send messages.
10. Create a new nonadmin homeserver user, and have it join a matrix channel on the homeserver.
  * The user joins the matrix channel, but does not show up on the user log and while it can read all messages from matrix.org users, it cannot send any.
  * Surprisingly, _this non admin user can change their display name._

### Version information

* Homeserver: Personal hosted homeserver.
* Version: < Server: Synapse/0.22.1 (b=matrix-org-hotfixes,88185fe)
* Install Method: installed through python2 pip
* Platform: CentOS 7

The firewall has port 8448 open, and nginx proxy passing 8008 to port 443.

**Comment by richvdh** [comment]
Is this still an issue on recent synapse? Logs from a more recent version would be helpful if so

**Comment by antonizoon** [comment]
I'll try again soon with a newer version, hopefully it is all resolved.

**Comment by EorlBruder** [comment]
I am currently having this error minus the issues with changing display name. 
My messages aren't read by other homeservers, but I can read their messages. 

This error turns up in the logs: 
```
2018-08-10 08:08:31,819 - synapse.metrics - 255 - INFO - - Collecting gc 0
2018-08-10 08:08:31,820 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2018-08-10 08:08:31,821 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/user_directory.py", line 113, in notify_new_event
    yield self._unsafe_process()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/user_directory.py", line 137, in _unsafe_process
    self.pos = yield self.store.get_user_directory_stream_pos()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 318, in runInteraction
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 368, in runWithConnection
    inner_func, *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 364, in inner_func
    return func(conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 245, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 623, in _simple_select_one_onecol_txn
    raise StoreError(404, "No row found")
StoreError: 404: No row found
```

I had some db-corruption before this error appeared, so it may be connected with that. Is there any way of fixing this issue?
