### ISSUE TITLE
Somehow got a user in profiles table but not users

### ISSUE THREAD

**Issue by Ironlenny** [matrix-org/synapse#2535]
### Description

Trying to register a user with the username "foo" using the 'register_new_matrix_user' script results in a 500 error.

### Steps to reproduce

- run `register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml -u foo -p password -a`

This causes the server to report "Error! Receive 500 Internal Server Error". If I use 'fooo' instead of 'foo' it works fine.

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

```
017-10-11 22:06:04,420 - synapse.access.https.8448 - 59 - INFO - POST-12- 127.0.0.1 - 8448 - Received request: POST /_matrix/client/api/v1/register
2017-10-11 22:06:04,710 - synapse.metrics - 162 - INFO - - Collecting gc 0
2017-10-11 22:06:04,713 - synapse.http.server - 139 - ERROR - POST-12- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f5bb9db9710>: <S
ynapseRequest at 0x7f5bb98840e0 method=POST uri=/_matrix/client/api/v1/register clientproto=HTTP/1.1 site=8448>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 255, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/register.py", line 145, in on_POST
    session_info
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/register.py", line 364, in _do_shared_secret
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/register.py", line 145, in on_POST
    session_info
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/register.py", line 364, in _do_shared_secret
    admin=bool(admin),
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/register.py", line 166, in register
    admin=admin,
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 325, in runInteraction
    inner_func, *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 285, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 319, in inner_func
    func, *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 247, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/registration.py", line 182, in _register
    (create_profile_with_localpart,)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 84, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 114, in _do_execute
    sql, *args
IntegrityError: UNIQUE constraint failed: profiles.user_id
2017-10-11 22:06:04,714 - synapse.access.https.8448 - 91 - INFO - POST-12- 127.0.0.1 - 8448 - {None} Processed request: 293ms (284ms, 0ms) (1ms/2) 55B 500 "POST /_matrix/client/api/v1/register HTTP/1.1" "Python-urllib/2.7"
```
### Version information

- **Homeserver**

If not matrix.org:
- **0.23.1**

-->
- **package manager**
- **Ubuntu**

**Comment by turt2live** [comment]
I think it's trying to tell you `foo` is already registered, but it seems to have exploded in doing so.

**Comment by Ironlenny** [comment]
No, foo is not an entry in my database.

```
root@matrix:/var/lib/matrix-synapse# sqlite3 homeserver.db 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from users
   ...> ;
@steve:localhost|$2b$12$c4cYb08aPBExMs4vFN7A3exuVCDDnUyRcFQ8eSlGslb3Ay1P2G5ou|1506550324|1||0|
@f:localhost|$2b$12$gm1.3nim2mobSs9XHAtpruNiJ/YsUyJRZOOplMchk8jukzIUXarUi|1507758572|0||0|
@jam:localhost|$2b$12$Bzg2RloArtbShpNdIcYjj.ITK7AolHNAU8Cmw8eXyiY4JwN7/hkCm|1507758636|0||0|
@bob:localhost|$2b$12$.FfC7UFk1zI1kqcIGn8D9.lbDZaAR6a2VtKwDZAdi.d.EGKTKGjoS|1507758727|0||0|
@fooo:localhost|$2b$12$gq7dbwc83G11e1Xfsa3pfu3y4ENpJdVJeK3FSf/r5Zvcn2ZhUr9He|1507759025|0||0|
@foobar:localhost|$2b$12$cM.ljsQKNbjgulaKVOdBBOy6dYxH8lTBU2XSBRW.6sdA1IRScz3ja|1507764916|0||0|
```

**Comment by turt2live** [comment]
The error is on the profiles table, so try the following: ` select * from profiles where user_id = 'foo';`

**Comment by Ironlenny** [comment]
Sure enough:
```
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select * from profiles where user_id = 'foo';
foo||
```

**Comment by richvdh** [comment]
assuming that this is not an ongoing problem.
