### ISSUE TITLE
User invited to a bridge room cannot join it

### ISSUE THREAD

**Issue by floviolleau** [matrix-org/synapse#2541]
### Description

I use my own homeserver.

I binded a discord bridge to a specific room in riot. Users from discord side, successfully joined that room in riot side. My riot user and my discord user can join that room and talk together.

Everything is working fine except that if an another riot user has been invited to join that bridge room, he cannot join it if he clicks on accept invite and I have that error messages in logs.

Who can help me?

### Steps to reproduce

- setup a discord bridge
- have a specific room for that bridge on riot side
- join on riot side that room bridge with a user
- invite an another riot user to join that bridge
- the user invited will have a 500 error

Logs:

```
2017-10-16 13:30:18,961 - synapse.storage.events - 179 - ERROR - POST-29622- IntegrityError, retrying.
Traceback (most recent call last):
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/events.py", line 177, in f
    res = yield func(self, *args, **kwargs)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/events.py", line 385, in _persist_events
    new_forward_extremeties=new_forward_extremeties,
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 325, in runInteraction
    inner_func, *args, **kwargs
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 319, in inner_func
    func, *args, **kwargs
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 247, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/util/logutils.py", line 84, in wrapped
    return f(*args, **kwargs)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/events.py", line 657, in _persist_events_txn
    self._update_current_state_txn(txn, current_state_for_room, max_stream_order)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/events.py", line 739, in _update_current_state_txn
    for key, ev_id in to_insert.iteritems()
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 476, in _simple_insert_many_txn
    txn.executemany(sql, vals)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 87, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 114, in _do_execute
    sql, *args
IntegrityError: UNIQUE constraint failed: current_state_events.event_id
2017-10-16 13:30:18,975 - synapse.http.server - 139 - ERROR - POST-29622- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x74aabf70>: <XForwardedForRequest at 0x6e4fccd8 method=POST uri=/_matrix/client/r0/join/%23_discord_107487159992250368_107487159992250368:my.domain.org?access_token=<redacted> clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/path/matrix/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
IntegrityError: UNIQUE constraint failed: current_state_events.event_id
2017-10-16 13:30:18,980 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-16 13:30:18,981 - twisted - 131 - CRITICAL - -
IntegrityError: UNIQUE constraint failed: current_state_events.event_id
```

### Version information

- **Homeserver**: my homeserver

If not matrix.org:
- **Version**:        Synapse version 0.22.1
- **Install method**: pip      
- **Platform**: raspbian, raspberry pi, inside python vhost
- **Database schema version number**: V43

**Comment by saintger** [comment]
Perhaps it is related to this issue as well:
https://github.com/matrix-org/synapse/issues/2555

**Comment by MadLittleMods** [comment]
Given https://github.com/matrix-org/synapse/issues/2555 was also closed as probably not a problem in recent Synapse, going to close this one.
