### ISSUE TITLE
IntegrityError: UNIQUE constraint failed: current_state_events.event_id

### ISSUE THREAD

**Issue by saintger** [matrix-org/synapse#2555]
### Description

Impossible to rename a room or to invite members in a private 1to1 room (members and room are hosted on my Synapse server).
It seemed to happen after iOS/Android app update.

Context: I have my own synapse server 0.23.1-1 on Debian Stretch, there are only 3 account on this server (me, friendA, friendB) and I have 2 rooms A and B where I am discussing on 1to1 with friendA and friendB.

Before the last update: the room were named with the name of each friend (room A is named friendA and room B is named friendB).

After the last update: in iOS the room B has been renamed friendA (but room A remains with the name friendA, so I have 2 rooms named the same) and the member list of room B is listing friendA as a member instead of friendB. friendB cannot post in the room B anymore.
However on riot-web, the room B name and room B member list hasn't changed.
Either with riot-ios or riot-web, I cannot rename the room or change the member list because I got an "Internal Server Error". 

### Steps to reproduce

Trying to rename the room B through riot-web I got the following error on my Synapse server:

```
Oct 18 13:41:49 example python[1400]: 2017-10-18 13:41:49,889 - synapse.storage.events - 179 - ERROR - PUT-5612- IntegrityError, retrying.
Oct 18 13:41:49 example python[1400]: Traceback (most recent call last):
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 177, in f
Oct 18 13:41:49 example python[1400]:     res = yield func(self, *args, **kwargs)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Oct 18 13:41:49 example python[1400]:     result = result.throwExceptionIntoGenerator(g)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Oct 18 13:41:49 example python[1400]:     return g.throw(self.type, self.value, self.tb)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 385, in _persist_events
Oct 18 13:41:49 example python[1400]:     new_forward_extremeties=new_forward_extremeties,
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Oct 18 13:41:49 example python[1400]:     result = result.throwExceptionIntoGenerator(g)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Oct 18 13:41:49 example python[1400]:     return g.throw(self.type, self.value, self.tb)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 325, in runInteraction
Oct 18 13:41:49 example python[1400]:     inner_func, *args, **kwargs
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
Oct 18 13:41:49 example python[1400]:     result = inContext.theWork()
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
Oct 18 13:41:49 example python[1400]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
Oct 18 13:41:49 example python[1400]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
Oct 18 13:41:49 example python[1400]:     return func(*args,**kw)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
Oct 18 13:41:49 example python[1400]:     compat.reraise(excValue, excTraceback)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
Oct 18 13:41:49 example python[1400]:     result = func(conn, *args, **kw)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 319, in inner_func
Oct 18 13:41:49 example python[1400]:     func, *args, **kwargs
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 247, in _new_transaction
Oct 18 13:41:49 example python[1400]:     r = func(txn, *args, **kwargs)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/util/logutils.py", line 84, in wrapped
Oct 18 13:41:49 example python[1400]:     return f(*args, **kwargs)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 657, in _persist_events_txn
Oct 18 13:41:49 example python[1400]:     self._update_current_state_txn(txn, current_state_for_room, max_stream_order)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 739, in _update_current_state_txn
Oct 18 13:41:49 example python[1400]:     for key, ev_id in to_insert.iteritems()
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 476, in _simple_insert_many_txn
Oct 18 13:41:49 example python[1400]:     txn.executemany(sql, vals)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 87, in executemany
Oct 18 13:41:49 example python[1400]:     self._do_execute(self.txn.executemany, sql, *args)
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 114, in _do_execute
Oct 18 13:41:49 example python[1400]:     sql, *args
Oct 18 13:41:49 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
Oct 18 13:41:49 example python[1400]: 2017-10-18 13:41:49,904 - synapse.http.server - 139 - ERROR - PUT-5612- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fda0daa9210>: <SynapseRequest at 0x7fda06b263b0 method=PUT uri=/_matrix/client/r0/rooms/!sCoXDoPiVngDDqLZAS%3Aexample.org/state/m.room.name?access_token=<redacted> clientproto=HTTP/1.0 site=8008>
Oct 18 13:41:49 example python[1400]: Traceback (most recent call last):
Oct 18 13:41:49 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
Oct 18 13:41:49 example python[1400]:     yield request_handler(self, request, request_metrics)
Oct 18 13:41:49 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
Oct 18 13:41:49 example python[1400]: 2017-10-18 13:41:49,910 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
Oct 18 13:41:49 example python[1400]: 2017-10-18 13:41:49,911 - twisted - 131 - CRITICAL - -
Oct 18 13:41:49 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
```

Trying to re-add the previous member friend B to the room B through riot-web, I got the following error:

```
Oct 18 13:44:03 example python[1400]: 2017-10-18 13:44:03,752 - synapse.storage.events - 179 - ERROR - POST-5619- IntegrityError, retrying.
Oct 18 13:44:03 example python[1400]: Traceback (most recent call last):
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 177, in f
Oct 18 13:44:03 example python[1400]:     res = yield func(self, *args, **kwargs)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Oct 18 13:44:03 example python[1400]:     result = result.throwExceptionIntoGenerator(g)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Oct 18 13:44:03 example python[1400]:     return g.throw(self.type, self.value, self.tb)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 385, in _persist_events
Oct 18 13:44:03 example python[1400]:     new_forward_extremeties=new_forward_extremeties,
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Oct 18 13:44:03 example python[1400]:     result = result.throwExceptionIntoGenerator(g)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Oct 18 13:44:03 example python[1400]:     return g.throw(self.type, self.value, self.tb)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 325, in runInteraction
Oct 18 13:44:03 example python[1400]:     inner_func, *args, **kwargs
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
Oct 18 13:44:03 example python[1400]:     result = inContext.theWork()
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
Oct 18 13:44:03 example python[1400]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
Oct 18 13:44:03 example python[1400]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
Oct 18 13:44:03 example python[1400]:     return func(*args,**kw)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
Oct 18 13:44:03 example python[1400]:     compat.reraise(excValue, excTraceback)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
Oct 18 13:44:03 example python[1400]:     result = func(conn, *args, **kw)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 319, in inner_func
Oct 18 13:44:03 example python[1400]:     func, *args, **kwargs
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 247, in _new_transaction
Oct 18 13:44:03 example python[1400]:     r = func(txn, *args, **kwargs)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/util/logutils.py", line 84, in wrapped
Oct 18 13:44:03 example python[1400]:     return f(*args, **kwargs)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 657, in _persist_events_txn
Oct 18 13:44:03 example python[1400]:     self._update_current_state_txn(txn, current_state_for_room, max_stream_order)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/events.py", line 739, in _update_current_state_txn
Oct 18 13:44:03 example python[1400]:     for key, ev_id in to_insert.iteritems()
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 476, in _simple_insert_many_txn
Oct 18 13:44:03 example python[1400]:     txn.executemany(sql, vals)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 87, in executemany
Oct 18 13:44:03 example python[1400]:     self._do_execute(self.txn.executemany, sql, *args)
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 114, in _do_execute
Oct 18 13:44:03 example python[1400]:     sql, *args
Oct 18 13:44:03 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
Oct 18 13:44:03 example python[1400]: 2017-10-18 13:44:03,771 - synapse.http.server - 139 - ERROR - POST-5619- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fda0daa9210>: <SynapseRequest at 0x7fda06a6b0e0 method=POST uri=/_matrix/client/r0/rooms/!sCoXDoPiVngDDqLZAS%3Aexample.org/invite?access_token=<redacted> clientproto=HTTP/1.0 site=8008>
Oct 18 13:44:03 example python[1400]: Traceback (most recent call last):
Oct 18 13:44:03 example python[1400]:   File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 116, in wrapped_request_handler
Oct 18 13:44:03 example python[1400]:     yield request_handler(self, request, request_metrics)
Oct 18 13:44:03 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
Oct 18 13:44:03 example python[1400]: 2017-10-18 13:44:03,778 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
Oct 18 13:44:03 example python[1400]: 2017-10-18 13:44:03,780 - twisted - 131 - CRITICAL - -
Oct 18 13:44:03 example python[1400]: IntegrityError: UNIQUE constraint failed: current_state_events.event_id
```

### Version information

- **Homeserver**: Synapse server 0.23.1-1 on Debian Stretch (kernel 4.9.0-3-amd64) installed through the matrix repository

**Comment by saintger** [comment]
And now on riot-web, the room name and the room member list are also incorrect.
Very strange...

**Comment by richvdh** [comment]
Is this still a problem on recent synapse?

**Comment by richvdh** [comment]
let's assume not.
