### ISSUE TITLE
Fail to upgrade Synapse (Pillow)

### ISSUE THREAD

**Issue by nioc** [matrix-org/synapse#2562]
### Description

Hello, I try yo upgrade Synapse from 0.22.1 to latest version using virtualenv/pip and I got an error with "Pillow" (see the log)

### Steps to reproduce

I just followed the [help](https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst)

````
me@pi:~/.synapse $ source ~/.synapse/bin/activate
(.synapse) me@pi:~/.synapse $ pip install --upgrade --process-dependency-links https://github.com/matrix-org/synapse/tarball/master
Collecting https://github.com/matrix-org/synapse/tarball/master
  Downloading https://github.com/matrix-org/synapse/tarball/master (847kB)
    100% |████████████████████████████████| 849kB 158kB/s 
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Requirement already up-to-date: matrix-synapse-ldap3>=0.1 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: msgpack-python>=0.3.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: daemonize in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: frozendict>=0.4 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: psutil>=2.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: pyopenssl>=0.14 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: pydenticon in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: pymacaroons-pynacl in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: service_identity>=1.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: signedjson>=1.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: pyyaml in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: Twisted>=16.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: bleach>=1.4.2 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: unpaddedbase64>=1.1.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Collecting pillow (from matrix-synapse==0.23.1)
  Using cached Pillow-4.3.0.tar.gz
Collecting pyasn1 (from matrix-synapse==0.23.1)
  Using cached pyasn1-0.3.7-py2.py3-none-any.whl
Requirement already up-to-date: ujson in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: pynacl==0.3.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: netaddr>=0.7.18 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: jsonschema>=2.5.1 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: blist in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: canonicaljson>=1.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: matrix_angular_sdk>=0.6.8 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Requirement already up-to-date: Jinja2>=2.8 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Collecting affinity (from matrix-synapse==0.23.1)
Requirement already up-to-date: pysaml2<4.0.0,>=3.0.0 in ./lib/python2.7/site-packages (from matrix-synapse==0.23.1)
Collecting bcrypt (from matrix-synapse==0.23.1)
Collecting phonenumbers>=8.2.0 (from matrix-synapse==0.23.1)
  Using cached phonenumbers-8.8.4-py2.py3-none-any.whl
Requirement already up-to-date: ldap3>=0.9.5 in ./lib/python2.7/site-packages (from matrix-synapse-ldap3>=0.1->matrix-synapse==0.23.1)
Requirement already up-to-date: six>=1.5.2 in ./lib/python2.7/site-packages (from pyopenssl>=0.14->matrix-synapse==0.23.1)
Collecting cryptography>=1.9 (from pyopenssl>=0.14->matrix-synapse==0.23.1)
Collecting pyasn1-modules (from service_identity>=1.0.0->matrix-synapse==0.23.1)
  Using cached pyasn1_modules-0.1.5-py2.py3-none-any.whl
Requirement already up-to-date: attrs in ./lib/python2.7/site-packages (from service_identity>=1.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: zope.interface>=3.6.0 in ./lib/python2.7/site-packages (from Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: constantly>=15.1 in ./lib/python2.7/site-packages (from Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: incremental>=16.10.1 in ./lib/python2.7/site-packages (from Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: Automat>=0.3.0 in ./lib/python2.7/site-packages (from Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: hyperlink>=17.1.1 in ./lib/python2.7/site-packages (from Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in ./lib/python2.7/site-packages (from bleach>=1.4.2->matrix-synapse==0.23.1)
Requirement already up-to-date: olefile in ./lib/python2.7/site-packages (from pillow->matrix-synapse==0.23.1)
Collecting cffi>=0.8 (from pynacl==0.3.0->matrix-synapse==0.23.1)
Requirement already up-to-date: functools32; python_version == "2.7" in ./lib/python2.7/site-packages (from jsonschema>=2.5.1->matrix-synapse==0.23.1)
Requirement already up-to-date: simplejson>=3.6.5 in ./lib/python2.7/site-packages (from canonicaljson>=1.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: MarkupSafe>=0.23 in ./lib/python2.7/site-packages (from Jinja2>=2.8->matrix-synapse==0.23.1)
Requirement already up-to-date: decorator in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: requests>=1.0.0 in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: paste in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: repoze.who in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: pycrypto>=2.5 in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: pytz in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: python-dateutil in ./lib/python2.7/site-packages (from pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: enum34; python_version < "3" in ./lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl>=0.14->matrix-synapse==0.23.1)
Requirement already up-to-date: asn1crypto>=0.21.0 in ./lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl>=0.14->matrix-synapse==0.23.1)
Requirement already up-to-date: idna>=2.1 in ./lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl>=0.14->matrix-synapse==0.23.1)
Requirement already up-to-date: ipaddress; python_version < "3" in ./lib/python2.7/site-packages (from cryptography>=1.9->pyopenssl>=0.14->matrix-synapse==0.23.1)
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted>=16.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: webencodings in ./lib/python2.7/site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach>=1.4.2->matrix-synapse==0.23.1)
Requirement already up-to-date: pycparser in ./lib/python2.7/site-packages (from cffi>=0.8->pynacl==0.3.0->matrix-synapse==0.23.1)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in ./lib/python2.7/site-packages (from requests>=1.0.0->pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in ./lib/python2.7/site-packages (from requests>=1.0.0->pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: certifi>=2017.4.17 in ./lib/python2.7/site-packages (from requests>=1.0.0->pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Requirement already up-to-date: WebOb in ./lib/python2.7/site-packages (from repoze.who->pysaml2<4.0.0,>=3.0.0->matrix-synapse==0.23.1)
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command /home/pi/.synapse/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-48jqkj/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp579vaopip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing requirements to Pillow.egg-info/requires.txt
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-48jqkj/pillow/setup.py", line 799, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow, pyasn1, affinity, cffi, bcrypt, phonenumbers, matrix-synapse, cryptography, pyasn1-modules
  Found existing installation: Pillow 4.2.1
    Uninstalling Pillow-4.2.1:
      Successfully uninstalled Pillow-4.2.1
  Running setup.py install for pillow ... error
    Complete output from command /home/pi/.synapse/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-48jqkj/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xL1Bcd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.synapse/include/site/python2.7/pillow:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
    running egg_info
    writing requirements to Pillow.egg-info/requires.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis/*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-48jqkj/pillow/setup.py", line 799, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
  Rolling back uninstall of Pillow
Command "/home/pi/.synapse/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-48jqkj/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xL1Bcd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.synapse/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-build-48jqkj/pillow/
````

### Version information

- **Homeserver**: Own

If not matrix.org:
- **Version**:        Synapse/0.22.1
- **Install method**: pip
- **Platform**:       Raspbian Stretch (4.9.41 ARM7) on raspberrypi 2

**Comment by turt2live** [comment]
It seems like your system is missing `zlib`.

**Comment by nioc** [comment]
I checked, I have this package installed:
`zlib1g:armhf   1:1.2.8.dfsg-5    armhf    compression library - runtime`
Maybe not enough (I do not find any python-zlib package)?

**Comment by turt2live** [comment]
Try `zlib-devel`

**Comment by nioc** [comment]
Good call.
I've just installed `zlib1g-dev` and it works :+1: 
Thanks.
