### ISSUE TITLE
556,592+ group attestation renewals sent to self in a tightloop, resulting in server failure

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2592]
### Description

Background:
The `+discord:t2bot.io` group has 7372 members in it. These members were added using [this](https://github.com/turt2live/matrix-grouper) approach. Members then manually had `is_public` in `group_users` set to false.

The timespan for this event is spread over nearly 12 hours, with only the last 2 hours causing server failure. At the time of writing this, 556,592 requests have failed. This number is only going up.

The logs are filled with all kinds of events. Here's a heavily trimmed snippet:
```
2017-10-27 03:03:35,280 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-6764} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: DeferredTimedOutError('504: Timed out',)
2017-10-27 03:03:35,280 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-6727} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: DeferredTimedOutError('504: Timed out',)
2017-10-27 03:03:35,281 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-6942} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: DeferredTimedOutError('504: Timed out',)
2017-10-27 03:03:35,281 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-6844} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: DeferredTimedOutError('504: Timed out',)

----snip----

2017-10-27 03:03:35,286 - synapse.http.endpoint - 264 - INFO - - Connecting to 136.243.62.149:8448
2017-10-27 03:03:35,287 - synapse.http.endpoint - 264 - INFO - - Connecting to 136.243.62.149:8448
2017-10-27 03:03:35,288 - synapse.http.endpoint - 264 - INFO - - Connecting to 136.243.62.149:8448
2017-10-27 03:03:35,289 - synapse.http.endpoint - 264 - INFO - - Connecting to 136.243.62.149:8448
2017-10-27 03:03:35,289 - synapse.http.endpoint - 264 - INFO - - Connecting to 136.243.62.149:8448

----snip----

2017-10-27 03:03:35,357 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-8498} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: ResponseNeverReceived:[ConnectionDone()]
2017-10-27 03:03:35,357 - synapse.http.outbound - 236 - INFO - - {POST-O-8498} [t2bot.io] Result: ResponseNeverReceived:[ConnectionDone()]
2017-10-27 03:03:35,357 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 03:03:35,358 - twisted - 131 - CRITICAL - - 
ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2017-10-27 03:03:35,358 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e99e14398>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6eca729a90>)
2017-10-27 03:03:35,358 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-8649} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: ResponseNeverReceived:[ConnectionDone()]
2017-10-27 03:03:35,358 - synapse.http.outbound - 236 - INFO - - {POST-O-8649} [t2bot.io] Result: ResponseNeverReceived:[ConnectionDone()]
2017-10-27 03:03:35,359 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 03:03:35,359 - twisted - 131 - CRITICAL - - 
ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>]
2017-10-27 03:03:35,359 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6eca2c0050>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea72d7f10>)
2017-10-27 03:03:35,379 - synapse.http.matrixfederationclient - 212 - WARNING - - {POST-O-9097} Sending request failed to t2bot.io: POST matrix://t2bot.io/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io: ResponseNeverReceived:[ConnectionLost('Connection lost',)]
2017-10-27 03:03:35,379 - synapse.http.outbound - 236 - INFO - - {POST-O-9097} [t2bot.io] Result: ResponseNeverReceived:[ConnectionLost('Connection lost',)]
2017-10-27 03:03:35,380 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 03:03:35,380 - twisted - 131 - CRITICAL - - 
ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]

----snip----

2017-10-27 03:03:35,381 - twisted - 131 - INFO - - Starting factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e9b3ae500>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea1387b50>)
2017-10-27 03:03:35,382 - twisted - 131 - INFO - - Starting factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6ea7e14050>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6e9f7bea90>)
2017-10-27 03:03:35,382 - twisted - 131 - INFO - - Starting factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6ec933ad70>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea6f816d0>)
2017-10-27 03:03:35,383 - twisted - 131 - INFO - - Starting factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6ed9c14230>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea56d9d50>)

----snip----

2017-10-27 03:03:35,426 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e99c368c0>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea55eb2d0>)
2017-10-27 03:03:35,426 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e9ca409b0>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea257c810>)
2017-10-27 03:03:35,427 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e9ca9fa28>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea554a190>)
2017-10-27 03:03:35,428 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e9c848f50>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea5566510>)
2017-10-27 03:03:35,428 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7f6e99bc79b0>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7f6ea5510350>)

----snip----

2017-10-27 03:03:35,829 - synapse.access.https.8558 - 59 - INFO - POST-8556- 136.243.62.149 - 8558 - Received request: POST /_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io
2017-10-27 03:03:35,830 - synapse.federation.transport.server - 140 - INFO - POST-8556- Request from t2bot.io
2017-10-27 03:03:35,830 - synapse.access.https.8558 - 59 - INFO - POST-8557- 136.243.62.149 - 8558 - Received request: POST /_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io
2017-10-27 03:03:35,831 - synapse.federation.transport.server - 140 - INFO - POST-8557- Request from t2bot.io
2017-10-27 03:03:35,832 - synapse.access.https.8558 - 59 - INFO - POST-8558- 136.243.62.149 - 8558 - Received request: POST /_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io
2017-10-27 03:03:35,832 - synapse.federation.transport.server - 140 - INFO - POST-8558- Request from t2bot.io
2017-10-27 03:03:35,833 - synapse.access.https.8558 - 59 - INFO - POST-8559- 136.243.62.149 - 8558 - Received request: POST /_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io
2017-10-27 03:03:35,834 - synapse.federation.transport.server - 140 - INFO - POST-8559- Request from t2bot.io
2017-10-27 03:03:35,834 - synapse.access.https.8558 - 59 - INFO - POST-8560- 136.243.62.149 - 8558 - Received request: POST /_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io
2017-10-27 03:03:35,835 - synapse.federation.transport.server - 140 - INFO - POST-8560- Request from t2bot.io
```

The Discord user IDs have been redacted. They are unique, and do represent members of the group.

Synapse itself is 500ing the requests, but is blocked for so long on so many requests that it simply cannot keep up. The 500 errors have two common stacktraces:

```
2017-10-27 03:03:36,344 - synapse.http.outbound - 236 - INFO - - {POST-O-6287} [t2bot.io] Result: 500 Internal Server Error
2017-10-27 03:03:36,345 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 03:03:36,345 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/groups/attestations.py", line 140, in _renew_attestation
    content={"attestation": attestation},
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 388, in post_json
    ignore_backoff=ignore_backoff,
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 247, in _request
    response.code, response.phrase, body
HttpResponseException: 500: Internal Server Error
```
```
2017-10-27 06:53:38,537 - synapse.http.server - 123 - INFO - POST-15031- <XForwardedForRequest at 0x7f98e97d6710 method=POST uri=/_matrix/federation/v1/groups/+discord:t2bot.io/renew_attestation/@_discord_REDACTED:t2bot.io clientproto=HTTP/1.0 site=8558> SynapseError: 404 - No row found
2017-10-27 06:53:38,537 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 06:53:38,537 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 131, in wrapped_request_handler
    version_string=self.version_string,
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 374, in respond_with_json
    version_string=version_string
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 399, in respond_with_json_bytes
    request.write(json_bytes)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/web/server.py", line 234, in write
    http.Request.write(self, data)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/web/http.py", line 1069, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'
```

All while this is happening, the entire server is unresponsive. Occasionally, `/_matrix/federation/v1/version` would return a 500 error, although I'm not easily able to figure out why (probably an nginx thing?)

When the server becomes dislodged, the entire thing falls apart and is no longer able to function:
```
2017-10-27 07:00:56,079 - synapse.access.https.8558 - 91 - INFO - PUT-19438- 83.136.250.51 - 8558 - {matrix.org} Processed request: 192ms (12ms, 0ms) (161ms/13) 50B 200 "PUT /_matrix/federation/v1/send/1508841436873/ HTTP/1.0" "Synapse/0.23.1 (b=matrix-org-hotfixes,8bcbeea)"
2017-10-27 07:00:56,096 - synapse.metrics - 162 - INFO - - Collecting gc 0
2017-10-27 07:00:56,099 - synapse.replication.tcp.resource - 166 - INFO - - Failed to handle stream caches
2017-10-27 07:00:56,100 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-10-27 07:00:56,100 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/replication/tcp/resource.py", line 164, in on_notifier_poke
    updates, current_token = yield stream.get_updates()
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/replication/tcp/streams.py", line 169, in get_updates
    updates, current_token = yield self.get_updates_since(self.last_token)
  File "/root/synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/local/lib/python2.7/site-packages/synapse/replication/tcp/streams.py", line 200, in get_updates_since
    raise Exception("stream %s has fallen behined" % (self.NAME))
Exception: stream caches has fallen behined
```

I've had to restart the entire stack a few times, although it only keeps the issue at bay for 30-45 minutes before failing again.

Full logs are available upon request.

### Version information

- **Homeserver**: t2bot.io
- **Version**:      0.24.1
- **Install method**: pip
- **Platform**:       Ubuntu 16.04 running under a container.
- **Workers**:
  - appservice
  - federation_reader (no traffic)
  - federation_sender
  - media_repository
  - synchrotron (1)

**Comment by turt2live** [comment]
As a temporary fix, I've vacated the group of most members. This brings the number of requests down to a manageable level.

**Comment by richvdh** [comment]
#2593 has fixed most of this, though https://github.com/vector-im/riot-web/issues/5545 would make it better still
