### ISSUE TITLE
OperationalError: no such module: fts4

### ISSUE THREAD

**Issue by Linuxine** [matrix-org/synapse#2696]
I have Matrix version 0.25, on a CentOS Linux release 7.4.1708 (Core).

As the default version for sqlite is 3.7.17 on CentOS 7, it does not support partial indexes, and this causes error when updating Matrix (since at least 0.24, there is a partial index, see #2572).

So I tried to compile locally a newer sqlite version.

To compile sqlite, I did:
~~~
& curl -L -O https://sqlite.org/2017/sqlite-amalgamation-3210000.zip
    && unzip sqlite-amalgamation-3210000.zip \
    && cd sqlite-amalgamation-3210000 \
    && gcc -c sqlite3.c -o sqlite3.o && ar rcs libsqlite3.a sqlite3.o \
    && gcc -c -fPIC sqlite3.c -o sqlite3_ind.o && gcc -shared -Wl,-soname,libsqlite3.so.1 -o libsqlite3.so.0  sqlite3_ind.o
~~~

Then, I tried to start Matrix by adding in my systemd unit file the following line:

~~~
Environment=LD_LIBRARY_PATH=/home/matrix/sqlite-amalgamation-3210000
~~~

The server seems to start without error. But when I send a message in Riot, I get the following error:

~~~
2017-11-20 14:35:08,707 - synapse.http.server - 139 - ERROR - PUT-86- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x493b7d0>: <XForwardedForRequest at 0x7f3c844e60e0 method=PUT uri=/_matrix/client/r0/rooms/!qbVTdEptIqJBNbAvVw:linuxine.net/send/m.room.message/m1511184908563.0?access_token=<redacted> clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/home/matrix/synapse/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
OperationalError: no such module: fts4
2017-11-20 14:35:08,729 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-11-20 14:35:08,729 - twisted - 131 - CRITICAL - - 
OperationalError: no such module: fts4
2017-11-20 14:35:11,004 - synapse.http.server - 139 - ERROR - PUT-91- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x493b7d0>: <XForwardedForRequest at 0x53a7440 method=PUT uri=/_matrix/client/r0/rooms/!qbVTdEptIqJBNbAvVw:linuxine.net/send/m.room.message/m1511184908563.0?access_token=<redacted> clientproto=HTTP/1.1 site=8008>
Traceback (most recent call last):
  File "/home/matrix/synapse/lib/python2.7/site-packages/synapse/http/server.py", line 116, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
OperationalError: no such module: fts4
2017-11-20 14:35:11,005 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2017-11-20 14:35:11,005 - twisted - 131 - CRITICAL - - 
OperationalError: no such module: fts4
~~~

Then it is all broken, the error appears in a loop, and the messages are not sent.

**Comment by richvdh** [comment]
> OperationalError: no such module: fts4

This suggests that you haven't enabled the [fts4](https://sqlite.org/fts3.html) module. Try setting `-DSQLITE_ENABLE_FTS4` when compiling sqlite. (See https://sqlite.org/compile.html#_options_to_enable_features_normally_turned_off. You may want to find out what other options CentOS use for their distribution and copy them).

**Comment by Linuxine** [comment]
Thanks. When launching the default sqlite on my Centos7, I get
~~~
sqlite> PRAGMA compile_options;
DISABLE_DIRSYNC
ENABLE_COLUMN_METADATA
ENABLE_FTS3
ENABLE_RTREE
ENABLE_UNLOCK_NOTIFY
SECURE_DELETE
TEMP_STORE=1
THREADSAFE=1
~~~

So should I try with fts4 or fts3 enabled ?

Besides, I think this issue is related to #1717.

**Comment by richvdh** [comment]
we're using fts4, so I'd expect you to need that. It might be that you get FTS4 for free when FTS3 is enabled, or something.

Suggest you try -DSQLITE_ENABLE_FTS4 and see how it goes!

**Comment by Linuxine** [comment]
So I tried to compile sqlite with the same instruction, but adding -DSQLITE_ENABLE_FTS4 as suggested. And it works ! \o/
Thanks a lot for you help !
