### ISSUE TITLE
_get_public_room_list throws exception for zero public rooms

### ISSUE THREAD

**Issue by petercolberg** [matrix-org/synapse#2819]
On a private homeserver without any public rooms, Synapse 0.26.0 throws this exception from time to time:
```
synapse.http.server - 145 - ERROR - POST-286- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fd0c5b61750>: <XForwardedForRequest at 0x7fd0b4b62f80 method=POST uri=/_matrix/client/r0/publicRooms?access_token=<redacted> clientproto=HTTP/1.0 site=8008>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 360, in on_POST
    network_tuple=network_tuple,
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/room_list.py", line 86, in get_local_public_room_list
    limit, since_token, network_tuple=network_tuple
  File "/usr/lib/python2.7/dist-packages/synapse/util/logcontext.py", line 278, in g
    res = f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/room_list.py", line 209, in _get_public_room_list
    for i in xrange(0, len(rooms_to_scan), step):
exceptions.ValueError: xrange() arg 3 must not be zero
```
It looks like this was introduced by commit 44a1bfd6a6a1cda272677c9ea8704957bc940509.

**Comment by richvdh** [comment]
fixed by #2827
