### ISSUE TITLE
Return an appropriate response when getting joined_members after leaving

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#2851]
```
2018-02-05 19:59:38,357 - synapse.http.server - 183 - ERROR - GET-132067- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRest
Resource object at 0x7f9dae55b590>: <XForwardedForRequest at 0x7f9d7856c2d8 method=GET uri=/_matrix/client/r0/rooms/!vfFxDRtZSSdspfTSEr:matrix.org/joined_mem
bers?access_token=<redacted> clientproto=HTTP/1.1 site=8008>: Traceback (most recent call last):
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v1/room.py", line 408, in on_GET
    requester, room_id,
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/.synapse/local/lib/python2.7/site-packages/synapse/handlers/message.py", line 449, in get_joined_members
    "Getting joined members after leaving is not implemented"
exceptions.NotImplementedError: Getting joined members after leaving is not implemented
```

**Comment by DMRobertson** [comment]
Shows up smiregularly in Sentry here: https://sentry.tools.element.io/organizations/element/issues/55/?project=2

[The spec](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidjoined_members) allows us to return 403 in this situation.

**Comment by DMRobertson** [comment]
If anyone wants to take this on:

1. Change this to raise a `SynapseError` with status code 403, an appropriate error message and and appropriate [matrix error code](https://spec.matrix.org/v1.2/client-server-api/#standard-error-response).
2. Add a test case which asserts that Synapse responses with status code 403 if you try to get the joined members of a room you've left.
3. Optional, harder: for bonus points, write a [complement](https://spec.matrix.org/v1.2/client-server-api/#standard-error-response) test case instead of a Synapse unit test.

**Comment by andrewdoh** [comment]
Hi @DMRobertson id like to work on this. I've created the two PRs below. please check them out, thanks.
https://github.com/matrix-org/synapse/pull/13374
https://github.com/matrix-org/complement/pull/424

**Comment by akstron** [comment]
Hi @DMRobertson, seems like this issue is already resolved but not closed. Is there anything else which needs to be done?

**Comment by DMRobertson** [comment]
This is done, but wasn't marked as closed by the corresponding PR. Note that we ended up returning 403, contrary to the original title.
