### ISSUE TITLE
Getting lots of sqlite3.ProgrammingError

### ISSUE THREAD

**Issue by rkfg** [matrix-org/synapse#2852]
While I don't quite have any visible issues with the server (except some, described below), I have lots of these errors in the log:

```
2018-02-01 02:38:00,208 - synapse.http.server - 145 - ERROR - GET-44841- Failed handle request synapse.rest.media.v1.preview_url_resource._async_render_GET on <synapse.rest.media.v1.preview_url_resource.PreviewUrlResource instance at 0x7f6480981908>: <SynapseRequest at 0x7f645ad62908 method=GET uri=/_matrix/media/r0/preview_url?url=http%3A%2F%2Fcontext.reverso.net%2F%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%2F%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D1%84%D1%80%D0%B0%D0%BD%D1%86%D1%83%D0%B7%D1%81%D0%BA%D0%B8%D0%B9%2F%D0%BF%D0%B8%D0%B4%D0%BE%D1%80&ts=1517432938220&access_token=<redacted> clientproto=HTTP/1.0 site=8009>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1355, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 119, in wrapped_request_handler
    yield request_handler(self, request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 154, in _async_render_GET
    og = yield make_deferred_yieldable(observable.observe())
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/util/logcontext.py", line 316, in make_deferred_yieldable
    r = yield deferred
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 171, in _do_preview
    cache_result = yield self.store.get_url_cache(url, ts)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 319, in runInteraction
    inner_func, *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 313, in inner_func
    func, *args, **kwargs
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 241, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/media_repository.py", line 80, in get_url_cache_txn
    txn.execute(sql, (url, ts))
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 82, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 112, in _do_execute
    sql, *args
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

I'm also having lots of NoRouteError that are perhaps related to the server network and are investigated by the Leaseweb techies. This may be related as messages get delayed often and I had a broken preview of remote content at least once. The NoRouteError happens to many servers, not just matrix.org so I'm inclined to think it's an issue on my end. However, "ProgrammingError" sounds more dangerous so I think you'd like to know about it.

### Version information

- **Homeserver**: own homeserver
- **Version**:  Synapse/0.26.0
- **Install method**: package manager
- **Platform**: set up on Debian 9.3 amd64.

**Comment by ara4n** [comment]
this looks like it's choking on non-ascii url preview data.

**Comment by rkfg** [comment]
Yes, that's true. Posting a link like https://ru.wikipedia.org/wiki/Коаксиальный_радиочастотный_разъём to the room provokes the error. However, if I post it encoded, it's fine: https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%B0%D0%BA%D1%81%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%B4%D0%B8%D0%BE%D1%87%D0%B0%D1%81%D1%82%D0%BE%D1%82%D0%BD%D1%8B%D0%B9_%D1%80%D0%B0%D0%B7%D1%8A%D1%91%D0%BC

**Comment by richvdh** [comment]
probably fixed by moving to py3?
