### ISSUE TITLE
Failed to handle some PDUs - responsible for client connectivity problems?

### ISSUE THREAD

**Issue by JoKeyser** [matrix-org/synapse#2862]
### Description

I'm recently experiencing connectivity problems to my self-hosted HS from all my Riot clients (Android and Desktop). Occasionally I can connect again (just waiting for tens of minutes, without doing anything to Synapse), but most of the time Riot alerts "Connectivity to the server has been lost".

Synapse seeminly uses constantly 100% CPU (of 1 of 4 cores) and about 2-3 GiB RAM, but that has been the case since the last few weeks (~10 larger rooms federated with matrix.org), i.e. is unlikely to account for the problems.

I've tried to find clues in `/var/log/matrix-synapse/homeserver.log` and `/var/log/daemon.log`, but imo the only unusual logs were these, not sure they're related at all:

```
Feb 11 14:52:39 myhost python[2054]: 2018-02-11 14:52:39,271 - synapse.federation.federation_server - 198 - ERROR - PUT-92- Failed to handle PDU $15183545302556338gEFmH:matrix.org
Feb 11 14:52:39 myhost python[2054]: Traceback (most recent call last):
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 190, in process_pdus_for_room
Feb 11 14:52:39 myhost python[2054]:     transaction.origin, pdu
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 582, in _handle_received_pdu
Feb 11 14:52:39 myhost python[2054]:     yield self.handler.on_receive_pdu(origin, pdu, get_missing=True)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 193, in on_receive_pdu
Feb 11 14:52:39 myhost python[2054]:     origin, pdu, prevs, min_depth
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 296, in _get_missing_events_for_pdu
Feb 11 14:52:39 myhost python[2054]:     timeout=10000,
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_client.py", line 787, in get_missing_events
Feb 11 14:52:39 myhost python[2054]:     timeout=timeout,
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/client.py", line 470, in get_missing_events
Feb 11 14:52:39 myhost python[2054]:     timeout=timeout,
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 388, in post_json
Feb 11 14:52:39 myhost python[2054]:     ignore_backoff=ignore_backoff,
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = result.throwExceptionIntoGenerator(g)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
Feb 11 14:52:39 myhost python[2054]:     return g.throw(self.type, self.value, self.tb)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 136, in _request
Feb 11 14:52:39 myhost python[2054]:     ignore_backoff=ignore_backoff,
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
Feb 11 14:52:39 myhost python[2054]:     result = g.send(result)
Feb 11 14:52:39 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/util/retryutils.py", line 82, in get_retry_limiter
Feb 11 14:52:39 myhost python[2054]:     destination=destination,
Feb 11 14:52:39 myhost python[2054]: NotRetryingDestination: Not retrying server matrix.org.
```

```
Feb 11 15:05:10 myhost python[2054]: 2018-02-11 15:05:10,104 - synapse.federation.federation_server - 198 - ERROR - PUT-1157- Failed to handle PDU $15183570472585802aksZP:matrix.org
Feb 11 15:05:10 myhost python[2054]: Traceback (most recent call last):
Feb 11 15:05:10 myhost python[2054]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 190, in process_pdus_for_room
Feb 11 15:05:10 myhost python[2054]:     transaction.origin, pdu
Feb 11 15:05:10 myhost python[2054]: NotRetryingDestination: Not retrying server matrix.org.
```

Apart from that, there are plenty warnings about federation with many specific domains that are usual, i.e. DNSLookupError, ConnectionRefusedError, TimeoutError, DeferredTimedOutError.

I'm happy to report anything in more detail.

### Version information

- **Version**:   Debian package matrix-synapse 0.24.0+dfsg-1
- **Install method**: Debian apt
- **Platform**:  Debian buster, amd64, on dedicated hardware with 4 cores and 4 GiB, http://www.pcengines.ch/apu2c4.htm.

**Comment by JoKeyser** [comment]
Hm, the client connectivity problem has improved a lot over the past few hours; Synapse's RAM usage is down to ~1.5 GiB.

I still get occasional ERRORs about failed PDU handling, but there seems to be no link with my actual problem, so I'm closing here.
