### ISSUE TITLE
ImportError: No module named interface - Server won't start

### ISSUE THREAD

**Issue by loi219** [matrix-org/synapse#2907]
### Description

Unable to start matrix-synapse server on Debian 9

### Steps to reproduce
Reproduce the bug
1. service matrix-synapse start
2. Job for matrix-synapse.service failed because the control process exited with error code. See "systemctl status matrix-synapse.service" and "journalctl -xe" for details.

And from journalctl -u matrix-synapse:
```
matrix-synapse.service: Service hold-off time over, scheduling restart.
Feb 23 10:57:09 thylacine systemd[1]: Stopped Synapse Matrix homeserver.
Feb 23 10:57:09 thylacine systemd[1]: Starting Synapse Matrix homeserver...
Feb 23 10:57:10 thylacine python[2600]: Traceback (most recent call last):
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Feb 23 10:57:10 thylacine python[2600]:     "__main__", fname, loader, pkg_name)
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Feb 23 10:57:10 thylacine python[2600]:     exec code in run_globals
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", l
Feb 23 10:57:10 thylacine python[2600]:     import synapse.config.logger
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/synapse/config/logger.py", li
Feb 23 10:57:10 thylacine python[2600]:     from synapse.util.logcontext import LoggingContextFilter
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/synapse/util/__init__.py", li
Feb 23 10:57:10 thylacine python[2600]:     from synapse.util.logcontext import PreserveLoggingContext
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/synapse/util/logcontext.py",
Feb 23 10:57:10 thylacine python[2600]:     from twisted.internet import defer
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", l
Feb 23 10:57:10 thylacine python[2600]:     from twisted.logger import Logger
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/logger/__init__.py",
Feb 23 10:57:10 thylacine python[2600]:     from ._logger import Logger, _loggerFor
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/logger/_logger.py", l
Feb 23 10:57:10 thylacine python[2600]:     _log = Logger()
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/logger/_logger.py", l
Feb 23 10:57:10 thylacine python[2600]:     from ._global import globalLogPublisher
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/logger/_global.py", l
Feb 23 10:57:10 thylacine python[2600]:     from ._buffer import LimitedHistoryLogObserver
Feb 23 10:57:10 thylacine python[2600]:   File "/usr/lib/python2.7/dist-packages/twisted/logger/_buffer.py", l
Feb 23 10:57:10 thylacine python[2600]:     from zope.interface import implementer
Feb 23 10:57:10 thylacine python[2600]: ImportError: No module named interface
Feb 23 10:57:10 thylacine systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Feb 23 10:57:10 thylacine systemd[1]: Failed to start Synapse Matrix homeserver.
Feb 23 10:57:10 thylacine systemd[1]: matrix-synapse.service: Unit entered failed state.
Feb 23 10:57:10 thylacine systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
```
The server can be started

### Version information

- **Homeserver**: homeserver

If not matrix.org:
- **Version**:         Synapse 0.26.0
- **Install method**: apt  
- **Platform**:       Debian GNU/Linux 9

**Comment by vkotous** [comment]
Hi,
I have resolved the same issue by upgrading Python Twisted module to the latest version (in my case from 16.6.0 to 18.4.0).

**Comment by richvdh** [comment]
This can happen if you install some other `zope` packages with `pip` instead of `apt-get`:

before:

```
(stretch-amd64)root@fred:~# python -c 'import zope.interface'
(stretch-amd64)root@fred:~# 
```

After:
```
(stretch-amd64)root@fred:~# pip install -q zope.event
(stretch-amd64)root@fred:~#  python -c 'import zope.interface'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named interface
```

The problem is that `pip install` puts packages in `/usr/local/lib/python2.7/dist-packages`, whereas `zope.interface` is in `/usr/lib/python2.7/dist-packages`; the `zope` directory in `/usr/local` means that python won't look for `zope.interface` in the right place.

It's generally a bad idea to use `pip` on the system python install, for this sort of reason. A workaround is to symlink `zope.interface` into where python is looking for it:

```
ln -s /usr/lib/python2.7/dist-packages/zope/interface /usr/local/lib/python2.7/dist-packages/zope/
```
