### ISSUE TITLE
Custom home server and remote 3PID cannot resolve email addresses and produce CORS errors

### ISSUE THREAD

**Issue by almereyda** [matrix-org/synapse#2914]
### Description

On a custom Matrix instance deployed to another domain than its Riot, we are receiving CORS errors when trying to add new members via their email address to the channel:

- https://github.com/allmende/docker-matrix/issues/10

### Steps to reproduce

- Open an empty room with riot.allmende.io
- Invite some email address
- receive the error in the browser as
```
Failed to load https://riot.im/_matrix/identity/api/v1/lookup?medium=email&address=almereyda%2Briottest%40allmende.io: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://riot.allmende.io' is therefore not allowed access. The response had HTTP status code 504.
```

### Expected response

The home server invites users

### logs

```
2018-02-27 15:23:08,164 - synapse.http.server - 124 - INFO - GET-275- <XForwardedForRequest at 0x7fa5cd006e60 method=GET uri=/_matrix/client/r0/account/3p
id/email/requestToken clientproto=HTTP/1.1 site=8080> SynapseError: 400 - Unrecognized request
2018-02-27 15:23:08,165 - synapse.access.http.8080 - 91 - INFO - GET-275- 172.18.0.1 - 8080 - {None} Processed request: 1ms (0ms, 0ms) (0ms/0) 75B 400 "GE
T /_matrix/client/r0/account/3pid/email/requestToken HTTP/1.1" "Synapse/0.26.0"
2018-02-27 15:23:08,187 - synapse.http.client - 105 - INFO - GET-268- Received response to  GET https://matrix.allmende.io/_matrix/client/r0/account/3pid/
email/requestToken: 400
2018-02-27 15:23:08,187 - synapse.http.client - 356 - WARNING - GET-268- Got 400 when downloading https://matrix.allmende.io/_matrix/client/r0/account/3pi
d/email/requestToken
```

or

```
2018-02-27 15:26:44,729 - twisted - 131 - INFO - - Stopping factory _HTTP11ClientFactory(<function quiescentCallback at 0x7fa6574c8c08>, <synapse.http.endpoint._WrappingEndpointFac object at 0x7fa657d92b90>)
2018-02-27 15:26:45,255 - synapse.http.client - 112 - INFO - POST-790- Error sending request to  GET https://riot.im/_matrix/identity/api/v1/lookup?medium=email&address=almereyda%2Briottest%40allmende.io: DeferredTimedOutError 504: Timed out
2018-02-27 15:26:45,256 - synapse.http.server - 145 - ERROR - POST-790- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7fa693638910>: <XForwardedForRequest at 0x7fa64f966d40 method=POST uri=/_matrix/client/r0/rooms/!UFjUjKgJoabjBwMPBg%3Amatrix.allmende.io/invite?access_token=<redacted> clientproto=HTTP/1.1 site=8080>: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 117, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 263, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 603, in on_POST
    txn_id
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 518, in do_3pid_invite
    id_server, medium, address
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 558, in _lookup_3pid
    "address": address,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/client.py", line 215, in get_json
    raise self._exceptionFromFailedRequest(e.code, e.msg)
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/client.py", line 315, in _exceptionFromFailedRequest
    return CodeMessageException(response.code, body)
exceptions.AttributeError: 'int' object has no attribute 'code'
2018-02-27 15:26:45,257 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
2018-02-27 15:26:45,258 - twisted - 131 - CRITICAL - - 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 156, in wrapped_request_handler
    version_string=self.version_string,
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 380, in respond_with_json
    version_string=version_string
  File "/usr/local/lib/python2.7/dist-packages/synapse/http/server.py", line 405, in respond_with_json_bytes
    request.write(json_bytes)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 1069, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'
```

This therefore seems to be associated with trying to reach a riot.im 3pid service, which apparently does not answer, and throwing more meaningful error messages in Synapse, propagating to Riot.

### Version information

Key | Value
--- | ---
**Homeserver** | `matrix.allmende.io`
**Version** | `v0.26.0`
**Install method** | https://github.com/allmende/docker-matrix 
**Platform** | `debian-slim` on `debian`

**Comment by almereyda** [comment]
This was due to using `riot.im`, where `vector.im` remains still open for anyone to use.
