### ISSUE TITLE
Register new user - certificate verify failed urllib2.URLError: <urlopen error

### ISSUE THREAD

**Issue by Apperator** [matrix-org/synapse#2950]
Hello,

Linux: CentOS 7
Python 2.7.5

I'm trying to register a new Matrix user (first time setup)
`
register_new_matrix_user -c homeserver.yaml https://localhost:8448`

but I am returned with the following error:
```
(synapse)[root@li592-85 synapse]# register_new_matrix_user -c homeserver.yaml https://localhost:8448
New user localpart [root]: admin
Password:
Confirm password:
Make admin [no]: yes
Sending registration request...
Traceback (most recent call last):
  File "/opt/synapse/bin/register_new_matrix_user", line 174, in <module>
    register_new_user(args.user, args.password, args.server_url, secret, args.admin)
  File "/opt/synapse/bin/register_new_matrix_user", line 117, in register_new_user
    request_registration(user, password, server_location, shared_secret, bool(admin))
  File "/opt/synapse/bin/register_new_matrix_user", line 65, in request_registration
    f = urllib2.urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)>
<!- 

```

#2411 
One workaround I've seen is to run:
`[register_new_matrix_user -c homeserver.yaml https://localhost:8008](url)`
However, AFAIK https and port 8448 won't work with this.

I'm following this guide:
https://www.vultr.com/docs/create-a-chat-server-using-matrix-synapse-and-riot-on-centos-7

**Comment by turt2live** [comment]
Try using `http://localhost:8008` instead of `htttps://localhost:8448` (http instead of https).

Port 8448 is the federation API and generally isn't great for registration and the like.

**Comment by neilisfragile** [comment]
What @turt2live said. Closing
