### ISSUE TITLE
BAD GATEWAY when I try to join a room

### ISSUE THREAD

**Issue by bzhfloriane** [matrix-org/synapse#2957]
I'm trying to join the room #matrix-dev:matrix.org, but I get a 502 Bad Gateway error.
Here are my logs when I try to join this room:

```
2018-03-06 12:14:31,666 - synapse.access.http.8008 - 59 - INFO - GET-434- - - 8008 - Received request: GET /_matrix/client/api/v1/directory/room/%23matrix-dev%3Amatrix.org
2018-03-06 12:14:31,668 - synapse.http.outbound - 154 - INFO - GET-434- {GET-O-12} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23matrix-dev%3Amatrix.org
2018-03-06 12:14:32,797 - synapse.handlers.typing - 78 - INFO - - Checking for typing timeouts
2018-03-06 12:14:32,797 - synapse.handlers.presence - 327 - INFO - - Handling presence timeouts
2018-03-06 12:14:32,873 - synapse.storage.TIME - 213 - INFO - - Total database time: 0.004% {get_destination_retry_timings(1): 0.003%, _update_client_ips_batch(2): 0.001%, who_forgot(0): 0.000%} {}
2018-03-06 12:14:37,796 - synapse.handlers.typing - 78 - INFO - - Checking for typing timeouts
2018-03-06 12:14:37,797 - synapse.handlers.presence - 327 - INFO - - Handling presence timeouts
2018-03-06 12:14:42,795 - synapse.handlers.typing - 78 - INFO - - Checking for typing timeouts
2018-03-06 12:14:42,797 - synapse.handlers.presence - 327 - INFO - - Handling presence timeouts
2018-03-06 12:14:42,872 - synapse.storage.TIME - 213 - INFO - - Total database time: 0.001% {_update_client_ips_batch(2): 0.001%, who_forgot(0): 0.000%, update_user_directory_stream_pos(0): 0.000%} {}
2018-03-06 12:14:42,899 - synapse.http.outbound - 236 - INFO - GET-434- {GET-O-12} [matrix.org] Result: 502 Bad Gateway
2018-03-06 12:14:42,900 - root - 188 - WARNING - GET-434- Error retrieving alias
2018-03-06 12:14:42,902 - synapse.http.server - 127 - ERROR - GET-434- 502: Bad Gateway
Traceback (most recent call last):
  File "/root/.synapse/lib/python2.7/site-packages/synapse/http/server.py", line 117, in wrapped_request_handler
    yield request_handler(self, request, request_metrics)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/http/server.py", line 263, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/rest/client/v1/directory.py", line 50, in on_GET
    res = yield dir_handler.get_association(room_alias)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/handlers/directory.py", line 185, in get_association
    ignore_backoff=True,
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/federation/transport/client.py", line 188, in make_query
    ignore_backoff=ignore_backoff,
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/root/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 442, in get_json
    ignore_backoff=ignore_backoff,
  File "/root/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/root/.synapse/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 247, in _request
    response.code, response.phrase, body
HttpResponseException: 502: Bad Gateway
```

My conf of nginx is : 

```
worker_processes  1;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost;

        location /_matrix {
            proxy_pass http://localhost:8008;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
   }
}
```

Any help is appreciated..

**Comment by neilisfragile** [comment]
Hi @bzhfloriane is this issue persisting? Can you join other rooms?

**Comment by bzhfloriane** [comment]
Oui j'ai toujours ce problème. Non je ne peux joindre aucune room. Et j'essaye aussi de créer une discussion avec un autre serveur, mais cela me met ceci comme erreur : 

```
2018-03-08 17:38:47,207 - synapse.handlers.profile - 123 - ERROR - POST-793- Failed to get displayname
Traceback (most recent call last):
  File "/root/.synapse/lib/python2.7/site-packages/synapse/handlers/profile.py", line 115, in get_displayname
    ignore_backoff=True,
ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

2018-03-08 17:38:47,515 - synapse.handlers.profile - 176 - ERROR - POST-793- Failed to get avatar_url
Traceback (most recent call last):
  File "/root/.synapse/lib/python2.7/site-packages/synapse/handlers/profile.py", line 169, in get_avatar_url
    ignore_backoff=True,
ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

2018-03-08 17:38:53,261 - synapse.http.server - 145 - ERROR - POST-793- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x53777d0>: <XForwardedForRequest at 0x5ecaa70 method=POST uri=/_matrix/client/api/v1/createRoom?access_token=<redacted> clientproto=HTTP/1.1 site=8008>: Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

**Comment by iammer** [comment]
I am seeing this too.  Did you ever find a solution?

**Comment by neilisfragile** [comment]
Can't reproduce and so struggling to debug - can you send through some recent logs?

**Comment by iammer** [comment]
@neilisfragile, I believe I had figured this out.  I had misconfigured my SRV record and was pointing to the wrong port. 8448 vs 443

**Comment by Eideen** [comment]
### I have the same problem.

I get same error message `502: b'Bad Gateway'`when trying to fetch room list.


### Version information




- **Homeserver**:


`matrix-synapse-py3`



- **Version**:

0.99.3+bionic1

- **Install method**:

installed via apt






- **Platform**:


server:

- Intel(R) Pentium(R) CPU G4620 @ 3.70GHz
- 32GB DDR4 EEC
- Ubuntu 18.04.2 LTS
- Apache2 frontend  2.4.29
- Allow port 443,8448 from Anywhere
 - no limited on outbound.
- No vm or container

## config:

DNS setup
````sh
#dig SRV _matrix._tcp.<domain>
...
;; ANSWER SECTION:
_matrix._tcp.<domain>. 600     IN      SRV     10 0  443 matrix.<domain>.
....
````
Kernel info:
````sh
#uname -a
Linux <domain> 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
````
matrix-synapse config:
````yaml
pid_file: "/var/run/matrix-synapse.pid"
cpu_affinity: 0x00000008 # CPU core 4.
public_baseurl: https://matrix.<domain>/
listeners:
  - port: 8008
    tls: false
    bind_addresses: ['127.0.0.1']
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
admin_contact: 'mailto:admin@<domain>'
acme:
database:
  name: "sqlite3"
  args:
    database: "/var/lib/matrix-synapse/homeserver.db"
log_config: "/etc/matrix-synapse/log.yaml"
media_store_path: "/volum/@matrix/media"
uploads_path: "/volum/@matrix/uploads"
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '169.254.0.0/16'
  - '::1/128'
  - 'fe80::/64'
  - 'fc00::/7'
url_preview_ip_range_whitelist:
   - '192.168.2.8'
enable_registration: false
registration_shared_secret: "<key>"
default_identity_server: https://matrix.org
trusted_third_party_id_servers:
  - matrix.org
  - vector.im
auto_join_rooms:
  - "#home:matrix.<domain>"
autocreate_auto_join_rooms: true
signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
password_config:
server_notices:
  system_mxid_localpart: notices
  system_mxid_display_name: "Server Notices"
  system_mxid_avatar_url: "mxc://matrix.<domain>/<random 24 number>"
  room_name: "Server Notices"
````

apache2 config for matrix.<domain>:

````bash
<VirtualHost *:443>
      ServerName matrix.<domain>
      webmaster@localhost

      ErrorLog ${APACHE_LOG_DIR}/matrix-ssl-error.log
      CustomLog ${APACHE_LOG_DIR}/matrix-ssl-access.log combined

      SSLEngine on
      SSLCertificateKeyFile /etc/letsencrypt/live/<domain>/privkey.pem
      SSLCertificateFile /etc/letsencrypt/live/<domain>/fullchain.pem
      SSLProxyEngine on
      SSLProxyVerify none
      SSLProxyCheckPeerCN off
      SSLProxyCheckPeerName off
      SSLProxyCheckPeerExpire off
      ProxyPreserveHost On
      ProxyRequests off
      ProxyPass /_matrix http://localhost:8008/_matrix nocanon
      ProxyPassReverse /_matrix http://localhost:8008/_matrix
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
      LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common
</VirtualHost>

<VirtualHost *:80>
                ServerName matrix.<domain>
                Redirect permanent / https://matrix.<domain>
</VirtualHost>

<VirtualHost *:8448>
    SSLEngine on
    ServerName matrix.<domain>;

    ProxyPass /_matrix http://127.0.0.1:8008/_matrix nocanon
    ProxyPassReverse /_matrix http://127.0.0.1:8008/_matrix
    SSLCertificateKeyFile /etc/letsencrypt/live/<domain>/privkey.pem
    SSLCertificateFile /etc/letsencrypt/live/<domain>/fullchain.pem



    ErrorLog ${APACHE_LOG_DIR}/matrix-ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/matrix-ssl-access.log combined


</VirtualHost>
````

apache2 enabled mods:
````sh
#tree /etc/apache2/mods-enabled/
mods-enabled/
├── access_compat.load -> ../mods-available/access_compat.load
├── alias.conf -> ../mods-available/alias.conf
├── alias.load -> ../mods-available/alias.load
├── auth_basic.load -> ../mods-available/auth_basic.load
├── authn_core.load -> ../mods-available/authn_core.load
├── authn_file.load -> ../mods-available/authn_file.load
├── authz_core.load -> ../mods-available/authz_core.load
├── authz_host.load -> ../mods-available/authz_host.load
├── authz_user.load -> ../mods-available/authz_user.load
├── autoindex.conf -> ../mods-available/autoindex.conf
├── autoindex.load -> ../mods-available/autoindex.load
├── cgi.load -> ../mods-available/cgi.load
├── deflate.conf -> ../mods-available/deflate.conf
├── deflate.load -> ../mods-available/deflate.load
├── dir.conf -> ../mods-available/dir.conf
├── dir.load -> ../mods-available/dir.load
├── env.load -> ../mods-available/env.load
├── filter.load -> ../mods-available/filter.load
├── headers.load -> ../mods-available/headers.load
├── mime.conf -> ../mods-available/mime.conf
├── mime.load -> ../mods-available/mime.load
├── mpm_prefork.conf -> ../mods-available/mpm_prefork.conf
├── mpm_prefork.load -> ../mods-available/mpm_prefork.load
├── negotiation.conf -> ../mods-available/negotiation.conf
├── negotiation.load -> ../mods-available/negotiation.load
├── php7.2.conf -> ../mods-available/php7.2.conf
├── php7.2.load -> ../mods-available/php7.2.load
├── proxy.conf -> ../mods-available/proxy.conf
├── proxy_http.load -> ../mods-available/proxy_http.load
├── proxy.load -> ../mods-available/proxy.load
├── proxy_wstunnel.load -> ../mods-available/proxy_wstunnel.load
├── reqtimeout.conf -> ../mods-available/reqtimeout.conf
├── reqtimeout.load -> ../mods-available/reqtimeout.load
├── rewrite.load -> ../mods-available/rewrite.load
├── setenvif.conf -> ../mods-available/setenvif.conf
├── setenvif.load -> ../mods-available/setenvif.load
├── socache_shmcb.load -> ../mods-available/socache_shmcb.load
├── ssl.conf -> ../mods-available/ssl.conf
└── status.load -> ../mods-available/status.load
├── ssl.load -> ../mods-available/ssl.load
├── status.conf -> ../mods-available/status.conf

````


**log**:
````python
2019-04-21 16:21:13,741 - twisted - 242 - INFO - - Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=37634)
2019-04-21 16:21:13,742 - synapse.handlers.sync - 909 - INFO - GET-279- Calculating sync response for @<user>:matrix.<domain> between StreamToken(room_key='s38', presence_key='861', typing_key='0', receipt_key='1', account_data_key='24', push_rules_key='1', to_device_key='12', device_list_key='15', groups_key='1') and StreamToken(room_key='s38', presence_key=862, typing_key=0, receipt_key=1, account_data_key=24, push_rules_key=1, to_device_key=12, device_list_key=15, groups_key=1)
2019-04-21 16:21:13,747 - twisted - 242 - INFO - - Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=37746)
2019-04-21 16:21:13,748 - synapse.access.http.8008 - 302 - INFO - GET-279- 192.168.2.245 - 8008 - {@<user>:matrix.<domain>} Processed request: 30.009sec/0.002sec (0.007sec, 0.000sec) (0.000sec/0.000sec/0) 482B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_861_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.0.8 Chrome/69.0.3497.128 Electron/4.1.3 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,763 - synapse.access.http.8008 - 233 - INFO - OPTIONS-294- 192.168.2.245 - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,765 - synapse.access.http.8008 - 302 - INFO - OPTIONS-294- 192.168.2.245 - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.0.8 Chrome/69.0.3497.128 Electron/4.1.3 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,772 - synapse.access.http.8008 - 233 - INFO - GET-295- 192.168.2.245 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,774 - synapse.util.caches.response_cache - 151 - INFO - GET-295- [sync]: no cached result for [(@<user>:matrix.<domain>, 30000, 's38_862_0_1_24_1_12_15_1', '0', False, 'ZSOHCGMGHK')], calculating new one
2019-04-21 16:21:13,775 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-04-21 16:21:13,791 - synapse.handlers.sync - 909 - INFO - GET-283- Calculating sync response for @<user>:matrix.<domain> between StreamToken(room_key='s38', presence_key='861', typing_key='0', receipt_key='1', account_data_key='24', push_rules_key='1', to_device_key='12', device_list_key='15', groups_key='1') and StreamToken(room_key='s38', presence_key=862, typing_key=0, receipt_key=1, account_data_key=24, push_rules_key=1, to_device_key=12, device_list_key=15, groups_key=1)
2019-04-21 16:21:13,799 - synapse.access.http.8008 - 302 - INFO - GET-283- 192.168.2.245 - 8008 - {@<user>:matrix.<domain>} Processed request: 30.009sec/0.003sec (0.004sec, 0.000sec) (0.000sec/0.000sec/0) 480B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_861_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,800 - synapse.access.http.8008 - 302 - INFO - GET-293- 192.168.2.245 - 8008 - {@<user>:matrix.<domain>} Processed request: 9.997sec/0.002sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 480B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_861_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,801 - synapse.access.http.8008 - 302 - INFO - GET-292- 192.168.2.245 - 8008 - {@<user>:matrix.<domain>} Processed request: 10.002sec/0.004sec (0.006sec, 0.000sec) (0.000sec/0.000sec/0) 480B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_861_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,821 - synapse.access.http.8008 - 233 - INFO - OPTIONS-296- 192.168.2.245 - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,823 - synapse.access.http.8008 - 302 - INFO - OPTIONS-296- 192.168.2.245 - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,825 - synapse.access.http.8008 - 233 - INFO - OPTIONS-297- 192.168.2.245 - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,826 - synapse.access.http.8008 - 233 - INFO - OPTIONS-298- 192.168.2.245 - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,828 - synapse.access.http.8008 - 302 - INFO - OPTIONS-297- 192.168.2.245 - 8008 - {None} Processed request: 0.001sec/0.002sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,829 - synapse.access.http.8008 - 302 - INFO - OPTIONS-298- 192.168.2.245 - 8008 - {None} Processed request: 0.001sec/0.002sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1 HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36" [0 dbevts]
2019-04-21 16:21:13,831 - synapse.access.http.8008 - 233 - INFO - GET-299- 192.168.2.245 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s38_862_0_1_24_1_12_15_1
2019-04-21 16:21:13,834 - synapse.util.caches.response_cache - 151 - INFO - GET-299- [sync]: no cached result for [(@<user>:matrix.<domain>, 30000, 's38_862_0_1_24_1_12_15_1', '0', False, 'DIOLJFBNRD')], calculating new one
2019-04-21 16:21:14,824 - synapse.handlers.typing - 89 - INFO - - Checking for typing timeouts
2019-04-21 16:21:14,825 - synapse.handlers.presence - 350 - INFO - - Handling presence timeouts
2019-04-21 16:21:17,231 - synapse.access.http.8008 - 233 - INFO - OPTIONS-300- 192.168.2.245 - 8008 - Received request: OPTIONS /_matrix/client/r0/publicRooms?server=matrix.org
2019-04-21 16:21:17,232 - synapse.access.http.8008 - 302 - INFO - OPTIONS-300- 192.168.2.245 - 8008 - {None} Processed request: 0.001sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/publicRooms?server=matrix.org HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.0.8 Chrome/69.0.3497.128 Electron/4.1.3 Safari/537.36" [0 dbevts]
2019-04-21 16:21:17,233 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-04-21 16:21:17,237 - synapse.access.http.8008 - 233 - INFO - POST-301- 192.168.2.245 - 8008 - Received request: POST /_matrix/client/r0/publicRooms?server=matrix.org
2019-04-21 16:21:17,238 - synapse.util.caches.response_cache - 151 - INFO - POST-301- [remote_room_list]: no cached result for [('matrix.org', 20, None, True, None)], calculating new one
2019-04-21 16:21:17,241 - synapse.http.matrixfederationclient - 356 - INFO - POST-301- {GET-O-3} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20; timeout 60.000000s
2019-04-21 16:21:17,298 - synapse.http.federation.matrix_federation_agent - 373 - INFO - POST-301- Connecting to matrix.org.cdn.cloudflare.net:8443
2019-04-21 16:21:19,824 - synapse.handlers.typing - 89 - INFO - - Checking for typing timeouts
2019-04-21 16:21:19,825 - synapse.handlers.presence - 350 - INFO - - Handling presence timeouts
2019-04-21 16:21:19,828 - synapse.rest.media.v1.preview_url_resource - 396 - INFO - expire_url_cache_data-78- Running url preview cache expiry
2019-04-21 16:21:19,828 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-04-21 16:21:19,832 - synapse.rest.media.v1.preview_url_resource - 475 - INFO - expire_url_cache_data-78- Deleted 0 media from url cache
2019-04-21 16:21:19,839 - synapse.storage.TIME - 301 - INFO - - Total database time: 0.001% {update_presence(1): 0.001%, get_expired_url_cache(2): 0.000%, get_url_cache_media_before(2): 0.000%} {}
2019-04-21 16:21:23,607 - synapse.http.matrixfederationclient - 388 - INFO - POST-301- {GET-O-3} [matrix.org] Got response headers: 502 Bad Gateway
2019-04-21 16:21:23,608 - synapse.http.matrixfederationclient - 472 - WARNING - POST-301- {GET-O-3} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: HttpResponseException("502: b'Bad Gateway'",)
2019-04-21 16:21:23,609 - synapse.util.retryutils - 193 - INFO - POST-301- Connection to matrix.org was unsuccessful (<class 'synapse.api.errors.HttpResponseException'>(502: b'Bad Gateway')); backoff now 600000
2019-04-21 16:21:23,613 - synapse.http.server - 112 - ERROR - POST-301- Failed handle request via 'PublicRoomListRestServlet': <XForwardedForRequest at 0x7f444a8218d0 method='POST' uri='/_matrix/client/r0/publicRooms?server=matrix.org' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 365, in on_POST
    third_party_instance_id=third_party_instance_id,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 467, in get_remote_public_room_list
    third_party_instance_id=third_party_instance_id,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 348, in get_public_rooms
    ignore_backoff=True,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 703, in get_json
    timeout=timeout,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 220, in _send_request_with_optional_trailing_slash
    request, **send_request_args
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 427, in _send_request
    raise e
synapse.api.errors.HttpResponseException: 502: b'Bad Gateway'

````

**Comment by Half-Shot** [comment]
@Eideen it would be better to create a new issue rather than trying to reuse a closed one. You've already created #5086, so let's use that.
