### ISSUE TITLE
issue with matrix.org

### ISSUE THREAD

**Issue by ReK2Fernandez** [matrix-org/synapse#2994]
Issues with matrix.org
Getting a lot of similar msgs:
```
synapse.federation.federation_server - 199 - ERROR - PUT-2142- Failed to handle PDU $15209916783669230GTgsj:matrix.org
```
Also having issues with people from matrix.org seems ok with people in our node and nother indy nodes.
```
Mar 14 01:45:16 hispagatos-matrix python[8863]: 2018-03-14 01:45:16,689 - synapse.federation.federation_server - 199 - ERROR - PUT-1434- Failed to handle PDU $15209913095091HqDEb:vurpo.fi
Mar 14 01:45:16 hispagatos-matrix python[8863]: Traceback (most recent call last):
Mar 14 01:45:16 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 191, in process_pdus_for_room
Mar 14 01:45:16 hispagatos-matrix python[8863]:     transaction.origin, pdu
Mar 14 01:45:16 hispagatos-matrix python[8863]: DeferredTimedOutError: 504: Timed out
Mar 14 01:45:37 hispagatos-matrix python[8863]: 2018-03-14 01:45:37,491 - synapse.federation.transport.server - 181 - ERROR - PUT-2352- authenticate_request failed
Mar 14 01:45:37 hispagatos-matrix python[8863]: Traceback (most recent call last):
Mar 14 01:45:37 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/server.py", line 174, in new_func
Mar 14 01:45:37 hispagatos-matrix python[8863]:     origin = yield authenticator.authenticate_request(request, content)
Mar 14 01:45:37 hispagatos-matrix python[8863]: SynapseError: 401: Invalid signature for server ostez.com with key ed25519:a_GUdu
Mar 14 01:45:39 hispagatos-matrix python[8863]: 2018-03-14 01:45:39,025 - synapse.federation.federation_server - 199 - ERROR - PUT-2142- Failed to handle PDU $15209913461043226zNxqU:matrix.org
Mar 14 01:45:39 hispagatos-matrix python[8863]: Traceback (most recent call last):
Mar 14 01:45:39 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 191, in process_pdus_for_room
Mar 14 01:45:39 hispagatos-matrix python[8863]:     transaction.origin, pdu
Mar 14 01:45:39 hispagatos-matrix python[8863]: NotRetryingDestination: Not retrying server matrix.org.
Mar 14 01:45:44 hispagatos-matrix python[8863]: 2018-03-14 01:45:44,621 - synapse.federation.transport.server - 181 - ERROR - PUT-2433- authenticate_request failed
Mar 14 01:45:44 hispagatos-matrix python[8863]: Traceback (most recent call last):
Mar 14 01:45:44 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/server.py", line 174, in new_func
Mar 14 01:45:44 hispagatos-matrix python[8863]:     origin = yield authenticator.authenticate_request(request, content)
Mar 14 01:45:44 hispagatos-matrix python[8863]: SynapseError: 401: Invalid signature for server ostez.com with key ed25519:a_GUdu
```

**Comment by ReK2Fernandez** [comment]
more info:
```
Mar 14 01:47:40 hispagatos-matrix python[8863]: SynapseError: 401: Invalid signature for server musclecomm.com with key ed25519:a_WwpN
Mar 14 01:47:40 hispagatos-matrix python[8863]: 2018-03-14 01:47:40,479 - synapse.federation.transport.server - 181 - ERROR - PUT-2849- authenticate_request failed
Mar 14 01:47:40 hispagatos-matrix python[8863]: Traceback (most recent call last):
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/server.py", line 174, in new_func
Mar 14 01:47:40 hispagatos-matrix python[8863]:     origin = yield authenticator.authenticate_request(request, content)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Mar 14 01:47:40 hispagatos-matrix python[8863]:     result = result.throwExceptionIntoGenerator(g)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Mar 14 01:47:40 hispagatos-matrix python[8863]:     return g.throw(self.type, self.value, self.tb)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/server.py", line 138, in authenticate_request
Mar 14 01:47:40 hispagatos-matrix python[8863]:     yield self.keyring.verify_json_for_server(origin, json_request)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
Mar 14 01:47:40 hispagatos-matrix python[8863]:     result = result.throwExceptionIntoGenerator(g)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
Mar 14 01:47:40 hispagatos-matrix python[8863]:     return g.throw(self.type, self.value, self.tb)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/util/logcontext.py", line 316, in make_deferred_yieldable
Mar 14 01:47:40 hispagatos-matrix python[8863]:     r = yield deferred
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
Mar 14 01:47:40 hispagatos-matrix python[8863]:     result = g.send(result)
Mar 14 01:47:40 hispagatos-matrix python[8863]:   File "/usr/lib/python2.7/dist-packages/synapse/crypto/keyring.py", line 768, in _handle_key_deferred
Mar 14 01:47:40 hispagatos-matrix python[8863]:     Codes.UNAUTHORIZED,
```
not sure if this is related..
