### ISSUE TITLE
Multiple test failures 0.27.0-rc2

### ISSUE THREAD

**Issue by jhdulaney** [matrix-org/synapse#3020]
Building for Fedora 28, I get get several test failures:

https://kojipkgs.fedoraproject.org//work/tasks/4017/25864017/build.log

For example:

[FAIL]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/builddir/build/BUILD/synapse-0.27.0-rc2/tests/replication/slave/storage/test_receipts.py", line 38, in test_receipt
    ROOM_ID: EVENT_ID
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/builddir/build/BUILD/synapse-0.27.0-rc2/tests/replication/slave/storage/_base.py", line 73, in check
    self.assertEqual(slaved_result, expected_result)
  File "/usr/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 551, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 873, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: {} != {'!room:blue': '$event:blue'}
- {}
+ {'!room:blue': '$event:blue'}
tests.replication.slave.storage.test_receipts.SlavedReceiptTestCase.test_receipt

**Comment by krombel** [comment]
This is fixed by #3015
So expect it to be in the next rc or even release

**Comment by jhdulaney** [comment]
Thanks!
