### ISSUE TITLE
[Ubuntu 18.04 LTS] Will not start on 18.04, depends on broken python-cryptography

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3147]
### Description

On 18.04, ``python-cryptography`` is broken and when trying to run things like ``pip`` or synapse. They will be met with the error:

### matrix-synapse
```
Apr 28 01:36:14 Halfy-VM python[3120]: Traceback (most recent call last):
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
Apr 28 01:36:14 Halfy-VM python[3120]:     mod_name, _Error)
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
Apr 28 01:36:14 Halfy-VM python[3120]:     loader = get_loader(mod_name)
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/pkgutil.py", line 462, in get_loader
Apr 28 01:36:14 Halfy-VM python[3120]:     return find_loader(fullname)
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/pkgutil.py", line 472, in find_loader
Apr 28 01:36:14 Halfy-VM python[3120]:     for importer in iter_importers(fullname):
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/pkgutil.py", line 428, in iter_importers
Apr 28 01:36:14 Halfy-VM python[3120]:     __import__(pkg)
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/synapse/app/__init__.py", line 22, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     python_dependencies.check_requirements()
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 106, in check_requir
Apr 28 01:36:14 Halfy-VM python[3120]:     module = __import__(module_name)
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from OpenSSL import crypto, SSL
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from cryptography import x509
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from cryptography.x509.base import (
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from cryptography.x509.extensions import Extension, ExtensionType
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     from cryptography.x509.name import Name
Apr 28 01:36:14 Halfy-VM python[3120]:   File "/usr/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
Apr 28 01:36:14 Halfy-VM python[3120]:     _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
```
### pip (for comparison)
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/index.py", line 15, in <module>
    from pip._vendor import html5lib, requests, six
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py", line 86, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
```

This looks like it might be an upstream problem with Twisted, but either way it's a blocker on 18.04 to which quite a few homeowners will be moving too soon.

Either way, the only way I can get pip back to a working state is to remove ``python-cryptography`` and then obviously I won't be able to run Synapse.

### Steps to reproduce

- Create a fresh Ubuntu 18.04 install.
- Install python2.7, ``matrix-synapse``
- Try to run.
- Will not start due to the error above 

### Version information

Version: 0.28 
Deb package (from yakkety, since all the matrix repositorys are ancient :disappointed: )

python-cryptography/bionic 2.1.4-1ubuntu1.1 amd64

**Comment by Half-Shot** [comment]
Ran a plain 18.04 VM via digital ocean and it started okay, so this might be specific to my system. I'll keep this updated if I find anything.

**Comment by Half-Shot** [comment]
However, my system is still crippled. I've narrowed it down to these packages:
``matrix-synapse python-openssl python-pysaml2 python-service-identity python-twisted python-twisted-core``

**Comment by Half-Shot** [comment]
Found it: ``python-openssl`` seems to cause ``pip`` to fail, so removing it brings it back to life. Synapse obviously complains that it can't find openssl so working around that now.

**Comment by Half-Shot** [comment]
Aaaand the culprit was a very neatly hidden enum package that was taking priority over enum34. Found and removed it and now everything is going along neatly. Closing.
