### ISSUE TITLE
Worker endlessly fails with "stream X has fallen behined"

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3204]
### Description

Hi, I recently setup a synchrotron worker to help with the endlessly rubbish performance on synapse.

However, when I start the worker it connects to the various replication streams and then immediately closes them with "stream X has fallen behind". I tried this with both a long running synapse process and also starting the worker and synapse process at roughly the same time, it always thinks it has falle behind.

I followed the guide in ``workers.rst``, so let me know if I am missing something. I was running the synapse process through the regular systemd service I have. The worker process was running inside a screen session and started directly with ``python3 -m synapse.app.synchrotron``.

Logging from worker:

```
2018-05-10 13:20:45,794 - synapse.replication.tcp.client - 50 - INFO - - Connecting to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:45,795 - synapse.replication.tcp.client - 53 - INFO - - Connected to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:45,796 - synapse.replication.tcp.protocol - 147 - INFO - - [anon-SnNVe] Connection established
2018-05-10 13:20:45,797 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'groups' from 28
2018-05-10 13:20:45,797 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'account_data' from 21735
2018-05-10 13:20:45,797 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'to_device' from 36140
2018-05-10 13:20:45,797 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'backfill' from 1
2018-05-10 13:20:45,798 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'presence' from 1
2018-05-10 13:20:45,798 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'tag_account_data' from 21735
2018-05-10 13:20:45,798 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'push_rules' from 487
2018-05-10 13:20:45,798 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'public_rooms' from 231
2018-05-10 13:20:45,798 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'typing' from 11
2018-05-10 13:20:45,799 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'device_lists' from 240162
2018-05-10 13:20:45,799 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'events' from 1
2018-05-10 13:20:45,799 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-SnNVe] Subscribing to replication stream: 'receipts' from 1
2018-05-10 13:20:45,940 - synapse.replication.tcp.protocol - 290 - ERROR - - [anon-SnNVe] Remote reported error: u"failed to handle replicate: Exception('stream receipts has fallen behined',)"
2018-05-10 13:20:45,941 - synapse.replication.tcp.protocol - 314 - INFO - - [anon-SnNVe] Stop producing
2018-05-10 13:20:45,941 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-SnNVe] Connection was closed
2018-05-10 13:20:45,942 - synapse.replication.tcp.protocol - 318 - INFO - - [anon-SnNVe] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:45,942 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-SnNVe] Connection was closed
2018-05-10 13:20:45,942 - synapse.replication.tcp.client - 60 - ERROR - - Lost replication conn: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:48,442 - synapse.replication.tcp.client - 50 - INFO - - Connecting to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:48,443 - synapse.replication.tcp.client - 53 - INFO - - Connected to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:48,444 - synapse.replication.tcp.protocol - 147 - INFO - - [anon-RWqdA] Connection established
2018-05-10 13:20:48,445 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'groups' from 28
2018-05-10 13:20:48,445 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'account_data' from 21735
2018-05-10 13:20:48,445 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'to_device' from 36140
2018-05-10 13:20:48,445 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'backfill' from 1
2018-05-10 13:20:48,446 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'presence' from 1
2018-05-10 13:20:48,446 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'tag_account_data' from 21735
2018-05-10 13:20:48,446 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'push_rules' from 487
2018-05-10 13:20:48,446 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'public_rooms' from 231
2018-05-10 13:20:48,446 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'typing' from 11
2018-05-10 13:20:48,447 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'device_lists' from 240162
2018-05-10 13:20:48,447 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'events' from 1
2018-05-10 13:20:48,447 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-RWqdA] Subscribing to replication stream: 'receipts' from 1
2018-05-10 13:20:48,684 - synapse.replication.tcp.protocol - 290 - ERROR - - [anon-RWqdA] Remote reported error: u"failed to handle replicate: Exception('stream receipts has fallen behined',)"
2018-05-10 13:20:48,685 - synapse.replication.tcp.protocol - 314 - INFO - - [anon-RWqdA] Stop producing
2018-05-10 13:20:48,685 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-RWqdA] Connection was closed
2018-05-10 13:20:48,686 - synapse.replication.tcp.protocol - 318 - INFO - - [anon-RWqdA] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:48,686 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-RWqdA] Connection was closed
2018-05-10 13:20:48,686 - synapse.replication.tcp.client - 60 - ERROR - - Lost replication conn: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:51,615 - synapse.replication.tcp.client - 50 - INFO - - Connecting to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:51,617 - synapse.replication.tcp.client - 53 - INFO - - Connected to replication: IPv4Address(TCP, '127.0.0.1', 9592)
2018-05-10 13:20:51,617 - synapse.replication.tcp.protocol - 147 - INFO - - [anon-LjaMn] Connection established
2018-05-10 13:20:51,618 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'groups' from 28
2018-05-10 13:20:51,618 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'account_data' from 21735
2018-05-10 13:20:51,618 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'to_device' from 36140
2018-05-10 13:20:51,618 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'backfill' from 1
2018-05-10 13:20:51,619 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'presence' from 1
2018-05-10 13:20:51,619 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'tag_account_data' from 21735
2018-05-10 13:20:51,619 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'push_rules' from 487
2018-05-10 13:20:51,619 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'public_rooms' from 231
2018-05-10 13:20:51,619 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'typing' from 11
2018-05-10 13:20:51,620 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'device_lists' from 240162
2018-05-10 13:20:51,620 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'events' from 1
2018-05-10 13:20:51,620 - synapse.replication.tcp.protocol - 557 - INFO - - [anon-LjaMn] Subscribing to replication stream: 'receipts' from 1
2018-05-10 13:20:51,831 - synapse.replication.tcp.protocol - 290 - ERROR - - [anon-LjaMn] Remote reported error: u"failed to handle replicate: Exception('stream receipts has fallen behined',)"
2018-05-10 13:20:51,832 - synapse.replication.tcp.protocol - 314 - INFO - - [anon-LjaMn] Stop producing
2018-05-10 13:20:51,832 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-LjaMn] Connection was closed
2018-05-10 13:20:51,833 - synapse.replication.tcp.protocol - 318 - INFO - - [anon-LjaMn] Replication connection closed: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:51,833 - synapse.replication.tcp.protocol - 337 - INFO - - [anon-LjaMn] Connection was closed
2018-05-10 13:20:51,833 - synapse.replication.tcp.client - 60 - ERROR - - Lost replication conn: <twisted.python.failure.Failure twisted.internet.error.ConnectionDone: Connection was closed cleanly.>
2018-05-10 13:20:52,636 - synapse.storage.TIME - 213 - INFO - - Total database time: 0.000% {get_user_by_access_token(0): 0.000%, get_rooms_for_user_where_membership_is(0): 0.000%} {}
```

Logging from synapse:
```
2018-05-10 13:20:48,688 - synapse.replication.tcp.protocol - 452 - ERROR - - [synapse.app.synchrotron-ZJyBX] Failed to handle REPLICATE command
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/replication/tcp/protocol.py", line 429, in subscribe_to_stream
    stream_name, token,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/util/metrics.py", line 95, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/replication/tcp/streams.py", line 200, in get_updates_since
    raise Exception("stream %s has fallen behined" % (self.NAME))
Exception: stream events has fallen behined
2018-05-10 13:20:48,688 - synapse.replication.tcp.protocol - 225 - WARNING - - [synapse.app.synchrotron-ZJyBX] Closing connection
2018-05-10 13:20:48,689 - synapse.replication.tcp.protocol - 337 - INFO - - [synapse.app.synchrotron-ZJyBX] Connection was closed
2018-05-10 13:20:48,689 - synapse.util.async - 230 - INFO - - Acquired uncontended linearizer lock 'external_sync_linearizer' for key 'ZJyBX'
2018-05-10 13:20:48,690 - synapse.util.async - 237 - INFO - - Releasing linearizer lock 'external_sync_linearizer' for key 'ZJyBX'
2018-05-10 13:20:48,696 - synapse.metrics - 221 - INFO - - Collecting gc 0
2018-05-10 13:20:48,870 - synapse.replication.tcp.protocol - 452 - ERROR - - [synapse.app.synchrotron-ZJyBX] Failed to handle REPLICATE command
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/replication/tcp/protocol.py", line 429, in subscribe_to_stream
    stream_name, token,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/util/metrics.py", line 95, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/replication/tcp/streams.py", line 200, in get_updates_since
    raise Exception("stream %s has fallen behined" % (self.NAME))
Exception: stream backfill has fallen behined
```
Worker config:
```
worker_app: synapse.app.synchrotron
server_name: half-shot.uk
report_stats: False

# The replication listener on the synapse to talk to.
worker_replication_host: 127.0.0.1
worker_replication_port: 9592
worker_replication_http_port: 9593

worker_listeners:
 - type: http
   port: 8018
   resources:
     - names:
       - client

worker_daemonize: False
worker_pid_file: /var/run/synapse.synchrotron.pid
worker_log_config: /etc/matrix-synapse/workers.conf.d/synchrotron.log.cfg
```

### Version information

Server is Synapse 0.28.1.

**Comment by Half-Shot** [comment]
## Conclusion

I hadn't given the worker access to the database config file, which it failed to complain about. Sorted now.

**Comment by richvdh** [comment]
bit of a shame the worker didn't make that more obvious :/
