### ISSUE TITLE
synapse.push.httppusher WARNING - None- Failed to send badge count

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#3207]
In Synapse logs sometimes I see the long HTML code with error `Failed to send badge count`:
```
2018-05-10 19:24:02,751 - synapse.push.httppusher - 372 - WARNING - None- Failed to send badge count to @username:homeserver.org/im.vector.app.android/dQlbgaa9EjU:APA91bG4Z1qfKtooo2WKare9S02dxKv_yPmota4CtcJ6PlkLmH-h9A0tsdCi6F_RIaJjOWUkPkUYT76XIO2Jan8KQaBI9veCRCadO4yyNuQ2p1FTl4xxxDvk5X9hVIIUFz3Q2Sv_mXF
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 368, in _send_badge
    resp = yield self.http_client.post_json_get_json(self.url, d)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 200, in post_json_get_json
    raise self._exceptionFromFailedRequest(response, body)
CodeMessageException: 403: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Attention Required! | Cloudflare</title>
<meta name="captcha-bypass" id="captcha-bypass" />
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>


<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->
... [about 100 additional lines of html code] ...
```
What this error mean and why it outputs so long HTML page?

**Comment by richvdh** [comment]
It means it's failing to send a push notification via the push gateway. Apparently because Cloudflare is sending you a captcha.

**Comment by MurzNN** [comment]
This errors disappears after some time, but sometimes returns, e.g. yesterday from  2018-05-17 15:41:30,781 to 2018-05-17 15:54:23,340 - 54 records in logs with this error:
```
май 17 15:53:46 tad python[22929]: 2018-05-17 15:53:46,716 - synapse.push.httppusher - 338 - WARNING - None- Failed to push event $15265615736570hxxx:homeserver.ru to @login:homeserver.ru/im.vector.app.android/cWxI0xxx9HE:APA91bGxxxlGjIukjIdvUl-U7wHaG2vhJsH6oPTFFFVYj5ZqVAe7g81RJGeRoJR9iXxxxaC6BCQLzrwZjIkHJc6rc3ELD_AM7kwFbyGyS978GVJ_H7guCcPWdV0htA4HT9kNRxxx
май 17 15:53:50 tad python[22929]: 2018-05-17 15:53:50,320 - synapse.push.httppusher - 372 - WARNING - None- Failed to send badge count to @login:homeserver.ru/im.vector.app.android/cWxI0x3G9HE:APA91bGTz5xxxdvUl-U7wHaG2vhJsH6oPTFFFVYj5ZqVAe7g81RJGeRoJR9xxXWaC6BCQLzrwZjIkHJc6rc3ELD_AM7kwFbyGyS978GVJ_H7guCcPWdV0htA4HT9kNRxxx
```

**Comment by Half-Shot** [comment]
Just for reference I checked my HS to see if I had any failures involving the CF capture, but it looks fine my end :s
