### ISSUE TITLE
synapse_port_db fails

### ISSUE THREAD

**Issue by dvarum12** [matrix-org/synapse#3238]
### Description
I am trying to port my synapse database from sqlite to postgresql

### Steps to reproduce
I followed this guide for porting 
https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst#using-the-port-script
but when I execute `synapse_port_db` it fails after the preparing both databases.

I am not sure what is wrong, but I have attach the log from `synapse_port_db`.
[port-synapse.log](https://github.com/matrix-org/synapse/files/2016475/port-synapse.log)
```
user_directory_stream_pos: 100% (1/1)
device_max_stream_id: 100% (1/1)
appservice_stream_position: 100% (1/1)
federation_stream_position: 100% (2/2)
event_push_summary_stream_ordering: 100% (1/1)
account_data_max_stream_id: 100% (1/1)
background_updates: 100% (17/17)
2018-05-18 12:24:36,112 - synapse_port_db - 562 - ERROR - 
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 556, in run
    yield self._setup_state_group_id_seq()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/bin/synapse_port_db", line 138, in r
    *args, **kwargs
  File "/usr/bin/synapse_port_db", line 720, in r
    next_id = txn.fetchone()[0]+1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 556, in run
    yield self._setup_state_group_id_seq()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/bin/synapse_port_db", line 138, in r
    *args, **kwargs
  File "/usr/bin/synapse_port_db", line 720, in r
    next_id = txn.fetchone()[0]+1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

### Version information
- **Homeserver**: This is my own homeserver
- **Version**:  0.28.1 & 0.29.0
- **Install method**: pacman (ArchLinux)      
- **Platform**:  ArchLinux and it is not running in a container or VM

**Comment by richvdh** [comment]
has your sqlite database ever seen any traffic? I suspect this might happen when the db is "empty"

**Comment by dvarum12** [comment]
there is 300mb of data, so yes it has seen traffic

**Comment by vioBF** [comment]
I have a similar problem as the described one.

I've just set up a Debian 9 server and installed the synapse with apt-get. The version of the package is 0.31.2-1. 
After I had configured everything, I wanted to migrate the database according to the instructions given.
However, I have received the following error:

> account_data_max_stream_id: 100% (1/1)
e2e_one_time_keys_json: 100% (50/50)
2018-07-06 11:07:11,357 - synapse_port_db - 562 - ERROR -
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 556, in run
    yield self._setup_state_group_id_seq()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 307, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 298, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/bin/synapse_port_db", line 138, in r
    *args, **kwargs
  File "/usr/bin/synapse_port_db", line 720, in r
    next_id = txn.fetchone()[0]+1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

Nevertheless, I have finished the migration and it seems to work. But I'm not sure I want to use it as a production system.

**Comment by hawkowl** [comment]
If the migration worked after, I'll close this.

**Comment by lnicola** [comment]
For anyone else running into this, it will also happen if the database you're passing to `synapse_port_db` does not exist.

**Comment by DanSman** [comment]
Hi

I have the same or similar problem. 

`federation_stream_position: 100% (2/2)
2019-05-31 21:16:48,482 - synapse_port_db - 548 - ERROR - 
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 542, in run
    yield self._setup_state_group_id_seq()
  File "/usr/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/usr/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/bin/synapse_port_db", line 136, in r
    **kwargs
  File "/usr/bin/synapse_port_db", line 699, in r
    next_id = txn.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 542, in run
    yield self._setup_state_group_id_seq()
  File "/usr/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/usr/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/bin/synapse_port_db", line 136, in r
    **kwargs
  File "/usr/bin/synapse_port_db", line 699, in r
    next_id = txn.fetchone()[0] + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
`
I'm using Arch as well.

**Comment by kingwap99** [comment]
1. make sure you have at least one account in the .db, empty db not working
2. the synapse would be on starting mode while you do the transferring job.
actually please 100% follow the steps in the document.

https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst#using-the-port-script

**Comment by DanSman** [comment]
Thanks for the reply.

I just had to add the path to the database.    
Instead of:  

> synapse_port_db --sqlite-database homeserver.db.snapshot  --postgres-config homeserver-postgres.yaml
  
`synapse_port_db --sqlite-database /var/lib/synapse/homeserver.db.snapshot  --postgres-config homeserver-postgres.yaml`

Thanks again!

**Comment by Pitje1986** [comment]
Hi

I have the same or similar problem.

/etc/matrix-synapse# synapse_port_db --sqlite-database /var/lib/synapse/homeserver.db.snapshot --postgres-config homeserver-postgres.yaml
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 8, in <module>
    sys.exit(main())
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/_scripts/synapse_port_db.py", line 1217, in main
    config.parse_config_dict(hs_config, "", "")
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 721, in parse_config_dict
    self.invoke_all(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 347, in invoke_all
    res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/server.py", line 252, in read_config
    self.server_name = config["server_name"]
KeyError: 'server_name'

**Comment by DMRobertson** [comment]
@Pitje1986 this is a different problem (note how the last line of the error message is different).

Please double check that you have provided the `server_name` config value in `homeserver-postgres.yml`. If that doesn't solve your problem, try [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) for support; or, if you're sure the `port_db` script has a bug, please raise a new issue. Many thanks!
