### ISSUE TITLE
Unescaped colon in the path upsets the server

### ISSUE THREAD

**Issue by KitsuneRal** [matrix-org/synapse#3250]
Synapse seems to expect that colons be escaped in the path part of URL and throws 500 Internal Server Error upon encounter with an unescaped colon. To reproduce, try, e.g., `https://matrix.org/_matrix/client/r0/join/%23matrix-clients:lain.haus` (note that the hash is properly escaped)

Background: Qt encodes the path passed to `QUrl::setPath()` in this manner (which seems to be compliant with RFC 3986, FWIW). I can workaround it in libqmatrixclient but 500 is not a good answer anyway; so probably better fix on the server side.

**Comment by richvdh** [comment]
```
2018-05-21 09:30:09,060 - synapse.http.server - 196 - ERROR - POST-2719115 - Failed handle request synapse.http.server._async_render on <synapse.http.server.JsonResource object at 0x7fe7cd936ad0>: <XForwardedForRequest at 0x7fe6b9917cb0 method=POST uri=/_matrix/client/r0/join/%23matrix-clients:lain.haus clientproto=HTTP/1.1 site=8095>: Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "synapse/handlers/room_member.py", line 251, in update_membership
    
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "synapse/handlers/room_member.py", line 285, in _update_membership
    
exceptions.KeyError: 'sender'
```

**Comment by richvdh** [comment]
This looks like it might be an interaction with third-party invites

**Comment by richvdh** [comment]
I'd like to get rid of 500s on malformed requests. could you open a new issue giving an example request?
