### ISSUE TITLE
error join to room  !mHIzfmDaswOshUSeBd:matrix.org

### ISSUE THREAD

**Issue by progserega** [matrix-org/synapse#3266]
### Steps to reproduce

 - setup server matrix-synapse 0.28.1-1 on debian from official matrix repo.
 - join from account1 on matrix.org to !mHIzfmDaswOshUSeBd:matrix.org room (#русскоязычная:matrix.org)
- send invite to account2 (on my server) fro join to this room (#русскоязычная:matrix.org)
- in riot (android) I try join to this room.
- I got "Internal server error" in android client
- in my server log I get:
2018-05-23 09:22:22,347 - twisted - 131 - ERROR - POST-305- UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
2018-05-23 09:22:22,348 - twisted - 131 - ERROR - POST-305- Logged from file room.py, line 214

It must join to this room. Or need to rename this room (this room have not admins for this).

If you can identify any relevant log snippets from _homeserver.log_, please include
those here (please be careful to remove any personal or private data):

```
2018-05-23 09:22:22,326 - twisted - 131 - ERROR - POST-305- Traceback (most recent call last):
2018-05-23 09:22:22,327 - twisted - 131 - ERROR - POST-305-   File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
2018-05-23 09:22:22,328 - twisted - 131 - ERROR - POST-305-     if self.shouldRollover(record):
2018-05-23 09:22:22,329 - twisted - 131 - ERROR - POST-305-   File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
2018-05-23 09:22:22,330 - twisted - 131 - ERROR - POST-305-     msg = "%s\n" % self.format(record)
2018-05-23 09:22:22,331 - twisted - 131 - ERROR - POST-305-   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
2018-05-23 09:22:22,332 - twisted - 131 - ERROR - POST-305-     return fmt.format(record)
2018-05-23 09:22:22,333 - twisted - 131 - ERROR - POST-305-   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
2018-05-23 09:22:22,334 - twisted - 131 - ERROR - POST-305-     record.message = record.getMessage()
2018-05-23 09:22:22,335 - twisted - 131 - ERROR - POST-305-   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
2018-05-23 09:22:22,336 - twisted - 131 - ERROR - POST-305-     msg = msg % self.args
2018-05-23 09:22:22,337 - twisted - 131 - ERROR - POST-305- UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
2018-05-23 09:22:22,338 - twisted - 131 - ERROR - POST-305- Logged from file room.py, line 214
```

Full log at: [homeserver.log](https://github.com/matrix-org/synapse/files/2029023/homeserver.log)
### Version information

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?
This is on my server.

If not matrix.org:
- **Version**:        What version of Synapse is running? < Server: nginx/1.10.3

- **Install method**: package manager/git clone/pip      
package manager

- **Platform**:       Tell us about the environment in which your homeserver is operating
                      - distro, hardware, if it's running in a vm/container, etc.
debian 9.0

**Comment by ara4n** [comment]
thanks for the excellent bug report. the room.py which is barfing looks to be handlers/room.py choking on:

```python
            yield room_member_handler.update_membership(
                requester,
                UserID.from_string(invitee),
                room_id,
                "invite",
                ratelimit=False,
                content=content,
            )
```

The fact that the room alias is cyrillic shouldn't matter, but I'm wondering if the invitee's user ID somehow has ended up with cyrillic characters in it? (nowadays user IDs are intended primarily for machines & disambiguation and are all ASCII to avoid homoglyph attacks; displayname should be used for the human-readable name).

**Comment by progserega** [comment]
Hmm...
You tell about my ID, which try join to this room or any other ID in this room?

My id is (I was copy&past it from riot UI): 
root@im:/var/log/matrix-synapse# cat /tmp/1
@progserega:rsprim.ru
root@im:/var/log/matrix-synapse# enca /tmp/1
7bit ASCII characters

And I was join to any other rooms success from this uid.

Next, I try join to this room by it's alias:
#russian:tchncs.de
#communism:gazizova.net

I was see error in last case (try join to #communism:gazizova.net) in my server error:

    2018-05-23 15:57:14,060 - synapse.http.server - 196 - ERROR - POST-1280- Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at 0x7f7372ec3190>: <SynapseRequest at 0x7f7358161c20 method=P    __OST uri=/_matrix/client/r0/join/%23communism%3Agazizova.net? clientproto=HTTP/1.0 site=8008>: Traceback (most recent call last):
    Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.IndexError'>: list index out of range
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    --- <exception caught here> ---
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:152:handle_queue_loop
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:298:persisting_queue
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:193:f
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:455:_persist_events
    /usr/lib/python2.7/dist-packages/synapse/server.py:186:is_mine_id
    ]]
    2018-05-23 15:57:14,064 - synapse.access.http.8008 - 93 - INFO - POST-1280- 127.0.0.1 - 8008 - {@progserega:rsprim.ru} Processed request: 21234ms (863ms, 82ms) (3ms/31ms/27) 67B 500 "POST /_matrix/client/r0/join/%23communism%3Agazizov    __a.net? HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Rambox/0.5.17 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36"

**Comment by richvdh** [comment]
I think the encoding problem is a red herring here; we've done some work on this area in recent releases, and it may well be fixed in any case.

Rather, there is a problem with this room:
```
2018-05-23 09:22:22,588 - synapse.handlers.federation - 1632 - WARNING - POST-305- Rejecting $1416421138607kmdDk:matrix.org because Invalid ID: 'matrix.org'
```
That event (`$1416421138607kmdDk:matrix.org`) has a sender of `matrix.org`, which is indeed invalid (it should be an `@user:id`). 

I also note that there are no admins at all in this room.

So, this room is broken, and we need to recreate it. I'm happy to remove the aliases from matrix.org's room directory: would either of you guys like to take responsibility for creating a new `#русскоязычная:matrix.org` / `#russian:matrix.org` ?

**Comment by richvdh** [comment]
I've removed the offending aliases.

**Comment by progserega** [comment]
![error](https://user-images.githubusercontent.com/1297163/45743611-cb071280-bc3f-11e8-8bf3-c40575857a08.png)

```
    2018-09-19 19:10:41,949 - synapse.http.server - 102 - ERROR - POST-167102- Failed handle request via <function _async_render at 0x7f5c3689fc80>: <SynapseRequest at 0x7f5bd1dac488 method='POST' uri='/_matrix/client/r0/join/%23russian%3Atchncs.de?' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last)    __:
    Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.IndexError'>: list index out of range
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    --- <exception caught here> ---
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:151:handle_queue_loop
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:297:persisting_queue
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1297:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:192:f
    /usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
    /usr/lib/python2.7/dist-packages/synapse/storage/events.py:456:_persist_events
    /usr/lib/python2.7/dist-packages/synapse/server.py:197:is_mine_id
    ]]
    2018-09-19 19:10:41,959 - synapse.access.http.8008 - 131 - INFO - POST-167102- 127.0.0.1 - 8008 - {@progserega:rsprim.ru} Processed request: 30.795sec (1.937sec, 0.033sec) (0.004sec/0.026sec/22) 67B 500 "POST /_matrix/client/r0/join/%23russian%3Atchncs.de? HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537    __.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36"
```

**Comment by progserega** [comment]
not working 

ii  matrix-synapse                  0.31.2-1

**Comment by richvdh** [comment]
looks like you're trying to join #russian:tchncs.de. You'll have to talk to the tchncs.de admins about that.
