### ISSUE TITLE
Discord bridge's AS bot fails to sync with a NotImplementedError

### ISSUE THREAD

**Issue by eeeeeta** [matrix-org/synapse#3376]
### Description

When running the `adminme` tool from [matrix-appservice-discord](https://github.com/eeeeeta/matrix-appservice-discord), the tool fails with a 500 ISE on attempting to `/sync` as the AS user (the user configured as `sender_localpart` in the AS registration file).

Relevant logs:

```
2018-06-09 14:56:59,212 - synapse.access.http.8008 - 97 - INFO - GET-376- ::ffff:127.0.0.1 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=28&timeout=30000&_cacheBuster=1528552619108&access_token=<redacted>
2018-06-09 14:56:59,294 - synapse.util.caches.response_cache - 151 - INFO - GET-376- [sync]: no cached result for [(@_discord_bot:theta.eu.org, 30000, None, '28', False, None)], calculating new one
2018-06-09 14:56:59,295 - synapse.handlers.sync - 583 - INFO - GET-376- Calculating sync response for @_discord_bot:theta.eu.org
2018-06-09 14:56:59,300 - synapse.http.server - 102 - ERROR - GET-376- Failed handle request via <function _async_render at 0x7f2f66fcc938>: <SynapseRequest at 0x7f2f506ba248 method='GET' uri='/_matrix/client/r0/sync?filter=28&timeout=30000&_cacheBuster=1528552619108&access_token=<redacted>' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/site-packages/synapse/handlers/sync.py", line 214, in _wait_for_sync_for_user
    sync_config, since_token, full_state=full_state,
  File "/usr/lib/python2.7/site-packages/synapse/handlers/sync.py", line 233, in current_sync_for_user
    return self.generate_sync_result(sync_config, since_token, full_state)
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1532, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/site-packages/synapse/handlers/sync.py", line 596, in generate_sync_result
    raise NotImplementedError()
exceptions.NotImplementedError:
2018-06-09 14:56:59,305 - synapse.access.http.8008 - 131 - INFO - GET-376- ::ffff:127.0.0.1 - 8008 - {@_discord_bot:theta.eu.org} Processed request: 0.093sec (0.013sec, 0.002sec) (0.000sec/0.004sec/1) 55B 500 "GET /_matrix/client/r0/sync?filter=28&timeout=30000&_cacheBuster=1528552619108&access_token=<redacted> HTTP/1.0" "None"

```

### Steps to reproduce

- Have a running installation of [matrix-appservice-discord](https://github.com/eeeeeta/matrix-appservice-discord)
- `npm run adminme` (with appropriate parameters)
- Watch it fail

### Version information

- **Homeserver**: `matrix-synapse 0.31.1-1` from Arch Linux repositories
- **Install method**: see above
- **Platform**: Arch Linux in a VM

**Comment by turt2live** [comment]
This is expected.

See:
* https://github.com/Half-Shot/matrix-appservice-discord/issues/58
* https://github.com/matrix-org/matrix-doc/issues/1144

**Comment by eeeeeta** [comment]
Oh, alright. Thanks @turt2live for the links, anyhow!
