### ISSUE TITLE
Freeze due to "Too many open files"

### ISSUE THREAD

**Issue by pacien** [matrix-org/synapse#3392]
### Description

Synapse ~~crashes~~ freezes due to a fatal error: `exceptions.IOError: [Errno 24] Too many open files: …`.
This is somewhat similar to issue https://github.com/matrix-org/synapse/issues/1723 (closed in 2016).

### Logs

```
Jun 13 01:24:01 synapse python[24074]: 2018-06-13 01:24:01,433 - twisted - 131 - CRITICAL - - Unhandled error in Deferred:
Jun 13 01:24:01 synapse python[24074]: 2018-06-13 01:24:01,446 - twisted - 131 - CRITICAL - -
Jun 13 01:24:01 synapse python[24074]: Traceback (most recent call last):
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/synapse/metrics/metric.py", line 285, in _update_curr_values                                            
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/psutil/_common.py", line 293, in wrapper
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 1086, in memory_info
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1084, in wrapper
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1273, in memory_info
Jun 13 01:24:01 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/psutil/_pslinux.py", line 181, in open_binary
Jun 13 01:24:01 synapse python[24074]: IOError: [Errno 24] Too many open files: '/proc/24074/statm'
Jun 13 01:24:13 synapse python[24074]: 2018-06-13 01:24:13,028 - twisted - 131 - CRITICAL - - Unhandled Error
Jun 13 01:24:13 synapse python[24074]: Traceback (most recent call last):
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/synapse/app/_base.py", line 101, in run
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1199, in run
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/synapse/metrics/__init__.py", line 201, in f
Jun 13 01:24:13 synapse python[24074]: --- <exception caught here> ---
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 828, in runUntilCurrent
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/names/client.py", line 152, in maybeParseConfig
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/names/client.py", line 143, in _openFile
Jun 13 01:24:13 synapse python[24074]:   File "/usr/lib/python2.7/dist-packages/twisted/python/filepath.py", line 1014, in open
Jun 13 01:24:13 synapse python[24074]: exceptions.IOError: [Errno 24] Too many open files: '/etc/resolv.conf'
```

### Version information

```
0.31.1-1 (/var/lib/apt/lists/matrix.org_packages_debian_dists_stretch_main_binary-amd64_Packages)
```

**Comment by richvdh** [comment]
sounds like a dup of #2800?

**Comment by neilisfragile** [comment]
closing as dupe
