### ISSUE TITLE
Unhandled error in deferred: SortedDict.itervalues() is not implemented

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3445]
This popped up in the log for t2bot.io. Unknown cause and unknown impact. Synapse 0.31.2
```
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/send_queue.py", line 109, in _clear_queue
    self._clear_queue_before_pos(position_to_delete)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/send_queue.py", line 122, in _clear_queue_before_pos
    for uids in itervalues(self.presence_changed)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/six.py", line 602, in itervalues
    return d.itervalues(**kw)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/sortedcontainers/sorteddict.py", line 370, in method
    raise AttributeError(message)
AttributeError: SortedDict.itervalues() is not implemented. Use SortedDict.values() instead.
```

**Comment by turt2live** [comment]
Impact is presence to the outside world is affected, sometimes wrong. Doesn't appear to affect inbound PDUs. Would be nice to have it fixed, given it shows up more frequently than it did a month ago.

**Comment by turt2live** [comment]
PR looks to fix the right area - closing assuming fixed
