### ISSUE TITLE
Error when i invite unregistered users

### ISSUE THREAD

**Issue by vandsten** [matrix-org/synapse#3509]
Good Morning,

I have implementing private matrix homeserver with synapse. Features:
- SO: Debian 8
- Binary package repo debian matrix
- Version: 0.31.2-1
- Riot Web and riot-android
- Users LDAP
- No federated matrix (private)
- Email notifications enable.

Problem:
When i invite unregistered users by email with riot-web or riot-android fail create room.

Log output:
```
2018-07-11 09:05:26,705 - synapse.access.http.8008 - 97 - INFO - OPTIONS-716- None - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s378_8504_0_219_343_1_3_72_2
2018-07-11 09:05:26,705 - synapse.access.http.8008 - 131 - INFO - OPTIONS-716- None - 8008 - {None} Processed request: 0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s378_8504_0_219_343_1_3_72_2 HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36"
2018-07-11 09:05:26,707 - synapse.http.client - 108 - INFO - POST-702- Received response to  GET https://HOSTNAMESERVERMATRIX/_matrix/identity/api/v1/lookup?medium=email&address=jacintovera77%40gmail.com: 404
2018-07-11 09:05:26,708 - synapse.http.server - 102 - ERROR - POST-702- Failed handle request via <function _async_render at 0x7f8aec774848>: <SynapseRequest at 0x7f8ae4525d40 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.1' site=8008>: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 79, in wrapped_request_handler
    yield h(self, request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 305, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 68, in on_POST
    requester, self.get_room_config(request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/room.py", line 252, in create_room
    txn_id=None,
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 617, in do_3pid_invite
    id_server, medium, address
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/room_member.py", line 657, in _lookup_3pid
    "address": address,
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 218, in get_json
    raise self._exceptionFromFailedRequest(e.code, e.msg)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 318, in _exceptionFromFailedRequest
    return CodeMessageException(response.code, body)
exceptions.AttributeError: 'int' object has no attribute 'code'
2018-07-11 09:05:26,710 - synapse.access.http.8008 - 131 - INFO - POST-702- None - 8008 - {@IDUSER:HOSTNAMESERVER} Processed request: 0.507sec (0.012sec, 0.000sec) (0.009sec/0.117sec/31) 67B 500 "POST /_matrix/client/r0/createRoom HTTP/1.1" "Riot.im/0.8.12 (Linux; U; Android 7.1.1; Aquaris U Build/NMF26; Flavour GooglePlay; MatrixAndroidSDK 0.9.6)"
```
I have changed hostname server matrix and id user.

Thanks

**Comment by jacintovera** [comment]
Good Morning,

We have updated versions.
* Matrix-synapse: 0.33.0-1
* Riot Web: 0.15.7 

Same problem!

**Comment by lephisto** [comment]
Suffering from the same.. 

- synapse 0.34.0.1

**Comment by richvdh** [comment]
I think this has been fixed. If not, please could you share a log with an updated stacktrace: this code has been rewritten.
