### ISSUE TITLE
Doesn't work anymore, worked 2 minutes before

### ISSUE THREAD

**Issue by 6GVp8WcnM9TPDBrw** [matrix-org/synapse#3516]
### Description

I restarted, to change the max possible size of uploaded file, since then I can't restart the server, I can't even create a new one

When I try to create the setting file for exemple (python -m synapse.app.homeserver --server-name XXXXX --config-path homeserver.yaml --generate-config --report-stats=no)

It give me the error : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/usr/lib/python2.7/dist-packages/synapse/app/__init__.py", line 22, in <module>
    python_dependencies.check_requirements()
  File "/usr/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 124, in check_requirements
    module = __import__(module_name)
  File "/usr/lib/python2.7/dist-packages/service_identity/__init__.py", line 7, in <module>
    from . import pyopenssl
  File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 14, in <module>
    from .exceptions import SubjectAltNameWarning
  File "/usr/lib/python2.7/dist-packages/service_identity/exceptions.py", line 21, in <module>
    @attr.s
AttributeError: 'module' object has no attribute 's'

I have no idea what is different that before

I tried to reinstall completely, same problem.

### Steps to reproduce

No idea

### Version information

Debian Repository

**Comment by 6GVp8WcnM9TPDBrw** [comment]
Ok I finally managed to make it works again... I reinstalled, using the source and the virtualenv, worked perfectly, I managed to restore my server.

Something is wrong with my python "normal" install I guess...

Well at least it's fixed now... It just took me 2 hours
