### ISSUE TITLE
Syncrotron worker fail

### ISSUE THREAD

**Issue by jacintovera** [matrix-org/synapse#3517]
### Description

We would like horizontal scaling for synapse. We have one virtual machine private synapse running almost without problems.
We have found this url where it expain this:
https://github.com/matrix-org/synapse/blob/master/docs/workers.rst
 
But we have many problems when we configure workers with syncrotron. Our idea is add several virtual machines and then load balance with haproxy among them. Is it possible?

### Steps to reproduce
We have created second virtualmachine, and cloning actual private synapse server. We add listeners to /etc/matrix-synapse/homeserver.yaml and restarting "systemctl restart matrix-synapse" up new ports without problem.

Then we add new configuration file /etc/matrix-synapse/conf.d/syncrotron.yaml with next content:
```
worker_app: synapse.app.synchrotron
server_name: matrix.example.com
report_stats: false

worker_replication_host: 127.0.0.1
worker_replication_port: 9092
worker_replication_http_port: 9093

worker_listeners:
 - type: http
   port: 8083
   resources:
     - names:
       - client

worker_daemonize: True
worker_pid_file: /var/lib/matrix-synapse/synchrotron.pid
worker_log_config: /var/log/matrix-synapse/synchrotron_log_config.yaml
```
Then we restart service with "systemctl restart matrix-synapse" but no start synapse service.
Log output is next (/var/log/matrix-synapse/homeserver.log):
```
2018-07-12 09:36:40,332 - twisted - 131 - ERROR - - Traceback (most recent call last):
2018-07-12 09:36:40,333 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
2018-07-12 09:36:40,333 - twisted - 131 - ERROR - -     "__main__", fname, loader, pkg_name)
2018-07-12 09:36:40,334 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
2018-07-12 09:36:40,335 - twisted - 131 - ERROR - -     exec code in run_globals
2018-07-12 09:36:40,336 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 537, in <module>
2018-07-12 09:36:40,336 - twisted - 131 - ERROR - -     main()
2018-07-12 09:36:40,337 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 532, in main
2018-07-12 09:36:40,338 - twisted - 131 - ERROR - -     hs = setup(sys.argv[1:])
2018-07-12 09:36:40,339 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 361, in setup
2018-07-12 09:36:40,339 - twisted - 131 - ERROR - -     hs.start_listening()
2018-07-12 09:36:40,340 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 243, in start_listening
2018-07-12 09:36:40,341 - twisted - 131 - ERROR - -     self._listener_http(config, listener)
2018-07-12 09:36:40,342 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 113, in _listener_http
2018-07-12 09:36:40,342 - twisted - 131 - ERROR - -     config, name, res.get("compress", False),
2018-07-12 09:36:40,343 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 173, in _configure_named_resource
2018-07-12 09:36:40,344 - twisted - 131 - ERROR - -     client_resource = ClientRestResource(self)
2018-07-12 09:36:40,345 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/rest/__init__.py", line 66, in __init__
2018-07-12 09:36:40,345 - twisted - 131 - ERROR - -     self.register_servlets(self, hs)
2018-07-12 09:36:40,346 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/rest/__init__.py", line 73, in register_servlets
2018-07-12 09:36:40,347 - twisted - 131 - ERROR - -     room.register_servlets(hs, client_resource)
2018-07-12 09:36:40,347 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 833, in register_servlets
2018-07-12 09:36:40,348 - twisted - 131 - ERROR - -     RoomTypingRestServlet(hs).register(http_server)
2018-07-12 09:36:40,349 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/rest/client/v1/room.py", line 714, in __init__
2018-07-12 09:36:40,350 - twisted - 131 - ERROR - -     self.presence_handler = hs.get_presence_handler()
2018-07-12 09:36:40,350 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/server.py", line 449, in _get
2018-07-12 09:36:40,351 - twisted - 131 - ERROR - -     dep = builder()
2018-07-12 09:36:40,352 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/server.py", line 249, in build_presence_handler
2018-07-12 09:36:40,352 - twisted - 131 - ERROR - -     return PresenceHandler(self)
2018-07-12 09:36:40,353 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/handlers/presence.py", line 105, in __init__
2018-07-12 09:36:40,354 - twisted - 131 - ERROR - -     self.federation = hs.get_federation_sender()
2018-07-12 09:36:40,354 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/server.py", line 449, in _get
2018-07-12 09:36:40,355 - twisted - 131 - ERROR - -     dep = builder()
2018-07-12 09:36:40,356 - twisted - 131 - ERROR - -   File "/usr/lib/python2.7/dist-packages/synapse/server.py", line 368, in build_federation_sender
2018-07-12 09:36:40,357 - twisted - 131 - ERROR - -     raise Exception("Workers cannot send federation traffic")
2018-07-12 09:36:40,357 - twisted - 131 - ERROR - - Exception: Workers cannot send federation traffic
```
Maybe we have misunderstood the documentation

### Version information
If not matrix.org:
- **Version**:       Synapse/0.31.2
- **Install method**: package manager /deb
- **Platform**:       Debian 8, virtual machine, with external server postgresql 9.6

**Comment by neilisfragile** [comment]
The best place to get support for this query is #synapse-dev:matrix.org
