### ISSUE TITLE
Failed to handle PDU: local variable 'context' referenced before assignment

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3522]
On synapse v0.32.0 I sometimes see:
```
2018-07-12 15:57:17,752 - synapse.federation.federation_server - 194 - ERROR - PUT-622100- Failed to handle PDU $1531402580121103NaleC:matrix.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 186, in process_pdus_for_room
    transaction.origin, pdu
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 604, in _handle_received_pdu
    origin, pdu, get_missing=True, sent_to_us_directly=True,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 210, in on_receive_pdu
    origin, pdu, prevs, min_depth
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 363, in _get_missing_events_for_pdu
    get_missing=False
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 287, in on_receive_pdu
    auth_chain=auth_chain,
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/handlers/federation.py", line 486, in _process_received_pdu
    prev_state_id = context.prev_state_ids.get(
UnboundLocalError: local variable 'context' referenced before assignment
```

**Comment by richvdh** [comment]
pretty sure this got fixed.
