### ISSUE TITLE
Problem enabling metrics: got an unexpected keyword argument 'registry'

### ISSUE THREAD

**Issue by szimszon** [matrix-org/synapse#3566]
### Description

Problem enabling metrics.
I got:

```
 2018-07-19 19:45:40,741 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):       
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner                                                           
     self.run()                                                     
   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)                                  
   File "/usr/lib/python2.7/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
     task()                                                                               
   File "/usr/lib/python2.7/dist-packages/twisted/_threads/_team.py", line 190, in doWork
     task()                                             
 --- <exception caught here> ---                             
   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
     result = inContext.theWork()                                            
   File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>           
     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
     return self.currentContext().callWithContext(ctx, func, *args, **kw)
   File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext                                                                return func(*args,**kw)                                           
 exceptions.TypeError: start_http_server() got an unexpected keyword argument 'registry'      
```

### Steps to reproduce

Change the settings in the homeserver.yaml:

```
enable_metrics: True
...
listeners:
...
  - port: 9999
    bind_address: '0.0.0.0'
    type: metrics
```

Restart matrix-synapse.

### Version information

If not matrix.org:
- **Version**:        Server /usr/lib/python2.7/dist-packages/synapse/app/homeserver.py version 0.33.0 
- **Install method**: package manager      
- **Platform**:       Debian Stretch

**Comment by richvdh** [comment]
assuming this is no longer a problem. let us know if it is.
