### ISSUE TITLE
"Could not find event" in federation_sender

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3617]
This is on t2bot.io running this: https://github.com/turt2live/synapse/commits/travis/t2bot.io

The following error brought federation from t2bot.io -> matrix.org to a crawl, with the error repeated a few times a minute.

```
federation_sender - 2018-07-26 21:27:48,334 - synapse.federation.transaction_queue - 335 - ERROR - - Error sending presence states to servers
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 333, in send_presence
    yield self._process_presence_inner(list(states_map.values()))
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/util/metrics.py", line 55, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 348, in _process_presence_inner
    hosts_and_states = yield get_interested_remotes(self.store, states, self.state)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/presence.py", line 1314, in get_interested_remotes
    hosts = yield state_handler.get_current_hosts_in_room(room_id)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/state.py", line 182, in get_current_hosts_in_room
    joined_hosts = yield self.store.get_joined_hosts(room_id, entry)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/roommember.py", line 456, in _get_joined_hosts
    joined_hosts = yield cache.get_destinations(state_entry)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/roommember.py", line 717, in get_destinations
    event = yield self.store.get_event(event_id)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/events_worker.py", line 104, in get_event
    raise SynapseError(404, "Could not find event %s" % (event_id,))
SynapseError: 404: Could not find event $redacted:matrix.org
```

A restart of the federation_sender did not work: the federation sender failed to re-establish connection with the master process. However, restarting the whole thing appears to have fixed it.

**Comment by turt2live** [comment]
I'm seeing this again, and it's effectively killed federation. The event exists in the database and is a leave event from matrix.org, albeit a very old one. Interestingly, it's the same event as last time this happened too :/

Modern stacktrace:
```
federation_sender_1 - 2018-09-07 22:39:08,514 - synapse.federation.transaction_queue - 344 - ERROR - replication-RDATA-federation-123693- Error sending presence states to servers
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 342, in send_presence
    yield self._process_presence_inner(list(states_map.values()))
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/util/metrics.py", line 55, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/federation/transaction_queue.py", line 357, in _process_presence_inner
    hosts_and_states = yield get_interested_remotes(self.store, states, self.state)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/handlers/presence.py", line 1331, in get_interested_remotes
    hosts = yield state_handler.get_current_hosts_in_room(room_id)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/state.py", line 182, in get_current_hosts_in_room
    joined_hosts = yield self.store.get_joined_hosts(room_id, entry)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/roommember.py", line 456, in _get_joined_hosts
    joined_hosts = yield cache.get_destinations(state_entry)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/roommember.py", line 717, in get_destinations
    event = yield self.store.get_event(event_id)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/events_worker.py", line 113, in get_event
    raise NotFoundError("Could not find event %s" % (event_id,))
NotFoundError: 404: Could not find event $redacted:matrix.org
```

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/5157 instead of tracking year old stack traces. The problems here are not entirely the same as those described in https://github.com/matrix-org/synapse/issues/5157
