### ISSUE TITLE
Context for new extremity event has no state group

### ISSUE THREAD

**Issue by tleydxdy** [matrix-org/synapse#3651]
### Description

Setting the error below for many events constantly.

### Steps to reproduce

Error log:
```
2018-08-05 18:31:19,665 - synapse.federation.federation_server - 190 - ERROR - PUT-364503- Failed to handle PDU $15335082751004kkyOw:disroot.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 182, in process_pdus_for_room
    transaction.origin, pdu
FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.Exception'>: Context for new extremity event $15327592651049172ywZab:matrix.org has no state group
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:426:_persist_events
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1445:unwindGenerator
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:548:_get_new_state_after_events
]]
2018-08-05 18:31:21,110 - synapse.federation.federation_server - 190 - ERROR - PUT-364509- Failed to handle PDU $1533508276176414QUrTN:matrix.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 182, in process_pdus_for_room
    transaction.origin, pdu
FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.Exception'>: Context for new extremity event $15327592651049172ywZab:matrix.org has no state group
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:426:_persist_events
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1445:unwindGenerator
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:548:_get_new_state_after_events
]]
2018-08-05 18:34:30,246 - synapse.federation.federation_server - 190 - ERROR - PUT-365101- Failed to handle PDU $1533508424527556VwJGS:matrix.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/federation/federation_server.py", line 182, in process_pdus_for_room
    transaction.origin, pdu
FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.Exception'>: Context for new extremity event $15330740255368938YKNAL:matrix.org has no state group
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1355:gotResult
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:426:_persist_events
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1445:unwindGenerator
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1299:_inlineCallbacks
/usr/lib/python2.7/dist-packages/synapse/storage/events.py:548:_get_new_state_after_events
]]
```

<!-- If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly. -->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?
Don't know

If not matrix.org:
- **Version**:        0.33.1 <!-- 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Install method**: apt  
- **Platform**:       Debian 9 VM

**Comment by richvdh** [comment]
is this still an issue?

**Comment by tleydxdy** [comment]
I have since started a new server, and I didn't encounter it for a long while anyways. probably stale at this point
