### ISSUE TITLE
URL previews not showing - Resulting in error: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by Zjemm** [matrix-org/synapse#3728]
For urls posted in rooms the URL preview feature does not work. It does not show the preview.
looking in the log's the previews result in the following:

example:
`2018-08-21 11:42:31,728 - synapse.http.server - 98 - ERROR - GET-4397- Failed handle request via <function _async_render_GET at 0x7f7402160140>: <XForwardedForRequest at 0x7f73f83b4d88 method='GET' uri='/_matrix/media/r0/preview_url?url=https%3A%2F%2Fwww.nu.nl%2Fbinnenland%2F5422781%2Fvan-weijden-haalt-met-zwemtocht-ruim-25-miljoen-euro-kwf.html&ts=1534844551112' clientproto='HTTP/1.0' site=8448>: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 459, in callback
self._startRunCallbacks(result)
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
self._runCallbacks()
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
result = g.send(result)
File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 227, in _do_preview
og = decode_and_calc_og(body, media_info['uri'], encoding)
File "/usr/lib/python2.7/dist-packages/synapse/rest/media/v1/preview_url_resource.py", line 471, in decode_and_calc_og
from lxml import etree
exceptions.ImportError: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf`

this is on debian testing with synapse installed via the dep-package

the url previews on the matrix.org server works without a problem, so i asked another matrix member with a homeserver setup to test, and he has the same issue.

Is this a python problem or a synapse problem?
how to troubleshoot from here?

**Comment by richvdh** [comment]
*please* read the issue template.

**Comment by Zjemm** [comment]
edited as requested

**Comment by richvdh** [comment]
> edited as requested

Thanks. Any suggestions how we can word it so that people use triple-backticks for their log samples?

**Comment by richvdh** [comment]
In relation to your problem:

```
exceptions.ImportError: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf
```

This suggests whatever provides `/usr/local/lib/python2.7/dist-packages/lxml/etree.so` (it's not one of our packages, afaik) has been built against the wrong version of python.

**Comment by Zjemm** [comment]
i'm running debian testing and have installed the provided dep package: python-lxml version (4.2.3-1)
also python3-lxml is installed. so both python2.7 and 3 are available.
these are packaged by debian so i assume the are correct?

**Comment by richvdh** [comment]
that's a big assumption.

Also, debian doesn't normally package things into /usr/local/lib. I'd say that file has come from somewhere else.

**Comment by Zjemm** [comment]
well i find that very weird as this is a container purely for synapse, and all software is installed using apt.
that's why i assume that :)

but what would be best to do according to you to get the right lxml ?

**Comment by richvdh** [comment]
ohh, did you install lxml with pip?

The best solution would be to not have done that. However, having done so, `pip install --force-reinstall lxml` might fix it.

**Comment by richvdh** [comment]
I suspect you've been bitten by https://github.com/matrix-org/synapse/issues/3743; sorry.

**Comment by Zjemm** [comment]
so what is recommended then.....
using apt to install synapse doesnt install lxml so it seems.

would i use pip or apt to install lxml ?

**Comment by richvdh** [comment]
`apt-get python-lxml`. It's now (since 0.33.3-2) recommended by our synapse packages so you may get it autmatically.

**Comment by Zjemm** [comment]
ok thnx
