### ISSUE TITLE
 502: Bad Gateway when trying to connect to other home servers

### ISSUE THREAD

**Issue by l1f** [matrix-org/synapse#3729]
### Description

Whenever I try to connect to another home server I get the error "#riot:matrix.org is currently inaccessible", I find this in the error log: 

2018-08-21 13:49:35,221 - synapse.http.server - 98 - ERROR - GET-191 - Failed handle request via <function _async_render at 0x7f240e476848>: <SynapseRequest at 0x7f23f2a81050 method='GET' uri='/_matrix/client/r0/directory/room/%23riot%3Amatrix.org?' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/opt/synapse/lib/python2.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    yield h(self, request)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/http/server.py", line 313, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/rest/client/v1/directory.py", line 49, in on_GET
    res = yield dir_handler.get_association(room_alias)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/handlers/directory.py", line 187, in get_association
    ignore_backoff=True,
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/federation/transport/client.py", line 191, in make_query
    ignore_backoff=ignore_backoff,
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 486, in get_json
    ignore_backoff=ignore_backoff,
  File "/opt/synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/synapse/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 257, in _request
    response.code, response.phrase, body
synapse.api.errors.HttpResponseException: 502: Bad Gateway

### Steps to reproduce

- Install Matrix-Synapse on a CentOS Host
- Open Riot und try to connect to #riot:matrix.org

I shall not receive a Bad Gateway. So that I can join the room on Matrix.org

<!-- If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly. -->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:  The installed version is the latest one from the master of this repo. I don't know exactly which one that is, curl .. only returns nginx <!--
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Install method**: git clone      
- **Platform**: This is a centos with 8 GB Ram and four cores, in a VM

**Comment by l1f** [comment]
Sorry, guys, I was overlookin' something in the docs.

**Comment by turt2live** [comment]
Which part was missed? Knowing which parts might need some work are important, and having an explanation here can help future people potentially solve their problems.

**Comment by xgodon** [comment]
@l1f could you explain what you did?

**Comment by yousefamar** [comment]
https://xkcd.com/979/
