### ISSUE TITLE
Running "generate" on synapse 0.33.3 fails since pysaml2 4.6.0 release on pypi

### ISSUE THREAD

**Issue by karthanistyr** [matrix-org/synapse#3742]
### Description
Running "generate" (to generate the config file) on a built-from-source synapse 0.33.3 started failing in my docker image since the upgrading of `pysaml2` (4.6.0) on pypi, on the 9th of August, 2018 (https://pypi.org/project/pysaml2/4.6.0/#history).

### Steps to reproduce

- Build synapse from source in docker environment (https://github.com/karthanistyr/matrix-synapse-docker).
```
$ git clone https://github.com/karthanistyr/matrix-synapse-docker
$ cd matrix-synapse-docker
$ docker build --build-arg SYNAPSE_VERSION=v0.33.3 --build-arg SERVER_NAME=MYDOMAIN.TLD -t karthanistyr/matrix-synapse:0.33.3 .
```
- The dockerfile reaches a step to generate a config file, and `docker build` dies.

When `pip` updates the synapse dependencies, it finds a recently updated `pysaml2` (4.6.0) on pypi and proceeds to install it.
At the step to generate a config file, it fails to load `saml2` because of a problem locating pkg_resources. This is a new behaviour from `pysaml2` to try and load pkg_resources, so I'm a bit at a loss as to why this happens (`setuptools` are being upgraded as part of the same process, earlier than this step).

Relevant error:
```
ERROR:root:Can't import 'saml2' which is part of 'pysaml2>=3.0.0'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synapse/python_dependencies.py", line 124, in check_requirements
    module = __import__(module_name)
  File "/usr/lib/python2.7/site-packages/saml2/__init__.py", line 24, in <module>
    import saml2.version
  File "/usr/lib/python2.7/site-packages/saml2/version.py", line 1, in <module>
    import pkg_resources as _pkg_resources
ImportError: No module named pkg_resources
```

Full trace of both building against pysaml2 4.5.0 and against pysaml2 4.6.0: https://gist.github.com/karthanistyr/9c04ee4cbcc53113d95d2d8cd7ab8d7e

### Version information
- **Homeserver**: It's a custom Dockerfile that builds according to the instructions provided here (git install): [synapse/blob/master/UPGRADE.rst](https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst)

If not matrix.org:
- **Version**: building version 0.33.3, but other versions previously successfully built now fail to run `generate` due to the updated pysaml2
- **Install method**: git clone, then `pip install`
- **Platform**: docker image, based on alpine 3.8

**Comment by karthanistyr** [comment]
Turns out I was being an idiot and was uninstalling `py2-pip` during the course of the build, which effectively deletes setuptools and pkg_resources... :-1:
