### ISSUE TITLE
Made perspectives.servers empty and it blew up.

### ISSUE THREAD

**Issue by oliverjanik** [matrix-org/synapse#3767]
```
$ /usr/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 580, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 575, in main
    hs = setup(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 321, in setup
    config_options,
  File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 341, in load_or_generate_config
    generate_keys=generate_keys,
  File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 385, in read_config_files
    self.invoke_all("read_config", config)
  File "/usr/lib/python2.7/dist-packages/synapse/config/_base.py", line 165, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/usr/lib/python2.7/dist-packages/synapse/config/key.py", line 49, in read_config
    config["perspectives"]
  File "/usr/lib/python2.7/dist-packages/synapse/config/key.py", line 121, in read_perspectives
    for server_name, server_config in perspectives_config["servers"].items():
```

Relevant section from the config:
```
# The trusted servers to download signing keys from.
perspectives:
  servers: []
```

- What are perspectives? 
- Why does my server need to download signing keys from somewhere?
- Is homeserver.yaml documented somewhere in its entirety? 

This section is confusing because I want my server to be completely standalone and not talk to any other server sor I removed matrix.org from this section in to config.

**Comment by richvdh** [comment]
looks like you've cut out the exception message?

**Comment by oliverjanik** [comment]
Don't think so, but I managed to resolve this by commenting out the `perspectives` node in the config YAML
