### ISSUE TITLE
Prosgresql Host variable with localhost produce an error

### ISSUE THREAD

**Issue by maitrenageur** [matrix-org/synapse#3773]
### Description

The Synapse-Configuration with postgresql and the allocation of the "Host" variable to localhost will produce this errors (interesting is the last line):

~~~~
synapse.app.homeserver - 356 - INFO - None - Preparing database: psycopg2...
584 - twisted - 131 - ERROR -  - Traceback (most recent call last):
584 - twisted - 131 - ERROR -  -   File "/package/host/localhost/python-2.7.15/lib/python2.7/runpy.py", line 174, in _run_module_as_main
585 - twisted - 131 - ERROR -  -     "__main__", fname, loader, pkg_name)
585 - twisted - 131 - ERROR -  -   File "/package/host/localhost/python-2.7.15/lib/python2.7/runpy.py", line 72, in _run_code
586 - twisted - 131 - ERROR -  -     exec code in run_globals
586 - twisted - 131 - ERROR -  -   File "/projekte/synapse/venv/lib/python2.7/site-packages/synapse/app/homeserver.py", line 581, in <module>
587 - twisted - 131 - ERROR -  -     main()
587 - twisted - 131 - ERROR -  -   File "/projekte/synapse/venv/lib/python2.7/site-packages/synapse/app/homeserver.py", line 576, in main
588 - twisted - 131 - ERROR -  -     hs = setup(sys.argv[1:])
588 - twisted - 131 - ERROR -  -   File "/projekte/synapse/venv/lib/python2.7/site-packages/synapse/app/homeserver.py", line 359, in setup
589 - twisted - 131 - ERROR -  -     db_conn = hs.get_db_conn(run_new_connection=False)
589 - twisted - 131 - ERROR -  -   File "/projekte/synapse/venv/lib/python2.7/site-packages/synapse/server.py", line 364, in get_db_conn
589 - twisted - 131 - ERROR -  -     db_conn = self.database_engine.module.connect(**db_params)
590 - twisted - 131 - ERROR -  -   File "/projekte/synapse/venv/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
590 - twisted - 131 - ERROR -  -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
591 - twisted - 131 - ERROR -  - psycopg2.OperationalError: could not translate host name "localhost:12345" to address: Name or service not known
~~~~
### Steps to reproduce

A switch to a Unix Domain Socket for the Host variable is still running. If I switch back to localhost and port I get the same error like above.

### Version information

Synapse 0.33.3

**Comment by turt2live** [comment]
The port needs to specified separately, like so:

```
host: localhost
port: 12345
```

**Comment by maitrenageur** [comment]
LOL,
This was the fastest help in my life, thank you very much.
