### ISSUE TITLE
Missing Requirement: Can't import 'service_identity' which is part of 'service_identity>=1.0.0'

### ISSUE THREAD

**Issue by ssbarnea** [matrix-org/synapse#3809]
### Description

Installing official [Debian distribution](https://www.howtoforge.com/tutorial/how-to-install-matrix-synapse-on-ubuntu-1804/) fails to start service due to

```
-- Unit matrix-synapse.service has begun starting up.
Sep 06 15:17:01 smini python[24474]: ERROR:root:Can't import 'service_identity' which is part of 'service_identity>=1.0.0'
Sep 06 15:17:01 smini python[24474]: Traceback (most recent call last):
Sep 06 15:17:01 smini python[24474]:   File "/usr/lib/python2.7/dist-packages/synapse/python_dependencies.py", line 124, in check_requirements
Sep 06 15:17:01 smini python[24474]:     module = __import__(module_name)
Sep 06 15:17:01 smini python[24474]:   File "/usr/lib/python2.7/dist-packages/service_identity/__init__.py", line 7, in <module>
Sep 06 15:17:01 smini python[24474]:     from . import pyopenssl
Sep 06 15:17:01 smini python[24474]:   File "/usr/lib/python2.7/dist-packages/service_identity/pyopenssl.py", line 12, in <module>
Sep 06 15:17:01 smini python[24474]:     from pyasn1_modules.rfc2459 import GeneralNames
Sep 06 15:17:01 smini python[24474]:   File "/usr/lib/python2.7/dist-packages/pyasn1_modules/rfc2459.py", line 20, in <module>
Sep 06 15:17:01 smini python[24474]:     from pyasn1.type import opentype
Sep 06 15:17:01 smini python[24474]: ImportError: cannot import name opentype
Sep 06 15:17:01 smini python[24474]: Missing Requirement: Can't import 'service_identity' which is part of 'service_identity>=1.0.0'
Sep 06 15:17:01 smini python[24474]: To install run:
Sep 06 15:17:01 smini python[24474]:     pip install --upgrade --force "service_identity>=1.0.0"
Sep 06 15:17:01 smini systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Sep 06 15:17:01 smini systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Sep 06 15:17:01 smini systemd[1]: Failed to start Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has failed
```

```
cat /etc/debian_version
buster/sid

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
Attempting to installing missing dependencies (should have none) also fails:
```
pip install --upgrade --force "service_identity>=1.0.0"
Collecting service_identity>=1.0.0
  Using cached https://files.pythonhosted.org/packages/29/fa/995e364220979e577e7ca232440961db0bf996b6edaf586a7d1bd14d81f1/service_identity-17.0.0-py2.py3-none-any.whl
Collecting pyopenssl>=0.12 (from service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Collecting pyasn1 (from service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting attrs (from service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting six>=1.5.2 (from pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting cryptography>=2.2.1 (from pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/87/e6/915a482dbfef98bbdce6be1e31825f591fc67038d4ee09864c1d2c3db371/cryptography-2.3.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.1 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/14/dd/3e7a1e1280e7d767bd3fa15791759c91ec19058ebe31217fe66f3e9a8c49/cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting ipaddress; python_version < "3" (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl>=0.12->service_identity>=1.0.0)
python3-ldap 0.9.5.3 has requirement pyasn1==0.1.7, but you'll have pyasn1 0.4.4 which is incompatible.
Installing collected packages: six, enum34, idna, asn1crypto, pycparser, cffi, ipaddress, cryptography, pyopenssl, pyasn1, attrs, pyasn1-modules, service-identity
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: enum34 1.1.6
    Uninstalling enum34-1.1.6:
      Successfully uninstalled enum34-1.1.6
  Found existing installation: idna 2.7
    Uninstalling idna-2.7:
      Successfully uninstalled idna-2.7
  Found existing installation: asn1crypto 0.24.0
    Uninstalling asn1crypto-0.24.0:
      Successfully uninstalled asn1crypto-0.24.0
  Found existing installation: pycparser 2.18
Cannot uninstall 'pycparser'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
This failure has good reasons as it prevents messing system libraries.

**Comment by richvdh** [comment]
Yeah, the advice to use pip is awful; I have updated #3743 accordingly.

That said, I can't reproduce your problem, which looks like it is with `pyasn1` rather than `service_identity` itself. What does this give you:

```bash
python -c 'import pyasn1.type; print pyasn1.type.__file__'
```
