### ISSUE TITLE
Thumbnail rendering can throw an error while it's outputting and cause a traceback

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#3813]
```
2018-09-06 18:27:29,177 - synapse.http.site - 144 - ERROR - GET-3175501- Asynchronous messge handler raised an uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/http/site.py", line 141, in processing
    yield
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 190, in wrapped_async_request_handler
    yield h(self, request)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 111, in wrapped_request_handler
    pretty_print=_request_user_agent_is_curl(request),
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 409, in respond_with_json
    response_code_message=response_code_message,
  File "/usr/lib/python2.7/dist-packages/synapse/http/server.py", line 439, in respond_with_json_bytes
    producer.start()
  File "/usr/lib/python2.7/dist-packages/twisted/web/static.py", line 735, in start
    self.request.registerProducer(self, False)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 927, in registerProducer
    "unregistered" % (producer, self.producer))
ValueError: registering producer <twisted.web.static.NoRangeStaticProducer object at 0x7f65f5a56e10> before previous one (<twisted.protocols.basic.FileSender instance at 0x7f662505c830>) was unregistered
```

**Comment by richvdh** [comment]
I think this is probably harmless except for the noise in the log?
