### ISSUE TITLE
VOIP crashes under Python 3

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#3821]
```
2018-09-07 12:33:00,847 - synapse.http.server - 101 - ERROR - b'GET'-83- Failed handle request via <function JsonResource._async_render at 0x7f3dc8904158>: <XForwardedForRequest at 0x7f3dc633c198 method=b'GET' uri=b'/_matrix/client/r0/voi
p/turnServer?' clientproto=b'HTTP/1.1' site=8008>: Traceback (most recent call last):
  File "/home/krombel/synapse/venv35/lib/python3.5/site-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/krombel/synapse/synapse/http/server.py", line 295, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/krombel/synapse/venv35/lib/python3.5/site-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/krombel/synapse/venv35/lib/python3.5/site-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status) 
--- <exception caught here> ---
  File "/home/krombel/synapse/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/krombel/synapse/synapse/http/server.py", line 295, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/krombel/synapse/venv35/lib/python3.5/site-packages/Twisted-18.7.0-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1418, in _inlineCallbacks                                                                                 result = g.send(result)
  File "/home/krombel/synapse/synapse/rest/client/v1/voip.py", line 45, in on_GET
    mac = hmac.new(turnSecret, msg=username, digestmod=hashlib.sha1) 
  File "/home/krombel/synapse/venv35/lib/python3.5/hmac.py", line 144, in new                                                                                                                                                                     return HMAC(key, msg, digestmod)
  File "/home/krombel/synapse/venv35/lib/python3.5/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
builtins.TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by hawkowl** [comment]
Fixed. Thanks @krombel
