### ISSUE TITLE
AttributeError 'module' object has no attribute 'OP_SINGLE_ECDH_USE'

### ISSUE THREAD

**Issue by rozahp** [matrix-org/synapse#3828]
Distro: Ubuntu 16.04 running in a container
Synapse: version 0.33.4

Issue: Push notifications failed after apt-get upgrade of matrix-synapse in August.

**Errors from /var/log/matrix-synapse/homeserver.log** (### = anonymized info)

```
2018-09-08 20:54:40,049 - synapse.push.httppusher - 165 - INFO - None- Processing 1 unprocessed push actions for @USERXXX:matrix.mydomain.com/im.vector.app.ios.voip.prod/############################# starting at stream_ordering 1255
2018-09-08 20:54:40,050 - synapse.http.client - 93 - INFO - None- Sending request POST https://matrix.org/_matrix/push/v1/notify
2018-09-08 20:54:40,050 - synapse.http.client - 115 - INFO - None- Error sending request to  POST https://matrix.org/_matrix/push/v1/notify: AttributeError 'module' object has no attribute 'OP_SINGLE_ECDH_USE'
2018-09-08 20:54:40,051 - synapse.push.httppusher - 338 - WARNING - None- Failed to push event $##################:matrix.mydomain.com to @USERXXX:matrix.mydomain.com/im.vector.app.ios.voip.prod/#############################
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/synapse/push/httppusher.py", line 334, in dispatch_push
    resp = yield self.http_client.post_json_get_json(self.url, notification_dict)
AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'
2018-09-08 20:54:40,051 - synapse.push.httppusher - 222 - INFO - None- Push failed: delaying for 512s


```

**Comment by rozahp** [comment]
Solvved

**Comment by iclou** [comment]
I have downgraded Twisted to 17.1.0 and I  get the following error:

2018-09-16 23:08:33,111 - synapse.http.server - 101 - ERROR - POST-34- Failed handle request via <function _async_render at 0x7fbde9bec140>: <SynapseRequest at 0x7fbde6ba90e0 method='POST' uri='/_matrix/client/r0/account/3pid/email/requestToken' clientproto='HTTP/1.1' site=8448>: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 196, in post_json_get_json
    bodyProducer=FileBodyProducer(StringIO(json_str))
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1447, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python2.7/dist-packages/synapse/http/client.py", line 97, in request
    method, uri, *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1625, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1609, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1486, in endpointForURI
    uri.port)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 929, in creatorForNetloc
    trustRoot=self._trustRoot)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1287, in optionsForClientTLS
    **extraCertificateOptions
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/deprecate.py", line 724, in wrapped
    return wrappee(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1583, in __init__
    self._options |= SSL.OP_SINGLE_DH_USE | SSL.OP_SINGLE_ECDH_USE
exceptions.AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'

**Comment by ara4n** [comment]
that sounds like you need to upgrade your openssl and/or pyopenssl.

**Comment by iclou** [comment]
upgrading pyopenssl did the job
pip install pyOpenSSL --upgrade
Thanks so much!
