### ISSUE TITLE
NoneType has no attribute shutdown

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3837]
Unsure what causes this, but it seems to happen frequently. Observed on a federation_sender worker. Shows up in pairs.

```
federation_sender_1 - 2018-09-10 20:03:46,477 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/app/_base.py", line 104, in run
    reactor.run()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 243, in f
    ret = func(*args, **kwargs)
--- <exception caught here> ---
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/util/async_helpers.py", line 415, in time_it_out
    deferred.cancel()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 548, in cancel
    self.result.cancel()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 537, in cancel
    canceller(self)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 1481, in cancelRequest
    self.transport.abortConnection()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
exceptions.AttributeError: 'NoneType' object has no attribute 'shutdown'
```

**Comment by richvdh** [comment]
this is https://twistedmatrix.com/trac/ticket/9535
