### ISSUE TITLE
Unexpected exception due to failed federation PUT requests

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#3838]
This doesn't appear to affect operation of the server, but it is annoying to have in the logs.

```
federation_sender_1 - 2018-09-10 20:26:19,097 - synapse.http.matrixfederationclient - 250 - WARNING - federation_transaction_transmission_loop-20771366- {PUT-O-7745791} Sending request failed to REDACTED.com: PUT matrix://REDACTED.com/_matrix/federation/v1/send/1536467941257/: RequestTransmissionFailed:[ConnectionDone()]
federation_sender_1 - 2018-09-10 20:26:19,097 - twisted - 131 - CRITICAL - - Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 195, in _callAppFunction
    function()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/web/client.py", line 1087, in stopProducing
    self._task.stop()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
TaskStopped
```

**Comment by turt2live** [comment]
Closing in favour of https://github.com/matrix-org/synapse/issues/4003 due to more information over there
