### ISSUE TITLE
Outbound federation breaks to a particular server until restart

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#3842]
No events were sent from jki.re to matrix.org for ~24h. Other requests were successfully sent.

The last log line in the federation transmission loop for matrix.org is:

```
2018-09-10 10:15:54,901 - synapse.http.outbound - 182 - INFO - federation_transaction_transmission_loop-26525 - {PUT-O-13438} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v1/send/1536569581947/
```

suggesting that the deferred to actually send the transaction got wedged entirely.

Later we have an unhandled error, which may or may not be related.

```
2018-09-10 10:15:56,438 - twisted - 131 - CRITICAL -  - Unhandled error in Deferred:
2018-09-10 10:15:56,438 - twisted - 131 - CRITICAL -  - 
ResponseNeverReceived: [<twisted.python.failure.Failure twisted.web._newclient.ConnectionAborted: >]
```

Edit: Version: `Synapse/0.33.4 (b=develop,9a5ea511b)`

**Comment by erikjohnston** [comment]
One recent change that may be relevant is that we've moved to use `treq`.

We also don't seem to time out reading the body from the response:

https://github.com/matrix-org/synapse/blob/9a5ea511b5ce2c8d782c11a2d57461661324b3d6/synapse/http/matrixfederationclient.py#L380-L398

**Comment by erikjohnston** [comment]
Right, so what probably isn't helping is that our retry schedule for "long retries" is insane:

https://github.com/matrix-org/synapse/blob/9a5ea511b5ce2c8d782c11a2d57461661324b3d6/synapse/http/matrixfederationclient.py#L255-L266

**Comment by erikjohnston** [comment]
In what will shock everyone it turns out I can't read, the maximum sleep time is actually only 84 seconds

**Comment by erikjohnston** [comment]
After the logging change its clear that things are getting wedged in the actual request deferred, which suggests that the timeouts are broken.

**Comment by erikjohnston** [comment]
The awful hack didn't work. But I found a stack trace:

```
2018-09-14 19:14:17,035 - twisted - 243 - CRITICAL -  - Unhandled Error
Traceback (most recent call last):
  File "synapse/app/_base.py", line 104, in run
    
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "synapse/metrics/__init__.py", line 349, in f
    
--- <exception caught here> ---
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "synapse/util/async_helpers.py", line 459, in time_it_out
    
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 548, in cancel
    self.result.cancel()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 537, in cancel
    canceller(self)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/web/_newclient.py", line 1481, in cancelRequest
    self.transport.abortConnection()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/protocols/tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
exceptions.AttributeError: 'NoneType' object has no attribute 'shutdown'
```

so I hacked the hack to hack around that and moved the cancellation until *after* resolving the new deferred

**Comment by erikjohnston** [comment]
The hack is: https://github.com/matrix-org/synapse/blob/9d13ff4da8483e4fdd66dd16e8ad4ac299f10e43/synapse/util/async_helpers.py#L443-L492

**Comment by erikjohnston** [comment]
So conclusion is that this is a bug in twisted, where the `cancel` function doesn't handle the `canceller` throwing an exception, which stops the deferred from being resolved. https://github.com/twisted/twisted/blob/twisted-18.4.0/src/twisted/internet/defer.py#L536

**Comment by erikjohnston** [comment]
https://twistedmatrix.com/trac/ticket/9534#ticket

**Comment by erikjohnston** [comment]
We've updated all timeouts to use the new function
