### ISSUE TITLE
Synchrotron blows up on python3

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3867]
```
Sep 13 20:13:20 Halfy-VM systemd[1]: Started Synapse Sychrotron.
Sep 13 20:13:21 Halfy-VM python[7099]: Traceback (most recent call last):
Sep 13 20:13:21 Halfy-VM python[7099]:   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
Sep 13 20:13:21 Halfy-VM python[7099]:     "__main__", mod_spec)
Sep 13 20:13:21 Halfy-VM python[7099]:   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
Sep 13 20:13:21 Halfy-VM python[7099]:     exec(code, run_globals)
Sep 13 20:13:21 Halfy-VM python[7099]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/app/synchrotron.py", line 40, in <module>
Sep 13 20:13:21 Halfy-VM python[7099]:     from synapse.replication.slave.storage.deviceinbox import SlavedDeviceInboxStore
Sep 13 20:13:21 Halfy-VM python[7099]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/replication/slave/storage/deviceinbox.py", line 24, in <module>
Sep 13 20:13:21 Halfy-VM python[7099]:     class SlavedDeviceInboxStore(BaseSlavedStore):
Sep 13 20:13:21 Halfy-VM python[7099]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/replication/slave/storage/deviceinbox.py", line 46, in SlavedDeviceInboxStore
Sep 13 20:13:21 Halfy-VM python[7099]:     get_to_device_stream_token = DataStore.get_to_device_stream_token.__func__
Sep 13 20:13:21 Halfy-VM python[7099]: AttributeError: 'function' object has no attribute '__func__'
Sep 13 20:13:21 Halfy-VM systemd[1]: synchrotron.service: Main process exited, code=exited, status=1/FAILURE
Sep 13 20:13:21 Halfy-VM systemd[1]: synchrotron.service: Failed with result 'exit-code'.
```

**Comment by hawkowl** [comment]
Fixed by #4027
