### ISSUE TITLE
expire_url_cache_data | psycopg2.ProgrammingError: operator does not exist: text = bytea

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#3891]
I noticed this in the logs when running the py3 develop (master process, not a worker), but I'm not sure how concerned I should be about it:

```
Sep 17 15:32:14 Halfy-VM python3[27988]: 2018-09-17 15:32:14,330 - twisted - 243 - CRITICAL - expire_url_cache_data-10-
Sep 17 15:32:14 Halfy-VM python3[27988]: Traceback (most recent call last):
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 17 15:32:14 Halfy-VM python3[27988]:     result = result.throwExceptionIntoGenerator(g)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Sep 17 15:32:14 Halfy-VM python3[27988]:     return g.throw(self.type, self.value, self.tb)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/metrics/background_process_metrics.py", line 193, in run
Sep 17 15:32:14 Halfy-VM python3[27988]:     yield func(*args, **kwargs)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 17 15:32:14 Halfy-VM python3[27988]:     result = result.throwExceptionIntoGenerator(g)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Sep 17 15:32:14 Halfy-VM python3[27988]:     return g.throw(self.type, self.value, self.tb)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 325, in runInteraction
Sep 17 15:32:14 Halfy-VM python3[27988]:     *args, **kwargs
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 17 15:32:14 Halfy-VM python3[27988]:     result = result.throwExceptionIntoGenerator(g)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Sep 17 15:32:14 Halfy-VM python3[27988]:     return g.throw(self.type, self.value, self.tb)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 374, in runWithConnection
Sep 17 15:32:14 Halfy-VM python3[27988]:     inner_func, *args, **kwargs
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
Sep 17 15:32:14 Halfy-VM python3[27988]:     result = inContext.theWork()
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Sep 17 15:32:14 Halfy-VM python3[27988]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
Sep 17 15:32:14 Halfy-VM python3[27988]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
Sep 17 15:32:14 Halfy-VM python3[27988]:     return func(*args,**kw)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Sep 17 15:32:14 Halfy-VM python3[27988]:     compat.reraise(excValue, excTraceback)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/compat.py", line 463, in reraise
Sep 17 15:32:14 Halfy-VM python3[27988]:     raise exception.with_traceback(traceback)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Sep 17 15:32:14 Halfy-VM python3[27988]:     result = func(conn, *args, **kw)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 370, in inner_func
Sep 17 15:32:14 Halfy-VM python3[27988]:     return func(conn, *args, **kwargs)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 246, in _new_transaction
Sep 17 15:32:14 Halfy-VM python3[27988]:     r = func(txn, *args, **kwargs)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/client_ips.py", line 135, in _update_client_ips_batch_txn
Sep 17 15:32:14 Halfy-VM python3[27988]:     lock=False,
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 557, in _simple_upsert_txn
Sep 17 15:32:14 Halfy-VM python3[27988]:     txn.execute(sql, sqlargs)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 87, in execute
Sep 17 15:32:14 Halfy-VM python3[27988]:     self._do_execute(self.txn.execute, sql, *args)
Sep 17 15:32:14 Halfy-VM python3[27988]:   File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 117, in _do_execute
Sep 17 15:32:14 Halfy-VM python3[27988]:     sql, *args
Sep 17 15:32:14 Halfy-VM python3[27988]: psycopg2.ProgrammingError: operator does not exist: text = bytea
Sep 17 15:32:14 Halfy-VM python3[27988]: LINE 1: ...BtGygH1FzJC-5MUT7M2m-3g6NoYePMzKuZG0JKxCg' AND ip = '\x2d'::...
Sep 17 15:32:14 Halfy-VM python3[27988]:                                                              ^
Sep 17 15:32:14 Halfy-VM python3[27988]: HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

**Comment by richvdh** [comment]
dup #3893
