### ISSUE TITLE
After upgrading to Ubuntu 18.04.1, Synapse won't start

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#3896]
### Description

I can't start Synapse after upgrading Ubuntu versions. Sorry for filing an issue on this but I didn't get any responses in #matrix:matrix.org or #synapse-community:matrix.org

### Steps to reproduce

- Upgrade from Ubuntu 16.04.5 to Ubuntu 18.04.1
- `sudo systemctl start synapse`

Expected result: Synapse should start

Actual result: Synapse does not start 

Homeserver.log
```
2018-09-17 17:18:34,953 - root - 212 - WARNING - None- ***** STARTING SERVER *****
2018-09-17 17:18:34,983 - root - 215 - WARNING - None- Server /usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py version 0.33.5rc1
2018-09-17 17:18:34,988 - twisted - 243 - ERROR - - Traceback (most recent call last):
2018-09-17 17:18:34,989 - twisted - 243 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
2018-09-17 17:18:34,990 - twisted - 243 - ERROR - -     "__main__", fname, loader, pkg_name)
2018-09-17 17:18:34,990 - twisted - 243 - ERROR - -   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
2018-09-17 17:18:34,991 - twisted - 243 - ERROR - -     exec code in run_globals
2018-09-17 17:18:34,991 - twisted - 243 - ERROR - -   File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 591, in <module>
2018-09-17 17:18:34,992 - twisted - 243 - ERROR - -     main()
2018-09-17 17:18:34,992 - twisted - 243 - ERROR - -   File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 586, in main
2018-09-17 17:18:34,992 - twisted - 243 - ERROR - -     hs = setup(sys.argv[1:])
2018-09-17 17:18:34,993 - twisted - 243 - ERROR - -   File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 349, in setup
2018-09-17 17:18:34,993 - twisted - 243 - ERROR - -     database_engine = create_engine(config.database_config)
2018-09-17 17:18:34,993 - twisted - 243 - ERROR - -   File "/usr/local/lib/python2.7/dist-packages/synapse/storage/engines/__init__.py", line 38, in create_engine
2018-09-17 17:18:34,994 - twisted - 243 - ERROR - -     module = importlib.import_module(name)
2018-09-17 17:18:34,994 - twisted - 243 - ERROR - -   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
2018-09-17 17:18:34,995 - twisted - 243 - ERROR - -     __import__(name)
2018-09-17 17:18:34,995 - twisted - 243 - ERROR - -   File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 50, in <module>
2018-09-17 17:18:34,995 - twisted - 243 - ERROR - -     from psycopg2._psycopg import (                     # noqa
2018-09-17 17:18:34,996 - twisted - 243 - ERROR - - ImportError: /usr/local/lib/python2.7/dist-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

`sudo journalctl -xef -u synapse`:
```
Sep 17 17:18:33 ubuntu systemd[1]: Started Matrix reference homeserver.
-- Subject: Unit synapse.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit synapse.service has finished starting up.
--
-- The start-up result is RESULT.
Sep 17 17:18:34 ubuntu python2.7[18908]: No handlers could be found for logger "synapse.config.server"
Sep 17 17:18:35 ubuntu systemd[1]: synapse.service: Main process exited, code=exited, status=1/FAILURE
Sep 17 17:18:35 ubuntu systemd[1]: synapse.service: Failed with result 'exit-code'.
```

### Version information

- **Homeserver**: raim.ist
- **Version**:  0.33.5rc1 (also affected 0.33.4)
- **Install method**: pip      
- **Platform**: Linode server running Ubuntu 18.04.1

**Comment by Half-Shot** [comment]
@aaronraimist just for future reference, can you document what you did to fix this?

**Comment by ara4n** [comment]
I fixed it with him: https://github.com/psycopg/psycopg2-wheels/issues/2#issuecomment-347685219 was the answer.

**Comment by aaronraimist** [comment]
I think pip told me that was deprecated or going to be deprecated, so the command you actually want to run is `sudo pip install psycopg2-binary`
