### ISSUE TITLE
Failed after update to 0.33.5.1 on Ubuntu 16.04.5 LTS

### ISSUE THREAD

**Issue by aleks-o** [matrix-org/synapse#3945]
### Description

Failed to start after update to version 0.33.5.1 on Ubuntu 16.04.5 LTS

### Steps to reproduce

Update to version 0.33.5.1
Service failed to start with the error:

```
-- Unit matrix-synapse.service has begun starting up.
Sep 25 05:05:08 matrix1 python[13262]: Traceback (most recent call last):
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Sep 25 05:05:08 matrix1 python[13262]:     "__main__", fname, loader, pkg_name)
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Sep 25 05:05:08 matrix1 python[13262]:     exec code in run_globals
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 58, in <module>
Sep 25 05:05:08 matrix1 python[13262]:     from synapse.replication.http import REPLICATION_PREFIX, ReplicationRestResource
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/synapse/replication/http/__init__.py", line 17, in <module>
Sep 25 05:05:08 matrix1 python[13262]:     from synapse.replication.http import federation, membership, send_event
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/synapse/replication/http/federation.py", line 24, in <module>
Sep 25 05:05:08 matrix1 python[13262]:     from synapse.util.metrics import Measure
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/synapse/util/metrics.py", line 53, in <module>
Sep 25 05:05:08 matrix1 python[13262]:     sub_metrics=["real_time_max", "real_time_sum"],
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/synapse/metrics/__init__.py", line 121, in __init__
Sep 25 05:05:08 matrix1 python[13262]:     slots=True,
Sep 25 05:05:08 matrix1 python[13262]:   File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 581, in make_class
Sep 25 05:05:08 matrix1 python[13262]:     return attributes(**attributes_arguments)(type(name, (object,), cl_dict))
Sep 25 05:05:08 matrix1 python[13262]: TypeError: attributes() got an unexpected keyword argument 'slots'
Sep 25 05:05:08 matrix1 systemd[1]: matrix-synapse.service: Control process exited, code=exited status=1
Sep 25 05:05:08 matrix1 systemd[1]: Failed to start Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has failed

```

### Version information

- **Homeserver**:  My own homeserver. 

If not matrix.org:
- **Version**: 0.33.5.1
- **Install method**: package manager
- **Platform**: Ubuntu 16.04.5 LTS

**Comment by richvdh** [comment]
yup, looks like we're using features from `attrs` which arrived in 16.0.0 but xenial only has 15.2.0.

**Comment by richvdh** [comment]
@aleks-o: I have added python-attr 16.3.0 to our repo. Could you upgrade again?

**Comment by aleks-o** [comment]
python-attr upgraded to 16.3.0-1 and now synapse can start without errors.
@richvdh , thanks!

**Comment by richvdh** [comment]
sorry for the snafu
