### ISSUE TITLE
Tests not shutting down sqlite connections cleanly

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/synapse#4000]
On running the following test, I get this log output, it looks like the db conn is just being closed in a different thread from the thread of execution, but weird nonetheless.

Test code

```
class RegistrationTestCase(unittest.TestCase):
@defer.inlineCallbacks
    def setUp(self):
        self.mock_distributor = Mock()
        self.mock_distributor.declare("registered_user")
        self.mock_captcha_client = Mock()
        self.hs = yield setup_test_homeserver(
            self.addCleanup,
            handlers=None,
            http_client=None,
            expire_access_token=True,
            profile_handler=Mock(),
        )
@defer.inlineCallbacks
    def test_auto_create_auto_join_rooms(self):
        res = yield self.handler.register(localpart='jeff')
        rooms = yield self.store.get_rooms_for_user(res[0])
        print rooms
```

Log output is 

```
2018-10-03 16:42:35+0100 [-] Log opened.
2018-10-03 16:42:35+0100 [-] --> tests.handlers.test_register.RegistrationTestCase.test_auto_create_auto_join_rooms <--
2018-10-03 16:42:36+0100 [-] Main loop terminated.
2018-10-03 16:42:36+0100 [-] 2018-10-03 16:42:36,233 - synapse.util.logcontext - 321 - WARNING - update_client_ips-0 - Called stop on logcontext update_client_ips@1047901b8 without calling start
2018-10-03 16:42:36+0100 [-] 2018-10-03 16:42:36,234 - synapse.util.logcontext - 321 - WARNING - update_client_ips-0 - Called stop on logcontext runWithConnection@1047900c8 without calling start
2018-10-03 16:42:36+0100 [-] 2018-10-03 16:42:36,235 - synapse.util.logcontext - 321 - WARNING - update_client_ips-0 - Called stop on logcontext update_client_ips@1047901b8 without calling start
2018-10-03 16:42:36+0100 [-] Connection close failed
        Traceback (most recent call last):
          File "/Users/neil/Development/matrix-org/synapse/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
            self._runCallbacks()
          File "/Users/neil/Development/matrix-org/synapse/env/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/Users/neil/Development/matrix-org/synapse/env/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
            callable(*args, **kwargs)
          File "/Users/neil/Development/matrix-org/synapse/env/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 406, in finalClose
            self._close(conn)
        --- <exception caught here> ---
          File "/Users/neil/Development/matrix-org/synapse/env/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 456, in _close
            conn.close()
        sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145439305728 and this is thread id 140735888212864
        
2018-10-03 16:42:36+0100 [-] Main loop terminated.
```

**Comment by richvdh** [comment]
I no longer see this error when running this test, so I'm going to assume it's fixed.
