### ISSUE TITLE
SQLite error when running server

### ISSUE THREAD

**Issue by AppleDash** [matrix-org/synapse#401]
I installed and configured a server according to the instructions in the README, and upon running, I get the following output:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/appledash/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 745, in <module>
    main()
  File "/home/appledash/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 740, in main
    hs = setup(sys.argv[1:])
  File "/home/appledash/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 423, in setup
    database_engine.prepare_database(db_conn)
  File "/home/appledash/.synapse/local/lib/python2.7/site-packages/synapse/storage/engines/sqlite3.py", line 41, in prepare_database
    prepare_database(db_conn, self)
  File "/home/appledash/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 64, in prepare_database
    cur, user_version, delta_files, upgraded, database_engine
  File "/home/appledash/.synapse/local/lib/python2.7/site-packages/synapse/storage/prepare_database.py", line 248, in _upgrade_existing_database
    module.run_upgrade(cur, database_engine)
  File "/home/appledash/.synapse/local/lib/python2.7/site-packages/synapse/storage/schema/delta/25/fts.py", line 51, in run_upgrade
    cur.execute(SQLITE_TABLE)
sqlite3.OperationalError: near "NOT": syntax error
Starting ... error starting (exit code: 255); see above for logs
```

Here is some system info:

```
$ python2 --version
Python 2.7.3
$ sqlite3 --version
3.7.9 2011-11-01 00:52:41 c7c6050ef060877ebe77b41d959e9df13f8c9b5e
$ uname -a
Linux $server_hostname 3.13.0-37-generic #64~precise1-Ubuntu SMP Wed Sep 24 21:37:11 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Any idea what could be going on here?

**Comment by ara4n** [comment]
From first glance your sqlite is very old - and synapse relies on at least 3.8.something for full text search features such that search works. Can you upgrade it?

**Comment by AppleDash** [comment]
I don't think I can upgrade it - the package is up to date according to `apt`.

**Comment by erikjohnston** [comment]
@AppleDash Could you try running the following two commands in a new sqlite3 DB? (For example by simply running the `sqlite3` command, which creates a temporary in memory DB)

```
CREATE VIRTUAL TABLE IF NOT EXISTS test1 USING fts4 ( column );
CREATE VIRTUAL TABLE test2 USING fts4 ( column );
```

Looking at the documentation, sqlite3 3.7.9 should support FTS4 tables. My guess is that it may not support the `IF NOT EXISTS` part.

**Comment by AppleDash** [comment]
@erikjohnston Here's the output, it seems you might be right:

```
sqlite> CREATE VIRTUAL TABLE IF NOT EXISTS test1 USING fts4 ( column );
Error: near "NOT": syntax error
sqlite> CREATE VIRTUAL TABLE test2 USING fts4 ( column );
sqlite> 
```

**Comment by erikjohnston** [comment]
Okay, we can easily fix that. Will try and make sure it gets into a release ASAP.

If you want, you can also just remove the offending `IF NOT EXISTS` from https://github.com/matrix-org/synapse/blob/master/synapse/storage/schema/delta/25/fts.py#L41 . It should be perfectly safe to do so.

**Comment by NANASHI0X74** [comment]
I tried to compile sqlite3.30 from https://www.sqlite.org/download.html and replacing /usr/bin/sqlite3 with it, but I got the same error. Now after finding an rpm for sqlite3.8 it worked
