### ISSUE TITLE
Failed to get displayname  - InvalidCodepoint

### ISSUE THREAD

**Issue by progserega** [matrix-org/synapse#4032]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce

- Unknown - this is remote user

Error in logs:
```
    2018-10-12 17:32:31,709 - synapse.handlers.profile - 146 - ERROR - POST-442241- Failed to get displayname
    Traceback (most recent call last): 
      File "/usr/lib/python2.7/dist-packages/synapse/handlers/profile.py", line 139, in get_displayname
        ignore_backoff=True,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/client.py", line 191, in make_query
        ignore_backoff=ignore_backoff,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 486, in get_json
        ignore_backoff=ignore_backoff,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 199, in _request
        request_deferred,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 154, in connect
        conn = yield self.endpoint_fac.connect(protocolFactory)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
        result = g.send(result)
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 334, in connect
        self.reactor, server.host, server.port, **self.endpoint_kw_args
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 131, in transport_endpoint
        tls_client_options_factory.get_options(host),
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 127, in get_options
        CertificateOptions(verify=False).getContext()
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 100, in __init__
        self._hostnameBytes = _idnaBytes(hostname)
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 67, in _idnaBytes
        return idna.encode(text)
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 355, in encode 
        result.append(alabel(label))
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 276, in alabel 
        check_label(label)
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 253, in check_label
        raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
    InvalidCodepoint: Codepoint U+0020 at position 3 of u'ru ' not allowed
```

### Version information
ii  matrix-synapse                  0.33.4-1mx1
debian 9.5

- own **Homeserver**: rsprim.ru

$ curl -v https://rsprim.ru/_matrix/client/versions 2>&1 | grep "Server:"

Server: nginx/1.10.3

- **Install method**: package manager "apt-get" from 
deb https://matrix.org/packages/debian stretch main

- **Platform**:       debian 9.5 in lxc-container

**Comment by progserega** [comment]
Such problem from another user:

`
     2018-10-12 17:32:31,783 - synapse.http.matrixfederationclient - 222 - WARNING - POST-442241- {GET-O-141762} Sending request failed to rsprim.ru : GET matrix://rsprim.ru /_matrix/federation/v1/query/profile?field=avatar_url&user_id=%40belik%3Arsprim.ru+: InvalidCodepoint("Codepoint U+0020 at position 3 of u'ru '    __ not allowed",)
    2018-10-12 17:32:31,784 - synapse.http.outbound - 246 - INFO - POST-442241- {GET-O-141762} [rsprim.ru ] Result: InvalidCodepoint("Codepoint U+0020 at position 3 of u'ru ' not allowed",)
    2018-10-12 17:32:31,789 - synapse.handlers.profile - 203 - ERROR - POST-442241- Failed to get avatar_url
    Traceback (most recent call last): 
      File "/usr/lib/python2.7/dist-packages/synapse/handlers/profile.py", line 196, in get_avatar_url
        ignore_backoff=True,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/federation/transport/client.py", line 191, in make_query
        ignore_backoff=ignore_backoff,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 486, in get_json
        ignore_backoff=ignore_backoff,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/matrixfederationclient.py", line 199, in _request
        request_deferred,
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 422, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 154, in connect
        conn = yield self.endpoint_fac.connect(protocolFactory)
      File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
        result = g.send(result)
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 334, in connect
        self.reactor, server.host, server.port, **self.endpoint_kw_args
      File "/usr/lib/python2.7/dist-packages/synapse/http/endpoint.py", line 131, in transport_endpoint
        tls_client_options_factory.get_options(host),
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 127, in get_options
        CertificateOptions(verify=False).getContext()
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 100, in __init__
        self._hostnameBytes = _idnaBytes(hostname)
      File "/usr/lib/python2.7/dist-packages/synapse/crypto/context_factory.py", line 67, in _idnaBytes
        return idna.encode(text)
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 355, in encode 
        result.append(alabel(label))
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 276, in alabel 
        check_label(label)
      File "/usr/lib/python2.7/dist-packages/idna/core.py", line 253, in check_label
        raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
    InvalidCodepoint: Codepoint U+0020 at position 3 of u'ru ' not allowed
    2018-10-12 17:32:31,804 - synapse.handlers.message - 308 - INFO - POST-442241- Failed to get profile information for @belik:rsprim.ru : local variable 'result' referenced before assignment
    2018-10-12 17:32:31,814 - twisted - 131 - INFO - - (UDP Port 65266 Closed)

`

**Comment by progserega** [comment]
Users add utf8 display name and it is fail on server?

**Comment by progserega** [comment]
I think this is such problem

**Comment by hawkowl** [comment]
@progserega You seem to have a space in your homeserver name? It's saying the " " in "ru " isn't allowed.

**Comment by progserega** [comment]
Yes, free 30 Gb.

I investigate problem: web interface allow add to our bot mxid with spaces. When bot try create room for user and try invite this user to this room - server show such error. 

Do I think properly, that it is not server error? And this bug may be close?

**Comment by progserega** [comment]
> we should probably handle this more gracefully, in any case. It would be useful if you could tell us how to reproduce this: "web interface allow add to our bot mxid with spaces". Which web interface, exactly?

Our internal company web-interface, which symply get from user "mxid", which must be receive corporate automated messages:

1. Admin open out web interface.
2. Admin find needed users in user-list. 
3. Admin set for user his mxid.
4. Our matrix-bot get this mxid and send to this mxid corporate messages.

Problem was in our web interface, which not strip spaces across entered mxid.

But I think that matrix-synapse must avoid this "bad mxid" in message from bot without any exceptions in logs... Or no?

**Comment by richvdh** [comment]
The problem is that we need to know which APIs are being used which cause the problem. It looks from the above as though it is the createRoom API - is that correct?

**Comment by progserega** [comment]
I use matrix_client python sdk 0.3.2

```
from matrix_client.client import MatrixClient
from matrix_client.api import MatrixRequestError
from matrix_client.api import MatrixHttpLibError
from requests.exceptions import MissingSchema


def create_room(db_con,matrix_uid):
  global log
  global client

  cur=db_con["cur"]
  con=db_con["con"]
  try:
    room=client.create_room(is_public=False, invitees=[matrix_uid])
    print("room_id=",room.room_id)
  except MatrixRequestError as e:
    print(e)
    if e.code == 400:
      log.error("Room ID/Alias in the wrong format")
      return False
    else:
      log.error("Couldn't find room.")
      return False
```

If matrix_uid have spaces in end of string - then server log have exception from current issue.

**Comment by richvdh** [comment]
Ok thanks very much: I have opened #4088 to describe the problem more succinctly.
