### ISSUE TITLE
/publicRooms fails on python3 with 500 - KeyError

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#4039]
Logs:
```
2018-10-15 18:40:40,840 - synapse.util.caches.response_cache - 151 - INFO - POST-117277- [room_list]: no cached result for [(20, 'hKFzzgCr+fuhcM0BXqFuE6Fkww', ThirdPartyInstanceID(appservice_id=None, network_id=None))], calculating new one
2018-10-15 18:40:40,841 - synapse.http.server - 112 - ERROR - POST-117277- Failed handle request via <function JsonResource._async_render at 0x7f0027bf6a60>: <XForwardedForRequest at 0x7effd5b46080 method='POST' uri='/_matrix/client/r0/publicRooms?' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/util/caches/response_cache.py", line 152, in wrap
    d = run_in_background(callback, *args, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/util/logcontext.py", line 497, in run_in_background
    res = f(*args, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 371, in on_POST
    network_tuple=network_tuple,
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 92, in _get_public_room_list
    since_token = RoomListNextBatch.from_token(since_token)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 449, in from_token
    for key, val in msgpack.loads(decode_base64(token)).items()
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 449, in <dictcomp>
    for key, val in msgpack.loads(decode_base64(token)).items()
builtins.KeyError: b's'
2018-10-15 18:40:40,842 - synapse.access.http.8008 - 302 - INFO - POST-117277- - - 8008 - {@Half-Shot:half-shot.uk} Processed request: 0.002sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 55B 500 "POST /_matrix/client/r0/publicRooms? HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/0.16.5 Chrome/61.0.3163.100 Electron/2.0.8 Safari/537.36" [0 dbevts]
```

**Comment by hawkowl** [comment]
PR: https://github.com/matrix-org/synapse/pull/4046
