### ISSUE TITLE
CPU metrics can sometimes have a negative CPU time (???)

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#4055]
```
Traceback (most recent call last):
  File "/home/matrix/synapse/synapse/metrics/__init__.py", line 64, in collect
    calls = self.caller()
  File "/home/matrix/synapse/synapse/http/request_metrics.py", line 131, in _get_in_flight_counts
    rm.update_metrics()
  File "/home/matrix/synapse/synapse/http/request_metrics.py", line 225, in update_metrics
    in_flight_requests_ru_utime.labels(self.method, self.name).inc(diff.ru_utime)
  File "/home/matrix/.synapse-py3/lib/python3.6/site-packages/prometheus_client/core.py", line 672, in inc
    raise ValueError('Counters can only be incremented by non-negative amounts.')
ValueError: Counters can only be incremented by non-negative amounts.
```

**Comment by richvdh** [comment]
ugh we had this before and hacked around it, meaning to come back to it. I can't remember what happened to it. the issue may still be open.

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/issues/3548

**Comment by hawkowl** [comment]
This particular instance is fixed. The one that is mentioned in the ticket
is different and isn't.

**Comment by richvdh** [comment]
what was the fix?

**Comment by hawkowl** [comment]
`max(0, cpu_time)` because TIME ISN'T LINEAR YAYYYY
