### ISSUE TITLE
manhole appears not to work under py3

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4058]
```
matrix@aphrodite:~/synapse-test$ ssh -p9124 matrix@localhost
Received disconnect from 127.0.0.1 port 9124:3: couldn't match all kex parts
Disconnected from 127.0.0.1 port 9124
```

**Comment by richvdh** [comment]
(except it works fine on sw1v.org; I am deeply mystified)

**Comment by richvdh** [comment]
(I'm assuming it's py3 related as it appears to affect all of the matrix.org workers which have been switched to py3)

**Comment by richvdh** [comment]
OHHH I bet it's something to do with the custom build of python 3.6.

**Comment by hawkowl** [comment]
Traceback:

```
2018-10-18 22:07:21,802 - twisted - 243 - CRITICAL -  - Unhandled Error
Traceback (most recent call last):
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1435, in doRead
    protocol.makeConnection(transport)
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
    self.connectionMade()
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 544, in connectionMade
    self.sendKexInit()
  File "/home/matrix/synapse-test/py3venv/lib/python3.6/site-packages/twisted/conch/ssh/transport.py", line 566, in sendKexInit
    NS(b','.join(self.supportedPublicKeys)),
builtins.TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by hawkowl** [comment]
https://github.com/matrix-org/synapse/pull/4060 < fix

**Comment by richvdh** [comment]
nope:

```

2018-10-19 10:25:39,888 - twisted - 243 - INFO -  - b'matrix' failed auth b'password'
2018-10-19 10:25:39,889 - twisted - 243 - INFO -  - unauthorized login: 
```
