### ISSUE TITLE
The link preview API is broken on Python 3

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#4150]
Reports from users in matrix HQ that it's stopped working since the upgrade.

**Comment by hawkowl** [comment]
Traceback courtesy of Tulir:

```2018-11-05 15:37:21,998 - synapse.http.server - 112 - ERROR - GET-32367- Failed handle request via <function PreviewUrlResource._async_render_GET at 0x7f3d86a93ea0>: <XForwardedForRequest at 0x7f3d7e6ff860 method='GET' uri='/_matrix/media/r0/preview_url?url=https%3A%2F%2Fexample.com&ts=1541432241444' clientproto='HTTP/1.1' site=8008>: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/media/v1/preview_url_resource.py", line 161, in _async_render_GET
    respond_with_json_bytes(request, 200, og, send_cors=True)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 457, in respond_with_json_bytes
    bytes_io = BytesIO(json_bytes)
builtins.TypeError: a bytes-like object is required, not 'str'
```

**Comment by hawkowl** [comment]
Likely same symptoms: https://github.com/matrix-org/synapse/issues/2915

**Comment by hawkowl** [comment]
Also likely similar: https://github.com/matrix-org/synapse/issues/2681

**Comment by hawkowl** [comment]
```
  File "/home/matrix/synapse-venv/lib/python3.6/site-packages/synapse/rest/media/v1/media_repository.py", line 332, in _get_remote_media_impl
    server_name, media_id, file_id
  File "/home/matrix/synapse-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse-venv/lib/python3.6/site-packages/synapse/rest/media/v1/media_repository.py", line 405, in _download_remote_file
    _, params = cgi.parse_header(content_disposition[0].decode('ascii'),)
builtins.UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 18: ordinal not in range(128)
```

similar problem...

**Comment by hawkowl** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/4157
