### ISSUE TITLE
createRoom fails after user registration

### ISSUE THREAD

**Issue by andrewrynhard** [matrix-org/synapse#4154]
### Description

createRoom fails after user registration

### Steps to reproduce

- Register new user

Describe how what happens differs from what you expected.

Not sure which room should get created after registering, but it fails. I expect it not to.

<!-- If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly. -->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

- **Homeserver**: Was this issue identified on matrix.org or another homeserver?

If not matrix.org:
- **Version**:        v0.33.8 <!-- 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Install method**: docker
- **Platform**:       Running in Kubernetes behind ingress controller (reverse proxy)


```
Amatrix.dev.autonomy.io/%2415414690116cDJCf%3Amatrix.dev.autonomy.io: ResponseNeverReceived:[CancelledError()]
2018-11-06 01:54:24,943 - synapse.http.server - 112 - ERROR - POST-57- Failed handle request via <function JsonResource._async_render at 0x7fe834933a60>: <SynapseRequest at 0x7fe831b340b8 method='POST' uri='/_matrix/client/r0/createRoom?' clientproto='HTTP/1.1' site=8008>: Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 74, in on_POST
    requester, self.get_room_config(request)
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/room.py", line 272, in create_room
    content=content,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 254, in update_membership
    content=content,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 451, in _update_membership
    content=content,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 201, in _local_membership_update
    ratelimit=ratelimit,
  File "/usr/local/lib/python3.6/site-packages/synapse/util/metrics.py", line 63, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/message.py", line 644, in handle_new_client_event
    extra_users=extra_users,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/message.py", line 733, in persist_and_notify_client_event
    event,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/federation.py", line 1070, in send_invite
    pdu=event
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 699, in send_invite
    content=pdu.get_pdu_json(time_now),
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 299, in send_invite
    ignore_backoff=True,
  File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 507, in put_json
    backoff_on_404=backoff_on_404,
  File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 340, in _send_request
    request_deferred,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/synapse/util/async_helpers.py", line 431, in convert_cancelled
    return to_call(value, timeout)
  File "/usr/local/lib/python3.6/site-packages/synapse/util/async_helpers.py", line 379, in _cancelled_to_timed_out_error
    value.trap(CancelledError)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 439, in trap
    self.raiseException()
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 467, in raiseException
    raise self.value.with_traceback(self.tb)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
2018-11-06 01:54:24,944 - synapse.http.server - 415 - WARNING - POST-57- Not sending response to request <SynapseRequest at 0x7fe831b340b8 method='POST' uri='/_matrix/client/r0/createRoom?' clientproto='HTTP/1.1' site=8008>, already disconnected.
```

**Comment by andrewrynhard** [comment]
```
Failed to create room undefined Error: Server returned 504 error rageshake.js:99
value/</e[r]
rageshake.js:99
e.exports/<
createRoom.js:146
```

**Comment by andrewrynhard** [comment]
After opening up the federation port, the above was fixed. The documentation makes it seem like federation is _optional_.

**Comment by richvdh** [comment]
This sounds like a client problem to me. @rxl881 @dbkr do you know if riot will try to send an invite to `@riot-bot:matrix.org` even when the user isn't on `matrix.org`?

**Comment by dbkr** [comment]
Yes, it does, but for non-matrix.org users it should work over federation: riot cant really tell if federation is disabled. Assuming you have your own Riot, the thing to do here is to disable the welcome user in the config (or set it to one on your own homeserver).

**Comment by neilisfragile** [comment]
Taking the thumbs up to be reason to close

**Comment by richvdh** [comment]
(is there an action point to clarify the documentation here somehow?)
