### ISSUE TITLE
UTF-8 Content-Disposition breaks remote download in media repo

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#4160]
``` 
File "/home/matrix/synapse-venv/lib/python3.6/site-packages/synapse/rest/media/v1/media_repository.py", line 332, in _get_remote_media_impl
    server_name, media_id, file_id
  File "/home/matrix/synapse-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse-venv/lib/python3.6/site-packages/synapse/rest/media/v1/media_repository.py", line 405, in _download_remote_file
    _, params = cgi.parse_header(content_disposition[0].decode('ascii'),)
builtins.UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 18: ordinal not in range(128)
```

**Comment by richvdh** [comment]
looks like this was introduced in #3823. Worth noting that line isn't the only place a content-disposition header is decoded as ascii.

**Comment by aaronraimist** [comment]
Related: #4165

**Comment by kiorky** [comment]
On a local homeserver we are also hit by that bug, is there any ETA as this is critical ?

**Comment by kiorky** [comment]
I tried to backport on top of 0.33.8 with https://github.com/matrix-org/synapse/pull/4176 but this seems not to be sufficient, it still crashes.

**Comment by kiorky** [comment]
I tried to backport on top of 0.33.8 with https://github.com/corpusops/synapse/commit/afc77c4a0123d9e731fd27acf4a9e83c2edb1bed (backport of the tied PR)  but this seems not to be sufficient, it still crashes.

**Comment by hawkowl** [comment]
@kiorky do you have a traceback to share?

**Comment by kiorky** [comment]
For today, it was flooded in the logs, so i hoped to relaunch the deamon in foreground and that the bug would happen back again, that's not the case for now.

For those of yesterday, the error was a UnicodeDecodeError, with the same symptoms as per the first note of this issue, but in the logs i didnt have a full traceback.

**Comment by kiorky** [comment]
<pre>
2018-11-15 12:24:45,351 - synapse.access.http.8008 - 233 - INFO - GET-117973- 92.88.249.199 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s543777_21972192_1149_607731_354593_779_10110_44441_153
2018-11-15 12:24:45,352 - synapse.util.caches.response_cache - 151 - INFO - GET-117973- [sync]: no cached result for [(@jmr:matrix.redacted, 30000, u's543777_21972192_1149_607731_354593_779_10110_44441_153', u'0', False, u'RHUAKFDCFJ')], calculating new one
2018-11-15 12:24:45,352 - synapse.metrics - 374 - INFO - - Collecting gc 0
2018-11-15 12:24:45,353 - synapse.access.http.8008 - 233 - INFO - GET-117974- 92.88.249.199 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=4&timeout=30000&since=s543777_21972192_1149_607731_354593_779_10110_44441_153
2018-11-15 12:24:45,354 - synapse.util.caches.response_cache - 151 - INFO - GET-117974- [sync]: no cached result for [(@sbo:matrix.redacted, 30000, u's543777_21972192_1149_607731_354593_779_10110_44441_153', u'4', False, u'ZDNZPABKEC')], calculating new one
2018-11-15 12:24:45,355 - synapse.access.http.8008 - 233 - INFO - GET-117975- 92.88.249.199 - 8008 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s543777_21972192_1149_607731_354593_779_10110_44441_153
2018-11-15 12:24:45,357 - synapse.util.caches.response_cache - 151 - INFO - GET-117975- [sync]: no cached result for [(@yfo:matrix.redacted, 30000, u's543777_21972192_1149_607731_354593_779_10110_44441_153', u'0', False, u'VQBDTBCVNV')], calculating new one
2018-11-15 12:24:45,357 - synapse.metrics - 374 - INFO - - Collecting gc 0
2018-11-15 12:24:45,358 - synapse.access.http.8008 - 233 - INFO - OPTIONS-117976- 92.88.249.199 - 8008 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s543777_21972192_1149_607731_354593_779_10110_44441_153
2018-11-15 12:24:45,358 - twisted - 243 - ERROR - POST-117962- Traceback (most recent call last): 
2018-11-15 12:24:45,359 - twisted - 243 - ERROR - POST-117962-   File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit 
2018-11-15 12:24:45,360 - twisted - 243 - ERROR - POST-117962-     if self.shouldRollover(record):
2018-11-15 12:24:45,360 - twisted - 243 - ERROR - POST-117962-   File "/usr/lib/python2.7/logging/handlers.py", line 156, in shouldRollover
2018-11-15 12:24:45,360 - twisted - 243 - ERROR - POST-117962-     msg = "%s\n" % self.format(record)
2018-11-15 12:24:45,360 - twisted - 243 - ERROR - POST-117962-   File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
2018-11-15 12:24:45,361 - twisted - 243 - ERROR - POST-117962-     return fmt.format(record)
2018-11-15 12:24:45,361 - twisted - 243 - ERROR - POST-117962-   File "/usr/lib/python2.7/logging/__init__.py", line 474, in format
2018-11-15 12:24:45,361 - twisted - 243 - ERROR - POST-117962-     s = self._fmt % record.__dict__
2018-11-15 12:24:45,361 - twisted - 243 - ERROR - POST-117962- UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 68: ordinal not in range(128)
</pre>

Is the traceback i get when the daemon stops.

**Comment by kiorky** [comment]
I think this is related as there is a media preview a bit sooner:
<pre>
2018-11-15 12:24:45,280 - synapse.access.http.8008 - 233 - INFO - GET-117956- 1.2.3.4 - 8008 - Received request: GET /_matrix/media/r0/preview_url?url=<redacted>l&ts=1542279806447

</pre>

**Comment by hawkowl** [comment]
Hi @kiorky , I don't think this is related (even if the error is similar in nature -- it's happening in another location). Could you open another ticket with the traceback and we'll look into this one, so I can mark this specific issue as closed?

**Comment by richvdh** [comment]
This was fixed in https://github.com/matrix-org/synapse/pull/4176
