### ISSUE TITLE
install test fails under python3

### ISSUE THREAD

**Issue by peterhoeg** [matrix-org/synapse#4162]
### Description

install test fails under python3.6 while fine under python 2.7:

Cc: @hawkowl 

```
running install tests                                                                                                                     [33/5691]
test.test_support
  TestSupport
    test_CleanImport ...                                                   [OK]
    test_DirsOnSysPath ...                                                 [OK]
    test_HOST ...                                                          [OK]
    test_bind_port ...                                                     [OK]
    test_captured_stderr ...                                               [OK]
    test_captured_stdin ...                                                [OK]
    test_captured_stdout ...                                               [OK]
    test_change_cwd ...                                                    [OK]
    test_change_cwd__chdir_warning ...                                     [OK]
    test_change_cwd__non_existent_dir ...                                  [OK]
    test_change_cwd__non_existent_dir__quiet_true ...                      [OK]
    test_check__all__ ...                                                [FAIL]
    test_check_syntax_error ...                                            [OK]
    test_detect_api_mismatch ...                                           [OK]
    test_detect_api_mismatch__ignore ...                                   [OK]
    test_fd_count ...                                                      [OK]
    test_find_unused_port ...                                              [OK]
    test_forget ...                                                        [OK]
    test_gc_collect ...                                                    [OK]
    test_get_attribute ...                                                 [OK]
    test_get_original_stdout ...                                      [SKIPPED]
    test_import_fresh_module ...                                           [OK]
    test_import_module ...                                                 [OK]
    test_make_bad_fd ...                                                   [OK]
    test_match_test ...                                                    [OK]
    test_python_is_optimized ...                                           [OK]
    test_rmtree ...                                                        [OK]
    test_sortdict ...                                                      [OK]
    test_swap_attr ...                                                     [OK]
    test_swap_item ...                                                     [OK]
    test_temp_cwd ...                                                      [OK]
    test_temp_cwd__name_none ...                                           [OK]
    test_temp_dir ...                                                      [OK]
    test_temp_dir__existing_dir__quiet_default ...                         [OK]
    test_temp_dir__existing_dir__quiet_true ...                            [OK]
    test_temp_dir__forked_child ...                                        [OK]
    test_temp_dir__path_none ...                                           [OK]
    test_unlink ...                                                        [OK]
    test_unload ...                                                        [OK]

===============================================================================
[SKIPPED]
failing buildbots

test.test_support.TestSupport.test_get_original_stdout
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/test/test_support.py", line 393, in test_check__all__
    blacklist=blacklist)
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/test/support/__init__.py", line 2511, in check__all__
    test_case.assertCountEqual(module.__all__, expected)
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/unittest/case.py", line 1183, in assertCountEqual
    self.fail(msg)
  File "/nix/store/bwfygfcdvis9wd1c1v51xwnwhw1hx0a0-python3-3.6.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
builtins.AssertionError: Element counts were not equal:
First has 1, Second has 0:  'SkipTest'

test.test_support.TestSupport.test_check__all__
-------------------------------------------------------------------------------
Ran 39 tests in 0.289s

FAILED (skips=1, failures=1, successes=37)
```

### Version information

- **Version**:       0.33.8
- **Platform**:     NixOS

**Comment by volth** [comment]
@richvdh 

I guess

1. Install ```nix``` (```apt-get install nix``` or ```curl https://nixos.org/nix/install | sh```)
2. ```nix-build --option binary-caches http://cache.nixos.org -E '(import (builtins.fetchTarball https://github.com/peterhoeg/nixpkgs/archive/f/synapse.tar.gz) {}).matrix-synapse```

But it works for me without error

**Comment by richvdh** [comment]
that sounds like it might be a problem with `nix-build`, or the environment, then? I'm struggling to see how the core cpython tests failing can be synapse's fault.
