### ISSUE TITLE
test_metrics fails on both python 2.7 and 3.7

### ISSUE THREAD

**Issue by pvagner** [matrix-org/synapse#4167]
### Description

On both python 2.7 and python 3.7 test_metrics appear to fail for me since Synapse 0.33.8.

### Steps to reproduce

- Download a release
- Make sure dependencies are installed
- and run...

```
$ 	PYTHONPATH=. trial tests
tests.api.test_auth
  AuthTestCase
    test_blocking_mau ...                                                  [OK]
    test_single_insert_fetch ...                                           [OK]

===============================================================================
[SKIPPED]
Disabled by default because it's slow

tests.test_visibility.FilterEventsForServerTestCase.test_large_room
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/tmp/matrix-synapse/src/synapse-0.33.8/tests/test_metrics.py", line 44, in test_basic
    }, self.get_metrics_from_gauge(gauge))
  File "/tmp/matrix-synapse/src/synapse-0.33.8/tests/test_metrics.py", line 78, in get_metrics_from_gauge
    for _, labels, value in r.samples
  File "/tmp/matrix-synapse/src/synapse-0.33.8/tests/test_metrics.py", line 78, in <dictcomp>
    for _, labels, value in r.samples
exceptions.ValueError: too many values to unpack

tests.test_metrics.TestMauLimit.test_basic
-------------------------------------------------------------------------------
Ran 521 tests in 279.820s

FAILED (skips=1, errors=1, successes=519)
```

### Version information

- **Version**:        0.33.8
- **Install method**: git clone
- **Platform**:       Arch linux witch patched glibc running as an OpenVZ container.

**Comment by kyrias** [comment]
I would guess that this is due to Arch having `prometheus_client` 0.4.2.  They switched to a named tuple for the samples in 0.4.0.

**Comment by richvdh** [comment]
oh right. Well, there's a reason we pin to prometheus_client 0.3. Thanks @kyrias .
