### ISSUE TITLE
Can't join rooms or communities

### ISSUE THREAD

**Issue by Eisfunke** [matrix-org/synapse#4196]
### Description

When trying to join a room (not on my server), I get a »No known servers« error. Trying to accept a community invite fails with »Unable to accept invite«.

### Log

When trying to join a room this appears in the log:
```
Nov 17 17:08:38 ruby synapse[21198]: synapse.access.http.8008: [POST-6443] **ip** - 8008 - Received request: POST /_matrix/client/r0/join/**room id**matrix.org?
Nov 17 17:08:38 ruby synapse[21198]: synapse.util.async_helpers: [POST-6443] Acquired uncontended linearizer lock 'member' for key (u'**room id**:matrix.org',)
Nov 17 17:08:38 ruby synapse[21198]: synapse.metrics: [] Collecting gc 0
Nov 17 17:08:38 ruby synapse[21198]: synapse.http.server: [POST-6443] <XForwardedForRequest at 0x7f2f8db46ef0 method=u'POST' uri=u'/_matrix/client/r0/join/**room id**matrix.org?' clientproto=u'HTTP/1.0' site=8008> SynapseError: 404 - No known servers
Nov 17 17:08:38 ruby synapse[21198]: synapse.access.http.8008: [POST-6443] **ip** - 8008 - {**my username**} Processed request: 0.011sec/0.000sec (0.005sec, 0.000sec) (0.001sec/0.002sec/3) 50B 404 "POST /_matrix/client/r0/join/**room id**matrix.org? HTTP/1.0" "**user agent**" [0 dbevts]
```

And when trying to accept a community invite:
```
Nov 17 17:10:51 ruby synapse[21198]: synapse.access.http.8008: [PUT-6461] **ip** - 8008 - Received request: PUT /_matrix/client/r0/groups/**community name**matrix.org/self/accept_invite?
Nov 17 17:10:51 ruby synapse[21198]: synapse.http.matrixfederationclient: [PUT-6461] {POST-O-888} [matrix.org] Sending request: POST matrix://matrix.org/_matrix/federation/v1/groups/**community name**matrix.org/users/**my username**/accept_invite
Nov 17 17:10:51 ruby synapse[21198]: synapse.http.matrixfederationclient: [PUT-6461] {POST-O-888} [matrix.org] Got response headers: 500 Internal Server Error
Nov 17 17:10:51 ruby synapse[21198]: synapse.util.retryutils: [PUT-6461] Connection to matrix.org was unsuccessful (<class 'synapse.api.errors.HttpResponseException'>(500: Internal Server Error)); backoff now 600000
Nov 17 17:10:51 ruby synapse[21198]: synapse.http.server: [PUT-6461] Failed handle request via <function _async_render at 0x7f2fa0c42140>: <XForwardedForRequest at 0x7f2f8db5a6c8 method=u'PUT' uri=u'/_matrix/client/r0/groups/**community name**matrix.org/self/accept_invite?' clientproto=u'HTTP/1.0' site=8008>: Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
_inlineCallbacks(r, g, status)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
File "/usr/lib/python2.7/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
yield h(self, request)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/usr/lib/python2.7/site-packages/synapse/http/server.py", line 316, in _async_render
callback_return = yield callback(request, **kwargs)
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/usr/lib/python2.7/site-packages/synapse/rest/client/v2_alpha/groups.py", line 653, in on_PUT
group_id, requester_user_id, content,
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/usr/lib/python2.7/site-packages/synapse/handlers/groups_local.py", line 289, in accept_invite
get_domain_from_id(group_id), group_id, user_id, content,
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "/usr/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "/usr/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 557, in post_json
ignore_backoff=ignore_backoff,
File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
result = g.send(result)
File "/usr/lib/python2.7/site-packages/synapse/http/matrixfederationclient.py", line 399, in _send_request
response.code, response.phrase, body
synapse.api.errors.HttpResponseException: 500: Internal Server Error
Nov 17 17:10:51 ruby synapse[21198]: synapse.access.http.8008: [PUT-6461] **ip** - 8008 - {**my username**} Processed request: 0.354sec/0.001sec (0.015sec, 0.000sec) (0.000sec/0.002sec/1) 55B 500 "PUT /_matrix/client/r0/groups/**community name**matrix.org/self/accept_invite? HTTP/1.0" "**user agent**" [0 dbevts]
```

### Version information

- **Version**: 0.2.99.4-1
- **Install method**: Package manager (pacman community package on Arch Linux)
- **Platform**: Arch Linux on a vServer I'm renting.
  The client listener is reverse-proxied through nginx, the federation API is direct with the self-signed default certs.
  The federation tester gives no errors, all checks are true.
  nginx sets the X-Forwarded-For header, x_forwarded for the client listener is true, for the federation listener it's false.

The problem started some time ago and persisted. It didn't occur when I installed the server. I can chat in remote rooms I joined before the problem started without any problems.

**Comment by richvdh** [comment]
> Nov 17 17:08:38 ruby synapse[21198]: synapse.access.http.8008: [POST-6443] **ip** - 8008 - Received request: POST /_matrix/client/r0/join/**room id**matrix.org?


You can't join rooms by room ID. Try using a room alias.

**Comment by Eisfunke** [comment]
> You can't join rooms by room ID. Try using a room alias.

Well... how do I do that using Riot?

**Comment by richvdh** [comment]
via the room list, I guess.

**Comment by neilisfragile** [comment]
@Eisfunke You can join a room in three ways:-
 * Have someone invite you
 * Happen to know the room alias and join using the same method you use already 
 * Discover the room via the room directory, which in Riot lives in the bottom left hand corner

For community invite accepting, could it be an occurrence of #2633?

**Comment by Eisfunke** [comment]
I tried to join the room through a community directory. I checked with a room with an alias, it works. So I guess it is an issue that riot shows the join option for aliasless rooms when entering through a community?

Also, the problem with accepting a community invite still doesn't work. Should I open a new issue for that or why was this already closed?

**Comment by turt2live** [comment]
Unjoinable rooms via a community is being tracked as https://github.com/vector-im/riot-web/issues/7339. Problems with accepting a community invite is probably https://github.com/matrix-org/synapse/issues/2633.

**Comment by Eisfunke** [comment]
Okay, thanks.
