### ISSUE TITLE
we seem to accept events with non-ascii event IDs, but later barf on them

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4226]
Obviously, we shouldn't accept them in the first place (but a workaround for the current brokenness of rooms which include such events might be to encode as utf8 rather than ascii)

**Comment by richvdh** [comment]
```
Traceback (most recent call last):
  File "/home/matrix/synapse/synapse/handlers/federation.py", line 385, in on_receive_pdu
    state_res_store=StateResolutionStore(self.store),
  File "/home/matrix/.synapse-py3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse/synapse/state/v1.py", line 108, in resolve_events_with_store
    unconflicted_state, conflicted_state, auth_events, state_map
  File "/home/matrix/synapse/synapse/state/v1.py", line 193, in _resolve_with_state
    conflicted_state, auth_events
  File "/home/matrix/synapse/synapse/state/v1.py", line 240, in _resolve_state_events
    auth_events
  File "/home/matrix/synapse/synapse/state/v1.py", line 256, in _resolve_auth_events
    reverse = [i for i in reversed(_ordered_events(events))]
  File "/home/matrix/synapse/synapse/state/v1.py", line 303, in _ordered_events
    return sorted(events, key=key_func)
  File "/home/matrix/synapse/synapse/state/v1.py", line 301, in key_func
    return -int(e.depth), hashlib.sha1(e.event_id.encode('ascii')).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u205f' in position 42: ordinal not in range(128)
```
