### ISSUE TITLE
"Background process 'user_directory.notify_new_event' threw an exception" spam in logs

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#4275]
```
2018-12-07 20:54:02,778 - synapse.metrics.background_process_metrics - 203 - ERROR - user_directory.notify_new_event-85438- Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/metrics/background_process_metrics.py", line 201, in run
    yield func(*args, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/user_directory.py", line 114, in process
    yield self._unsafe_process()
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/user_directory.py", line 160, in _unsafe_process
    yield self._handle_deltas(deltas)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/user_directory.py", line 364, in _handle_deltas
    yield self._handle_new_user(room_id, state_key, profile)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/handlers/user_directory.py", line 455, in _handle_new_user
    yield self.store.add_profiles_to_user_dir(room_id, {user_id: profile})
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 325, in runInteraction
    *args, **kwargs
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 374, in runWithConnection
    inner_func, *args, **kwargs
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 370, in inner_func
    return func(conn, *args, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 246, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/user_directory.py", line 124, in _add_profiles_to_user_dir_txn
    txn.executemany(sql, args)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 90, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/srv/matrix/synapse/lib/python3.6/site-packages/synapse/storage/_base.py", line 117, in _do_execute
    sql, *args
psycopg2.IntegrityError: duplicate key value violates unique constraint "user_directory_search_user_idx"
DETAIL:  Key (user_id)=(@_gimpnet_dlandau:matrix.org) already exists.
```

**Comment by richvdh** [comment]
dup #4453
