### ISSUE TITLE
test.rest.client.test_consent should be skipped without Jinja

### ISSUE THREAD

**Issue by matoro** [matrix-org/synapse#4286]
### Description

In the test suite, the following tests are appropriately skipped when Jinja, an optional dep, is not available:

```
[SKIPPED]
No Jinja installed

tests.push.test_email.EmailPusherTests.test_sends_email
tests.push.test_http.HTTPPusherTests.test_sends_http
```

However, `tests.rest.client.test_consent` is not, which results in the following traceback:

```
[ERROR]                                                                           
Traceback (most recent call last):                                
  File "/usr/lib64/python2.7/site-packages/twisted/trial/runner.py", line 530, in loadPackage
    module = modinfo.load()                          
  File "/usr/lib64/python2.7/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/usr/lib64/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)                                          
  File "/usr/lib64/python2.7/site-packages/twisted/python/reflect.py", line 255, in _importAndCheckStack                           
    reraise(excValue, excTraceback)                                                                                     
  File "/var/tmp/portage/net-im/synapse-0.33.9/work/synapse-0.33.9/tests/rest/client/test_consent.py", line 20, in <module>
    from synapse.rest.consent import consent_resource                    
  File "/var/tmp/portage/net-im/synapse-0.33.9/work/synapse-0.33.9/synapse/rest/consent/consent_resource.py", line 23, in <module>
    import jinja2                            
exceptions.ImportError: No module named jinja2            
                                                                                 
tests.rest.client.test_consent
```

### Version information

- **Homeserver**: Yes

If not matrix.org:
- **Version**:        0.33.9 
- **Install method**: package manager (in-progress ebuild)
- **Platform**:

Gentoo GNU/Linux x86_64 on physical Intel Core 2 Duo T5850
Linux 4.19.8
Python 2.7.15
Postgres 11.1

**Comment by matoro** [comment]
This looks to be fixed in 0.34.0.
