### ISSUE TITLE
Missing info in upgrade guide for synapse 0.34/python3

### ISSUE THREAD

**Issue by chresan** [matrix-org/synapse#4314]
I've just installed the matrix-synapse-py3 version 0.34 debian package. Starting synapse failed because I missed upgrading the https://github.com/kamax-matrix/matrix-synapse-rest-auth package that belongs to mxisd.

This caused the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 573, in <module>
    main()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 568, in main
    hs = setup(sys.argv[1:])
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 306, in setup
    config_options,
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 328, in load_or_generate_config
    generate_keys=generate_keys,
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 372, in read_config_files
    self.invoke_all("read_config", config)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 150, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/password_auth_providers.py", line 48, in read_config
    "config": provider['config'],
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/util/module_loader.py", line 32, in load_module
    module = importlib.import_module(module)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'rest_auth_provider'
```
The problem was easily fixed by installing the missing rest_auth_provider.py file into the new matrix-synapse virtual-env directory.

Please include a link to the update instructions https://github.com/kamax-matrix/matrix-synapse-rest-auth
in the upgrade guide located at https://github.com/matrix-org/synapse/blob/v0.34.0/UPGRADE.rst#upgrading-to-v0340

**Comment by richvdh** [comment]
Updated https://github.com/matrix-org/synapse/blob/release-v0.34.0/debian/NEWS

**Comment by chresan** [comment]
Great, thank you!
