### ISSUE TITLE
Appservice worker prints a ton of stacktraces randomly

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4332]
0.34 on t2bot.io - python 3.5

```
appservice_1 - 2018-12-28 06:14:50,378 - twisted - 244 - CRITICAL - - Unhandled error in Deferred:
appservice_1 - 2018-12-28 06:14:50,380 - twisted - 244 - CRITICAL - -
Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/storage/_base.py", line 378, in runWithConnection
    defer.returnValue(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/storage/_base.py", line 336, in runInteraction
    defer.returnValue(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/storage/appservice.py", line 309, in get_oldest_unsent_txn
    defer.returnValue(None)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:


--- SNIPPED (last stacktrace repeated for pages ---

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    _background_processes[desc].remove(proc)
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/util/logcontext.py", line 277, in __exit__
    logger.warn("Expected logging context %s has been lost", self)
  File "/usr/lib/python3.5/logging/__init__.py", line 1296, in warn
    self.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1291, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.5/logging/__init__.py", line 1414, in _log
    exc_info, func, extra, sinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 1384, in makeRecord
    sinfo)
  File "/usr/lib/python3.5/logging/__init__.py", line 269, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
  File "/home/matrix/.synapse-py3/lib/python3.5/abc.py", line 191, in __instancecheck__
    return cls.__subclasscheck__(subclass)
  File "/home/matrix/.synapse-py3/lib/python3.5/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/home/matrix/.synapse-py3/lib/python3.5/abc.py", line 226, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/home/matrix/.synapse-py3/lib/python3.5/abc.py", line 197, in __subclasscheck__
    if subclass in cls._abc_cache:
  File "/home/matrix/.synapse-py3/lib/python3.5/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by richvdh** [comment]
This seems likely to be fixed.
