### ISSUE TITLE
synapse_port_db broken, duplicate key on received_transactions_transaction_id_origin_key

### ISSUE THREAD

**Issue by MartijnBraam** [matrix-org/synapse#4357]
### Description

`synapse_port_db` in the 0.34.0-0matrix1 debian package crashes when running the second time to insert events that happened while the first migration step was running.

### Steps to reproduce

- follow https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst
- first run `synapse_port_db` on a copy of homeserver.db while the server continues running (runs fine!)
- run it again on the real homeserver.db with the server shut down.

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:  brixit.nl

If not matrix.org:

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.34.0-0matrix1

- **Install method**: debian package
<!-- examples: package manager/git clone/pip  -->

- **Platform**: debian 9
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

### Output

```
# synapse_port_db --sqlite-database /var/lib/matrix-synapse/homeserver.db --postgres-config /etc/matrix-synapse/homeserver-postgres.yaml 
2019-01-07 17:33:51,870 - synapse.metrics - 374 - INFO - Collecting gc 0
Preparing SQLite3...
Preparing PostgreSQL...
Creating port tables...
Fetching tables...
2019-01-07 17:33:51,901 - synapse_port_db - 525 - INFO - Found 131 tables
Checking on port progress...
2019-01-07 17:33:51,912 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:52,233 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:52,800 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:53,143 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:53,865 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:53,941 - synapse.metrics - 374 - INFO - Collecting gc 1
2019-01-07 17:33:53,952 - synapse.metrics - 374 - INFO - Collecting gc 2
2019-01-07 17:33:54,530 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:55,845 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,037 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,080 - synapse.metrics - 374 - INFO - Collecting gc 0
Copying to postgres...
2019-01-07 17:33:56,225 - synapse_port_db - 259 - INFO - Table feedback: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,225 - synapse_port_db - 259 - INFO - Table monthly_active_users: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table event_signatures: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table rooms: 66/66 (rows 1-67) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table group_summary_rooms: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table users_pending_deactivation: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table e2e_room_keys_versions: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table local_media_repository_thumbnails: 1974/1974 (rows 1-1974) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table remote_media_cache_thumbnails: 7679/7679 (rows 1-7679) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table group_summary_users: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,226 - synapse_port_db - 259 - INFO - Table presence: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,227 - synapse_port_db - 259 - INFO - Table push_rules: 0/17 (rows 1-0) already ported
2019-01-07 17:33:56,227 - synapse_port_db - 259 - INFO - Table user_directory_stream_pos: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,227 - synapse_port_db - 259 - INFO - Table room_tags: 0/4 (rows 1-0) already ported
2019-01-07 17:33:56,227 - synapse_port_db - 259 - INFO - Table user_daily_visits: 0/541 (rows 1-0) already ported
2019-01-07 17:33:56,227 - synapse_port_db - 259 - INFO - Table state_groups_state: 2083326/2083326 (rows 1-6730770) already ported
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table e2e_device_keys_json: 0/9 (rows 1-0) already ported
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table user_directory_search: 0/3076 (rows 1-0) already ported
user_directory_search: 100% (3076/3076)
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table event_search: 182862/182862 (rows 1-182997) already ported
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table local_invites: 0/40 (rows 1-0) already ported
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table users_who_share_rooms: 0/1719 (rows 1-0) already ported
users_who_share_rooms: 100% (1719/1719)
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table threepid_guest_access_tokens: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,228 - synapse_port_db - 259 - INFO - Table events: 319497/319497 (rows -6442-7336333) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table device_lists_outbound_last_success: 0/408 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table device_inbox: 0/814 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table redactions: 998/998 (rows 1-998) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table room_names: 39/39 (rows 1-40) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table open_id_tokens: 0/32 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table group_users: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table background_updates: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table history_visibility: 0/67 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table user_threepids: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table room_tags_revisions: 0/6 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table room_aliases: 0/12 (rows 1-0) already ported
2019-01-07 17:33:56,229 - synapse_port_db - 259 - INFO - Table profiles: 0/27 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table receipts_linearized: 0/4466 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table stream_ordering_to_exterm: 41703/41703 (rows 1-360395) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table event_auth: 415928/415928 (rows 1-525508) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table event_reference_hashes: 325888/325888 (rows 1-388739) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table device_max_stream_id: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table deleted_pushers: 0/5 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table application_services: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table group_attestations_renewals: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table remote_media_cache: 1767/1767 (rows 1-1767) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table pushers: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,230 - synapse_port_db - 259 - INFO - Table push_rules_stream: 41/41 (rows 1-41) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table application_services_state: 0/2 (rows 1-0) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table groups: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table event_to_state_groups: 263035/263035 (rows 1-263101) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table user_directory: 0/3076 (rows 1-0) already ported
user_directory: 100% (3076/3076)
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table public_room_list_stream: 11/11 (rows 1-11) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table event_content_hashes: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,231 - synapse_port_db - 259 - INFO - Table current_state_resets: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table state_events: 138758/138758 (rows 1-175324) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table current_state_delta_stream: 0/236769 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table group_summary_room_categories: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table event_edge_hashes: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table state_groups: 79342/79342 (rows 1-79573) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table appservice_stream_position: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table appservice_room_list: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table pusher_throttle: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,232 - synapse_port_db - 259 - INFO - Table users_in_public_rooms: 0/3062 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table presence_list: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table e2e_room_keys: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table group_invites: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table event_edges: 341311/341311 (rows 1-389441) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table group_summary_roles: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table device_federation_outbox: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table push_rules_enable: 0/15 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table presence_allow_inbound: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table event_json: 324052/324052 (rows 1-375325) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table ex_outlier_stream: 755/755 (rows 1-755) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table user_ips: 0/85 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table destinations: 0/1313 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table event_push_actions_staging: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,233 - synapse_port_db - 259 - INFO - Table ratelimit_override: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table server_tls_certificates: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table user_filters: 0/8 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table federation_stream_position: 0/2 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table remote_profile_cache: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table group_room_categories: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table event_reports: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table receipts_graph: 0/4466 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table transaction_id_to_pdu: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table received_transactions: 2517095/2519644 (rows 1-23090204) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table device_lists_remote_cache: 0/36581 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table device_federation_inbox: 0/44 (rows 1-0) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table room_memberships: 137592/137592 (rows 1-173991) already ported
2019-01-07 17:33:56,234 - synapse_port_db - 259 - INFO - Table access_tokens: 0/37 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table server_signature_keys: 0/2459 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table event_push_summary_stream_ordering: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table room_alias_servers: 0/39 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table application_services_regex: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table event_forward_extremities: 0/68 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table room_depth: 0/66 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table current_state_events: 0/48758 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table presence_stream: 1673/1673 (rows 1-17761401) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table devices: 0/36 (rows 1-0) already ported
2019-01-07 17:33:56,235 - synapse_port_db - 259 - INFO - Table local_group_updates: 0/21 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table event_push_summary: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table local_media_repository_url_cache: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table local_media_repository: 428/428 (rows 1-428) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table guest_access: 0/48 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table state_group_edges: 78126/78126 (rows 1-78126) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table topics: 46/46 (rows 1-47) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table stats_reporting: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table applied_module_schemas: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table group_rooms: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table room_hosts: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table event_push_actions: 0/187 (rows 1-0) already ported
2019-01-07 17:33:56,236 - synapse_port_db - 259 - INFO - Table account_data: 0/2 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table event_backward_extremities: 0/286 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table state_forward_extremities: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table server_keys_json: 0/2467 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table erased_users: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table room_account_data: 0/65 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table blocked_rooms: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table users: 27/27 (rows 1-27) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table device_lists_stream: 0/43231 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table event_destinations: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table group_roles: 0/0 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table device_lists_outbound_pokes: 0/250 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table application_services_txns: 0/129559 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table group_attestations_remote: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,237 - synapse_port_db - 259 - INFO - Table device_lists_remote_extremeties: 0/1650 (rows 1-0) already ported
2019-01-07 17:33:56,238 - synapse_port_db - 259 - INFO - Table account_data_max_stream_id: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,238 - synapse_port_db - 259 - INFO - Table e2e_one_time_keys_json: 0/436 (rows 1-0) already ported
2019-01-07 17:33:56,238 - synapse_port_db - 259 - INFO - Table local_group_membership: 0/1 (rows 1-0) already ported
2019-01-07 17:33:56,238 - synapse_port_db - 259 - INFO - Table rejections: 216/216 (rows 1-14686) already ported
2019-01-07 17:33:56,238 - synapse.metrics - 374 - INFO - Collecting gc 0
user_directory_stream_pos: 100% (1/1)
2019-01-07 17:33:56,242 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,248 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,263 - synapse.metrics - 374 - INFO - Collecting gc 0
room_tags: 100% (4/4)
2019-01-07 17:33:56,286 - synapse.metrics - 374 - INFO - Collecting gc 0
local_invites: 100% (40/40)
push_rules: 100% (17/17)
e2e_device_keys_json: 100% (9/9)
room_tags_revisions: 100% (6/6)
room_aliases: 100% (12/12)
2019-01-07 17:33:56,306 - synapse.metrics - 374 - INFO - Collecting gc 0
history_visibility: 100% (67/67)
open_id_tokens: 100% (32/32)
2019-01-07 17:33:56,316 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,317 - synapse.metrics - 374 - INFO - Collecting gc 1
profiles: 100% (27/27)
device_max_stream_id: 100% (1/1)
2019-01-07 17:33:56,329 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,340 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,353 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,365 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,375 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,386 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,395 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,411 - synapse.metrics - 374 - INFO - Collecting gc 0
pushers: 100% (1/1)
deleted_pushers: 100% (5/5)
application_services_state: 100% (2/2)
group_attestations_renewals: 100% (1/1)
2019-01-07 17:33:56,428 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,444 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,456 - synapse.metrics - 374 - INFO - Collecting gc 0
2019-01-07 17:33:56,456 - synapse.metrics - 374 - INFO - Collecting gc 1
2019-01-07 17:33:56,466 - synapse.metrics - 374 - INFO - Collecting gc 0
user_daily_visits: 100% (541/541)
appservice_stream_position: 100% (1/1)
device_lists_outbound_last_success: 100% (408/408)
push_rules_enable: 100% (15/15)
device_inbox: 100% (814/814)
user_ips: 100% (85/85)
federation_stream_position: 100% (2/2)
user_filters: 100% (8/8)
receipts_linearized: 22% (1000/4466)
device_federation_inbox: 100% (44/44)
2019-01-07 17:33:56,506 - synapse_port_db - 176 - ERROR - Failed to insert: received_transactions
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 174, in insert_many_txn
    txn.executemany(sql, rows)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 91, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/usr/lib/python2.7/dist-packages/synapse/storage/_base.py", line 118, in _do_execute
    sql, *args
IntegrityError: duplicate key value violates unique constraint "received_transactions_transaction_id_origin_key"
DETAIL:  Key (transaction_id, origin)=(1546310743597, thebeckmeyers.xyz) already exists.

2019-01-07 17:33:56,508 - synapse_port_db - 552 - ERROR - 
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 542, in run
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
FirstError: FirstError[#84, [Failure instance: Traceback: <class 'psycopg2.IntegrityError'>: duplicate key value violates unique constraint "received_transactions_transaction_id_origin_key"
DETAIL:  Key (transaction_id, origin)=(1546310743597, thebeckmeyers.xyz) already exists.

/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:500:errback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:567:_startRunCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:653:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1442:gotResult
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1384:_inlineCallbacks
/usr/lib/python2.7/dist-packages/twisted/python/failure.py:422:throwExceptionIntoGenerator
/usr/bin/synapse_port_db:352:handle_table
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py:307:_runWithConnection
/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py:298:_runWithConnection
/usr/bin/synapse_port_db:140:r
/usr/bin/synapse_port_db:340:insert
/usr/bin/synapse_port_db:174:insert_many_txn
/usr/lib/python2.7/dist-packages/synapse/storage/_base.py:91:executemany
/usr/lib/python2.7/dist-packages/synapse/storage/_base.py:118:_do_execute
]]
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 542, in run
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
FirstError: FirstError[#84, [Failure instance: Traceback: <class 'psycopg2.IntegrityError'>: duplicate key value violates unique constraint "received_transactions_transaction_id_origin_key"
DETAIL:  Key (transaction_id, origin)=(1546310743597, thebeckmeyers.xyz) already exists.

/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:500:errback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:567:_startRunCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:653:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1442:gotResult
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:1384:_inlineCallbacks
/usr/lib/python2.7/dist-packages/twisted/python/failure.py:422:throwExceptionIntoGenerator
/usr/bin/synapse_port_db:352:handle_table
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:250:inContext
/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/lib/python2.7/dist-packages/twisted/python/context.py:122:callWithContext
/usr/lib/python2.7/dist-packages/twisted/python/context.py:85:callWithContext
/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py:307:_runWithConnection
/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py:298:_runWithConnection
/usr/bin/synapse_port_db:140:r
/usr/bin/synapse_port_db:340:insert
/usr/bin/synapse_port_db:174:insert_many_txn
/usr/lib/python2.7/dist-packages/synapse/storage/_base.py:91:executemany
/usr/lib/python2.7/dist-packages/synapse/storage/_base.py:118:_do_execute
]]

```

**Comment by avignat** [comment]
I had the same issue after one incomplete run of the script.
I solved the problem by dropping the database and start over.

**Comment by richvdh** [comment]
I'm rather assuming this is no longer a problem. If anyone sees it again, we can reopen.
