### ISSUE TITLE
matrix-corporal, weechat-matrix: Failure to log in

### ISSUE THREAD

**Issue by x-0n** [matrix-org/synapse#4378]
### Description

matrix-corporal fails to reconcile, also weechat-matrix fails to log in. Symptoms are the same in server log.

### Steps to reproduce

- update to synapse:v0.34.1.1-py3 
- try to log in with weechat-matrix
- check matrix-corporal log ("failed to reconcile")

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
```
2019-01-11 16:13:04,323 - synapse.http.server - 112 - ERROR - POST-107 - Failed handle request via <function JsonResource._async_render at 0x7ff4992242f0>: <XForwardedForRequest at 0x7ff4952d72b0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/auth.py", line 664, in validate_login
    qualified_user_id, password,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 140, in on_POST
    result = yield self._do_other_login(login_submission)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v1/login.py", line 220, in _do_other_login
    login_submission,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/auth.py", line 664, in validate_login
    qualified_user_id, password,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/shared_secret_authenticator.py", line 43, in check_password
    computed_hmac = hmac.new(self.sharedSecret, user_id, hashlib.sha512).hexdigest().decode('utf-8')
  File "/usr/local/lib/python3.6/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/lib/python3.6/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
builtins.TypeError: key: expected bytes or bytearray, but got 'str'
```
### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 
If not matrix.org: staubsaugertraum.de

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 
synapse-v0.34.1.1-py3

- **Install method**: 
docker-ansible-matrix-deploy

- **Platform**: 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

```
$ uname -a
Linux hostname.domain 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
running on KVM (Proxmox).

**Comment by x-0n** [comment]
As per Slavi in #Synapse-Admins:matrix.org

> Slavi
> 17:50
> ￼richvdh: he's using matrix-synapse-shared-secret-auth. But it appears that he's using an outdated version which doesn't support Python 3.6.
> 
> Upgrading to matrix-synapse-shared-secret-auth v1.0.1 should fix the problem.


My issue was that I had apparently copied an absolute download link to matrix-synapse-shared-secret-auth from the template vars file:

``` 
/matrix-docker-ansible-deploy/inventory/host_vars/matrix.staubsaugertraum.de/vars.yml:matrix_synapse_ext_password_provider_shared_secret_auth_download_url: "https://raw.githubusercontent.com/devture/matrix-synapse-shared-secret-auth/1.0/shared_secret_authenticator.py"
```

Commented out this line and re-ran the playbook, now everything works.
