### ISSUE TITLE
"Failed to contact identity server" when deactivating account

### ISSUE THREAD

**Issue by Valodim** [matrix-org/synapse#4383]
A user complained he is getting "unknown errors" in Riot when trying to disable an old account. I checked the logs and there is a relevant stack trace:

```
2019-01-14 12:01:36,512 - synapse.handlers.deactivate_account - 82 - ERROR - POST-860975- Failed to remove threepid from ID server
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/identity.py", line 186, in try_unbind_threepid
    headers,
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/client.py", line 380, in post_json_get_json
    raise HttpResponseException(response.code, response.phrase, body)
synapse.api.errors.HttpResponseException: 502: b'Proxy Error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/deactivate_account.py", line 76, in deactivate_account
    'address': threepid['address'],
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/identity.py", line 195, in try_unbind_threepid
    raise SynapseError(502, "Failed to contact identity server")
synapse.api.errors.SynapseError: 502: Failed to contact identity server
```

The user has a validated email address in `user_threepids`, and very likely left the identity server setting at `vector.im` when logging in to riot. The `trusted_third_party_id_servers` setting in homeserver.yaml lists `matrix.org`, `riot.im`, and `vector.im`. The `users_pending_deactivation` table is empty. The user says their account left all rooms, but they can still log in.

This is synapse 0.34.0.1-0matrix1 debian package running on a debian stable, on matrix.stratum0.org.

**Comment by aaronraimist** [comment]
Yes you need to remove riot.im from the list of trusted identity servers (was mentioned in the UPGRADE guide for 0.34.0 https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst#upgrading-to-v0340)

**Comment by Valodim** [comment]
`riot.im` is only the second entry in that list? but I'll remove it and see if that works. thanks for the hint.

**Comment by Valodim** [comment]
Seems to have worked. I understand it's in the readme, but in the interest of reducing support volume I'm sure it would be nice to have more helpful error log messages. Or simply ignore riot.im? Either way, there are probably a lot of HSes out there right now with broken account disabling functionality.
