### ISSUE TITLE
Exceptions with `list.remove(x): x not in list`

### ISSUE THREAD

**Issue by jo-so** [matrix-org/synapse#4418]
### Description

I'm seeing many exceptions in the log:
```
twisted: [] Unhandled Error
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/_base.py", line 104, in run
    reactor.run()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/base.py", line 1276, in mainLoop
    self.runUntilCurrent()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/metrics/__init__.py", line 349, in f
    ret = func(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/task.py", line 671, in _tick
    taskObj._oneWorkUnit()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/task.py", line 521, in _oneWorkUnit
    self._completeWith(TaskFailed(), Failure())
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/task.py", line 477, in _completeWith
    self._cooperator._removeTask(self)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/task.py", line 644, in _removeTask
    self._tasks.remove(task)
builtins.ValueError: list.remove(x): x not in list
```

### Version information

- **Homeserver**: alea.gnuu.de

If not matrix.org:

- **Version**: 0.34.1.1++1+stretch1
- **Install method**: Debian package manager
- **Platform**: a qemu VM, no container

**Comment by jo-so** [comment]
This is not the only exception I see. Since yesterday, Synapse continuously gets victim of the OOM killer. I don't know what happened, but since yesterday Synapse is unusable and I'm seeing many exceptions in the log.

**Comment by richvdh** [comment]
As in #3981: this exception is a harmless side-effect of the (harmful) situation of synapse being overloaded.

**Comment by Ralith** [comment]
Flooding the logs with "harmless side-effect" errors makes it very difficult to find the actual errors causing synapse to malfunction.

**Comment by richvdh** [comment]
well, yes. That's why this bug is open.

**Comment by richvdh** [comment]
It seems that @jchenggggg has fixed the bug in Twisted (thank you!); it'll be interesting to confirm if this stops happening once the fix is released.

**Comment by Ralith** [comment]
I actually can't remember the last time I saw this on my HS.

**Comment by richvdh** [comment]
well, let's assume it's fixed until proven otherwise.
