### ISSUE TITLE
Server Crash / Memory Leak on Invitation from Email

### ISSUE THREAD

**Issue by marcotuna** [matrix-org/synapse#4424]
### Description

Today a member from my company invited other to a room, usually I do **@username:companyname.com** however he did username@companyname.com which triggered an email from Riot, he opened the email and boom, my server with 8 GB RAM was instantly full, logging without stopping errors

### Steps to reproduce

- On Riot.IM connected to a custom HomeServer inside a Room
- Send Invitation to an e-mail address
- Went to mail address and had a new message from noreply@riot.im
- Clicked on the link:

https://riot.im/app/#/room/!NDdUOhYnkGMauzMkwh:IHADTOREMOVETHIS.COM?email=USERNAME@IHADTOREMOVETHIS.COM&signurl=https://vector.im/_matrix/identity/api/v1/sign-ed25519?token=TOKENDATA&private_key=PRIVATEKEYDATA&room_name=#ROOMNAME&room_avatar_url=&inviter_name=PERSONINVITING&guest_access_token=&guest_user_id=

```
2019-01-21 14:52:11,306 - synapse.http.matrixfederationclient - 384 - INFO - POST-3200- {GET-O-109} [matrix.org] Got response headers: 200 OK
2019-01-21 14:52:11,307 - synapse.http.matrixfederationclient - 170 - INFO - POST-3200- {GET-O-109} [matrix.org] Completed: 200 OK
2019-01-21 14:52:11,308 - synapse.util.async_helpers - 205 - INFO - POST-3200- Acquired uncontended linearizer lock 'member' for key ('!tDRGDwZwQnlkowsjsm:matrix.org',)
2019-01-21 14:52:11,315 - synapse.http.matrixfederationclient - 320 - INFO - POST-3200- {GET-O-110} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/make_join/%21tDRGDwZwQnlkowsjsm%3Amatrix.org/%40USERNAME%3AIHADTOOMITTHIS.COM?ver=vdh-test-version&ver=state-v2-test&ver=1
2019-01-21 14:52:11,440 - synapse.http.matrixfederationclient - 384 - INFO - POST-3200- {GET-O-110} [matrix.org] Got response headers: 200 OK
2019-01-21 14:52:11,441 - synapse.http.matrixfederationclient - 170 - INFO - POST-3200- {GET-O-110} [matrix.org] Completed: 200 OK
2019-01-21 14:52:11,444 - synapse.http.matrixfederationclient - 320 - INFO - POST-3200- {PUT-O-111} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v1/send_join/%21tDRGDwZwQnlkowsjsm%3Amatrix.org/%24154808233173QAFFQ%3AIHADTOOMITTHIS.COM
2019-01-21 14:52:11,472 - synapse.metrics - 374 - INFO - - Collecting gc 0
2019-01-21 14:52:12,087 - synapse.handlers.typing - 89 - INFO - - Checking for typing timeouts
2019-01-21 14:52:12,092 - synapse.handlers.presence - 350 - INFO - - Handling presence timeouts
2019-01-21 14:52:13,327 - synapse.http.matrixfederationclient - 384 - INFO - POST-3200- {PUT-O-111} [matrix.org] Got response headers: 200 OK
2019-01-21 14:52:13,749 - synapse.http.matrixfederationclient - 170 - INFO - POST-3200- {PUT-O-111} [matrix.org] Completed: 200 OK
2019-01-21 14:52:14,027 - synapse.crypto.keyring - 117 - WARNING - POST-3200- Request from scal.plootarg.net: no supported signature keys
2019-01-21 14:52:14,028 - synapse.crypto.keyring - 230 - INFO - POST-3200- Waiting for existing lookups for ['scal.plootarg.net'] to complete [loop 1]
2019-01-21 14:52:14,029 - synapse.crypto.keyring - 688 - ERROR - POST-3200- Got Exception when downloading keys for scal.plootarg.net: SynapseError 400: Not signed with a supported algorithm
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/crypto/keyring.py", line 674, in _handle_key_deferred
    _, key_id, verify_key = yield verify_request.deferred
synapse.api.errors.SynapseError: 400: Not signed with a supported algorithm
2019-01-21 14:52:14,440 - twisted - 244 - ERROR - POST-3200- --- Logging error ---
2019-01-21 14:52:14,664 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:14,665 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-01-21 14:52:14,665 - twisted - 244 - ERROR - POST-3200-     result = g.send(result)
2019-01-21 14:52:14,666 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 172, in _handle_json_response
2019-01-21 14:52:14,667 - twisted - 244 - ERROR - POST-3200-     defer.returnValue(body)
2019-01-21 14:52:14,667 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
2019-01-21 14:52:14,668 - twisted - 244 - ERROR - POST-3200-     raise _DefGen_Return(val)
2019-01-21 14:52:14,699 - twisted - 244 - ERROR - POST-3200- --- Logging error ---
2019-01-21 14:52:14,907 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:14,908 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-01-21 14:52:14,909 - twisted - 244 - ERROR - POST-3200-     result = g.send(result)
2019-01-21 14:52:14,910 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 172, in _handle_json_response
2019-01-21 14:52:14,911 - twisted - 244 - ERROR - POST-3200-     defer.returnValue(body)
2019-01-21 14:52:14,911 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
2019-01-21 14:52:14,912 - twisted - 244 - ERROR - POST-3200-     raise _DefGen_Return(val)
2019-01-21 14:52:14,934 - twisted - 244 - ERROR - POST-3200- --- Logging error ---
2019-01-21 14:52:15,125 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:15,126 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-01-21 14:52:15,126 - twisted - 244 - ERROR - POST-3200-     result = g.send(result)
2019-01-21 14:52:15,127 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 172, in _handle_json_response
2019-01-21 14:52:15,128 - twisted - 244 - ERROR - POST-3200-     defer.returnValue(body)
2019-01-21 14:52:15,129 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
2019-01-21 14:52:15,129 - twisted - 244 - ERROR - POST-3200-     raise _DefGen_Return(val)
2019-01-21 14:52:15,151 - twisted - 244 - ERROR - POST-3200- --- Logging error ---
2019-01-21 14:52:15,338 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:15,339 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-01-21 14:52:15,340 - twisted - 244 - ERROR - POST-3200-     result = g.send(result)
2019-01-21 14:52:15,341 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 172, in _handle_json_response
2019-01-21 14:52:15,341 - twisted - 244 - ERROR - POST-3200-     defer.returnValue(body)
2019-01-21 14:52:15,341 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
2019-01-21 14:52:15,342 - twisted - 244 - ERROR - POST-3200-     raise _DefGen_Return(val)
2019-01-21 14:52:15,363 - twisted - 244 - ERROR - POST-3200- --- Logging error ---
...
2019-01-21 14:52:21,550 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,551 - twisted - 244 - ERROR - POST-3200- During handling of the above exception, another exception occurred:
2019-01-21 14:52:21,551 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,551 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:21,551 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 494, in _try_destination_list
2019-01-21 14:52:21,552 - twisted - 244 - ERROR - POST-3200-     res = yield callback(destination)
2019-01-21 14:52:21,552 - twisted - 244 - ERROR - POST-3200- twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'synapse.api.errors.SynapseError'>: 401: No key for scal.plootarg.net with id []
2019-01-21 14:52:21,552 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/synapse/util/logcontext.py:478:g
2019-01-21 14:52:21,553 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/synapse/util/logcontext.py:497:run_in_background
2019-01-21 14:52:21,553 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1613:unwindGenerator
2019-01-21 14:52:21,553 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1529:_cancellableInlineCallbacks
2019-01-21 14:52:21,553 - twisted - 244 - ERROR - POST-3200- --- <exception caught here> ---
2019-01-21 14:52:21,554 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
2019-01-21 14:52:21,554 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
2019-01-21 14:52:21,554 - twisted - 244 - ERROR - POST-3200- /usr/local/lib/python3.6/site-packages/synapse/crypto/keyring.py:693:_handle_key_deferred
2019-01-21 14:52:21,555 - twisted - 244 - ERROR - POST-3200- ]]
2019-01-21 14:52:21,555 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,555 - twisted - 244 - ERROR - POST-3200- During handling of the above exception, another exception occurred:
2019-01-21 14:52:21,556 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,556 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:21,556 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/logging/__init__.py", line 995, in emit
2019-01-21 14:52:21,557 - twisted - 244 - ERROR - POST-3200-     stream.write(msg)
2019-01-21 14:52:21,557 - twisted - 244 - ERROR - POST-3200- UnicodeEncodeError: 'ascii' codec can't encode character '\u0e07' in position 141852: ordinal not in range(128)
2019-01-21 14:52:21,557 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,557 - twisted - 244 - ERROR - POST-3200- During handling of the above exception, another exception occurred:
2019-01-21 14:52:21,558 - twisted - 244 - ERROR - POST-3200- 
2019-01-21 14:52:21,558 - twisted - 244 - ERROR - POST-3200- Traceback (most recent call last):
2019-01-21 14:52:21,558 - twisted - 244 - ERROR - POST-3200-   File "/usr/local/lib/python3.6/logging/__init__.py", line 995, in emit
2019-01-21 14:52:21,558 - twisted - 244 - ERROR - POST-3200-     stream.write(msg)
2019-01-21 14:52:21,559 - twisted - 244 - ERROR - POST-3200- UnicodeEncodeError: 'ascii' codec can't encode character '\u0e07' in position 141335: ordinal not in range(128)
2019-01-21 14:52:21,559 - twisted - 244 - ERROR - POST-3200- 
```

**I also have a custom authentication using a REST API**

### Version information

- **Version**: 
0.34.1.1

- **Install method**: 
pkg install py36-matrix-synapse

- **Platform**: 
FreeBSD 11.2-RELEASE-p4

**Comment by marcotuna** [comment]
@richvdh
Adding to log.config: `encoding: utf8` solved this issue, the server no longer crashes

Thanks!
