### ISSUE TITLE
Workers no longer start up on latest develop due to new TLS stuff

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#4479]
From IRL:

> @hawkowl:  I made loading the key async
> @hawkowl: So none of the workers do it

Stack trace:

```
2019-01-25 14:34:59,946 - root - 211 - WARNING - None - ***** STARTING SERVER *****
2019-01-25 14:34:59,997 - root - 214 - WARNING - None - Server /home/matrix/synapse/synapse/app/media_repository.py version 0.34.1.1 (b=matrix-org-hotfixes,53d25116d)
2019-01-25 14:34:59,997 - root - 216 - INFO - None - Server hostname: matrix.org
2019-01-25 14:35:01,918 - twisted - 242 - WARNING - None - /home/matrix/.synapse-py3/lib/python3.6/site-packages/psycopg2/__init__.py:144: builtins.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-i
2019-01-25 14:35:01,919 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-01-25 14:35:01,919 - twisted - 242 - ERROR -  -   File "/home/matrix/hawkowl/Python-3.6.6/Lib/runpy.py", line 193, in _run_module_as_main
2019-01-25 14:35:01,919 - twisted - 242 - ERROR -  -     "__main__", mod_spec)
2019-01-25 14:35:01,919 - twisted - 242 - ERROR -  -   File "/home/matrix/hawkowl/Python-3.6.6/Lib/runpy.py", line 85, in _run_code
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -     exec(code, run_globals)
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -   File "/home/matrix/synapse/synapse/app/media_repository.py", line 180, in <module>
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -     start(sys.argv[1:])
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -   File "/home/matrix/synapse/synapse/app/media_repository.py", line 154, in start
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -     tls_server_context_factory = context_factory.ServerContextFactory(config)
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -   File "/home/matrix/synapse/synapse/crypto/context_factory.py", line 34, in __init__
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -     self.configure_context(self._context, config)
2019-01-25 14:35:01,920 - twisted - 242 - ERROR -  -   File "/home/matrix/synapse/synapse/crypto/context_factory.py", line 48, in configure_context
2019-01-25 14:35:01,921 - twisted - 242 - ERROR -  -     context.use_privatekey(config.tls_private_key)
2019-01-25 14:35:01,921 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse-py3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1000, in use_privatekey
2019-01-25 14:35:01,921 - twisted - 242 - ERROR -  -     raise TypeError("pkey must be a PKey instance")
2019-01-25 14:35:01,921 - twisted - 242 - ERROR -  - TypeError: pkey must be a PKey instance
```

**Comment by erikjohnston** [comment]
Probably introduced by #4384 ?

**Comment by hawkowl** [comment]
yes :(

**Comment by hawkowl** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/4492 but I'd like it verified before I close this.
