### ISSUE TITLE
types.py conflicts with built in python types module

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#4491]
```
$ python synapse/python_dependencies.py 
Traceback (most recent call last):
  File "synapse/python_dependencies.py", line 17, in <module>
    import logging
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/dave/matrix/synapse/synapse/types.py", line 15, in <module>
    import string
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 78, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 88, in Template
    flags = _re.IGNORECASE
AttributeError: module 're' has no attribute 'IGNORECASE'
```

**Comment by dbkr** [comment]
Never mind - this was something going very wrong between virtualenvs.

**Comment by dbkr** [comment]
It turns out it's not my broken virtualenvs - this is because synapse has a file called `types.py` which, because python doesn't believe in namespaces, gets imported instead of the python `types` module by all sorts of internal python things:

```
(venv) dave@yaw ~/matrix/synapse $ cat synapse/test.py 
import string
(venv) dave@yaw ~/matrix/synapse $ python synapse/test.py 
Traceback (most recent call last):
  File "synapse/test.py", line 1, in <module>
    import string
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/string.py", line 52, in <module>
    import re as _re
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/re.py", line 122, in <module>
    import enum
  File "/Users/dave/matrix/synapse/venv/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "/Users/dave/matrix/synapse/synapse/types.py", line 19, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

**Comment by dbkr** [comment]
FTR, the workaround to this it to do `python -m synapse.python_dependencies` rather than `python synapse/python_dependencies.py` which presumably does some subtly different yet pivotal thing with module search paths.

**Comment by richvdh** [comment]
the correct thing to do nowadays is to install with `pip install .` rather than try and use python_dependencies. AFAIK all of the documentation now says so, so I don't think this is an issue any more.
