### ISSUE TITLE
Consent template error does not kill the process, or prevent it from starting

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4500]
Synapse version: `develop` at time of writing.

The following happened *after* `synctl start` passed and the server was left running, checking only for typing timeouts.

```
2019-01-28 21:17:00,100 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-01-28 21:17:00,101 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 394, in start
2019-01-28 21:17:00,101 - twisted - 242 - ERROR -  -     hs.start_listening()
2019-01-28 21:17:00,101 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 245, in start_listening
2019-01-28 21:17:00,101 - twisted - 242 - ERROR -  -     self._listener_http(config, listener)
2019-01-28 21:17:00,102 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 101, in _listener_http
2019-01-28 21:17:00,102 - twisted - 242 - ERROR -  -     name, res.get("compress", False),
2019-01-28 21:17:00,102 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 183, in _configure_named_resource
2019-01-28 21:17:00,102 - twisted - 242 - ERROR -  -     consent_resource = ConsentResource(self)
2019-01-28 21:17:00,102 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/rest/consent/consent_resource.py", line 111, in __init__
2019-01-28 21:17:00,103 - twisted - 242 - ERROR -  -     consent_template_directory,
2019-01-28 21:17:00,103 - twisted - 242 - ERROR -  - ConfigError: Could not find template directory '/res/templates/privacy'
2019-01-28 21:17:00,104 - synapse.handlers.deactivate_account - 144 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-01-28 21:17:00,111 - synapse.metrics - 374 - INFO -  - Collecting gc 0
2019-01-28 21:17:00,144 - twisted - 242 - CRITICAL -  - Unhandled error in Deferred:
2019-01-28 21:17:00,145 - twisted - 242 - CRITICAL -  -
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 407, in start
    sys.exit(1)
SystemExit: 1
```

**Comment by richvdh** [comment]
This was introduced by https://github.com/matrix-org/synapse/pull/4384/files#diff-01aac508ef38061957e6fb961582e5ceL364; fixed by #4512.
