### ISSUE TITLE
Consent listener activated but lack of user_consent section does not stop the homeserver or prevent it from starting

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4502]
Synapse version: `develop` at time of writing.

Likely same cause as #4500, just a different startup requirement:

```
2019-01-28 21:23:35,910 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-01-28 21:23:35,911 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 394, in start
2019-01-28 21:23:35,911 - twisted - 242 - ERROR -  -     hs.start_listening()
2019-01-28 21:23:35,911 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 245, in start_listening
2019-01-28 21:23:35,911 - twisted - 242 - ERROR -  -     self._listener_http(config, listener)
2019-01-28 21:23:35,912 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 101, in _listener_http
2019-01-28 21:23:35,912 - twisted - 242 - ERROR -  -     name, res.get("compress", False),
2019-01-28 21:23:35,912 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 183, in _configure_named_resource
2019-01-28 21:23:35,912 - twisted - 242 - ERROR -  -     consent_resource = ConsentResource(self)
2019-01-28 21:23:35,912 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/rest/consent/consent_resource.py", line 100, in __init__
2019-01-28 21:23:35,913 - twisted - 242 - ERROR -  -     "Consent resource is enabled but user_consent section is "
2019-01-28 21:23:35,913 - twisted - 242 - ERROR -  - ConfigError: Consent resource is enabled but user_consent section is missing in config file.
2019-01-28 21:23:35,914 - synapse.handlers.deactivate_account - 144 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-01-28 21:23:35,916 - synapse.metrics - 374 - INFO -  - Collecting gc 0
2019-01-28 21:23:35,944 - twisted - 242 - CRITICAL -  - Unhandled error in Deferred:
2019-01-28 21:23:35,944 - twisted - 242 - CRITICAL -  -
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 407, in start
    sys.exit(1)
SystemExit: 1

```

**Comment by richvdh** [comment]
This was also introduced by This was introduced by https://github.com/matrix-org/synapse/pull/4384/files#diff-01aac508ef38061957e6fb961582e5ceL364.

**Comment by neilisfragile** [comment]
Fixed by #4512?

**Comment by richvdh** [comment]
no, I don't think so.

**Comment by richvdh** [comment]
Related: #4543
