### ISSUE TITLE
DataStore has no attribute updates (during upsert_safety_check)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4504]
Synapse version: `develop` as of writing

```
2019-01-28 21:47:55,708 - synapse.metrics - 374 - INFO -  - Collecting gc 0
2019-01-28 21:47:55,755 - synapse.metrics.background_process_metrics - 203 - ERROR - upsert_safety_check-0 - Background process 'upsert_safety_check' threw an exception
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/metrics/background_process_metrics.py", line 201, in run
    yield func(*args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 239, in _check_safe_to_upsert
    if self.updates:
AttributeError: 'DataStore' object has no attribute 'updates'
```

**Comment by hawkowl** [comment]
oops (my fault)

**Comment by hawkowl** [comment]
fixed!
