### ISSUE TITLE
Cannot login an existant user (but registration work fine)

### ISSUE THREAD

**Issue by eauchat** [matrix-org/synapse#4529]
Not 100% sure it's a bug, but I can't see what I'd be doing wrong here.

I installed synapse through yunohost and the process worked fine, I can access the matrix server, it says everything is ok. Then I used riot client to create a user, and everything worked fine, I could use this user to communicate with other matrix users on other servers.
The problem is when I log out, then I cannot log in again.
I can create any user, I just never can log with them again other time than the first login that happens automatically after registration.

When I try to log in, it says "Error: Problem communicating with the given homeserver. (M_UNKNOWN)", and synapse gives the following logs:
```
2019-01-30 10:58:18,020 - synapse.access.https.8448 - 302 - INFO - OPTIONS-188- ::ffff:192.168.122.1 - 8448 - {None} Processed request: 0.000sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "OPTIONS /_matrix/client/r0/login HTTP/1.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" [0 dbevts]
2019-01-30 10:58:18,062 - synapse.access.https.8448 - 233 - INFO - POST-189- ::ffff:192.168.122.1 - 8448 - Received request: POST /_matrix/client/r0/login
2019-01-30 10:58:18,062 - synapse.rest.client.v1.login - 178 - INFO - POST-189- Got login request with identifier: {'user': 'test2', 'type': 'm.id.user'}, medium: None, address: None, user: 'test2'
2019-01-30 10:58:18,064 - synapse.storage._base - 319 - WARNING - - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
2019-01-30 10:58:18,065 - synapse.storage._base - 355 - WARNING - - Starting db connection from sentinel context: metrics will be lost
2019-01-30 10:58:18,301 - synapse.http.server - 112 - ERROR - - Failed handle request via <function JsonResource._async_render at 0x7f39865b68c8>: <SynapseRequest at 0x7f397c01a9b0 method='POST' uri='/_matrix/client/r0/login' clientproto='HTTP/1.1' site=8448>: Traceback (most recent call last):
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/login.py", line 155, in on_POST
    result = yield self._do_other_login(login_submission)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/login.py", line 231, in _do_other_login
    login_submission,
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/auth.py", line 709, in validate_login
    qualified_user_id, password,
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/auth.py", line 743, in _check_local_password
    result = yield self.validate_hash(password, password_hash)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/util/logcontext.py", line 633, in g
    return f(*args, **kwargs)
  File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/util/logcontext.py", line 289, in __exit__
    self.parent_context._resource_usage += self._resource_usage
builtins.AttributeError: 'Sentinel' object has no attribute '_resource_usage'
2019-01-30 10:58:18,304 - synapse.access.https.8448 - 302 - INFO - POST-189- ::ffff:192.168.122.1 - 8448 - {None} Processed request: 0.242sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 67B 500 "POST /_matrix/client/r0/login HTTP/1.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" [0 dbevts]
```

I talked with yunohost developers who recommended me to come here, saying the issue is probably coming from synapse directly. I also posted in #synapse:matrix.org room but without much result.

**Comment by eauchat** [comment]
Reinstalling the app somehow solved the issue.
