### ISSUE TITLE
During config parsing, when `tls_fingerprints` is specified as an empty value, the server crashes

### ISSUE THREAD

**Issue by abeluck** [matrix-org/synapse#4550]
### Description

During config parsing, when `tls_fingerprints` is specified as an empty value, the server crashes.

Ideally the empty value would be interpreted as `[]` and continue merrily along.

```
Feb 02 13:36:35 ip-10-55-1-131 python[3019]: Traceback (most recent call last):
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     "__main__", mod_spec)
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     exec(code, run_globals)
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 576, in <module>
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     main()
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 571, in main
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     hs = setup(sys.argv[1:])
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 312, in setup
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     config_options,
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 356, in load_or_generate_config
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     generate_keys=generate_keys,
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 402, in read_config_files
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     self.invoke_all("read_config", config)
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 146, in invoke_all
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     results.append(getattr(cls, name)(self, *args, **kargs))
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/tls.py", line 58, in read_config
Feb 02 13:36:35 ip-10-55-1-131 python[3019]:     sha256_fingerprints = set(f["sha256"] for f in self.tls_fingerprints)
Feb 02 13:36:35 ip-10-55-1-131 python[3019]: TypeError: 'NoneType' object is not iterable
```

### Steps to reproduce

- Configure synapse with the line:
    ```yaml
        tls_fingerprints:
    ```
- Start the server
- Observe the stacktrace

### Version information

Found during local testing

- **Version**: 

matrix-synapse-py3
0.34.1.1++1+stretch1

- **Install method**: 
Debian packages

- **Platform**: 

Debian VM

**Comment by richvdh** [comment]
fixed by #4589
