### ISSUE TITLE
ERROR:root:Needed msgpack-python>=0.4.2 but it was not installed

### ISSUE THREAD

**Issue by matoro** [matrix-org/synapse#4571]
### Description

After upgrading from 0.34.0 to 0.34.1.1, attempting to start the server results in the following error:

```
$ sudo -u synapse python3.6 -m synapse.app.homeserver --config-path=/etc/synapse/homeserver.yaml --report-stats=no
ERROR:root:Needed msgpack-python>=0.4.2 but it was not installed
Missing Requirements: "msgpack-python>=0.4.2"
To install run:
    pip install --upgrade --force "msgpack-python>=0.4.2"
```

However msgpack-python is installed:

```
$ equery list dev-python/msgpack
 * Searching for msgpack in dev-python ...
[IP-] [  ] dev-python/msgpack-0.5.6:0
```

```
$ python3.6 -c "from msgpack._version import version ; print(version)"
(0, 5, 6)
```

### Version information

- **Homeserver**: yes

If not matrix.org:

- **Version**: 0.34.1.1

- **Install method**: package manager

- **Platform**:  Gentoo amd64 on Linux 4.20.6 on Intel Core 2 Duo T5850 (2) @ 1.179GHz

**Comment by hawkowl** [comment]
This uses the `pkg_resources` method of checking for versions -- can you run:

```
import pkg_resources
pkg_resources.require("msgpack-python")
```

**Comment by matoro** [comment]
@hawkowl Thanks, that helps narrow down the problem.  It seems to be an issue with the package naming, `msgpack-python` vs `msgpack`.

```
$ python3.6
>>> import pkg_resources
>>> pkg_resources.require("msgpack-python")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python' distribution was not found and is required by the application
>>> pkg_resources.require("msgpack")
[msgpack 0.5.6 (/usr/lib/python3.6/site-packages)]
```

Not sure what could have changed to break this between synapse versions.  I may also point toward the following in `msgpack`'s setup:  https://github.com/msgpack/msgpack-python/blob/master/setup.py#L103

```
if TRANSITIONAL:
    name = 'msgpack-python'
long_desc = "This package is deprecated.  Install msgpack instead."
```

**Comment by matoro** [comment]
Just upgraded to 0.99.1.1 and this seems to be resolved.
