### ISSUE TITLE
Internal server error and ThumbnailResource

### ISSUE THREAD

**Issue by 4nd3r** [matrix-org/synapse#4594]
my syslog is full errors related to ThumbnailResource.

for example:

```
Feb  9 09:41:06 uvn-67-169 python[28993]: Error processing request <XForwardedForRequest at 0x7f83602056d8 method='GET' uri='/_matrix/media/v1/thumbnail/kvlt.ee/GTjQVuyymNIaogBbtsRAFCVP?width=24&height=24&method=crop' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Feb  9 09:41:06 uvn-67-169 python[28993]: Failed handle request via <function ThumbnailResource._async_render_GET at 0x7f836675ef28>: <XForwardedForRequest at 0x7f83602056d8 method='GET' uri='/_matrix/media/v1/thumbnail/kvlt.ee/GTjQVuyymNIaogBbtsRAFCVP?width=24&height=24&method=crop' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Feb  9 09:41:06 uvn-67-169 python[28993]:     result = g.send(result)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 121, in _respond_local_thumbnail
Feb  9 09:41:06 uvn-67-169 python[28993]:     yield respond_with_responder(request, responder, t_type, t_length)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
Feb  9 09:41:06 uvn-67-169 python[28993]:     return _cancellableInlineCallbacks(gen)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
Feb  9 09:41:06 uvn-67-169 python[28993]:     _inlineCallbacks(None, g, status)
Feb  9 09:41:06 uvn-67-169 python[28993]: --- <exception caught here> ---
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
Feb  9 09:41:06 uvn-67-169 python[28993]:     yield h(self, request)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 71, in _async_render_GET
Feb  9 09:41:06 uvn-67-169 python[28993]:     request, media_id, width, height, method, m_type
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 121, in _respond_local_thumbnail
Feb  9 09:41:06 uvn-67-169 python[28993]:     yield respond_with_responder(request, responder, t_type, t_length)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Feb  9 09:41:06 uvn-67-169 python[28993]:     result = g.send(result)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/rest/media/v1/_base.py", line 137, in respond_with_responder
Feb  9 09:41:06 uvn-67-169 python[28993]:     yield responder.write_to_consumer(request)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/synapse/rest/media/v1/media_storage.py", line 263, in write_to_consumer
Feb  9 09:41:06 uvn-67-169 python[28993]:     FileSender().beginFileTransfer(self.open_file, consumer)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/protocols/basic.py", line 923, in beginFileTransfer
Feb  9 09:41:06 uvn-67-169 python[28993]:     self.consumer.registerProducer(self, False)
Feb  9 09:41:06 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/web/http.py", line 958, in registerProducer
Feb  9 09:41:06 uvn-67-169 python[28993]:     self.channel.registerProducer(producer, streaming)
Feb  9 09:41:06 uvn-67-169 python[28993]: builtins.AttributeError: 'NoneType' object has no attribute 'registerProducer'
Feb  9 09:41:06 uvn-67-169 python[28993]: Not sending response to request <XForwardedForRequest at 0x7f83602056d8 method='GET' uri='/_matrix/media/v1/thumbnail/kvlt.ee/GTjQVuyymNIaogBbtsRAFCVP?width=24&height=24&method=crop' clientproto='HTTP/1.0' site=8008>, already disconnected.
```
full log available here: https://matrix.kvlt.ee/synapse-ThumbnailResource.log

i'm seeing these errors for months now, but can't pinpoint version which introduced them.

i'm running Debian 9, Python 3.5.3 and synapse inside virtualenv.

**Comment by 2Belette** [comment]
I got theses kind or errors every minute or less, I also note that a lot of time I have to `synctl restart` as my synapse appears disconnected on riot.. @4nd3r does it crashes your synapse as well?

```
2019-03-19 09:48:14,017 - synapse.access.http.8008 - 302 - INFO - GET-154 - 10.20.110.1 - 8008 - {None} Processed request: 0.706sec/0.000sec (0.230sec, 0.007sec) (0.000sec/0.000sec/3) 55B 500 "GET /_matrix/media/v1/thumbnail/matrix.fdn.fr/VXVhSTfqPOdQNLwGiQHyJWDa?width=30&height=30&method=crop HTTP/1.1" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0" [0 dbevts]
2019-03-19 09:48:14,025 - synapse.rest.media.v1.media_repository - 534 - INFO - GET-155 - Stored thumbnail in file u'/home/belette/.synapse/media_store/remote_thumbnail/matrix.fdn.fr/VX/Vh/STfqPOdQNLwGiQHyJWDa/14-14-image-png'
2019-03-19 09:48:14,027 - synapse.http.server - 112 - ERROR - GET-155 - Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x3ed028565a8 method=u'GET' uri=u'/_matrix/media/v1/thumbnail/matrix.fdn.fr/VXVhSTfqPOdQNLwGiQHyJWDa?width=14&height=14&method=crop' clientproto=u'HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 78, in _async_render_GET
    width, height, method, m_type
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 221, in _select_or_generate_remote_thumbnail
    desired_height, desired_method, desired_type
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/rest/media/v1/media_repository.py", line 540, in generate_remote_exact_thumbnail
    t_width, t_height, t_type, t_method, t_len
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 516, in _simple_insert
    self._simple_insert_txn, table, values,
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 408, in runInteraction
    *args, **kwargs
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 457, in runWithConnection
    inner_func, *args, **kwargs
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/belette/.synapse/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 453, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 329, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 536, in _simple_insert_txn
    txn.execute(sql, vals)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 119, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/belette/.synapse/lib/python2.7/site-packages/synapse/storage/_base.py", line 149, in _do_execute
    sql, *args
IntegrityError: UNIQUE constraint failed
```

**Comment by ArchangeGabriel** [comment]
@2Belette This looks more like #4389 than #4379.

**Comment by 4nd3r** [comment]
> does it crashes your synapse as well?

no, it does not

**Comment by richvdh** [comment]
@4nd3r please can you include lines logged at INFO or WARNING?

**Comment by 4nd3r** [comment]
hmm, I'm not seeing ThumbnailResource related errors anymore in the logs since 21st and I don't have older logs available. fixed for me, I guess?

**Comment by Sharparam** [comment]
I've noticed this error (or very similar) in my log today. I get the following:

```
2019-04-23 16:12:03,076 - synapse.http.server - 112 - ERROR - GET-48473- Failed handle request via 'ThumbnailResource': <XForwardedForRequest at 0x7f6501fe0b00 method='GET' uri='/_matrix/media/v1/thumbnail/gruenhage.xyz/d37e643164e89c5266405ac6d3cd84a4' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 460, in runWithConnection
    defer.returnValue(result)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [{'thumbnail_width': 32, 'thumbnail_height': 32, 'thumbnail_method': 'crop', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 898, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 96, 'thumbnail_height': 96, 'thumbnail_method': 'crop', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 2223, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 238, 'thumbnail_height': 240, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 7537, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 477, 'thumbnail_height': 480, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 21755, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 596, 'thumbnail_height': 600, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 31183, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 418, in runInteraction
    defer.returnValue(result)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [{'thumbnail_width': 32, 'thumbnail_height': 32, 'thumbnail_method': 'crop', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 898, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 96, 'thumbnail_height': 96, 'thumbnail_method': 'crop', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 2223, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 238, 'thumbnail_height': 240, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 7537, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 477, 'thumbnail_height': 480, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 21755, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}, {'thumbnail_width': 596, 'thumbnail_height': 600, 'thumbnail_method': 'scale', 'thumbnail_type': 'image/jpeg', 'thumbnail_length': 31183, 'filesystem_id': 'TebzRUhZaeolOdvoZESiSgRd'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 83, in _async_render_GET
    width, height, method, m_type
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 244, in _respond_remote_thumbnail
    width, height, method, m_type, thumbnail_infos
  File "/home/matrix/synapse/env/lib/python3.6/site-packages/synapse/rest/media/v1/thumbnail_resource.py", line 303, in _select_thumbnail
    size_quality = abs((d_w - t_w) * (d_h - t_h))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

I can reproduce it by sending the GET request in postman:

```
GET /_matrix/media/r0/thumbnail/gruenhage.xyz/d37e643164e89c5266405ac6d3cd84a4 HTTP/1.1
Host: matrix.sharparam.com
Authorization: Bearer <snip>
cache-control: no-cache
```

Which responds with internal server error:

```
{"errcode":"M_UNKNOWN","error":"Internal server error"}
```

And generates the above error message in `homeserver.log`.

**Comment by Sharparam** [comment]
If I add size parameters to the request then it works. If both `width` and `height` are set I get a working thumbnail back. If one or both are missing then I get an internal server error.

**Comment by richvdh** [comment]
@Sharparam your issue is #2748 

Sounds like the original problem is fixed
