### ISSUE TITLE
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing

### ISSUE THREAD

**Issue by 4nd3r** [matrix-org/synapse#4595]
getting this exception ~300 times per day.

```
Feb  9 05:54:16 uvn-67-169 python[28993]: Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Feb  9 05:54:16 uvn-67-169 python[28993]: Traceback (most recent call last):
Feb  9 05:54:16 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/web/_newclient.py", line 195, in _callAppFunction
Feb  9 05:54:16 uvn-67-169 python[28993]:     function()
Feb  9 05:54:16 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/web/client.py", line 1087, in stopProducing
Feb  9 05:54:16 uvn-67-169 python[28993]:     self._task.stop()
Feb  9 05:54:16 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/task.py", line 497, in stop
Feb  9 05:54:16 uvn-67-169 python[28993]:     self._checkFinish()
Feb  9 05:54:16 uvn-67-169 python[28993]:   File "/home/matrix-synapse/synapse/env/lib/python3.5/site-packages/twisted/internet/task.py", line 507, in _checkFinish
Feb  9 05:54:16 uvn-67-169 python[28993]:     raise self._completionState
Feb  9 05:54:16 uvn-67-169 python[28993]: twisted.internet.task.TaskStopped
```

i'm seeing these errors for months now, but can't pinpoint version which introduced them.

i'm running Debian 9, Python 3.5.3 and synapse inside virtualenv.

**Comment by richvdh** [comment]
dup #4003
