### ISSUE TITLE
TLS certificate permissions error does not prevent synctl from succeeding

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#4602]
Example:

```
(.synapse) matrix@matrix:~/.synapse$ synctl restart
stopped synapse.app.homeserver
Starting ...
... snip ...
started synapse.app.homeserver('homeserver.yaml')

(.synapse) matrix@matrix:~/.synapse$ tail -f homeserver.log
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 391, in start
    _base.start(hs, config.listeners)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/app/_base.py", line 254, in start
    sys.exit(1)
SystemExit: 1
2019-02-10 04:28:04,510 - twisted - 239 - INFO -  - Main loop terminated.
2019-02-10 04:28:04,511 - synapse.app.homeserver - 70 - WARNING -  - Stopping daemon.
```

The exception is:
```
2019-02-10 04:28:04,445 - root - 215 - INFO -  - Loading certificate from disk...
2019-02-10 04:28:04,446 - twisted - 239 - ERROR -  - Traceback (most recent call last):
2019-02-10 04:28:04,446 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/app/_base.py", line 244, in start
2019-02-10 04:28:04,446 - twisted - 239 - ERROR -  -     refresh_certificate(hs)
2019-02-10 04:28:04,446 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/app/_base.py", line 216, in refresh_certificate
2019-02-10 04:28:04,450 - twisted - 239 - ERROR -  -     hs.config.read_certificate_from_disk()
2019-02-10 04:28:04,450 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/config/tls.py", line 99, in read_certificate_from_disk
2019-02-10 04:28:04,450 - twisted - 239 - ERROR -  -     self.tls_certificate = self.read_tls_certificate(self.tls_certificate_file)
2019-02-10 04:28:04,451 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/config/tls.py", line 240, in read_tls_certificate
2019-02-10 04:28:04,451 - twisted - 239 - ERROR -  -     cert_pem = self.read_file(cert_path, "tls_certificate")
2019-02-10 04:28:04,452 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/config/_base.py", line 133, in read_file
2019-02-10 04:28:04,452 - twisted - 239 - ERROR -  -     cls.check_file(file_path, config_name)
2019-02-10 04:28:04,452 - twisted - 239 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/config/_base.py", line 115, in check_file
2019-02-10 04:28:04,453 - twisted - 239 - ERROR -  -     % (file_path, config_name, e.strerror)
2019-02-10 04:28:04,453 - twisted - 239 - ERROR -  - ConfigError: Error accessing file '/etc/letsencrypt/live/my.domain.example.org/fullchain.pem' (config for tls_certificate): Permission denied
2019-02-10 04:28:04,461 - synapse.metrics - 374 - INFO -  - Collecting gc 0
2019-02-10 04:28:04,505 - twisted - 239 - CRITICAL -  - Unhandled error in Deferred:
2019-02-10 04:28:04,505 - twisted - 239 - CRITICAL -  -
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 391, in start
    _base.start(hs, config.listeners)
  File "/home/matrix/.synapse/local/lib/python2.7/site-packages/synapse/app/_base.py", line 254, in start
    sys.exit(1)
SystemExit: 1
2019-02-10 04:28:04,510 - twisted - 239 - INFO -  - Main loop terminated.

```

**Comment by richvdh** [comment]
#4543
