### ISSUE TITLE
Federation demo cannot be launched anymore

### ISSUE THREAD

**Issue by manuroe** [matrix-org/synapse#4612]
### Description

The federation [demo](https://github.com/matrix-org/synapse/tree/master/demo) does not work anymore in 0.99.

I got the same error in each homeserver.log:

```
2019-02-11 14:59:08,119 - twisted - 245 - ERROR -  - Traceback (most recent call last):
2019-02-11 14:59:08,122 - twisted - 245 - ERROR -  -   File "/Users/manu/UC/matrix/github/server/synapse/synapse/app/homeserver.py", line 430, in start
2019-02-11 14:59:08,124 - twisted - 245 - ERROR -  -     hs.config.read_certificate_from_disk()
2019-02-11 14:59:08,127 - twisted - 245 - ERROR -  -   File "/Users/manu/UC/matrix/github/server/synapse/synapse/config/tls.py", line 99, in read_certificate_from_disk
2019-02-11 14:59:08,130 - twisted - 245 - ERROR -  -     self.tls_certificate = self.read_tls_certificate(self.tls_certificate_file)
2019-02-11 14:59:08,132 - twisted - 245 - ERROR -  -   File "/Users/manu/UC/matrix/github/server/synapse/synapse/config/tls.py", line 240, in read_tls_certificate
2019-02-11 14:59:08,133 - twisted - 245 - ERROR -  -     cert_pem = self.read_file(cert_path, "tls_certificate")
2019-02-11 14:59:08,135 - twisted - 245 - ERROR -  -   File "/Users/manu/UC/matrix/github/server/synapse/synapse/config/_base.py", line 133, in read_file
2019-02-11 14:59:08,137 - twisted - 245 - ERROR -  -     cls.check_file(file_path, config_name)
2019-02-11 14:59:08,139 - twisted - 245 - ERROR -  -   File "/Users/manu/UC/matrix/github/server/synapse/synapse/config/_base.py", line 115, in check_file
2019-02-11 14:59:08,140 - twisted - 245 - ERROR -  -     % (file_path, config_name, e.strerror)
2019-02-11 14:59:08,141 - twisted - 245 - ERROR -  - ConfigError: Error accessing file '/Users/manu/UC/matrix/github/server/synapse/demo/etc/localhost:8480.tls.crt' (config for tls_certificate): No such file or directory
```

This has been discussed [here](https://matrix.to/#/!yZHTGeDKZUeKaqeTeU:matrix.org/$15498936862613172EwtHm:matrix.org?via=matrix.org&via=sw1v.org&via=half-shot.uk) with that proposed [workaround](https://matrix.to/#/!yZHTGeDKZUeKaqeTeU:matrix.org/$154990586167YGBoP:jki.re?via=matrix.org&via=sw1v.org&via=half-shot.uk).

If the creation of self-signed certs is no more handled by Synapse, the demo script should do it and set up everything.

### Steps to reproduce

- Follow the howto doc to start federated homeservers: https://github.com/matrix-org/synapse/tree/master/demo
- Try to open http://localhost:8081

-> Nothing happens. Servers are not running.

### Version information
Broken since 0.99
Works great in 0.34.1
- **Platform**: 
MacOS, Linux

**Comment by manuroe** [comment]
I should have mentioned we heavily use the federation demo script to develop features in mobile SDKs. We have hundreds of integration tests that rely on it.

**Comment by richvdh** [comment]
I thnk this got fixed?
