### ISSUE TITLE
sqlite3.OperationalError: ambiguous column name: event_id

### ISSUE THREAD

**Issue by Artiom-M** [matrix-org/synapse#4634]
Just configured a new instance and started it with synctl start :

2019-02-12 22:28:26,970 - synapse.storage.prepare_database - 267 - **INFO - None - Applying schema 31/invites.sql**
```
2019-02-12 22:28:26,971 - twisted - 245 - ERROR -  - Traceback (most recent call last):
2019-02-12 22:28:26,972 - twisted - 245 - ERROR -  -   File "/opt/alt/python36/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
2019-02-12 22:28:26,972 - twisted - 245 - ERROR -  -     "__main__", mod_spec)
2019-02-12 22:28:26,973 - twisted - 245 - ERROR -  -   File "/opt/alt/python36/lib64/python3.6/runpy.py", line 85, in _run_code
2019-02-12 22:28:26,973 - twisted - 245 - ERROR -  -     exec(code, run_globals)
2019-02-12 22:28:26,973 - twisted - 245 - ERROR -  -   File "/virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/app/homeserver.py", line 657, in <module>
2019-02-12 22:28:26,974 - twisted - 245 - ERROR -  -     main()
2019-02-12 22:28:26,974 - twisted - 245 - ERROR -  -   File "/virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/app/homeserver.py", line 652, in main
2019-02-12 22:28:26,975 - twisted - 245 - ERROR -  -     hs = setup(sys.argv[1:])
2019-02-12 22:28:26,975 - twisted - 245 - ERROR -  -   File "/virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/app/homeserver.py", line 362, in setup
2019-02-12 22:28:26,975 - twisted - 245 - ERROR -  -     prepare_database(db_conn, database_engine, config=config)
2019-02-12 22:28:26,976 - twisted - 245 - ERROR -  -   File "/virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 72, in prepare_database
2019-02-12 22:28:26,976 - twisted - 245 - ERROR -  -     _setup_new_database(cur, database_engine)
2019-02-12 22:28:26,976 - twisted - 245 - ERROR -  -   File "/virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 159, in _setup_new_database
2019-02-12 22:28:26,976 - twisted - 245 - ERROR -  -     is_empty=True,
2019-02-12 22:28:26,977 - twisted - 245 - ERROR -  -   File "/home//virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 268, in _upgrade_existing_database
2019-02-12 22:28:26,977 - twisted - 245 - ERROR -  -     executescript(cur, absolute_path)
2019-02-12 22:28:26,977 - twisted - 245 - ERROR -  -   File "/home//virtualenv/python_synapse/3.6/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 407, in executescript
2019-02-12 22:28:26,978 - twisted - 245 - ERROR -  -     txn.execute(statement)
```
2019-02-12 22:28:26,978 - twisted - 245 - **ERROR -  - sqlite3.OperationalError: ambiguous column name: event_id**

**Comment by Artiom-M** [comment]
I have modified the invites.sql as following:

INSERT INTO local_invites SELECT
        stream_ordering as stream_id,
        sender as inviter,
        state_key as invitee,
        **e.event_id,
        e.room_id,**
        NULL as locally_rejected,
        NULL as replaced_by
    **FROM events e**
    NATURAL JOIN current_state_events
    NATURAL JOIN room_memberships
    WHERE membership = 'invite'  AND state_key IN (SELECT name FROM users);

And this solved the issue

**Comment by Artiom-M** [comment]
And now in the log I have the same errors:
`2019-02-12 23:45:53,559 - synapse.storage._base - 307 - WARNING - background_updates-0 - [TXN OPERROR] {room_membership_profile_update-51d} ambiguous column name: event_id 5/5
`

**Comment by richvdh** [comment]
is this still a problem? if so, what version of sqlite?

**Comment by Artiom-M** [comment]
I will install a new instance soon and will post here.

**Comment by richvdh** [comment]
surely this has been fixed
