### ISSUE TITLE
ACME support doesn't work on python 2

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4649]
```
2019-02-14 17:15:20,924 - twisted - 239 - ERROR - - Error during startup:
2019-02-14 17:15:20,924 - twisted - 239 - ERROR - - Traceback (most recent call last):
2019-02-14 17:15:20,925 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-02-14 17:15:20,925 - twisted - 239 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-02-14 17:15:20,925 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
2019-02-14 17:15:20,925 - twisted - 239 - ERROR - -     _inlineCallbacks(r, g, status)
2019-02-14 17:15:20,926 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-02-14 17:15:20,926 - twisted - 239 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-02-14 17:15:20,926 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
2019-02-14 17:15:20,927 - twisted - 239 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-02-14 17:15:20,928 - twisted - 239 - ERROR - - --- <exception caught here> ---
2019-02-14 17:15:20,928 - twisted - 239 - ERROR - -   File "/home/synapse/matrixtest/synapse/app/homeserver.py", line 430, in start
2019-02-14 17:15:20,929 - twisted - 239 - ERROR - -     yield do_acme()
2019-02-14 17:15:20,929 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-02-14 17:15:20,929 - twisted - 239 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-02-14 17:15:20,929 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
2019-02-14 17:15:20,930 - twisted - 239 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-02-14 17:15:20,930 - twisted - 239 - ERROR - -   File "/home/synapse/matrixtest/synapse/app/homeserver.py", line 407, in do_acme
2019-02-14 17:15:20,930 - twisted - 239 - ERROR - -     yield acme.provision_certificate()
2019-02-14 17:15:20,930 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-02-14 17:15:20,931 - twisted - 239 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-02-14 17:15:20,931 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
2019-02-14 17:15:20,931 - twisted - 239 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-02-14 17:15:20,931 - twisted - 239 - ERROR - -   File "synapse/handlers/acme.py", line 129, in provision_certificate
2019-02-14 17:15:20,932 - twisted - 239 - ERROR - -     
2019-02-14 17:15:20,932 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-02-14 17:15:20,932 - twisted - 239 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-02-14 17:15:20,932 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/txacme/service.py", line 230, in <lambda>
2019-02-14 17:15:20,933 - twisted - 239 - ERROR - -     csr=csr_for_names([server_name], key))))
2019-02-14 17:15:20,933 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/txacme/util.py", line 153, in csr_for_names
2019-02-14 17:15:20,933 - twisted - 239 - ERROR - -     x509.NameAttribute(NameOID.COMMON_NAME, common_name)]))
2019-02-14 17:15:20,933 - twisted - 239 - ERROR - -   File "/home/synapse/env/local/lib/python2.7/site-packages/cryptography/x509/name.py", line 49, in __init__
2019-02-14 17:15:20,934 - twisted - 239 - ERROR - -     "value argument must be a text type."
2019-02-14 17:15:20,934 - twisted - 239 - ERROR - - exceptions.TypeError: value argument must be a text type.
```

**Comment by aaronraimist** [comment]
`INSTALL.md` now says you need Python 3.5+
