### ISSUE TITLE
assert minthreads >= 0, 'minimum is negative'

### ISSUE THREAD

**Issue by cwmke** [matrix-org/synapse#4684]
### Description
After following install instructions under "Installing from source" I attempt to start the server with `synctl start` and receive the above error.

### Steps to reproduce

1. Follow install from source instructions on Fedora 29
2. synctl start

```Server /home/matrix/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py version 0.99.1.1
Server hostname: REDACTED
Redirected stdout/stderr to logs
/home/matrix/synapse/env/lib/python3.7/site-packages/psycopg2/__init__.py:144: builtins.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Preparing database: psycopg2...
Upgrading schema to v53
Database prepared in psycopg2.
Setting up.
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 659, in <module>
    main()
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 654, in main
    hs = setup(sys.argv[1:])
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 378, in setup
    hs.setup()
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/server.py", line 217, in setup
    self.datastore = self.DATASTORE_CLASS(conn, self)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/__init__.py", line 220, in __init__
    super(DataStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/roommember.py", line 556, in __init__
    super(RoomMemberStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/registration.py", line 147, in __init__
    super(RegistrationStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/registration.py", line 32, in __init__
    super(RegistrationWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/stream.py", line 164, in __init__
    super(StreamWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/transactions.py", line 61, in __init__
    super(TransactionStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/state.py", line 1303, in __init__
    super(StateStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/events.py", line 215, in __init__
    super(EventsStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/state.py", line 375, in __init__
    super(StateGroupWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/event_federation.py", line 459, in __init__
    super(EventFederationStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/media_repository.py", line 22, in __init__
    super(MediaRepositoryStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/push_rule.py", line 74, in __init__
    super(PushRulesWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/appservice.py", line 59, in __init__
    super(ApplicationServiceWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/receipts.py", line 342, in __init__
    super(ReceiptsStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/receipts.py", line 43, in __init__
    super(ReceiptsWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/search.py", line 47, in __init__
    super(SearchStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/account_data.py", line 275, in __init__
    super(AccountDataStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/account_data.py", line 47, in __init__
    super(AccountDataWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/event_push_actions.py", line 590, in __init__
    super(EventPushActionsStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/event_push_actions.py", line 70, in __init__
    super(EventPushActionsWorkerStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/client_ips.py", line 45, in __init__
    super(ClientIpStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/devices.py", line 39, in __init__
    super(DeviceStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/deviceinbox.py", line 33, in __init__
    super(DeviceInboxStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 86, in __init__
    super(BackgroundUpdateStore, self).__init__(db_conn, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/monthly_active_users.py", line 32, in __init__
    super(MonthlyActiveUsersStore, self).__init__(None, hs)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/storage/_base.py", line 188, in __init__
    self._db_pool = hs.get_db_pool()
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/server.py", line 515, in _get
    dep = builder()
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/synapse/server.py", line 382, in build_db_pool
    **self.db_config.get("args", {})
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 244, in __init__
    self.threadpool = threadpool.ThreadPool(self.min, self.max)
  File "/home/matrix/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 67, in __init__
    assert minthreads >= 0, 'minimum is negative'
TypeError: '>=' not supported between instances of 'str' and 'int'
```

### Version information
- **Homeserver**: Fedora 29
-**Database**: Postgresql
- **Version**: 0.99.1.1
- **Install method**: source/pip
- **Platform**: Running inside of virtualenv after installing with pip. Attempted to start with selinux enfrocing and also tried while in permissive mode. Previously attempted installation a month ago with python2 and received the same error. Using sqlite removed the error so I'm guessing it may be tied to postgresql. This time was attempted with a clean start with the same result (none of the old files from the python2 test a month ago.)

**Comment by richvdh** [comment]
sounds like you've got the database settings wrong in the config.

**Comment by cwmke** [comment]
Here's the section from my config. 
```
database:
name: "psycopg2"
  args:
    user: "synapse_user"
    password: "PASSWORD"
    database: "synapse"
    host: "localhost"
    cp_min: "5"
    cp_max: "10"

**Comment by richvdh** [comment]
cp_min and cp_max should be integers, not strings. remove the quotes.

**Comment by cwmke** [comment]
Many, many thanks @richvdh. I've been trying to figure this out for a while.
