### ISSUE TITLE
cache invalidation is broken on the media repo woker

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4702]
```
2019-02-21 00:00:00,143 - synapse.metrics.background_process_metrics - 203 - ERROR - replication-RDATA-caches-229781 - Background process 'replication-RDATA-caches' threw an exception
Capture point (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/matrix/synapse/synapse/app/media_repository.py", line 169, in <module>
    start(sys.argv[1:])
  File "/home/matrix/synapse/synapse/app/media_repository.py", line 164, in start
    _base.start_worker_reactor("synapse-media-repository", config)
  File "/home/matrix/synapse/synapse/app/_base.py", line 71, in start_worker_reactor
    logger,
  File "/home/matrix/synapse/synapse/app/_base.py", line 135, in start_reactor
    daemon.start()
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/home/matrix/synapse/synapse/app/_base.py", line 124, in run
    reactor.run()
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/base.py", line 1279, in mainLoop
    self.doIteration(t)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/home/matrix/synapse/synapse/replication/tcp/protocol.py", line 230, in lineReceived
    cmd,
  File "/home/matrix/synapse/synapse/metrics/background_process_metrics.py", line 211, in run_as_background_process
    return run()
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
  File "/home/matrix/.synapse-py36/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
Traceback (most recent call last):
  File "/home/matrix/synapse/synapse/metrics/background_process_metrics.py", line 201, in run
    yield func(*args, **kwargs)
  File "/home/matrix/synapse/synapse/replication/tcp/protocol.py", line 562, in on_RDATA
    return self.handler.on_rdata(stream_name, cmd.token, rows)
  File "/home/matrix/synapse/synapse/replication/tcp/client.py", line 110, in on_rdata
    return self.store.process_replication_rows(stream_name, token, rows)
  File "/home/matrix/synapse/synapse/replication/slave/storage/_base.py", line 60, in process_replication_rows
    self._invalidate_state_caches(room_id, members_changed)
  File "/home/matrix/synapse/synapse/storage/_base.py", line 1351, in _invalidate_state_caches
    self.get_users_in_room.invalidate((room_id,))
AttributeError: 'MediaRepositorySlavedStore' object has no attribute 'get_users_in_room'
```

**Comment by richvdh** [comment]
fixed by #4715
