### ISSUE TITLE
Can't upload large files

### ISSUE THREAD

**Issue by itsmeagainsorry** [matrix-org/synapse#4739]
marks will be invisible in the report.

-->

### Description

Can't upload large files, despite changing values in the homeserver.yaml and nginx.

### Steps to reproduce

- Use unfederated server
- Try to upload large file

<!-- 
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
I changed the values in the .yaml and nginx to 4096m, and that increased my possible file upload size from the default. If I try to upload a larger file (using riot) the progress bar goesall thae way to the end before waiting for a while and telling me it was unable to upload the file. Here's the part of the log I think is relevant:

```
2019-02-23 11:21:56,272 - synapse.access.http.8008 - 233 - INFO - POST-56858- ::ffff:127.0.0.1 - 8008 - Received request: POST /_matrix/media/v1/upload
2019-02-23 11:22:14,466 - synapse.http.site - 203 - WARNING - POST-56858- Error processing request <SynapseRequest at 0x7fae8bf0d7b8 method='POST' uri='/_matrix/media/v1/upload' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
2019-02-23 11:22:14,488 - synapse.http.server - 112 - ERROR - POST-56858- Failed handle request via <function UploadResource._async_render_POST at 0x7fae8e228840>: <SynapseRequest at 0x7fae8bf0d7b8 method='POST' uri='/_matrix/media/v1/upload' clientproto='HTTP/1.0' site=8008>: Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/media/v1/upload_resource.py", line 95, in _async_render_POST
    content_length, requester.user
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/media/v1/media_repository.py", line 162, in create_content
    fname = yield self.media_storage.store_file(content, file_info)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/media/v1/media_storage.py", line 70, in store_file
    _write_file_synchronously, source, f,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/logcontext.py", line 636, in g
    return f(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/media/v1/media_storage.py", line 248, in _write_file_synchronously
    shutil.copyfileobj(source, dest)
  File "/usr/lib/python3.6/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
builtins.ValueError: read of closed file
2019-02-23 11:22:14,494 - synapse.http.server - 415 - WARNING - POST-56858- Not sending response to request <SynapseRequest at 0x7fae8bf0d7b8 method='POST' uri='/_matrix/media/v1/upload' clientproto='HTTP/1.0' site=8008>, already disconnected.
2019-02-23 11:22:14,494 - synapse.access.http.8008 - 302 - INFO - POST-56858- ::ffff:127.0.0.1 - 8008 - {@me:mydomain.com} Processed request: 18.223sec/-4.321sec (0.084sec, 0.273sec) (0.000sec/0.000sec/0) 0B 200! "POST /_matrix/media/v1/upload HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.0.1 Chrome/66.0.3359.181 Electron/3.1.3 Safari/537.36" [0 dbevts]

```

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- Homeserver: 

If not matrix.org:

<!-- 
What version of Synapse is running? 
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 

- **Install method**: 
<!-- examples: package manager/git clone/pip  -->

- **Platform**: 
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
looks like your client (or possibly a reverse proxy) is timing out the request. Sadly there's not much we can do about this on the server side.

**Comment by richvdh** [comment]
(check your ngnix logs I guess)
