### ISSUE TITLE
500 Internal Server Error: Failed handle request via 'GroupRoomServlet'

### ISSUE THREAD

**Issue by jo-so** [matrix-org/synapse#4786]
### Description

```
synapse.http.server: [GET-46332] Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7fc86d47c4a8 method='GET' uri='/_matrix/client/r0/gro
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v2_alpha/groups.py", line 355, in on_GET
    result = yield self.groups_handler.get_rooms_in_group(group_id, requester_user_id)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/groups_local.py", line 34, in f
    if self.is_mine_id(group_id):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/server.py", line 237, in is_mine_id
    return string.split(":", 1)[1] == self.hostname
IndexError: list index out of range
```

### Version information

- **Version**: 0.99.2+stretch1
- **Install method**: Debian package from matrix.org
- **Platform**: Debian stable

**Comment by richvdh** [comment]
is this still a problem?

**Comment by richvdh** [comment]
assuming not.
