### ISSUE TITLE
synapse fails if `prev_state` is missing from an event received over federation

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#4787]
This field is not specced, and we shouldn't be relying on what the remove server is telling us anyway

**Comment by richvdh** [comment]
```
2019-03-03 15:56:11,267 - synapse.http.server - 112 - ERROR - PUT-4279- Failed handle request via 'FederationSendJoinServlet': <SynapseRequest at 0x7f3738494e10 method='PUT' uri='/_matrix/federati
Traceback (most recent call last):
  File "/home/rav/work/synapse/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/rav/work/synapse/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/rav/work/synapse/synapse/federation/transport/server.py", line 289, in new_func
    origin, content, request.args, *args, **kwargs
  File "/home/rav/work/synapse/synapse/federation/transport/server.py", line 502, in on_PUT
    content = yield self.handler.on_send_join_request(origin, content, context)
  File "/home/rav/work/synapse/synapse/federation/federation_server.py", line 419, in on_send_join_request
    res_pdus = yield self.handler.on_send_join_request(origin, pdu)
  File "/home/rav/work/synapse/synapse/handlers/federation.py", line 1257, in on_send_join_request
    origin, event
  File "/home/rav/work/synapse/synapse/handlers/federation.py", line 1598, in _handle_new_event
    backfilled=backfilled,
  File "/home/rav/work/synapse/synapse/handlers/federation.py", line 2527, in persist_events_and_notify
    backfilled=backfilled,
  File "/home/rav/work/synapse/synapse/storage/events.py", line 277, in persist_events
    defer.gatherResults(deferreds, consumeErrors=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: prev_state
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
--- <exception caught here> ---
/home/rav/work/synapse/synapse/storage/events.py:157:handle_queue_loop
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/rav/work/synapse/synapse/storage/events.py:316:persisting_queue
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/rav/work/synapse/synapse/storage/events.py:198:f
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/rav/work/synapse/synapse/storage/events.py:493:_persist_events
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/rav/work/synapse/synapse/storage/_base.py:408:runInteraction
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/rav/work/synapse/synapse/storage/_base.py:457:runWithConnection
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/python/compat.py:464:reraise
/home/rav/work/synapse/env3/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/home/rav/work/synapse/synapse/storage/_base.py:453:inner_func
/home/rav/work/synapse/synapse/storage/_base.py:329:_new_transaction
/home/rav/work/synapse/synapse/util/logutils.py:88:wrapped
/home/rav/work/synapse/synapse/storage/events.py:902:_persist_events_txn
/home/rav/work/synapse/synapse/storage/events.py:1419:_update_metadata_tables_txn
/home/rav/work/synapse/synapse/storage/events.py:1420:<listcomp>
/home/rav/work/synapse/synapse/events/__init__.py:89:getter
]]
```

**Comment by richvdh** [comment]
sytest branch at https://github.com/matrix-org/sytest/tree/rav/remove_prev_state
