### ISSUE TITLE
federation_reader: 'FederationReaderSlavedStore' object has no attribute 'get_user_directory_stream_pos'

### ISSUE THREAD

**Issue by krombel** [matrix-org/synapse#4802]
### Description
The following line appears when starting the federation_reader worker
```
<timestamp> - synapse.metrics.background_process_metrics - 203 - ERROR - user_directory.notify_new_event-0 - Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/path/to/env/lib/python3.5/site-packages/matrix_synapse-0.99.2-py3.5.egg/synapse/metrics/background_process_metrics.py", line 201, in run                                             
    yield func(*args, **kwargs)
AttributeError: 'FederationReaderSlavedStore' object has no attribute 'get_user_directory_stream_pos'
```

I don't know if there is any observable effect because of this error.

### Steps to reproduce

- start worker federation_reader
- experience the mentioned log

### Version information
- **Homeserver**: selfhosted
- **Version**: 0.99.2
- **Install method**: git clone
- **Platform**: Linux

**Comment by jo-so** [comment]
I think, I'm getting the same error:
```
synapse.metrics.background_process_metrics: [renew_attestations-16] Background process 'renew_attestations' threw an exception
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/metrics/background_process_metrics.py", line 201, in run
    yield func(*args, **kwargs)
AttributeError: 'FederationReaderSlavedStore' object has no attribute 'get_attestations_need_renewals'
```

**Comment by turt2live** [comment]
@jo-so your error looks to be in the same place, but a different function

**Comment by jo-so** [comment]
Yes, I've dug a little bit into the code and found that
`FederationReaderSlavedStore` misses `UserDirectoryStore` and
`GroupServerStore`. There's `SlavedGroupServerStore`, but this misses
something like

```
get_attestations_need_renewals = __func__(DataStore.get_attestations_need_renewals)
```

But I'm unsure, this is the correct solution. For
`get_user_directory_stream_pos` I think the `UserDirectoryStore` must get
ported as *Slaved*.

**Comment by turt2live** [comment]
and now it's my turn to get this on startup:
```
federation_reader_3 - 2019-05-08 21:09:08,021 - synapse.app.federation_reader - 121 - INFO - - Synapse federation reader now listening on port 9102
federation_reader_3 - 2019-05-08 21:09:08,021 - synapse.replication.tcp.client - 53 - INFO - - Connecting to replication: IPv4Address(type='TCP', host='127.0.0.1', port=9092)
federation_reader_3 - 2019-05-08 21:09:08,022 - synapse.metrics.background_process_metrics - 203 - ERROR - user_directory.notify_new_event-0- Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/home/matrix/.synapse-py3/lib/python3.5/site-packages/synapse/metrics/background_process_metrics.py", line 201, in run
    yield func(*args, **kwargs)
AttributeError: 'FederationReaderSlavedStore' object has no attribute 'get_user_directory_stream_pos'

```

**Comment by richvdh** [comment]
presumably this got fixed somewhere along the way.
