### ISSUE TITLE
Federation stopped and synapse required a restart

### ISSUE THREAD

**Issue by Zauberstuhl** [matrix-org/synapse#4831]
### Description

Suddenly federation stopped but the server didn't crash completely.
I had to restart synapse to get it working again and I found following in the log:

```
3/7/2019 10:32:39 PM2019-03-07 21:32:39,103 - synapse.storage._base - 337 - WARNING - GET-67714 - [TXN OPERROR] {get_users_in_room-4cbc5} server closed the connection unexpectedly
3/7/2019 10:32:39 PM This probably means the server terminated abnormally
3/7/2019 10:32:39 PM before or while processing the request.
3/7/2019 10:32:39 PM 0/5
3/7/2019 10:32:39 PM2019-03-07 21:32:39,105 - synapse.storage._base - 337 - WARNING - GET-67754 - [TXN OPERROR] {get_users_in_room-4cbc7} server closed the connection unexpectedly
3/7/2019 10:32:39 PM This probably means the server terminated abnormally
3/7/2019 10:32:39 PM before or while processing the request.
3/7/2019 10:32:39 PM 0/5
3/7/2019 10:32:39 PM2019-03-07 21:32:39,110 - synapse.storage._base - 346 - WARNING - GET-67714 - [TXN EROLL] {get_users_in_room-4cbc5} connection already closed
3/7/2019 10:32:39 PM2019-03-07 21:32:39,111 - synapse.storage._base - 346 - WARNING - GET-67754 - [TXN EROLL] {get_users_in_room-4cbc7} connection already closed
3/7/2019 10:32:39 PM2019-03-07 21:32:39,117 - twisted - 240 - CRITICAL -  - Rollback failed
3/7/2019 10:32:39 PMTraceback (most recent call last):
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
3/7/2019 10:32:39 PM    result = inContext.theWork()
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
3/7/2019 10:32:39 PM    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
3/7/2019 10:32:39 PM    return self.currentContext().callWithContext(ctx, func, *args, **kw)
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
3/7/2019 10:32:39 PM    return func(*args,**kw)
3/7/2019 10:32:39 PM--- <exception caught here> ---
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 303, in _runWithConnection
3/7/2019 10:32:39 PM    conn.rollback()
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback
3/7/2019 10:32:39 PM    self._connection.rollback()
3/7/2019 10:32:39 PMpsycopg2.InterfaceError: connection already closed
3/7/2019 10:32:39 PM
3/7/2019 10:32:39 PM2019-03-07 21:32:39,123 - twisted - 240 - CRITICAL -  - Rollback failed
3/7/2019 10:32:39 PMTraceback (most recent call last):
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
3/7/2019 10:32:39 PM    result = inContext.theWork()
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
3/7/2019 10:32:39 PM    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
3/7/2019 10:32:39 PM    return self.currentContext().callWithContext(ctx, func, *args, **kw)
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
3/7/2019 10:32:39 PM    return func(*args,**kw)
3/7/2019 10:32:39 PM--- <exception caught here> ---
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 303, in _runWithConnection
3/7/2019 10:32:39 PM    conn.rollback()
3/7/2019 10:32:39 PM  File "/usr/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback
3/7/2019 10:32:39 PM    self._connection.rollback()
3/7/2019 10:32:39 PMpsycopg2.InterfaceError: connection already closed
```
I hope this can help/improve synapse. You are doing a great job :) :tada: 

### Steps to reproduce

- unkown

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: feneas.org

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 0.99.2

- **Install method**: docker image (matrixdotorg/synapse:v0.99.2)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Hetzner Cloud, Debian
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
sounds like your database server died?

**Comment by Zauberstuhl** [comment]
> sounds like your database server died?

mh nothing in the DB log indicates something like this, but I have my suspicions too.
maybe some network issue..

still should synapse crash that hard if the database is unavailable for even a split second?
I think it makes more sense to a) die completely so that e.g. the docker container can restart and recover or b) throw the error and retry

// lukas

**Comment by richvdh** [comment]
> still should synapse crash that hard if the database is unavailable for even a split second?

certainly it should not. I'm surprised if it does so. I'd expect it to fail the operation (and return a 500 for the relevant request).

If it's reproducible it might be possible to fix it...

**Comment by richvdh** [comment]
I've not heard of this ever happening again, so I don't think it's something we can do much about
