### ISSUE TITLE
Upgrade don't work with Python 2.7 (pep517 dependency doesn't build)

### ISSUE THREAD

**Issue by codeandcreate** [matrix-org/synapse#4860]
### Description

I want to upgrade my home server (0.99.0) with following little script to the latest version.
i installed it in a custom folder with python 2.7.

### Steps to reproduce

```
source ./bin/activate
synctl stop
pip install --upgrade https://github.com/matrix-org/synapse/tarball/master
synctl start
```

### Error log

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting https://github.com/matrix-org/synapse/tarball/master
  Downloading https://github.com/matrix-org/synapse/tarball/master
     - 1.5MB 7.5MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /ssd/server/matrix/synapse/bin/python2.7 /ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpCzsAbA:
  Traceback (most recent call last):
    File "/ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: 'module' object has no attribute '__legacy__'

  ----------------------------------------
Command "/ssd/server/matrix/synapse/bin/python2.7 /ssd/server/matrix/synapse/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpCzsAbA" failed with error code 1 in /tmp/pip-req-build-V8iM3H
```

### Version information

- **Version**: Synapse/0.99.0
- **Platform**:  git clone/pip
- **OS**: Ubuntu 16.04.6 LTS 4.11.2
- **Hardware**: FriendlyElec NanoPi Duo (ARM)
- **Python Version**: 2.7

**Comment by richvdh** [comment]
works fine for me. That looks like an issue with `pip`, not synapse: possibly https://github.com/pypa/pip/issues/6264. I don't think it's related to python 2.7, either.

**Comment by codeandcreate** [comment]
A workaround is to upgrade to python3; i have done it in following (maybe hacky) way:

```
cd synapse
source ./bin/activate
synctl stop
deactivate
cd ..
mv synapse synapse_old
cd synapse_old
rm bin/pip{,2,2.7}
rm bin/python{,2,2.7}
rm -r include/python2.7
rm lib/python2.7/*
rm -r lib/python2.7/distutils
rm lib/python2.7/site-packages/easy_install.*
rm -r lib/python2.7/site-packages/pip
rm -r lib/python2.7/site-packages/pip-*.dist-info
rm -r lib/python2.7/site-packages/setuptools
rm -r lib/python2.7/site-packages/setuptools-*.dist-info
cd ..
python3 -m venv synapse
mv -f synapse_old/* synapse/
mv -f synapse_old/bin/* synapse/bin/
mv -f synapse_old/lib/* synapse/bin/
cd synapse
source ./bin/activate
pip install --upgrade pip
pip install --upgrade https://github.com/matrix-org/synapse/tarball/master
```

**Comment by richvdh** [comment]
I don't think this is a synapse issue.

**Comment by richvdh** [comment]
Possibly the problem was that your python 2.7 virtualenv was broken in some way (such as using `--system-site-packages`).
