### ISSUE TITLE
debian packages try to put ACME certificate into read-only directory by default

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#4871]
### Description

Splitting #4788 into separate issues. ACME certificate request tries to store data in /etc/matrix-synapse/conf.d but the /etc/matrix-synapse/conf.d belongs to root. Everything fails.

### Steps to reproduce

- install matrix-synapse-py3 ver. 0.99.2 on bionic1 with

```
wget -qO - https://matrix.org/packages/debian/repo-key.asc | sudo apt-key add -
sudo add-apt-repository https://matrix.org/packages/debian/
sudo apt install matrix-synapse-py3 -y
```

- add an acme section
- start the server and see it fail with

```
2019-03-17 17:36:18,927 - root - 209 - WARNING - None- ***** STARTING SERVER *****
2019-03-17 17:36:18,938 - root - 212 - WARNING - None- Server /opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py version 0.99.2
2019-03-17 17:36:18,938 - root - 214 - INFO - None- Server hostname: matrix.vaizard.xyz
2019-03-17 17:36:18,939 - twisted - 240 - INFO - None- Redirected stdout/stderr to logs
2019-03-17 17:36:18,948 - twisted - 240 - WARNING - None- /opt/venvs/matrix-synapse/lib/python3.6/site-packages/psycopg2/__init__.py:144: builtins.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2019-03-17 17:36:18,960 - synapse.app.homeserver - 358 - INFO - None- Preparing database: psycopg2...
2019-03-17 17:36:18,964 - synapse.storage.prepare_database - 223 - INFO - None- Upgrading schema to v53
2019-03-17 17:36:18,965 - synapse.app.homeserver - 376 - INFO - None- Database prepared in psycopg2.
2019-03-17 17:36:18,965 - synapse.server - 217 - INFO - None- Setting up.
2019-03-17 17:36:18,976 - synapse.storage.event_push_actions - 471 - INFO - None- Searching for stream ordering 1 month ago
2019-03-17 17:36:18,977 - synapse.storage.event_push_actions - 477 - INFO - None- Found stream ordering 1 month ago: it's 0
2019-03-17 17:36:18,977 - synapse.storage.event_push_actions - 479 - INFO - None- Searching for stream ordering 1 day ago
2019-03-17 17:36:18,977 - synapse.storage.event_push_actions - 485 - INFO - None- Found stream ordering 1 day ago: it's 0
2019-03-17 17:36:18,978 - synapse.server - 221 - INFO - None- Finished setting up.
2019-03-17 17:36:18,979 - synapse.app.homeserver - 628 - INFO - None- Scheduling stats reporting for 3 hour intervals
2019-03-17 17:36:18,979 - synapse.app.homeserver - 105 - INFO - - Running
2019-03-17 17:36:18,979 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 1048576
2019-03-17 17:36:19,076 - synapse.handlers.acme - 106 - INFO - - Listening for ACME requests on 127.0.0.1:8080
2019-03-17 17:36:19,076 - twisted - 240 - INFO - - Site starting on 8080
2019-03-17 17:36:19,193 - twisted - 240 - ERROR - - Error during startup:
2019-03-17 17:36:19,194 - twisted - 240 - ERROR - - Traceback (most recent call last):
2019-03-17 17:36:19,194 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-03-17 17:36:19,194 - twisted - 240 - ERROR - -     result = g.send(result)
2019-03-17 17:36:19,194 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 429, in start
2019-03-17 17:36:19,194 - twisted - 240 - ERROR - -     yield acme.start_listening()
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -     return _cancellableInlineCallbacks(gen)
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -     _inlineCallbacks(None, g, status)
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - - --- <exception caught here> ---
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 429, in start
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -     yield acme.start_listening()
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2019-03-17 17:36:19,195 - twisted - 240 - ERROR - -     result = g.send(result)
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 122, in start_listening
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -     yield self._issuer._ensure_registered()
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/service.py", line 243, in _ensure_registered
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -     return self._with_client(self._register)
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/service.py", line 184, in _with_client
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -     return self._client_creator().addCallback(f, *a, **kw)
2019-03-17 17:36:19,196 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 86, in <lambda>
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -     FilePath(self.hs.config.config_dir_path)
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/endpoint.py", line 153, in load_or_create_client_key
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -     encryption_algorithm=serialization.NoEncryption()))
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/filepath.py", line 1538, in setContent
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -     with sib.open('w') as f:
2019-03-17 17:36:19,197 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/filepath.py", line 1008, in open
2019-03-17 17:36:19,198 - twisted - 240 - ERROR - -     return self.create()
2019-03-17 17:36:19,198 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/filepath.py", line 1581, in create
2019-03-17 17:36:19,198 - twisted - 240 - ERROR - -     fdint = os.open(self.path, _CREATE_FLAGS)
2019-03-17 17:36:19,198 - twisted - 240 - ERROR - - builtins.PermissionError: [Errno 13] Permission denied: b'/etc/matrix-synapse/conf.d/GvBX3vZAnqkSvBJEclient.key.new'
2019-03-17 17:36:19,199 - synapse.app.homeserver - 577 - INFO - - report_stats can use psutil
2019-03-17 17:36:19,200 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:36:19,218 - twisted - 240 - CRITICAL - - Unhandled error in Deferred:
2019-03-17 17:36:19,219 - twisted - 240 - CRITICAL - - 
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 429, in start
    yield acme.start_listening()
PermissionError: [Errno 13] Permission denied: b'/etc/matrix-synapse/conf.d/GvBX3vZAnqkSvBJEclient.key.new'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 451, in start
    sys.exit(1)
SystemExit: 1
2019-03-17 17:36:19,222 - twisted - 240 - INFO - - (TCP Port 8080 Closed)
2019-03-17 17:36:19,223 - twisted - 240 - INFO - - Main loop terminated.
```

**Simple fix:** add `--keys-directory=/etc/matrix-synapse` to the systemd unit, run `systemctl daemon-reload`

**Comment by richvdh** [comment]
>  add --keys-directory=/etc/matrix-synapse to the systemd unit

I'm somewhat surprised this works, given the synapse user doesn't have permission to write to `/etc/matrix-synapse` either.

Probably we ought to set `keys-directory` to `/var/lib/matrix-synapse`.

**Comment by killua-eu** [comment]
The /etc/matrix-synapse owner is matrix-synapse if I remember correctly. But whatever works, /var/lib/matrix-synapse is fine too.

**Comment by ReK2Fernandez** [comment]
I hit this 2 hours a go and was able to work around it thanks to the response above adding the right part on the systemd for synapse start. Trying to troubleshot a ACME issue since then ... something is wrong with the synapse side.. nginx is forwarding the calls to the right place.. but hits a 404.

**Comment by jooize** [comment]
To resolve `PermissionError: [Errno 13] Permission denied: b'/etc/matrix-synapse/conf.d/GvBX3vZAnqkSvBJEclient.key.new'` on Ubuntu 16.04 with **matrix-synapse-py3 1.1.0** I did this:

1. Edit `/etc/systemd/system/multi-user.target.wants/matrix-synapse.service` and append 
` --keys-directory=/var/lib/matrix-synapse` to the `ExecStart` line.
2. Run `systemctl daemon-reload`
3. Run `systemctl restart matrix-synapse` (unnecessary?)

Do not confuse with `/etc/init.d/matrix-synapse`.

**Comment by richvdh** [comment]
given synapse no longer supports ACME, I guess this is no longer a problem.
