### ISSUE TITLE
ACME / matrix doesn't respect configured acme port

### ISSUE THREAD

**Issue by killua-eu** [matrix-org/synapse#4872]
Description

Splitting #4788 into separate issues. ACME challenge configured to port 8080 possibly ignores the port, listens on port 80. Error messages are unhelpful, problem unintuitive to debug. Follows #4871 during my testing of the 0.9 branch.  To reproduce, install accordingly to #4871, then add

```
tls_certificate_path: /etc/matrix-synapse/homeserver.tls.crt
tls_private_key_path: /etc/matrix-synapse/homeserver.tls.key
acme:
    enabled: true
    port: 8080
    url: https://acme-staging.api.letsencrypt.org/directory
    bind_addresses: ['127.0.0.1']
```

to the config ... acme-staging is used because the systemd unit **will try** to get the cert so many times, that acme blocks your test server from further requests due to too many requests.

```
2019-03-17 17:41:30,460 - root - 209 - WARNING - None- ***** STARTING SERVER *****
2019-03-17 17:41:30,472 - root - 212 - WARNING - None- Server /opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py version 0.99.2
2019-03-17 17:41:30,473 - root - 214 - INFO - None- Server hostname: matrix.vaizard.xyz
2019-03-17 17:41:30,474 - twisted - 240 - INFO - None- Redirected stdout/stderr to logs
2019-03-17 17:41:30,483 - twisted - 240 - WARNING - None- /opt/venvs/matrix-synapse/lib/python3.6/site-packages/psycopg2/__init__.py:144: builtins.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2019-03-17 17:41:30,496 - synapse.app.homeserver - 358 - INFO - None- Preparing database: psycopg2...
2019-03-17 17:41:30,500 - synapse.storage.prepare_database - 223 - INFO - None- Upgrading schema to v53
2019-03-17 17:41:30,501 - synapse.app.homeserver - 376 - INFO - None- Database prepared in psycopg2.
2019-03-17 17:41:30,501 - synapse.server - 217 - INFO - None- Setting up.
2019-03-17 17:41:30,512 - synapse.storage.event_push_actions - 471 - INFO - None- Searching for stream ordering 1 month ago
2019-03-17 17:41:30,512 - synapse.storage.event_push_actions - 477 - INFO - None- Found stream ordering 1 month ago: it's 0
2019-03-17 17:41:30,513 - synapse.storage.event_push_actions - 479 - INFO - None- Searching for stream ordering 1 day ago
2019-03-17 17:41:30,513 - synapse.storage.event_push_actions - 485 - INFO - None- Found stream ordering 1 day ago: it's 0
2019-03-17 17:41:30,514 - synapse.server - 221 - INFO - None- Finished setting up.
2019-03-17 17:41:30,515 - synapse.app.homeserver - 628 - INFO - None- Scheduling stats reporting for 3 hour intervals
2019-03-17 17:41:30,515 - synapse.app.homeserver - 105 - INFO - - Running
2019-03-17 17:41:30,515 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 1048576
2019-03-17 17:41:30,592 - synapse.handlers.acme - 106 - INFO - - Listening for ACME requests on 127.0.0.1:8080
2019-03-17 17:41:30,592 - twisted - 240 - INFO - - Site starting on 8080
2019-03-17 17:41:30,642 - synapse.app.homeserver - 577 - INFO - - report_stats can use psutil
2019-03-17 17:41:30,642 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:41:30,937 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:41:31,620 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:41:31,831 - synapse.handlers.acme - 127 - WARNING - - Reprovisioning matrix.vaizard.xyz
2019-03-17 17:41:32,095 - twisted - 240 - INFO - - Requesting a certificate for 'matrix.vaizard.xyz'.
2019-03-17 17:41:32,473 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:41:38,132 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 17:41:38,332 - synapse.handlers.acme - 132 - ERROR - - Fail!
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 130, in provision_certificate
    yield self._issuer.issue_cert(self._acme_domain)
txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value='matrix.vaizard.xyz') [Error(typ='urn:acme:error:unauthorized', title=None, detail='Invalid response from http://matrix.vaizard.xyz/.well-known/acme-challenge/deZVII6Wyso5bAsgJkiFrHDUcf-zeqe4IGCD55ylQLU [78.44.255.11]: 503')]>)
2019-03-17 17:41:38,333 - twisted - 240 - ERROR - - Error during startup:
2019-03-17 17:41:38,333 - twisted - 240 - ERROR - - Traceback (most recent call last):
2019-03-17 17:41:38,333 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/treq/client.py", line 80, in _deliverWaiting
2019-03-17 17:41:38,333 - twisted - 240 - ERROR - -     waiter.connectionLost(reason)
2019-03-17 17:41:38,334 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/treq/content.py", line 39, in connectionLost
2019-03-17 17:41:38,334 - twisted - 240 - ERROR - -     self.finished.callback(None)
2019-03-17 17:41:38,334 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
2019-03-17 17:41:38,334 - twisted - 240 - ERROR - -     self._startRunCallbacks(result)
2019-03-17 17:41:38,335 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
2019-03-17 17:41:38,335 - twisted - 240 - ERROR - -     self._runCallbacks()
2019-03-17 17:41:38,335 - twisted - 240 - ERROR - - --- <exception caught here> ---
2019-03-17 17:41:38,335 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 430, in start
2019-03-17 17:41:38,335 - twisted - 240 - ERROR - -     yield do_acme()
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 407, in do_acme
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -     yield acme.provision_certificate()
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 130, in provision_certificate
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -     yield self._issuer.issue_cert(self._acme_domain)
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-03-17 17:41:38,336 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/client.py", line 599, in repoll
2019-03-17 17:41:38,337 - twisted - 240 - ERROR - -     raise AuthorizationFailed(authzr)
2019-03-17 17:41:38,337 - twisted - 240 - ERROR - - txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value='matrix.vaizard.xyz') [Error(typ='urn:acme:error:unauthorized', title=None, detail='Invalid response from http://matrix.vaizard.xyz/.well-known/acme-challenge/deZVII6Wyso5bAsgJkiFrHDUcf-zeqe4IGCD55ylQLU [78.44.255.11]: 503')]>)
2019-03-17 17:41:38,339 - twisted - 240 - INFO - - (TCP Port 8080 Closed)
2019-03-17 17:41:38,340 - twisted - 240 - INFO - - Main loop terminated.
```

The interesting bits are **Error(typ='urn:acme:error:unauthorized', title=None, detail='Invalid response from http://matrix.vaizard.xyz/.well-known/acme-challenge/deZVII6Wyso5bAsgJkiFrHDUcf-zeqe4IGCD55ylQLU [78.44.255.11]: 503')** - the url doesn't contain the required 8080 port. While the line **2019-03-17 17:41:38,339 - twisted - 240 - INFO - - (TCP Port 8080 Closed)** makes it seem, like all behaves correctly, the 503 was a nice giveaway. I have haproxy listening infront of the matrix container, haproxy listens on port 80 and 443. Upon stopping haproxy, the error changed to

```
2019-03-17 18:26:40,192 - root - 209 - WARNING - None- ***** STARTING SERVER *****
2019-03-17 18:26:40,203 - root - 212 - WARNING - None- Server /opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py version 0.99.2
2019-03-17 18:26:40,204 - root - 214 - INFO - None- Server hostname: matrix.vaizard.xyz
2019-03-17 18:26:40,204 - twisted - 240 - INFO - None- Redirected stdout/stderr to logs
2019-03-17 18:26:40,213 - twisted - 240 - WARNING - None- /opt/venvs/matrix-synapse/lib/python3.6/site-packages/psycopg2/__init__.py:144: builtins.UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
2019-03-17 18:26:40,225 - synapse.app.homeserver - 358 - INFO - None- Preparing database: psycopg2...
2019-03-17 18:26:40,228 - synapse.storage.prepare_database - 223 - INFO - None- Upgrading schema to v53
2019-03-17 18:26:40,229 - synapse.app.homeserver - 376 - INFO - None- Database prepared in psycopg2.
2019-03-17 18:26:40,229 - synapse.server - 217 - INFO - None- Setting up.
2019-03-17 18:26:40,239 - synapse.storage.event_push_actions - 471 - INFO - None- Searching for stream ordering 1 month ago
2019-03-17 18:26:40,240 - synapse.storage.event_push_actions - 477 - INFO - None- Found stream ordering 1 month ago: it's 0
2019-03-17 18:26:40,240 - synapse.storage.event_push_actions - 479 - INFO - None- Searching for stream ordering 1 day ago
2019-03-17 18:26:40,240 - synapse.storage.event_push_actions - 485 - INFO - None- Found stream ordering 1 day ago: it's 0
2019-03-17 18:26:40,241 - synapse.server - 221 - INFO - None- Finished setting up.
2019-03-17 18:26:40,242 - synapse.app.homeserver - 628 - INFO - None- Scheduling stats reporting for 3 hour intervals
2019-03-17 18:26:40,242 - synapse.app.homeserver - 105 - INFO - - Running
2019-03-17 18:26:40,242 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 1048576
2019-03-17 18:26:40,318 - synapse.handlers.acme - 106 - INFO - - Listening for ACME requests on 127.0.0.1:8080
2019-03-17 18:26:40,319 - twisted - 240 - INFO - - Site starting on 8080
2019-03-17 18:26:40,367 - synapse.app.homeserver - 577 - INFO - - report_stats can use psutil
2019-03-17 18:26:40,367 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 18:26:40,639 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 18:26:41,300 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 18:26:41,500 - synapse.handlers.acme - 127 - WARNING - - Reprovisioning matrix.vaizard.xyz
2019-03-17 18:26:41,900 - twisted - 240 - INFO - - Requesting a certificate for 'matrix.vaizard.xyz'.
2019-03-17 18:26:42,168 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 18:26:47,837 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-03-17 18:26:48,052 - synapse.handlers.acme - 132 - ERROR - - Fail!
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 130, in provision_certificate
    yield self._issuer.issue_cert(self._acme_domain)
txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value='matrix.vaizard.xyz') [Error(typ='urn:acme:error:connection', title=None, detail='Fetching http://matrix.vaizard.xyz/.well-known/acme-challenge/enHSX5-Lv-ntxcLPdpRMSpSubiXtJ5CaZCCSKByilW0: Error getting validation data')]>)
2019-03-17 18:26:48,052 - twisted - 240 - ERROR - - Error during startup:
2019-03-17 18:26:48,053 - twisted - 240 - ERROR - - Traceback (most recent call last):
2019-03-17 18:26:48,053 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/treq/client.py", line 80, in _deliverWaiting
2019-03-17 18:26:48,053 - twisted - 240 - ERROR - -     waiter.connectionLost(reason)
2019-03-17 18:26:48,054 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/treq/content.py", line 39, in connectionLost
2019-03-17 18:26:48,054 - twisted - 240 - ERROR - -     self.finished.callback(None)
2019-03-17 18:26:48,054 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
2019-03-17 18:26:48,055 - twisted - 240 - ERROR - -     self._startRunCallbacks(result)
2019-03-17 18:26:48,055 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
2019-03-17 18:26:48,055 - twisted - 240 - ERROR - -     self._runCallbacks()
2019-03-17 18:26:48,055 - twisted - 240 - ERROR - - --- <exception caught here> ---
2019-03-17 18:26:48,055 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 430, in start
2019-03-17 18:26:48,056 - twisted - 240 - ERROR - -     yield do_acme()
2019-03-17 18:26:48,056 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 407, in do_acme
2019-03-17 18:26:48,056 - twisted - 240 - ERROR - -     yield acme.provision_certificate()
2019-03-17 18:26:48,056 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 130, in provision_certificate
2019-03-17 18:26:48,056 - twisted - 240 - ERROR - -     yield self._issuer.issue_cert(self._acme_domain)
2019-03-17 18:26:48,057 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-03-17 18:26:48,057 - twisted - 240 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-03-17 18:26:48,057 - twisted - 240 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/client.py", line 599, in repoll
2019-03-17 18:26:48,057 - twisted - 240 - ERROR - -     raise AuthorizationFailed(authzr)
2019-03-17 18:26:48,058 - twisted - 240 - ERROR - - txacme.client.AuthorizationFailed: AuthorizationFailed(<Status(invalid) Identifier(typ=IdentifierType(dns), value='matrix.vaizard.xyz') [Error(typ='urn:acme:error:connection', title=None, detail='Fetching http://matrix.vaizard.xyz/.well-known/acme-challenge/enHSX5-Lv-ntxcLPdpRMSpSubiXtJ5CaZCCSKByilW0: Error getting validation data')]>)
2019-03-17 18:26:48,059 - twisted - 240 - INFO - - (TCP Port 8080 Closed)
2019-03-17 18:26:48,061 - twisted - 240 - INFO - - Main loop terminated.
```

to ensure that the container has port 8080 correctly exposed, i stopped synapse, installed nginx and reconfigured it to listen on port 8080. Browsing `http://matrix.vaizard.xyz:8080/.well-known/acme-challenge/deZVII6Wyso5bAsgJkiFrHDUcf-zeqe4IGCD55ylQLU` gave me a nice 404 error with a nginx banner.

**I suppose that this is can be a major reason for the bad adoption rate of the acme certs** - a lot people have their homeserver behind a reverse proxy. Since the acme challenge ignores the port configuration, nobody ever gets their certificates, as long as they have a similar setup to mine.

**Comment by hawkowl** [comment]
The ACME listener does respect the port, but the ACME request *must* come to Port 80. As on https://letsencrypt.org/docs/challenge-types/ :

> The HTTP-01 challenge can only be done on port 80. Allowing clients to specify arbitrary ports would make the challenge less secure, and so it is not allowed by the ACME standard.

The ACME listener is respecting the port and listening to the configured/default 8080. As per our documentation, this then needs to be forwarded to port 80 via some mechanism: https://github.com/matrix-org/synapse/blob/master/docs/ACME.md#listening-on-port-80

We do not listen to port 80 by default, as that requires root on 99.9% of systems, and requires some other mechanism such as authbind to be configured to allow it, or a reverse proxy. As such, Synapse users behind a reverse proxy just need to configure their reverse proxy to forward all `.well-known/acme-challenge` requests to the ACME listener backend.

**Comment by ReK2Fernandez** [comment]
I am having similar problems, but I know is not the port.. is what actually listens on the 8009 port.. nginx gets the request on port 80 just fine and redirects it to 8009
example nginx log:
```
30 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
34.213.106.112 - - [23/Mar/2019:03:52:13 +0000] "GET /.well-known/acme-challenge/xMIxxNBd_j1_tz5zjBxq2mRgTiqkjXwoP8_4N6yLVuw HTTP/1.1" 404 130 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
66.133.109.36 - - [23/Mar/2019:03:52:13 +0000] "GET /.well-known/acme-challenge/xMIxxNBd_j1_tz5zjBxq2mRgTiqkjXwoP8_4N6yLVuw HTTP/1.1" 404 130 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)"
172.104.154.76 - - [23/Mar/2019:04:01:33 +0000] "GET /.well-known/matrix/server HTTP/1.0" 404 162 "-" "-"
```
but then synapse is not working right actually presenting lets script with the right path or token after.. 
if curious take a look to my issue post
https://github.com/matrix-org/synapse/issues/4922
