### ISSUE TITLE
Error register_new_matrix_user

### ISSUE THREAD

**Issue by DmitryNC** [matrix-org/synapse#4874]
[Edited for legibility]

Install from manual https://github.com/matrix-org/synapse/blob/master/INSTALL.md for Debian

```
cat /etc/issue:
Debian GNU/Linux 9 \n \l

aptitude -F "%p - %v" search matrix-synapse-py3
matrix-synapse-py3 - 0.99.2+stretch
```

Registering a user from CLI:
```
root@test:/# cd /opt/venvs/matrix-synapse/bin/
root@test:/opt/venvs/matrix-synapse/bin# source /opt/venvs/matrix-synapse/bin/activate
(matrix-synapse) root@test:/opt/venvs/matrix-synapse/bin# register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml http://127.0.0.1:8008
New user localpart [root]: manager
Password: 
Confirm password: 
Make admin [no]: yes
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/bin/register_new_matrix_user", line 22, in <module>
    main()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
    admin, args.user_type)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/_scripts/register_new_matrix_user.py", line 138, in register_new_user
    bool(admin), user_type)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/_scripts/register_new_matrix_user.py", line 60, in request_registration
    mac = hmac.new(key=shared_secret.encode('utf8'), digestmod=hashlib.sha1)
AttributeError: 'int' object has no attribute 'encode'

root@test:/# LANG=C ls -l /opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/_scripts/register_new_matrix_user.py
-rw-r--r-- 1 root root 6082 Mar  1 12:58 /opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/_scripts/register_new_matrix_user.py
```

**Comment by richvdh** [comment]
looks like you have set `shared_secret` to a number rather than a string in your config

**Comment by gabrix73** [comment]
I found the same problem.
I can’t register the first user yet everything else seems to work.
I'm on debian 10 and i have installed matrix-synapse-py3 from packages point matrix point org.
this is the exception:

`root@diego ~ # register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml https://127.0.0.1:8008
New user localpart [root]: Gabx
Password: 
Confirm password: 
Make admin [no]: yes
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/register_new_matrix_user", line 19, in <module>
    main()
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 229, in main
    args.user, args.password, args.server_url, secret, admin, args.user_type
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 142, in register_new_user
    user, password, server_location, shared_secret, bool(admin), user_type
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/_scripts/register_new_matrix_user.py", line 44, in request_registration
    r = requests.get(url, verify=False)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))`

**Comment by babolivier** [comment]
Hi @gabrix73, looks like you're connecting to your homeserver using https instead of http (https won't work with 127.0.0.1). In general though, please use [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) for support requests.
