### ISSUE TITLE
500 Error when accessing /messages for a room I am not a member of

### ISSUE THREAD

**Issue by Cadair** [matrix-org/synapse#5016]
### Description

I called `/messages` on a room I am not a member of (it's possible I was in the past) and received a 500 `M_UNKNOWN` error.

I dug the following up from the logs:
```
2019-04-05 14:57:38,144 - synapse.access.http.8008 - 233 - INFO - GET-801968 - 10.21.11.2 - 8008 - Received request: GET /_matrix/client/r0/rooms/%21HUeDbmFUsWAhxHHvFG%3Amatrix.org/messages?roomId=%21HUeDbmFUsWAhxHHvFG%3Amatrix.org&from=&dir=b&limit=10&access_token=<redacted>
2019-04-05 14:57:38,145 - synapse.storage.txn - 317 - DEBUG - GET-801968 - [TXN START] {_get_max_topological_txn-1f5c5d}
2019-04-05 14:57:38,147 - synapse.storage.txn - 373 - DEBUG - GET-801968 - [TXN END] {_get_max_topological_txn-1f5c5d} 0.001782 sec
2019-04-05 14:57:38,148 - synapse.http.server - 112 - ERROR - GET-801968 - Failed handle request via 'RoomMessageListRestServlet': <XForwardedForRequest at 0x7fcc160270f0 method='GET' uri='/_matrix/client/r0/rooms/%21HUeDbmFUsWAhxHHvFG%3Amatrix.org/messages?roomId=%21HUeDbmFUsWAhxHHvFG%3Amatrix.org&from=&dir=b&limit=1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/storage/_base.py", line 460, in runWithConnection
    defer.returnValue(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/storage/_base.py", line 418, in runInteraction
    defer.returnValue(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 479, in on_GET
    event_filter=event_filter,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/pagination.py", line 186, in get_messages
    room_id=room_id
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/streams/events.py", line 81, in get_current_token_for_room
    yield self.sources["room"].get_current_key_for_room(room_id)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/storage/stream.py", line 465, in get_room_events_max_id
    defer.returnValue("t%d-%d" % (topo, token))
TypeError: %d format: a number is required, not NoneType
2019-04-05 14:57:38,150 - synapse.access.http.8008 - 302 - INFO - GET-801968 - 10.21.11.2 - 8008 - {@cadair:cadair.com} Processed request: 0.005sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.002sec/1) 55B 500 "GET /_matrix/client/r0/rooms/%21HUeDbmFUsWAhxHHvFG%3Amatrix.org/messages?roomId=%21HUeDbmFUsWAhxHHvFG%3Amatrix
```

**Comment by MadLittleMods** [comment]
Closing as all of this code has changed nowadays: https://github.com/matrix-org/synapse/blob/172ce29b149afb91bbf728b88bffb117172a8f2c/synapse/storage/databases/main/stream.py
