### ISSUE TITLE
User directory issues lots of transactions in 0.99.3

### ISSUE THREAD

**Issue by evoL** [matrix-org/synapse#5018]
### Description

Since upgrading to 0.99.3 I've noticed that my machine has been doing way more IO operations than before. I can basically hear the hard drives all the time.
I've checked in htop and it reports 600KB/s of writes to Postgres from the Synapse user. The CPU and RAM usage is not significant, but there are constant writes.

I've since setup Prometheus metrics and here's what I've found:
![image](https://user-images.githubusercontent.com/155995/55653448-de9a5500-57ee-11e9-9fd6-4d2d6ecdb9b4.png)

The `update_profile_in_user_dir` thing is a clear outlier here, which makes me think something's not right with the new user directory.

Some more context: my homeserver has a single real user and around ~300 users bridged from 3 IRC channels of low to moderate activity. This should

### Steps to reproduce

- upgrade to 0.99.3
- check your IOPS

### Version information

- **Homeserver**: evolved.systems
- **Version**:  0.99.3

- **Install method**: 
avhost/docker-matrix Docker image

- **Platform**: 
Intel Celeron N3060, 8GB RAM, Docker on Linux, PostgreSQL 10.7

**Comment by neilisfragile** [comment]
The first time the new user directory comes on line it indexes every user available to it. We tried to soften the impact of the indexing (at the expense of speed of completion) - but it sounds like you are still noticing the impact. 

At this point I'd recommend waiting on the assumption that once the initial index is complete then things will go back to normal (with the benefit of really fast user search). I can't tell you how long to wait, for an installation like matrix.org it took days to complete, though I would not expect anything like the same in your case.

Please let me know if this continues past the weekend.

**Comment by evoL** [comment]
@neilisfragile 
Reporting that it's still going strong.
![image](https://user-images.githubusercontent.com/155995/55742960-6374b100-5a31-11e9-9223-fd2293943220.png)

However I managed to look at the logs and it looks that it cannot really execute the transactions:
```
2019-04-08 17:11:42,170 - synapse.storage.background_updates - 113 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 457, in runWithConnection
    inner_func, *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/local/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 453, in inner_func
    return func(conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 329, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/user_directory.py", line 547, in _add_users_in_public_rooms_txn
    value_values=None,
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 813, in _simple_upsert_many_txn
    txn, table, key_names, key_values, value_names, value_values
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 890, in _simple_upsert_many_txn_native_upsert
    return txn.execute_batch(sql, args)
  File "/usr/local/lib/python2.7/dist-packages/synapse/storage/_base.py", line 112, in execute_batch
    from psycopg2.extras import execute_batch
ImportError: cannot import name execute_batch
2019-04-08 17:11:43,183 - synapse.storage.background_updates - 191 - INFO - background_updates-0- Starting update batch on background update 'populate_user_directory_process_rooms'
2019-04-08 17:11:43,191 - synapse.storage.user_directory - 184 - INFO - background_updates-0- Processing the next 171 rooms of 171 remaining
```

I'll try to tinker with the Docker image. Maybe `psycopg2` is outdated.

**Comment by evoL** [comment]
I built a new Docker image with `psycopg2` 2.8.1. Looking at the logs, it seems to have moved forward. 
I'll let the image maintainers know.

Sorry for bothering!
