### ISSUE TITLE
develop does not start

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5040]
```
2019-04-10 00:22:21,102 - synapse.storage.prepare_database - 267 - INFO - None - Applying schema 54/drop_legacy_tables.sql
2019-04-10 00:22:21,106 - twisted - 242 - ERROR -  - Traceback (most recent call last):
2019-04-10 00:22:21,106 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
2019-04-10 00:22:21,106 - twisted - 242 - ERROR -  -     "__main__", mod_spec)
2019-04-10 00:22:21,107 - twisted - 242 - ERROR -  -   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
2019-04-10 00:22:21,107 - twisted - 242 - ERROR -  -     exec(code, run_globals)
2019-04-10 00:22:21,108 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 661, in <module>
2019-04-10 00:22:21,109 - twisted - 242 - ERROR -  -     main()
2019-04-10 00:22:21,109 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 656, in main
2019-04-10 00:22:21,110 - twisted - 242 - ERROR -  -     hs = setup(sys.argv[1:])
2019-04-10 00:22:21,110 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 362, in setup
2019-04-10 00:22:21,111 - twisted - 242 - ERROR -  -     prepare_database(db_conn, database_engine, config=config)
2019-04-10 00:22:21,111 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 69, in prepare_database
2019-04-10 00:22:21,111 - twisted - 242 - ERROR -  -     cur, user_version, delta_files, upgraded, database_engine, config
2019-04-10 00:22:21,112 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 268, in _upgrade_existing_database
2019-04-10 00:22:21,112 - twisted - 242 - ERROR -  -     executescript(cur, absolute_path)
2019-04-10 00:22:21,113 - twisted - 242 - ERROR -  -   File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/prepare_database.py", line 400, in executescript
2019-04-10 00:22:21,113 - twisted - 242 - ERROR -  -     txn.execute(statement)
2019-04-10 00:22:21,114 - twisted - 242 - ERROR -  - psycopg2.InternalError: cannot drop table application_services because other objects depend on it
2019-04-10 00:22:21,114 - twisted - 242 - ERROR -  - DETAIL:  constraint application_services_regex_as_id_fkey on table application_services_regex depends on table application_services
2019-04-10 00:22:21,114 - twisted - 242 - ERROR -  - HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2019-04-10 00:22:21,115 - twisted - 242 - ERROR -  -
error starting synapse.app.homeserver('workers/homeserver.yaml') (exit code: 1); see above for logs
```

**Comment by turt2live** [comment]
additional context: This is a homeserver which receives moderately infrequent updates, is running postgres, and has been around for a while. It is not a new homeserver.

**Comment by neilisfragile** [comment]
#5033 should fix

**Comment by turt2live** [comment]
indeed, fixed by https://github.com/matrix-org/synapse/pull/5033

Sorry for the noise
