### ISSUE TITLE
Invite accept via federation causes "internal server error"

### ISSUE THREAD

**Issue by jacotec** [matrix-org/synapse#5050]
**Issue description:**

A user on homeserver "domain2.de" invites a user on homeserver "domain1.de" to a chat.
The user on domain1 gets the invite, but as soon as he wants to accept the invite, he'll get "internal server error" after a few seconds.
There seems to be no way to accept the invite via Riot Web or Riot IOS.

**Homeserver:** 
Synapse/0.99.3 on Ubuntu 16.04 installed via Repos (Python 3 venv) (VM @ESXi 6.5)

**Error log on the server:**

```
2019-04-12 10:10:36,962 - synapse.access.https.8448 - 233 - INFO - POST-459868- xx.xx.xx.xx - 8448 - Received request: POST /_matrix/client/r0/join/!cbOLYNtiPtFwqqUQUc%3Adomain2.de
2019-04-12 10:10:36,963 - synapse.http.servlet - 212 - WARNING - POST-459868- Unable to parse JSON: Expecting value: line 1 column 1 (char 0)
2019-04-12 10:10:36,967 - synapse.metrics - 372 - INFO - - Collecting gc 0
2019-04-12 10:10:36,972 - synapse.federation.federation_client - 541 - WARNING - POST-459868- Failed to make_join via domain2.de
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 460, in runWithConnection
    defer.returnValue(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 418, in runInteraction
    defer.returnValue(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/profile.py", line 190, in get_avatar_url
    defer.returnValue(avatar_url)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/federation/federation_client.py", line 523, in _try_destination_list
    res = yield callback(destination)
synapse.util.retryutils.NotRetryingDestination: Not retrying server domain2.de.
2019-04-12 10:10:36,985 - synapse.http.server - 112 - ERROR - POST-459868- Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7f6b350df630 method='POST' uri='/_matrix/client/r0/join/!cbOLYNtiPtFwqqUQUc%3Adomain2.de' clientproto='HTTP/1.1' site=8448>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 460, in runWithConnection
    defer.returnValue(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 418, in runInteraction
    defer.returnValue(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/profile.py", line 190, in get_avatar_url
    defer.returnValue(avatar_url)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: mxc://domain1.de/TiwBfLAsazAToOBzxeyyHWzj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/room.py", line 282, in on_POST
    third_party_signed=content.get("third_party_signed", None),
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/room_member.py", line 325, in update_membership
    require_consent=require_consent,
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/util/async_helpers.py", line 216, in _ctx_manager
    yield
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/room_member.py", line 325, in update_membership
    require_consent=require_consent,
RuntimeError: Failed to make_join via any server

```

**Comment by jacotec** [comment]
I found that the issue was caused by a configuration change.
Instead of having two ports (8448 and 8449) for two servers behind the same IP address, I've configured all to my HAPROXY on port 8448 and forwarded it based on the domain to the matrix servers.

That seemed to have killed the invite communication when accepting the invite, although "arewereadyyet.com" reported no errors.

Rolled back to different ports now via HAPROXY (for Certificate/SSL offloading) and it works again.

Sorry for the inconvenience!
