### ISSUE TITLE
KeyError: 'expiry_template_html'

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#5076]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rav/work/synapse/synapse/app/homeserver.py", line 661, in <module>
    main()
  File "/home/rav/work/synapse/synapse/app/homeserver.py", line 656, in main
    hs = setup(sys.argv[1:])
  File "/home/rav/work/synapse/synapse/app/homeserver.py", line 329, in setup
    config_options,
  File "/home/rav/work/synapse/synapse/config/_base.py", line 362, in load_or_generate_config
    generate_keys=generate_keys,
  File "/home/rav/work/synapse/synapse/config/_base.py", line 408, in read_config_files
    self.parse_config_dict(config)
  File "/home/rav/work/synapse/synapse/config/_base.py", line 411, in parse_config_dict
    self.invoke_all("read_config", config_dict)
  File "/home/rav/work/synapse/synapse/config/_base.py", line 146, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/home/rav/work/synapse/synapse/config/emailconfig.py", line 74, in read_config
    self.email_expiry_template_html = email_config["expiry_template_html"]
KeyError: 'expiry_template_html'
```

**Comment by babolivier** [comment]
Fixed in #5077
