### ISSUE TITLE
Server does not run, error during event_search_postgres_gin

### ISSUE THREAD

**Issue by SuperRoboWizard** [matrix-org/synapse#5208]
### Description
New homeserver, once started, spams a single error to the log constantly and does not respond to being contacted.

### Steps to reproduce

- Install Matrix from source using pip (INSTALL.md)
- Configure homeserver.yaml, add certificates
  - May use SQLite3 or PostgreSQL, both caused the error
- Set up port-forwarding with NGINX
- synctl start

```
[...]
2019-05-18 02:21:43,533 - synapse.storage.background_updates - 187 - INFO - background_updates-0 - Starting update batch on background update 'event_search_postgres_gin'
2019-05-18 02:21:43,534 - synapse.storage.background_updates - 110 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/home/robo/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/robo/synapse/env/lib/python3.5/site-packages/synapse/util/__init__.py", line 51, in sleep
    defer.returnValue(res)
  File "/home/robo/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: 1.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robo/synapse/env/lib/python3.5/site-packages/synapse/storage/background_updates.py", line 107, in _run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
KeyError: 'event_search_postgres_gin'
2019-05-18 02:21:45,538 - synapse.storage.background_updates - 187 - INFO - background_updates-0 - Starting update batch on background update 'event_search_postgres_gin'
2019-05-18 02:21:45,539 - synapse.storage.background_updates - 110 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
[...]
```

### Version information

- **Homeserver**:  My own, URL is private at the moment

- **Version**: Server doesn't start, can't inspect headers

- **Install method**: pip

- **Platform**: Bare-metal Debian 9.9, Core 2 duo, 4GB RAM

**Comment by richvdh** [comment]
is this still a problem?

**Comment by SuperRoboWizard** [comment]
I gave up on this a while ago and have since removed the server. Given nobody else seems to have had this problem, I'll close the issue.
