### ISSUE TITLE
Can't leave community if server is offline

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#5254]
There seems to be no way to leave a community if the server that community is hosted on is offline. This is pretty annoying when a server is permanently taken down because now you are stuck in unleaveable groups.

**Comment by aaronraimist** [comment]
Also the API responds 200 OK `{}` even though it doesn't actually leave. It will also respond 200 OK to invalid group ids.

`curl -XOPTIONS "https://server.com/_matrix/client/r0/groups/+group:server.com/self/leave?access_token=`

**Comment by aaronraimist** [comment]
Hmm has this behavior changed recently? I randomly tried leaving from Riot iOS and got an "Internal Server Error" but the community is now gone from my devices even though I got the following logs

```
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: 2019-07-13 01:26:28,221 - synapse.http.matrixfederationclient - 464 - WARNING - PUT-1340550 - {POST-O-415227} [swedneck.xyz] Request failed: POST matrix://swedneck.xyz/_matrix/federation/v1/groups/%2Bthinkpad%3Aswedneck.xyz/users/%40aaron%3Araim.ist/remove?requester_user_id=%40aaron%3Araim.ist: ConnectionRefusedError('Connection refused')
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: 2019-07-13 01:26:28,222 - synapse.http.server - 108 - ERROR - PUT-1340550 - Failed handle request via 'GroupSelfLeaveServlet': <XForwardedForRequest at 0x7f3ba2ba0630 method='PUT' uri='/_matrix/client/r0/groups/%2Bthinkpad%3Aswedneck.xyz/self/leave' clientproto='HTTP/1.0' site=8008>
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: Traceback (most recent call last):
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 407, in _send_request
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     response = yield request_deferred
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: The above exception was the direct cause of the following exception:
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: Traceback (most recent call last):
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 76, in wrapped_request_handler
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     await h(self, request)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 301, in _async_render
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     callback_return = await callback_return
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     result = result.throwExceptionIntoGenerator(g)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     return g.throw(self.type, self.value, self.tb)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/groups.py", line 598, in on_PUT
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     group_id, requester_user_id, requester_user_id, content
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     result = result.throwExceptionIntoGenerator(g)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     return g.throw(self.type, self.value, self.tb)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/groups_local.py", line 406, in remove_user_from_group
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     content,
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     result = result.throwExceptionIntoGenerator(g)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     return g.throw(self.type, self.value, self.tb)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 685, in post_json
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     ignore_backoff=ignore_backoff,
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     result = result.throwExceptionIntoGenerator(g)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     return g.throw(self.type, self.value, self.tb)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 412, in _send_request
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:     raise_from(RequestSendFailed(e, can_retry=True), e)
Jul 13 01:26:28 ubuntu matrix-synapse[10840]:   File "<string>", line 3, in raise_from
Jul 13 01:26:28 ubuntu matrix-synapse[10840]: synapse.api.errors.RequestSendFailed: Failed to send request: ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.```

**Comment by ptman** [comment]
groups as rooms should help with this, right?

**Comment by Twi1ightSparkle** [comment]
For those stumbling across this looking for a possible solution: https://github.com/Twi1ightSparkle/matrix-documentation/wiki/Leave-Community-on-Dead-Homeserver

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
