### ISSUE TITLE
AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#5398]
```
2019-06-08 05:53:49,223 - synapse.handlers.federation - 446 - INFO - PUT-5546-$15599731921601uiBel:half-shot.uk - [!MbRaSiMIRhhxDtJENL:maunium.net $15599731921601uiBel:half-shot.uk]: Requesting missing events between ['$155997314481RCEII:testmatrix.vgorcum.com', '$15599731451599XaAST:half-shot.uk', '$155997315826DJaMQ:raim.ist'] and $15599731921601uiBel:half-shot.uk
2019-06-08 05:53:49,223 - synapse.federation.transport.client - 489 - DEBUG - PUT-5546-$15599731921601uiBel:half-shot.uk - Invoked 'get_missing_events' with args: self=<synapse.federation.transport.client.TransportLaye..., destination=half-shot.uk, room_id=!MbRaSiMIRhhxDtJENL:maunium.net, earliest_events=['$155997314481RCEII:testmatrix.vgorcum.com', '$15..., latest_events=['$15599731921601uiBel:half-shot.uk'], limit=10, min_depth=17410, timeout=60000
2019-06-08 05:53:49,224 - synapse.http.matrixfederationclient - 401 - INFO - PUT-5546-$15599731921601uiBel:half-shot.uk - {POST-O-2558} [half-shot.uk] Sending request: POST matrix://half-shot.uk/_matrix/federation/v1/get_missing_events/%21MbRaSiMIRhhxDtJENL%3Amaunium.net; timeout 60.000000s
2019-06-08 05:53:49,240 - synapse.http.matrixfederationclient - 425 - INFO - PUT-5546-$15599731921601uiBel:half-shot.uk - Failed to send request: [<twisted.python.failure.Failure builtins.AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'>]
2019-06-08 05:53:49,241 - synapse.http.matrixfederationclient - 482 - WARNING - PUT-5546-$15599731921601uiBel:half-shot.uk - {POST-O-2558} [half-shot.uk] Request failed: POST matrix://half-shot.uk/_matrix/federation/v1/get_missing_events/%21MbRaSiMIRhhxDtJENL%3Amaunium.net: RequestGenerationFailed:[AttributeError("'QuieterFileBodyProducer' object has no attribute '_task'",)]
2019-06-08 05:53:49,241 - synapse.util.retryutils - 214 - INFO - PUT-5546-$15599731921601uiBel:half-shot.uk - Connection to half-shot.uk was unsuccessful (<class 'synapse.api.errors.RequestSendFailed'>(Failed to send request: RequestGenerationFailed: [<twisted.python.failure.Failure builtins.AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'>])); backoff now 600000
2019-06-08 05:53:49,243 - synapse.util.async_helpers - 237 - DEBUG - PUT-5546-$15599731921601uiBel:half-shot.uk - Releasing linearizer lock 'fed_room_pdu' for key '!MbRaSiMIRhhxDtJENL:maunium.net'
2019-06-08 05:53:49,243 - synapse.storage.txn - 397 - DEBUG - PUT-5546-$15599731921601uiBel:half-shot.uk - [TXN START] {set_destination_retry_timings-61e4}
2019-06-08 05:53:49,243 - synapse.util.async_helpers - 277 - DEBUG - PUT-5543-$15599731908328xLIfd:maunium.net - Acquired linearizer lock 'fed_room_pdu' for key '!MbRaSiMIRhhxDtJENL:maunium.net'
2019-06-08 05:53:49,246 - synapse.federation.federation_server - 258 - ERROR - PUT-5546-$15599731921601uiBel:half-shot.uk - Failed to handle PDU $15599731921601uiBel:half-shot.uk
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 421, in _send_request
    response = yield request_deferred
twisted.web._newclient.RequestGenerationFailed: [<twisted.python.failure.Failure builtins.AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 246, in process_pdus_for_room
    origin, pdu
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 701, in _handle_received_pdu
    origin, pdu, sent_to_us_directly=True,
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/federation.py", line 256, in on_receive_pdu
    origin, pdu, prevs, min_depth
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/federation.py", line 504, in _get_missing_events_for_pdu
    timeout=60000,
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 953, in get_missing_events
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 504, in get_missing_events
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 695, in post_json
    ignore_backoff=ignore_backoff,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 426, in _send_request
    raise_from(RequestSendFailed(e, can_retry=True), e)
  File "<string>", line 3, in raise_from
synapse.api.errors.RequestSendFailed: Failed to send request: RequestGenerationFailed: [<twisted.python.failure.Failure builtins.AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'>]
2019-06-08 05:53:49,315 - synapse.federation.federation_server - 278 - DEBUG - PUT-5546 - Returning: {'pdus': {'$15599731921601uiBel:half-shot.uk': {'error': "Failed to send request: RequestGenerationFailed: [<twisted.python.failure.Failure builtins.AttributeError: 'QuieterFileBodyProducer' object has no attribute '_task'>]"}}}
```

- **Homeserver**: raim.ist

If not matrix.org:

- **Version**: 1.0.0rc1

**Comment by aaronraimist** [comment]
I haven't seen this recently so I'll close for now.

**Comment by richvdh** [comment]
we see it every couple of minutes on matrix.org :/

**Comment by clokep** [comment]
matrix.org saw this a couple of times around when this was filed and not since. Do we think this is still an issue?

**Comment by dkasak** [comment]
I was in the vicinity and stumbled onto this issue, so I quickly checked some EMS hosts to check. It's still an issue.

![image](https://user-images.githubusercontent.com/463342/202001900-8a835df3-40dd-46cf-8227-46402ca272c2.png)
