### ISSUE TITLE
Can't delete group with remote user - matrix.org/remove: HttpResponseException("400: b'Bad Request'",)

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#5403]
```
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,108 - synapse.access.http.8008 - 233 - INFO - POST-31388 - - 8008 - Received request: POST /_synapse/admin/v1/delete_group/+test:raim.ist?access_token=<redacted>
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,109 - synapse.storage.txn - 397 - DEBUG - POST-31388 - [TXN START] {is_server_admin-16b71}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,111 - synapse.storage.txn - 459 - DEBUG - POST-31388 - [TXN END] {is_server_admin-16b71} 0.001427 sec
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,112 - synapse.storage.txn - 397 - DEBUG - POST-31388 - [TXN START] {get_group-16b72}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,114 - synapse.storage.txn - 459 - DEBUG - POST-31388 - [TXN END] {get_group-16b72} 0.002181 sec
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,115 - synapse.storage.txn - 397 - DEBUG - POST-31388 - [TXN START] {is_user_in_group-16b73}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,117 - synapse.storage.txn - 459 - DEBUG - POST-31388 - [TXN END] {is_user_in_group-16b73} 0.001868 sec
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,119 - synapse.storage.txn - 397 - DEBUG - POST-31388 - [TXN START] {is_user_admin_in_group-16b74}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,120 - synapse.storage.txn - 459 - DEBUG - POST-31388 - [TXN END] {is_user_admin_in_group-16b74} 0.001465 sec
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,121 - synapse.storage.txn - 397 - DEBUG - POST-31388 - [TXN START] {get_users_in_group-16b75}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,122 - synapse.storage.txn - 459 - DEBUG - POST-31388 - [TXN END] {get_users_in_group-16b75} 0.001458 sec
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,123 - synapse.federation.transport.client - 710 - DEBUG - POST-31388 - Invoked 'remove_user_from_group_notification' with args: self=<synapse.federation.transport.client.TransportLaye..., destination=matrix.org, group_id=+test:raim.ist, user_id=@aaronraimist:matrix.org, content={}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,124 - synapse.http.matrixfederationclient - 401 - INFO - POST-31388 - {POST-O-9971} [matrix.org] Sending request: POST matrix://matrix.org/_matrix/federation/v1/groups/local/%2Btest%3Araim.ist/users/%40aaronraimist%3Amatrix.org/remove; timeout 60.000000s
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,125 - synapse.http.federation.matrix_federation_agent - 273 - DEBUG - POST-31388 - Picked matrix.org.cdn.cloudflare.net:8443 from SRV records for matrix.org
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,299 - synapse.http.matrixfederationclient - 433 - INFO - POST-31388 - {POST-O-9971} [matrix.org] Got response headers: 400 Bad Request
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,300 - synapse.http.matrixfederationclient - 517 - WARNING - POST-31388 - {POST-O-9971} [matrix.org] Request failed: POST matrix://matrix.org/_matrix/federation/v1/groups/local/%2Btest%3Araim.ist/users/%40aaronraimist%3Amatrix.org/remove: HttpResponseException("400: b'Bad Request'",)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,301 - synapse.http.server - 112 - ERROR - POST-31388 - Failed handle request via 'DeleteGroupAdminRestServlet': <XForwardedForRequest at 0x7f0349256748 method='POST' uri='/_synapse/admin/v1/delete_group/+test:raim.ist?access_token=<redacted>' clientproto='HTTP/1.0' site=8008>Jun 08 23:06:22 ubuntu matrix-synapse[8681]: Traceback (most recent call last):
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     yield h(self, request)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     callback_return = yield callback(request, **kwargs)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/rest/admin/__init__.py", line 777, in on_POST
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     yield self.group_server.delete_group(group_id, requester.user.to_string())
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/groups/groups_server.py", line 966, in delete_group
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     yield concurrently_execute(_kick_user_from_group, non_admins, 10)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/util/async_helpers.py", line 149, in _concurrently_execute_inner
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     yield func(next(it))
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/groups/groups_server.py", line 945, in _kick_user_from_group
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     get_domain_from_id(user_id), group_id, user_id, {}
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = result.throwExceptionIntoGenerator(g)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     return g.throw(self.type, self.value, self.tb)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 695, in post_json
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     ignore_backoff=ignore_backoff,
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     result = g.send(result)
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:   File "/usr/local/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 472, in _send_request
Jun 08 23:06:22 ubuntu matrix-synapse[8681]:     raise e
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: synapse.api.errors.HttpResponseException: 400: b'Bad Request'
Jun 08 23:06:22 ubuntu matrix-synapse[8681]: 2019-06-08 23:06:22,373 - synapse.access.http.8008 - 302 - INFO - POST-31388 - 2001:48f8:3006:3b8:c5ee:35b4:53f9:2847 - 8008 - {@aaron:raim.ist} Processed request: 0.258sec/0.007sec (0.082sec, 0.000sec) (0.001sec/0.008sec/5) 69B 500 "POST /_synapse/admin/v1/delete_group/+test:raim.ist?access_token=<redacted> HTTP/1.0" "curl/7.54.0" [0 dbevts]
```
### Version information

- **Homeserver**: raim.ist, user that couldn't be removed is on matrix.org

If not matrix.org:

- **Version**: 1.0.0rc1

**Comment by clokep** [comment]
Communities/groups are being removed, see #11584.
