### ISSUE TITLE
Sync: list index out of range

### ISSUE THREAD

**Issue by waylon531** [matrix-org/synapse#5407]
### Description

This morning when opened up Riot I got a message that I had lost connectivity to the homeserver. Synapse and all of its workers appeared to be running fine, but my logs for the synchrotron worker were filled with this error message:

https://gist.github.com/waylon531/90c205b7540ea017dbf0fec705506e05

As far as workers go I'm running a federation sender, a federation reader, and a synchrotron worker. The synchrotron worker is the only worker that appears to be broken. I have no clue what caused this error, the server was working fine last night and appears to have broken by itself overnight.

### Version information

- **Homeserver**: riot.firechicken.net

- **Version**: 99.5.2

- **Install method**: pip

- **Platform**: A google cloud VPS running CentOS 7

**Comment by aaronraimist** [comment]
Related: https://github.com/matrix-org/synapse/issues/4842

By the way it is probably better if you paste your error in here in a code block so it is searchable

**Comment by waylon531** [comment]
Will do, here it is:
```
2019-06-09 19:03:46,553 - synapse.http.server - 112 - ERROR - GET-835 - Failed handle request via 'SyncRestServlet': <SynapseRequest at 0x7f955618ce10 method='GET' uri='/_matrix/client/r0/sync?filter=0&timeout=0&since=s707461_26561430_2874_634533_24909_56_95_55442_1' clientproto='HTTP/1.0' site=8083>
Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py", line 527, in runWithConnection
    defer.returnValue(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [_EventDictReturn(event_id='$15600950391010258hrwAd:matrix.org', topological_ordering=None, stream_ordering=708773), _EventDictReturn(event_id='$15600950171010117CdspK:matrix.org', topological_ordering=None, stream_ordering=708772), _EventDictReturn(event_id='$15600949401009508lTpzl:matrix.org', topological_ordering=None, stream_ordering=708771), _EventDictReturn(event_id='$15600949261009398foetQ:matrix.org', topological_ordering=None, stream_ordering=708770), _EventDictReturn(event_id='$15600949091009307PONGY:matrix.org', topological_ordering=None, stream_ordering=708769), _EventDictReturn(event_id='$15600948911009164JkHeG:matrix.org', topological_ordering=None, stream_ordering=708768), _EventDictReturn(event_id='$15600948821009108qkrIj:matrix.org', topological_ordering=None, stream_ordering=708767), _EventDictReturn(event_id='$15600948591008929UoHxd:matrix.org', topological_ordering=None, stream_ordering=708766), _EventDictReturn(event_id='$15600948501008732joyAz:matrix.org', topological_ordering=None, stream_ordering=708765), _EventDictReturn(event_id='$15600948321008586DDtRZ:matrix.org', topological_ordering=None, stream_ordering=708764), _EventDictReturn(event_id='$15600948311008562BFdsx:matrix.org', topological_ordering=None, stream_ordering=708763), _EventDictReturn(event_id='$15600948311008555lylfW:matrix.org', topological_ordering=None, stream_ordering=708762), _EventDictReturn(event_id='$15600948051008364bsBFK:matrix.org', topological_ordering=None, stream_ordering=708761), _EventDictReturn(event_id='$15600947551008018jCiVq:matrix.org', topological_ordering=None, stream_ordering=708760), _EventDictReturn(event_id='$15600947491007978QDPLH:matrix.org', topological_ordering=None, stream_ordering=708759), _EventDictReturn(event_id='$15600947131007663SiNSd:matrix.org', topological_ordering=None, stream_ordering=708758), _EventDictReturn(event_id='$15600946391007033aolro:matrix.org', topological_ordering=None, stream_ordering=708755), _EventDictReturn(event_id='$15600946091006766ZzkSV:matrix.org', topological_ordering=None, stream_ordering=708754), _EventDictReturn(event_id='$15600945021005812lLBZU:matrix.org', topological_ordering=None, stream_ordering=708752), _EventDictReturn(event_id='$15600945001005804zAlqr:matrix.org', topological_ordering=None, stream_ordering=708751), _EventDictReturn(event_id='$15600945001005796CUSFf:matrix.org', topological_ordering=None, stream_ordering=708750)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py", line 487, in runInteraction
    defer.returnValue(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [_EventDictReturn(event_id='$15600950391010258hrwAd:matrix.org', topological_ordering=None, stream_ordering=708773), _EventDictReturn(event_id='$15600950171010117CdspK:matrix.org', topological_ordering=None, stream_ordering=708772), _EventDictReturn(event_id='$15600949401009508lTpzl:matrix.org', topological_ordering=None, stream_ordering=708771), _EventDictReturn(event_id='$15600949261009398foetQ:matrix.org', topological_ordering=None, stream_ordering=708770), _EventDictReturn(event_id='$15600949091009307PONGY:matrix.org', topological_ordering=None, stream_ordering=708769), _EventDictReturn(event_id='$15600948911009164JkHeG:matrix.org', topological_ordering=None, stream_ordering=708768), _EventDictReturn(event_id='$15600948821009108qkrIj:matrix.org', topological_ordering=None, stream_ordering=708767), _EventDictReturn(event_id='$15600948591008929UoHxd:matrix.org', topological_ordering=None, stream_ordering=708766), _EventDictReturn(event_id='$15600948501008732joyAz:matrix.org', topological_ordering=None, stream_ordering=708765), _EventDictReturn(event_id='$15600948321008586DDtRZ:matrix.org', topological_ordering=None, stream_ordering=708764), _EventDictReturn(event_id='$15600948311008562BFdsx:matrix.org', topological_ordering=None, stream_ordering=708763), _EventDictReturn(event_id='$15600948311008555lylfW:matrix.org', topological_ordering=None, stream_ordering=708762), _EventDictReturn(event_id='$15600948051008364bsBFK:matrix.org', topological_ordering=None, stream_ordering=708761), _EventDictReturn(event_id='$15600947551008018jCiVq:matrix.org', topological_ordering=None, stream_ordering=708760), _EventDictReturn(event_id='$15600947491007978QDPLH:matrix.org', topological_ordering=None, stream_ordering=708759), _EventDictReturn(event_id='$15600947131007663SiNSd:matrix.org', topological_ordering=None, stream_ordering=708758), _EventDictReturn(event_id='$15600946391007033aolro:matrix.org', topological_ordering=None, stream_ordering=708755), _EventDictReturn(event_id='$15600946091006766ZzkSV:matrix.org', topological_ordering=None, stream_ordering=708754), _EventDictReturn(event_id='$15600945021005812lLBZU:matrix.org', topological_ordering=None, stream_ordering=708752), _EventDictReturn(event_id='$15600945001005804zAlqr:matrix.org', topological_ordering=None, stream_ordering=708751), _EventDictReturn(event_id='$15600945001005796CUSFf:matrix.org', topological_ordering=None, stream_ordering=708750)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/stream.py", line 414, in get_room_events_stream_for_room
    defer.returnValue((ret, key))
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: ([<FrozenEvent event_id='$15600945001005796CUSFf:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600945001005804zAlqr:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600945021005812lLBZU:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600946091006766ZzkSV:matrix.org', type='m.room.member', state_key='@freenode_heatsink:matrix.org'>, <FrozenEvent event_id='$15600946391007033aolro:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600947131007663SiNSd:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600947491007978QDPLH:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600947551008018jCiVq:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948051008364bsBFK:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948311008555lylfW:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948311008562BFdsx:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948321008586DDtRZ:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948501008732joyAz:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948591008929UoHxd:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948821009108qkrIj:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600948911009164JkHeG:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600949091009307PONGY:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600949261009398foetQ:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600949401009508lTpzl:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600950171010117CdspK:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$15600950391010258hrwAd:matrix.org', type='m.room.message', state_key='None'>], 's708750')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 472, in _load_filtered_recents
    limited=limited or newly_joined_room
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: TimelineBatch(prev_batch=StreamToken(room_key='s708889', presence_key=26599051, typing_key=57, receipt_key=636004, account_data_key=24914, push_rules_key=56, to_device_key=95, device_list_key=55442, groups_key=1), events=[], limited=True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/sync.py", line 167, in on_GET
    full_state=full_state
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 242, in wait_for_sync_for_user
    sync_config, since_token, timeout, full_state,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 264, in _wait_for_sync_for_user
    sync_config, since_token, full_state=full_state,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 935, in generate_sync_result
    sync_result_builder, account_data_by_room
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 1316, in _generate_sync_entry_for_rooms
    yield concurrently_execute(handle_room_entries, room_entries, 10)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/util/async_helpers.py", line 149, in _concurrently_execute_inner
    yield func(next(it))
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 1752, in _generate_room_entry
    full_state=full_state
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/sync.py", line 775, in compute_state_delta
    batch.events[0].event_id, state_filter=state_filter,
IndexError: list index out of range
```

**Comment by waylon531** [comment]
Here's the object I'm getting with no events:
```
TimelineBatch(prev_batch=StreamToken(room_key='s708889', presence_key=26606688, 
  typing_key=181, receipt_key=636329, account_data_key=24914, push_rules_key=56, 
  to_device_key=95, device_list_key=55442, groups_key=1), 
events=[], limited=True)
```

**Comment by waylon531** [comment]
For some reason this error only happens when I'm connecting via my self-hosted riot instance. I can connect fine using the android app even though both clients are calling the same endpoint

This request triggers the error: `GET /_matrix/client/r0/sync?filter=0&timeout=0&since=s707461_26561430_2874_634533_24909_56_95_55442_1`

But this doesn't: `GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s710004_26612436_282_636657_24915_56_95_55442_1`

**Comment by Half-Shot** [comment]
>For some reason this error only happens when I'm connecting via my self-hosted riot instance. I can connect fine using the android app even though both clients are calling the same endpoint

Have you tried doing cache refresh in your riot instance? Could be some broken incremental sync data.

**Comment by waylon531** [comment]
Yep, that did it. It's working now, thanks!

**Comment by waylon531** [comment]
It turns out that clearing the cache was a temporary fix. I get the same issue about once a day now, fortunately fixing it again is pretty easy but it's still annoying

**Comment by richvdh** [comment]
So this is the same as #4842, which we never got to the bottom of. Again, the surprising thing is that the returned results have `limited=True` with `events=[]`. 

@waylon531 I'm interested in the settings on your sync filter. Can you share the results of this database query: `select encode(filter_json, 'escape') from user_filters where user_id='uelen' and filter_id=0;`

**Comment by waylon531** [comment]
Here it is:
```
synapse=> select encode(filter_json, 'escape') from user_filters where user_id='uelen' and filter_id=0;
                    encode                     
-----------------------------------------------
 {"room":{"state":{"lazy_load_members":true}}}
(1 row)
```

**Comment by ara4n** [comment]
Parity are seeing this too for a user on their homeserver with precisely the same symptoms - it's fixed by clearing cache, but then breaks roughly once a day.  stacktrace is:

```
2019-08-02 09:55:04,695 - synapse.handlers.sync - 1859 - INFO - GET-654776- Incremental gappy sync of !fOOzymDEHiIIUtmlBE:matrix.org for user @xxxxx:matrix.parity.io with 6 state events
2019-08-02 09:55:04,698 - synapse.http.server - 108 - ERROR - GET-654776- Failed handle request via 'SyncRestServlet': <SynapseRequest at 0x7f15030838d0 method='GET' uri='/_matrix/client/r0/sync?filter=2&set_presence=offline&timeout=30000&since=s4595570_52728671_220931_4516767_2479108_3345_1584806_196913_331' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 542, in runWithConnection
    defer.returnValue(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [_EventDictReturn(event_id='$1564717051444590nClvE:matrix.org', topological_ordering=None, stream_ordering=4609238), _EventDictReturn(event_id='$1564717038444527BwigZ:matrix.org', topological_ordering=None, stream_ordering=4609236), _EventDictReturn(event_id='$1564716506441830NfarU:matrix.org', topological_ordering=None, stream_ordering=4609230), _EventDictReturn(event_id='$1564716455441595yCQRr:matrix.org', topological_ordering=None, stream_ordering=4609229), _EventDictReturn(event_id='$1564716259440492UVxKe:matrix.org', topological_ordering=None, stream_ordering=4609224), _EventDictReturn(event_id='$1564715302434816qGSGE:matrix.org', topological_ordering=None, stream_ordering=4609207), _EventDictReturn(event_id='$1564715262434620WyShA:matrix.org', topological_ordering=None, stream_ordering=4609206), _EventDictReturn(event_id='$1564715241434521QPSqb:matrix.org', topological_ordering=None, stream_ordering=4609205), _EventDictReturn(event_id='$1564715130433764KOzNu:matrix.org', topological_ordering=None, stream_ordering=4609203), _EventDictReturn(event_id='$1564714939432644bZqIZ:matrix.org', topological_ordering=None, stream_ordering=4609201), _EventDictReturn(event_id='$1564714912432488TrYwO:matrix.org', topological_ordering=None, stream_ordering=4609198), _EventDictReturn(event_id='$1564714904432430RIFIp:matrix.org', topological_ordering=None, stream_ordering=4609197), _EventDictReturn(event_id='$1564714807431835pTodu:matrix.org', topological_ordering=None, stream_ordering=4609196), _EventDictReturn(event_id='$1564714805431828upIXQ:matrix.org', topological_ordering=None, stream_ordering=4609195), _EventDictReturn(event_id='$1564714797431782rphGA:matrix.org', topological_ordering=None, stream_ordering=4609194), _EventDictReturn(event_id='$1564714795431770TYuPq:matrix.org', topological_ordering=None, stream_ordering=4609193), _EventDictReturn(event_id='$1564714794431759jTOAF:matrix.org', topological_ordering=None, stream_ordering=4609192), _EventDictReturn(event_id='$1564714792431752otGTC:matrix.org', topological_ordering=None, stream_ordering=4609191), _EventDictReturn(event_id='$1564714792431749MouBZ:matrix.org', topological_ordering=None, stream_ordering=4609190), _EventDictReturn(event_id='$1564714791431747VGcSe:matrix.org', topological_ordering=None, stream_ordering=4609189), _EventDictReturn(event_id='$1564714791431745CKyqe:matrix.org', topological_ordering=None, stream_ordering=4609188)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 502, in runInteraction
    defer.returnValue(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: [_EventDictReturn(event_id='$1564717051444590nClvE:matrix.org', topological_ordering=None, stream_ordering=4609238), _EventDictReturn(event_id='$1564717038444527BwigZ:matrix.org', topological_ordering=None, stream_ordering=4609236), _EventDictReturn(event_id='$1564716506441830NfarU:matrix.org', topological_ordering=None, stream_ordering=4609230), _EventDictReturn(event_id='$1564716455441595yCQRr:matrix.org', topological_ordering=None, stream_ordering=4609229), _EventDictReturn(event_id='$1564716259440492UVxKe:matrix.org', topological_ordering=None, stream_ordering=4609224), _EventDictReturn(event_id='$1564715302434816qGSGE:matrix.org', topological_ordering=None, stream_ordering=4609207), _EventDictReturn(event_id='$1564715262434620WyShA:matrix.org', topological_ordering=None, stream_ordering=4609206), _EventDictReturn(event_id='$1564715241434521QPSqb:matrix.org', topological_ordering=None, stream_ordering=4609205), _EventDictReturn(event_id='$1564715130433764KOzNu:matrix.org', topological_ordering=None, stream_ordering=4609203), _EventDictReturn(event_id='$1564714939432644bZqIZ:matrix.org', topological_ordering=None, stream_ordering=4609201), _EventDictReturn(event_id='$1564714912432488TrYwO:matrix.org', topological_ordering=None, stream_ordering=4609198), _EventDictReturn(event_id='$1564714904432430RIFIp:matrix.org', topological_ordering=None, stream_ordering=4609197), _EventDictReturn(event_id='$1564714807431835pTodu:matrix.org', topological_ordering=None, stream_ordering=4609196), _EventDictReturn(event_id='$1564714805431828upIXQ:matrix.org', topological_ordering=None, stream_ordering=4609195), _EventDictReturn(event_id='$1564714797431782rphGA:matrix.org', topological_ordering=None, stream_ordering=4609194), _EventDictReturn(event_id='$1564714795431770TYuPq:matrix.org', topological_ordering=None, stream_ordering=4609193), _EventDictReturn(event_id='$1564714794431759jTOAF:matrix.org', topological_ordering=None, stream_ordering=4609192), _EventDictReturn(event_id='$1564714792431752otGTC:matrix.org', topological_ordering=None, stream_ordering=4609191), _EventDictReturn(event_id='$1564714792431749MouBZ:matrix.org', topological_ordering=None, stream_ordering=4609190), _EventDictReturn(event_id='$1564714791431747VGcSe:matrix.org', topological_ordering=None, stream_ordering=4609189), _EventDictReturn(event_id='$1564714791431745CKyqe:matrix.org', topological_ordering=None, stream_ordering=4609188)]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/storage/stream.py", line 410, in get_room_events_stream_for_room
    defer.returnValue((ret, key))
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: ([<FrozenEvent event_id='$1564714791431745CKyqe:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714791431747VGcSe:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714792431749MouBZ:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714792431752otGTC:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714794431759jTOAF:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714795431770TYuPq:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714797431782rphGA:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714805431828upIXQ:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714807431835pTodu:matrix.org', type='m.room.message', state_key='None'>, <FrozenEvent event_id='$1564714904432430RIFIp:matrix.org', type='m.room.member', state_key='@mozilla_alx741:matrix.org'>, <FrozenEvent event_id='$1564714912432488TrYwO:matrix.org', type='m.room.member', state_key='@mozilla_asdasd:matrix.org'>, <FrozenEvent event_id='$1564714939432644bZqIZ:matrix.org', type='m.room.member', state_key='@mozilla_siddhartharao17:matrix.org'>, <FrozenEvent event_id='$1564715130433764KOzNu:matrix.org', type='m.room.member', state_key='@mozilla_siddhart_:matrix.org'>, <FrozenEvent event_id='$1564715241434521QPSqb:matrix.org', type='m.room.member', state_key='@mozilla_frum:matrix.org'>, <FrozenEvent event_id='$1564715262434620WyShA:matrix.org', type='m.room.member', state_key='@mozilla_frum:matrix.org'>, <FrozenEvent event_id='$1564715302434816qGSGE:matrix.org', type='m.room.member', state_key='@mozilla_siddhartharao17:matrix.org'>, <FrozenEvent event_id='$1564716259440492UVxKe:matrix.org', type='m.room.member', state_key='@mozilla_sp1ff1:matrix.org'>, <FrozenEvent event_id='$1564716455441595yCQRr:matrix.org', type='m.room.member', state_key='@mozilla_fowlslegs:matrix.org'>, <FrozenEvent event_id='$1564716506441830NfarU:matrix.org', type='m.room.member', state_key='@mozilla_machuga:matrix.org'>, <FrozenEvent event_id='$1564717038444527BwigZ:matrix.org', type='m.room.member', state_key='@mozilla_SandraRE:matrix.org'>, <FrozenEvent event_id='$1564717051444590nClvE:matrix.org', type='m.room.member', state_key='@mozilla_Guest12645:matrix.org'>], 's4609188')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/handlers/sync.py", line 497, in _load_filtered_recents
    limited=limited or newly_joined_room,
  File "/home/matrix/.synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: TimelineBatch(prev_batch=StreamToken(room_key='s4610833', presence_key=52921735, typing_key=7502, receipt_key=4534228, account_data_key=2500108, push_rules_key=3369, to_device_key=1593624, device_list_key=197629, groups_key=331), events=[], limited=True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/http/server.py", line 76, in wrapped_request_handler
    await h(self, request)
  File "/home/matrix/.synapse/lib/python3.5/site-packages/synapse/http/server.py", line 315, in _async_render
    callback_return = await callback_return
IndexError: list index out of range
2019-08-02 09:55:04,700 - synapse.access.http.8008 - 302 - INFO - GET-654776- 127.0.0.1 - 8008 - {@xxxxx:matrix.parity.io} Processed request: 0.391sec/0.000sec (0.253sec, 0.030sec) (0.451sec/0.965sec/110) 67B 500 "GET /_matrix/client/r0/sync?filter=2&set_presence=offline&timeout=30000&since=s4595570_52728671_220931_4516767_2479108_3345_1584806_196913_331 HTTP/1.0" "Riot.im/0.9.3 (Linux; U; Android 9; SM-G975F Build/PPR1.180610.01; Flavour GooglePlay; MatrixAndroidSDK 0.9.26)" [0 dbevts]
```

**Comment by ara4n** [comment]
...and parity now have another user being bitten by this.

**Comment by erikjohnston** [comment]
I've pushed https://github.com/matrix-org/synapse/pull/5825, which should a) fix this and b) add some logging to figure out how this comes about. It would be great if those that were bitten by this could keep an eye on their logs for the new logging, that would be greatly appreciated.

**Comment by erikjohnston** [comment]
At least one cause of this appears to be that the syncing user has ignored the senders of all recent events. `_load_filtered_recents` will loop to attempt to fetch more events, but has a limit to stop it from spinning. 

We could potentially handle this case better, but it doesn't particularly feel like an actual bug that this happens.
