### ISSUE TITLE
synapse_port_db fails while processing server_signature_keys

### ISSUE THREAD

**Issue by voice06** [matrix-org/synapse#5409]
### Description

Attempting to get my homeserver ready for 1.0 by getting it off of sqlite to postgres however whenever I run the port script it fails out while processing the table server_signature_keys:

```
2019-06-09 21:24:15,778 - synapse.metrics - 372 - INFO - Collecting gc 1
2019-06-09 21:24:15,883 - synapse.metrics - 372 - INFO - Collecting gc 0
2019-06-09 21:24:15,903 - synapse_port_db - 172 - ERROR - Failed to insert: server_signature_keys
Traceback (most recent call last):
  File "/home/matrixserv/synapse/env/bin/synapse_port_db", line 170, in insert_many_txn
    txn.executemany(sql, rows)
  File "/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 131, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py", line 154, in _do_execute
    return func(sql, *args)
psycopg2.errors.UndefinedColumn: column "ts_valid_until_ms" of relation "server_signature_keys" does not exist
LINE 1: ...me, key_id, from_server, ts_added_ms, verify_key, ts_valid_u...
                                                             ^
pushers: 100% (1/1)

device_max_stream_id: 100% (1/1)
event_backward_extremities: 100% (2/2)
device_lists_remote_cache: 100% (137/137)
user_daily_visits: 100% (126/126)
2019-06-09 21:24:16,152 - synapse.metrics - 372 - INFO - Collecting gc 2
2019-06-09 21:24:16,281 - synapse.metrics - 372 - INFO - Collecting gc 0
account_data_max_stream_id: 100% (1/1)
e2e_room_keys_versions: 100% (2/2)
application_services_state: 100% (4/4)
event_push_summary_stream_ordering: 100% (1/1)
event_forward_extremities: 100% (21/21)
2019-06-09 21:24:16,333 - synapse_port_db - 548 - ERROR - 
Traceback (most recent call last):
  File "/home/matrixserv/synapse/env/bin/synapse_port_db", line 538, in run
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
twisted.internet.defer.FirstError: FirstError[#40, [Failure instance: Traceback: <class 'psycopg2.errors.UndefinedColumn'>: column "ts_valid_until_ms" of relation "server_signature_keys" does not exist
LINE 1: ...me, key_id, from_server, ts_added_ms, verify_key, ts_valid_u...
                                                             ^

/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:501:errback
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/home/matrixserv/synapse/env/bin/synapse_port_db:348:handle_table
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/compat.py:464:reraise
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/home/matrixserv/synapse/env/bin/synapse_port_db:136:r
/home/matrixserv/synapse/env/bin/synapse_port_db:336:insert
/home/matrixserv/synapse/env/bin/synapse_port_db:170:insert_many_txn
/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py:131:executemany
/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py:154:_do_execute
]]
deleted_pushers: 100% (1/1)
application_services_txns: 100% (6/6)
users_in_public_rooms: 100% (329/329)
room_aliases: 100% (6/6)
profiles: 100% (34/34)
2019-06-09 21:24:17,924 - synapse.metrics - 372 - INFO - Collecting gc 0
Traceback (most recent call last):
  File "/home/matrixserv/synapse/env/bin/synapse_port_db", line 538, in run
    [self.handle_table(*res) for res in setup_res], consumeErrors=True
twisted.internet.defer.FirstError: FirstError[#40, [Failure instance: Traceback: <class 'psycopg2.errors.UndefinedColumn'>: column "ts_valid_until_ms" of relation "server_signature_keys" does not exist
LINE 1: ...me, key_id, from_server, ts_added_ms, verify_key, ts_valid_u...
                                                             ^

/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:501:errback
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/home/matrixserv/synapse/env/bin/synapse_port_db:348:handle_table
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/python/compat.py:464:reraise
/home/matrixserv/synapse/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/home/matrixserv/synapse/env/bin/synapse_port_db:136:r
/home/matrixserv/synapse/env/bin/synapse_port_db:336:insert
/home/matrixserv/synapse/env/bin/synapse_port_db:170:insert_many_txn
/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py:131:executemany
/home/matrixserv/synapse/env/lib/python3.6/site-packages/synapse/storage/_base.py:154:_do_execute
]]
```

### Steps to reproduce

- Follow the steps outlined in [postgres.rst](https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst)

### Version information

- **Version**: 0.99.5.2

- **Install method**: 
pip

- **Platform**: 
Linux VM - Ubuntu 18.10
Python 3.6

**Comment by richvdh** [comment]
this seems to have fallen through the cracks. is it still an issue?

**Comment by voice06** [comment]
That instance has been long since blown away and replaced with a new one
running postgresql.
