### ISSUE TITLE
Federation silently breaks (to users of 3rd party server) with error:  "x509: certificate signed by unknown authority" using LetsEncrypt.

### ISSUE THREAD

**Issue by unknown-user-9246102101** [matrix-org/synapse#5429]
I am unable to ask for support in the support room because my user info returns 401 Unauthorized on REST calls to matrix servers. Therefore the room I cannot join. The errors in the log look like this:

```
2019-06-11 15:35:07,589 - synapse.http.server - 112 - ERROR - GET-524 - Failed handle request via <function JsonResource._async_render at 0x000000080d92efc0>: <XForwardedForRequest at 0x80dc26838 method='GET' uri='/_matrix/client/r0/directory/room/%23matrix%3Amatrix.org' clientproto='HTTP/1.0' site=8833>: Traceback (most recent call last)


  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/usr/home/matrix/venv/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/home/matrix/venv/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/home/matrix/venv/site-packages/synapse/rest/client/v1/directory.py", line 49, in on_GET
    res = yield dir_handler.get_association(room_alias)
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/home/matrix/venv/site-packages/synapse/handlers/directory.py", line 226, in get_association
    ignore_backoff=True,
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/home/matrix/venv/site-packages/synapse/federation/transport/client.py", line 195, in make_query
    ignore_backoff=ignore_backoff,
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/home/matrix/venv/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/home/matrix/venv/site-packages/synapse/http/matrixfederationclient.py", line 616, in get_json
    ignore_backoff=ignore_backoff,
  File "/usr/home/matrix/venv/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/home/matrix/venv/site-packages/synapse/http/matrixfederationclient.py", line 400, in _send_request
    response.code, response.phrase, body
synapse.api.errors.HttpResponseException: 401: b'Unauthorized'
```

I have ran the following:

```(venv) $ curl 'https://federationtester.matrix.org/api/report?server_name=SNIP'
{
  "WellKnownResult": {
    "m.server": "",
    "result": "No .well-known found"
  },
  "DNSResult": {
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": {
      "Message": "lookup _matrix._tcp.SNIP on NSSNIP: no such host"
    },
    "Hosts": {
      "SNIP": {
        "CName": "SNIP.",
        "Addrs": [
          "ADDRSNIP"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "ADDRSNIP:8448"
    ]
  },
  "ConnectionReports": {
    "ADDRSNIP:8448": {
      "Certificates": [
        {
          "SubjectCommonName": "CNSNIP",
          "IssuerCommonName": "Let's Encrypt Authority X3",
          "SHA256Fingerprint": "jY8pf8B5rs/f+cmcC8eb9LXmnPvnTw6p574PPV8zAjs",
          "DNSNames": [
            "SNIP",
            "CNSNIP",
            "WWWSNIP"
          ]
        }
      ],
      "Cipher": {
        "Version": "TLS 1.2",
        "CipherSuite": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      },
      "Checks": {
        "AllChecksOK": false,
        "MatchingServerName": true,
        "FutureValidUntilTS": true,
        "HasEd25519Key": true,
        "AllEd25519ChecksOK": true,
        "Ed25519Checks": {
          "ed25519:a_BXbX": {
            "ValidEd25519": true,
            "MatchingSignature": true
          }
        },
        "ValidCertificates": false
      },
      "Errors": [
        {
          "Message": "x509: certificate signed by unknown authority"
        }
      ],
      "Ed25519VerifyKeys": {
        "ed25519:a_BXbX": "HL4rh3GKY4ig6fmgJzkcyO3nq7/0lOVM6Fn6l9eqdoI"
      },
      "Info": {},
      "Keys": {
        "old_verify_keys": {},
        "server_name": "SNIP",
        "signatures": {
          "SNIP": {
            "ed25519:a_BXbX": "ZwUlTbKGuCuczWowwnfX8w5BXrSxlMQEfXd3vgjx8qlKe7tDTxgakpE8pIf/EieT4Zpaj17Uw5hCCbwX+TTDDg"
          }
        },
        "tls_fingerprints": [
          {
            "sha256": "jY8pf8B5rs/f+cmcC8eb9LXmnPvnTw6p574PPV8zAjs"
          }
        ],
        "valid_until_ts": 1560367496623,
        "verify_keys": {
          "ed25519:a_BXbX": {
            "key": "HL4rh3GKY4ig6fmgJzkcyO3nq7/0lOVM6Fn6l9eqdoI"
          }
        }
      }
    }
  },
  "ConnectionErrors": {},
  "Version": {
    "name": "Synapse",
    "version": "0.33.8"
  },
  "FederationOK": false
}
```

I did update security/ca_root_nss to no avail (same error returned) though I am fairly certain that either that's not my error, or that I may need to get new keys with LetsEncrypt.

I am stuck on what to do next and would appreciate advice/debugging/etc.

Furthermore, there is no alarming in clients like when the server is not available. I simply appear offline to others, and I enter a quasi multidimensional alternate universe as far as I'm aware. I understand it's self hosted and therefore my responsibility, and luckily I did check the logs and do research. Just a not however it would have been helpful to notify everyone in the room with at least a orange warning (or if it's specific to me then to only me) -- Just a suggestion to prevent others having to go through it.

**Comment by aaronraimist** [comment]
You already opened #5428?

**Comment by unknown-user-9246102101** [comment]
Weird. Sorry about that. I was previewing it to make sure it looked up okay and maybe a keyboard shortcut happened. Not my intent to dupe it.

**Comment by richvdh** [comment]
Make sure you include the full certificate chain

**Comment by richvdh** [comment]
sorry, that was unnecessarily cryptic. What I mean is: when you give synapse (or your reverse proxy) the TLS cert from letsencrypt, make sure you use the fullchain.pem file rather than just the leaf certificate file: it's important to include the intermediate certificates, as the letsencrypt CA is typically not directly trusted by most operating systems' CA configs.

**Comment by unknown-user-9246102101** [comment]
Ahhhhhhhh that makes sense. My setup is a bit weird but this configuration change would be correct for me. This worked for me.
In `matrix.yaml` pseudo diff
```
----
-tls_certificate_path: "/etc/ssl/certs/SNIP/cert.pem"
----
+tls_certificate_path: "/etc/ssl/certs/SNIP/fullchain.pem"
----
```

Also, updated to 0.34, then 1.0.

You all work quick and I very much appreciate it. Thank you very much for your help.

**Comment by jobukkit** [comment]
I had this problem with a Comodo certificate (on Construct instead of Synapse). https://whatsmychaincert.com solved it.
