### ISSUE TITLE
ModuleNotFoundError: No module named 'jinja2'

### ISSUE THREAD

**Issue by Lrizika** [matrix-org/synapse#5431]
### As of #5377, jinja2 is an unconditional import in /rest/client/v2_alpha/account.py, but is still listed under CONDITIONAL_REQUIREMENTS in /python_dependencies.py

As a result, after upgrading with pip3 to 1.0.0, there's a ModuleNotFoundError (presumably, the same would occur on a new install):

```
~/synapse$ synctl start
Starting ...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 64, in <module>
    from synapse.rest import ClientRestResource
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/__init__.py", line 32, in <module>
    from synapse.rest.client.v2_alpha import (
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/account.py", line 21, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
error starting (exit code: 1); see above for logs
```

### Workaround:
Install jinja2 (`pip3 install jinja2`).

**Comment by 927589452** [comment]
can confirm the bug for fresh installations

**Comment by richvdh** [comment]
this should be a quickish fix and is a regression in 1.0

**Comment by menturion** [comment]
I can also confirm this bug for a fresh installation. Please fix this ASAP.

**Comment by anoadragon453** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/5514. Thanks for reporting.
