### ISSUE TITLE
Synapse 1.0 doesn't start.

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/synapse#5434]
```
-- The start-up result is done.
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]: Traceback (most recent call last):
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     "__main__", mod_spec)
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     exec(code, run_globals)
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 664, in <module>
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     main()
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 659, in main
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     hs = setup(sys.argv[1:])
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 331, in setup
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     config_options,
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 362, in load_or_generate_config
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     generate_keys=generate_keys,
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 408, in read_config_files
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     self.parse_config_dict(config)
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 411, in parse_config_dict
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     self.invoke_all("read_config", config_dict)
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 146, in invoke_all
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     results.append(getattr(cls, name)(self, *args, **kargs))
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/config/password.py", line 28, in read_config
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]:     self.password_enabled = password_config.get("enabled", True)
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]: AttributeError: 'str' object has no attribute 'get'
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b matrix-synapse[17337]: Found file in config directory that does not end in '.yaml': '/etc/matrix-synapse/conf.d/client.key'. IGNORING.
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b systemd[1]: matrix-synapse.service: Unit entered failed state.
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 12 07:55:17 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b sudo[17302]: pam_unix(sudo:session): session closed for user root
Jun 12 07:55:20 VM-f02b3b8b-ff70-403a-9a86-86eb9654da8b sudo[17346]:  pcadmin : TTY=pts/0 ; PWD=/home/pcadmin ; USER=root ; COMMAND=/bin/journalctl -xe
```

**Comment by PC-Admin** [comment]
Eep

**Comment by Half-Shot** [comment]
You are trying to load your client.key as a config file. You probably don't want it inside conf.d

**Comment by PC-Admin** [comment]
Where is is supposed to go?

**Comment by PC-Admin** [comment]
I didn't move any files around before this latest update so it's a bit wierd

**Comment by PC-Admin** [comment]
syntax error in homeserver.yaml

my bad!
