### ISSUE TITLE
Synapse fails with sqlite3.OperationalError: duplicate column name: ts_valid_until_ms after update to 1.0.0

### ISSUE THREAD

**Issue by jklmnn** [matrix-org/synapse#5436]
After upgrading matrix-synapse-py3 to 1.0.0+stretch1 the server doesn't start anymore with the following error:
```
2019-06-12 14:19:22,161 - root - 211 - WARNING - None- ***** STARTING SERVER *****
2019-06-12 14:19:22,188 - root - 214 - WARNING - None- Server /opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py version 1.0.0
2019-06-12 14:19:22,189 - root - 216 - INFO - None- Server hostname: xxx
2019-06-12 14:19:22,190 - twisted - 242 - INFO - None- Redirected stdout/stderr to logs
2019-06-12 14:19:22,217 - synapse.app.homeserver - 360 - INFO - None- Preparing database: sqlite3...
2019-06-12 14:19:22,222 - synapse.storage.prepare_database - 241 - INFO - None- Upgrading schema to v54
2019-06-12 14:19:22,222 - synapse.storage.prepare_database - 279 - INFO - None- Applying schema 54/add_validity_to_server_keys.sql
2019-06-12 14:19:22,223 - twisted - 242 - ERROR - - Traceback (most recent call last):
2019-06-12 14:19:22,224 - twisted - 242 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
2019-06-12 14:19:22,224 - twisted - 242 - ERROR - -     "__main__", mod_spec)
2019-06-12 14:19:22,225 - twisted - 242 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
2019-06-12 14:19:22,226 - twisted - 242 - ERROR - -     exec(code, run_globals)
2019-06-12 14:19:22,226 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 664, in <module>
2019-06-12 14:19:22,227 - twisted - 242 - ERROR - -     main()
2019-06-12 14:19:22,228 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 659, in main
2019-06-12 14:19:22,229 - twisted - 242 - ERROR - -     hs = setup(sys.argv[1:])
2019-06-12 14:19:22,230 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 364, in setup
2019-06-12 14:19:22,230 - twisted - 242 - ERROR - -     prepare_database(db_conn, database_engine, config=config)
2019-06-12 14:19:22,231 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/prepare_database.py", line 71, in prepare_database
2019-06-12 14:19:22,232 - twisted - 242 - ERROR - -     cur, user_version, delta_files, upgraded, database_engine, config
2019-06-12 14:19:22,232 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/prepare_database.py", line 280, in _upgrade_existing_database
2019-06-12 14:19:22,233 - twisted - 242 - ERROR - -     executescript(cur, absolute_path)
2019-06-12 14:19:22,234 - twisted - 242 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/prepare_database.py", line 412, in executescript
2019-06-12 14:19:22,234 - twisted - 242 - ERROR - -     txn.execute(statement)
2019-06-12 14:19:22,235 - twisted - 242 - ERROR - - sqlite3.OperationalError: duplicate column name: ts_valid_until_ms
```

**Comment by richvdh** [comment]
I'm guessing it started running the schema updates on a previous run, but didn't manage to complete them before being killed. Do you have the logs since the last time it started successfully?

**Comment by jklmnn** [comment]
I assume so. Unfortunately I don't have the logs anymore (since it was a small server I simply used the opportunity to set it up freshly with PostgreSQL). From what I can remember the part I posted was also the initial log after restarting the server after the update. It then repeated itself with each time the server tried to restart.
The database seems to be in a intermediate state. The old synapse version doesn't accept it as it is to new, the database conversion script says it's too old and the new synapse gives the posted error.

**Comment by richvdh** [comment]
> From what I can remember the part I posted was also the initial log after restarting the server after the update.

well, there should have been a bunch of other schema updates which should have been run first.

> I simply used the opportunity to set it up freshly with PostgreSQL
> The database seems to be in a intermediate state

I'm confused: you've recreated the database, but still have an inoperable system?

**Comment by jklmnn** [comment]
> I'm confused: you've recreated the database, but still have an inoperable system?
Sorry for the confusion. I encountered this issue and since I wasn't able to solve it and the server is quite small I set it up freshly. I now have a working system on Synapse 1.0.

Since I cannot provide the original logs anymore and it seems that nobody else has this issue I'd be fine if you close this issue.
In case you need any further information, I have the original database still lying around and could test it against different versions, give you some details about it (I hope you understand that I won't share the whole database).

**Comment by richvdh** [comment]
I'm going to assume that the problem stems from synapse being killed while it was trying to run the schema migrations, which isn't really something we can do much about.

Thanks for your feedback.

**Comment by menturion** [comment]
I am getting exactly the same issue after upgrading to synaspe v1.6.1.
How to fix this?

**Comment by menturion** [comment]
I am getting a similar issue after upgrading to synapse v1.6.1.
How to fix this?

```
> 
> $ synctl start
> Starting ...
> 2019-12-03 18:16:44,189 - twisted - 172 - INFO - None - Redirected stdout/stderr to logs
> 2019-12-03 18:16:44,190 - root - 237 - WARNING - None - ***** STARTING SERVER *****
> 2019-12-03 18:16:44,190 - root - 238 - WARNING - None - Server /var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.6.1
> 2019-12-03 18:16:44,190 - root - 239 - INFO - None - Server hostname: myhostname
> 2019-12-03 18:16:44,190 - synapse.app.homeserver - 360 - INFO - None - Preparing database: sqlite3...
> 2019-12-03 18:16:44,194 - synapse.storage.prepare_database - 301 - INFO - None - Upgrading schema to v56
> 2019-12-03 18:16:44,195 - synapse.storage.prepare_database - 364 - INFO - None - Applying schema 56/add_spans_to_device_lists.sql
> 2019-12-03 18:16:44,195 - twisted - 172 - ERROR -  - Traceback (most recent call last):
> 2019-12-03 18:16:44,195 - twisted - 172 - ERROR -  -   File "/opt/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> 2019-12-03 18:16:44,196 - twisted - 172 - ERROR -  -     "__main__", mod_spec)
> 2019-12-03 18:16:44,196 - twisted - 172 - ERROR -  -   File "/opt/python37/lib/python3.7/runpy.py", line 85, in _run_code
> 2019-12-03 18:16:44,196 - twisted - 172 - ERROR -  -     exec(code, run_globals)
> 2019-12-03 18:16:44,197 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 669, in <module>
> 2019-12-03 18:16:44,197 - twisted - 172 - ERROR -  -     main()
> 2019-12-03 18:16:44,197 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 664, in main
> 2019-12-03 18:16:44,198 - twisted - 172 - ERROR -  -     hs = setup(sys.argv[1:])
> 2019-12-03 18:16:44,198 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 364, in setup
> 2019-12-03 18:16:44,199 - twisted - 172 - ERROR -  -     prepare_database(db_conn, database_engine, config=config)
> 2019-12-03 18:16:44,199 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 82, in prepare_database
> 2019-12-03 18:16:44,199 - twisted - 172 - ERROR -  -     data_stores=data_stores,
> 2019-12-03 18:16:44,200 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 365, in _upgrade_existing_database
> 2019-12-03 18:16:44,200 - twisted - 172 - ERROR -  -     executescript(cur, absolute_path)
> 2019-12-03 18:16:44,200 - twisted - 172 - ERROR -  -   File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/storage/prepare_database.py", line 504, in executescript
> 2019-12-03 18:16:44,201 - twisted - 172 - ERROR -  -     txn.execute(statement)
> 2019-12-03 18:16:44,201 - twisted - 172 - ERROR -  - sqlite3.OperationalError: duplicate column name: opentracing_context
> error starting (exit code: 1); see above for logs
```

**Comment by jklmnn** [comment]
@menturion my fix was to start from scratch and loose all my users (I only had 2). Except from having to login into all my clients and loosing my E2E encryption fingerprints I didn't have any larger problems. I could even join all rooms I was in before. I only needed a room ID, but then I could even join the private ones and received my old admin rights. If you want to fix the database manually, someone else probably has to help you.

**Comment by richvdh** [comment]
@menturion please can you open a new issue for this.

**Comment by richvdh** [comment]
(we'll need all the logs since you upgraded, please. the trace above does not look sufficient.)
