### ISSUE TITLE
500 error when handling received events due to 'more than one row returned by a subquery used as an expression'

### ISSUE THREAD

**Issue by waylon531** [matrix-org/synapse#5454]
### Description

My homeserver is having issues federating with matrix.org. Users from matrix.org can usually see messages that I send, but messages from matrix.org typically take hours or days to be delivered to users on my homeserver. I went digging through my logs to try to figure out what the issue was, and I found these errors:

This is in the federation reader's log:
```
2019-06-13 19:45:25,091 - synapse.federation.federation_server - 258 - ERROR - PUT-167922-$15604476071471796lcdkC:matrix.org - Failed to handle PDU $15604476071471796lcdkC:matrix.org
Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/replication/http/_base.py", line 162, in send_request
    result = yield request_func(uri, data)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/http/client.py", line 393, in post_json_get_json
    raise HttpResponseException(response.code, response.phrase, body)
synapse.api.errors.HttpResponseException: 500: b'Internal Server Error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 246, in process_pdus_for_room
    origin, pdu
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 701, in _handle_received_pdu
    origin, pdu, sent_to_us_directly=True,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 256, in on_receive_pdu
    origin, pdu, prevs, min_depth
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 526, in _get_missing_events_for_pdu
    sent_to_us_directly=False,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 416, in on_receive_pdu
    auth_chain=auth_chain,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 589, in _process_received_pdu
    state=state,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 1642, in _handle_new_event
    backfilled=backfilled,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 2757, in persist_events_and_notify
    backfilled=backfilled
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/replication/http/_base.py", line 177, in send_request
    raise e.to_synapse_error()
synapse.api.errors.ProxiedRequestError: 500: Internal server error
```

And this is in the log of the main process;
```
2019-06-13 19:41:47,899 - synapse.http.server - 112 - ERROR - POST-189497 - Failed handle request via 'ReplicationFederationSendEventsRestServlet': <SynapseRequest at 0x7f3a9b882240 method='POST' uri='/_synapse/replication/fed_send_events/ddiBHmuOoS' clientproto='HTTP/1.1' site=9093>
Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/replication/http/federation.py", line 117, in _handle_request
    event_and_contexts, backfilled,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 2762, in persist_events_and_notify
    backfilled=backfilled,
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py", line 258, in persist_events
    defer.gatherResults(deferreds, consumeErrors=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.ProgrammingError'>: more than one row returned by a subquery used as an expression

/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
--- <exception caught here> ---
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:164:handle_queue_loop
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:295:persisting_queue
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:206:f
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:467:_persist_events
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:495:runInteraction
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:543:runWithConnection
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:306:_runWithConnection
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/compat.py:464:reraise
/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/enterprise/adbapi.py:297:_runWithConnection
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:540:inner_func
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:412:_new_transaction
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/util/logutils.py:88:wrapped
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:871:_persist_events_txn
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events.py:1000:_update_current_state_txn
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:132:executemany
/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/_base.py:155:_do_execute
]]
```

### Version information

- **Homeserver**: riot.firechicken.net

- **Version**: 1.0

- **Install method**: pip

- **Platform**: CentOS 7

**Comment by erikjohnston** [comment]
Hi, can you check in your postgres database if you have a unique index on `current_state_events (room_id, type, state_key)`? e.g. run `\d current_state_events` from psql:

```
$ psql synapse
psql (11.2 (Debian 11.2-2), server 9.6.12)
Type "help" for help.

synapse=# \d current_state_events
        Table "public.current_state_events"
  Column   | Type | Collation | Nullable | Default 
-----------+------+-----------+----------+---------
 event_id  | text |           | not null | 
 room_id   | text |           | not null | 
 type      | text |           | not null | 
 state_key | text |           | not null | 
Indexes:
    "current_state_events_event_id_key" UNIQUE CONSTRAINT, btree (event_id)
    "current_state_events_room_id_type_state_key_key" UNIQUE, btree (room_id, type, state_key)
    "current_state_events_member_index" btree (state_key) WHERE type = 'm.room.member'::text
    "current_state_events_rm_id_event_id" btree (room_id, event_id)
    "current_state_events_room_id_type_state_key_idx5" btree (room_id, type, state_key)
    "current_state_events_state_key" btree (state_key) WHERE type = 'm.room.member'::text

```

**Comment by waylon531** [comment]
I'm not sure how to read this output, but here's what I get from the query:

```
synapse=> \d current_state_events
        Table "public.current_state_events"
  Column   | Type | Collation | Nullable | Default 
-----------+------+-----------+----------+---------
 event_id  | text |           | not null | 
 room_id   | text |           | not null | 
 type      | text |           | not null | 
 state_key | text |           | not null | 
Indexes:
    "current_state_events_event_id_key" UNIQUE CONSTRAINT, btree (event_id)
    "current_state_events_room_id_type_state_key_key" UNIQUE CONSTRAINT, btree (room_id, type, state_key)
    "current_state_events_member_index" btree (state_key) WHERE type = 'm.room.member'::text
```

**Comment by richvdh** [comment]
@erikjohnston looks like the index is in place. Does this imply a corrupt database?

**Comment by richvdh** [comment]
@waylon531 if this is still a problem, it suggests the index on this database table is corrupt. See https://github.com/matrix-org/synapse/issues/6696#issuecomment-575280941 for a likely cause of it. Fixing it will require rebuilding the index: see https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md#fixing-incorrect-collate-or-ctype for some notes on what to do about it.
