### ISSUE TITLE
Room Creation inside Community Failed with 500

### ISSUE THREAD

**Issue by devilankur18** [matrix-org/synapse#5470]
### Description
When trying to create a new room inside synapse community. Its failing

### Steps to reproduce

- Create a new community
- Invite users
- Create a new Room inside the community

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
its giving 500 error. Here is the server log

```
2019-06-17 04:27:19,910 - synapse.access.http.8008 - 233 - INFO - OPTIONS-88202 - - - 8008 - Received request: OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat
2019-06-17 04:27:19,912 - synapse.access.http.8008 - 302 - INFO - OPTIONS-88202 - - - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3822.0 Safari/537.36" [0 dbevts]
2019-06-17 04:27:19,941 - synapse.access.http.8008 - 233 - INFO - OPTIONS-88203 - - - 8008 - Received request: OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat.example.com
2019-06-17 04:27:19,943 - synapse.access.http.8008 - 302 - INFO - OPTIONS-88203 - - - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat.example.com HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3822.0 Safari/537.36" [0 dbevts]
2019-06-17 04:27:19,952 - synapse.access.http.8008 - 233 - INFO - PUT-88204 - - - 8008 - Received request: PUT /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat
2019-06-17 04:27:19,985 - synapse.access.http.8008 - 233 - INFO - PUT-88205 - - - 8008 - Received request: PUT /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat.example.com
2019-06-17 04:27:20,003 - synapse.access.http.8008 - 302 - INFO - PUT-88204 - - - 8008 - {@admin:chat.example.com} Processed request: 0.050sec/0.001sec (0.003sec, 0.000sec) (0.005sec/0.041sec/4) 2B 200 "PUT /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3822.0 Safari/537.36" [0 dbevts]
2019-06-17 04:27:20,005 - synapse.metrics - 372 - INFO -  - Collecting gc 0
2019-06-17 04:27:20,019 - synapse.access.http.8008 - 302 - INFO - PUT-88205 - - - 8008 - {@admin:chat.example.com} Processed request: 0.034sec/0.001sec (0.002sec, 0.000sec) (0.017sec/0.014sec/4) 2B 200 "PUT /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/admin/rooms/!team1%3Achat.example.com HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3822.0 Safari/537.36" [0 dbevts]
2019-06-17 04:27:20,046 - synapse.access.http.8008 - 233 - INFO - OPTIONS-88206 - - - 8008 - Received request: OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/rooms
2019-06-17 04:27:20,048 - synapse.access.http.8008 - 302 - INFO - OPTIONS-88206 - - - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/rooms HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3822.0 Safari/537.36" [0 dbevts]
2019-06-17 04:27:20,088 - synapse.access.http.8008 - 233 - INFO - GET-88207 - - - 8008 - Received request: GET /_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/rooms

2019-06-17 04:27:20,101 - synapse.http.server - 112 - ERROR - GET-88207 - Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f0a44d09550 method='GET' uri='/_matrix/client/r0/groups/%2Bcompany-team%3Achat.example.com/rooms' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/storage/_base.py", line 527, in runWithConnection
    defer.returnValue(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/storage/_base.py", line 487, in runInteraction
    defer.returnValue(result)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/groups.py", line 355, in on_GET
    result = yield self.groups_handler.get_rooms_in_group(group_id, requester_user_id)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/synapse/groups/groups_server.py", line 547, in get_rooms_in_group
    room_id, len(joined_users), with_alias=False, allow_private=True,
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 401, in generate_room_entry
    result["m.federate"] = create_event.content.get("m.federate", True)
AttributeError: 'NoneType' object has no attribute 'content'
```



### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: 

If not matrix.org:

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: 
Synapse/0.99.5.2
- **Install method**: 
Docker Image
<!-- examples: package manager/git clone/pip  -->

- **Platform**: 
Docker Image: docker.io/matrixdotorg/synapse:v0.99.5.2
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
seems to be a dup of #4891
