### ISSUE TITLE
TypeError when creating configuration file

### ISSUE THREAD

**Issue by ErikasRaginis** [matrix-org/synapse#5472]
When running this command 
`python -m synapse.app.homeserver --server-name example.com --config-path homeserver.yaml --generate-config --report-stats=yes `
trying to create a configuration file (i did change example.com to my domain), i get this error:
```
/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/app/homeserver.py", line 52, in <module>
    from synapse.config.homeserver import HomeServerConfig
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/config/homeserver.py", line 37, in <module>
    from .server import ServerConfig
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/config/server.py", line 24, in <module>
    from synapse.http.endpoint import parse_and_validate_server_name
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/http/__init__.py", line 21, in <module>
    from twisted.web.client import FileBodyProducer
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/twisted/web/client.py", line 50, in <module>
    from twisted.web._newclient import _ensureValidURI, _ensureValidMethod
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/twisted/web/_newclient.py", line 592, in <module>
    b"\x61-\x7A",
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
(env)installer@opilionas:/usr/local/install/matrix-synapse/matrix-synapse-latest$ python -m synapse.app.homeserver --server-name sytes.net --config-path homeserver.yaml --generate-config --report-stats=yes
/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/app/homeserver.py", line 52, in <module>
    from synapse.config.homeserver import HomeServerConfig
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/config/homeserver.py", line 37, in <module>
    from .server import ServerConfig
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/config/server.py", line 24, in <module>
    from synapse.http.endpoint import parse_and_validate_server_name
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/synapse/http/__init__.py", line 21, in <module>
    from twisted.web.client import FileBodyProducer
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/twisted/web/client.py", line 50, in <module>
    from twisted.web._newclient import _ensureValidURI, _ensureValidMethod
  File "/usr/local/install/matrix-synapse/matrix-synapse-latest/env/lib/python3.4/site-packages/twisted/web/_newclient.py", line 592, in <module>
    b"\x61-\x7A",
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

**Comment by richvdh** [comment]
I'm afraid python 3.4 isn't supported.

**Comment by qovnika** [comment]
So what version of Python is supported then?

**Comment by neilisfragile** [comment]
@qovnika At the time of writing 3.5, 3.6, 3.7, these are the versions that we run against in CI.

**Comment by HighPriest** [comment]
Hey.
I have a similiar issue, where my server uses OpenSSL 1.0.2 patched by the freebsd initiative.
When I attempt to run the service, I get 
```
/usr/home/Vitex/apps/synapse/env/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py:179: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will completely remove support for it.
  utils.CryptographyDeprecationWarning,
error starting (exit code: 1); see above for logs
```

And in an hour of search, I didn't find any resolution :(
