### ISSUE TITLE
Synapse v1.0.0: Issue while trying to create the "homeserver.yaml" config file 

### ISSUE THREAD

**Issue by menturion** [matrix-org/synapse#5487]
Synapse v1.0.0

While trying to create the "homeserver.yaml" config file (according to the INSTALL.md) the following issue is reported:

```
Traceback (most recent call last):
  File "/opt/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 64, in <module>
    from synapse.rest import ClientRestResource
  File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/rest/__init__.py", line 32, in <module>
    from synapse.rest.client.v2_alpha import (
  File "/var/www/webroot/synapse/env/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/account.py", line 21, in <module>
    import jinja2
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by richvdh** [comment]
#5431

**Comment by menturion** [comment]
Thanks!
