### ISSUE TITLE
Consent broken on develop

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#5582]
From riot-web's end to end tests:
```
2019-06-30 18:27:03,267 - synapse.http.server - 177 - ERROR - GET-526 - Failed handle request <XForwardedForRequest at 0x7fbf0a8f6fd0 method='GET' uri='/_matrix/consent?h=f0691bd8ff7161edcd6f5349db69807dd600a49ddc5c5412b8201098dd8065e9&u=charly-4' clientproto='HTTP/1.1' site=5005>
Traceback (most recent call last):
  File "/workdir/matrix-react-end-to-end-tests/synapse/installations/consent/env/lib/python3.5/site-packages/synapse/http/server.py", line 142, in wrapped_request_handler
    return await h(self, request)
  File "/workdir/matrix-react-end-to-end-tests/synapse/installations/consent/env/lib/python3.5/site-packages/synapse/rest/consent/consent_resource.py", line 142, in _async_render_GET
    u = await self.store.get_user_by_id(qualified_user_id)
TypeError: object dict can't be used in 'await' expression
```

Log: https://buildkite.com/matrix-dot-org/matrix-react-sdk/builds/1360#0ec3ad58-40f7-40fa-abb9-36613530047f

**Comment by richvdh** [comment]
Guessing this has been introduced by #5475
