### ISSUE TITLE
Synapse fails to start after upgrade to 1.1.0

### ISSUE THREAD

**Issue by Delurkdotcom** [matrix-org/synapse#5652]
Hi,

First, my setup is a prebuilt packages on Debian 9. I upgrade my synapse server from 0.99 to 1.1.0 and it doesn't start with this error :

2019-07-10 11:30:45,071 - root - 225 - WARNING - None- ***** STARTING SERVER *****
2019-07-10 11:30:45,075 - root - 226 - WARNING - None- Server /opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py version 1.1.0
2019-07-10 11:30:45,076 - twisted - 253 - ERROR - - Traceback (most recent call last):
2019-07-10 11:30:45,077 - twisted - 253 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
2019-07-10 11:30:45,077 - twisted - 253 - ERROR - -     "__main__", mod_spec)
2019-07-10 11:30:45,077 - twisted - 253 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
2019-07-10 11:30:45,078 - twisted - 253 - ERROR - -     exec(code, run_globals)
2019-07-10 11:30:45,078 - twisted - 253 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 658, in <module>
2019-07-10 11:30:45,079 - twisted - 253 - ERROR - -     main()
2019-07-10 11:30:45,079 - twisted - 253 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 653, in main
2019-07-10 11:30:45,079 - twisted - 253 - ERROR - -     hs = setup(sys.argv[1:])
2019-07-10 11:30:45,080 - twisted - 253 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 349, in setup
2019-07-10 11:30:45,080 - twisted - 253 - ERROR - -     database_engine = create_engine(config.database_config)
2019-07-10 11:30:45,080 - twisted - 253 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/engines/__init__.py", line 34, in create_engine
2019-07-10 11:30:45,081 - twisted - 253 - ERROR - -     module = importlib.import_module(name)
2019-07-10 11:30:45,081 - twisted - 253 - ERROR - -   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
2019-07-10 11:30:45,081 - twisted - 253 - ERROR - -     return _bootstrap._gcd_import(name[level:], package, level)
2019-07-10 11:30:45,082 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
2019-07-10 11:30:45,082 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
2019-07-10 11:30:45,082 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
2019-07-10 11:30:45,083 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2019-07-10 11:30:45,083 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
2019-07-10 11:30:45,083 - twisted - 253 - ERROR - -   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-07-10 11:30:45,084 - twisted - 253 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/psycopg2/__init__.py", line 50, in <module>
2019-07-10 11:30:45,084 - twisted - 253 - ERROR - -     from psycopg2._psycopg import (                     # noqa
2019-07-10 11:30:45,084 - twisted - 253 - ERROR - - ImportError: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by richvdh** [comment]
you will need the postgres library (`libpq5`) if you want to use postgres

**Comment by Delurkdotcom** [comment]
Thanks. It works.
