### ISSUE TITLE
Synapse server cannot reach remote servers

### ISSUE THREAD

**Issue by Inlinebool** [matrix-org/synapse#5662]
### Description

When trying to get public room list from other home servers (e.g. `matrix.org`). Riot says `Riot failed to get the public room list. Internal server error`, and the server log shows
```
2019-07-11 00:29:28,691 - synapse.access.http.8008 - 233 - INFO - OPTIONS-197 - 12.34.56.78 - 8008 - Received request: OPTIONS /_matrix/client/r0/publicRooms?server=matrix.org
2019-07-11 00:29:28,693 - synapse.access.http.8008 - 302 - INFO - OPTIONS-197 - 12.34.56.78 - 8008 - {None} Processed request: 0.002sec/0.001sec (0.002sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/publicRooms?server=matrix.org HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.2.3 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
2019-07-11 00:29:28,859 - synapse.access.http.8008 - 233 - INFO - POST-198 - 12.34.56.78 - 8008 - Received request: POST /_matrix/client/r0/publicRooms?server=matrix.org
2019-07-11 00:29:28,861 - synapse.util.caches.response_cache - 148 - INFO - POST-198 - [remote_room_list]: no cached result for [('matrix.org', 20, None, True, None)], calculating new one
2019-07-11 00:29:28,868 - synapse.http.matrixfederationclient - 387 - INFO - POST-198 - {GET-O-10} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20; timeout 60.000000s
2019-07-11 00:29:28,873 - synapse.http.matrixfederationclient - 411 - INFO - POST-198 - Failed to send request: [Errno 101] Network is unreachable
2019-07-11 00:29:28,873 - synapse.http.matrixfederationclient - 464 - WARNING - POST-198 - {GET-O-10} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: OSError(101, 'Network is unreachable')
2019-07-11 00:29:29,373 - synapse.http.matrixfederationclient - 387 - INFO - POST-198 - {GET-O-10} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20; timeout 60.000000s
2019-07-11 00:29:29,377 - synapse.http.matrixfederationclient - 411 - INFO - POST-198 - Failed to send request: [Errno 101] Network is unreachable
2019-07-11 00:29:29,378 - synapse.http.matrixfederationclient - 464 - WARNING - POST-198 - {GET-O-10} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: OSError(101, 'Network is unreachable')
2019-07-11 00:29:29,414 - synapse.handlers.typing - 86 - INFO -  - Checking for typing timeouts
2019-07-11 00:29:29,417 - synapse.handlers.presence - 336 - INFO - handle_presence_timeouts-364 - Handling presence timeouts
2019-07-11 00:29:30,684 - synapse.http.matrixfederationclient - 387 - INFO - POST-198 - {GET-O-10} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20; timeout 60.000000s
2019-07-11 00:29:30,688 - synapse.http.matrixfederationclient - 411 - INFO - POST-198 - Failed to send request: [Errno 101] Network is unreachable
2019-07-11 00:29:30,689 - synapse.http.matrixfederationclient - 464 - WARNING - POST-198 - {GET-O-10} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: OSError(101, 'Network is unreachable')
2019-07-11 00:29:32,630 - synapse.http.matrixfederationclient - 387 - INFO - POST-198 - {GET-O-10} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20; timeout 60.000000s
2019-07-11 00:29:32,633 - synapse.http.matrixfederationclient - 411 - INFO - POST-198 - Failed to send request: [Errno 101] Network is unreachable
2019-07-11 00:29:32,634 - synapse.http.matrixfederationclient - 464 - WARNING - POST-198 - {GET-O-10} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=true&limit=20: OSError(101, 'Network is unreachable')
2019-07-11 00:29:32,636 - synapse.http.server - 108 - ERROR - POST-198 - Failed handle request via 'PublicRoomListRestServlet': <XForwardedForRequest at 0x7fa52455d358 method='POST' uri='/_matrix/client/r0/publicRooms?server=matrix.org' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/util/__init__.py", line 52, in sleep
    defer.returnValue(res)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: 1.3032461707343603

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 407, in _send_request
    response = yield request_deferred
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/server.py", line 76, in wrapped_request_handler
    await h(self, request)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/server.py", line 301, in _async_render
    callback_return = await callback_return
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 375, in on_POST
    third_party_instance_id=third_party_instance_id,
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/handlers/room_list.py", line 498, in get_remote_public_room_list
    third_party_instance_id=third_party_instance_id,
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 339, in get_public_rooms
    destination=remote_server, path=path, args=args, ignore_backoff=True
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 754, in get_json
    timeout=timeout,
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 240, in _send_request_with_optional_trailing_slash
    response = yield self._send_request(request, **send_request_args)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/jkr/synapse/env/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 412, in _send_request
    raise_from(RequestSendFailed(e, can_retry=True), e)
  File "<string>", line 3, in raise_from
synapse.api.errors.RequestSendFailed: Failed to send request: OSError: [Errno 101] Network is unreachable
2019-07-11 00:29:32,640 - synapse.access.http.8008 - 302 - INFO - POST-198 - 12.34.56.78 - 8008 - {@jkr:jiangkairong.me} Processed request: 3.780sec/0.001sec (0.032sec, 0.000sec) (0.001sec/0.002sec/1) 55B 500 "POST /_matrix/client/r0/publicRooms?server=matrix.org HTTP/1.0" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.2.3 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
```

When trying to list public rooms on my home server from an account on `matrix.org`, the log on my server shows
```
2019-07-11 00:37:08,568 - synapse.access.http.8008 - 233 - INFO - GET-243 - 94.237.61.93 - 8008 - Received request: GET /_matrix/federation/v1/publicRooms?include_all_networks=false&limit=20
2019-07-11 00:37:08,571 - synapse.crypto.keyring - 651 - INFO - GET-243 - Requesting keys dict_items([('matrix.org', {'ed25519:auto': 1562805428570})]) from notary server matrix.org
2019-07-11 00:37:08,579 - synapse.crypto.keyring - 603 - WARNING - GET-243 - Key lookup failed from 'matrix.org': Failed to connect to remote server
2019-07-11 00:37:08,582 - synapse.http.matrixfederationclient - 387 - INFO - GET-243 - {GET-O-12} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/key/v2/server/ed25519%3Aauto; timeout 10.000000s
2019-07-11 00:37:08,587 - synapse.http.matrixfederationclient - 411 - INFO - GET-243 - Failed to send request: [Errno 101] Network is unreachable
2019-07-11 00:37:08,588 - synapse.http.matrixfederationclient - 464 - WARNING - GET-243 - {GET-O-12} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/key/v2/server/ed25519%3Aauto: OSError(101, 'Network is unreachable')
2019-07-11 00:37:08,589 - synapse.crypto.keyring - 782 - WARNING - GET-243 - Error looking up keys {'ed25519:auto': 1562805428570} from matrix.org: Failed to connect to remote server
2019-07-11 00:37:08,590 - synapse.federation.transport.server - 288 - WARNING - GET-243 - authenticate_request failed: 401: No key for matrix.org with ids in ['ed25519:auto'] (min_validity 1562805428570)
2019-07-11 00:37:08,591 - synapse.http.server - 79 - INFO - GET-243 - <XForwardedForRequest at 0x7fa5242d80f0 method='GET' uri='/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=20' clientproto='HTTP/1.0' site=8008> SynapseError: 401 - No key for matrix.org with ids in ['ed25519:auto'] (min_validity 1562805428570)
2019-07-11 00:37:08,594 - synapse.access.http.8008 - 302 - INFO - GET-243 - 94.237.61.93 - 8008 - {None} Processed request: 0.024sec/0.001sec (0.018sec, 0.000sec) (0.002sec/0.003sec/1) 118B 401 "GET /_matrix/federation/v1/publicRooms?include_all_networks=false&limit=20 HTTP/1.0" "Synapse/1.1.0rc1 (b=matrix-org-hotfixes,43e01be15)" [0 dbevts]
```

I also tried other public home servers like `perthchat.org` and got the same result.

Sending stickers is also failing and the log shows
```
2019-07-11 00:42:53,737 - synapse.access.http.8008 - 233 - INFO - GET-315 - 66.194.253.20 - 8008 - Received request: GET /_matrix/media/v1/download/matrix.org/DIxxSqyaDnRBCqQghgUBLPaI
2019-07-11 00:42:53,742 - synapse.rest.media.v1.media_repository - 388 - WARNING - GET-315 - Not retrying destination 'matrix.org'
2019-07-11 00:42:53,743 - synapse.http.server - 79 - INFO - GET-315 - <XForwardedForRequest at 0x7fa52a4ba438 method='GET' uri='/_matrix/media/v1/download/matrix.org/DIxxSqyaDnRBCqQghgUBLPaI' clientproto='HTTP/1.0' site=8008> SynapseError: 502 - Failed to fetch remote media
2019-07-11 00:42:53,746 - synapse.access.http.8008 - 302 - INFO - GET-315 - 66.194.253.20 - 8008 - {None} Processed request: 0.008sec/0.001sec (0.006sec, 0.000sec) (0.001sec/0.002sec/1) 62B 502 "GET /_matrix/media/v1/download/matrix.org/DIxxSqyaDnRBCqQghgUBLPaI HTTP/1.0" "Dalvik/2.1.0 (Linux; U; Android 9; Pixel 2 XL Build/PQ3A.190705.001)" [0 dbevts]
```

I can ping `matrix.org` from my server. 

Messaging within the home server is functioning well, and I have tried https://matrix.org/federationtester with my domain and it returns successful on everything.

I posted this on #synapse:matrix.org but got little response, and the problem is still there.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: jiangkairong.me

<!--
What version of Synapse is running?
You can find the Synapse version by inspecting the server headers (replace matrix.org with
your own homeserver domain):
$ curl -v https://matrix.org/_matrix/client/versions 2>&1 | grep "Server:"
-->
- **Version**: synapse 1.1.0

- **Install method**: pip
<!-- examples: package manager/git clone/pip  -->

- **Platform**: ubuntu 18.04
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
It's annoying that the stack traces and errors are so opaque, but I think this is due to a failure to contact your nameservers. Check the servers listed in `/etc/resolv.conf`, and check that they are reachable on TCP port 53.

**Comment by Inlinebool** [comment]
My `/etc/resov.conf` says
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 2001:19f0:300:1704::6
nameserver 127.0.0.53
```

By running `systemd-resolve --status` I have
```
Global
         DNS Servers: 108.61.10.10
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 2 (eth0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
```

I can reach to TCP 53 port on 108.61.10.10 with
```
jkr@vultr:~/synapse$ nc -zv 108.61.10.10 53
Connection to 108.61.10.10 53 port [tcp/domain] succeeded!
```


Also, I can resolve domain name of `matrix.org` with `nslookup`.
```
jkr@vultr:~/synapse$ nslookup matrix.org
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	matrix.org
Address: 104.20.20.236
Name:	matrix.org
Address: 104.20.21.236
Name:	matrix.org
Address: 2606:4700:10::6814:14ec
Name:	matrix.org
Address: 2606:4700:10::6814:15ec
```

However with more digging I found out that this is a [`twisted` bug](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320). I was able to solve it using the solution mentioned in the link.

Thanks for the help.

**Comment by nordurljosahvida** [comment]
@Inlinebool can I ask you what the solution *from the link* that you applied is? Thanks

**Comment by MayeulC** [comment]
@nordurljosahvida probably [that one](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320/comments/8) but I guess you figured this out already?
