### ISSUE TITLE
Failed to handle PDU - could not find event

### ISSUE THREAD

**Issue by waylon531** [matrix-org/synapse#5681]
### Description

My logs are full of an error about being unable to handle a PDU. This error happens every few minutes, and it's always about the same event.

```
2019-07-13 20:49:17,289 - synapse.federation.federation_server - 252 - ERROR - PUT-3012-$15630331035606281nobdT:matrix.org - Failed to handle PDU $15630331035606281nobdT:matrix.org
Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events_worker.py", line 476, in _enqueue_events
    defer.returnValue({e.event.event_id: e for e in res if e})
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events_worker.py", line 320, in get_events_as_list
    defer.returnValue(events)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1362, in returnValue
    raise _DefGen_Return(val)
twisted.internet.defer._DefGen_Return: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 241, in process_pdus_for_room
    yield self._handle_received_pdu(origin, pdu)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 667, in _handle_received_pdu
    yield self.handler.on_receive_pdu(origin, pdu, sent_to_us_directly=True)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 249, in on_receive_pdu
    origin, pdu, prevs, min_depth
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 537, in _get_missing_events_for_pdu
    yield self.on_receive_pdu(origin, ev, sent_to_us_directly=False)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 415, in on_receive_pdu
    origin, pdu, state=state, auth_chain=auth_chain
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 595, in _process_received_pdu
    context = yield self._handle_new_event(origin, event, state=state)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/handlers/federation.py", line 1604, in _handle_new_event
    event, context
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/push/action_generator.py", line 43, in handle_push_actions_for_event
    yield self.bulk_evaluator.action_for_event_by_user(event, context)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/push/bulk_push_rule_evaluator.py", line 153, in action_for_event_by_user
    yield self._get_power_levels_and_sender_level(event, context)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/push/bulk_push_rule_evaluator.py", line 124, in _get_power_levels_and_sender_level
    pl_event = yield self.store.get_event(pl_event_id)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env3/lib/python3.6/site-packages/synapse/storage/events_worker.py", line 157, in get_event
    raise NotFoundError("Could not find event %s" % (event_id,))
```

The event in question is an `m.room.power_levels` event. The event took place in `#haskell:matrix.org`. I believe I left this room a couple of months ago, and I suspect this event is from around that time. This room is Hotel California'd for me right now, I'm not actually in the room anymore but it still shows up in my client and is unleavable. I suspect this problem may have been caused when I left the channel, but I have no way of actually confirming this.

### Version information

- **Homeserver**: riot.firechicken.net

If not matrix.org:

- **Version**: 1.1.0

- **Install method**: pip

- **Platform**: CentOS

**Comment by waylon531** [comment]
When I try to leave the room I get this error:
```
{
    "errcode": "M_UNRECOGNIZED",
    "error": "Unrecognized request"
}
```

and when I try to join I get this error:
```
{
    "errcode": "M_UNKNOWN",
    "error": "No known servers"
}
```

**Comment by waylon531** [comment]
It appears that the `curl` command to join the room may have partially worked, my server is now accepting events for that room and I'm no longer getting errors about not being able to find events. I'll report back if it breaks again. The room is still broken in my client, but I can at least federate with matrix.org without getting rate-limited now.

**Comment by richvdh** [comment]
Is this still a problem?

**Comment by waylon531** [comment]
It's probably safe to close this issue now, rejoining that room fixed the temporary issue I was having. I just checked to see if the room was still Hotel California'd for me but it appears that I actually successfully left it at some point, everything is good now
