### ISSUE TITLE
After migrating to new Server log says: Cannot use this database as it is too new

### ISSUE THREAD

**Issue by cavemanr** [matrix-org/synapse#5708]
Hey there,

after I migrated to a new server (Ubuntu 18.04.01 with Postgres 10.9) the server won't start.
I've installed matrix-synapse via apt, so I use the prebuild ubuntu packages.

```
Jul 17 20:21:58 ServerName systemd[1]: Started Synapse Matrix homeserver.
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals
File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 449, in <module> main()
File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 444, in main hs = setup(sys.argv[1:])
File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 305, in setup 
File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 62, in prepare_database cur, user_version, delta_files, upgraded, database_engine, config
File "/usr/lib/python2.7/dist-packages/synapse/storage/prepare_database.py", line 202, in _upgrade_existing_database "new for the server to understand"
ValueError: Cannot use this database as it is too new for the server to understand
Main process exited, code=exited, status=1/FAILURE
Failed with result 'exit-code'.
```
Is there an script which can help me to fix his problem?

Regards

Robert

**Comment by aaronraimist** [comment]
What version of Synapse were you using before and what version is installed on the new server?

You probably need to install the latest version of Synapse from the matrix.org repo as described here: https://github.com/matrix-org/synapse/blob/master/INSTALL.md

**Comment by richvdh** [comment]
yup, don't use the matrix packages from ubuntu; they are ancient.

**Comment by nmattela** [comment]
I'm facing the same error. My Kubernetes cluster crashed and I managed to recover my postgres database and synapse configs, but I didn't keep track of the synapse version I was using. Is there any way to figure this information out from the database/synapse content?

I know my Postgres version. It was 10. So I do wonder whether the error refers to the synapse of the postgres version...
