### ISSUE TITLE
[matrix.org] Got response headers: 401 Unauthorized — Failure to create room. Server may be unavailable, overloaded, or you hit a bug

### ISSUE THREAD

**Issue by adrianolucas** [matrix-org/synapse#5820]
I've followed [this howto](https://www.howtoforge.com/tutorial/how-to-install-matrix-synapse-on-ubuntu-1804/) to set up my self-hosted Matrix/Synapse server. It is proxied through ports 80/443 (with default 8008/8443 ports) via Apache. It basically works fine. This is the homeserver config:

    pid_file: "/var/run/matrix-synapse.pid"
    public_baseurl: https://matrix.server.com/
    use_presence: false
    require_auth_for_profile_requests: true
    allow_public_rooms_without_auth: false
    allow_public_rooms_over_federation: false
    default_room_version: "5"
    filter_timeline_limit: 5000
    block_non_admin_invites: true
    federation_ip_range_blacklist:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '100.64.0.0/10'
      - '169.254.0.0/16'
      - '::1/128'
      - 'fe80::/64'
      - 'fc00::/7'
    listeners:
      - port: 8448
        type: http
        tls: true
        bind_addresses: ['::1', '127.0.0.1']
        resources:
          - names: [client, federation]
      - port: 8008
        tls: false
        bind_addresses: ['::1', '127.0.0.1']
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false
    tls_certificate_path: "/etc/matrix-synapse/fullchain.pem"
    tls_private_key_path: "/etc/matrix-synapse/privkey.pem"
    acme:
        account_key_file: /var/lib/matrix-synapse/acme_account.key
    database:
      name: "sqlite3"
      args:
        database: "/var/lib/matrix-synapse/homeserver.db"
    log_config: "/etc/matrix-synapse/log.yaml"
    media_store_path: "/var/lib/matrix-synapse/media"
    uploads_path: "/var/lib/matrix-synapse/uploads"
    max_upload_size: 100M
    max_image_pixels: 32M
    enable_registration: false
    allow_guest_access: false
    default_identity_server: https://matrix.org
    signing_key_path: "/etc/matrix-synapse/homeserver.signing.key"
    password_config:

The Apache proxy config:

    80:
    ProxyPass / https://127.0.0.1:8008/
    ProxyPassReverse / https://127.0.0.1:8008/

    443:
    ProxyPass / https://127.0.0.1:8448/
    ProxyPassReverse / https://127.0.0.1:8448/

It runs well. Local users can be created and conversations run fine.

The config was tested with [https://fed.mau.dev/](https://fed.mau.dev/), but since it's proxied, it fails as 8008/8443 aren't reachable. Same with [https://federationtester.matrix.org](https://federationtester.matrix.org).

The issue is when trying to communicate/create a room with a user at `:matrix.org`, it fails with ` [matrix.org] Got response headers: 401 Unauthorized`, as well as `Failed to get profile information for @matrix.user:matrix.org: 401: No key for matrix.server.com with ids ...`. I'm not sure which error is causing the request to fail. The actual error from Riot.im is: "Failure to create room. Server may be unavailable, overloaded, or you hit a bug."

This the relevant log for this part:

    2019-08-04 11:16:37,834 - synapse.access.https.8448 - 233 - INFO - OPTIONS-44- 127.0.0.1 - 8448 - Received request: OPTIONS /_matrix/client/r0/createRoom
    2019-08-04 11:16:37,836 - synapse.access.https.8448 - 302 - INFO - OPTIONS-44- 127.0.0.1 - 8448 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/createRoom HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,011 - synapse.access.https.8448 - 233 - INFO - POST-45- 127.0.0.1 - 8448 - Received request: POST /_matrix/client/r0/createRoom
    2019-08-04 11:16:38,015 - synapse.metrics - 451 - INFO - - Collecting gc 1
    2019-08-04 11:16:38,018 - synapse.handlers.room - 700 - INFO - POST-45- Sending m.room.create in new room
    2019-08-04 11:16:38,030 - synapse.storage.events - 475 - INFO - persist_events-0- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,044 - synapse.handlers.room - 714 - INFO - POST-45- Sending m.room.member in new room
    2019-08-04 11:16:38,047 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-1- Handling 1 state deltas
    2019-08-04 11:16:38,048 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-1- Handling 1 state deltas
    2019-08-04 11:16:38,112 - synapse.storage.events - 475 - INFO - persist_events-1- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,122 - synapse.handlers.sync - 925 - INFO - GET-41- Calculating sync response for @myuser:matrix.server.com between StreamToken(room_key='s193', presence_key='509', typing_key='0', receipt_key='73', account_data_key='1', push_rules_key='12', to_device_key='1', device_list_key='16', groups_key='1') and StreamToken(room_key='s195', presence_key=509, typing_key=0, receipt_key=73, account_data_key=1, push_rules_key=12, to_device_key=1, device_list_key=16, groups_key=1)
    2019-08-04 11:16:38,124 - synapse.handlers.room - 700 - INFO - POST-45- Sending m.room.power_levels in new room
    2019-08-04 11:16:38,127 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-2- Handling 1 state deltas
    2019-08-04 11:16:38,129 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-2- Handling 1 state deltas
    2019-08-04 11:16:38,144 - synapse.handlers.sync - 1467 - INFO - GET-41- Membership changes in !JmazLauIpKMjCwKLXK:matrix.server.com: [$UGyrBdx-WVO1zZGS9Iq-tUzwuqjkS6ZDYfQJ5lZn_Ww (join)]
    2019-08-04 11:16:38,150 - synapse.metrics - 451 - INFO - - Collecting gc 1
    2019-08-04 11:16:38,164 - synapse.storage.events - 475 - INFO - persist_events-2- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,176 - synapse.handlers.room - 700 - INFO - POST-45- Sending m.room.join_rules in new room
    2019-08-04 11:16:38,179 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-3- Handling 1 state deltas
    2019-08-04 11:16:38,180 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-3- Handling 1 state deltas
    2019-08-04 11:16:38,199 - synapse.access.https.8448 - 302 - INFO - GET-41- 127.0.0.1 - 8448 - {@myuser:matrix.server.com} Processed request: 16.572sec/0.001sec (0.008sec, 0.001sec) (0.050sec/0.012sec/13) 1563B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s193_509_0_73_1_12_1_16_1 HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,208 - synapse.storage.events - 475 - INFO - persist_events-3- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,217 - synapse.handlers.room - 700 - INFO - POST-45- Sending m.room.history_visibility in new room
    2019-08-04 11:16:38,219 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-4- Handling 1 state deltas
    2019-08-04 11:16:38,221 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-4- Handling 1 state deltas
    2019-08-04 11:16:38,244 - synapse.storage.events - 475 - INFO - persist_events-4- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,253 - synapse.handlers.room - 700 - INFO - POST-45- Sending m.room.guest_access in new room
    2019-08-04 11:16:38,255 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-5- Handling 1 state deltas
    2019-08-04 11:16:38,256 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-5- Handling 1 state deltas
    2019-08-04 11:16:38,280 - synapse.storage.events - 475 - INFO - persist_events-5- Calculating state delta for room !JmazLauIpKMjCwKLXK:matrix.server.com
    2019-08-04 11:16:38,290 - synapse.handlers.user_directory - 145 - INFO - user_directory.notify_new_event-6- Handling 1 state deltas
    2019-08-04 11:16:38,291 - synapse.handlers.stats - 98 - INFO - stats.notify_new_event-6- Handling 1 state deltas
    2019-08-04 11:16:38,305 - synapse.http.matrixfederationclient - 404 - INFO - POST-45- {GET-O-1} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40matrix.user%3Amatrix.org&field=displayname; timeout 10.000000s
    2019-08-04 11:16:38,305 - synapse.http.federation.matrix_federation_agent - 335 - INFO - POST-45- Fetching https://matrix.org/.well-known/matrix/server
    2019-08-04 11:16:38,320 - synapse.handlers.typing - 86 - INFO - - Checking for typing timeouts
    2019-08-04 11:16:38,321 - synapse.handlers.presence - 336 - INFO - handle_presence_timeouts-9- Handling presence timeouts
    2019-08-04 11:16:38,322 - synapse.metrics - 451 - INFO - - Collecting gc 1
    2019-08-04 11:16:38,324 - synapse.metrics - 451 - INFO - - Collecting gc 2
    2019-08-04 11:16:38,395 - synapse.storage.TIME - 377 - INFO - - Total database time: 2.244% {persist_events(6): 0.375%, update_room_state(3): 0.337%, get_all_new_events_stream(12): 0.176%}
    2019-08-04 11:16:38,396 - synapse.access.https.8448 - 233 - INFO - OPTIONS-46- 127.0.0.1 - 8448 - Received request: OPTIONS /_matrix/client/r0/keys/query
    2019-08-04 11:16:38,397 - synapse.access.https.8448 - 302 - INFO - OPTIONS-46- 127.0.0.1 - 8448 - {None} Processed request: 0.001sec/0.000sec (0.001sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/keys/query HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,453 - synapse.http.federation.matrix_federation_agent - 351 - INFO - POST-45- Error fetching https://matrix.org/.well-known/matrix/server: Non-200 response 404
    2019-08-04 11:16:38,454 - twisted - 254 - INFO - POST-45- b'/etc/resolv.conf' changed, reparsing
    2019-08-04 11:16:38,454 - twisted - 254 - INFO - POST-45- Resolver added ('127.0.0.53', 53) to server list
    2019-08-04 11:16:38,459 - synapse.http.federation.matrix_federation_agent - 385 - INFO - POST-45- Connecting to matrix.org.cdn.cloudflare.net:8443
    2019-08-04 11:16:38,591 - synapse.access.https.8448 - 233 - INFO - OPTIONS-47- 127.0.0.1 - 8448 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s195_509_0_73_1_12_1_16_1
    2019-08-04 11:16:38,592 - synapse.access.https.8448 - 302 - INFO - OPTIONS-47- 127.0.0.1 - 8448 - {None} Processed request: 0.001sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s195_509_0_73_1_12_1_16_1 HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,722 - synapse.access.https.8448 - 233 - INFO - POST-48- 127.0.0.1 - 8448 - Received request: POST /_matrix/client/r0/keys/query
    2019-08-04 11:16:38,726 - synapse.access.https.8448 - 302 - INFO - POST-48- 127.0.0.1 - 8448 - {@myuser:matrix.server.com} Processed request: 0.003sec/0.000sec (0.001sec, 0.000sec) (0.001sec/0.001sec/1) 1067B 200 "POST /_matrix/client/r0/keys/query HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,762 - synapse.access.https.8448 - 233 - INFO - GET-49- 127.0.0.1 - 8448 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s195_509_0_73_1_12_1_16_1
    2019-08-04 11:16:38,763 - synapse.util.caches.response_cache - 148 - INFO - GET-49- [sync]: no cached result for [(@myuser:matrix.server.com, 30000, 's195_509_0_73_1_12_1_16_1', '0', False, 'LSRQDRYODX')], calculating new one
    2019-08-04 11:16:38,764 - synapse.handlers.sync - 925 - INFO - GET-49- Calculating sync response for @myuser:matrix.server.com between StreamToken(room_key='s195', presence_key='509', typing_key='0', receipt_key='73', account_data_key='1', push_rules_key='12', to_device_key='1', device_list_key='16', groups_key='1') and StreamToken(room_key='s199', presence_key=509, typing_key=0, receipt_key=73, account_data_key=1, push_rules_key=12, to_device_key=1, device_list_key=16, groups_key=1)
    2019-08-04 11:16:38,771 - synapse.access.https.8448 - 302 - INFO - GET-49- 127.0.0.1 - 8448 - {@myuser:matrix.server.com} Processed request: 0.009sec/0.000sec (0.000sec, 0.000sec) (0.001sec/0.001sec/2) 1881B 200 "GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s195_509_0_73_1_12_1_16_1 HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:38,954 - synapse.access.https.8448 - 233 - INFO - OPTIONS-50- 127.0.0.1 - 8448 - Received request: OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s199_509_0_73_1_12_1_16_1
    2019-08-04 11:16:38,955 - synapse.access.https.8448 - 302 - INFO - OPTIONS-50- 127.0.0.1 - 8448 - {None} Processed request: 0.001sec/0.000sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "OPTIONS /_matrix/client/r0/sync?filter=0&timeout=30000&since=s199_509_0_73_1_12_1_16_1 HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.3.0 Chrome/69.0.3497.128 Electron/4.2.6 Safari/537.36" [0 dbevts]
    2019-08-04 11:16:39,114 - synapse.access.https.8448 - 233 - INFO - GET-51- 127.0.0.1 - 8448 - Received request: GET /_matrix/client/r0/sync?filter=0&timeout=30000&since=s199_509_0_73_1_12_1_16_1
    2019-08-04 11:16:39,116 - synapse.util.caches.response_cache - 148 - INFO - GET-51- [sync]: no cached result for [(@myuser:matrix.server.com, 30000, 's199_509_0_73_1_12_1_16_1', '0', False, 'LSRQDRYODX')], calculating new one
    2019-08-04 11:16:39,627 - synapse.http.matrixfederationclient - 436 - INFO - POST-45- {GET-O-1} [matrix.org] Got response headers: 401 Unauthorized
    2019-08-04 11:16:39,627 - synapse.http.matrixfederationclient - 520 - WARNING - POST-45- {GET-O-1} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40matrix.user%3Amatrix.org&field=displayname: HttpResponseException("401: b'Unauthorized'",)
    2019-08-04 11:16:39,628 - synapse.handlers.message - 350 - INFO - POST-45- Failed to get profile information for @matrix.user:matrix.org: 401: No key for matrix.server.com with ids in ['ed25519:a_hYDB'] (min_validity 1564910198505)
    2019-08-04 11:16:39,640 - synapse.http.matrixfederationclient - 404 - INFO - POST-45- {PUT-O-2} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21JmazLauIpKMjCwKLXK%3Amatrix.server.com/%24dROA6O6mcKLBt6ZZwnCR4x0cTNqLDgRIWzMmoefqL1g; timeout 60.000000s
    2019-08-04 11:16:43,316 - synapse.handlers.typing - 86 - INFO - - Checking for typing timeouts
    2019-08-04 11:16:43,316 - synapse.handlers.presence - 336 - INFO - handle_presence_timeouts-10- Handling presence timeouts
    2019-08-04 11:16:43,729 - synapse.http.matrixfederationclient - 436 - INFO - POST-45- {PUT-O-2} [matrix.org] Got response headers: 401 Unauthorized
    2019-08-04 11:16:43,730 - synapse.http.matrixfederationclient - 520 - WARNING - POST-45- {PUT-O-2} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21JmazLauIpKMjCwKLXK%3Amatrix.server.com/%24dROA6O6mcKLBt6ZZwnCR4x0cTNqLDgRIWzMmoefqL1g: HttpResponseException("401: b'Unauthorized'",)
    2019-08-04 11:16:43,732 - synapse.http.server - 108 - ERROR - POST-45- Failed handle request via 'RoomCreateRestServlet': <SynapseRequest at 0x7fee3a7b7a58 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.1' site=8448>
    Traceback (most recent call last):
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 76, in wrapped_request_handler
        await h(self, request)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 315, in _async_render
        callback_return = await callback_return
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v1/room.py", line 91, in on_POST
        requester, self.get_room_config(request)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room.py", line 651, in create_room
        content=content,
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 303, in update_membership
        require_consent=require_consent,
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 509, in _update_membership
        require_consent=require_consent,
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/room_member.py", line 197, in _local_membership_update
        requester, event, context, extra_users=[target], ratelimit=ratelimit
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/metrics.py", line 69, in measured_func
        r = yield func(self, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/message.py", line 701, in handle_new_client_event
        requester, event, context, ratelimit=ratelimit, extra_users=extra_users
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/message.py", line 779, in persist_and_notify_client_event
        invitee.domain, event
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/federation.py", line 1082, in send_invite
        pdu=event,
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 745, in send_invite
        content = yield self._do_send_invite(destination, pdu, room_version)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 786, in _do_send_invite
        "invite_room_state": pdu.unsigned.get("invite_room_state", []),
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/federation/transport/client.py", line 310, in send_invite_v2
        destination=destination, path=path, data=content, ignore_backoff=True
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 640, in put_json
        timeout=timeout,
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 241, in _send_request_with_optional_trailing_slash
        response = yield self._send_request(request, **send_request_args)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
      File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/matrixfederationclient.py", line 475, in _send_request
        raise e
    synapse.api.errors.HttpResponseException: 401: b'Unauthorized'

Apologies for the length of this post, but I'm new to this.

**Comment by GovanifY** [comment]
Hey,
As a matter of fact I tried to set up yesterday my own synapse server and ran into the same issues.
On my side though the federation tester works just fine(try [it](https://federationtester.matrix.org/) with govanify.com and you'll see)

Relevant logs:
```
2019-08-04 14:46:38,346 - synapse.util.caches.response_cache - 148 - INFO - GET-213 - [sync]: no cached result for [(@govanify:govanify.com, 30000, 's13_29_0_1_3_1_1_6_1', '0', False, 'QMGNWJUGAJ')], calculating new one
2019-08-04 14:46:38,541 - synapse.http.matrixfederationclient - 436 - INFO - POST-205 - {GET-O-4} [matrix.org] Got response headers: 401 Unauthorized
2019-08-04 14:46:38,542 - synapse.http.matrixfederationclient - 520 - WARNING - POST-205 - {GET-O-4} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40govanify%3Amatrix.org&field=displayname: HttpResponseException("401: b'Unauthorized'",)
2019-08-04 14:46:38,544 - synapse.handlers.message - 350 - INFO - POST-205 - Failed to get profile information for @govanify:matrix.org: 401: No key for govanify.com with ids in ['ed25519:a_dQmo'] (min_validity 1564926398971)
2019-08-04 14:46:38,552 - synapse.metrics - 451 - INFO -  - Collecting gc 1
2019-08-04 14:46:38,575 - synapse.http.matrixfederationclient - 404 - INFO - POST-205 - {PUT-O-5} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21jDwYqnpldLoJLEFQvF%3Agovanify.com/%24OL7YN5JbASwMv6G1StrbB7Jg08CEC82-Ry3f0q-9VYI; timeout 60.000000s
2019-08-04 14:46:38,661 - synapse.handlers.typing - 86 - INFO -  - Checking for typing timeouts
2019-08-04 14:46:38,662 - synapse.handlers.presence - 336 - INFO - handle_presence_timeouts-326 - Handling presence timeouts
2019-08-04 14:46:38,943 - synapse.http.matrixfederationclient - 436 - INFO - POST-205 - {PUT-O-5} [matrix.org] Got response headers: 401 Unauthorized
2019-08-04 14:46:38,944 - synapse.http.matrixfederationclient - 520 - WARNING - POST-205 - {PUT-O-5} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21jDwYqnpldLoJLEFQvF%3Agovanify.com/%24OL7YN5JbASwMv6G1StrbB7Jg08CEC82-Ry3f0q-9VYI: HttpResponseException("401: b'Unauthorized'",)
2019-08-04 14:46:38,948 - synapse.http.server - 108 - ERROR - POST-205 - Failed handle request via 'RoomCreateRestServlet': <XForwardedForRequest at 0x7f1430a694a8 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.1' site=8008>
```

**Comment by adrianolucas** [comment]
Thanks for the input. I'm trying RocketChat right now, which is closer to what I'd like to achieve.

**Comment by GovanifY** [comment]
This is still an issue to me, keep this one closed, reopening a new one
