### ISSUE TITLE
Spell out that Synapse's ACME support doesn't support ACME v2

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#5872]
Synapse fails on startup if given an ACME v2 endpoint (see https://letsencrypt.org/docs/acme-protocol-updates/):

```
2019-08-16 20:57:52,893 - twisted - 197 - ERROR - - Error during startup:
2019-08-16 20:57:52,894 - twisted - 197 - ERROR - - Traceback (most recent call last):
2019-08-16 20:57:52,895 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-08-16 20:57:52,896 - twisted - 197 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-08-16 20:57:52,896 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
2019-08-16 20:57:52,897 - twisted - 197 - ERROR - -     _inlineCallbacks(r, g, status)
2019-08-16 20:57:52,897 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-08-16 20:57:52,898 - twisted - 197 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-08-16 20:57:52,898 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
2019-08-16 20:57:52,899 - twisted - 197 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-08-16 20:57:52,899 - twisted - 197 - ERROR - - --- <exception caught here> ---
2019-08-16 20:57:52,900 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/app/homeserver.py", line 429, in start
2019-08-16 20:57:52,900 - twisted - 197 - ERROR - -     yield acme.start_listening()
2019-08-16 20:57:52,901 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-08-16 20:57:52,901 - twisted - 197 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-08-16 20:57:52,901 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
2019-08-16 20:57:52,902 - twisted - 197 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-08-16 20:57:52,902 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/handlers/acme.py", line 74, in start_listening
2019-08-16 20:57:52,903 - twisted - 197 - ERROR - -     yield self._issuer._ensure_registered()
2019-08-16 20:57:52,903 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-08-16 20:57:52,903 - twisted - 197 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-08-16 20:57:52,904 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/service.py", line 254, in _register
2019-08-16 20:57:52,904 - twisted - 197 - ERROR - -     client.register(regr)
2019-08-16 20:57:52,905 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/txacme/client.py", line 157, in register
2019-08-16 20:57:52,905 - twisted - 197 - ERROR - -     new_reg, uri=self.directory[new_reg]))
2019-08-16 20:57:52,906 - twisted - 197 - ERROR - -   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/acme/messages.py", line 251, in __getitem__
2019-08-16 20:57:52,906 - twisted - 197 - ERROR - -     raise KeyError('Directory field not found')
2019-08-16 20:57:52,907 - twisted - 197 - ERROR - - builtins.KeyError: 'Directory field not found'
```

This lack of support should be spelled out both in the ACME doc and the config comments.

**Comment by babolivier** [comment]
This is a doc omission rather than a Synapse bug since ACME v1 support works fine as of v1.3.1.

**Comment by hawkowl** [comment]
this is probably a thing we need to worry about because now you can't do new signups on ACME v1

**Comment by andrewhotlab** [comment]
I'm setting up Synapse 1.4.0, and it is not able to generate needed certificates, even setting the right ``url`` parameter in homeserver.yaml in order to use ACME v2 API:
```
acme:
    enabled: true
    url: https://acme-v02.api.letsencrypt.org/directory
```

Here is the error from log file:
```
2019-11-13 11:48:22,601 - synapse.app.homeserver - 245 - WARNING - - Starting daemon.
2019-11-13 11:48:23,418 - twisted - 171 - ERROR - - Error during startup:
2019-11-13 11:48:23,418 - twisted - 171 - ERROR - - Traceback (most recent call last):
2019-11-13 11:48:23,419 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-11-13 11:48:23,420 - twisted - 171 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-11-13 11:48:23,421 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
2019-11-13 11:48:23,421 - twisted - 171 - ERROR - -     _inlineCallbacks(r, g, status)
2019-11-13 11:48:23,421 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-11-13 11:48:23,422 - twisted - 171 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-11-13 11:48:23,422 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
2019-11-13 11:48:23,423 - twisted - 171 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-11-13 11:48:23,423 - twisted - 171 - ERROR - - --- <exception caught here> ---
2019-11-13 11:48:23,424 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/synapse/app/homeserver.py", line 429, in start
2019-11-13 11:48:23,425 - twisted - 171 - ERROR - -     yield acme.start_listening()
2019-11-13 11:48:23,425 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
2019-11-13 11:48:23,425 - twisted - 171 - ERROR - -     result = result.throwExceptionIntoGenerator(g)
2019-11-13 11:48:23,426 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
2019-11-13 11:48:23,426 - twisted - 171 - ERROR - -     return g.throw(self.type, self.value, self.tb)
2019-11-13 11:48:23,426 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/synapse/handlers/acme.py", line 74, in start_listening
2019-11-13 11:48:23,427 - twisted - 171 - ERROR - -     yield self._issuer._ensure_registered()
2019-11-13 11:48:23,427 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2019-11-13 11:48:23,428 - twisted - 171 - ERROR - -     current.result = callback(current.result, *args, **kw)
2019-11-13 11:48:23,428 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/txacme/service.py", line 254, in _register
2019-11-13 11:48:23,429 - twisted - 171 - ERROR - -     client.register(regr)
2019-11-13 11:48:23,429 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/txacme/client.py", line 157, in register
2019-11-13 11:48:23,430 - twisted - 171 - ERROR - -     new_reg, uri=self.directory[new_reg]))
2019-11-13 11:48:23,430 - twisted - 171 - ERROR - -   File "/usr/local/lib/python3.6/site-packages/acme/messages.py", line 251, in __getitem__
2019-11-13 11:48:23,431 - twisted - 171 - ERROR - -     raise KeyError('Directory field not found')
2019-11-13 11:48:23,432 - twisted - 171 - ERROR - - builtins.KeyError: 'Directory field not found'
2019-11-13 11:48:23,437 - synapse.app.homeserver - 70 - WARNING - - Stopping daemon.
```
I guess it is not acceptable such a missing point, since a valid and verifiable certificate is a must, at least to be able to federate, for what I know.

**Comment by babolivier** [comment]
Hey @andrewhotlab, we're looking into ways to make Synapse support ACME v2 (especially now that v1 is deprecated). In the meantime, you can use other ACME clients such as [certbot](https://github.com/certbot/certbot) which allow you to retrieve a valid Let's Encrypt certificate. You can then make Synapse use that certificate (and its private key) by setting, in Synapse's configuration file, the config options `tls_certificate_path` and `tls_private_key_path` to the path of the certificate (with its full chain) and the path of its private key respectively.

**Comment by botto** [comment]
For anyone who wants to get a cert without having to deal with setting up nginx frontend, domain validation is supported by certbot and it helps you through the process:
https://certbot.eff.org/docs/using.html#manual

**Comment by babolivier** [comment]
https://github.com/matrix-org/synapse/issues/6397 has been opened to track the status of the implementation of ACME v2 in Synapse.

**Comment by aaronraimist** [comment]
This has been fixed https://github.com/matrix-org/synapse/blob/develop/docs/ACME.md

**Comment by clokep** [comment]
> This has been fixed [`develop`/docs/ACME.md](https://github.com/matrix-org/synapse/blob/develop/docs/ACME.md?rgh-link-date=2020-07-18T21%3A18%3A19Z)

See #7824.
