### ISSUE TITLE
_check_threepid in auth.py incorrect for MSISDN

### ISSUE THREAD

**Issue by jryans** [matrix-org/synapse#6103]
Looking at this snippet:

https://github.com/matrix-org/synapse/blob/f99a9c9cb062374eb532e3caf72eb4d2e784b574/synapse/handlers/auth.py#L446-L463

...the MSISDN handling should not depend on the `threepid_behaviour_email` setting. Instead, we should use the MSISDN delegate if it exists or else fail.

Riot Web hits this block when trying to provide a MSISDN during registration.

**Comment by jryans** [comment]
Fixed by https://github.com/matrix-org/synapse/pull/6104

**Comment by dudeisbrendan03** [comment]
I'm having an issue starting my synapse server after configuring email, is it related to this?

```
stopped synapse.app.homeserver
Waiting for process to exit before restarting...
All processes exited; now restarting...
Starting ...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 659, in <module>
    main()
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 654, in main
    hs = setup(sys.argv[1:])
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 333, in setup
    "Synapse Homeserver", config_options
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/config/_base.py", line 515, in load_or_generate_config
    config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/config/_base.py", line 537, in parse_config_dict
    data_dir_path=data_dir_path,
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/config/_base.py", line 154, in invoke_all
    results.append(getattr(cls, name)(self, *args, **kargs))
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/config/registration.py", line 103, in read_config
    self.account_threepid_delegate_email = account_threepid_delegates.get("email")
AttributeError: 'list' object has no attribute 'get'
error starting (exit code: 1); see above for logs
```
