### ISSUE TITLE
AmbiguousColumn: column reference "membership" is ambiguous

### ISSUE THREAD

**Issue by nboin123** [matrix-org/synapse#6166]
We have one instance of matrix server running in our production on schema version 55. I configured another server pointing to the same database to test some failures. The new server has was using the version 56 and updated the DB schema. Now the live server started running into this issue - **AmbiguousColumn: column reference "membership" is ambiguous** 

And then the live server failed to restart complaining that the database was too new. I then added the 56 delta manually to the server and updated the schema version in prepare.database.py to 56 ad started up the server without any issues. But that didn't solve the problem. 

I then renamed the "membership" column on the database to eliminate ambiguity and then my server started working. I'm concerned if this rename will affect any other parts of the application. Is this a bug?  

I'm continuously running into errors on the "synapse.storage.background_updates".

**Comment by richvdh** [comment]
please can you share the complete stacktrace

**Comment by nboin123** [comment]
2019-10-04 16:36:52,114 - synapse.http.server - 112 - ERROR - GET-1213103 - Failed handle request via 'SyncRestServlet': <SynapseRequest at 0x7fbf79bfb7e8 method=u'GET' uri=u'/_matrix/client/r0/sync?filter=0&timeout=0&_cacheBuster=1570207012121&access_token=<redacted>' clientproto=u'HTTP/1.0' site=8448>
Traceback (most recent call last):
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    yield h(self, request)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/http/server.py", line 316, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/rest/client/v2_alpha/sync.py", line 167, in on_GET
    full_state=full_state
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/handlers/sync.py", line 242, in wait_for_sync_for_user
    sync_config, since_token, timeout, full_state,
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/handlers/sync.py", line 264, in _wait_for_sync_for_user
    sync_config, since_token, full_state=full_state,
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/handlers/sync.py", line 938, in generate_sync_result
    sync_result_builder, account_data_by_room
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/handlers/sync.py", line 1302, in _generate_sync_entry_for_rooms
    res = yield self._get_all_rooms(sync_result_builder, ignored_users)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/handlers/sync.py", line 1614, in _get_all_rooms
    membership_list=membership_list
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 495, in runInteraction
    **kwargs
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 543, in runWithConnection
    result = yield self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 540, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 412, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/roommember.py", line 245, in _get_rooms_for_user_where_membership_is_txn
    txn.execute(sql, args)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 129, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/matrixadmin/.synapse/local/lib/python2.7/site-packages/synapse/storage/_base.py", line 155, in _do_execute
    return func(sql, *args)
AmbiguousColumn: column reference "membership" is ambiguous
LINE 1: ... '@c5ee872d-761c-e311-a8b0-0050569257ef:ypo' AND (membership...

**Comment by richvdh** [comment]
uhhh, python 2.7 is unsupported. Which version of synapse are you using?

**Comment by nboin123** [comment]
Yeah figured that'd be it. Using 2.7. How can I switch to 3.7?

**Comment by richvdh** [comment]
latest synapse will refuse to start under python 2.7, so I doubt that is correct.

https://github.com/matrix-org/synapse/blob/master/UPGRADE.rst#upgrading-to-v0340 documents the process for switching to python 3.

I'm going to close this as I don't think it is a problem in the current release.
