### ISSUE TITLE
getaddrinfo "Device or resource busy" error spam

### ISSUE THREAD

**Issue by Ralith** [matrix-org/synapse#6190]
### Description

Under routine operation, logs contain large amounts of the following error, which is apparently harmless:

```
twisted: [] 
Traceback (most recent call last):
  File "/nix/store/h8m6qvxi6z6jsa0836gm1wfz8z6mh3mp-python3.7-Twisted-18.9.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/nix/store/h8m6qvxi6z6jsa0836gm1wfz8z6mh3mp-python3.7-Twisted-18.9.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/nix/store/h8m6qvxi6z6jsa0836gm1wfz8z6mh3mp-python3.7-Twisted-18.9.0/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/nix/store/h8m6qvxi6z6jsa0836gm1wfz8z6mh3mp-python3.7-Twisted-18.9.0/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/nix/store/h8m6qvxi6z6jsa0836gm1wfz8z6mh3mp-python3.7-Twisted-18.9.0/lib/python3.7/site-packages/twisted/internet/_resolver.py", line 124, in get
    socketType)
  File "/nix/store/96p42644i76jqgdkxjgyl3f0c8n8k16j-python3-3.7.4/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy
```

### Version information

- **Version**: Synapse 1.3.1
- **Install method**: NixOS package
- **Platform**: NixOS on a small dedicated server

**Comment by richvdh** [comment]
I've never seen this, and I'm a bit mystified as to why getaddrinfo would return EBUSY. I think it must be something specific to your system. Are you using an `nscd`? Can you capture an strace while it happens?

**Comment by Ralith** [comment]
`nscd` is running on the system. It's not quite constant enough to be easy to capture live, unfortunately; maybe when I find some time I can hammer on it for a while.

**Comment by richvdh** [comment]
ok, it sounds a bit like a problem with your libc/nscd then; not really something we can do much about.

**Comment by Ralith** [comment]
I don't think it's reasonable to assume libc is broken just because you've never seen a certain error before.

**Comment by richvdh** [comment]
That's not what I said. 

To me, "Device or resource busy" (ie, EBUSY) sounds like your libc is trying to connect to something, and failing, and I'm assuming it's your nscd.

An strace would help diagnose what's going on.

**Comment by hawkowl** [comment]
Your libc or NSS or something is probably broken. This is a system configuration error, not a Synapse one:

https://code.woboq.org/userspace/glibc/sysdeps/posix/getaddrinfo.c.html#912

**Comment by fadenb** [comment]
I am encountering the same issues from time to time on my system.
I disabled nscd without luck, still getting those errors.

Would appreciate any pointer on what I could check to find the cause :)

**Comment by rihardsk** [comment]
I'm also encountering the same issue. It's not too common - happens ~4 times an hour. Leaving strace running on synapse in the background doesn't seem feasible. I could limit it to some specific types of system calls but i'm not sure what to look for.

**Comment by effolkronium** [comment]
Happens to me on Ubuntu 20, Centos 8. But previous versions of this distros is ok

**Comment by effolkronium** [comment]
Discovered some trash after space after ip in string) that was a cause. Previous Linux distorts uses only first substring before space and do not validate entire string
