### ISSUE TITLE
Server crashes with account validity disabled, can't sign in with it enabled

### ISSUE THREAD

**Issue by dudeisbrendan03** [matrix-org/synapse#6199]
When account validity is disabled I get the following error (only when disabled, if I enable it then nobody can sign in)

```
2019-10-12 00:55:46,374 - synapse.push.mailer - 124 - INFO -  - Created Mailer for app_name 0x80 Social
2019-10-12 00:55:46,375 - synapse.push.mailer - 687 - INFO -  - loading email templates ['add_threepid_failure.html'] from '/home/brendantdj/synapse/res/templates'
2019-10-12 00:55:46,380 - synapse.push.mailer - 687 - INFO -  - loading email templates ['registration.html', 'registration.txt'] from '/home/brendantdj/synapse/res/templates'
2019-10-12 00:55:46,381 - synapse.push.mailer - 124 - INFO -  - Created Mailer for app_name 0x80 Social
2019-10-12 00:55:46,382 - synapse.push.mailer - 687 - INFO -  - loading email templates ['registration_failure.html'] from '/home/brendantdj/synapse/res/templates'
2019-10-12 00:55:46,382 - synapse.push.mailer - 687 - INFO -  - loading email templates ['registration_failure.html'] from '/home/brendantdj/synapse/res/templates'
2019-10-12 00:55:46,387 - synapse.federation.federation_server - 786 - INFO -  - Registering federation EDU handler for 'm.receipt'
2019-10-12 00:55:46,388 - synapse.federation.federation_server - 804 - INFO -  - Registering federation query handler for 'client_keys'
2019-10-12 00:55:46,389 - synapse.federation.federation_server - 786 - INFO -  - Registering federation EDU handler for 'm.direct_to_device'
2019-10-12 00:55:46,396 - twisted - 171 - ERROR -  - Traceback (most recent call last):
2019-10-12 00:55:46,396 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/handlers/account_validity.py", line 53, in __init__
2019-10-12 00:55:46,396 - twisted - 171 - ERROR -  -     self._subject = self._account_validity.renew_email_subject % {
2019-10-12 00:55:46,396 - twisted - 171 - ERROR -  - AttributeError: 'AccountValidityConfig' object has no attribute 'renew_email_subject'
2019-10-12 00:55:46,396 - twisted - 171 - ERROR -  - 
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  - During handling of the above exception, another exception occurred:
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  - 
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  - Traceback (most recent call last):
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 269, in start
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  -     hs.start_listening(listeners)
2019-10-12 00:55:46,397 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 266, in start_listening
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -     self._listening_services.extend(self._listener_http(config, listener))
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 104, in _listener_http
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -     self._configure_named_resource(name, res.get("compress", False))
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 171, in _configure_named_resource
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -     client_resource = ClientRestResource(self)
2019-10-12 00:55:46,398 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/__init__.py", line 72, in __init__
2019-10-12 00:55:46,399 - twisted - 171 - ERROR -  -     self.register_servlets(self, hs)
2019-10-12 00:55:46,399 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/__init__.py", line 119, in register_servlets
2019-10-12 00:55:46,399 - twisted - 171 - ERROR -  -     account_validity.register_servlets(hs, client_resource)
2019-10-12 00:55:46,399 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/account_validity.py", line 103, in register_servlets
2019-10-12 00:55:46,399 - twisted - 171 - ERROR -  -     AccountValidityRenewServlet(hs).register(http_server)
2019-10-12 00:55:46,403 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/account_validity.py", line 43, in __init__
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -     self.account_activity_handler = hs.get_account_validity_handler()
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/server.py", line 569, in _get
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -     dep = builder()
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/server.py", line 530, in build_account_validity_handler
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -     return AccountValidityHandler(self)
2019-10-12 00:55:46,404 - twisted - 171 - ERROR -  -   File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/handlers/account_validity.py", line 60, in __init__
2019-10-12 00:55:46,405 - twisted - 171 - ERROR -  -     self._subject = self._account_validity.renew_email_subject
2019-10-12 00:55:46,405 - twisted - 171 - ERROR -  - AttributeError: 'AccountValidityConfig' object has no attribute 'renew_email_subject'
2019-10-12 00:55:46,406 - synapse.handlers.deactivate_account - 161 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-10-12 00:55:46,413 - synapse.handlers.presence - 236 - INFO - presence.on_shutdown-0 - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-10-12 00:55:46,413 - synapse.handlers.presence - 247 - INFO - presence.on_shutdown-0 - Finished _on_shutdown
2019-10-12 00:55:46,472 - twisted - 171 - CRITICAL -  - Unhandled error in Deferred:
2019-10-12 00:55:46,472 - twisted - 171 - CRITICAL -  - 
Traceback (most recent call last):
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/handlers/account_validity.py", line 53, in __init__
    self._subject = self._account_validity.renew_email_subject % {
AttributeError: 'AccountValidityConfig' object has no attribute 'renew_email_subject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 269, in start
    hs.start_listening(listeners)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 266, in start_listening
    self._listening_services.extend(self._listener_http(config, listener))
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 104, in _listener_http
    self._configure_named_resource(name, res.get("compress", False))
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 171, in _configure_named_resource
    client_resource = ClientRestResource(self)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/__init__.py", line 72, in __init__
    self.register_servlets(self, hs)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/__init__.py", line 119, in register_servlets
    account_validity.register_servlets(hs, client_resource)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/account_validity.py", line 103, in register_servlets
    AccountValidityRenewServlet(hs).register(http_server)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/account_validity.py", line 43, in __init__
    self.account_activity_handler = hs.get_account_validity_handler()
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/server.py", line 569, in _get
    dep = builder()
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/server.py", line 530, in build_account_validity_handler
    return AccountValidityHandler(self)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/handlers/account_validity.py", line 60, in __init__
    self._subject = self._account_validity.renew_email_subject
AttributeError: 'AccountValidityConfig' object has no attribute 'renew_email_subject'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 435, in start
    _base.start(hs, config.listeners)
  File "/home/brendantdj/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 279, in start
    sys.exit(1)
SystemExit: 1
2019-10-12 00:55:46,497 - twisted - 171 - INFO -  - Main loop terminated.
2019-10-12 00:55:46,498 - synapse.app.homeserver - 70 - WARNING -  - Stopping daemon.
```

**Comment by dudeisbrendan03** [comment]
Config available at https://gist.github.com/dudeisbrendan03/dca5266906d7f2b6dd1f8b4093768acd

**Comment by dudeisbrendan03** [comment]
Commenting out entire account validity section let the server start and function correctly.
