### ISSUE TITLE
JSONDecodeError causes 500's while initial syncing or leaving room

### ISSUE THREAD

**Issue by Cadair** [matrix-org/synapse#6207]
### Description

When trying to initial sync a clean device, or when trying to leave the room in question (HQ) I get a 500 error. I get what looks to be this everytime:

```
2019-10-14 15:23:51,140 - synapse.http.server - 109 - ERROR - POST-65085 - Failed handle request via 'RoomMembershipRestServlet': <XForwardedForRequest at 0x7fce967a4050 method='POST' uri='/_matrix/client/r0/rooms/!QtykxKocfZaZOUrTwp%3Amatrix.org/leave' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$1568139640328aHhmJ:200acres.org': {'event_id': '$1568139640328aHhmJ:200acres.org', 'internal_metadata': '{"outlier": false, "soft_failed": true, "stream_ordering": 2553997}', 'json': '{"auth_events": [["$1564954903473544gXBNd:matrix.org", {"sha256": "DJ+cruN2sWXFbpmv5h9Vtd+PtLDcww5pVvVrMzfgnbo"}], ["$152873010877837iaE
ate": [], "redacts": "$15687419811091673hBcYn:matrix.org", "room_id": "!QtykxKocfZaZOUrTwp:matrix.org", "sender": "@risc-j508:matrix.org", "type": "m.room.redaction", "signatures": {"matrix.org": {"ed25519:auto": "wPBUJuabMbJ5kZ5hh5RldAo4a+msvj3U2e4zWPUSWlm5DHwuOHzEE4bBDPYxzHazLYORAoocf3trrTWqvYdoDA"}}, "unsigned": {"age_ts": 1568742008
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
... [truncated] ...
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/events_worker.py", line 512, in _get_events_from_db
    d = json.loads(row["json"])
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

(Full traceback here: https://gist.github.com/Cadair/130ce1e704f2761415bdde17ef8d8482)

### Version information

- **Homeserver**: cadair.com

- **Version**: 1.4.0

- **Install method**: docker

- **Platform**: debian 9 host, postgres 9.6, docker for everything else

**Comment by richvdh** [comment]
I wonder if this is the thing that got fixed by #6185/#6186.

Can you show us a `SELECT json from event_json where event_id='$15687419811091673hBcYn:matrix.org'`?

**Comment by Cadair** [comment]
Here it is in all it's glory:

```
homeserver=# SELECT json from event_json where event_id='$15687419811091673hBcYn:matrix.org';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                json                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {"auth_events":[["$152873010877837iaEeS:matrix.org",{"sha256":"FadaICEbPU11CFeC8NlvANHQdkviLqR7R3dgLQ7tElE"}],["$152873067778016gOxgX:matrix.org",{"sha256":"6QyXfF6kZQqD69jwk86IW4PVTaTw8fN7rebtTPK8E2k"}],["$156710140811KQJyx:sw1v.org",{"sha256":"oaSn85MM9ViNfH6bRgr2rksRg+B43QasmfpGIdXxb0I"}]],"content":{"membership":"join"},"depth":172121,"event_id":"$15687419811091673hBcYn:matrix.org","hashes":{"sha256":"xvHoQlmHzJYMzEZfaICScd40at5ciPHb3rB3bKvisXA"},"origin":"matrix.org","origin_server_ts":1568741981409,"prev_events":[["$15687401151085258TeyvI:matrix.org",{"sha256":"Awd00/HYc25xTDWwy4oq2zMoxIbfWkoHu/YI4tQgHmA"}]],"prev_state":[],"room_id":"!QtykxKocfZaZOUrTwp:matrix.org","sender":"@risc-j508:matrix.org","signatures":{"matrix.org":{"ed25519:auto":"zwoPV0fSxMpyiGb5mWg2QvQMc5baKssEr49c1UGC5mYXjkXTVtq0As6ud2dog5axZIS0K4xhjJt1xFZOpcq8Bg"}},"state_key":"@risc-j508:matrix.org","type":"m.room.member","unsigned":{"age_ts":1568741981409,"replaces_state":"$156779401432679GPhAt:matrix.org"}}
```

**Comment by richvdh** [comment]
Hrm, can't see anything wrong there, but I'm still wondering if it's the same problem as that fixed in #6185/#6186.

Perhaps you could try develop to see if #6186 fixes it?

**Comment by Cadair** [comment]
I upgraded to develop, and then ended up back on 1.4.0 (because of a VM issue) and it seems to have resolved itself. Presumably due to the database changes?

**Comment by richvdh** [comment]
makes sense. the issue might come up again though.

**Comment by z3ntu** [comment]
I experienced a similar problem, I couldn't log in to my account on my homeserver because of a jsondecodeerror. After inspecting the database I found 846 events in the `event_json` table which had binary data instead of json in the json column.

The only special thing I did was migrating from sqlite to postgres after upgrading to v1.5.0. I've checked the old sqlite database and it had no non-plain-text json columns (`SELECT COUNT(*) FROM event_json WHERE json NOT LIKE '{"%';`). I'm checking right now if there are any malformed rows in the database after running the synapse_port_db script on an empty postgres database again, I'll update this post.

I've solved the problem for now by removing the offending rows from the db (`DELETE FROM event_json WHERE json NOT LIKE '{"%';`).

**Comment by tailtwo** [comment]
Same problem here. Some users reported being unable to login. Deleting the offending rows solved the problem.

```
postgres=# \c synapse 
You are now connected to database "synapse" as user "postgres".
synapse=# DELETE FROM event_json WHERE json NOT LIKE '{"%';
DELETE 144
```

**Comment by z3ntu** [comment]
@richvdh Can this issue be re-opened or should a new one be created?

**Comment by richvdh** [comment]
actually @z3ntu I'm going to redirect you to #5312. @Cadair had similar symptoms but a different cause.
