### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by hawkowl** [matrix-org/synapse#6223]
This mostly requires adding it to CI.

**Comment by hawkowl** [comment]
Blocking Twisted issue: https://twistedmatrix.com/trac/ticket/9718#ticket

**Comment by hawkowl** [comment]
Weird test error?

```
[FAIL]
Traceback (most recent call last):
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/hawkowl/code/synapse/synapse/util/patch_inline_callbacks.py", line 146, in check_yield_points_inner
    d = gen.send(result)
  File "/home/hawkowl/code/synapse/tests/storage/test__base.py", line 308, in test_double_get
    self.assertEquals(a.func2.cache.cache.pop.call_count, 3)
  File "/home/hawkowl/code/synapse/.tox/py38/lib/python3.8/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/home/hawkowl/.pyenv/versions/3.8.0/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/hawkowl/.pyenv/versions/3.8.0/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 4 != 3

tests.storage.test__base.CacheDecoratorTestCase.test_double_get
```

**Comment by auscompgeek** [comment]
Relevant issue: #6200

**Comment by hawkowl** [comment]
Twisted issue is fixed in the downstream dependency (https://github.com/glyph/automat/issues/118)

**Comment by V02460** [comment]
I wrote #6213 to address the weird test error. I guess the bug did not materialize because of an implementation detail of Python < 3.8 where different functions share the same reference/are the same object.

**Comment by V02460** [comment]
Adding Python 3.8 support to CI should now be possible as #6213 was merged.

**Comment by richvdh** [comment]
we now have CI

**Comment by richvdh** [comment]
(https://github.com/matrix-org/pipelines/pull/29)
