### ISSUE TITLE
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "group_rooms_g_idx"

### ISSUE THREAD

**Issue by olmari** [matrix-org/synapse#6281]
On Synapse logs when starting up Mautrix-whatsapp I get essentially error `psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "group_rooms_g_idx"` with long traceback. I can't tell on which side, Synapse or Mautrix-whatsapp, the rootcause actually is.

This relates to "room community list" feature where Mautrix-whatsapp pushes whatsapp chatrooms onto "community" for user convenience...

Mautrix-whatsapp log example:
```
Oct 29 18:38:58 morpheus mautrix-whatsapp[22982]: [Oct 29, 2019 18:38:58] [User/@olmari:hacklab.fi/WARN] Failed to add !RQHAnMLyVGOtRkvmvQ:hacklab.fi to +whatsapp_olmari=hacklab.fi:hacklab.fi: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_olmari=hacklab.fi:hacklab.fi/admin/rooms/!RQHAnMLyVGOtRkvmvQ:hacklab.fi code=500 wrapped=M_UNKNOWN: Internal server error
```

and corresponding traceback from Synapse log:
```
Oct 29 18:38:58 morpheus matrix-synapse[22138]: psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "group_rooms_g_idx"
Oct 29 18:38:58 morpheus matrix-synapse[22138]: DETAIL:  Key (group_id, room_id)=(+whatsapp_olmari=hacklab.fi:hacklab.fi, !RQHAnMLyVGOtRkvmvQ:hacklab.fi) already exists.
Oct 29 18:38:59 morpheus matrix-synapse[22138]: 2019-10-29 18:38:59,215 - synapse.http.server - 109 - ERROR - PUT-14805- Failed handle request via 'GroupAdminRoomsServlet': <XForwardedForRequest at 0x7f536e156128 method='PUT' uri='/_matrix/client/r0/groups/+whatsapp_sytem=hacklab.fi:hacklab.fi/admin/rooms/%21sIXNsSPfopbtMojdvz:hacklab.fi?user_id=%40whatsappbot%3Ahacklab.fi' clientproto='HTTP/1.1' site=8008>
Oct 29 18:38:59 morpheus matrix-synapse[22138]: Traceback (most recent call last):
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     await h(self, request)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 326, in _async_render
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     callback_return = await callback_return
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = result.throwExceptionIntoGenerator(g)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return g.throw(self.type, self.value, self.tb)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/groups.py", line 477, in on_PUT
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     group_id, requester_user_id, room_id, content
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = result.throwExceptionIntoGenerator(g)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return g.throw(self.type, self.value, self.tb)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/groups/groups_server.py", line 545, in add_room_to_group
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     yield self.store.add_room_to_group(group_id, room_id, is_public=is_public)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = result.throwExceptionIntoGenerator(g)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return g.throw(self.type, self.value, self.tb)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 614, in _simple_insert
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     yield self.runInteraction(desc, self._simple_insert_txn, table, values)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = result.throwExceptionIntoGenerator(g)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return g.throw(self.type, self.value, self.tb)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 507, in runInteraction
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     **kwargs
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = result.throwExceptionIntoGenerator(g)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return g.throw(self.type, self.value, self.tb)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 555, in runWithConnection
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = inContext.theWork()
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return func(*args,**kw)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     compat.reraise(excValue, excTraceback)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     raise exception.with_traceback(traceback)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     result = func(conn, *args, **kw)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 552, in inner_func
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return func(conn, *args, **kwargs)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 424, in _new_transaction
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     r = func(txn, *args, **kwargs)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 633, in _simple_insert_txn
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     txn.execute(sql, vals)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 152, in execute
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     self._do_execute(self.txn.execute, sql, *args)
Oct 29 18:38:59 morpheus matrix-synapse[22138]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/_base.py", line 178, in _do_execute
Oct 29 18:38:59 morpheus matrix-synapse[22138]:     return func(sql, *args)
```

There is plenty of these for seemingly all of bridge users.

I've made same ticket also onto Mautrix-whatsapp side, as I don't know where is the rootcause: https://github.com/tulir/mautrix-whatsapp/issues/106

- hacklab.fi HS
- 1.5.0
- matrix.org buster repo

**Comment by richvdh** [comment]
I guess mautrix-whatsapp is trying to add a user to a group who is already a member of that group?

Unfortunately groups/communities aren't really finished in synapse: this is the sort of rough edge that is to be expected.

**Comment by olmari** [comment]
I guess best thing to do as of current situation is to wait out what communities / groups / related will become and then see whole deal with new eyes, as this isn't showstopper in itself, and by looking of current task list for synapse rewamping of groups / communities is on the table anyways...

**Comment by olmari** [comment]
I'd say this should/could propably be closed now, as communities isn't really an thing anymore and being deprecated and removed anyway, thus none of this matters anymore.
