### ISSUE TITLE
index "redactions_censored_redacts" does not exist

### ISSUE THREAD

**Issue by Valodim** [matrix-org/synapse#6282]
Just updated from 1.4.1 to 1.5.0, now getting one of these per second in my log:

```
2019-10-29 18:11:43,443 - synapse.storage.background_updates - 110 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/background_updates.py", line 107, in _run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/background_updates.py", line 202, in do_next_background_update
    res = yield self._do_background_update(update_name, desired_duration_ms)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/background_updates.py", line 235, in _do_background_update
    items_updated = yield update_handler(progress, batch_size)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/events_bg_updates.py", line 500, in _event_fix_redactions_bytes
    "_event_fix_redactions_bytes", _event_fix_redactions_bytes_txn
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 507, in runInteraction
    **kwargs
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 555, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 552, in inner_func
    return func(conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 424, in _new_transaction
    r = func(txn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/events_bg_updates.py", line 497, in _event_fix_redactions_bytes_txn
    txn.execute("DROP INDEX redactions_censored_redacts")
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 152, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/_base.py", line 178, in _do_execute
    return func(sql, *args)
psycopg2.errors.UndefinedObject: index "redactions_censored_redacts" does not exist
```

### Version information

- **Homeserver**: stratum0.org
- **Version**: synapse 1.5.0
- **Install method**: debian package
- **Platform**: debian

**Comment by richvdh** [comment]
@Valodim can you share the rest of your logs since you restarted synapse on the new version please?

**Comment by Valodim** [comment]
Sorry, I can't. Meanwhile the log consists 100% of these log entries, and that's 10 files at 100M each :\ On the plus side, synapse seems to work just fine, other than the one failed update attempt per second.

This doesn't seem to have come up for anyone else, does it? perhaps I hit the jackpot freak migration path somehow, and I'm fairly certain I never made any structural changes to the database. My synapse is four or so years old by now and has gone through many versions since then.

**Comment by Valodim** [comment]
No, sorry. I didn't think they would cycle *that* fast.

**Comment by Valodim** [comment]
```
matrix=# SELECT file from applied_schema_deltas where version=56;
                       file                       
--------------------------------------------------
 56/current_state_events_membership.sql
 56/current_state_events_membership_mk2.sql
 56/room_membership_idx.sql
 56/add_spans_to_device_lists.sql
 56/destinations_failure_ts.sql
 56/destinations_retry_interval_type.sql.postgres
 56/devices_last_seen.sql
 56/fix_room_keys_index.sql
 56/redaction_censor.sql
 56/redaction_censor2.sql
 56/stats_separated.sql
 56/user_external_ids.sql
 56/users_in_public_rooms_idx.sql
 56/redaction_censor3_fix_update.sql.postgres
 56/drop_unused_event_tables.sql
 56/hidden_devices.sql
 56/public_room_list_idx.sql
 56/signing_keys.sql
 56/unique_user_filter_index.py
(19 rows)

matrix=# SELECT * from background_updates;
        update_name         | progress_json |               depends_on                
----------------------------+---------------+-----------------------------------------
 event_fix_redactions_bytes | {}            | event_fix_redactions_bytes_create_index
(1 row)
```

doing the other thing

**Comment by richvdh** [comment]
sigh. seems the issue hasn't repeated on the second attempt. guess it will forever remain a mystery.

**Comment by Valodim** [comment]
Thanks for the quick and helpful response, either way!
