### ISSUE TITLE
When you try to add a user, errors pop up

### ISSUE THREAD

**Issue by Nicolayka** [matrix-org/synapse#6292]
For the first time started the server. When you try to add a user, errors pop up. What to do in this case?

In the directory matrix (web) there are no these folders: /_matrix/client/r0/admin/register, where from to take I do not know, prompt please

    Ср 15:20:29 [root] -> /root: $ register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml https://site.ru:443
    New user localpart [root]: username
    Password:
    Confirm password:
    Make admin [no]: yes
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw)
      File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -2] Name or service not known
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
        self._validate_conn(conn)
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
        conn.connect()
      File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
        conn = self._new_conn()
      File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b3bb99128>: Failed to establish a new connection: [Errno -2] Name or service not known
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
        timeout=timeout
      File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='site.ru', port=443): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b3bb99128>: Failed to establish a new connection: [Errno -2] Name or service not known'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/bin/register_new_matrix_user", line 22, in <module>
        main()
      File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
        admin, args.user_type)
      File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 138, in register_new_user
        bool(admin), user_type)
      File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 47, in request_registration
        r = requests.get(url, verify=False)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
        return request('get', url, params=params, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='site.ru', port=443): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9b3bb99128>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Debian 10 x64

**Comment by Bazis007** [comment]
Your domain is site.ru ? :)
HTTPSConnectionPool(host='site.ru', port=443)

I think you need to check connection settings.

**Comment by Nicolayka** [comment]
> Your domain is site.ru ? :)
> HTTPSConnectionPool(host='site.ru', port=443)
> 
> I think you need to check connection settings.

No, no, no. My domain is correctly spelled out in the settings, I just do not want to show it to everyone :)

**Comment by Bazis007** [comment]
@Nicolayka It seems your backend not running. Or virtual host configuration error. Can you make request, using curl? 

Если запущен как демон, посмотри нетстатом, слушается ли сокет.

**Comment by Nicolayka** [comment]
> @Nicolayka It seems your backend not running. Or virtual host configuration error. Can you make request, using curl?
> 
> Если запущен как демон, посмотри нетстатом, слушается ли сокет.

Слушается

The socket listens to
