### ISSUE TITLE
"'resource.struct_rusage' object cannot be interpreted as an integer" on startup

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#6351]
I'm not sure when this started happening, but for some time now I've been getting this error everytime I start my personal homeserver. FWIW I run develop.

```
Nov 11 16:46:34 errol synapse[18767]: 2019-11-11 16:46:34,438 - twisted - 172 - CRITICAL - - Unhandled Error
Nov 11 16:46:34 errol synapse[18767]: Traceback (most recent call last):
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/synapse/app/_base.py", line 114, in run
Nov 11 16:46:34 errol synapse[18767]:     run_command()
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/env/lib/python3.6/site-packages/twisted/internet/base.py", line 1272, in run
Nov 11 16:46:34 errol synapse[18767]:     self.mainLoop()
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/env/lib/python3.6/site-packages/twisted/internet/base.py", line 1281, in mainLoop
Nov 11 16:46:34 errol synapse[18767]:     self.runUntilCurrent()
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/synapse/metrics/__init__.py", line 434, in f
Nov 11 16:46:34 errol synapse[18767]:     ret = func(*args, **kwargs)
Nov 11 16:46:34 errol synapse[18767]: --- <exception caught here> ---
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/env/lib/python3.6/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
Nov 11 16:46:34 errol synapse[18767]:     call.func(*call.args, **call.kw)
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/synapse/util/__init__.py", line 97, in wrapped_callback
Nov 11 16:46:34 errol synapse[18767]:     callback(*args, **kwargs)
Nov 11 16:46:34 errol synapse[18767]:   File "/home/synapse/synapse/synapse/app/homeserver.py", line 588, in performance_stats_init
Nov 11 16:46:34 errol synapse[18767]:     (int(hs.get_clock().time(), resource.getrusage(resource.RUSAGE_SELF)))
Nov 11 16:46:34 errol synapse[18767]: builtins.TypeError: 'resource.struct_rusage' object cannot be interpreted as an integer
```

It doesn't prevent Synapse from starting up though. I haven't taken the time (yet) to track down the cause.

**Comment by DMRobertson** [comment]
Fixed by #6418.
