### ISSUE TITLE
Docker image, using "generate" doesn't work...

### ISSUE THREAD

**Issue by flatline-studios** [matrix-org/synapse#6365]
### Description

Attempting to generate a Synapse config with the `generate` command, as per the Docker hub docs.

### Steps to reproduce

Running the following command:

```
docker run -it --rm \
     --mount type=volume,src=synapse-data,dst=/data \
     -e SYNAPSE_SERVER_NAME=my.matrix.host \
     -e SYNAPSE_REPORT_STATS=no \
     -e SYNAPSE_CONFIG_DIR=/data/conf \
     -e SYNAPSE_CONFIG_PATH=/data/conf/homeserver.yaml \
     -e SYNAPSE_DATA_DIR=/data/data \
     matrixdotorg/synapse:latest generate
```

Results in:

```
Container running as UserID 0:0, ENV (or defaults) requests 991:991
Creating log config /data/conf/my.matrix.host.log.config
Traceback (most recent call last):
  File "/start.py", line 259, in <module>
    main(sys.argv, os.environ)
  File "/start.py", line 201, in main
    return run_generate_config(environ, ownership)
  File "/start.py", line 150, in run_generate_config
    convert("/conf/log.config", log_config_file, environ)
  File "/start.py", line 33, in convert
    with open(dst, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: '/data/conf/my.matrix.host.log.config'
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Docker version 19.03.2, build 6a30dfca03

**Comment by flatline-studios** [comment]
In fact, even just running with the command listed on the Docker Hub page doesn't work (albeit with a different error).

```
~$ docker run -it --rm \
 >     --mount type=volume,src=synapse-data,dst=/data \
>     -e SYNAPSE_SERVER_NAME=my.matrix.host \
>     -e SYNAPSE_REPORT_STATS=yes \
>     matrixdotorg/synapse:latest generate
Container running as UserID 0:0, ENV (or defaults) requests 991:991
Creating log config /data/my.matrix.host.log.config
Generating config file /data/homeserver.yaml
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 659, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 654, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 333, in setup
    "Synapse Homeserver", config_options
  File "/usr/local/lib/python3.7/site-packages/synapse/config/_base.py", line 576, in load_or_generate_config
    with open(config_path, "w") as config_file:
PermissionError: [Errno 13] Permission denied: '/data/homeserver.yaml'
```

**Comment by BlackWolfDEsign** [comment]
docker run -it --name matrix -v $(pwd)/data/:/data/ -e SYNAPSE_SERVER_NAME=chat.domain.de -e SYNAPSE_REPORT_STATS=yes matrixdotorg/synapse:latest migrate_config
docker stop matrix
docker rm matrix
echo "starting:"
docker run -d --name matrix -v $(pwd)/data/:/data/ -p 8008:8008 matrixdotorg/synapse:latest

**Comment by richvdh** [comment]
dup #6303

**Comment by qknight** [comment]
I now reinstalled git for windows and clicked:
**[x] Checkout as-is, commit: Unix-style line endings**
Then I cloned synapse again and it worked out of the box!

Thanks for your support.
