### ISSUE TITLE
synapse_port_db does not parse server_name for debian conf.d

### ISSUE THREAD

**Issue by thifranc** [matrix-org/synapse#6370]
### Description

I tried to run /opt/venvs/matrix-synapse/bin/synapse_port_db  --sqlite-database ~/homeserver.db --postgres-config ./homeserver.psql.yaml as per https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#using-the-port-script
But the script fails

### Steps to reproduce

- get a matrix-synapse debian packaged installed ( with your server_name in /etc/matrix-synapse/conf.d/server_name.yaml )
- set up a postgresql config
- you do not need to start the synapse server
- even without data, I think it should be enough, just running `/opt/venvs/matrix-synapse/bin/synapse_port_db  --sqlite-database [ homeserver.db sqlite3 database  ] --postgres-config [ config containing psql connection ]`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

The error is pretty well explained : the config parser can't find the server_name variable in debian config file ( which is, in my case, located in /etc/matrix-synapse/conf.d/server_name.yaml )
I could proceed by just adding my server_name in the config file containing psql connection like following :
```
server_name: "matrix.l-internet.fr"
```
So this issue is not really blocking and difficult to pass through, but just in case, I rather dig it up hoping that it can help others or even you guys :)


### Version information

- **Homeserver**: Homeserver

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:
{
    "python_version": "3.5.3",
    "server_version": "1.5.1"
}

- **Install method**:
<!-- examples: package manager/git clone/pip  -->
apt install matrix-synapse ( so matrix-synapse-py3 is running )
- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
Debian stretch

**Comment by richvdh** [comment]
> * you do not need to start the synapse server
> * even without data, I think it should be enough, just running `/opt/venvs/matrix-synapse/bin/synapse_port_db  --sqlite-database [ homeserver.db sqlite3 database  ] --postgres-config [ config containing psql connection ]`

If you do not start the server or have any data, you will not have a sqlite3 database which needs porting?

**Comment by thifranc** [comment]
Technically no, but I had added that just for the steps to reproduce the bug. I may have not read the script thoroughly enough, but I think that it will launch and crash just by having a sqlite DB, even without data

**Comment by richvdh** [comment]
The irony is that the port script doesn't need the server_name at all - it's just using the same config parsing functions as synapse, which bail out if there is no server_name.

**Comment by lhorace** [comment]
Does it need email.notif_template_html or email.notif_template_text if email.enable_notifs is True?

```
Traceback (most recent call last):
  File "/usr/bin/synapse_port_db", line 1019, in <module>
    config.parse_config_dict(hs_config, "", "")
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/_base.py", line 651, in parse_config_dict
    data_dir_path=data_dir_path,
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/_base.py", line 266, in invoke_all
    res[name] = getattr(config, func_name)(*args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/config/emailconfig.py", line 264, in read_config
    % (", ".join(["email." + k for k in missing]),)
RuntimeError: email.enable_notifs is True but required keys are missing: email.notif_template_html, email.notif_template_text
```

I figured include this here instead of opening a new issues.

Regards

**Comment by MRAAGH** [comment]
I have encountered this issue as well. Maybe it would make more sense if the script had its own parsing functions? Or maybe the functionality could be split into "shared" and "synapse-only"?
Or maybe the current implementation is better because it's more maintainable
