### ISSUE TITLE
Federation reader should fail more gracefully on a refused connection

### ISSUE THREAD

**Issue by hg-runs** [matrix-org/synapse#6412]
### Description

At the moment a stack trace is logged:

```
2019-11-25 22:34:49,018 - synapse.http.server - 109 - ERROR - PUT-1573 - Failed handle request via 'FederationSendServlet': <SynapseRequest at 0x7f59711748 method='PUT' uri='/_matrix/federation/v1/send/1574214481058' clientproto='HTTP/1.1' site=8011>
Traceback (most recent call last):
  File "/root/syntest/synapse/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/root/syntest/synapse/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/root/syntest/synapse/synapse/federation/transport/server.py", line 324, in new_func
    origin, content, request.args, *args, **kwargs
  File "/root/syntest/synapse/synapse/federation/transport/server.py", line 407, in on_PUT
    origin, transaction_data
  File "/root/syntest/synapse/synapse/federation/federation_server.py", line 121, in on_incoming_transaction
    origin, transaction, request_time
  File "/root/syntest/synapse/synapse/federation/federation_server.py", line 253, in _handle_incoming_transaction
    await self.received_edu(origin, edu.edu_type, edu.content)
  File "/root/syntest/synapse/synapse/federation/federation_server.py", line 264, in received_edu
    await self.registry.on_edu(edu_type, origin, content)
  File "/root/syntest/synapse/synapse/federation/federation_server.py", line 826, in on_edu
    return await self._send_edu(edu_type=edu_type, origin=origin, content=content)
twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: using matrix-synapse 1.60RC2

**Comment by richvdh** [comment]
I think this is a refused connection when attempting to talk to the master, so to some extent all bets are off. OTOH we could probably fail a *bit* more gracefully.

> 1.60RC2

I think you mean 1.6.0rc2 ;)
