### ISSUE TITLE
Can't view or modify list of rooms in a community

### ISSUE THREAD

**Issue by logic** [matrix-org/synapse#6413]
### Description

I have a community defined on my homeserver, and viewing it in riot-web gives a spinner forever on the list of rooms, and am unable to add rooms to the community.

### Steps to reproduce

In riot, go to "view community", see spinner under the "ROOMS" heading. On the server, synapse throws:

```
synapse[4356]: synapse.http.server: [GET-136] Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7fac2448e810 method='GET' uri=
'/_matrix/client/r0/groups/%2Bclub140%3Alogic.net/rooms' clientproto='HTTP/1.0' site=8008>
                                                        Traceback (most recent call last):
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
                                                            result = g.send(result)
                                                        StopIteration: {}
                                                        
                                                        During handling of the above exception, another exception occurred:
                                                        
                                                        Traceback (most recent call last):
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
                                                            result = g.send(result)
                                                        StopIteration: {}
                                                        
                                                        During handling of the above exception, another exception occurred:
                                                        
                                                        Traceback (most recent call last):
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
                                                            await h(self, request)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/synapse/http/server.py", line 326, in _async_render
                                                            callback_return = await callback_return
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                                            result = result.throwExceptionIntoGenerator(g)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerat
or
                                                            return g.throw(self.type, self.value, self.tb)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/synapse/rest/client/v2_alpha/groups.py", line 347, in on_GET
                                                            group_id, requester_user_id
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                                            result = result.throwExceptionIntoGenerator(g)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerat
or
                                                            return g.throw(self.type, self.value, self.tb)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/synapse/groups/groups_server.py", line 519, in get_rooms_in_group
                                                            room_id, len(joined_users), with_alias=False, allow_private=True
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
                                                            result = g.send(result)
                                                          File "/srv/matrix.logic.net/venv3.7/lib64/python3.7/site-packages/synapse/handlers/room_list.py", line 294, in generate_room_entry
                                                            result["m.federate"] = create_event.content.get("m.federate", True)
                                                        AttributeError: 'NoneType' object has no attribute 'content'
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.logic.net

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.5.1

- **Install method**: pip (virtualenv)
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Fedora 31 x86_64 on a DigitalOcean VM
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by logic** [comment]
Aaaaaaaand, a little more searching shows that this is just the same thing as #5824, and the solution there seems to have fixed the problem for me.
