### ISSUE TITLE
Exception("Cannot handle PUT /push_rules on worker")

### ISSUE THREAD

**Issue by hg-runs** [matrix-org/synapse#6432]
### Description

Trying to disable notifications for an account throws an exception:

```
2019-11-28 09:04:28,020 - synapse.http.server - 109 - ERROR - PUT-16 - Failed handle request via 'PushRuleRestServlet': <SynapseRequest at 0x7f7dec7e48 method='PUT' uri='/_matrix/client/r0/pushrules/global/override/.m.rule.master/enabled' clientproto='HTTP/1.1' site=8084>
Traceback (most recent call last):
  File "/opt/syntest/synapse/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/opt/syntest/synapse/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/opt/syntest/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/syntest/synapse/synapse/rest/client/v1/push_rule.py", line 52, in on_PUT
    raise Exception("Cannot handle PUT /push_rules on worker")
```

### Steps to reproduce

Using Riot Desktop:
- User settings => notifications => Enable notifications for this account => Set to OFF
- Check log for exception

![2019-11-28 09_06_20-Riot  1  _ Riot Web_Desktop](https://user-images.githubusercontent.com/29901271/69789682-5293ce00-11c1-11ea-926b-06b9910e718b.png)

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

- **Version**:
{
    "python_version": "3.7.3",
    "server_version": "1.6.0 (b=develop,0f87b912a)"
}

- **Install method**:
  git clone
- **Platform**:
Debian 10, ARM64

**Comment by richvdh** [comment]
sounds like you're routing `PUT ^/_matrix/client/r0/pushrules` to a worker instance. Don't. The list of APIs that each worker can handle is at https://github.com/matrix-org/synapse/blob/master/docs/workers.md.

**Comment by hg-runs** [comment]
My fault...
Actually I **was** looking at workers.md and copy pasting the regex, but simply overlooked the 'GET'

> Additionally, the following REST endpoints can be handled for GET requests:
`^/_matrix/client/(api/v1|r0|unstable)/pushrules/.*$`
