### ISSUE TITLE
Pusher throws exceptions on startup on matrix.org

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#6508]
Sample stack trace:

```
Traceback (most recent call last):
  File "/home/synapse/src/synapse/push/pusherpool.py", line 254, in _start_pusher
    p = self.pusher_factory.create_pusher(pusherdict)
  File "/home/synapse/src/synapse/push/pusher.py", line 67, in create_pusher
    return f(self.hs, pusherdict)
  File "/home/synapse/src/synapse/push/pusher.py", line 70, in _create_email_pusher
    app_name = self._app_name_from_pusherdict(pusherdict)
  File "/home/synapse/src/synapse/push/pusher.py", line 83, in _app_name_from_pusherdict
    if "data" in pusherdict and "brand" in pusherdict["data"]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by richvdh** [comment]
fixed by #6558
