### ISSUE TITLE
Error in configuring postgress sql with matrix

### ISSUE THREAD

**Issue by souvikbhattacharyas** [matrix-org/synapse#654]
Hi, 
when I am trying to setup matrix with postgress I am facing below error, though I am able to run matrix through sqllite.

Command: python -m synapse.app.homeserver --report-stats=no -c homeserver.yaml -c db.yaml
db.yaml:
database:
    name: psycopg2
    args:
        user: matrix
        password: *Syn@pse#
        database: synapse
        host: 172.17.0.2
        cp_min: 5
        cp_max: 10

Error : 

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 746, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 741, in main
    hs = setup(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 360, in setup
    generate_section="Homeserver"
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 310, in load_config
    yaml_config = cls.read_config_file(config_file)
  File "/usr/local/lib/python2.7/dist-packages/synapse/config/_base.py", line 129, in read_config_file
    return yaml.load(file_stream)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 69, in compose_node
    % anchor.encode('utf-8'), event.start_mark)
yaml.composer.ComposerError: found undefined alias 'Syn'
  in "db.yaml", line 5, column 19

**Comment by ara4n** [comment]
your YAML config is not valid YAML: you need to quote the password string as "*Syn@pse#".

**Comment by souvikbhattacharyas** [comment]
Ok. Also can you tell me the process to run the server in background.

Command: python -m synapse.app.homeserver --report-stats=no -c homeserver.yaml -c db.yaml

**Comment by souvikbhattacharyas** [comment]
Yes it's working now. Thanks.
