### ISSUE TITLE
Cannot create pid file: /var/run/turnserver.pid: Permission denied

### ISSUE THREAD

**Issue by Tidle999** [matrix-org/synapse#6568]
Hello,

trying to install Matrix via Docker with the following commands:

```
docker run -v /share/Docker-Configs/matrix:/data --rm \
    -e SERVER_NAME=chat.***.de -e REPORT_STATS=no silviof/docker-matrix generate
```

without changing anything, because want to use the default settings, i am running the container with this:

`docker run --name matrix \
-v /share/Docker-Configs/matrix:/data \
-e SERVER_NAME=chat.***.de \
-e REPORT_STATS=no \
-p 8108:8008 \
-p 8448:8448 \
-p 3478:3478 \
silviof/docker-matrix`

But getting errors:

```
-=> start turn
-=> start matrix
Cannot create pid file: /var/run/turnserver.pid: Permission denied
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
2019-12-19 11:41:24,041 - root - 169 - WARNING - None - ***** STARTING SERVER *****
2019-12-19 11:41:24,089 - root - 170 - WARNING - None - Server /usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py version 1.3.1
2019-12-19 11:41:24,090 - root - 171 - INFO - None - Server hostname: chat.*****.de
2019-12-19 11:41:24,091 - twisted - 197 - INFO - None - Redirected stdout/stderr to logs
2019-12-19 11:41:24,096 - synapse.app.homeserver - 359 - INFO - None - Preparing database: sqlite3...
2019-12-19 11:42:13,327 - synapse.storage.prepare_database - 242 - INFO - None - Upgrading schema to v55
2019-12-19 11:42:13,328 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 55/access_token_expiry.sql
2019-12-19 11:42:13,336 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 55/track_threepid_validations.sql
2019-12-19 11:42:13,339 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 55/users_alter_deactivated.sql
2019-12-19 11:42:13,343 - synapse.storage.prepare_database - 242 - INFO - None - Upgrading schema to v56
2019-12-19 11:42:13,344 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 56/current_state_events_membership.sql
2019-12-19 11:42:13,348 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 56/current_state_events_membership_mk2.sql
2019-12-19 11:42:13,349 - synapse.storage.prepare_database - 280 - INFO - None - Applying schema 56/room_membership_idx.sql
2019-12-19 11:42:13,525 - synapse.app.homeserver - 377 - INFO - None - Database prepared in sqlite3.
2019-12-19 11:42:13,525 - synapse.server - 233 - INFO - None - Setting up.
2019-12-19 11:42:13,550 - synapse.storage.event_push_actions - 498 - INFO - None - Searching for stream ordering 1 month ago
2019-12-19 11:42:13,551 - synapse.storage.event_push_actions - 503 - INFO - None - Found stream ordering 1 month ago: it's 0
2019-12-19 11:42:13,551 - synapse.storage.event_push_actions - 505 - INFO - None - Searching for stream ordering 1 day ago
2019-12-19 11:42:13,551 - synapse.storage.event_push_actions - 510 - INFO - None - Found stream ordering 1 day ago: it's 0
2019-12-19 11:42:13,561 - synapse.server - 237 - INFO - None - Finished setting up.
2019-12-19 11:42:13,600 - synapse.app.homeserver - 108 - INFO -  - Running
2019-12-19 11:42:13,600 - synapse.app.homeserver - 30 - INFO -  - Set file limit to: 65536
2019-12-19 11:42:13,604 - synapse.federation.federation_server - 801 - INFO -  - Registering federation query handler for 'profile'
2019-12-19 11:42:13,605 - synapse.push.pusher - 41 - INFO -  - email enable notifs: False
2019-12-19 11:42:13,607 - synapse.federation.federation_server - 801 - INFO -  - Registering federation query handler for 'directory'
2019-12-19 11:42:13,608 - synapse.handlers.auth - 84 - INFO -  - Extra password_providers: []
2019-12-19 11:42:13,610 - synapse.federation.federation_server - 783 - INFO -  - Registering federation EDU handler for 'm.device_list_update'
2019-12-19 11:42:13,610 - synapse.federation.federation_server - 801 - INFO -  - Registering federation query handler for 'user_devices'
2019-12-19 11:42:13,637 - synapse.federation.federation_server - 783 - INFO -  - Registering federation EDU handler for 'm.presence'
2019-12-19 11:42:13,638 - synapse.federation.federation_server - 783 - INFO -  - Registering federation EDU handler for 'm.typing'
2019-12-19 11:42:13,641 - synapse.handlers.deactivate_account - 149 - INFO - user_parter_loop-0 - Starting user parter
2019-12-19 11:42:13,643 - synapse.federation.federation_server - 783 - INFO -  - Registering federation EDU handler for 'm.receipt'
2019-12-19 11:42:13,644 - synapse.federation.federation_server - 801 - INFO -  - Registering federation query handler for 'client_keys'
2019-12-19 11:42:13,646 - synapse.federation.federation_server - 783 - INFO -  - Registering federation EDU handler for 'm.direct_to_device'
2019-12-19 11:42:13,675 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f40be153828> to path b'/_matrix/client/api/v1'
2019-12-19 11:42:13,676 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f40be153828> to path b'/_matrix/client/r0'
2019-12-19 11:42:13,676 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f40be153828> to path b'/_matrix/client/unstable'
2019-12-19 11:42:13,676 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f40be153828> to path b'/_matrix/client/v2_alpha'
2019-12-19 11:42:13,676 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f40be153828> to path b'/_matrix/client/versions'
2019-12-19 11:42:13,677 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.well_known.WellKnownResource object at 0x7f40bd8a7588> to path b'/.well-known/matrix/client'
2019-12-19 11:42:13,677 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.admin.AdminRestResource object at 0x7f40bd8ca978> to path b'/_synapse/admin'
2019-12-19 11:42:13,677 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching FilePath('/usr/local/lib/python3.7/dist-packages/synapse/static') to path b'/_matrix/static'
2019-12-19 11:42:13,677 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7f40bd8b2da0> to path b'/_matrix/media/r0'
2019-12-19 11:42:13,678 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7f40bd8b2da0> to path b'/_matrix/media/v1'
2019-12-19 11:42:13,678 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource object at 0x7f40bd8d4400> to path b'/_matrix/content'
2019-12-19 11:42:13,678 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x7f40bd8cafd0> to path b'/_matrix/federation'
2019-12-19 11:42:13,679 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.key.v2.KeyApiV2Resource object at 0x7f40bd8b8c18> to path b'/_matrix/key/v2'
2019-12-19 11:42:13,683 - twisted - 197 - ERROR -  - Traceback (most recent call last):
2019-12-19 11:42:13,684 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/tcp.py", line 1361, in startListening
2019-12-19 11:42:13,684 - twisted - 197 - ERROR -  -     skt.bind(addr)
2019-12-19 11:42:13,685 - twisted - 197 - ERROR -  - OSError: [Errno 99] Cannot assign requested address
2019-12-19 11:42:13,685 - twisted - 197 - ERROR -  -
2019-12-19 11:42:13,686 - twisted - 197 - ERROR -  - During handling of the above exception, another exception occurred:
2019-12-19 11:42:13,686 - twisted - 197 - ERROR -  -
2019-12-19 11:42:13,687 - twisted - 197 - ERROR -  - Traceback (most recent call last):
2019-12-19 11:42:13,688 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 267, in start
2019-12-19 11:42:13,688 - twisted - 197 - ERROR -  -     hs.start_listening(listeners)
2019-12-19 11:42:13,689 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 266, in start_listening
2019-12-19 11:42:13,690 - twisted - 197 - ERROR -  -     self._listening_services.extend(self._listener_http(config, listener))
2019-12-19 11:42:13,690 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 152, in _listener_http
2019-12-19 11:42:13,691 - twisted - 197 - ERROR -  -     reactor=self.get_reactor(),
2019-12-19 11:42:13,692 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 173, in listen_tcp
2019-12-19 11:42:13,692 - twisted - 197 - ERROR -  -     check_bind_error(e, address, bind_addresses)
2019-12-19 11:42:13,692 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/__init__.py", line 49, in check_bind_error
2019-12-19 11:42:13,693 - twisted - 197 - ERROR -  -     raise e
2019-12-19 11:42:13,693 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 171, in listen_tcp
2019-12-19 11:42:13,694 - twisted - 197 - ERROR -  -     r.append(reactor.listenTCP(port, factory, backlog, address))
2019-12-19 11:42:13,694 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2019-12-19 11:42:13,695 - twisted - 197 - ERROR -  -     p.startListening()
2019-12-19 11:42:13,695 - twisted - 197 - ERROR -  -   File "/usr/local/lib/python3.7/dist-packages/twisted/internet/tcp.py", line 1363, in startListening
2019-12-19 11:42:13,696 - twisted - 197 - ERROR -  -     raise CannotListenError(self.interface, self.port, le)
2019-12-19 11:42:13,696 - twisted - 197 - ERROR -  - twisted.internet.error.CannotListenError: Couldn't listen on ::1:8008: [Errno 99] Cannot assign requested address.
2019-12-19 11:42:13,698 - synapse.handlers.deactivate_account - 159 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-12-19 11:42:13,703 - synapse.handlers.presence - 236 - INFO - presence.on_shutdown-0 - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-12-19 11:42:13,703 - synapse.handlers.presence - 247 - INFO - presence.on_shutdown-0 - Finished _on_shutdown
2019-12-19 11:42:13,744 - twisted - 197 - CRITICAL -  - Unhandled error in Deferred:
2019-12-19 11:42:13,744 - twisted - 197 - CRITICAL -  -
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 267, in start
    hs.start_listening(listeners)
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 266, in start_listening
    self._listening_services.extend(self._listener_http(config, listener))
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 152, in _listener_http
    reactor=self.get_reactor(),
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 173, in listen_tcp
    check_bind_error(e, address, bind_addresses)
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/__init__.py", line 49, in check_bind_error
    raise e
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 171, in listen_tcp
    r.append(reactor.listenTCP(port, factory, backlog, address))
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on ::1:8008: [Errno 99] Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/homeserver.py", line 435, in start
    _base.start(hs, config.listeners)
  File "/usr/local/lib/python3.7/dist-packages/synapse/app/_base.py", line 277, in start
    sys.exit(1)
SystemExit: 1
2019-12-19 11:42:13,761 - twisted - 197 - INFO -  - Main loop terminated.

```

Any ideas what i am doing wrong?

Thanks

Tom

**Comment by richvdh** [comment]
this sounds like an issue with the `silviof/docker-matrix` image, not synapse.
