### ISSUE TITLE
psql error trying to update device list for remote user

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#6593]
This is causing UISIs because my device list is outdated on my dev server (by a couple years, only kinda annoying now). This is what happens when the device list update hits the dev box:

```
2019-12-23 19:54:10,417 - synapse.federation.transport.server - 154 - INFO - PUT-42735 - Request from t2l.io
2019-12-23 19:54:10,419 - synapse.federation.transport.server - 389 - INFO - PUT-42735 - Received txn 1576857429888 from t2l.io. (PDUs: 0, EDUs: 1)
2019-12-23 19:54:10,422 - synapse.http.matrixfederationclient - 408 - INFO - PUT-42735 - {GET-O-57} [t2l.io] Sending request: GET matrix://t2l.io/_matrix/federation/v1/user/devices/%40travis%3At2l.io; timeout 30.000000s
2019-12-23 19:54:10,424 - synapse.http.federation.matrix_federation_agent - 242 - INFO - PUT-42735 - Connecting to matrix.t2l.io:8448
2019-12-23 19:54:11,168 - synapse.http.matrixfederationclient - 440 - INFO - PUT-42735 - {GET-O-57} [t2l.io] Got response headers: 200 OK
2019-12-23 19:54:11,170 - synapse.http.matrixfederationclient - 164 - INFO - PUT-42735 - {GET-O-57} [t2l.io] Completed: 200 OK
2019-12-23 19:54:11,176 - synapse.federation.federation_server - 793 - ERROR - PUT-42735 - Failed to handle edu 'm.device_list_update'
Traceback (most recent call last):
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/federation/federation_server.py", line 789, in on_edu
    await handler(origin, content)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/handlers/device.py", line 575, in incoming_device_list_update
    yield self._handle_device_updates(user_id)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/util/metrics.py", line 82, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/handlers/device.py", line 604, in _handle_device_updates
    yield self.user_device_resync(user_id)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/handlers/device.py", line 724, in user_device_resync
    yield self.store.update_remote_device_list_cache(user_id, devices, stream_id)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 456, in runInteraction
    **kwargs
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 504, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 501, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 339, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/data_stores/main/devices.py", line 958, in _update_remote_device_list_cache_txn
    lock=False,
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 697, in simple_upsert_txn
    txn, table, keyvalues, values, insertion_values=insertion_values
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 810, in simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 142, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/matrix/.synapse/local/lib/python3.6/site-packages/synapse/storage/database.py", line 168, in _do_execute
    return func(sql, *args)
psycopg2.ProgrammingError: there is no unique or exclusion constraint matching the ON CONFLICT specification

2019-12-23 19:54:11,188 - synapse.access.https.8448 - 302 - INFO - PUT-42735 - ::ffff:157.230.115.0 - 8448 - {t2l.io} Processed request: 1.198sec/0.000sec (0.022sec, 0.001sec) (0.002sec/0.011sec/7) 12B 200 "PUT /_matrix/federation/v1/send/1576857429888 HTTP/1.1" "Synapse/1.7.2" [0 dbevts]
```

**Comment by richvdh** [comment]
that suggests it's missing the unique index on `device_lists_remote_extremeties`. Can you `\d device_lists_remote_extremeties` ?

**Comment by turt2live** [comment]
```
synapse=# \d device_lists_remote_extremeties
  Table "public.device_lists_remote_extremeties"
  Column   | Type | Collation | Nullable | Default
-----------+------+-----------+----------+---------
 user_id   | text |           | not null |
 stream_id | text |           | not null |
```

**Comment by turt2live** [comment]
Creating the index fixed it:
```
create unique index device_lists_remote_extremeties_unique_idx on device_lists_remote_extremeties(user_id);
```

@richvdh points out that this server previously had a similar problem here: https://github.com/matrix-org/synapse/issues/4503

Possibly https://github.com/matrix-org/synapse/issues/4877 ? In any case, this one is fixed.
