### ISSUE TITLE
Cant start synapse, what wrong?

### ISSUE THREAD

**Issue by wjhtinger** [matrix-org/synapse#6594]
2019-12-24 18:31:49,749 - synapse.app.homeserver - 140 - INFO -  - Synapse now listening on TCP port 8448 (TLS)
2019-12-24 18:31:49,769 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f4b3f210b38> to path b'/_matrix/client/api/v1'
2019-12-24 18:31:49,769 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f4b3f210b38> to path b'/_matrix/client/r0'
2019-12-24 18:31:49,770 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f4b3f210b38> to path b'/_matrix/client/unstable'
2019-12-24 18:31:49,770 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f4b3f210b38> to path b'/_matrix/client/v2_alpha'
2019-12-24 18:31:49,770 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7f4b3f210b38> to path b'/_matrix/client/versions'
2019-12-24 18:31:49,770 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.well_known.WellKnownResource object at 0x7f4b3f205a90> to path b'/.well-known/matrix/client'
2019-12-24 18:31:49,770 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.admin.AdminRestResource object at 0x7f4b3f1c0e80> to path b'/_synapse/admin'
2019-12-24 18:31:49,771 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching FilePath('/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/static') to path b'/_matrix/static'
2019-12-24 18:31:49,771 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7f4b3f250320> to path b'/_matrix/media/r0'
2019-12-24 18:31:49,771 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7f4b3f250320> to path b'/_matrix/media/v1'
2019-12-24 18:31:49,771 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource object at 0x7f4b3f25a470> to path b'/_matrix/content'
2019-12-24 18:31:49,771 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x7f4b3f1bb390> to path b'/_matrix/federation'
2019-12-24 18:31:49,772 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.key.v2.KeyApiV2Resource object at 0x7f4b3f210710> to path b'/_matrix/key/v2'
2019-12-24 18:31:49,774 - twisted - 172 - ERROR -  - Traceback (most recent call last):
2019-12-24 18:31:49,775 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2019-12-24 18:31:49,775 - twisted - 172 - ERROR -  -     skt.bind(addr)
2019-12-24 18:31:49,775 - twisted - 172 - ERROR -  - OSError: [Errno 99] Cannot assign requested address
2019-12-24 18:31:49,775 - twisted - 172 - ERROR -  -
2019-12-24 18:31:49,776 - twisted - 172 - ERROR -  - During handling of the above exception, another exception occurred:
2019-12-24 18:31:49,776 - twisted - 172 - ERROR -  -
2019-12-24 18:31:49,776 - twisted - 172 - ERROR -  - Traceback (most recent call last):
2019-12-24 18:31:49,777 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/_base.py", line 271, in start
2019-12-24 18:31:49,777 - twisted - 172 - ERROR -  -     hs.start_listening(listeners)
2019-12-24 18:31:49,777 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 267, in start_listening
2019-12-24 18:31:49,778 - twisted - 172 - ERROR -  -     self._listening_services.extend(self._listener_http(config, listener))
2019-12-24 18:31:49,778 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 153, in _listener_http
2019-12-24 18:31:49,778 - twisted - 172 - ERROR -  -     reactor=self.get_reactor(),
2019-12-24 18:31:49,778 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/_base.py", line 175, in listen_tcp
2019-12-24 18:31:49,779 - twisted - 172 - ERROR -  -     check_bind_error(e, address, bind_addresses)
2019-12-24 18:31:49,779 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/__init__.py", line 51, in check_bind_error
2019-12-24 18:31:49,779 - twisted - 172 - ERROR -  -     raise e
2019-12-24 18:31:49,779 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/synapse/app/_base.py", line 173, in listen_tcp
2019-12-24 18:31:49,780 - twisted - 172 - ERROR -  -     r.append(reactor.listenTCP(port, factory, backlog, address))
2019-12-24 18:31:49,780 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2019-12-24 18:31:49,780 - twisted - 172 - ERROR -  -     p.startListening()
2019-12-24 18:31:49,780 - twisted - 172 - ERROR -  -   File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2019-12-24 18:31:49,781 - twisted - 172 - ERROR -  -     raise CannotListenError(self.interface, self.port, le)
2019-12-24 18:31:49,781 - twisted - 172 - ERROR -  - twisted.internet.error.CannotListenError: Couldn't listen on ::1:8008: [Errno 99] Cannot assign requested address.
2019-12-24 18:31:49,783 - synapse.handlers.deactivate_account - 201 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-12-24 18:31:49,784 - synapse.handlers.presence - 238 - INFO - presence.on_shutdown-0 - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-12-24 18:31:49,785 - synapse.handlers.presence - 249 - INFO - presence.on_shutdown-0 - Finished _on_shutdown
2019-12-24 18:31:49,785 - synapse.metrics - 462 - INFO -  - Collecting gc 1
2019-12-24 18:31:49,833 - twisted - 172 - CRITICAL -  - Unhandled error in Deferred:
2019-12-24 18:31:49,834 - twisted - 172 - CRITICAL -  -
Traceback (most recent call last):
  File "/home/wangjh/.synapse2/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)

**Comment by turt2live** [comment]
Looks like you've told it to bind to IPv6 without IPv6 being present. #synapse:matrix.org is better suited for such support requests.
