### ISSUE TITLE
On startup: Background process 'stats.notify_new_event' threw an exception

### ISSUE THREAD

**Issue by hg-runs** [matrix-org/synapse#6600]
### Description

Synapse throws an exception during startup

```
2019-12-28 18:13:58,866 - synapse.storage.background_updates - 102 - INFO - background_updates-0 - Starting background schema updates
2019-12-28 18:13:58,871 - synapse.handlers.deactivate_account - 196 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-12-28 18:13:58,878 - synapse.metrics - 462 - INFO -  - Collecting gc 1
2019-12-28 18:13:59,051 - synapse.metrics.background_process_metrics - 214 - ERROR - stats.notify_new_event-0 - Background process 'stats.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/opt/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: 82887

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: 82887

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/synapse/synapse/synapse/metrics/background_process_metrics.py", line 212, in run
    return (yield result)
  File "/opt/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/synapse/synapse/synapse/handlers/stats.py", line 74, in process
    yield self._unsafe_process()
  File "/opt/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/synapse/synapse/synapse/handlers/stats.py", line 100, in _unsafe_process
    self.pos, room_max_stream_ordering
  File "/opt/synapse/synapse/synapse/storage/data_stores/main/state_deltas.py", line 51, in get_current_state_deltas
    assert prev_stream_id <= max_stream_id
AssertionError
2019-12-28 18:13:59,064 - synapse.push.pusherpool - 240 - INFO - start_pushers-0 - Started pushers
2019-12-28 18:13:59,883 - synapse.storage.background_updates - 116 - INFO - background_updates-0 - No more background updates to do. Unscheduling background update task.
```

### Steps to reproduce

- Clone developer branch
- Generate fresh homeserver.yaml file
- Change yaml file from sqlite to an existing synapse postgresql db
- Try to start homeserver with synctl start

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

- **Version**:
{
    "python_version": "3.7.3",
    "server_version": "1.7.2 (b=develop,7c6b85355)"
}

- **Install method**:
  git clone
- **Platform**:
Debian 10, ARM64

**Comment by richvdh** [comment]
odd

can you show the results of the following queries on your database:

```
select max(stream_ordering) from events;
select * from stats_incremental_position;
```

**Comment by hg-runs** [comment]
There you go:
`postgres=# \c synapse
You are now connected to database "synapse" as user "postgres".
synapse=# select max(stream_ordering) from events;
  max
-------
 89137
(1 row)

synapse=# select * from stats_incremental_position;
 lock | stream_id
------+-----------
 X    |     89137
(1 row)

`
To be honest I am a bit lost. The error still persists.
Will restart postgres right now (just in case something else is messed up)

**Comment by richvdh** [comment]
very odd. might be worth turning  on debug logging and seeing if that gives any clues.

**Comment by hg-runs** [comment]
Can't reproduce the error while using the latest dev version:
- **Version**:
{
    "python_version": "3.7.3",
    "server_version": "1.7.2 (b=develop,4b36b482e)"
}

Closing this issue for now
