### ISSUE TITLE
Failed to register new user with matrix

### ISSUE THREAD

**Issue by hgy987654** [matrix-org/synapse#6610]
I cannot register a new matrix user. I get the following error feedback.

```linux
ERROR! Received 403 Forbidden 
HMAC incorrect
```
This is the configuration:

Ubuntu 16.04 on AWS
Python 3.6.9
I have a public IP and a legal domain name, encrypted with Let's encrypt.

When I enter  `synctl start`  will appear

```linux
2019-12-31 01:54:22,569 - twisted - 172 - INFO - None - Redirected stdout/stderr to logs
2019-12-31 01:54:22,569 - root - 237 - WARNING - None - ***** STARTING SERVER *****
2019-12-31 01:54:22,569 - root - 238 - WARNING - None - Server /root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py version 1.7.2
2019-12-31 01:54:22,569 - root - 239 - INFO - None - Server hostname: my_server_name
2019-12-31 01:54:22,570 - synapse.app.homeserver - 344 - INFO - None - Setting up server
2019-12-31 01:54:22,570 - synapse.server - 239 - INFO - None - Setting up.
2019-12-31 01:54:22,575 - synapse.storage.prepare_database - 301 - INFO - None - Upgrading schema to v56
2019-12-31 01:54:22,579 - synapse.storage.data_stores.main.event_push_actions - 499 - INFO - None - Searching for stream ordering 1 month ago
2019-12-31 01:54:22,579 - synapse.storage.data_stores.main.event_push_actions - 504 - INFO - None - Found stream ordering 1 month ago: it's 0
2019-12-31 01:54:22,580 - synapse.storage.data_stores.main.event_push_actions - 506 - INFO - None - Searching for stream ordering 1 day ago
2019-12-31 01:54:22,580 - synapse.storage.data_stores.main.event_push_actions - 511 - INFO - None - Found stream ordering 1 day ago: it's 0
2019-12-31 01:54:22,583 - synapse.server - 244 - INFO - None - Finished setting up.
2019-12-31 01:54:22,600 - synapse.app.homeserver - 615 - INFO - None - Scheduling stats reporting for 3 hour intervals
started synapse.app.homeserver('homeserver.yaml')
```
and this is homeserver.log

```
2019-12-31 01:28:27,533 - twisted - 172 - INFO -  - Main loop terminated.
2019-12-31 01:28:27,534 - synapse.app.homeserver - 70 - WARNING -  - Stopping daemon.
2019-12-31 01:54:22,569 - twisted - 172 - INFO - None - Redirected stdout/stderr to logs
2019-12-31 01:54:22,569 - root - 237 - WARNING - None - ***** STARTING SERVER *****
2019-12-31 01:54:22,569 - root - 238 - WARNING - None - Server /root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py version 1.7.2
2019-12-31 01:54:22,569 - root - 239 - INFO - None - Server hostname: my_server_name
2019-12-31 01:54:22,570 - synapse.app.homeserver - 344 - INFO - None - Setting up server
2019-12-31 01:54:22,570 - synapse.server - 239 - INFO - None - Setting up.
2019-12-31 01:54:22,575 - synapse.storage.prepare_database - 301 - INFO - None - Upgrading schema to v56
2019-12-31 01:54:22,579 - synapse.storage.data_stores.main.event_push_actions - 499 - INFO - None - Searching for stream ordering 1 month ago
2019-12-31 01:54:22,579 - synapse.storage.data_stores.main.event_push_actions - 504 - INFO - None - Found stream ordering 1 month ago: it's 0
2019-12-31 01:54:22,580 - synapse.storage.data_stores.main.event_push_actions - 506 - INFO - None - Searching for stream ordering 1 day ago
2019-12-31 01:54:22,580 - synapse.storage.data_stores.main.event_push_actions - 511 - INFO - None - Found stream ordering 1 day ago: it's 0
2019-12-31 01:54:22,583 - synapse.server - 244 - INFO - None - Finished setting up.
2019-12-31 01:54:22,600 - synapse.app.homeserver - 615 - INFO - None - Scheduling stats reporting for 3 hour intervals
2019-12-31 01:54:22,611 - synapse.app.homeserver - 245 - WARNING -  - Starting daemon.
2019-12-31 01:54:22,611 - synapse.app.homeserver - 110 - INFO -  - Running
2019-12-31 01:54:22,611 - synapse.app.homeserver - 30 - INFO -  - Set file limit to: 1048576
2019-12-31 01:54:22,627 - synapse.federation.federation_server - 778 - INFO -  - Registering federation query handler for 'profile'
2019-12-31 01:54:22,629 - synapse.push.pusher - 42 - INFO -  - email enable notifs: False
2019-12-31 01:54:22,643 - synapse.federation.federation_server - 778 - INFO -  - Registering federation query handler for 'directory'
2019-12-31 01:54:22,648 - synapse.handlers.auth - 84 - INFO -  - Extra password_providers: []
2019-12-31 01:54:22,650 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'm.device_list_update'
2019-12-31 01:54:22,650 - synapse.federation.federation_server - 778 - INFO -  - Registering federation query handler for 'user_devices'
2019-12-31 01:54:22,669 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'm.presence'
2019-12-31 01:54:22,682 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'm.typing'
2019-12-31 01:54:22,686 - synapse.handlers.deactivate_account - 191 - INFO - user_parter_loop-0 - Starting user parter
2019-12-31 01:54:22,689 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'm.receipt'
2019-12-31 01:54:22,699 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'org.matrix.signing_key_update'
2019-12-31 01:54:22,699 - synapse.federation.federation_server - 778 - INFO -  - Registering federation query handler for 'client_keys'
2019-12-31 01:54:22,700 - synapse.federation.federation_server - 760 - INFO -  - Registering federation EDU handler for 'm.direct_to_device'
2019-12-31 01:54:22,732 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7fd8553d6240> to path b'/_matrix/client/api/v1'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7fd8553d6240> to path b'/_matrix/client/r0'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7fd8553d6240> to path b'/_matrix/client/unstable'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7fd8553d6240> to path b'/_matrix/client/v2_alpha'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.ClientRestResource object at 0x7fd8553d6240> to path b'/_matrix/client/versions'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.well_known.WellKnownResource object at 0x7fd854b46cf8> to path b'/.well-known/matrix/client'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.admin.AdminRestResource object at 0x7fd854b46e80> to path b'/_synapse/admin'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching FilePath('/root/synapse/env/lib/python3.6/site-packages/synapse/static') to path b'/_matrix/static'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7fd854b41358> to path b'/_matrix/media/r0'
2019-12-31 01:54:22,733 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v1.media_repository.MediaRepositoryResource object at 0x7fd854b41358> to path b'/_matrix/media/v1'
2019-12-31 01:54:22,734 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.media.v0.content_repository.ContentRepoResource object at 0x7fd854b617f0> to path b'/_matrix/content'
2019-12-31 01:54:22,734 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.federation.transport.server.TransportLayerServer object at 0x7fd854b4f5f8> to path b'/_matrix/federation'
2019-12-31 01:54:22,734 - synapse.util.httpresourcetree - 46 - INFO -  - Attaching <synapse.rest.key.v2.KeyApiV2Resource object at 0x7fd854b619b0> to path b'/_matrix/key/v2'
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  - Traceback (most recent call last):
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  -     skt.bind(addr)
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  - OSError: [Errno 98] Address already in use
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  -
2019-12-31 01:54:22,736 - twisted - 172 - ERROR -  - During handling of the above exception, another exception occurred:
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  - Traceback (most recent call last):
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 271, in start
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -     hs.start_listening(listeners)
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 267, in start_listening
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -     self._listening_services.extend(self._listener_http(config, listener))
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 153, in _listener_http
2019-12-31 01:54:22,737 - twisted - 172 - ERROR -  -     reactor=self.get_reactor(),
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 175, in listen_tcp
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -     check_bind_error(e, address, bind_addresses)
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/__init__.py", line 51, in check_bind_error
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -     raise e
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 173, in listen_tcp
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -     r.append(reactor.listenTCP(port, factory, backlog, address))
2019-12-31 01:54:22,738 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
2019-12-31 01:54:22,739 - twisted - 172 - ERROR -  -     p.startListening()
2019-12-31 01:54:22,739 - twisted - 172 - ERROR -  -   File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
2019-12-31 01:54:22,739 - twisted - 172 - ERROR -  -     raise CannotListenError(self.interface, self.port, le)
2019-12-31 01:54:22,739 - twisted - 172 - ERROR -  - twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:8008: [Errno 98] Address already in use.
2019-12-31 01:54:22,740 - synapse.handlers.deactivate_account - 201 - INFO - user_parter_loop-0 - User parter finished: stopping
2019-12-31 01:54:22,746 - synapse.handlers.presence - 238 - INFO - presence.on_shutdown-0 - Performing _on_shutdown. Persisting 0 unpersisted changes
2019-12-31 01:54:22,747 - synapse.handlers.presence - 249 - INFO - presence.on_shutdown-0 - Finished _on_shutdown
2019-12-31 01:54:22,811 - twisted - 172 - CRITICAL -  - Unhandled error in Deferred:
2019-12-31 01:54:22,812 - twisted - 172 - CRITICAL -  -
Traceback (most recent call last):
  File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1361, in startListening
    skt.bind(addr)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 271, in start
    hs.start_listening(listeners)
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 267, in start_listening
    self._listening_services.extend(self._listener_http(config, listener))
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 153, in _listener_http
    reactor=self.get_reactor(),
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 175, in listen_tcp
    check_bind_error(e, address, bind_addresses)
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/__init__.py", line 51, in check_bind_error
    raise e
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 173, in listen_tcp
    r.append(reactor.listenTCP(port, factory, backlog, address))
  File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 127.0.0.1:8008: [Errno 98] Address already in use.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/homeserver.py", line 413, in start
    _base.start(hs, config.listeners)
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/app/_base.py", line 281, in start
    sys.exit(1)
SystemExit: 1
2019-12-31 01:54:22,826 - twisted - 172 - INFO -  - Main loop terminated.
2019-12-31 01:54:22,827 - synapse.app.homeserver - 70 - WARNING -  - Stopping daemon.
```

How to solve it? thank you!

**Comment by turt2live** [comment]
Synapse is already running somewhere and you need to stop it. Restarting the whole machine usually helps as a quick way to deal with this.

For future support, please visit #synapse:matrix.org

**Comment by hgy987654** [comment]
> Synapse is already running somewhere and you need to stop it. Restarting the whole machine usually helps as a quick way to deal with this.
> 
> For future support, please visit #synapse:matrix.org

Thank , I solved it!

**Comment by ehsanasgari** [comment]
Hi there, does it mean that we cannot have two separate synapses on the same server? I am getting the same error.

**Comment by ShadowJonathan** [comment]
No you cannot, you can only run 1 process which is "binding" to that `:8008` port.

That said, you *can* run multiple "containers" of synapse, and use a reverse proxy / loadbalancer to distribute load between the processes, but that's a whole different process (see [workers.md](https://github.com/matrix-org/synapse/blob/develop/docs/workers.md) for more information)
