### ISSUE TITLE
exception Failed handle request via 'JoinRoomAliasServlet' when attempting to join `!6DBPGS7a3qsI0sKcWB:zemos.net`

### ISSUE THREAD

**Issue by grinapo** [matrix-org/synapse#6680]
- **Homeserver**: grin.hu
- **Version**: synapse v1.7.1
- **Platform**: Debian/Linux amd64

```
2019-12-22 10:02:33,778 - synapse.http.server - 109 - ERROR - POST-497953- Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0x7f7af8932208 method='POST' uri='/_matrix/client/r0/join/!6DBPGS7a3
qsI0sKcWB%3Azemos.net' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/events/__init__.py", line 125, in getter
    return self._event_dict[key]
KeyError: 'auth_events'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/usr/lib/python3/dist-packages/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/usr/lib/python3/dist-packages/synapse/rest/client/v1/room.py", line 309, in on_POST
    third_party_signed=content.get("third_party_signed", None),
AttributeError: auth_events
```

Cut from #3374 .

**Comment by richvdh** [comment]
crash = "it stopped running": afaict this is not the case.

**Comment by ktpx** [comment]
ANything on this? Having same issue..

**Comment by rkokkelk** [comment]
Unfortunately I still have this issue, I can't seem to join public rooms anymore. The only public room I was able to join since this issue was very small, only 5 users in the rooms.


_Subset of logs, relevant to join the room_:
```
2022-07-04 11:42:21,319 - synapse.http.matrixfederationclient - 298 - INFO - GET-188265 - {GET-O-5810} [matrix.org] Completed request: 200 OK in 0.93 secs, got 69 bytes - GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23freenode_%23zabbix%3Amatrix.org

2022-07-04 11:42:21,340 - synapse.access.http.8008 - 450 - INFO - GET-188265 - 10.0.1.20 - 8008 - {None} Processed request: 0.946sec/0.002sec (0.003sec, 0.006sec) (0.001sec/0.014sec/1) 69B 200 "GET /_matrix/client/r0/directory/room/%23freenode_%23zabbix%3Amatrix.org HTTP/1.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0" [0 dbevts]

2022-07-04 11:42:21,742 - synapse.http.matrixfederationclient - 298 - INFO - POST-188267 - {GET-O-5811} [matrix.org] Completed request: 200 OK in 0.25 secs, got 69 bytes - GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23freenode_%23zabbix%3Amatrix.org

2022-07-04 11:44:26,976 - synapse.http.server - 183 - ERROR - POST-188267 - Failed handle request via 'JoinRoomAliasServlet': <XForwardedForRequest at 0xffff5848bbe0 method='POST' uri='/_matrix/client/r0/join/%23freenode_%23zabbix%3Amatrix.org?server_name=matrix.org' clientproto='HTTP/1.1' site='8008'>

2022-07-04 11:44:27,064 - synapse.access.http.8008 - 450 - INFO - POST-188267 - 10.0.1.20 - 8008 - {@roy=7d:matrix.xseth.nl} Processed request: 125.569sec/0.002sec (48.823sec, 0.518sec) (0.603sec/3.200sec/88) 55B 500 "POST /_matrix/client/r0/join/%23freenode_%23zabbix%3Amatrix.org?server_name=matrix.org HTTP/1.1" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0" [84 dbevts]
```

**Comment by richvdh** [comment]
> Unfortunately I still have this issue,

Unless your logs include the `AttributeError: auth_events`, you don't have this issue. 

More likely you are just seeing timeouts - joining rooms over federation is known to be slow (#1211) - but if you're sure it's not that, open a new issue and include all the logs.

**Comment by rkokkelk** [comment]
Ah thanks, I searched for issues with `Failed handle request via 'JoinRoomAliasServlet'` and only 2 results came up, this being one of them. My first thought was also that it is probably due to timeouts but the issue is that I've found no configuration which I can use to improve this, that's why I ended up here.
