### ISSUE TITLE
Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "current_state_events_event_id_key"

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6692]
I'm getting the following exception every few seconds on my server:

```
2020-01-12 23:11:29,786 - synapse.metrics.background_process_metrics - 214 - ERROR - send_dummy_events_to_fill_extremities-306- Background process 'send_dummy_events_to_fill_extremities' threw an exception
Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 212, in run
    return (yield result)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/message.py", line 1071, in _send_dummy_events_to_fill_extremities
    requester, event, context, ratelimit=False
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/message.py", line 656, in send_nonmember_event
    requester=requester, event=event, context=context, ratelimit=ratelimit
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/util/metrics.py", line 82, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/message.py", line 846, in handle_new_client_event
    requester, event, context, ratelimit=ratelimit, extra_users=extra_users
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/message.py", line 996, in persist_and_notify_client_event
    event, context=context
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/persist_events.py", line 247, in persist_event
    yield make_deferred_yieldable(deferred)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/persist_events.py", line 147, in handle_queue_loop
    ret = yield per_item_callback(item)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/persist_events.py", line 257, in persisting_queue
    item.events_and_contexts, backfilled=item.backfilled
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/persist_events.py", line 412, in _persist_events
    backfilled=backfilled,
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py", line 88, in f
    res = yield func(self, *args, delete_existing=True, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py", line 215, in _persist_events_and_state_updates
    new_forward_extremeties=new_forward_extremeties,
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 456, in runInteraction
    **kwargs
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 504, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 501, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 339, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/logging/utils.py", line 79, in wrapped
    return f(*args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py", line 465, in _persist_events_txn
    self._update_current_state_txn(txn, state_delta_for_room, min_stream_order)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/data_stores/main/events.py", line 546, in _update_current_state_txn
    for key, ev_id in iteritems(to_insert)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 145, in executemany
    self._do_execute(self.txn.executemany, sql, *args)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/database.py", line 168, in _do_execute
    return func(sql, *args)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "current_state_events_event_id_key"
DETAIL:  Key (event_id)=($15528448292995604HGhyJ:matrix.org) already exists.
```

However, I'm not entirely sure this is related to dummy events, as the same error occurs when receiving federation transactions:

```
2020-01-12 23:37:27,901 - synapse.federation.transport.server - 389 - INFO - PUT-180175- Received txn 1578067853420 from halogen.city. (PDUs: 0, EDUs: 1)
2020-01-12 23:37:27,910 - synapse.federation.federation_server - 246 - ERROR - PUT-178435-$YfV5J5yL9h1VVhGDB9jztB2v7UVDjFSzk2DfPOD2gWM- Failed to handle PDU $YfV5J5yL9h1VVhGDB9jztB2v7UVDjFSzk2DfPOD2gWM
Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 235, in process_pdus_for_room
    await self._handle_received_pdu(origin, pdu)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 634, in _handle_received_pdu
    await self.handler.on_receive_pdu(origin, pdu, sent_to_us_directly=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'psycopg2.errors.UniqueViolation'>: duplicate key value violates unique constraint "current_state_events_event_id_key"
DETAIL:  Key (event_id)=($0qvIz9KeFY05AmzfYJsItOY6CDHOht0Z6l33-88tYMM) already exists.
```

`$0qvIz9KeFY05AmzfYJsItOY6CDHOht0Z6l33-88tYMM` being:

```
synapse=# select * from events where event_id = '$0qvIz9KeFY05AmzfYJsItOY6CDHOht0Z6l33-88tYMM';
 stream_ordering | topological_ordering |                   event_id                   |     type      |            room_id             | content | unrecognized_keys | processed | outlier | depth  | origin_server_ts |  received_ts  |            sender            | contains_url 
-----------------+----------------------+----------------------------------------------+---------------+--------------------------------+---------+-------------------+-----------+---------+--------+------------------+---------------+------------------------------+--------------
         5837523 |               173517 | $0qvIz9KeFY05AmzfYJsItOY6CDHOht0Z6l33-88tYMM | m.room.member | !YynUnYHpqlHuoTAjsp:matrix.org |         |                   | t         | f       | 173517 |    1578773940068 | 1578774103290 | @_freenode_jgrulich_:kde.org | f
```

I don't seem to be noticing a whole lot of breakage on my server other than a few UTDs, but that may be due to something else.

Synapse v1.7.3

**Comment by brrrrrrrt** [comment]
same here with synapse v1.8.0

it looks like the affected rooms do not work anymore, i get the userlist, but no content.
everytime i access such a room, those duplicate key errors appear in the log

**Comment by anoadragon453** [comment]
This may've been related to my other issue: #6696, which was a result of duplicate rows in `current_state_events`. Possibly as a result of migrating my database improperly and ending up with multiple duplicate rows.

If anyone else if facing this problem (@brrrrrrrt), I'd recommend taking a database backup, remove duplicate rows from the appropriate tables and going from there.

**Comment by brrrrrrrt** [comment]
> If anyone else if facing this problem (@brrrrrrrt), I'd recommend taking a database backup, remove duplicate rows from the appropriate tables and going from there.

ok, i did a database backup, there were so many duplicate entries i wrote a script which automates it:
it extracts the last duplicate id from the logfile, and deletes the entry from the database if it has not been already deleted. loops until there are no more such entries in the logfile (forever).

i know thats a crazy approach, but it helped me to get the chathistory on rooms up again:

**WARNING** this is just a testscript, it may hose your database, it uses german strings, do not just copy&paste&run !
```
#!/bin/bash

while [ `grep -c "existiert bereits" /var/log/matrix-synapse/homeserver.log` -gt 0 ]; do
        # get the last id
        str=`egrep "DETAIL:  Schlüssel.*event_id.*existiert bereits" /var/log/matrix-synapse/homeserver.log| tail -n 1 | sed 's/.*event_id.=..//' | sed 's/)«.*//'`                                                                            

        # strip "-" if it is the first character to make grep $str work
        if [[ $str = -* ]]; then
                str=`echo $str | cut -c 2-`
        fi

        # exit if $str is empty 
        if [ "$str" == '' ]; then
                exit
        fi

        #check if already deleted
        if [ `grep -c "$str" /tmp/deleted` -eq 0 ]; then
                echo "$str" >> /tmp/deleted
                # delete from DB
                echo "delete from event_relations where event_id like '%$str%'" | sudo -u postgres psql name_of_the_database
                echo $str
        fi
        sleep 1
done

```

still not sure what caused the duplicates, i activated retention and it looks like it deleted events, but did not delete entries from event_relations, but thats just a guess...

**Comment by richvdh** [comment]
@brrrrrrrt make sure you read https://github.com/matrix-org/synapse/issues/6696#issuecomment-575280941
