### ISSUE TITLE
/_matrix/key/v2/query: 'NoneType' object has no attribute 'registerProducer'

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6700]
### Description

A traceback I saw while skimming my logs:

```
2020-01-14 15:02:13,505 - synapse.http.server - 109 - ERROR - POST-48708- Failed handle request via 'RemoteKey': <XForwardedForRequest at 0x7f0fa40a9f60 method='POST' uri='/_matrix/key/v2/query' clientproto='HTTP/1.1' site=8008>
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {('mtrx.pro-i-l.de', 'ed25519:a_lehF', None): [{'key_id': 'ed25519:a_lehF', 'from_server': 'matrix.org', 'ts_added_ms': 1576922916596, 'ts_valid_until_ms': 1576921056903, 'key_json': <memory at 0x7f1111544108>}, {'key_id': 'ed25519:a_lehF', 'from_serve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {('mtrx.pro-i-l.de', 'ed25519:a_lehF', None): [{'key_id': 'ed25519:a_lehF', 'from_server': 'matrix.org', 'ts_added_ms': 1576922916596, 'ts_valid_until_ms': 1576921056903, 'key_json': <memory at 0x7f1111544108>}, {'key_id': 'ed25519:a_lehF', 'from_serve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/rest/key/v2/remote_key_resource.py", line 125, in _async_render_POST
    await self.query_keys(request, query, query_remote_on_cache_miss=True)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/rest/key/v2/remote_key_resource.py", line 230, in query_keys
    respond_with_json_bytes(request, 200, encode_canonical_json(results))
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/http/server.py", line 507, in respond_with_json_bytes
    producer.start()
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/web/static.py", line 765, in start
    self.request.registerProducer(self, False)
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/twisted/web/http.py", line 986, in registerProducer
    self.channel.registerProducer(producer, streaming)
AttributeError: 'NoneType' object has no attribute 'registerProducer'
```

Not sure if this is a bug or a fluke with a broken connection.

### Version information

Synapse v1.8.0 via pip

**Comment by richvdh** [comment]
I think this is a dup of #5304

**Comment by richvdh** [comment]
ok, it's not quite, but it's closely related

**Comment by richvdh** [comment]
I've explained what I think is going on here at https://github.com/matrix-org/synapse/issues/5304#issuecomment-574740003, but am going to leave this open too to track the fact that it probably needs fixing in both places.

The trivial fix here is to add `if request._disconnected: return` to `respond_with_json_bytes`.

(the error is harmless except for the noise in the log, and that the other end has timed out)

**Comment by richvdh** [comment]
also, the fact that you're seeing this error means that someone is using your server as a key notary, which is an interesting choice.

**Comment by anoadragon453** [comment]
> also, the fact that you're seeing this error means that someone is using your server as a key notary, which is an interesting choice.

Indeed...
