### ISSUE TITLE
/auth/m.login.terms/fallback/web: KeyError: 'session'

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#6703]
### Description

We're getting a traceback on matrix.org whenever someone tries to use the terms web fallback API:

```
2020-01-14 14:19:53,169 - synapse.access.http.8080 - 233 - INFO - POST-1176632 - 93.241.62.202 - 8080 - Received request: POST /_matrix/client/r0/auth/m.login.terms/fallback/web
2020-01-14 14:19:53,169 - synapse.http.server - 109 - ERROR - POST-1176632 - Failed handle request via 'AuthRestServlet': <XForwardedForRequest at 0x7fecb71c5860 method='POST' uri='/_matrix/client/r0/auth/m.login.terms/fallback/web' clientproto='HTTP/1.1' site=8080>
Capture point (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/synapse/src/synapse/app/homeserver.py", line 639, in <module>
    main()
  File "/home/synapse/src/synapse/app/homeserver.py", line 635, in main
    run(hs)
  File "/home/synapse/src/synapse/app/homeserver.py", line 626, in run
    logger=logger,
  File "/home/synapse/src/synapse/app/_base.py", line 137, in start_reactor
    daemon.start()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/home/synapse/src/synapse/app/_base.py", line 114, in run
    run_command()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1295, in mainLoop
    self.doIteration(t)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2985, in dataReceived
    return self._channel.dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2266, in dataReceived
    return basic.LineReceiver.dataReceived(self, data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/protocols/basic.py", line 579, in dataReceived
    why = self.rawDataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2273, in rawDataReceived
    self._transferDecoder.dataReceived(data)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 1754, in dataReceived
    finishCallback(data[contentLength:])
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2170, in _finishRequestBody
    self.allContentReceived()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 2245, in allContentReceived
    req.requestReceived(command, path, version)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/http.py", line 945, in requestReceived
    self.process()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/server.py", line 235, in process
    self.render(resrc)
  File "/home/synapse/src/synapse/http/site.py", line 132, in render
    Request.render(self, resrc)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/web/server.py", line 302, in render
    body = resrc.render(self)
  File "/home/synapse/src/synapse/http/server.py", line 298, in render
    defer.ensureDeferred(self._async_render(request))
  File "/home/synapse/src/synapse/logging/context.py", line 560, in g
    return run_in_background(f, *args, **kwargs)
  File "/home/synapse/src/synapse/logging/context.py", line 591, in run_in_background
    res = defer.ensureDeferred(res)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
    return _cancellableInlineCallbacks(coro)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/src/synapse/http/server.py", line 204, in wrapped_async_request_handler
    await h(self, request)
Traceback (most recent call last):
  File "/home/synapse/src/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/home/synapse/src/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/home/synapse/src/synapse/rest/client/v2_alpha/auth.py", line 212, in on_POST
    session = request.args["session"][0]
KeyError: 'session'
```

### Version information

Synapse v1.8.0

**Comment by anoadragon453** [comment]
Fixed in https://github.com/matrix-org/synapse/pull/6702
