### ISSUE TITLE
M_FORBIDDEN: "No create event in auth events" from createRoom

### ISSUE THREAD

**Issue by hannojg** [matrix-org/synapse#6721]
### Description
Sometimes when I request `/createRoom` shortly after a registration request (currenlty doing some test with JMeter, and there is just a pause of some hundreds of millisecs.) I get a strange response: 
```
{"errcode":"M_FORBIDDEN","error":"No create event in auth events"}
```

What's even more strange is, that it seems, that the user still joins the room...

### Steps to reproduce

- Run a registration 
- Use the returned auth token and create the first room
- The request I use looks like this:
```
POST https://matrix.myserver.tld/_matrix/client/r0/createRoom

POST data:
{
  "room_alias_name": "ajnDtCodKuxehXtqLwhpkuxgxVsijVCHaoAQaoICpTRBrfGtlZJZ",
  "preset": "trusted_private_chat",
  "is_direct": true,
  "visibility": "private",
  "invite": ["@ddkbjyscljjhosmzgn:cuvent.de"],
  "creation_content": {
    "m.federate": false
  }
}
```

What I can see from the logs:
```
Postgres:
Jan 16 21:05:24  matrix-postgres[8981]: 2020-01-16 20:05:24.247 UTC [56] ERROR:  ON CONFLICT DO UPDATE command cannot affect row a second time
Jan 16 21:05:24  matrix-postgres[8981]: 2020-01-16 20:05:24.247 UTC [56] HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
Jan 16 21:05:24  matrix-postgres[8981]: 2020-01-16 20:05:24.247 UTC [56] STATEMENT:  INSERT INTO room_stats_historical (room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, total_events, total_event_bytes, end_ts, bucket_size) SELECT room_id, current_state_events, joined_members, invited_members, left_members, banned_members, local_users_in_room, 8, 6835, 1579219200000, 86400000 FROM room_stats_current WHERE room_id = '!dRIstBAkEQNsHQOoYF:MYSERVER' ON CONFLICT (room_id, end_ts) DO UPDATE SET current_state_events = EXCLUDED.current_state_events, joined_members = EXCLUDED.joined_members, invited_members = EXCLUDED.invited_members, left_members = EXCLUDED.left_members, banned_members = EXCLUDED.banned_members, local_users_in_room = EXCLUDED.local_users_in_room, total_events = EXCLUDED.total_events + room_stats_historical.total_events, total_event_bytes = EXCLUDED.total_event_bytes + room_stats_historical.total_event_bytes

Synapse:
Jan 16 21:05:24 matrix-synapse[9102]: 2020-01-16 20:05:24,783 - synapse.metrics.background_process_metrics - 214 - ERROR - stats.notify_new_event-857 - Background process 'stats.notify_new_event' threw an exception
Jan 16 21:05:24 matrix-synapse[9102]: Traceback (most recent call last):
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 212, in run
Jan 16 21:05:24 matrix-synapse[9102]:     return (yield result)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 16 21:05:24 matrix-synapse[9102]:     result = result.throwExceptionIntoGenerator(g)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 16 21:05:24 matrix-synapse[9102]:     return g.throw(self.type, self.value, self.tb)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/stats.py", line 74, in process
Jan 16 21:05:24 matrix-synapse[9102]:     yield self._unsafe_process()
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 16 21:05:24 matrix-synapse[9102]:     result = result.throwExceptionIntoGenerator(g)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 16 21:05:24 matrix-synapse[9102]:     return g.throw(self.type, self.value, self.tb)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/stats.py", line 131, in _unsafe_process
Jan 16 21:05:24 matrix-synapse[9102]:     stream_id=max_pos,
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 16 21:05:24 matrix-synapse[9102]:     result = result.throwExceptionIntoGenerator(g)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 16 21:05:24 matrix-synapse[9102]:     return g.throw(self.type, self.value, self.tb)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 495, in runInteraction
Jan 16 21:05:24 matrix-synapse[9102]:     **kwargs
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 16 21:05:24 matrix-synapse[9102]:     result = result.throwExceptionIntoGenerator(g)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 16 21:05:24 matrix-synapse[9102]:     return g.throw(self.type, self.value, self.tb)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 543, in runWithConnection
Jan 16 21:05:24 matrix-synapse[9102]:     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
Jan 16 21:05:24 matrix-synapse[9102]:     result = inContext.theWork()
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Jan 16 21:05:24 matrix-synapse[9102]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
Jan 16 21:05:24 matrix-synapse[9102]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
Jan 16 21:05:24 matrix-synapse[9102]:     return func(*args,**kw)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Jan 16 21:05:24 matrix-synapse[9102]:     compat.reraise(excValue, excTraceback)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
Jan 16 21:05:24 matrix-synapse[9102]:     raise exception.with_traceback(traceback)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Jan 16 21:05:24 matrix-synapse[9102]:     result = func(conn, *args, **kw)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 540, in inner_func
Jan 16 21:05:24 matrix-synapse[9102]:     return func(conn, *args, **kwargs)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 378, in new_transaction
Jan 16 21:05:24 matrix-synapse[9102]:     r = func(cursor, *args, **kwargs)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/stats.py", line 345, in _bulk_update_stats_delta_txn
Jan 16 21:05:24 matrix-synapse[9102]:     complete_with_stream_id=stream_id,
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/stats.py", line 463, in _update_stats_delta_txn
Jan 16 21:05:24 matrix-synapse[9102]:     copy_columns=abs_field_names,
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/stats.py", line 615, in _upsert_copy_from_table_with_additive_relatives_txn
Jan 16 21:05:24 matrix-synapse[9102]:     txn.execute(sql, qargs)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 175, in execute
Jan 16 21:05:24 matrix-synapse[9102]:     self._do_execute(self.txn.execute, sql, *args)
Jan 16 21:05:24 matrix-synapse[9102]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 201, in _do_execute
Jan 16 21:05:24 matrix-synapse[9102]:     return func(sql, *args)
Jan 16 21:05:24 matrix-synapse[9102]: psycopg2.errors.CardinalityViolation: ON CONFLICT DO UPDATE command cannot affect row a second time
Jan 16 21:05:24 matrix-synapse[9102]: HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
```

### Version information

- **Homeserver**:
Self-hosted

- **Version**:
```
{
  "server_version": "1.8.0", 
  "python_version": "3.7.6"
}
```

- **Install method**:
ansible docker deploy method

- **Platform**:
Ubuntu 18.04 running on VServer, using Docker

**Comment by richvdh** [comment]
the CardinalityViolation is from the background process which updates the room stats. It may be a problem in itself, but it's unlikely to cause this issue.

It sounds like a race condition of some sort. INFO-level logs for the `createRoom` request would be helpful. See https://github.com/matrix-org/synapse/wiki#how-can-i-find-the-lines-corresponding-to-a-given-http-request-in-my-homeserver-log.
