### ISSUE TITLE
Sync request fails with simplejson.errors.JSONDecodeError

### ISSUE THREAD

**Issue by freaktechnik** [matrix-org/synapse#6725]
### Description

I wanted to try out RiotX, however it never managed to sync data. I eventually looked at the Synapse logs and saw it was repeatedly logging (exactly) the same error:

```
Jan 16 22:42:41 gateway synapse[20358]: synapse.http.server: [GET-332193] Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x69899190 method='GET' uri='/_matrix/client/r0/sync?filter=6&timeout=0' clientproto='HTTP/1.1' site=8008>
                                        Traceback (most recent call last):
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
                                            result = g.send(result)
                                        StopIteration: {a bunch of raw messages go here, let me know what parts of them may be of interest}

                                        During handling of the above exception, another exception occurred:

                                        Traceback (most recent call last):
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
                                            await h(self, request)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/http/server.py", line 326, in _async_render
                                            callback_return = await callback_return
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/rest/client/v2_alpha/sync.py", line 178, in on_GET
                                            full_state=full_state,
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 263, in wait_for_sync_for_user
                                            full_state,
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 285, in _wait_for_sync_for_user
                                            sync_config, since_token, full_state=full_state
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 956, in generate_sync_result
                                            sync_result_builder, account_data_by_room
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 1367, in _generate_sync_entry_for_rooms
                                            await concurrently_execute(handle_room_entries, room_entries, 10)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/util/async_helpers.py", line 155, in _concurrently_execute_inner
                                            await maybe_awaitable(func(next(it)))
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 1762, in _generate_room_entry
                                            newly_joined_room=newly_joined,
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/handlers/sync.py", line 455, in _load_filtered_recents
                                            room_id, limit=load_limit + 1, end_token=end_key
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/storage/data_stores/main/stream.py", line 486, in get_recent_events_for_room
                                            [r.event_id for r in rows], get_prev_content=True
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/storage/data_stores/main/events_worker.py", line 271, in get_events_as_list
                                            set(event_ids), allow_rejected=allow_rejected
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                            result = result.throwExceptionIntoGenerator(g)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
                                            return g.throw(self.type, self.value, self.tb)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/storage/data_stores/main/events_worker.py", line 418, in _get_events_from_cache_or_db
                                            missing_events_ids, allow_rejected=allow_rejected
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
                                            result = g.send(result)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/synapse/storage/data_stores/main/events_worker.py", line 574, in _get_events_from_db
                                            d = json.loads(row["json"])
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/simplejson/__init__.py", line 538, in loads
                                            return _default_decoder.decode(s)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
                                            obj, end = self.raw_decode(s)
                                          File "/home/pi/synapse/env/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
                                            return self.scan_once(s, idx=_w(s, idx).end())
                                        simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps to reproduce

- have some specific messages in your account
- try to set up a new client like RiotX

### Version information

- **Homeserver**: im.humanoids.be:8448

If not matrix.org:

- **Version**: 1.8.0

- **Install method**: pip

- **Platform**: Raspbian (Raspberry Pi, don't judge, it works) - synapse runs without TLS, TLS is added via apache proxy (thus also the port mismatch from the error to the public port). Database is PostgreSQL, which I recently migrated from SQLite with the official migration script around the time it was first declared stable.

**Comment by freaktechnik** [comment]
From  a closer look at the messages they appear to be from a conversation with @appservice-irc:matrix.org

**Comment by lfaraone** [comment]
I'm having the same issue on 1.8.0+xenial1, which looks to be related to https://github.com/matrix-org/synapse/issues/6605#issuecomment-569805497 , but that patch is included in 1.8.0, and the issue persists. cc @turt2live

**Comment by brandoncurtis** [comment]
I think I just spent the evening attempting to debug this same issue.

- present in 1.8.0 and 1.7.3.
- postgresql 11
- Ubuntu 18.04
- python 3.6

Anything that hits `/_matrix/client/r0/sync`... will trigger this, including `send_dummy_events_to_fill_extremities` if the server is sitting idle with no clients:

```
2020-01-18 18:48:37,422 - synapse.state - 495 - INFO - send_dummy_events_to_fill_extremities-0- Resolving state for !cURbafjkfsMDVwdRDQ:matrix.org with 10 groups
2020-01-18 18:48:37,430 - synapse.state - 518 - INFO - send_dummy_events_to_fill_extremities-0- Resolving conflicted state for '!cURbafjkfsMDVwdRDQ:matrix.org'
2020-01-18 18:48:37,596 - synapse.state.v1 - 79 - INFO - send_dummy_events_to_fill_extremities-0- Asking for 9132/9132 conflicted events
2020-01-18 18:48:38,707 - synapse.metrics.background_process_metrics - 214 - ERROR - send_dummy_events_to_fill_extremities-0- Background process 'send_dummy_events_to_fill_extremities' threw an exception
Traceback (most recent call last):
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$152231757428408OhOMC:matrix.org': {'event_id': '$152231757428408OhOMC:matrix.org',

Traceback (most recent call last):
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/federation/sender/__init__.py", line 408, in send_presence
    yield self._process_presence_inner(list(states_map.values()))
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/util/metrics.py", line 82, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/federation/sender/__init__.py", line 440, in _process_presence_inner
    hosts_and_states = yield get_interested_remotes(self.store, states, self.state)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/handlers/presence.py", line 1322, in get_interested_remotes
    hosts = yield state_handler.get_current_hosts_in_room(room_id)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/state/__init__.py", line 199, in get_current_hosts_in_room
    return (yield self.get_hosts_in_room_at_events(room_id, event_ids))
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/state/__init__.py", line 212, in get_hosts_in_room_at_events
    entry = yield self.resolve_state_groups_for_events(room_id, event_ids)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/util/metrics.py", line 82, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/state/__init__.py", line 402, in resolve_state_groups_for_events
    state_res_store=StateResolutionStore(self.store),
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/state/__init__.py", line 525, in resolve_state_groups
    state_res_store=state_res_store,
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/brandon/repo/synapse/.venv/lib/python3.6/site-packages/synapse/state/v1.py", line 93, in resolve_events_with_store
    % (room_id, event.event_id, event.room_id,)

Exception: Attempting to state-resolve for room !cURbafjkfsMDVwdRDQ:matrix.org with event $15038575082050669IRCkf:matrix.org which is in !xPRJVyOhRymgpkarYZ:matrix.org
```

or the initial sync request when I try to log in.

**Comment by richvdh** [comment]
@freaktechnik interesting, it looks like there is a corrupt event in your database. Any idea which it is? More logs will probably give more clues.

@brandoncurtis your error looks unrelated (the StopIteration is a red herring): please open a separate issue with more complete logs.

**Comment by freaktechnik** [comment]
I finally got some more time to look at the individual messages. One of them has a hex encoded json field (I've checked the hex encoded contents, I don't think there's anything sensitive in there, at least that I know of):
```python
{
    [...]
    '$15554202151983LjVRc:humanoids.be': {
        'format_version': 1,
        'json': '\\x7b22617574685f6576656e7473223a5b5b222431353437313134373437313536343566526e70423a6d61747269782e6f7267222c7b22736861323536223a22796c7a6b4d314f4f552f47475a687342567530714e536b54635732596d623244504f4c5a32507736503238227d5d2c5b2224313534373131363535363834474a4364533a68756d616e6f6964732e6265222c7b22736861323536223a22784831717a50384b456f36324e6c7162664c4c595139567668414776695637615a4a4e64576b7866354d77227d5d2c5b22243135343731313437343731353634376e616e476d3a6d61747269782e6f7267222c7b22736861323536223a226d376a667a5159314470497350453942577a496338635858775454676148466b56727947617a3777687938227d5d5d2c22636f6e74656e74223a7b7d2c226465707468223a34352c226576656e745f6964223a222431353535343230323135313938334c6a5652633a68756d616e6f6964732e6265222c22686173686573223a7b22736861323536223a226f50303575625a5658515a59685872546475555465386d54556f38665077366d53432b54446f6547694334227d2c226f726967696e223a2268756d616e6f6964732e6265222c226f726967696e5f7365727665725f7473223a313535353432303231353038322c22707265765f6576656e7473223a5b5b2224313535353431353633313835303143617474543a6d61747269782e6f7267222c7b22736861323536223a226e56454435774a4764622f5a466b5953734e3472506e6c4349505962746c4c672b4979664b4630624d6c41227d5d5d2c22707265765f7374617465223a5b5d2c22726f6f6d5f6964223a22214554456f5979736f786944516244505551773a6d61747269782e6f7267222c2273656e646572223a2240667265616b746563686e696b3a68756d616e6f6964732e6265222c227369676e617475726573223a7b2268756d616e6f6964732e6265223a7b22656432353531393a615f57425769223a226b567579494f672f43434938384c54615a42576934703644336258636f6d70354c514b68316f59614a3345545455696f39435943636445583134783774566a6c31306f38497a4d4474355972336337664d7a43764441227d7d2c2274797065223a226d2e726f6f6d2e6d657373616765222c22756e7369676e6564223a7b226167655f7473223a313535353432303231353038327d7d',
        'internal_metadata': '{"token_id": 321, "txn_id": "m1555420214865.1", "stream_ordering": 152665}',
        'redactions': ['$15555091052170qCznC:humanoids.be'],
        'event_id': '$15554202151983LjVRc:humanoids.be',
        'rejected_reason': None
    },
    [...]
}
```

**Comment by freaktechnik** [comment]
Finally got through all of the dumped messages. I've posted them [here](https://gist.github.com/freaktechnik/807aec82410198388b7f41821ef35593) with slightly formatted JSON sections, so it is no longer exactly the same formatting as in the error report (primarily additional whitespace and removed ')

**Comment by richvdh** [comment]
>         `'json': '\\x7b22617574685f6576656e7473223a5b5b222431353437313134373437313536343566526e70423a6d61747269782e6f7267222c7b22736861323536223a22796c7a6b4d314f4f552f47475a687342567530714e536b54635732596d623244504f4c5a32507736503238227d5d2c5b2224313534373131363535363834474a4364533a68756d616e6f6964732e6265222c7b22736861323536223a22784831717a50384b456f36324e6c7162664c4c595139567668414776695637615a4a4e64576b7866354d77227d5d2c5b22243135343731313437343731353634376e616e476d3a6d61747269782e6f7267222c7b22736861323536223a226d376a667a5159314470497350453942577a496338635858775454676148466b56727947617a3777687938227d5d5d2c22636f6e74656e74223a7b7d2c226465707468223a34352c226576656e745f6964223a222431353535343230323135313938334c6a5652633a68756d616e6f6964732e6265222c22686173686573223a7b22736861323536223a226f50303575625a5658515a59685872546475555465386d54556f38665077366d53432b54446f6547694334227d2c226f726967696e223a2268756d616e6f6964732e6265222c226f726967696e5f7365727665725f7473223a313535353432303231353038322c22707265765f6576656e7473223a5b5b2224313535353431353633313835303143617474543a6d61747269782e6f7267222c7b22736861323536223a226e56454435774a4764622f5a466b5953734e3472506e6c4349505962746c4c672b4979664b4630624d6c41227d5d5d2c22707265765f7374617465223a5b5d2c22726f6f6d5f6964223a22214554456f5979736f786944516244505551773a6d61747269782e6f7267222c2273656e646572223a2240667265616b746563686e696b3a68756d616e6f6964732e6265222c227369676e617475726573223a7b2268756d616e6f6964732e6265223a7b22656432353531393a615f57425769223a226b567579494f672f43434938384c54615a42576934703644336258636f6d70354c514b68316f59614a3345545455696f39435943636445583134783774566a6c31306f38497a4d4474355972336337664d7a43764441227d7d2c2274797065223a226d2e726f6f6d2e6d657373616765222c22756e7369676e6564223a7b226167655f7473223a313535353432303231353038327d7d'`

Yes, so this is the problem, and is likely caused by https://github.com/matrix-org/synapse/issues/5312.

**Comment by freaktechnik** [comment]
I ran the command at the very end of #5312 and it updated 184 records... But that fixed it. Thanks!
