### ISSUE TITLE
Failed to enable key backup

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/synapse#6726]
### Description

I tried to connect a new device, running Riot 1.5.7, to my existing key backup. Riot showed a spinner for several minutes so I checked the browser console which said `rageshake.js:104 No usable key backup: not enabling key backup`.

Checking the Synapse logs showed a bunch of errors like:
```
Jan 17 01:42:47 ubuntu matrix-synapse[20428]: 2020-01-17 01:42:47,380 - synapse.http.server - 109 - ERROR - POST-407365 - Failed handle request via 'OneTimeKeyServlet': <XForwardedForRequest at 0x7f5e44b91dd0 method='POST' uri='/_matrix/client/r0/keys/claim' clientproto='HTTP/1.1' site=8008>
Jan 17 01:42:47 ubuntu matrix-synapse[20428]: Traceback (most recent call last):
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     await h(self, request)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 326, in _async_render
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     callback_return = await callback_return
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/keys.py", line 233, in on_POST
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = await self.e2e_keys_handler.claim_one_time_keys(body, timeout)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = result.throwExceptionIntoGenerator(g)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return g.throw(self.type, self.value, self.tb)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/e2e_keys.py", line 399, in claim_one_time_keys
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     results = yield self.store.claim_e2e_one_time_keys(local_query)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = result.throwExceptionIntoGenerator(g)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return g.throw(self.type, self.value, self.tb)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 495, in runInteraction
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     **kwargs
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = result.throwExceptionIntoGenerator(g)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return g.throw(self.type, self.value, self.tb)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 543, in runWithConnection
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = inContext.theWork()
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return func(*args,**kw)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     compat.reraise(excValue, excTraceback)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     raise exception.with_traceback(traceback)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     result = func(conn, *args, **kw)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 540, in inner_func
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return func(conn, *args, **kwargs)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 378, in new_transaction
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     r = func(cursor, *args, **kwargs)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/end_to_end_keys.py", line 634, in _claim_e2e_one_time_keys
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     txn.execute(sql, (user_id, device_id, algorithm, key_id))
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 175, in execute
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     self._do_execute(self.txn.execute, sql, *args)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 201, in _do_execute
Jan 17 01:42:47 ubuntu matrix-synapse[20428]:     return func(sql, *args)
Jan 17 01:42:47 ubuntu matrix-synapse[20428]: psycopg2.errors.SerializationFailure: could not serialize access due to concurrent delete
```

Several minutes later the restore from backup seems to have succeeded and the browser console reports:

```
rageshake.js:104 Checking key backup status...
rageshake.js:104 Backup public key X is trusted locally
rageshake.js:104 Found usable key backup v1: enabling key backups
```

### Version information

- **Homeserver**: raim.ist

If not matrix.org:

- **Version**: 
```
{
    "python_version": "3.7.6",
    "server_version": "1.8.0"
}
```

- **Install method**: matrix-docker-ansible-deploy

- **Platform**: Ubuntu 18.04

**Comment by richvdh** [comment]
@aaronraimist: `/_matrix/client/r0/keys/claim` isn't involved in key backup so I think that log is unrelated.

It's hard to tell if this is a client problem or a server-side one: either way we'll need more logs. Can you share INFO-level synapse logs spanning the period in question and/or send a rageshake from your client?

**Comment by aaronraimist** [comment]
I just logged in and setup key backup several times without being able to trigger this again so I'll close for now.
