### ISSUE TITLE
Synapse homeserver registration seems to be broken

### ISSUE THREAD

**Issue by agyepong** [matrix-org/synapse#6738]
### Description

Call to /_matrix/client/r0/register returns M_UNKNOWN errcode

### Steps to reproduce
set msgBody: {password:pwd, username=username, auth={type:m.login.dummy}}
Call <homeserver>/_matrix/client/r0/register

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.
Expects the call to return user_id, access_token, etc

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
```
msgBody: {password:pwd, username=username, auth={type:m.login.dummy}}

response:
{
  "errcode" : "M_UNKNOWN",
  "error" : "Internal server error"
}

server.log
2020-01-15 17:12:13,444 - synapse.access.https.8448 - 233 - INFO - POST-19 - ::ffff:68.169.54.130 - 8448 - Received request: POST /_matrix/client/r0/register
2020-01-15 17:12:13,450 - synapse.http.server - 109 - ERROR - POST-19 - Failed handle request via 'RegisterRestServlet': <SynapseRequest at 0x7fa354e2d278 method='POST' uri='/_matrix/client/r0/register' clientproto='HTTP/1.1' site=8448>
Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/synapse/env/lib/python3.6/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/opt/synapse/env/lib/python3.6/site-packages/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
TypeError: string indices must be integers
```

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:
another homeserver

If not matrix.org:
matrix.dcubedev.com

<!--
 What version of Synapse is running?
{"server_version": "1.8.0 (b=matrix-org-hotfixes,a099ab7d3)", "python_version": "3.7.3"}

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->
centos 7 with postgresql 12

**Comment by richvdh** [comment]
Are you sure that is the complete stacktrace?

If so, can you clarify the repro steps: those you give work as expected for me:

```
$ curl https://matrix.org/_matrix/client/r0/register -d '{"password":"pwd", "username":"username12421434", "auth":{"type":"m.login.dummy"}}'
{
    "completed": [
        "m.login.dummy"
    ],
    ...
}
```

**Comment by agyepong** [comment]
Yes, that is the complete stacktrace.
The problem could be the Java application I am using to send the request Is
messing things up.
Is there a way to see the body of the message that is received in the log?

Thanks

**Comment by richvdh** [comment]
I'm afraid not. You'd need to capture this on the client side.

I'm going to close this as I don't think registration is actually broken.
