### ISSUE TITLE
AttributeError: 'DataStore' object has no attribute 'purge_room_state'

### ISSUE THREAD

**Issue by git-minix** [matrix-org/synapse#6743]
### Description
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 326, in _async_render
    callback_return = await callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/admin/purge_room_servlet.py", line 55, in on_POST
    await self.pagination_handler.purge_room(body["room_id"])
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/handlers/pagination.py", line 281, in purge_room
    await self.storage.purge_events.purge_room(room_id)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/purge_events.py", line 37, in purge_room
    yield self.stores.main.purge_room_state(room_id, state_groups_to_delete)
AttributeError: 'DataStore' object has no attribute 'purge_room_state'

### Steps to reproduce
curl https://xxx.xxx:8448/_synapse/admin/v1/purge_room -H 'Authorization: Bearer xxxxxxx' -XPOST -d '{"room_id":"!xxxxxxx"}'
{
    "errcode": "M_UNKNOWN",
    "error": "Internal server error"
}

### Version information

Debian matrix-synapse-py3            1.8.0+stretch1 

- **Install method**:
apt 

- **Platform**:
Debian 9.11
LXC Container

**Comment by richvdh** [comment]
#6707
