### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'xpath' when previewing URL in media_repo

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/synapse#6745]
Exception thrown up when trying to preview a URL - looks like `tree` can sometimes be None at https://github.com/matrix-org/synapse/blob/b98971e8a437eb3903506eadbefdf6cb2e0853d6/synapse/rest/media/v1/preview_url_resource.py#L490

```
Traceback (most recent call last):
  File "/home/synapse/src/synapse/http/server.py", line 77, in wrapped_request_handler
    await h(self, request)
  File "/home/synapse/src/synapse/rest/media/v1/preview_url_resource.py", line 164, in _async_render_GET
    og = await make_deferred_yieldable(defer.maybeDeferred(observable.observe))
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/src/synapse/rest/media/v1/preview_url_resource.py", line 243, in _do_preview
    og = decode_and_calc_og(body, media_info["uri"], encoding)
  File "/home/synapse/src/synapse/rest/media/v1/preview_url_resource.py", line 491, in decode_and_calc_og
    og = _calc_og(tree, media_uri)
  File "/home/synapse/src/synapse/rest/media/v1/preview_url_resource.py", line 522, in _calc_og
    for tag in tree.xpath("//*/meta[starts-with(@property, 'og:')]"):
AttributeError: 'NoneType' object has no attribute 'xpath'
```

**Comment by clokep** [comment]
I believe I had seen this happen when the content had a size of 0 for some reason. I suspect this is missing a guard to not try to parse when `body` is empty.

**Comment by clokep** [comment]
I think #9333 fixed this.
