### ISSUE TITLE
Update to 1.9.0 triggers sanity check error in room

### ISSUE THREAD

**Issue by saintger** [matrix-org/synapse#6779]
### Description

I had a room aaa in the past which cannot be used anymore:
https://github.com/matrix-org/synapse/issues/2534
I kept the room aaa in this frozen state until recently where it was accessible again after an update from Synapse.

Today I upgraded my homeserver to Synapse v1.9.0 (running on Debian Buster) and _another_ room bbb cannot be used anymore because of this error:
```
Exception: During auth for event xxx in room bbb, found event yyy in the state which is in room aaa
```
Commenting the code raising the exception makes the room usable again:
https://github.com/matrix-org/synapse/pull/6530/files/02137bef51779880d1b16194e2d2de9a693dc512

It is probably related to the following issues:
https://github.com/matrix-org/synapse/issues/3285
with a comment from @richvdh saying that existing room can be impacted.

I suppose that one (or both) room is somehow messed up.
What would be the fix or workaround in order to avoid losing all the history ? Could we fix the database ?

I can probably delete or wipe the room aaa, but I would really like to keep room bbb.

Thanks in advance,

**Comment by richvdh** [comment]
yes, I've seen this in the wild too.

First let me say that the problem here is definitely that room bbb is messed up in your database: it contains events which should never have been allowed into that room, so anything we do from here is going to be a hack with the danger of making things worse rather than better.

With that said, you might have some success with a query along the lines of:

```sql
DELETE FROM state_groups_state sgs USING events e 
WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id 
AND sgs.room_id= '<room id bbb>';
```

**Comment by saintger** [comment]
Sorry for the delay, I was still on sqlite (it is a very small homeserver...) and I had to move to postgresql before continuing further...

```
synapse=# SELECT COUNT(*) FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id;
 count 
-------
   182
(1 row)

synapse=# SELECT COUNT(*) FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
 count 
-------
     0
(1 row)
```

So strangely there is no occurrence where e.room_id != sgs.room_id.
However I still got the same error as before ?
Did I misunderstand the query ?

Thanks

**Comment by richvdh** [comment]
I guess something else must be wrong. Can you contact me via matrix? `@richvdh:sw1v.org`

**Comment by saintger** [comment]
After an extensive debugging session with @richvdh, the root cause was linked to the room having somehow 2 candidates for a previous state group.
```
sqlite> select * from state_group_edges where state_group=32;
32|29
32|22
```
So the "solution" was to delete one of them:
```
delete from state_group_edges where state_group=32 and prev_state_group=29;
```

For those interested in the debugging, here are the steps which led to finding the issue:
```
select * from event_forward_extremities where room_id='<room id>';
select * from event_to_state_groups where event_id='<previous event id>';
select * from state_group_edges where state_group=<previous state group>;
```

And then we repeat the last statement until we find the case with 2 predecessors.
Thanks a lot for @richvdh for helping me debug this.

**Comment by richvdh** [comment]
For the record: as @saintger says, the problem here was that state group 32 had two predecessors, 22 and 29. I *think* this was due to a bug in the way that we used to allocate state group ids caused state group 32 to be used twice. I think (hope) that bug has been long since fixed.

For anyone else looking at this, I think this query would have raised a red flag much quicker than iterating through the state group chain:

```sql
select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
```

if that returns any rows, there's a problem.

**Comment by worldowner** [comment]
The same thing happened to one of rooms on my homesever today. Currently I run synapse 1.11.0 (avhost/docker-matrix:v1.11.0). I got wrong entry in state_group_edges for a room that was created 3 days ago already on synapse 1.11.0. The version of room is 5. Deleting bad entry fixed the room for me.

I'm not sure if that means that this bug is still present or it is a leftover after what older synapse versions did (I've been running and constantly upgrading synapse since 0.26 or 0.27). Either way it may be something to take a look at.

**Comment by richvdh** [comment]
> I got wrong entry in state_group_edges for a room that was created 3 days ago already on synapse 1.11.0.

This doesn't sound good. Is this the same room as the discussion in #6975?

**Comment by worldowner** [comment]
No, it's completely new room created 3 days ago. My synapse was already on 1.11.0 when affected room was created (and so was federated server where other member has account).
The issue happened only on my homeserver.

**Comment by richvdh** [comment]
ok can you create a new issue with more information please?

**Comment by worldowner** [comment]
Done.

**Comment by schnuffle** [comment]
I'm on synapse 1.9.0 and when I run richvdhs query, I get:

```
synapse=# select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
   id   |             room_id              |                   event_id                   | state_group | prev_state_group |   id   |            room_id             |                   event_id                   
--------+----------------------------------+----------------------------------------------+-------------+------------------+--------+--------------------------------+----------------------------------------------
 526588 | !pJuUbnUuHXkdtZkuqv:matrix.org   | $15109483053HCPgf:schnuffle.de               |      526588 |           526587 | 526587 | !zNvOEhgMmMbHoqgwfD:matrix.org | $15109482971ypZxe:schnuffle.de
 526589 | !ZBjIxlFhJPUkrJGgCg:schnuffle.de | $15109483114cjUlM:schnuffle.de               |      526589 |           526588 | 526588 | !pJuUbnUuHXkdtZkuqv:matrix.org | $15109483053HCPgf:schnuffle.de
 742706 | !mjbDjyNsRXndKLkHIe:matrix.org   | $7eGUUGnG-f-AkUuiEM2CIW_C9_vO5dbxtoo48lFzeWg |      742706 |           742705 | 742705 | !OGEhHVWSdvArJzumhm:matrix.org | $rudfE1NeOC05BNGMoEdFBmCnOxrELXVTV4n7I7iMx6E
 742708 | !OGEhHVWSdvArJzumhm:matrix.org   | $vHX87BC0dhsB5ybdz_jyyANQUwAx2ya9JfRVnUq2sQE |      742708 |           742707 | 742707 | !mjbDjyNsRXndKLkHIe:matrix.org | $H2H9TlDQfJdhMakjvwArYwQ-3FNJCl272Z9k0_m1tNA
 742712 | !mjbDjyNsRXndKLkHIe:matrix.org   | $E568sGBnF3CUGKZQVfykEsN8Cq4RcyBZmdz3DyGaZ-M |      742712 |           742711 | 742711 | !OGEhHVWSdvArJzumhm:matrix.org | $gHSz1KPgIllYE8ryyBpwsZQ57y9ftdMU1zfYuHG68K4
 742713 | !OGEhHVWSdvArJzumhm:matrix.org   | $ar1rB_xWKQdHeAAVTdBbTymWHFJxbLJeTDBzPhOLBuw |      742713 |           742712 | 742712 | !mjbDjyNsRXndKLkHIe:matrix.org | $E568sGBnF3CUGKZQVfykEsN8Cq4RcyBZmdz3DyGaZ-M
 742716 | !mjbDjyNsRXndKLkHIe:matrix.org   | $SH7v2PXNX417twT_3WjqmqBEfzSqYXOGrJEyabKW1MY |      742716 |           742715 | 742715 | !OGEhHVWSdvArJzumhm:matrix.org | $xwiDOzd5NBQ3_EttWPDVHFr77HBf99tcE5PREpEkiZY
 742717 | !OGEhHVWSdvArJzumhm:matrix.org   | $SOeUehZoBftRV4QduWhHeCcq89uQrYCBTOpzxyAdDQ8 |      742717 |           742716 | 742716 | !mjbDjyNsRXndKLkHIe:matrix.org | $SH7v2PXNX417twT_3WjqmqBEfzSqYXOGrJEyabKW1MY
 742724 | !mjbDjyNsRXndKLkHIe:matrix.org   | $gGg4Ge1nuFDorrOylRvobbTZKYwXqw38W8pz0lYi0Ik |      742724 |           742723 | 742723 | !OGEhHVWSdvArJzumhm:matrix.org | $7VzU6Diy1z6scSXb7JRomKEtGTjT3VWNFI1Yz6VZwUc
 742725 | !OGEhHVWSdvArJzumhm:matrix.org   | $iLehzVciY311KlnaPgIztkQGyIOCG22SemJcvyBpxj8 |      742725 |           742724 | 742724 | !mjbDjyNsRXndKLkHIe:matrix.org | $gGg4Ge1nuFDorrOylRvobbTZKYwXqw38W8pz0lYi0Ik
 742731 | !mjbDjyNsRXndKLkHIe:matrix.org   | $K2apsC6NQN93KRUUE4NI2qsgePZVtkmVYiF--m8z8y8 |      742731 |           742730 | 742730 | !OGEhHVWSdvArJzumhm:matrix.org | $ondpxRRgEX5bvW2M1pQ3k6hYrZk9-i1Mr5JJbITPDrM
 742733 | !OGEhHVWSdvArJzumhm:matrix.org   | $e4S-hSsTbLquwE1u17kzfX3gmF2X4C3KS8a9TArRqjs |      742733 |           742732 | 742732 | !mjbDjyNsRXndKLkHIe:matrix.org | $gEFPHRuo3vbhy5-BjjLy18jyVFLsKY6u22ajB4TnAs0
 742734 | !mjbDjyNsRXndKLkHIe:matrix.org   | $eaoXxMJ7LOCfQO75fVnYMZYhDie7c_lLNM3JLYjO13o |      742734 |           742733 | 742733 | !OGEhHVWSdvArJzumhm:matrix.org | $e4S-hSsTbLquwE1u17kzfX3gmF2X4C3KS8a9TArRqjs
 742735 | !OGEhHVWSdvArJzumhm:matrix.org   | $JRTnjD9PQInaWgKVpK_zIh2asc3IxWBolKoLZmVjw2w |      742735 |           742734 | 742734 | !mjbDjyNsRXndKLkHIe:matrix.org | $eaoXxMJ7LOCfQO75fVnYMZYhDie7c_lLNM3JLYjO13o
 742736 | !mjbDjyNsRXndKLkHIe:matrix.org   | $17VBb5c8yENt7nz3JnTHR6zs7rWR_XwhDJSNviDL9Uo |      742736 |           742735 | 742735 | !OGEhHVWSdvArJzumhm:matrix.org | $JRTnjD9PQInaWgKVpK_zIh2asc3IxWBolKoLZmVjw2w
 742738 | !OGEhHVWSdvArJzumhm:matrix.org   | $T2ukM-22b2PJdFSfeBabPizM3pQCCGlzJacFiiup1Mk |      742738 |           742737 | 742737 | !mjbDjyNsRXndKLkHIe:matrix.org | $iAE3TVHronrPsfKGRkxcUJIZmzjE9HyD__xM3acJ0-w
 742750 | !xYvNcQPhnkrdUmYczI:matrix.org   | $5LguKnKqEsOclr8F6Tarez65N-XRyny9dmi_dnYtfvE |      742750 |           742749 | 742749 | !OGEhHVWSdvArJzumhm:matrix.org | $pDSWrSRLr2lOrWWXIhWDkuxDWXxwltJ8AXXt9wwNNU0
 742751 | !mjbDjyNsRXndKLkHIe:matrix.org   | $_em7gCNp1yGTYcD47VN8alHi5qtDCSOTLDFsOf2AZYc |      742751 |           742750 | 742750 | !xYvNcQPhnkrdUmYczI:matrix.org | $5LguKnKqEsOclr8F6Tarez65N-XRyny9dmi_dnYtfvE
 742754 | !OGEhHVWSdvArJzumhm:matrix.org   | $k8lVDvYNfXzJeXGQEHS1skQkbZsDcYIx2xc2S67crsQ |      742754 |           742753 | 742753 | !mjbDjyNsRXndKLkHIe:matrix.org | $8rnhE3tswyoWucqL1RwagJ8POXhDJ7v3hRoEMLXH2q4
 742757 | !xYvNcQPhnkrdUmYczI:matrix.org   | $16_cvJxO3AZHZXNSVHW9EqN7O7Fx-2XMcLrBY3kxBmE |      742757 |           742756 | 742756 | !OGEhHVWSdvArJzumhm:matrix.org | $XM7y-9ZCJ3WVw4NhpvEvL7XzG41SW2jWZBjqQk3IjtE
 742758 | !mjbDjyNsRXndKLkHIe:matrix.org   | $FhgRdM62K9IsRhpweAXk75CvnTeEJT-4bPAYes4zLEg |      742758 |           742757 | 742757 | !xYvNcQPhnkrdUmYczI:matrix.org | $16_cvJxO3AZHZXNSVHW9EqN7O7Fx-2XMcLrBY3kxBmE
 742760 | !OGEhHVWSdvArJzumhm:matrix.org   | $E3hcdWrHNZtWajNaTd6aPnAAowtJAWk6MXLfCmEuEiU |      742760 |           742758 | 742758 | !mjbDjyNsRXndKLkHIe:matrix.org | $FhgRdM62K9IsRhpweAXk75CvnTeEJT-4bPAYes4zLEg
 742761 | !mjbDjyNsRXndKLkHIe:matrix.org   | $SGUYCjl91khVh49VBAEObBADu47J6q27G6jA84nDyBQ |      742761 |           742760 | 742760 | !OGEhHVWSdvArJzumhm:matrix.org | $E3hcdWrHNZtWajNaTd6aPnAAowtJAWk6MXLfCmEuEiU
 742763 | !OGEhHVWSdvArJzumhm:matrix.org   | $4dsH4SJufBC12Eprmsm1IczFcb4PdAZlq0nO4L96iHw |      742763 |           742762 | 742762 | !mjbDjyNsRXndKLkHIe:matrix.org | $XuiHwUTfee5t6w6DGBXwe8u-UQtBy3VG1iKMmhmUUSQ
 742774 | !mjbDjyNsRXndKLkHIe:matrix.org   | $Zr6HuXzqg0VtNIdG_Dr9vjIvn-xl1BXmD2wXtcrnP6k |      742774 |           742773 | 742773 | !OGEhHVWSdvArJzumhm:matrix.org | $zZ3eG9Qxps5ioUMQkShDBgsThwbaff5FnDeEVu7EZ4U
 742785 | !OGEhHVWSdvArJzumhm:matrix.org   | $gqkoqOwZa4m-2l-C4vUp81JbbNHt0RhvAw3zNDecLsc |      742785 |           742784 | 742784 | !mjbDjyNsRXndKLkHIe:matrix.org | $A1RI6YnHjkaYmkrNz8YbrzOauPw9aFhf7VkBpiFBmSE
 742790 | !OGEhHVWSdvArJzumhm:matrix.org   | $BAct0BFtPzULc9xC9ZpkPExmhdieqBT3J93PREmYUBo |      742790 |           742789 | 742789 | !xYvNcQPhnkrdUmYczI:matrix.org | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8
 742812 | !OGEhHVWSdvArJzumhm:matrix.org   | $JC8J8qnIjwsGyc4IEBvg2QAD1nyAOIwaiC9WLmNbx4Q |      742812 |           742811 | 742811 | !xYvNcQPhnkrdUmYczI:matrix.org | $r9P750FnWIMqZWgg_6bmx_flLW-ZasMbky1kyu3MOOQ
 742815 | !xYvNcQPhnkrdUmYczI:matrix.org   | $3RJl-7Sap-9YVt0eLfWsyvPD82isArpGhM2Fa3xyUMg |      742815 |           742814 | 742814 | !OGEhHVWSdvArJzumhm:matrix.org | $qhtRTKoUrKD3XBytNGyACC-7Ppeexf99p63iY7biin8
 742786 | !mjbDjyNsRXndKLkHIe:matrix.org   | $yesnbQFa-PmWzBV7BaEGUCLldFXPWnsyp6Hj2b2LZ4Q |      742786 |           742785 | 742785 | !OGEhHVWSdvArJzumhm:matrix.org | $gqkoqOwZa4m-2l-C4vUp81JbbNHt0RhvAw3zNDecLsc
 742817 | !xYvNcQPhnkrdUmYczI:matrix.org   | $WK847qQk9V7eWn_oq0byr6M4brIiRErXDRfbgCKmRjk |      742817 |           742816 | 742816 | !OGEhHVWSdvArJzumhm:matrix.org | $XZ0JSzsaa0IMwMOAsT7BEnEthCtrspl3uKY8gp4UImk
 743101 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743101 |           743100 | 743100 | !xYvNcQPhnkrdUmYczI:matrix.org | $yHomHoiz2R8IuB3Z6ovHO3uzDGo60pUgj_VEruWUJfM
 742788 | !OGEhHVWSdvArJzumhm:matrix.org   | $j0zXBsbk0bCaZ_IjmN_4Op11ckrq7oyh7BBxEe2yVsE |      742788 |           742787 | 742787 | !mjbDjyNsRXndKLkHIe:matrix.org | $N6GgBcwQf-7JOhww4DtwfmgzuoudBhFKGOF2cr2EuGU
 742816 | !OGEhHVWSdvArJzumhm:matrix.org   | $XZ0JSzsaa0IMwMOAsT7BEnEthCtrspl3uKY8gp4UImk |      742816 |           742815 | 742815 | !xYvNcQPhnkrdUmYczI:matrix.org | $3RJl-7Sap-9YVt0eLfWsyvPD82isArpGhM2Fa3xyUMg
 742789 | !xYvNcQPhnkrdUmYczI:matrix.org   | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8 |      742789 |           742788 | 742788 | !OGEhHVWSdvArJzumhm:matrix.org | $j0zXBsbk0bCaZ_IjmN_4Op11ckrq7oyh7BBxEe2yVsE
 742792 | !xYvNcQPhnkrdUmYczI:matrix.org   | $LaJeYPpyuCOeajnYL_SVeVgOnagg3sOTn7ijI92b7Z8 |      742792 |           742791 | 742791 | !OGEhHVWSdvArJzumhm:matrix.org | $Ltx-RHwgptTTowd6SCqdjbo10EOeewUBqk8HNjOr17k
 743113 | !xYvNcQPhnkrdUmYczI:matrix.org   | $_fgwyVRq43OZrgc8YWUweJaRTzQf9haRUGt4QY49kqI |      743113 |           743112 | 743112 | !mjbDjyNsRXndKLkHIe:matrix.org | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU
 743102 | !xYvNcQPhnkrdUmYczI:matrix.org   | $cMOCtwagISN7vZOsByam_3Utq2PdPcKSYabA1o4zAW8 |      743102 |           743101 | 743101 | !mjbDjyNsRXndKLkHIe:matrix.org | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU
 743111 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743111 |           743110 | 743110 | !xYvNcQPhnkrdUmYczI:matrix.org | $EbBMH7ssxwx27J89VeYHn6WIRqu9cW5TlBmv-WQXmE4
 743116 | !mjbDjyNsRXndKLkHIe:matrix.org   | $y78ZzDbI9LsRM_N2ROe2QW0MlTTzoluduMXckjkX0CU |      743116 |           743110 | 743110 | !xYvNcQPhnkrdUmYczI:matrix.org | $EbBMH7ssxwx27J89VeYHn6WIRqu9cW5TlBmv-WQXmE4
```

Now the question is, how do I get this corrected?

 It has the effect that after having logged out my principal user, after logging in again, the initial sync is stuck forever, which can be seen as another error on Element Web/Android

And of course it has an impact in my logs:

```
2020-08-25 18:50:40,842 - synapse.http.server - 80 - ERROR - GET-12 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f1fc27a9100 method='GET' uri='/_matrix/client/r0/sync?filter=21&timeout=0' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$7tPxEanEvRk8ADzN9TxNOxr4__jTh9-PnToak-_kbDY':  ..................... a Massive json construct which I cut off

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 310, in _wait_for_sync_for_user
    result = await self.current_sync_for_user(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 342, in current_sync_for_user
    return await self.generate_sync_result(sync_config, since_token, full_state)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 998, in generate_sync_result
    res = await self._generate_sync_entry_for_rooms(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1430, in _generate_sync_entry_for_rooms
    await concurrently_execute(handle_room_entries, room_entries, 10)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 157, in _concurrently_execute_inner
    await maybe_awaitable(func(next(it)))
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1418, in handle_room_entries
    res = await self._generate_room_entry(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 1808, in _generate_room_entry
    batch = await self._load_filtered_recents(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/handlers/sync.py", line 504, in _load_filtered_recents
    current_state_ids_map = await self.state.get_current_state_ids(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 167, in get_current_state_ids
    ret = await self.resolve_state_groups_for_events(room_id, latest_event_ids)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/util/metrics.py", line 88, in measured_func
    r = await func(self, *args, **kwargs)
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 388, in resolve_state_groups_for_events
    result = await self._state_resolution_handler.resolve_state_groups(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/__init__.py", line 510, in resolve_state_groups
    new_state = await resolve_events_with_store(
  File "/home/synapse/.pyenv/versions/synapse-py381/lib/python3.8/site-packages/synapse/state/v2.py", line 104, in resolve_events_with_store
    raise Exception(
Exception: Attempting to state-resolve for room !xYvNcQPhnkrdUmYczI:matrix.org with event $3fZr80mRY-86Nq0ry4kl-TlF9vIIjFC2_adusEZOQVA which is in !OGEhHVWSdvArJzumhm:matrix.org

```


Regards

Schnuffle
