### ISSUE TITLE
Error: 500: More than one row matched

### ISSUE THREAD

**Issue by Dryusdan** [matrix-org/synapse#6808]
Hi

### Description

I had a index problem after migrating to en.us.UTF-8 colate on PostgreSQL 11 to C (dump and import).

I have some error like this 

```
2020-01-29 20:55:57,956 - synapse.storage.background_updates - 112 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 109, in run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 205, in do_next_background_update
    res = await self._do_background_update(update_name, desired_duration_ms)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 239, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/data_stores/main/user_directory.py", line 250, in _populate_user_directory_process_rooms
    yield self.db.simple_delete_one(TEMP_TABLE + "_rooms", {"room_id": room_id})
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 495, in runInteraction
    **kwargs
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 543, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 540, in inner_func
    return func(conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 378, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 1266, in simple_delete_one_txn
    raise StoreError(500, "More than one row matched (%s)" % (table,))
synapse.api.errors.StoreError: 500: More than one row matched (_temp_populate_user_directory_rooms)
```
And I don't find user_directory_rooms table. So I can't remove duplicate entry.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.drycat.fr

<!--
 What version of Synapse is running? 

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.9.1+buster1

```
{
    "python_version": "3.7.3",
    "server_version": "1.9.1"
}
```

- **Install method**: apt
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian 10 on KVM VM.
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

Thank for you're help :blush:

**Comment by richvdh** [comment]
looks like it's complaining about `_temp_populate_user_directory_rooms`, not `user_directory_rooms`.

**Comment by Dryusdan** [comment]
But I don't see `_temp_populate_user_directory_rooms` table :/

**Comment by richvdh** [comment]
to confirm: are you looking at the database or the dump?

**Comment by Dryusdan** [comment]
I looking at the database.

**Comment by Dryusdan** [comment]
Hum ok, I need to change my glasses...

```

synapse=# \dt+
                                       List of relations
 Schema |                  Name                  | Type  |  Owner   |    Size    | Description 
--------+----------------------------------------+-------+----------+------------+-------------
 public | _temp_populate_user_directory_position | table | synapse  | 16 kB      | 
 public | _temp_populate_user_directory_rooms    | table | synapse  | 112 kB     | 
 public | _temp_populate_user_directory_users    | table | synapse  | 64 kB      | 
 public | access_tokens                          | table | synapse  | 168 kB     | 
 public | account_data                           | table | synapse  | 184 kB     | 
 public | account_data_max_stream_id             | table | synapse  | 8192 bytes | 
 public | account_validity                       | table | synapse  | 8192 bytes | 
 public | application_services_state             | table | synapse  | 16 kB      | 
 public | application_services_txns              | table | synapse  | 8192 bytes | 
 public | applied_module_schemas                 | table | synapse  | 8192 bytes | 
 public | applied_schema_deltas                  | table | synapse  | 48 kB      | 
 public | appservice_room_list                   | table | synapse  | 8192 bytes | 
 public | appservice_stream_position             | table | synapse  | 8192 bytes | 
 public | background_updates                     | table | synapse  | 16 kB      | 
 public | blocked_rooms                          | table | synapse  | 8192 bytes | 
 public | cache_invalidation_stream              | table | synapse  | 134 MB     | 
 public | current_state_delta_stream             | table | synapse  | 106 MB     | 
 public | current_state_events                   | table | synapse  | 39 MB      | 
 public | deleted_pushers                        | table | synapse  | 48 kB      | 
 public | destinations                           | table | synapse  | 272 kB     | 
 public | device_federation_inbox                | table | synapse  | 688 kB     | 
 public | device_federation_outbox               | table | synapse  | 256 kB     | 
 public | device_inbox                           | table | synapse  | 185 MB     | 
 public | device_lists_outbound_last_success     | table | synapse  | 1656 kB    | 
 public | device_lists_outbound_pokes            | table | synapse  | 3960 kB    | 
 public | device_lists_remote_cache              | table | synapse  | 114 MB     | 
 public | device_lists_remote_extremeties        | table | synapse  | 1776 kB    | 
 public | device_lists_stream                    | table | synapse  | 39 MB      | 
 public | device_max_stream_id                   | table | synapse  | 8192 bytes | 
 public | devices                                | table | synapse  | 248 kB     | 
 public | e2e_cross_signing_keys                 | table | synapse  | 88 kB      | 
 public | e2e_cross_signing_signatures           | table | synapse  | 8192 bytes | 
 public | e2e_device_keys_json                   | table | synapse  | 472 kB     | 
 public | e2e_one_time_keys_json                 | table | synapse  | 12 MB      | 
 public | e2e_room_keys                          | table | synapse  | 6648 kB    | 
 public | e2e_room_keys_versions                 | table | synapse  | 56 kB      | 
 public | erased_users                           | table | synapse  | 16 kB      | 
 public | event_auth                             | table | synapse  | 236 MB     | 
 public | event_backward_extremities             | table | synapse  | 344 kB     | 
 public | event_edges                            | table | synapse  | 262 MB     | 
 public | event_expiry                           | table | synapse  | 8192 bytes | 
 public | event_forward_extremities              | table | synapse  | 1840 kB    | 
 public | event_json                             | table | synapse  | 2392 MB    | 
 public | event_labels                           | table | synapse  | 8192 bytes | 
 public | event_push_actions                     | table | synapse  | 1200 kB    | 
 public | event_push_actions_staging             | table | synapse  | 336 kB     | 
 public | event_push_summary                     | table | synapse  | 48 kB      | 
 public | event_push_summary_stream_ordering     | table | synapse  | 8192 bytes | 
 public | event_reference_hashes                 | table | synapse  | 192 MB     | 
 public | event_relations                        | table | synapse  | 3616 kB    | 
 public | event_reports                          | table | synapse  | 8192 bytes | 
 public | event_search                           | table | synapse  | 272 MB     | 
 public | event_to_state_groups                  | table | synapse  | 107 MB     | 
 public | events                                 | table | synapse  | 356 MB     | 
 public | ex_outlier_stream                      | table | synapse  | 1008 kB    | 
 public | federation_stream_position             | table | synapse  | 56 kB      | 
 public | group_attestations_remote              | table | synapse  | 16 kB      | 
 public | group_attestations_renewals            | table | synapse  | 16 kB      | 
 public | group_invites                          | table | synapse  | 8192 bytes | 
 public | group_roles                            | table | synapse  | 8192 bytes | 
 public | group_room_categories                  | table | synapse  | 8192 bytes | 
 public | group_rooms                            | table | synapse  | 16 kB      | 
 public | group_summary_roles                    | table | synapse  | 8192 bytes | 
 public | group_summary_room_categories          | table | synapse  | 8192 bytes | 
 public | group_summary_rooms                    | table | synapse  | 8192 bytes | 
 public | group_summary_users                    | table | synapse  | 8192 bytes | 
 public | group_users                            | table | synapse  | 16 kB      | 
 public | groups                                 | table | synapse  | 16 kB      | 
 public | guest_access                           | table | postgres | 8192 bytes | 
 public | history_visibility                     | table | postgres | 8192 bytes | 
 public | local_current_membership               | table | synapse  | 136 kB     | 
 public | local_group_membership                 | table | synapse  | 16 kB      | 
 public | local_group_updates                    | table | synapse  | 16 kB      | 
 public | local_invites                          | table | synapse  | 88 kB      | 
 public | local_media_repository                 | table | synapse  | 1280 kB    | 
 public | local_media_repository_thumbnails      | table | synapse  | 2160 kB    | 
 public | local_media_repository_url_cache       | table | synapse  | 408 kB     | 
 public | monthly_active_users                   | table | synapse  | 8192 bytes | 
 public | open_id_tokens                         | table | synapse  | 384 kB     | 
 public | presence                               | table | synapse  | 8192 bytes | 
 public | presence_allow_inbound                 | table | synapse  | 8192 bytes | 
 public | presence_stream                        | table | synapse  | 4328 kB    | 
 public | profiles                               | table | synapse  | 56 kB      | 
 public | public_room_list_stream                | table | synapse  | 16 kB      | 
 public | push_rules                             | table | synapse  | 64 kB      | 
 public | push_rules_enable                      | table | synapse  | 48 kB      | 
 public | push_rules_stream                      | table | synapse  | 96 kB      | 
 public | pusher_throttle                        | table | synapse  | 8192 bytes | 
 public | pushers                                | table | synapse  | 48 kB      | 
 public | ratelimit_override                     | table | synapse  | 8192 bytes | 
 public | receipts_graph                         | table | synapse  | 9848 kB    | 
 public | receipts_linearized                    | table | synapse  | 10136 kB   | 
 public | received_transactions                  | table | synapse  | 293 MB     | 
 public | redactions                             | table | synapse  | 2064 kB    | 
 public | rejections                             | table | synapse  | 128 kB     | 
 public | remote_media_cache                     | table | synapse  | 2128 kB    | 
 public | remote_media_cache_thumbnails          | table | synapse  | 6688 kB    | 
 public | remote_profile_cache                   | table | synapse  | 8192 bytes | 
 public | room_account_data                      | table | synapse  | 184 kB     | 
 public | room_alias_servers                     | table | synapse  | 16 kB      | 
 public | room_aliases                           | table | synapse  | 16 kB      | 
 public | room_depth                             | table | synapse  | 72 kB      | 
 public | room_memberships                       | table | synapse  | 102 MB     | 
 public | room_names                             | table | postgres | 8192 bytes | 
 public | room_retention                         | table | synapse  | 8192 bytes | 
 public | room_state                             | table | postgres | 8192 bytes | 
 public | room_stats                             | table | postgres | 8192 bytes | 
 public | room_stats_current                     | table | synapse  | 176 kB     | 
 public | room_stats_earliest_token              | table | synapse  | 64 kB      | 
 public | room_stats_historical                  | table | synapse  | 1256 kB    | 
 public | room_stats_state                       | table | synapse  | 144 kB     | 
 public | room_tags                              | table | synapse  | 48 kB      | 
 public | room_tags_revisions                    | table | synapse  | 48 kB      | 
 public | rooms                                  | table | synapse  | 80 kB      | 
 public | schema_version                         | table | synapse  | 8192 bytes | 
 public | server_keys_json                       | table | synapse  | 6024 kB    | 
 public | server_signature_keys                  | table | synapse  | 1072 kB    | 
 public | state_events                           | table | synapse  | 81 MB      | 
 public | state_group_edges                      | table | synapse  | 10 MB      | 
 public | state_groups                           | table | synapse  | 26 MB      | 
 public | state_groups_state                     | table | synapse  | 5871 MB    | 
 public | stats_incremental_position             | table | synapse  | 48 kB      | 
 public | stats_stream_pos                       | table | postgres | 0 bytes    | 
 public | stream_ordering_to_exterm              | table | synapse  | 45 MB      | 
 public | threepid_guest_access_tokens           | table | synapse  | 8192 bytes | 
 public | threepid_validation_session            | table | synapse  | 8192 bytes | 
 public | threepid_validation_token              | table | synapse  | 8192 bytes | 
 public | topics                                 | table | postgres | 8192 bytes | 
 public | user_daily_visits                      | table | synapse  | 800 kB     | 
 public | user_directory                         | table | synapse  | 7040 kB    | 
 public | user_directory_search                  | table | synapse  | 11 MB      | 
 public | user_directory_stream_pos              | table | synapse  | 8192 bytes | 
 public | user_external_ids                      | table | synapse  | 8192 bytes | 
 public | user_filters                           | table | synapse  | 56 kB      | 
 public | user_ips                               | table | synapse  | 592 kB     | 
 public | user_signature_stream                  | table | synapse  | 8192 bytes | 
 public | user_stats                             | table | postgres | 8192 bytes | 
 public | user_stats_current                     | table | synapse  | 80 kB      | 
 public | user_stats_historical                  | table | synapse  | 232 kB     | 
 public | user_threepid_id_server                | table | synapse  | 16 kB      | 
 public | user_threepids                         | table | synapse  | 16 kB      | 
 public | users                                  | table | synapse  | 88 kB      | 
 public | users_in_public_rooms                  | table | synapse  | 4672 kB    | 
 public | users_pending_deactivation             | table | synapse  | 8192 bytes | 
 public | users_who_share_private_rooms          | table | synapse  | 8192 bytes | 
(145 rows)
```

**Comment by Dryusdan** [comment]
Okay, I found some duplicates (I increase LIMIT value to 100 and the count value are always 2 ::
```
synapse=# select count(*), room_id, events from _temp_populate_user_directory_rooms group by 2,3 order by count(*) DESC LIMIT 10;
 count |               room_id                | events 
-------+--------------------------------------+--------
     2 | !XXX:matrix.drycat.fr |      6
     2 | !XXX:matrix.drycat.fr |      6
     2 | !XXX:matrix.drycat.fr |      7
     2 | !XXX:matrix.drycat.fr |      7
     2 | !XXX:matrix.org       |     15
     2 | !XXX:tchncs.de        |   1017
     2 | !XXX:matrix.org       |      9
     2 | !XXX:matrix.drycat.fr |      8
     2 | !XXX:matrix.drycat.fr |      6
     2 | !XXX:matrix.org       |   2497

```

No index is present 
```
synapse=# SELECT indexname, indexdef FROM pg_indexes WHERE  tablename = '_temp_populate_user_directory_rooms';

 indexname | indexdef 
-----------+----------
(0 rows)
```

**Comment by richvdh** [comment]
`_temp_populate_user_directory_rooms` is a temporary table which is only used during a database schema update. (In fact it's used when upgrading to synapse 0.99.3, and shouldn't be needed after that, so I'm rather surprised that you're still having problems with it.)

Anyway it should be safe to remove the duplicate rows, but your query won't work because the duplicate rows have identical `events` values. Try this:

```sql
DELETE _temp_populate_user_directory_rooms WHERE ctid NOT IN (SELECT last_value(ctid) OVER (PARTITION BY room_id ORDER BY events) FROM _temp_populate_user_directory_rooms);
```

**Comment by Dryusdan** [comment]
Thank :D 

I haven't any error now ! 

Thank :D

**Comment by Dryusdan** [comment]
Hum, I speak too fast...

Error is here :/

```
2020-01-30 14:36:58,623 - synapse.storage.background_updates - 112 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 109, in run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 205, in do_next_background_update
    res = await self._do_background_update(update_name, desired_duration_ms)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 239, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/data_stores/main/user_directory.py", line 250, in _populate_user_directory_process_rooms
    yield self.db.simple_delete_one(TEMP_TABLE + "_rooms", {"room_id": room_id})
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 495, in runInteraction
    **kwargs
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 543, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 540, in inner_func
    return func(conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 378, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/storage/database.py", line 1266, in simple_delete_one_txn
    raise StoreError(500, "More than one row matched (%s)" % (table,))
synapse.api.errors.StoreError: 500: More than one row matched (_temp_populate_user_directory_rooms)
2020-01-30 14:37:09,146 - synapse.http.site - 203 - WARNING - GET-216- Error processing request <XForwardedForRequest at 0x7f4e98d40128 method='GET' uri='/_matrix/client/r0/rooms/!vodMueWsIdJsXwRRjT%3Amatrix.org/context/%24IffubVCgdK6WX8NisbMjaDJ6m3VoBvNGxwUga-BJehE?filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
2020-01-30 14:37:29,277 - synapse.http.server - 463 - WARNING - GET-216- Not sending response to request <XForwardedForRequest at 0x7f4e98d40128 method='GET' uri='/_matrix/client/r0/rooms/!vodMueWsIdJsXwRRjT%3Amatrix.org/context/%24IffubVCgdK6WX8NisbMjaDJ6m3VoBvNGxwUga-BJehE?filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site=8008>, already disconnected.
2020-01-30 14:37:31,171 - synapse.storage.database - 389 - WARNING - PUT-253- [TXN OPERROR] {store_server_keys_json-1203} could not serialize access due to concurrent update
 0/5
2020-01-30 14:37:31,856 - synapse.storage.database - 389 - WARNING - PUT-256- [TXN OPERROR] {store_server_keys_json-1229} could not serialize access due to concurrent update
 0/5
2020-01-30 14:37:43,410 - synapse.storage.database - 389 - WARNING - PUT-266- [TXN OPERROR] {store_server_keys_json-13d2} could not serialize access due to concurrent update
 0/5
```

But this command : 
```
synapse=# select count(*), room_id, events from _temp_populate_user_directory_rooms group by 2,3 order by count(*) DESC LIMIT 10;
 count |               room_id                | events 
-------+--------------------------------------+--------
     1 | !x:matrix.drycat.fr |      6
     1 | !x:matrix.drycat.fr |      6
     1 | !x:matrix.drycat.fr |      7
     1 | !x:matrix.drycat.fr |      7
     1 | !x:matrix.org       |     15
     1 | !x:tchncs.de        |   1017
     1 | !x:matrix.org       |      9
     1 | !x:matrix.drycat.fr |      8
     1 | !x:matrix.drycat.fr |      6
     1 | !x:matrix.org       |   2497
```
send me no duplicate :/

**Comment by richvdh** [comment]
what does this say

```sql
select count(*), room_id from _temp_populate_user_directory_rooms group by 2 order by count(*) DESC LIMIT 10;

**Comment by Dryusdan** [comment]
I have two duplicate entry now : 

```
synapse=# select count(*), room_id from _temp_populate_user_directory_rooms group by 2 order by count(*) DESC LIMIT 10;
 count |               room_id                
-------+--------------------------------------
     2 | !XXX:privacytools.io
     2 | !XXX:privacytools.io
     1 | !XXX:matrix.drycat.fr
     1 | !XXX:matrix.org
     1 | !XXX:matrix.org
     1 | !XXX:gnous.eu
     1 | !XXX:matrix.drycat.fr
     1 | !XXX:matrix.org
     1 | !XXX:matrix.org
     1 | !XXX:swedneck.xyz
(10 rows)
```

**Comment by richvdh** [comment]
right. does the DELETE remove the duplicates? (Ie, is the problem with the delete, or are they being re-introduced?)

**Comment by Dryusdan** [comment]
The DELETE remove 508 duplicates.

I relunch one DELETE but it return `DELETE 0`

**Comment by richvdh** [comment]
ok

can you do `select ctid from _temp_populate_user_directory_rooms where room_id='<room with duplicates>';`

**Comment by Dryusdan** [comment]
Here the result : 

```

synapse=# select ctid from _temp_populate_user_directory_rooms where room_id='!XXX:privacytools.io';
  ctid   
---------
 (1,109)
 (4,5)
(2 rows)

synapse=# select ctid from _temp_populate_user_directory_rooms where room_id='!XXY:privacytools.io';
  ctid   
---------
 (1,111)
 (4,6)
(2 rows)

```

**Comment by richvdh** [comment]
I am confused.

How about this one:

```sql
SELECT last_value(ctid) OVER (PARTITION BY room_id ORDER BY events) FROM _temp_populate_user_directory_rooms WHERE room_id='!XXX:privacytools.io';
```

(You could just delete the remaining duplicate rows:

```sql
DELETE FROM _temp_populate_user_directory_rooms WHERE ctid='(4,5)';
DELETE FROM _temp_populate_user_directory_rooms WHERE ctid='(4,6)';
```

**Comment by Dryusdan** [comment]
This request return this value : 
```
synapse=# SELECT last_value(ctid) OVER (PARTITION BY room_id ORDER BY events) FROM _temp_populate_user_directory_rooms WHERE room_id='!tYmNuaXMRnHEZWdDqp:privacytools.io';
 last_value 
------------
 (1,109)
 (4,5)
(2 rows)
```

I restart Matrix and watching log.
I currently have no duplication errors.

I continue to monitor log for this day.

Thank you for your help :)

**Comment by Dryusdan** [comment]
Everything is ok o/
This repair also the connection problem between my instance and matrix.org :)

Thank for you're help !
