### ISSUE TITLE
Exception when trying to join a room

### ISSUE THREAD

**Issue by zell-mbc** [matrix-org/synapse#6927]
<<You will likely get better support more quickly if you ask in ** #synapse:matrix.org ** ;)>>
I realize this would be possibly better placed in #synapse:matrix.org but I can't join any room, hence not able to ask there.

"python_version": "3.8.1",
"server_version": "1.9.1"
OS Linux, kernel 5.5.3-arch1-1

Whenever I try to add a room to my homeserver matrix.zell-mbc.com:460 Synapse crashes with the error below.

Steps to recreate:
1. In Riot: Select Explore Rooms
2. Switch to server matrix.org
3. After ~30 seconds Riot will show this error and journalctl on the Synapse server will show the chrash messages.
> Riot failed to get the public room list. CORS request rejected: https://matrix.zell-mbc.com:460/_matrix/client/r0/publicRooms?server=matrix.org

Alternatively:
1. In Riot: Select Explore Rooms
2. Type #synapse:matrix.org
3. After ~30 seconds Riot will show this error and journalctl on the Synapse server will show the chrash messages.
> #synapse:matrix.org is not accessible at this time

Journalctl crash output:
```
homeserver synapse[999698]: 2020-02-15 14:40:11,443 - synapse.http.matrixfederationclient - 481 - WARNING - GET-77 - {GET-O-3} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/directory?room_alias=%23synapse%3Amatrix.org: TimeoutError(10.0, 'Deferred')
Feb 15 14:40:11 homeserver synapse[999698]: 2020-02-15 14:40:11,445 - synapse.http.server - 106 - ERROR - GET-77 - Failed handle request via 'ClientDirectoryServer': <XForwardedForRequest at 0x7f44fc44d1c0 method='GET' uri='/_matrix/client/r0/directory/room/%23synapse%3Amatrix.org' clientproto='HTTP/1.0' site=8008>
Feb 15 14:40:11 homeserver synapse[999698]: Traceback (most recent call last):
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 428, in _send_request
Feb 15 14:40:11 homeserver synapse[999698]:     response = yield request_deferred
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     current.result = callback(current.result, *args, **kw)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 464, in convert_cancelled
Feb 15 14:40:11 homeserver synapse[999698]:     return to_call(value, timeout)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/util/async_helpers.py", line 411, in _cancelled_to_timed_out_error
Feb 15 14:40:11 homeserver synapse[999698]:     raise defer.TimeoutError(timeout, "Deferred")
Feb 15 14:40:11 homeserver synapse[999698]: twisted.internet.defer.TimeoutError: (10.0, 'Deferred')
Feb 15 14:40:11 homeserver synapse[999698]: The above exception was the direct cause of the following exception:
Feb 15 14:40:11 homeserver synapse[999698]: Traceback (most recent call last):
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
Feb 15 14:40:11 homeserver synapse[999698]:     await h(self, request)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/server.py", line 331, in _async_render
Feb 15 14:40:11 homeserver synapse[999698]:     callback_return = await callback_return
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/rest/client/v1/directory.py", line 52, in on_GET
Feb 15 14:40:11 homeserver synapse[999698]:     res = await dir_handler.get_association(room_alias)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     result = result.throwExceptionIntoGenerator(g)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Feb 15 14:40:11 homeserver synapse[999698]:     return g.throw(self.type, self.value, self.tb)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/handlers/directory.py", line 245, in get_association
Feb 15 14:40:11 homeserver synapse[999698]:     result = yield self.federation.make_query(
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     result = result.throwExceptionIntoGenerator(g)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Feb 15 14:40:11 homeserver synapse[999698]:     return g.throw(self.type, self.value, self.tb)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 175, in make_query
Feb 15 14:40:11 homeserver synapse[999698]:     content = yield self.client.get_json(
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     result = result.throwExceptionIntoGenerator(g)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Feb 15 14:40:11 homeserver synapse[999698]:     return g.throw(self.type, self.value, self.tb)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 770, in get_json
Feb 15 14:40:11 homeserver synapse[999698]:     response = yield self._send_request_with_optional_trailing_slash(
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     result = result.throwExceptionIntoGenerator(g)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Feb 15 14:40:11 homeserver synapse[999698]:     return g.throw(self.type, self.value, self.tb)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 246, in _send_request_with_optional_trailing_slash
Feb 15 14:40:11 homeserver synapse[999698]:     response = yield self._send_request(request, **send_request_args)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Feb 15 14:40:11 homeserver synapse[999698]:     result = result.throwExceptionIntoGenerator(g)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Feb 15 14:40:11 homeserver synapse[999698]:     return g.throw(self.type, self.value, self.tb)
Feb 15 14:40:11 homeserver synapse[999698]:   File "/usr/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 433, in _send_request
Feb 15 14:40:11 homeserver synapse[999698]:     raise_from(RequestSendFailed(e, can_retry=True), e)
Feb 15 14:40:11 homeserver synapse[999698]:   File "<string>", line 3, in raise_from
Feb 15 14:40:11 homeserver synapse[999698]: synapse.api.errors.RequestSendFailed: Failed to send request: TimeoutError: (10.0, 'Deferred')
```

**Comment by richvdh** [comment]
please can you format your log with triple-backticks and with the newlines in the right places so that it is legible?

As a first thing to check, check that https://federationtester.matrix.org/ shows no errors for your server_name.

> I realize this would be possibly better placed in #synapse:matrix.org but I can't join any room, 

you can sign up for a temporary account on matrix.org.

**Comment by richvdh** [comment]
(crash = it stops running; that doesn't appear to be the case here)

**Comment by zell-mbc** [comment]
Yes, on both accounts. Sorry.
I noticed the `MatchingServerName | false` here https://fed.mau.dev/matrix.zell-mbc.com:460
But so far couldn't figure out which two items need to match to satisfy this requirement.

**Comment by richvdh** [comment]
> Update:

be aware that github doesn't send notifications for edited messages so it's lucky I happened to se e this...

> Feb 17 08:58:07 homeserver synapse[431239]: 2020-02-17 08:58:07,058 - synapse.http.site - 202 - WARNING - POST-2084 - Error processing request <XForwardedForRequest at 0x7f5b5039d4c0 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.

This just means that the client (or nginx) disconnected while synapse was still processing the request. Can you make sure you have INFO-level logs enabled, and grep for the request id (eg `POST-2084` in this case). Also please confirm what timezone your logs are in.

**Comment by zell-mbc** [comment]
Great! Info is on and timezone is Germany

```
journalctl | grep POST-2084
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,051 - synapse.access.http.8008 - 228 - INFO - POST-2084 - 46.223.117.217 - 8008 - Received request: POST /_matrix/client/r0/createRoom
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,065 - synapse.handlers.room - 768 - INFO - POST-2084 - Sending m.room.create in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,140 - synapse.handlers.room - 782 - INFO - POST-2084 - Sending m.room.member in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,235 - synapse.handlers.room - 768 - INFO - POST-2084 - Sending m.room.power_levels in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,357 - synapse.handlers.room - 768 - INFO - POST-2084 - Sending m.room.join_rules in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,474 - synapse.handlers.room - 768 - INFO - POST-2084 - Sending m.room.history_visibility in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,571 - synapse.handlers.room - 768 - INFO - POST-2084 - Sending m.room.guest_access in new room
Feb 17 08:57:07 homeserver synapse[431239]: 2020-02-17 08:57:07,697 - synapse.http.matrixfederationclient - 402 - INFO - POST-2084 - {GET-O-356} [matrix.org] Sending request: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40gifzly%3Amatrix.org&field=displayname; timeout 10.000000s
Feb 17 08:57:17 homeserver synapse[431239]: 2020-02-17 08:57:17,704 - synapse.http.matrixfederationclient - 432 - INFO - POST-2084 - Failed to send request: (10.0, 'Deferred')
Feb 17 08:57:17 homeserver synapse[431239]: 2020-02-17 08:57:17,704 - synapse.http.matrixfederationclient - 481 - WARNING - POST-2084 - {GET-O-356} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40gifzly%3Amatrix.org&field=displayname: TimeoutError(10.0, 'Deferred')
Feb 17 08:57:17 homeserver synapse[431239]: 2020-02-17 08:57:17,705 - synapse.handlers.message - 485 - INFO - POST-2084 - Failed to get profile information for @gifzly:matrix.org: 502: Failed to fetch profile
Feb 17 08:57:17 homeserver synapse[431239]: 2020-02-17 08:57:17,738 - synapse.http.matrixfederationclient - 402 - INFO - POST-2084 - {PUT-O-357} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg; timeout 60.000000s
Feb 17 08:58:07 homeserver synapse[431239]: 2020-02-17 08:58:07,058 - synapse.http.site - 202 - WARNING - POST-2084 - Error processing request <XForwardedForRequest at 0x7f5b5039d4c0 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>: <class 'twisted.internet.error.ConnectionDone'> Connection was closed cleanly.
Feb 17 08:58:17 homeserver synapse[431239]: 2020-02-17 08:58:17,743 - synapse.http.matrixfederationclient - 432 - INFO - POST-2084 - Failed to send request: (60, 'Deferred')
Feb 17 08:58:17 homeserver synapse[431239]: 2020-02-17 08:58:17,743 - synapse.http.matrixfederationclient - 481 - WARNING - POST-2084 - {PUT-O-357} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg: TimeoutError(60, 'Deferred')
Feb 17 08:58:18 homeserver synapse[431239]: 2020-02-17 08:58:18,387 - synapse.http.matrixfederationclient - 402 - INFO - POST-2084 - {PUT-O-357} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg; timeout 60.000000s
Feb 17 08:59:18 homeserver synapse[431239]: 2020-02-17 08:59:18,391 - synapse.http.matrixfederationclient - 432 - INFO - POST-2084 - Failed to send request: (60, 'Deferred')
Feb 17 08:59:18 homeserver synapse[431239]: 2020-02-17 08:59:18,391 - synapse.http.matrixfederationclient - 481 - WARNING - POST-2084 - {PUT-O-357} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg: TimeoutError(60, 'Deferred')
Feb 17 08:59:19 homeserver synapse[431239]: 2020-02-17 08:59:19,749 - synapse.http.matrixfederationclient - 402 - INFO - POST-2084 - {PUT-O-357} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg; timeout 60.000000s
Feb 17 09:00:19 homeserver synapse[431239]: 2020-02-17 09:00:19,756 - synapse.http.matrixfederationclient - 432 - INFO - POST-2084 - Failed to send request: (60, 'Deferred')
Feb 17 09:00:19 homeserver synapse[431239]: 2020-02-17 09:00:19,756 - synapse.http.matrixfederationclient - 481 - WARNING - POST-2084 - {PUT-O-357} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg: TimeoutError(60, 'Deferred')
Feb 17 09:00:22 homeserver synapse[431239]: 2020-02-17 09:00:22,030 - synapse.http.matrixfederationclient - 402 - INFO - POST-2084 - {PUT-O-357} [matrix.org] Sending request: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg; timeout 60.000000s
Feb 17 09:01:20 homeserver synapse[431239]: 2020-02-17 09:01:20,225 - synapse.http.matrixfederationclient - 432 - INFO - POST-2084 - Failed to send request:
Feb 17 09:01:20 homeserver synapse[431239]: 2020-02-17 09:01:20,225 - synapse.http.matrixfederationclient - 481 - WARNING - POST-2084 - {PUT-O-357} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21vweUbuGmUUHSMspCVj%3Azell-mbc.com/%24E8eNHhYmdaLKx6kRjv1goNDTYyCbMXqEpzRfj8pvkMg: CancelledError()
Feb 17 09:01:20 homeserver synapse[431239]: 2020-02-17 09:01:20,228 - synapse.http.server - 106 - ERROR - POST-2084 - Failed handle request via 'RoomCreateRestServlet': <XForwardedForRequest at 0x7f5b5039d4c0 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>
Feb 17 09:01:20 homeserver synapse[431239]: 2020-02-17 09:01:20,231 - synapse.http.server - 462 - WARNING - POST-2084 - Not sending response to request <XForwardedForRequest at 0x7f5b5039d4c0 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>, already disconnected.
Feb 17 09:01:20 homeserver synapse[431239]: 2020-02-17 09:01:20,232 - synapse.access.http.8008 - 282 - INFO - POST-2084 - 46.223.117.217 - 8008 - {@thomas:zell-mbc.com} Processed request: 253.181sec/-193.174sec (0.105sec, 0.026sec) (0.049sec/0.215sec/34) 0B 200! "POST /_matrix/client/r0/createRoom HTTP/1.0" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Riot/1.5.8 Chrome/80.0.3987.86 Electron/8.0.1 Safari/537.36" [0 dbevts]
```

**Comment by richvdh** [comment]
that's odd; I don't see any of those requests reaching matrix.org. Can you try this on the server where you are running synapse:

```
curl -v --resolve matrix.org:8443:104.20.201.37 https://matrix.org:8443/_matrix/federation/v1/query/profile/
```

(it should give a 400 error)

**Comment by zell-mbc** [comment]
Thanks a lot for helping me out on this one Richard! Really apprechiated.

So maybe the problem is at my end after all?
I'll try to understand the output from the curl command myself, but in the meantime here's the data:

```
sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
443                        ALLOW       Anywhere                  
8448                       ALLOW       Anywhere                  
22                         ALLOW       175.0.0.0/24              
80                         ALLOW       Anywhere                  


thomas at homeserver in ~
$ curl -v --resolve matrix.org:8443:104.20.201.37 https://matrix.org:8443/_matrix/federation/v1/query/profile/
* Added matrix.org:8443:104.20.201.37 to DNS cache
* Hostname matrix.org was found in DNS cache
*   Trying 104.20.201.37:8443...
* TCP_NODELAY set
* Connected to matrix.org (104.20.201.37) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=www.matrix.org
*  start date: Dec 19 09:10:47 2019 GMT
*  expire date: Mar 18 09:10:47 2020 GMT
*  subjectAltName: host "matrix.org" matched cert's "matrix.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5570465c7740)
> GET /_matrix/federation/v1/query/profile/ HTTP/2
> Host: matrix.org:8443
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 400 
< date: Tue, 18 Feb 2020 10:08:08 GMT
< content-type: application/json
< content-length: 73
< set-cookie: __cfduid=d41e3814944252bb17f0da3db573ec19c1582020488; expires=Thu, 19-Mar-20 10:08:08 GMT; path=/; domain=.matrix.org; HttpOnly; SameSite=Lax
< cache-control: no-cache, no-store, must-revalidate
< access-control-allow-origin: *
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 566f32b7780f9796-FRA
< 
{
    "errcode": "M_UNRECOGNIZED",
    "error": "Unrecognized request"
}
* Connection #0 to host matrix.org left intact
```

**Comment by zell-mbc** [comment]
By the way, I created a room on my server, #test:zell-mbc.com, which people coming from matrix.org weren't able to join. You should run into the same problem when you try and maybe you can tell what's going on from the responses you get?

**Comment by richvdh** [comment]
the curl looks correct; can you also try it on ipv6:

```
curl -v --resolve matrix.org:8443:2606:4700:10::6814:c925 https://matrix.org:8443/_matrix/federation/v1/query/profile/
```

If that works you'll probably have to start tcpdumping traffic from synapse to see where it is going. Again I'd prefer to take this out of github: can you ping me in #synapse:matrix.org.

I get a timeout when trying to join your room from matrix.org, which is consistent with your server not being able to reach matrix.org.

**Comment by zell-mbc** [comment]
Issue turned out to be related to DNS name resolution on the Synapse server. I had an error in my /etc/resolv.conf file:
"84.200.69.80" instead of "nameserver 84.200.69.80"

The only explanation for this behaviour is that the lookup to matrix.org is handled differently to looking up other Synapse servers which made this a hard one to troubleshoot.

Big thank you for helping me along with this one!
