### ISSUE TITLE
500s in GroupRoomServlet

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#6929]
```
2020-02-15 21:04:33,923 - synapse.http.server - 110 - ERROR - GET-16407845 - Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f120c1b4d30 method='GET' uri='/_matrix/client/r0/groups/%2Bfreie-deutsche-gesellschaft%3Amatrix.org/rooms' clientproto='HTTP/1.1' site=8090>
Capture point (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/synapse/src/synapse/app/client_reader.py", line 208, in <module>
    start(sys.argv[1:])
  File "/home/synapse/src/synapse/app/client_reader.py", line 203, in start
    _base.start_worker_reactor("synapse-client-reader", config)
  File "/home/synapse/src/synapse/app/_base.py", line 77, in start_worker_reactor
    run_command=run_command,
  File "/home/synapse/src/synapse/app/_base.py", line 137, in start_reactor
    daemon.start()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/daemonize.py", line 248, in start
    self.action(*privileged_action_result)
  File "/home/synapse/src/synapse/app/_base.py", line 114, in run
    run_command()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/synapse/src/synapse/metrics/__init__.py", line 434, in f
    ret = func(*args, **kwargs)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
    f(*a, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
    status.deferred.callback(getattr(e, "value", None))
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1421, in _inlineCallbacks
    status.deferred.callback(getattr(e, "value", None))
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 460, in callback
    self._startRunCallbacks(result)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1464, in _inlineCallbacks
    status.deferred.errback()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
Traceback (most recent call last):
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [{'room_id': '!WrHhpWEwRjaSonyadI:matrix.org', 'is_public': True}, {'room_id': '!oBNzkjnCySBMpRzZew:matrix.org', 'is_public': True}, {'room_id': '!uYDFdGlBrclnbHlgOo:matrix.org', 'is_public': True}, {'room_id': '!MkEniGFZCXZcbPOPDl:matrix.org', 'is_public': True}, {'room_id': '!YmecfshIbUATzoHlPA:matrix.org', 'is_public': True}, {'room_id': '!FqajpHIvyQLEDYavDt:matrix.org', 'is_public': True}, {'room_id': '!eAkvFlfVfkVJOPGIFC:matrix.org', 'is_public': True}, {'room_id': '!MTHjXwGwOqxtMVzHSd:matrix.org', 'is_public': True}, {'room_id': '!fgDjQqhfLqVwdfLPRp:matrix.org', 'is_public': True}, {'room_id': '!myZdMAvmQHqzuCbktE:matrix.org', 'is_public': True}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/env-py37/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [{'room_id': '!WrHhpWEwRjaSonyadI:matrix.org', 'is_public': True}, {'room_id': '!oBNzkjnCySBMpRzZew:matrix.org', 'is_public': True}, {'room_id': '!uYDFdGlBrclnbHlgOo:matrix.org', 'is_public': True}, {'room_id': '!MkEniGFZCXZcbPOPDl:matrix.org', 'is_public': True}, {'room_id': '!YmecfshIbUATzoHlPA:matrix.org', 'is_public': True}, {'room_id': '!FqajpHIvyQLEDYavDt:matrix.org', 'is_public': True}, {'room_id': '!eAkvFlfVfkVJOPGIFC:matrix.org', 'is_public': True}, {'room_id': '!MTHjXwGwOqxtMVzHSd:matrix.org', 'is_public': True}, {'room_id': '!fgDjQqhfLqVwdfLPRp:matrix.org', 'is_public': True}, {'room_id': '!myZdMAvmQHqzuCbktE:matrix.org', 'is_public': True}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/src/synapse/util/caches/descriptors.py", line 438, in _wrapped
    cached_result_d = cache.get(cache_key, callback=invalidate_callback)
  File "/home/synapse/src/synapse/util/caches/descriptors.py", line 160, in get
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/synapse/src/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/home/synapse/src/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/home/synapse/src/synapse/rest/client/v2_alpha/groups.py", line 329, in on_GET
    group_id, requester_user_id
AttributeError: 'NoneType' object has no attribute 'content'
```

This is killing someone who's deeplinking to the page for this community

**Comment by richvdh** [comment]
dup #4891
