### ISSUE TITLE
Can't leave room (During auth for event xxx in room AAA, found event yyy in the state which is in room DDD

### ISSUE THREAD

**Issue by worldowner** [matrix-org/synapse#6975]
### Steps to reproduce

- try to leave a room
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

When I try to leave a room an error occurs:
```Exception: During auth for event xxx in room AAA, found event yyy in the state which is in room DDD```

I saw a similar issue (#6779) so I executed:
```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
1026|AAA|$TCEpeTnKju0qBX__XNpo1WPrTkgnm0z6q3rozDYZiiI|1026|1025|1025|CCC|$gR7bue4-Pw5WrPPn-Jizm_8LJSw7lNQFui5MD_C9PZw
1027|BBB|$ail6Ea3drYx6xsvs3sun3pYW4vkYOf034fv8TmlIs0k|1027|1025|1025|CCC|$gR7bue4-Pw5WrPPn-Jizm_8LJSw7lNQFui5MD_C9PZw
1028|BBB|$ail6Ea3drYx6xsvs3sun3pYW4vkYOf034fv8TmlIs0k|1028|1026|1026|AAA|$TCEpeTnKju0qBX__XNpo1WPrTkgnm0z6q3rozDYZiiI

sqlite> select * from state_group_edges where state_group=1026;
1026|1025
1026|1024
sqlite> select * from state_group_edges where state_group=1027;
1027|1025
sqlite> select * from state_group_edges where state_group=1028;
1028|1026
1028|1027
```

Please note that channel DDD from log is not in the result of above query.
I tried to DELETE various combinations but I've never got it fixed. Can you let me know what should I do to fix it?

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.11.0

- **Install method**: avhost/docker-matrix
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Docker on Debian Linux
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by richvdh** [comment]
can you do 

```
select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
```

please can you use triple-backticks (```) to format the pasted output to make it legible. See https://guides.github.com/features/mastering-markdown/.

**Comment by worldowner** [comment]
Sure:

```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
1026|AAA|$TCEpeTnKju0qBX__XNpo1WPrTkgnm0z6q3rozDYZiiI|1026|1025|1025|CCC|$gR7bue4-Pw5WrPPn-Jizm_8LJSw7lNQFui5MD_C9PZw
1027|BBB|$ail6Ea3drYx6xsvs3sun3pYW4vkYOf034fv8TmlIs0k|1027|1025|1025|CCC|$gR7bue4-Pw5WrPPn-Jizm_8LJSw7lNQFui5MD_C9PZw
1028|BBB|$ail6Ea3drYx6xsvs3sun3pYW4vkYOf034fv8TmlIs0k|1028|1026|1026|AAA|$TCEpeTnKju0qBX__XNpo1WPrTkgnm0z6q3rozDYZiiI
```

There are 3 room_id in the result which I replaced with AAA, BBB, CCC. 4th is in the log:

```
Exception: During auth for event xxx in room AAA, found event yyy in the state which is in room DDD
```

I hope my replace didn't make it a lot harder.
I also edited initial report to make formatting better.

**Comment by richvdh** [comment]
ok. there are some bad rows there so I suggest deleting them, restarting, and seeing what happens. It may not fix the problem but it can't make things worse:

```sql
DELETE FROM state_group_edges WHERE
   (state_group=1026 AND prev_state_group=1025) OR
   (state_group=1027 AND prev_state_group=1025) OR
   (state_group=1028 AND prev_state_group=1026);
```

**Comment by worldowner** [comment]
I still can't leave the room. The query returns nothing through.

```
sqlite> select * from state_groups sg1 join state_group_edges sge on sge.state_group=sg1.id join state_groups sg2 on sg2.id=sge.prev_state_group where sg2.room_id != sg1.room_id;
sqlite>
```

When I try to leave the room exception is generated:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {'$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs': <FrozenEventV3 event_id='$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs', type='m.room.member', state_key='@MYUSER:local_server'>, '$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4': <FrozenEventV3 event_id='$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4', type='m.room.power_levels', state_key=''>, '$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU': <FrozenEventV3 event_id='$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU', type='m.room.create', state_key=''>}

During handling of the above exception, another exception occurred:

020-02-24 14:21:59,423 - synapse.http.server - 110 - ERROR - POST-159- Failed handle request via 'RoomMembershipRestServlet': <XForwardedForRequest at 0x7f6199084470 method='POST' uri='/_matrix/client/r0/rooms/AAA/leave' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: 1084

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: 1084

[...]

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/usr/local/lib/python3.7/dist-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/usr/local/lib/python3.7/dist-packages/synapse/rest/client/v1/room.py", line 750, in on_POST
    content=event_content,
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/dist-packages/synapse/handlers/room_member.py", line 283, in update_membership
    require_consent=require_consent,
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/dist-packages/synapse/handlers/room_member.py", line 489, in _update_membership
    require_consent=require_consent,
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/dist-packages/synapse/handlers/room_member.py", line 193, in _local_membership_update
    requester, event, context, extra_users=[target], ratelimit=ratelimit
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/dist-packages/synapse/util/metrics.py", line 82, in measured_func
    r = yield func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/dist-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/dist-packages/synapse/handlers/message.py", line 808, in handle_new_client_event
    yield self.auth.check_from_context(room_version, event, context)
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/dist-packages/synapse/api/auth.py", line 93, in check_from_context
    room_version_obj, event, auth_events=auth_events, do_sig_check=do_sig_check
  File "/usr/local/lib/python3.7/dist-packages/synapse/event_auth.py", line 74, in check
    % (event.event_id, room_id, auth_event.event_id, auth_event.room_id)
Exception: During auth for event xxx in room AAA, found event yyy in the state which is in room DDD
```

I don't know if that matters but AAA channel is on remote, federated server (AAA:remote_server).

It looks that server sees wrong members of the channel:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: (<FrozenEventV3 event_id='$G2iy2xtbkSgdkO6MqtPpnL8mePn6mF3M1_rnLqFccRs', type='m.room.member', state_key='@MYUSER:local_server'>, EventContext(rejected=False, _state_group=1084, state_group_before_event=1024, prev_group=1024, delta_ids={('m.room.member', '@MYUSER:local_server'): '$G2iy2xtbkSgdkO6MqtPpnL8mePn6mF3M1_rnLqFccRs'}, app_service=None, _current_state_ids={('m.room.create', ''): '$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU', ('m.room.encryption', ''): '$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ', ('m.room.guest_access', ''): '$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI', ('m.room.history_visibility', ''): '$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk', ('m.room.join_rules', ''): '$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4', ('m.room.power_levels', ''): '$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4', ('m.room.retention', ''): '$dQDvz_fa45jXf-rdG_Aourdq5ZMl1B_zkYW_MIBECfw', ('m.room.member', '@MYUSER:local_server'): '$G2iy2xtbkSgdkO6MqtPpnL8mePn6mF3M1_rnLqFccRs', ('m.room.member', '@WRONGUSER@remote_Server'): '$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8'}, _prev_state_ids=<frozendict {('m.room.create', ''): '$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU', ('m.room.encryption', ''): '$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ', ('m.room.guest_access', ''): '$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI', ('m.room.history_visibility', ''): '$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk', ('m.room.join_rules', ''): '$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4', ('m.room.power_levels', ''): '$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4', ('m.room.retention', ''): '$dQDvz_fa45jXf-rdG_Aourdq5ZMl1B_zkYW_MIBECfw', ('m.room.member', '@MYUSER:local_server'): '$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs', ('m.room.member', '@WRONGUSER:remote_server'): '$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8'}>))
```
@WRONGUSER:remote_server' is not a member of the channel I want to leave.

After I clear cache in Riot (locally hosted 1.5.10) I see him on the list of members but after browser restart he is gone. This doesn't happen on Android client though.

**Comment by richvdh** [comment]
ok,  let's check some other places:

can you also do:

```sql
SELECT * FROM state_groups_state sgs, events e 
WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
```

(that might take ages if you have a big database: you can optionally add `AND sgs.room_id='AAA'` to the query)

and

```sql
SELECT * FROM current_state_events cse, events e 
WHERE e.event_id=cse.event_id AND e.room_id != cse.room_id;
```

(again, optionally add `AND cse.room_id='AAA'`)

**Comment by worldowner** [comment]
My db is not big so both queries executed quickly. The first result is:

```
sqlite> SELECT * FROM state_groups_state sgs, events e WHERE e.event_id=sgs.event_id AND e.room_id != sgs.room_id;
1024|AAA|m.room.create||$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU|89651|1|$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU|m.room.create|DDD|||1|1|1|1581689811162|1581689842229|@wronguser:remote_server|0
1024|AAA|m.room.join_rules||$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4|89654|4|$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4|m.room.join_rules|DDD|||1|1|4|1581689812749|1581689842229|@wronguser:remote_server|0
1024|AAA|m.room.member|@MYUSER:local_server|$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs|89662|8|$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs|m.room.member|DDD|||1|1|8|1581689841528|1581689842303|@MYUSER:local_server|0
1024|AAA|m.room.member|@wronguser:remote_server|$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8|89652|2|$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8|m.room.member|DDD|||1|1|2|1581689811802|1581689842229|@wronguser:remote_server|0
1024|AAA|m.room.power_levels||$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4|89653|3|$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4|m.room.power_levels|DDD|||1|1|3|1581689812240|1581689842229|@wronguser:remote_server|0
1024|AAA|m.room.encryption||$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ|89663|9|$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ|m.room.encryption|DDD|||1|1|9|1581689844875|1581689845171|@wronguser:remote_server|0
1024|AAA|m.room.guest_access||$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI|89661|6|$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI|m.room.guest_access|DDD|||1|1|6|1581689813658|1581689842229|@wronguser:remote_server|0
1024|AAA|m.room.history_visibility||$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk|89664|10|$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk|m.room.history_visibility|DDD|||1|1|10|1581689860934|1581689860957|@MYUSER:local_server|0
1025|CCC|m.room.create||$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU|89651|1|$Hb5kcDGmR7Trk_9iIHHTcsjnI9CJ3Q2kZlb71uIGhxU|m.room.create|DDD|||1|1|1|1581689811162|1581689842229|@wronguser:remote_server|0
1025|CCC|m.room.encryption||$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ|89663|9|$3QLRrGvsPAq5bwNFqwzyQk9SUsBGO4Im3XIhzGeDEDQ|m.room.encryption|DDD|||1|1|9|1581689844875|1581689845171|@wronguser:remote_server|0
1025|CCC|m.room.guest_access||$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI|89661|6|$1jLliY8sahKBAZ-UzETp3rDiqMIOD4Wad1f0-umMAAI|m.room.guest_access|DDD|||1|1|6|1581689813658|1581689842229|@wronguser:remote_server|0
1025|CCC|m.room.history_visibility||$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk|89664|10|$LzjuUAGntXGXHd92JqFLaoD9RqyFOj0fh8cGpCAONsk|m.room.history_visibility|DDD|||1|1|10|1581689860934|1581689860957|@MYUSER:local_server|0
1025|CCC|m.room.join_rules||$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4|89654|4|$Kcz7QgVztKlyahqsPw_7WOmBUNqXhgECYVjP-VfCcX4|m.room.join_rules|DDD|||1|1|4|1581689812749|1581689842229|@wronguser:remote_server|0
1025|CCC|m.room.member|@MYUSER:local_server|$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs|89662|8|$anTBNP3OwPZHN9IcZBkLioe8qovF3JMVrU8w2MvjcVs|m.room.member|DDD|||1|1|8|1581689841528|1581689842303|@MYUSER:local_server|0
1025|CCC|m.room.member|@wronguser:remote_server|$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8|89652|2|$FpX4ecq1bXnsLmaXrvYEkDydezB20lkOAo4FzlB1KB8|m.room.member|DDD|||1|1|2|1581689811802|1581689842229|@wronguser:remote_server|0
1025|CCC|m.room.power_levels||$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4|89653|3|$O2xtR9df2i2bFLWK9aAmboSZAritVmwjsr66JtVN3Z4|m.room.power_levels|DDD|||1|1|3|1581689812240|1581689842229|@wronguser:remote_server|0
```
Second query returned nothing:
```
sqlite> SELECT * FROM current_state_events cse, events e WHERE e.event_id=cse.event_id AND e.room_id != cse.room_id;
sqlite> 
```

**Comment by richvdh** [comment]
ok, I suggest removing those rows:

```sql
DELETE FROM state_groups_state WHERE EXISTS (
SELECT 1 FROM events e WHERE e.event_id=state_groups_state.event_id AND e.room_id!=state_groups_state.room_id); 
```

restart synapse afterwards.

**Comment by worldowner** [comment]
Currently I have 2 errors:

```
2020-02-24 16:38:37,760 - synapse.http.server - 81 - INFO - GET-430- <XForwardedForRequest at 0x7f431b8ace10 method='GET' uri='/_matrix/client/r0/rooms/AAA/messages?from=s91116_646715_0_93038_85073_12_23764_260_1&limit=20&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site=8008> SynapseError: 403 - User @MYUSER:local_server not in room AAA, and room previews are disabled
2020-02-24 16:38:37,762 - synapse.access.http.8008 - 302 - INFO - GET-430- 89.79.119.196 - 8008 - {@MYUSER:local_server} Processed request: 0.003sec/0.000sec (0.004sec, 0.000sec) (0.000sec/0.000sec/0) 141B 403 "GET /_matrix/client/r0/rooms/AAA/messages?from=s91116_646715_0_93038_85073_12_23764_260_1&limit=20&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0" [0 dbevts]
```

and when trying to leave:

```
2020-02-24 16:51:33,046 - synapse.access.http.8008 - 302 - INFO - OPTIONS-108- 89.79.119.196 - 8008 - {None} Processed request: 0.000sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 22B 200 "OPTIONS /_matrix/client/r0/rooms/AAA/leave HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0" [0 dbevts]
2020-02-24 16:51:33,076 - synapse.http.server - 81 - INFO - POST-109- <XForwardedForRequest at 0x7fc5319e57b8 method='POST' uri='/_matrix/client/r0/rooms/AAA/leave' clientproto='HTTP/1.1' site=8008> SynapseError: 404 - Not a known room
2020-02-24 16:51:33,077 - synapse.access.http.8008 - 302 - INFO - POST-109- 89.79.119.196 - 8008 - {@MYUSER:local_server} Processed request: 0.004sec/0.000sec (0.000sec, 0.000sec) (0.001sec/0.001sec/1) 66B 404 "POST /_matrix/client/r0/rooms/AAA/leave HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0" [0 dbevts]
```

I also tried to remove the room via purge_api, but is says that users are still joined.

I can't remove even an empty room (I tried this on several empty rooms), but that's probably separate issue:
```
2020-02-24 16:45:24,818 - synapse.http.server - 81 - INFO - POST-621- <XForwardedForRequest at 0x7f431b9f4198 method='POST' uri='/_synapse/admin/v1/purge_room' clientproto='HTTP/1.1' site=8008> SynapseError: 404 - Unknown room SOME_ROOM:local_server
2020-02-24 16:45:24,819 - synapse.access.http.8008 - 302 - INFO - POST-621- 172.18.0.1 - 8008 - {@MYUSER:local_server} Processed request: 0.006sec/0.000sec (0.004sec, 0.000sec) (0.001sec/0.001sec/3) 91B 404 "POST /_synapse/admin/v1/purge_room HTTP/1.1" "curl/7.52.1" [0 dbevts]
```
I'm mentioning this here because I don't know if it is related.

**Comment by worldowner** [comment]
I assigned proper room_version to wrong channels, deleted entries from current_state_events for that broken rooms and then used purge_room api on them (I wanted to leave them anyway so I didn't care). So my personal issue is solved. Thank you for helping.
