### ISSUE TITLE
blocked room in group_rooms blocks listing of the community room list

### ISSUE THREAD

**Issue by airblag** [matrix-org/synapse#7097]
### Description

Two communities on my homeserver where not able to display the room list in riot (rolling circle animation never stops).
It shows in the logs of synapse this :

```
2020-03-16 12:30:36,168 - synapse.http.server - 110 - ERROR - GET-8088028- Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7fbe1e0796a0 method='GET' uri='/_matrix/client/r0/groups/%2Bdesk%3Amatrix.example.org/rooms' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [{'room_id': '!XxXxXxXxXxXxXxZrdt:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxCDNg:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxsbEE:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxBEhg:matrix.example.org
', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxgppS:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxmFNE:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxFpTn:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxIFYD:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxmxCs:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxkHBS:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxLBUJ:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxDEWL:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxXXKK:matrix.example.org', 'is_public': False}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [{'room_id': '!XxXxXxXxXxXxXxZrdt:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxCDNg:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxsbEE:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxBEhg:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxgppS:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxmFNE:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxFpTn:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxIFYD:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxmxCs:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxkHBS:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxLBUJ:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxDEWL:matrix.example.org', 'is_public': False}, {'room_id': '!XxXxXxXxXxXxXxXXKK:matrix.example.org', 'is_public': False}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/descriptors.py", line 438, in _wrapped
    cached_result_d = cache.get(cache_key, callback=invalidate_callback)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/util/caches/descriptors.py", line 160, in get
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/groups.py", line 329, in on_GET
    group_id, requester_user_id
AttributeError: 'NoneType' object has no attribute 'content'
```
Looking at the DB :
```
SELECT * from group_rooms, rooms where group_rooms.group_id='+desk:matrix.example.org' and rooms.room_id=group_rooms.room_id;
      group_id       |              room_id              | is_public |              room_id              | is_public |          creator          | room_version 
---------------------+-----------------------------------+-----------+-----------------------------------+-----------+---------------------------+--------------
 +desk:matrix.example.org | !XxXxXxXxXxXxXxZrdt:matrix.example.org | f         | !XxXxXxXxXxXxXxZrdt:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxCDNg:matrix.example.org | f         | !XxXxXxXxXxXxXxCDNg:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxsbEE:matrix.example.org | f         | !XxXxXxXxXxXxXxsbEE:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxBEhg:matrix.example.org | f         | !XxXxXxXxXxXxXxBEhg:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxgppS:matrix.example.org | f         | !XxXxXxXxXxXxXxgppS:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxmFNE:matrix.example.org | f         | !XxXxXxXxXxXxXxmFNE:matrix.example.org | t         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxFpTn:matrix.example.org | f         | !XxXxXxXxXxXxXxFpTn:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxIFYD:matrix.example.org | f         | !XxXxXxXxXxXxXxIFYD:matrix.example.org | f         | @user:matrix.example.org        | 
 +desk:matrix.example.org | !XxXxXxXxXxXxXxmxCs:matrix.example.org | f         | !XxXxXxXxXxXxXxmxCs:matrix.example.org | t         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxkHBS:matrix.example.org | f         | !XxXxXxXxXxXxXxkHBS:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxLBUJ:matrix.example.org | f         | !XxXxXxXxXxXxXxLBUJ:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxDEWL:matrix.example.org | f         | !XxXxXxXxXxXxXxDEWL:matrix.example.org | f         | @user:matrix.example.org        | 1
 +desk:matrix.example.org | !XxXxXxXxXxXxXxXXKK:matrix.example.org | f         | !XxXxXxXxXxXxXxXXKK:matrix.example.org | t         | @user:matrix.example.org        | 5

```
The room : !XxXxXxXxXxXxXxIFYD:matrix.example.org is not having a field "room_version"
After trying to join it, riot informs me that the room has been blocked on this server.

I removed references to this room from group_rooms to solve it 
`delete from group_rooms where room_id='!XxXxXxXxXxXxXxIFYD:matrix.example.org';`

### Steps to reproduce

- Add a room to a comunity
- Block this room on the server with /_matrix/client/unstable/admin/shutdown_room/$roomid
- room list of the community should not show up anymore

### Version information

- **Homeserver**: 
self hosted

- **Version**:
matrix-synapse-py3 1.11.1+buster1 amd64   
```
{
    "python_version": "3.7.3",
    "server_version": "1.11.1"
}
```

- **Install method**:

apt,  packages.matrix.org

**Comment by richvdh** [comment]
dup #4891
