### ISSUE TITLE
Failed to handle edu 'm.receipt'

### ISSUE THREAD

**Issue by dajohi** [matrix-org/synapse#7111]
### Description
```
2020-03-20 02:32:34,548 - synapse.federation.federation_server - 832 - ERROR - PUT-75910- Failed to handle edu 'm.receipt'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: 1584650095267

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 828, in on_edu
    await handler(origin, content)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/receipts.py", line 65, in _received_remote_receipt
    await self._handle_new_receipts(receipts)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/receipts.py", line 79, in _handle_new_receipts
    receipt.data,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/receipts.py", line 473, in insert_receipt
    stream_id=stream_id,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/database.py", line 499, in runInteraction
    after_callback(*after_args, **after_kwargs)
  File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/receipts.py", line 310, in _invalidate_get_users_with_receipts_in_room
    if res and user_id in res:
TypeError: argument of type 'ObservableDeferred' is not iterable
2020-03-20 02:32:34,841 - synapse.metrics - 462 - INFO - - Collecting gc 1

```

### Steps to reproduce

upgraded from 1.3.1 to 1.11.1

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

matrix.decred.org

1.11.1

docker

<!-- examples: package manager/git clone/pip  -->

linux

**Comment by richvdh** [comment]
#3234
