### ISSUE TITLE
Internal Server Error on /groups/<group>/rooms endpoint

### ISSUE THREAD

**Issue by bwindels** [matrix-org/synapse#7114]
Reported at https://github.com/vector-im/riot-web/issues/12714#issuecomment-601633142

Synapse logs:
```
Mar 19 22:57:57 matrix matrix-synapse[6661]: 2020-03-19 22:57:57,852 - synapse.http.server - 110 - ERROR - GET-19535 - Failed handle request via 'GroupRoomServlet': <XForwardedForRequest at 0x7f000e4b1240 method='GET' uri='/_matrix/client/r0/groups/%2Boxidize1k%3Achat.berline.rs/rooms' clientproto='HTTP/1.0' site=8008>
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar 19 22:57:57 matrix matrix-synapse[6661]:     result = g.send(result)
Mar 19 22:57:57 matrix matrix-synapse[6661]: StopIteration: [{'room_id': '!KZwlWkhTSkUNDrquFg:chat.berline.rs', 'is_public': False}, {'room_id': '!LSJjLKsbWZqdvBuXJa:chat.berline.rs', 'is_public': False}, {'room_id': '!UJDBxLRJoRCeIlROCH:chat.berline.rs', 'is_public': False}, {'room_id': '!wJFqQvoWQaskEAMzoB:chat.berline.rs', 'is_public': False}, {'room_id': '!G
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar 19 22:57:57 matrix matrix-synapse[6661]:     result = g.send(result)
Mar 19 22:57:57 matrix matrix-synapse[6661]: StopIteration: [{'room_id': '!KZwlWkhTSkUNDrquFg:chat.berline.rs', 'is_public': False}, {'room_id': '!LSJjLKsbWZqdvBuXJa:chat.berline.rs', 'is_public': False}, {'room_id': '!UJDBxLRJoRCeIlROCH:chat.berline.rs', 'is_public': False}, {'room_id': '!wJFqQvoWQaskEAMzoB:chat.berline.rs', 'is_public': False}, {'room_id': '!G
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/caches/descriptors.py", line 438, in _wrapped
Mar 19 22:57:57 matrix matrix-synapse[6661]:     cached_result_d = cache.get(cache_key, callback=invalidate_callback)
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/util/caches/descriptors.py", line 160, in get
Mar 19 22:57:57 matrix matrix-synapse[6661]:     raise KeyError()
Mar 19 22:57:57 matrix matrix-synapse[6661]: KeyError
Mar 19 22:57:57 matrix matrix-synapse[6661]: During handling of the above exception, another exception occurred:
Mar 19 22:57:57 matrix matrix-synapse[6661]: Traceback (most recent call last):
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
Mar 19 22:57:57 matrix matrix-synapse[6661]:     await h(self, request)
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/http/server.py", line 331, in _async_render
Mar 19 22:57:57 matrix matrix-synapse[6661]:     callback_return = await callback_return
Mar 19 22:57:57 matrix matrix-synapse[6661]:   File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/synapse/rest/client/v2_alpha/groups.py", line 329, in on_GET
Mar 19 22:57:57 matrix matrix-synapse[6661]:     group_id, requester_user_id
Mar 19 22:57:57 matrix matrix-synapse[6661]: AttributeError: 'NoneType' object has no attribute 'content'
```

**Comment by richvdh** [comment]
#4891
