### ISSUE TITLE
Failed to send_join via matrix.org (or any server) when joining #freenode_#trains:matrix.org

### ISSUE THREAD

**Issue by GuillaumeDIDIER** [matrix-org/synapse#7122]
### Description

When I attempt to join #freenode_#trains:matrix.org (aka #trains on FreeNode), the IRC a--service successfully joins my puppet (people on IRC believe I'm there), but I get an error message on my matrix client, and errors in the home server log.

My Homeserver is up to date using pip.

### Steps to reproduce

- `/join #freenode_#trains:matrix.org`
- wait a short while
- get error message `Failed to send_join via any server` on riot, no room joined.

Expected behaviour : no error message, join a room.

Logs : Too big to be inlined, attached. (Has some very long lines)
[homeserver.bug.log](https://github.com/matrix-org/synapse/files/4362577/homeserver.bug.log)

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information
- **Homeserver**: matrix.sobex.net (plus joining a channel on matrix.org)

- **Version**: {"server_version": "1.11.1", "python_version": "3.6.9"}

- **Install method**: pip / virtualenv
- **Platform**: gentoo / linux on a dedicated server.

**Comment by GuillaumeDIDIER** [comment]
Redacting the three long lines I get :
```
2020-03-21 08:13:50,664 - synapse.federation.federation_client - 421 - WARNING - POST-710 - Failed to send_join via matrix.org
Traceback (most recent call last):
  File "/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <long line redacted>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <long line redacted>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: <long line redacted>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/synapse/venv3/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 402, in _try_destination_list
    res = await callback(destination)
  File "/srv/synapse/venv3/lib/python3.6/site-packages/synapse/federation/federation_client.py", line 586, in send_request
    room_version=room_version.identifier,
  File "/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py", line 749, in send
    raise result.value
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'synapse.api.errors.SynapseError'>: 403: event id $145016016174178MeitS:matrix.org: unable to verify signature for sender whatthefuck.computer: 400: Not signed by whatthefuck.computer
/srv/synapse/venv3/lib/python3.6/site-packages/synapse/federation/federation_base.py:151:_check_sigs_and_hashes
/srv/synapse/venv3/lib/python3.6/site-packages/synapse/federation/federation_base.py:291:_check_sigs_on_pdus
/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py:333:addErrback
/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py:311:addCallbacks
--- <exception caught here> ---
/srv/synapse/venv3/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/srv/synapse/venv3/lib/python3.6/site-packages/synapse/federation/federation_base.py:288:sender_err
]]
```

**Comment by ssbothwell** [comment]
I'm getting this error on `1.12.4`

**Comment by reivilibre** [comment]
I think this would have been improved by work in lazy federated joins, plus error messages have been slightly improved as far as I know.
