### ISSUE TITLE
Cyclic dependency while building tcp_replication error in 1.12.0

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#7169]
Updating to 1.12.0 from 1.11.0 today, and found that my synchronous have stopped working and are displaying this error when handling requests. I can't see any warnings in CHANGES.md of package breakages so I'm not sure what's going on here.

```
2020-03-30 11:03:19,111 - synapse.http.server - 110 - ERROR - GET-292- Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f0da79160f0 method='GET' uri='/_matrix/client/r0/sync?filter=174&timeout=30000&since=s36342669_269113417_0_17571341_303994_1359_188889_1109467_48' clientproto='HTTP/1.0' site=8018>
Traceback (most recent call last):
  File "/opt/synapse/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/opt/synapse/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/opt/synapse/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/sync.py", line 96, in on_GET
    requester = await self.auth.get_user_by_req(request, allow_guest=True)
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/synapse/lib/python3.7/site-packages/synapse/api/auth.py", line 232, in get_user_by_req
    device_id=device_id,
  File "/opt/synapse/lib/python3.7/site-packages/synapse/replication/slave/storage/client_ips.py", line 47, in insert_client_ip
    self.hs.get_tcp_replication().send_user_ip(
  File "/opt/synapse/lib/python3.7/site-packages/synapse/server.py", line 565, in _get
    raise ValueError("Cyclic dependency while building %s" % (depname,))
ValueError: Cyclic dependency while building tcp_replication
```

**Comment by Half-Shot** [comment]
Rolling back to 1.11.0 seemed to fix this, so something may have changed.

**Comment by richvdh** [comment]
I think this is just a symptom of #7130. I'll raise a PR to fix the confusing error message though.
