### ISSUE TITLE
Inbound federation worker crashed with "Workers cannot send federation traffic" on 1.12.0

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#7170]
Not sure why it's trying to do this, or if it's a misconfigration. This was working on 1.11.0 and seems to have stopped when I upgraded to 1.12.0.

```
2020-03-30 11:07:26,668 - synapse.storage.data_stores.main.event_push_actions - 511 - INFO - None- Found stream ordering 1 day ago: it's 36326079
2020-03-30 11:07:26,739 - synapse.storage.data_stores - 68 - INFO - None- Starting 'state' data store
2020-03-30 11:07:26,746 - synapse.storage.data_stores - 81 - INFO - None- Database 'master' prepared
2020-03-30 11:07:26,747 - synapse.server - 243 - INFO - None- Finished setting up.
2020-03-30 11:07:26,750 - synapse.app.federation_reader - 110 - INFO - - Running
2020-03-30 11:07:26,751 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 524288
2020-03-30 11:07:26,751 - synapse.config.tls - 494 - INFO - - Loading TLS certificate from /etc/letsencrypt/live/reckless.half-shot.uk/fullchain.pem
2020-03-30 11:07:26,770 - synapse.app.generic_worker - 238 - INFO - - Presence process_id is 'kDnIJBEVcbbjIeAD'
2020-03-30 11:07:26,770 - synapse.push.pusher - 42 - INFO - - email enable notifs: False
2020-03-30 11:07:26,771 - twisted - 192 - ERROR - - Traceback (most recent call last):
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 277, in start
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -     hs.start_listening(listeners)
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/generic_worker.py", line 553, in start_listening
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -     self._listen_http(listener)
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/generic_worker.py", line 495, in _listen_http
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -     resources.update({FEDERATION_PREFIX: TransportLayerServer(self)})
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/federation/transport/server.py", line 76, in __init__
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -     self.authenticator = Authenticator(hs)
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/federation/transport/server.py", line 116, in __init__
2020-03-30 11:07:26,772 - twisted - 192 - ERROR - -     self.replication_client = hs.get_tcp_replication()
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/server.py", line 568, in _get
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     dep = builder()
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/generic_worker.py", line 581, in build_tcp_replication
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     return GenericWorkerReplicationHandler(self)
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/generic_worker.py", line 604, in __init__
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     self.send_handler = FederationSenderHandler(hs, self)
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/generic_worker.py", line 734, in __init__
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     self.federation_sender = hs.get_federation_sender()
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/server.py", line 568, in _get
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     dep = builder()
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -   File "/opt/synapse/lib/python3.7/site-packages/synapse/server.py", line 445, in build_federation_sender
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - -     raise Exception("Workers cannot send federation traffic")
2020-03-30 11:07:26,773 - twisted - 192 - ERROR - - Exception: Workers cannot send federation traffic
2020-03-30 11:07:26,774 - twisted - 192 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/base.py", line 1282, in run
    self.startRunning(installSignalHandlers=installSignalHandlers)
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/base.py", line 1262, in startRunning
    ReactorBase.startRunning(self)
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/base.py", line 770, in startRunning
    self.fireSystemEvent('startup')
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/base.py", line 721, in fireSystemEvent
    event.fireEvent()
--- <exception caught here> ---
  File "/opt/synapse/lib/python3.7/site-packages/twisted/internet/base.py", line 428, in fireEvent
    result = callable(*args, **kwargs)
  File "/opt/synapse/lib/python3.7/site-packages/synapse/app/_base.py", line 297, in start
    sys.exit(1)
builtins.SystemExit: 1
```

**Comment by Half-Shot** [comment]
Rolling back to 1.11.0 seemed to fix this, so something may have changed.

**Comment by richvdh** [comment]
this is a dup of #7130
