### ISSUE TITLE
Twisted Tests

### ISSUE THREAD

**Issue by Zay11Zay** [matrix-org/synapse#7218]
### Description
Twisted test suite doesn't pass after fresh clone and install

### Steps to reproduce
Steps from the Synapse Development portion of the README
- git clone https://github.com/matrix-org/synapse.git
- cd synapse

- virtualenv -p python3 env
- source env/bin/activate
python -m pip install --no-use-pep517 -e ".[all]"
python -m twisted.trial tests

Ran 907 tests in 41.853s
FAILED (skips=1, errors=610, successes=296)

I guess I was expecting them to pass off a fresh clone, is there something I'm doing wrong? Thanks!
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**:

- **Install method**:
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
@Zay11Zay Can you confirm what branch/commit you're on and post (some of) the logs from the failing test?

**Comment by Zay11Zay** [comment]
Sure!
Branch: master, whatever is the latest commit


A lot of the errors look similar to: 
```[ERROR]
Traceback (most recent call last):
  File "/home/ICChat/vanilla_synapse/synapse/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/util/patch_inline_callbacks.py", line 146, in check_yield_points_inner
    d = gen.send(result)
  File "/home/ICChat/vanilla_synapse/synapse/tests/api/test_filtering.py", line 56, in setUp
    keyring=Mock(),
  File "/home/ICChat/vanilla_synapse/synapse/tests/utils.py", line 268, in setup_test_homeserver
    hs.setup()
  File "/home/ICChat/vanilla_synapse/synapse/synapse/server.py", line 242, in setup
    self.datastores = DataStores(self.DATASTORE_CLASS, self)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/data_stores/__init__.py", line 47, in __init__
    with make_conn(database_config, engine) as db_conn:
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/database.py", line 102, in make_conn
    engine.on_new_connection(db_conn)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/engines/sqlite.py", line 85, in on_new_connection
    prepare_database(db_conn, self, config=None)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/prepare_database.py", line 88, in prepare_database
    _setup_new_database(cur, database_engine, data_stores=data_stores)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/prepare_database.py", line 218, in _setup_new_database
    is_empty=True,
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/prepare_database.py", line 405, in _upgrade_existing_database
    executescript(cur, absolute_path)
  File "/home/ICChat/vanilla_synapse/synapse/synapse/storage/prepare_database.py", line 540, in executescript
    txn.execute(statement)
sqlite3.OperationalError: no such function: json_extract```

I'm assuming it has something to do with the database.

**Comment by clokep** [comment]
Looks like your sqlite is missing the `json_extract` extension, it might be too old (or doesn't have support for that compiled for some reason). Poking around a little it sounds like support for this was added in 3.9 of sqlite.

**Comment by richvdh** [comment]
oh yeah, apparently some distros ship sqlite without the json extension.

**Comment by richvdh** [comment]
I think we could possibly rewrite the database migration to avoid `json_extract`, but unless it affects more than a handful of people I don't think it's a huge problem.
