### ISSUE TITLE
Crash in synapse triggered by user request

### ISSUE THREAD

**Issue by foldleft** [matrix-org/synapse#7247]
### Description

I managed to crash synapse, I think.  I didn't note the sequence of events so I'm not sure if I killed the server myself after (it got a SIGINT), but I certainly started getting weird responses from server

### Steps to reproduce

- I logged in with an old-ish test account
- I logged in a second session and tried to verify it. Instead, synapse crashed

```
2020-04-08 12:54:18,459 - synapse.access.http.8008 - 302 - INFO - GET-63733 - - - 8008 - {@test5:localhost} Processed request: 0.006sec/0.000sec (0.001sec, 0.001sec) (0.001sec/0.003sec/2) 465B 200 "GET /_matrix/client/unstable/room_keys/version HTTP/1.1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" [0 dbevts]
2020-04-08 12:54:27,204 - synapse.metrics.background_process_metrics - 214 - ERROR - presence.notify_new_event-4756 - Background process 'presence.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: (23728, 23728)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 212, in run
    return (yield result)
TypeError: object tuple can't be used in 'await' expression
```

### Version information

Going by reflog, quite an old one: [12d425900](https://github.com/matrix-org/synapse/commit/12d425900048b29a95b06428f04ed6ecc9e09d15)

- **Version**:
```
matrix-js-sdk develop $ curl http://localhost:8008/_synapse/admin/v1/server_version
{
    "python_version": "3.7.6",
    "server_version": "1.11.0"
}
```

- **Install method**:
Running in docker

- **Platform**:
macos 10.15.3

<img width="602" alt="Screenshot 2020-04-08 at 14 04 11" src="https://user-images.githubusercontent.com/3935731/78787224-ebbdc700-79a1-11ea-9b40-cb10011365ec.png">

**Comment by babolivier** [comment]
Hey @foldleft, could you please try that again with the latest version of Synapse (v1.12.3), to make sure this issue is still a thing?

**Comment by foldleft** [comment]
I was unable to reproduce it by following the same steps a second time, on `develop`.
