### ISSUE TITLE
yaml type errors in homeserver.yaml + synctl crashes with a very obscure traceback

### ISSUE THREAD

**Issue by ara4n** [matrix-org/synapse#7264]
When following the instructions from https://www.mytinydc.com/en/blog/matrix-synapse-installationserver-riotclient/ , someone ended up with this stacktrace:

```
Apr 11 16:33:07 matrix-bridges systemd[1]: Starting Matrix Synapse service...
Apr 11 16:33:08 matrix-bridges synapse[6050]: Traceback (most recent call last):
Apr 11 16:33:08 matrix-bridges synapse[6050]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Apr 11 16:33:08 matrix-bridges synapse[6050]:     "__main__", mod_spec)
Apr 11 16:33:08 matrix-bridges synapse[6050]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Apr 11 16:33:08 matrix-bridges synapse[6050]:     exec(code, run_globals)
Apr 11 16:33:08 matrix-bridges synapse[6050]:   File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 651, in 
Apr 11 16:33:08 matrix-bridges synapse[6050]:     main()
Apr 11 16:33:08 matrix-bridges synapse[6050]:   File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 646, in main
Apr 11 16:33:08 matrix-bridges synapse[6050]:     hs = setup(sys.argv[1:])
Apr 11 16:33:08 matrix-bridges synapse[6050]:   File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 324, in setup
Apr 11 16:33:08 matrix-bridges synapse[6050]:     "Synapse Homeserver", config_options
Apr 11 16:33:09 matrix-bridges synapse[6050]: Starting ...
Apr 11 16:33:09 matrix-bridges synapse[6050]: error starting (exit code: 1); see above for logs
Apr 11 16:33:09 matrix-bridges systemd[1]: matrix-synapse.service: Control process exited, code=exited, status=1/FAILURE
Apr 11 16:33:09 matrix-bridges systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Apr 11 16:33:09 matrix-bridges systemd[1]: Failed to start Matrix Synapse service.
```

Turned out it was due to there being a string where an int should be in homeserver.yaml.  Running synapse manually gave a sensible stacktrace:

```
python -m synapse.app.homeserver -c homeserver.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 651, in 
    main()
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 646, in main
    hs = setup(sys.argv[1:])
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/app/homeserver.py", line 324, in setup
    "Synapse Homeserver", config_options
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/config/_base.py", line 629, in load_or_generate_config
    config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/config/_base.py", line 651, in parse_config_dict
    data_dir_path=data_dir_path,
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/config/_base.py", line 266, in invoke_all
    res[name] = getattr(config, func_name)(*args, **kwargs)
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/config/server.py", line 278, in read_config
    self.retention_default_max_lifetime
  File "/opt/synapse/env/lib/python3.7/site-packages/synapse/config/_base.py", line 146, in parse_duration
    return int(value) * size
ValueError: invalid literal for int() with base 10: '1M'
```

...so this looks like synctl doing something daft.

**Comment by richvdh** [comment]
I don't think synctl truncates stderr in this way (indeed, synctl doesn't touch stderr). 

I think the main problem is probably the combination of synctl with systemd. They don't play well together; indeed synctl has little purpose other than to be a poor imitation of systemd. 

https://github.com/matrix-org/synapse/tree/master/contrib/systemd is the right way to do this.
