### ISSUE TITLE
Background process 'user_directory.notify_new_event' threw an exception

### ISSUE THREAD

**Issue by rihardsk** [matrix-org/synapse#7282]
### Description
My logs are flooded with exceptions `psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification`.

Here are the logs [invalidcolumnreference.error.redacted.log](https://github.com/matrix-org/synapse/files/4483206/invalidcolumnreference.error.redacted.log).

Thinking that this might be the same issue as #4453, i attempted to [trigger the regeneration of the directory info tables](https://github.com/matrix-org/synapse/blob/6fb63d6426b87e989143b6ff2679f5ae4a8fd22b/docs/user_directory.md) as suggested in a comment on that issue. After executing the linked sql script, the original exceptions are replaced with different ones:

```
synapse.storage.background_updates: [background_updates-0] Error doing update
Traceback (most recent call last):
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 109, in run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 205, in do_next_background_update
    res = await self._do_background_update(update_name, desired_duration_ms)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/background_updates.py", line 239, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/data_stores/main/user_directory.py", line 207, in _populate_user_directory_proce>
    user_id, profile.display_name, profile.avatar_url
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 524, in runInteraction
    **kwargs
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 574, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/nix/store/bmih96pr5vkyc6w67nixdk2y2pn94n7k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 571, in inner_func
    return func(conn, *args, **kwargs)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 407, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/data_stores/main/user_directory.py", line 377, in _update_profile_in_user_dir_txn
    lock=False,  # We're only inserter
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 767, in simple_upsert_txn
    txn, table, keyvalues, values, insertion_values=insertion_values
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 880, in simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 199, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/nix/store/4i8bhyazmbk75frbbpigkhnyqaspw75k-matrix-synapse-1.12.1/lib/python3.7/site-packages/synapse/storage/database.py", line 225, in _do_execute
    return func(sql, *args)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

For completeness, here are the logs after running the sql script [error-doing-update.redacted.log](https://github.com/matrix-org/synapse/files/4483420/error-doing-update.redacted.log).
 
### Some background information
I had database corruption issues previously due to `LC_COLLATE` being set to `'UTF-8'` (as described in https://github.com/matrix-org/synapse/issues/6696#issuecomment-575280941). I attempted to fix the corruption by
1. backing up the synapse db,
2. dropping it,
3. recreating it with `LC_CTYPE` and `LC_COLLATE` settings changed from `'UTF-8'` to `'C'`,
4. importing the backup,
5. deleting duplicate rows in tables that were being complained about in the indexing step
6. and then exporting and importing the database again.

The last import was clean - the indexing step didn't complain about anything, but if there were some other duplicate rows that weren't indexed i would have missed them. Or there might have been some other issues. 

### Version information

- **Homeserver**: my private homeserver

- **Version**: 1.12.1, but the original errors (before running the sql script) were also present on 1.9.1

- **Install method**: NixOS

- **Platform**: latest NixOS master branch (commit 01c8795673ecff6272895a085e9fe1ffa3b33620) running on a rockpro64 sbc (with a custom patched kernel).

**Comment by rihardsk** [comment]
Took a closer look at the stack trace i posted. I see that [`_update_profile_in_user_dir_txn()`](https://github.com/matrix-org/synapse/blob/6fb63d6426b87e989143b6ff2679f5ae4a8fd22b/synapse/storage/data_stores/main/user_directory.py#L373) is called and it leads to the `no unique or exclusion constraint` exception. That function attempts to do an insert into the `user_directory` table. I checked that the table is empty in my db (as it should be, i guess, - [user_directory.md](https://github.com/matrix-org/synapse/blob/6fb63d6426b87e989143b6ff2679f5ae4a8fd22b/docs/user_directory.md) says that running the [user_dir_populate.sql](https://github.com/matrix-org/synapse/blob/6fb63d6426b87e989143b6ff2679f5ae4a8fd22b/synapse/storage/data_stores/main/schema/delta/53/user_dir_populate.sql) makes synapse flush user directory related tables):
```
select count(*) from user_directory;
 count 
-------
     0
```

Does this mean that the values being inserted are themselves conflicting?

Another thing about the error - it seems that there's an error in the SQL statement being executed. [This SO answer](https://stackoverflow.com/a/54169587) states that `ON CONFLICT` should be accompanied by a `WHERE` which isn't being done [here](https://github.com/matrix-org/synapse/blob/6fb63d6426b87e989143b6ff2679f5ae4a8fd22b/synapse/storage/database.py#L873). I don't know whether the `ON CONFLICT` clause should be triggered with an empty db; might be a separate issue.

**Comment by richvdh** [comment]
the error means that you are missing an index which should be there. Try `\d user_directory`. The output should look like this:

```
  Table "public.user_directory"
    Column    | Type | Modifiers 
--------------+------+-----------
 user_id      | text | not null
 room_id      | text | 
 display_name | text | 
 avatar_url   | text | 
Indexes:
    "user_directory_user_idx" UNIQUE, btree (user_id)
    "user_directory_room_idx" btree (room_id)
```

if the indexes are missing, I would suggest your recreation process has dropped important steps in the creation of the database schema and you should check it carefully to see what other corruption has been caused.

**Comment by rihardsk** [comment]
Just checked my database backups. I see that i'm missing some index creation statements in the backup that i made after deleting the duplicate rows. Apparently the indexes that are missing are for tables that had the duplicate rows. I assumed that the indexes would be re-created on re-importing the db dump that was made after deleting the offending rows, but, apparently, that's not how that works.

I'll try to re-create the missing indexes. It seems that should be the only thing gone wrong in my procedure.

**Comment by rihardsk** [comment]
Yup, that was it. Had to create the missing indexes and the errors are gone now. Thank you.
