### ISSUE TITLE
pyasn1==0.4.5 incompatibility with synapse 1.11.0 (solved by upgrading to pyasn1==0.4.8)

### ISSUE THREAD

**Issue by Klodd** [matrix-org/synapse#7310]
### Description

matrix-synapse service fails to restart after upgrade of synapse to 1.11.0 (1.11.0~ynh1)

### Steps to reproduce

I'm using yunohost but I don't think it should be specific.

- upgrade to 1.11.0
- server does not restart, `journalctl -u matrix-synapse` output:
```Apr 20 15:43:13 [redacted] systemd[1]: Started Synapse Matrix homeserver.
Apr 20 15:43:22 [redacted] python[8486]: This server is configured to use 'matrix.org' as its trusted key server via the
Apr 20 15:43:22 [redacted] python[8486]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Apr 20 15:43:22 [redacted] python[8486]: server since it is long-lived, stable and trusted. However, some admins may
Apr 20 15:43:22 [redacted] python[8486]: wish to use another server for this purpose.
Apr 20 15:43:22 [redacted] python[8486]: To suppress this warning and continue using 'matrix.org', admins should set
Apr 20 15:43:22 [redacted] python[8486]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Apr 20 15:43:22 [redacted] python[8486]: --------------------------------------------------------------------------------
Apr 20 15:43:22 [redacted] python[8486]: Traceback (most recent call last):
Apr 20 15:43:22 [redacted] python[8486]:   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Apr 20 15:43:22 [redacted] python[8486]:     "__main__", mod_spec)
Apr 20 15:43:22 [redacted] python[8486]:   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Apr 20 15:43:22 [redacted] python[8486]:     exec(code, run_globals)
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 639, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     main()
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 634, in main
Apr 20 15:43:22 [redacted] python[8486]:     hs = setup(sys.argv[1:])
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 319, in setup
Apr 20 15:43:22 [redacted] python[8486]:     "Synapse Homeserver", config_options
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 629, in load_or_gen
Apr 20 15:43:22 [redacted] python[8486]:     config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 651, in parse_confi
Apr 20 15:43:22 [redacted] python[8486]:     data_dir_path=data_dir_path,
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/config/_base.py", line 266, in invoke_all
Apr 20 15:43:22 [redacted] python[8486]:     res[name] = getattr(config, func_name)(*args, **kwargs)
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/config/password_auth_providers.py", line 4
Apr 20 15:43:22 [redacted] python[8486]:     {"module": mod_name, "config": provider["config"]}
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/util/module_loader.py", line 33, in load_m
Apr 20 15:43:22 [redacted] python[8486]:     module = importlib.import_module(module)
Apr 20 15:43:22 [redacted] python[8486]:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
Apr 20 15:43:22 [redacted] python[8486]:     return _bootstrap._gcd_import(name[level:], package, level)
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
Apr 20 15:43:22 [redacted] python[8486]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/ldap_auth_provider.py", line 19, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     import ldap3
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/ldap3/__init__.py", line 139, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     from .core.connection import Connection
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/ldap3/core/connection.py", line 44, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     from ..operation.compare import compare_operation, compare_request_to_dict
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/ldap3/operation/compare.py", line 28, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     from ..operation.search import ava_to_dict
Apr 20 15:43:22 [redacted] python[8486]:   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/ldap3/operation/search.py", line 41, in <module>
Apr 20 15:43:22 [redacted] python[8486]:     from pyasn1.error import PyAsn1UnicodeDecodeError
Apr 20 15:43:22 [redacted] python[8486]: ImportError: cannot import name 'PyAsn1UnicodeDecodeError'
```

### Version information

- **Homeserver**: self-hosted

- **Version**:
{
    "python_version": "3.5.3",
    "server_version": "1.11.0"
}

- **Install method**:
Yunohost upgrade from interface.
(I think underlying is pip)

- **Platform**:
Debian stretch x86_64 GNU/Linux

### Resolution
pyasn 0.4.5 is incompatible and the culprit here.

pip install --upgrade pyasn1 pulls 0.4.8 and everything runs smoothly.

**Comment by clokep** [comment]
This looks like the ldap3 package is expecting a newer version of pyasn1, not Synapse directly. Could you provide the output of `pip freeze` in that virtualenv? I tried downgrading pyasn1 quickly and had no issues.

**Comment by Klodd** [comment]
Here you go:
```
user@server:~$ source /opt/yunohost/matrix-synapse/bin/activate
(new) user@server:~$ pip freeze
asn1crypto==0.24.0
attrs==19.1.0
Automat==0.7.0
bcrypt==3.1.6
bleach==3.1.0
canonicaljson==1.1.4
certifi==2019.3.9
cffi==1.14.0
chardet==3.0.4
constantly==15.1.0
cryptography==2.6.1
daemonize==2.5.0
frozendict==1.2
hyperlink==18.0.0
idna==2.8
importlib-metadata==1.6.0
incremental==17.5.0
Jinja2==2.11.2
jsonschema==3.0.1
ldap3==2.7
lxml==4.5.0
MarkupSafe==1.1.1
matrix-synapse==1.11.0
matrix-synapse-ldap3==0.1.4
msgpack==0.6.1
ndg-httpsclient==0.5.1
netaddr==0.7.19
phonenumbers==8.10.7
Pillow==5.4.1
pkg-resources==0.0.0
prometheus-client==0.3.1
psutil==5.6.1
psycopg2==2.8.5
pyasn1==0.4.8
pyasn1-modules==0.2.4
pycparser==2.19
PyHamcrest==1.9.0
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.14.11
PyYAML==5.1
requests==2.21.0
service-identity==18.1.0
signedjson==1.1.1
simplejson==3.16.0
six==1.12.0
sortedcontainers==2.1.0
treq==18.6.0
Twisted==18.9.0
typing-extensions==3.7.4.2
unpaddedbase64==1.1.0
urllib3==1.24.1
webencodings==0.5.1
zipp==1.2.0
zope.interface==4.6.0
```

**Comment by clokep** [comment]
This seems to be an issue with the `ldap3` package that Synapse is using, see cannatag/ldap3#802.
