### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by schildbach** [matrix-org/synapse#7375]
I keep seeing these errors in the log. I'm using Synapse 1.12.4 and Postgres 10.12, both inside Docker-Compose running Ubuntu 20.04 LTS on the host.

```
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | 2020-04-30 12:18:46,662 - synapse.http.server - 110 - ERROR - GET-15024 - Failed handle request via 'SyncRestServlet': <XForwardedForRequest at 0x7f411e0f9110 method='GET' uri='/_matrix/client/r0/sync?filter=7&timeout=0&_cacheBuster=1588249126037' clientpro>
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | Traceback (most recent call last):
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = g.send(result)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | StopIteration: {'$1560540549116pGgvF:fuckeverywhere.space': {'event_id': '$1560540549116pGgvF:fuckeverywhere.space', 'internal_metadata': '{"outlier": false, "redacted": true, "stream_ordering": -5104}', 'json': '{"content": {}, "event_id": "$1560540549116p>
Apr 30 12:18:46 ultima docker-compose[22585]: vh+26NN5fXDHwUZMqSQV9BNy/kHwUQvS4"}]], "signatures": {"fuckeverywhere.space": {"ed25519:a_HvTl": "XD6v5fLWbEd5K9Z6cXM8sq+OjItjhXalxZVnDylOOrA/TEF+uVSr0s4+/ztGqiQm1C7wAre5ikMawXqr/2ePBA"}}, "unsigned": {}}', 'format_version': 1, 'room_version_id': '1', 'rejected_reason': >
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | During handling of the above exception, another exception occurred:
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | Traceback (most recent call last):
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = result.throwExceptionIntoGenerator(g)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return g.throw(self.type, self.value, self.tb)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 312, in _wait_for_sync_for_user
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     sync_config, since_token, full_state=full_state
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 343, in current_sync_for_user
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return await self.generate_sync_result(sync_config, since_token, full_state)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 1000, in generate_sync_result
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     sync_result_builder, account_data_by_room
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 1419, in _generate_sync_entry_for_rooms
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     await concurrently_execute(handle_room_entries, room_entries, 10)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = result.throwExceptionIntoGenerator(g)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return g.throw(self.type, self.value, self.tb)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/util/async_helpers.py", line 159, in _concurrently_execute_inner
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     await maybe_awaitable(func(next(it)))
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 1803, in _generate_room_entry
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     newly_joined_room=newly_joined,
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/sync.py", line 498, in _load_filtered_recents
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     room_id, limit=load_limit + 1, end_token=end_key
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = result.throwExceptionIntoGenerator(g)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return g.throw(self.type, self.value, self.tb)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/stream.py", line 486, in get_recent_events_for_room
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     [r.event_id for r in rows], get_prev_content=True
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = result.throwExceptionIntoGenerator(g)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return g.throw(self.type, self.value, self.tb)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/events_worker.py", line 274, in get_events_as_list
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     set(event_ids), allow_rejected=allow_rejected
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = result.throwExceptionIntoGenerator(g)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return g.throw(self.type, self.value, self.tb)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/events_worker.py", line 421, in _get_events_from_cache_or_db
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     missing_events_ids, allow_rejected=allow_rejected
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     result = g.send(result)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/events_worker.py", line 577, in _get_events_from_db
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     d = json.loads(row["json"])
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return _default_decoder.decode(s)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     obj, end = self.raw_decode(s)
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |   File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   |     return self.scan_once(s, idx=_w(s, idx).end())
Apr 30 12:18:46 ultima docker-compose[22585]: synapse_1   | simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by babolivier** [comment]
Hey @schildbach, and thanks for your report. Could you please give answer a few questions (mainly about Synapse's database) for me so I can make sure of what's happening here?

* What's the type of the `json` column in the `event_json` table? You can see that on PostgreSQL by running `\d event_json`, or on SQLite by running `.schema event_json`.
* What's the result of `SELECT * FROM events WHERE event_id = '$1560540549116pGgvF:fuckeverywhere.space';`?
* What's the result of `SELECT * FROM redactions WHERE redacts = '$1560540549116pGgvF:fuckeverywhere.space';`?
* Have you attempted a database migration from SQLite to PostgreSQL since October 2019?

**Comment by schildbach** [comment]
@babolivier I did migrate from SQLite to Postgres some time last year, but I can't remember when that was exactly.

A few hours ago, I ran `update event_json set json = decode(substr(json,3), 'hex') where json like '\\x%';` on my database and it seems to have fixed the issue. I didn't look at the `redactions` table though.

```
synapse=# \d event_json
                  Table "public.event_json"
      Column       |  Type   | Collation | Nullable | Default 
-------------------+---------+-----------+----------+---------
 event_id          | text    |           | not null | 
 room_id           | text    |           | not null | 
 internal_metadata | text    |           | not null | 
 json              | text    |           | not null | 
 format_version    | integer |           |          | 
Indexes:
    "event_json_event_id_key" UNIQUE CONSTRAINT, btree (event_id)
    "event_json_room_id" btree (room_id)
```

**Comment by babolivier** [comment]
Right, so it's possibly the same cause as https://github.com/matrix-org/synapse/issues/7349 then. Could you please run the last SQL query from my list above? The update you performed shouldn't have changed that and it'd help me figure out how likely it is that both issues are the related.

**Comment by schildbach** [comment]
```
synapse=# SELECT * FROM redactions WHERE redacts = '$1560540549116pGgvF:fuckeverywhere.space';
 event_id | redacts | have_censored | received_ts 
----------+---------+---------------+-------------
(0 rows)
```

**Comment by babolivier** [comment]
Right, it was actually https://github.com/matrix-org/synapse/issues/5312, which we've fixed but people who migrated before then might have gotten some events stored the wrong way because of this, sorry :(

https://github.com/matrix-org/synapse/issues/5312#issuecomment-578142774 contains issues on how to fix it.

**Comment by schildbach** [comment]
Thanks for the explanation. Is there any risk of further damage to the database because of this?

**Comment by babolivier** [comment]
Not that I know of, the fix I mentioned above should fix all of the database weirdness introduced in that bug.
