### ISSUE TITLE
Adding an alt_alias with a bad server causes a 500

### ISSUE THREAD

**Issue by foldleft** [matrix-org/synapse#7451]
Attempting to add a bad server causes a 500 error:

```2020-05-07 12:36:31,038 - synapse.http.matrixfederationclient - 497 - WARNING - PUT-21 - {GET-O-1} [notaserver] Request failed: GET matrix://notaserver/_matrix/federation/v1/query/directory?room_alias=%23fake%3Anotaserver: DNSLookupError('no results for hostname lookup: notaserver')
2020-05-07 12:36:31,039 - synapse.http.server - 110 - ERROR - PUT-21 - Failed handle request via 'RoomStateEventRestServlet': <XForwardedForRequest at 0x7f30491edb10 method='PUT' uri='/_matrix/client/r0/rooms/!zZaFWLfjKbIeMyOOsU%3Alocalhost/state/m.room.canonical_alias/' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 430, in _send_request
    response = yield request_deferred
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/federation/matrix_federation_agent.py", line 162, in request
    self._agent.request(method, uri, headers, bodyProducer)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/federation/matrix_federation_agent.py", line 260, in _do_connect
    raise first_exception
  File "/usr/local/lib/python3.7/site-packages/synapse/http/federation/matrix_federation_agent.py", line 247, in _do_connect
    endpoint.connect(protocol_factory)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/endpoints.py", line 982, in startConnectionAttempts
    "no results for hostname lookup: {}".format(self._hostStr)
twisted.internet.error.DNSLookupError: DNS lookup failed: no results for hostname lookup: notaserver.
```

Similarly if the domain exists but isn't running a server:
```
2020-05-07 12:37:19,885 - synapse.http.server - 110 - ERROR - PUT-25 - Failed handle request via 'RoomStateEventRestServlet': <XForwardedForRequest at 0x7f3048d6f690 method='PUT' uri='/_matrix/client/r0/rooms/!zZaFWLfjKbIeMyOOsU%3Alocalhost/state/m.room.canonical_alias/' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 430, in _send_request
    response = yield request_deferred
twisted.internet.error.ConnectingCancelledError: HostnameAddress(hostname=b'example.com', port=8448)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v1/room.py", line 214, in on_PUT
    requester, event_dict, txn_id=txn_id
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 711, in create_and_send_nonmember_event
    requester, event, context, ratelimit=ratelimit
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 659, in send_nonmember_event
    requester=requester, event=event, context=context, ratelimit=ratelimit
  File "/usr/local/lib/python3.7/site-packages/synapse/util/metrics.py", line 73, in measured_func
    r = await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 839, in handle_new_client_event
    requester, event, context, ratelimit=ratelimit, extra_users=extra_users
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 957, in persist_and_notify_client_event
    directory_handler, alias_str, event.room_id
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 865, in _validate_canonical_alias
    mapping = yield directory_handler.get_association(room_alias)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/directory.py", line 248, in get_association
    ignore_backoff=True,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/transport/client.py", line 183, in make_query
    ignore_backoff=ignore_backoff,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 786, in get_json
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 246, in _send_request_with_optional_trailing_slash
    response = yield self._send_request(request, **send_request_args)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 435, in _send_request
    raise_from(RequestSendFailed(e, can_retry=True), e)
  File "<string>", line 3, in raise_from
synapse.api.errors.RequestSendFailed: Failed to send request: ConnectingCancelledError: HostnameAddress(hostname=b'example.com', port=8448)
```

Or if the server denies the request:
```2020-05-07 12:39:13,714 - synapse.http.server - 110 - ERROR - PUT-37 - Failed handle request via 'RoomStateEventRestServlet': <XForwardedForRequest at 0x7f3048d97a10 method='PUT' uri='/_matrix/client/r0/rooms/!zZaFWLfjKbIeMyOOsU%3Alocalhost/state/m.room.canonical_alias/' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v1/room.py", line 214, in on_PUT
    requester, event_dict, txn_id=txn_id
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 711, in create_and_send_nonmember_event
    requester, event, context, ratelimit=ratelimit
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 659, in send_nonmember_event
    requester=requester, event=event, context=context, ratelimit=ratelimit
  File "/usr/local/lib/python3.7/site-packages/synapse/util/metrics.py", line 73, in measured_func
    r = await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 839, in handle_new_client_event
    requester, event, context, ratelimit=ratelimit, extra_users=extra_users
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 957, in persist_and_notify_client_event
    directory_handler, alias_str, event.room_id
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 865, in _validate_canonical_alias
    mapping = yield directory_handler.get_association(room_alias)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/directory.py", line 248, in get_association
    ignore_backoff=True,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/transport/client.py", line 183, in make_query
    ignore_backoff=ignore_backoff,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 786, in get_json
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 246, in _send_request_with_optional_trailing_slash
    response = yield self._send_request(request, **send_request_args)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 487, in _send_request
    raise e
synapse.api.errors.HttpResponseException: 401: b'Unauthorized'
```

**Comment by foldleft** [comment]
nb this is on a fresh copy of `develop`

**Comment by clokep** [comment]
Could you provide some more detailed steps for how to reproduce this?

**Comment by foldleft** [comment]
sure. Fire up riot, open `/devtools`, send a room state event called `m.room.canonical_alias` and set the content to `{ alias: [] }`

**Comment by babolivier** [comment]
Given the lack of progress on this issue and of similar reports, I'm going to close it. Feel free to reopen if needed.
