### ISSUE TITLE
Background update error: column 'ordering' doesn't exist (1.14.0rc2)

### ISSUE THREAD

**Issue by turt2live** [matrix-org/synapse#7583]
```
[homeserver_1] 2020-05-27 15:40:38,216 - synapse.storage.background_updates - 114 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/background_updates.py", line 111, in run_background_updates
    self.BACKGROUND_UPDATE_DURATION_MS
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/background_updates.py", line 196, in do_next_background_update
    "background_updates", get_background_updates_txn,
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 527, in runInteraction
    **kwargs
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 575, in runWithConnection
    self._db_pool.runWithConnection(inner_func, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/matrix/synapse/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 572, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 418, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/background_updates.py", line 190, in get_background_updates_txn
    """
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 210, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/matrix/synapse/lib/python3.6/site-packages/synapse/storage/database.py", line 236, in _do_execute
    return func(sql, *args)
psycopg2.ProgrammingError: column "ordering" does not exist
LINE 1: ...name, depends_on FROM background_updates ORDER BY ordering, ...
```

**Comment by babolivier** [comment]
More context:

```
t2lsynapse=# select * from applied_schema_deltas where file = '58/00background_update_ordering.sql';
 version |                file
---------+-------------------------------------
      58 | 58/00background_update_ordering.sql
(1 row)
```

```
t2lsynapse=# \d background_updates
Table "public.background_updates"
    Column     | Type | Modifiers
---------------+------+-----------
 update_name   | text | not null
 progress_json | text | not null
 depends_on    | text |
Indexes:
    "background_updates_uniqueness" UNIQUE CONSTRAINT, btree (update_name)
```

So it looks like Synapse saw the update but didn't apply it for some reason. There also isn't any error around `Upgrading schema to v58` in the logs.

**Comment by turt2live** [comment]
Looks like this is a Me problem, somehow. The background update didn't apply, but all evidence says it should have.

Blaming unknown environmental factors.

**Comment by richvdh** [comment]
> The background update didn't apply, but all evidence says it should have.

seems like the problem is not with a background update, but with the *foreground* update that added the `ordering` column, specifically the one called (slightly confusingly, maybe) `58/00background_update_ordering.sql`.

It's not the first time we've seen this sort of random failure :/
