### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "_temp_populate_user_directory_users" does not exist

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7589]
After running the background jobs suggested here: https://github.com/matrix-org/synapse/blob/master/docs/user_directory.md it all seemed to be going fine.

However, I restarted my homeserver a couple times, including upgrading it from v1.13.0 -> v1.14.0. Now this is spewing into my homeserver logs every second or so:

```
2020-05-28 13:52:06,882 - synapse.storage.background_updates - 227 - INFO - background_updates-0- Starting update batch on background update 'populate_user_directory_process_users'
2020-05-28 13:52:06,906 - synapse.storage.background_updates - 114 - ERROR - background_updates-0- Error doing update
Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 110, in run_background_updates
    result = await self.do_next_background_update(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 222, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 255, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/user_directory.py", line 300, in _populate_user_directory_process_users
    users_to_work_on = yield self.db.runInteraction(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 520, in runInteraction
    result = yield self.runWithConnection(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 574, in runWithConnection
    result = yield make_deferred_yieldable(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 572, in inner_func
    return func(conn, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 418, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/user_directory.py", line 284, in _get_next_batch
    txn.execute(sql)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 210, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/database.py", line 236, in _do_execute
    return func(sql, *args)
psycopg2.errors.UndefinedTable: relation "_temp_populate_user_directory_users" does not exist
LINE 1: SELECT user_id FROM _temp_populate_user_directory_users LIMI...
```

Looks like the code doesn't like being restarted.

**Comment by anoadragon453** [comment]
Rerunning this query seems to fix this though:

```
INSERT INTO background_updates (update_name, progress_json) VALUES
    ('populate_user_directory_createtables', '{}');
```

which presumably just recreates the tables it needs. The code could probably be modified to work across these special circumstances, but as this was a bit of an edge case and the code has been around forever and nobody else reported this, I'm going to consider this workaround good enough.
