### ISSUE TITLE
A power level with a string as value is accepted

### ISSUE THREAD

**Issue by erdnaxeli** [matrix-org/synapse#7592]
### Description

A user's power level can be set with a value of type string.

It should be noted that [the spec](https://matrix.org/docs/spec/client_server/r0.6.1#id253) never says that a power level must be an int, but Riot web and some part of Synapse expect it to be an int (see bellow). By the way I can't found the definition of `User power levels` and `Even power levels` types.

### Steps to reproduce

- create a new room (v5 in my case)
- in riot, use `/devtools` to look at the `m.room.power_levels` event
- change your own power level from `100` to `"100"`
- send the event

What happens:
* the HS accept the event, it is even federated correctly
* Riot web is a little bit lost: I can't change anything in the room parameters, but I can still change the users' power level

What I would expect:
* the HS discard my event with an error

It must be noticed that this invalid power level still work on some place. I can still change my own power level back to `100`, or other user's, but `/upgraderoom` fails with the following error:
```
2020-05-28 15:36:01,839 - synapse.http.server - 110 - ERROR - POST-101101 - Failed handle request via 'Roo
mUpgradeRestServlet': <XForwardedForRequest at 0x7fe1efbe6978 method='POST' uri='/_matrix/client/r0/rooms/!gRrCzddQslIHoyrgwJ%3Amatrix.org/upgrade' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {('m.room.power_levels', ''): '$159067103139tJGGs:cervoi.se', ('m.room.topic', ''): '$15005781984112702txYYW:matrix.org', ('m.room.history_visibility', ''): '$1500301245224694DtwYG:matrix.org', ('m.room.avatar', ''): '$15005773424098264pQgLH:matrix.org', ('m.room.guest_access', ''): '$1500301169223450JVurV:matrix.org', ('m.room.name', ''): '$15005781124111252eKoVg:matrix.org', ('m.room.join_rules', ''): '$1500301245224695ZMvZw:matrix.org'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: {('m.room.power_levels', ''): '$159067103139tJGGs:cervoi.se', ('m.room.topic', ''): '$15005781984112702txYYW:matrix.org', ('m.room.history_visibility', ''): '$1500301245224694DtwYG:matrix.org', ('m.room.avatar', ''): '$15005773424098264pQgLH:matrix.org', ('m.room.guest_access', ''): '$1500301169223450JVurV:matrix.org', ('m.room.name', ''): '$15005781124111252eKoVg:matrix.org', ('m.room.join_rules', ''): '$1500301245224695ZMvZw:matrix.org'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 78, in wrapped_request_handler
    await h(self, request)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/http/server.py", line 331, in _async_render
    callback_return = await callback_return
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/rest/client/v2_alpha/room_upgrade_rest_servlet.py", line 76, in on_POST
    requester, room_id, new_version
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/room.py", line 146, in upgrade_room
    new_version,  # args for _upgrade_room
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/room.py", line 195, in _upgrade_room
    tombstone_event_id=tombstone_event.event_id,
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/handlers/room.py", line 378, in clone_existing_room
    initial_state[(EventTypes.PowerLevels, "")]
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/events/utils.py", line 445, in copy_power_levels_contents
    "Invalid power_levels value for %s.%s: %r" % (k, k1, v1)
TypeError: Invalid power_levels value for users.@fwhcat:mux.re: '100'
```

### Version information

- **Homeserver**: cervoi.se

If not matrix.org:

- **Version**: 1.14.0

- **Install method**: apt

- **Platform**: Debian 10, PostgreSQL 11.7, dedicated server

**Comment by erikjohnston** [comment]
We should definitely validate power levels on the CS API. Validating on inbound federation probably requires a bit more thought

**Comment by richvdh** [comment]
dup #1237

**Comment by erdnaxeli** [comment]
2014 :scream:
