### ISSUE TITLE
Failed to handle stream account_data: TypeError: '<' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7617]
possibly this happens if we have global account data and per-room account data with the same stream_id?

```
TypeError: '<' not supported between instances of 'str' and 'NoneType'
  File "synapse/metrics/background_process_metrics.py", line 213, in run
    return (yield result)
  File "twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "synapse/replication/tcp/resource.py", line 146, in _run_notifier_loop
    updates, current_token, limited = await stream.get_updates()
  File "synapse/replication/tcp/streams/_base.py", line 161, in get_updates
    self.local_instance_name, self.last_token, current_token
  File "synapse/replication/tcp/streams/_base.py", line 186, in get_updates_since
    instance_name, from_token, upto_token, _STREAM_UPDATE_TARGET_ROW_COUNT,
  File "synapse/replication/tcp/streams/_base.py", line 604, in _update_function
    updates = list(heapq.merge(room_rows, global_rows))
  File "heapq.py", line 353, in merge
    _heapify(h)

**Comment by cremesk** [comment]
i see the same issue in my synapse log.

**Comment by sndrsmnk** [comment]
Yes. Seeing the same.

Some more logging for the Googles:

```
2020-06-05 23:41:25,607 - synapse.access.http.9093 - 311 - INFO - POST-141761 - - - 9093 - {None} Processed request: 0.010sec/0.001sec (0.001sec, 0.000sec) (0.001sec/0.004sec/1) 4B 200 "POST /_synapse/replication/fed_send_edu/m.presence/YFkxZcrwmx HTTP/1.1" "Synapse/1.14.0
" [0 dbevts]
2020-06-05 23:41:25,611 - synapse.replication.tcp.resource - 158 - INFO - replication_notifier-31487 - Streaming: presence -> 30072754
2020-06-05 23:41:25,619 - synapse.replication.tcp.resource - 149 - INFO - replication_notifier-31487 - Failed to handle stream account_data
2020-06-05 23:41:25,619 - synapse.metrics.background_process_metrics - 215 - ERROR - replication_notifier-31487 - Background process 'replication_notifier' threw an exception
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [ .. participants, m.fully_read data .. ]

During handling of the above exception, another exception occurred:

[ .. and then the trace shown above .. ]
```
