### ISSUE TITLE
PhoneHomeStatsTestCase.test_performance_100 seems flaky on SQLite

### ISSUE THREAD

**Issue by babolivier** [matrix-org/synapse#7627]
I've seen it fail quite a few times over the past couple of days in BuildKite, exclusively on SQLite tests, with:

```
Traceback (most recent call last):
  File "/src/tests/test_phone_home.py", line 51, in test_performance_100
    self.assertApproximates(stats["cpu_average"], 100, tolerance=2.5)
  File "/src/.tox/py36/lib/python3.6/site-packages/twisted/trial/_synctest.py", line 564, in assertApproximates
    raise self.failureException(msg or "%s ~== %s" % (first, second))
twisted.trial.unittest.FailTest: 103 ~== 100
```

**Comment by clokep** [comment]
Related to #6676 maybe?

**Comment by babolivier** [comment]
Oops, yes, I forgot to link this one. Yeah, it might be related.
