### ISSUE TITLE
DatabaseError // twisted - 192 – ERROR

### ISSUE THREAD

**Issue by rocky-III** [matrix-org/synapse#7665]
Running a matrix server on an cubitruck with yunohost for some time very nicely… 
but now I get errors and the synapse doe not start 
have a look at the logs:

```
-- Logs begin at Tue 2020-06-09 14:48:54 UTC, end at Tue 2020-06-09 19:29:34 UTC. --
Jun 09 19:28:44 python[17693]: 2020-06-09 19:28:44,683 - twisted - 192 - ERROR - -         TCP/IP connections on port 5432?
Jun 09 19:28:44 python[17693]: 2020-06-09 19:28:44,686 - twisted - 192 - ERROR - -
Jun 09 19:28:46 systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jun 09 19:28:46 systemd[1]: matrix-synapse.service: Unit entered failed state.
Jun 09 19:28:46 systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 09 19:28:49 systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Jun 09 19:28:49 systemd[1]: Stopped Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit matrix-synapse.service has finished shutting down.
Jun 09 19:28:49 systemd[1]: Starting Synapse Matrix homeserver...
-- Subject: Unit matrix-synapse.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit matrix-synapse.service has begun starting up.
Jun 09 19:29:08 systemd[1]: Started Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit matrix-synapse.service has finished starting up.
-- 
-- The start-up result is done.
Jun 09 19:29:26 python[17720]: This server is configured to use 'matrix.org' as its trusted key server via the
Jun 09 19:29:26 python[17720]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Jun 09 19:29:26 python[17720]: server since it is long-lived, stable and trusted. However, some admins may
Jun 09 19:29:26 python[17720]: wish to use another server for this purpose.
Jun 09 19:29:26 python[17720]: To suppress this warning and continue using 'matrix.org', admins should set
Jun 09 19:29:26 python[17720]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Jun 09 19:29:26 python[17720]: --------------------------------------------------------------------------------
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,054 - root - 257 - WARNING - None- ***** STARTING SERVER *****
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,056 - root - 258 - WARNING - None- Server /opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py version 1.12.4
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,204 - twisted - 192 - ERROR - - Traceback (most recent call last):
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,206 - twisted - 192 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,211 - twisted - 192 - ERROR - -     "__main__", mod_spec)
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,214 - twisted - 192 - ERROR - -   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,218 - twisted - 192 - ERROR - -     exec(code, run_globals)
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,220 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 651, in <module>
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,226 - twisted - 192 - ERROR - -     main()
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,229 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 646, in main
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,234 - twisted - 192 - ERROR - -     hs = setup(sys.argv[1:])
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,237 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/app/homeserver.py", line 348, in setup
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,242 - twisted - 192 - ERROR - -     hs.setup()
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,244 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/server.py", line 242, in setup
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,249 - twisted - 192 - ERROR - -     self.datastores = DataStores(self.DATASTORE_CLASS, self)
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,252 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/__init__.py", line 47, in __init__
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,256 - twisted - 192 - ERROR - -     with make_conn(database_config, engine) as db_conn:
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,259 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 101, in make_conn
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,263 - twisted - 192 - ERROR - -     db_conn = engine.module.connect(**db_params)
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,265 - twisted - 192 - ERROR - -   File "/opt/yunohost/matrix-synapse/lib/python3.5/site-packages/psycopg2/__init__.py", line 127, in connect
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,270 - twisted - 192 - ERROR - -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,272 - twisted - 192 - ERROR - - psycopg2.OperationalError: could not connect to server: Connection refused
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,275 - twisted - 192 - ERROR - -         Is the server running on host "localhost" (::1) and accepting
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,278 - twisted - 192 - ERROR - -         TCP/IP connections on port 5432?
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,280 - twisted - 192 - ERROR - - could not connect to server: Connection refused
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,283 - twisted - 192 - ERROR - -         Is the server running on host "localhost" (127.0.0.1) and accepting
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,286 - twisted - 192 - ERROR - -         TCP/IP connections on port 5432?
Jun 09 19:29:27 python[17720]: 2020-06-09 19:29:27,289 - twisted - 192 - ERROR - -
Jun 09 19:29:29 systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Jun 09 19:29:29 systemd[1]: matrix-synapse.service: Unit entered failed state.
Jun 09 19:29:29 systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Jun 09 19:29:32 systemd[1]: matrix-synapse.service: Service hold-off time over, scheduling restart.
Jun 09 19:29:32 systemd[1]: Stopped Synapse Matrix homeserver.
-- Subject: Unit matrix-synapse.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit matrix-synapse.service has finished shutting down.
Jun 09 19:29:32 systemd[1]: Starting Synapse Matrix homeserver...
-- Subject: Unit matrix-synapse.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit matrix-synapse.service has begun starting up.
```

do you have any idea how to solve this THANKS

**Comment by clokep** [comment]
I'm guessing that port 5432 is your PostreSQL database? Is it still running / accessible from where you're running Synapse?

**Comment by clokep** [comment]
Closing due to lack of response.

**Comment by rocky-III** [comment]
sorry  -  I did a reinstall
