### ISSUE TITLE
Missing dependency for webp thumbnailing in Docker image

### ISSUE THREAD

**Issue by juhovan** [matrix-org/synapse#7694]
### Description
PR  #7586 added support for webp thumbnailing, but dockerfile is missing libwebp-dev which is required for Pillow to be able to handle webp images.

### Steps to reproduce

- Use official docker image (1.15.0)
- Upload a webp image and you will get an error and Synapse will log:
```2020-06-13 14:52:54,009 - synapse.http.server - 113 - ERROR - POST-212 - Failed handle request via 'UploadResource': <XForwardedForRequest at 0x7f83ec173d50 method='POST' uri='/_matrix/media/r0/upload?filename=APxeUttzxAlPQjaSFUHk.webp' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    await h(self, request)
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/upload_resource.py", line 86, in _async_render_POST
    media_type, upload_name, request.content, content_length, requester.user
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 171, in create_content
    await self._generate_thumbnails(None, media_id, media_id, media_type)
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/media_repository.py", line 578, in _generate_thumbnails
    thumbnailer = Thumbnailer(input_path)
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/media/v1/thumbnailer.py", line 40, in __init__
    self.image = Image.open(input_path)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file '/data/media_store/local_content/zE/eG/UpUBjEyPUTciGGeOzjHc'
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**:

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.15.0

- **Install method**: Docker image
<!-- examples: package manager/git clone/pip  -->

- **Platform**:
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by clokep** [comment]
Thanks for the bug report. Any chance you could put up a PR adding this to the docker file?
