### ISSUE TITLE
_contains_display_name evaluator barfs on events with no body

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#7700]
given an incoming event with no `content.body`:
```
2020-06-15 19:00:06,270 - synapse.federation.federation_server - 290 - ERROR - PUT-1359406-$1592244001432863GBGGz:matrix.org- Failed to handle PDU $1592244001432863GBGGz:matrix.org
...
Traceback (most recent call last):
  File "/opt/synapse/synapse/synapse/federation/federation_server.py", line 279, in process_pdus_for_room
    await self._handle_received_pdu(origin, pdu)
  File "/opt/synapse/synapse/synapse/federation/federation_server.py", line 658, in _handle_received_pdu
    await self.handler.on_receive_pdu(origin, pdu, sent_to_us_directly=True)
  File "/opt/synapse/synapse/synapse/handlers/federation.py", line 412, in on_receive_pdu
    await self._process_received_pdu(origin, pdu, state=state)
  File "/opt/synapse/synapse/synapse/handlers/federation.py", line 690, in _process_received_pdu
    context = await self._handle_new_event(origin, event, state=state)
  File "/opt/synapse/synapse/synapse/handlers/federation.py", line 1841, in _handle_new_event
    event, context
  File "/opt/synapse/synapse/synapse/push/action_generator.py", line 43, in handle_push_actions_for_event
    yield self.bulk_evaluator.action_for_event_by_user(event, context)
  File "/opt/synapse/env3/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/opt/synapse/synapse/synapse/push/bulk_push_rule_evaluator.py", line 190, in action_for_event_by_user
    evaluator, rule["conditions"], uid, display_name, condition_cache
  File "/opt/synapse/synapse/synapse/push/bulk_push_rule_evaluator.py", line 215, in _condition_checker
    res = evaluator.matches(cond, uid, display_name)
  File "/opt/synapse/synapse/synapse/push/push_rule_evaluator.py", line 107, in matches
    return self._contains_display_name(display_name)
  File "/opt/synapse/synapse/synapse/push/push_rule_evaluator.py", line 161, in _contains_display_name
    return r.search(body)
TypeError: expected string or bytes-like object
2020-06-15 19:00:06,285 - synapse.logging.context - 396 - WARNING - PUT-1359406-$1592244001432863GBGGz:matrix.org- Re-starting finished log context PUT-1359406-$1592244001432863GBGGz:matrix.org
```

**Comment by clokep** [comment]
We check right above this whether body exists

https://github.com/matrix-org/synapse/blob/7cb8b4bc67042a39bd1b0e05df46089a2fce1955/synapse/push/push_rule_evaluator.py#L150-L151

I wonder if this `body` in this case is an object or something here.

**Comment by richvdh** [comment]
my bad.

```json
{
  "content": {
    "body": 1
  },
  "event_id": "$1592244001432863GBGGz:matrix.org",
  "origin_server_ts": 1592244001222,
  "sender": "@richvdh:matrix.org",
  "type": "org.richvdh.n",
  "unsigned": {
    "age": 3129,
    "transaction_id": "m1592244001050.2"
  },
  "room_id": "!qOZKfwKPirAoSosXrf:matrix.org"
}
```

**Comment by richvdh** [comment]
and now the whole damn room is broken :-S. subsequent events give:

```
Exception: Error fetching missing prev_events for $1592244953434486sDgfG:matrix.org: expected string or bytes-like object
```
