### ISSUE TITLE
Sender address rejected: Domain not found . Where to specify sender/from email in homeserevr.yaml?

### ISSUE THREAD

**Issue by 4khi1** [matrix-org/synapse#7715]
I added my domain in /etc/mailname, postfix config also.
Still, I am getting this...

> MAIL FROM:<ubuntu@ip-172-26-13-215.ap-south-1.compute.internal> 

```
2020-06-17 12:09:50,006 - synapse.handlers.identity - 358 - ERROR - POST-1007 - Error sending threepid validation email to akhil@example.com 
Traceback (most recent call last): 
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/handlers/identity.py", line 355, in send_threepid_validation 
    await send_email_func(email_address, token, client_secret, session_id) 
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/push/mailer.py", line 207, in send_add_threepid_mail 
    template_vars, 
  File "/root/synapse/env/lib/python3.6/site-packages/synapse/push/mailer.py", line 323, in send_email 
    requireTransportSecurity=self.hs.config.require_transport_security, 
twisted.mail._except.SMTPDeliveryError: 450 No recipients accepted 
akhil@example.com: 450 4.1.8 <ubuntu@ip-172-26-13-215.ap-south-1.compute.internal>: Sender address rejected: Domain not found 
>>> MAIL FROM:<ubuntu@ip-172-26-13-215.ap-south-1.compute.internal> 
<<< 250 2.1.0 Ok 
>>> RCPT TO:<akhil@example.com> 
<<< 450 4.1.8 <ubuntu@ip-172-26-13-215.ap-south-1.compute.internal>: Sender address rejected: Domain not found 

2020-06-17 12:09:50,006 - synapse.http.server - 81 - INFO - POST-1007 - <SynapseRequest at 0x7fcf2d7064e0 method='POST' uri='/_matrix/client/r0/account/3pid/email/requestToken' clientproto='HTTP/1.1' site=8448> SynapseError: 500 - An error was encountered when sending the email 
2020-06-17 12:09:50,007 - synapse.access.http.8448 - 311 - INFO - POST-1007 - ::ffff:127.0.0.1 - 8448 - {None} Processed request: 2.592sec/0.000sec (0.009sec, 0.000sec) (0.001sec/0.001sec/2) 81B 500 "POST /_matrix/client/r0/account/3pid/email/requestToken HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36" [0 dbevts] 

```

**Comment by 4khi1** [comment]
Duplicate of #2326

**Comment by 4khi1** [comment]
# notif_from defines the "From" address to use when sending emails.
