### ISSUE TITLE
Read recipts not handled properly after upgrading to 1.15.1 (psql)

### ISSUE THREAD

**Issue by pstn** [matrix-org/synapse#7739]
### Description
I upgraded my synapse from 1.13 straight to 1.13 and since then read rooms appear to be unread again regularly

### Steps to reproduce
(Hard since it seems to be a DB that has been in service for years)

* Mark room as read
* Restart client
* Room unread again

#### Expected

* Room should stay read

#### Synapse Log

```
Jun 24 10:14:02 matrix synapse[320]: synapse.federation.federation_server: [PUT-1404643] Failed to handle edu 'm.receipt'
                                     Traceback (most recent call last):
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 818, in on_edu
                                         await handler(origin, content)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/handlers/receipts.py", line 65, in _received_remote_receipt
                                         await self._handle_new_receipts(receipts)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/handlers/receipts.py", line 79, in _handle_new_receipts
                                         receipt.data,
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/data_stores/main/receipts.py", line 468, in insert_receipt
                                         stream_id=stream_id,
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 527, in runInteraction
                                         **kwargs
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
                                         result = result.throwExceptionIntoGenerator(g)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
                                         return g.throw(self.type, self.value, self.tb)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 575, in runWithConnection
                                         self._db_pool.runWithConnection(inner_func, *args, **kwargs)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
                                         result = inContext.theWork()
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
                                         inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
                                         return self.currentContext().callWithContext(ctx, func, *args, **kw)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
                                         return func(*args,**kw)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
                                         compat.reraise(excValue, excTraceback)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
                                         raise exception.with_traceback(traceback)
                                       File "/nix/store/r5w3zav5744839zii5kr3hsm7llhhg3k-python3.7-Twisted-20.3.0/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
                                         result = func(conn, *args, **kw)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 572, in inner_func
                                         return func(conn, *args, **kwargs)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 418, in new_transaction
                                         r = func(cursor, *args, **kwargs)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/data_stores/main/receipts.py", line 409, in insert_linearized_receipt_txn
                                         lock=False,
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 768, in simple_upsert_txn
                                         txn, table, keyvalues, values, insertion_values=insertion_values
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 881, in simple_upsert_txn_native_upsert
                                         txn.execute(sql, list(allvalues.values()))
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 210, in execute
                                         self._do_execute(self.txn.execute, sql, *args)
                                       File "/nix/store/5ia3dfrx8isfwwzn0fhqb4pc2a3a2587-matrix-synapse-1.15.1/lib/python3.7/site-packages/synapse/storage/database.py", line 236, in _do_execute
                                         return func(sql, *args)
                                     psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: matrix.xndr.de

If not matrix.org:

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: 1.15.1

- **Install method**: Package manager
<!-- examples: package manager/git clone/pip  -->

- **Platform**: nixos-container
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by pstn** [comment]
I was able to resolve this issue by running

```
ALTER TABLE ONLY receipts_graph
    ADD CONSTRAINT receipts_graph_uniqueness UNIQUE (room_id, receipt_type, user_id);

ALTER TABLE ONLY receipts_linearized
    ADD CONSTRAINT receipts_linearized_uniqueness UNIQUE (room_id, receipt_type, user_id);
```

from the [synapse psql schemas](https://github.com/matrix-org/synapse/blob/develop/synapse/storage/data_stores/main/schema/full_schemas/54/full.sql.postgres#L1362).

I consider this issue to be resolved, however I'm leaving this open to give a project member a chance to see the issue. In case it's not an issue that is interesting in some way, just close this issue without any further comment.

**Comment by clokep** [comment]
I'm glad you got it figured out! Definitely seems like something odd happened as those indexes were added a long time ago (~2015).

A few questions that might help are:
* Do you know roughly when you setup your database / what version of Synapse was used?
* Was this database migrated from SQLite to Postgresql? (If so, do you know what version of Synapse was used to do that?)
* Have you ever did a dump & restore operation? (We've noticed this sometimes seems to drop the indexes. It is commonly done if the wrong character set was used when initially setting up the database.)

**Comment by pstn** [comment]
It is an old instance that was migrated from sqlite to postgres (before 2015 sounds about right) and then dumped/restored at least once for a postgresql mayor version upgrade. I guess that doesn't help much in finding the ultimate cause of the issue.

I'm thinking about running all the `ALTER TABLE [...] ADD CONSTRAINT` on the database again to rule out anything missing without causing visible issues right now. Do you think that is a good idea?

**Comment by clokep** [comment]
> It is an old instance that was migrated from sqlite to postgres (before 2015 sounds about right) and then dumped/restored at least once for a postgresql mayor version upgrade.

It was probably related to one of these, but yeah unlikely to find the original cause without logs and such from that time period.

> I'm thinking about running all the `ALTER TABLE [...] ADD CONSTRAINT` on the database again to rule out anything missing without causing visible issues right now. Do you think that is a good idea?

This *should* be OK (it should either reject the constraint for already being there...or add it). I'd backup before doing that of course. 😄

**Comment by pstn** [comment]
Alright, I'll be doing that and close this ticket in the hopes that it might help anybody that might have this issue in the future.

**Comment by clokep** [comment]
Thanks @pstn! Would be interesting to post back about how it goes!

**Comment by pstn** [comment]
@clokep I applied all the constraint and got an error for each and every one because they were already in place. Seems I'm good now.
