### ISSUE TITLE
psycopg2.errors.SerializationFailure in `populate_monthly_active_users`

### ISSUE THREAD

**Issue by progserega** [matrix-org/synapse#7752]
```
    2020-06-29 12:49:07,449 - synapse.http.server - 113 - ERROR - GET-39526 - Failed handle request via 'PushRuleRestServlet': <SynapseRequest at 0x7fe35291b710 method='GET' uri='/_matrix/client/r0/pushrules/' clientproto='HTTP/1.0' site=8008>
    Traceback (most recent call last): 
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
        await h(self, request)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/http/server.py", line 350, in _async_render
        callback_return = await callback_return
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/rest/client/v1/push_rule.py", line 131, in on_GET 
        requester = await self.auth.get_user_by_req(request)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/api/auth.py", line 244, in get_user_by_req
        device_id=device_id,
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/client_ips.py", line 395, in insert_client_ip
        yield self.populate_monthly_active_users(user_id)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/monthly_active_users.py", line 359, in populate_monthly_active_users
        yield self.upsert_monthly_active_user(user_id)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/monthly_active_users.py", line 277, in upsert_monthly_active_user
        "upsert_monthly_active_user", self.upsert_monthly_active_user_txn, user_id
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 527, in runInteraction
        **kwargs
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 575, in runWithConnection
        self._db_pool.runWithConnection(inner_func, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
        result = inContext.theWork()
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
        inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
        return self.currentContext().callWithContext(ctx, func, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
        return func(*args,**kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
        compat.reraise(excValue, excTraceback)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/python/compat.py", line 464, in reraise
        raise exception.with_traceback(traceback)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
        result = func(conn, *args, **kw)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 572, in inner_func
        return func(conn, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 418, in new_transaction
        r = func(cursor, *args, **kwargs)
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/data_stores/main/monthly_active_users.py", line 310, in upsert_monthly_active_user_txn
        values={"timestamp": int(self._clock.time_msec())},
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 768, in simple_upsert_txn
        txn, table, keyvalues, values, insertion_values=insertion_values
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 881, in simple_upsert_txn_native_upsert
        txn.execute(sql, list(allvalues.values()))
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 210, in execute
        self._do_execute(self.txn.execute, sql, *args) 
      File "/opt/venvs/matrix-synapse/lib/python3.5/site-packages/synapse/storage/database.py", line 236, in _do_execute
        return func(sql, *args) 
    psycopg2.errors.SerializationFailure: ОШИБКА:  не удалось сериализовать доступ из-за параллельного изменения
```

-->
- **Version**: 1.15.1

- **Install method**:
debian package

- **Platform**: debian 9.12

**Comment by babolivier** [comment]
Hi, and thanks for opening this issue.
Not beine able to read Cyrillic myself, could you please translate into English the error message on the last line?

> ОШИБКА:  не удалось сериализовать доступ из-за параллельного изменения

**Comment by savyajha** [comment]
I don't either, but I see this in my postgres logs all the time:

`ERROR:  could not serialize access due to concurrent update`

It could be concurrent update or delete. I don't see this behaviour on the other apps I have running on that server (shared database instance).

**Comment by progserega** [comment]
> Hi, and thanks for opening this issue.
> Not being able to read Cyrillic myself, could you please translate into English the error message on the last line?
> 
> > ОШИБКА:  не удалось сериализовать доступ из-за параллельного изменения

`ERROR: could not serialize access due to concurrent update`

**Comment by richvdh** [comment]
are there any other entries in the log before the error?

**Comment by progserega** [comment]
I do not found topic error in my logs... O_o May be log removed? O_o
But I get new such errors. I show it with lines before in attachment.

All russians text: "ОШИБКА:  не удалось сериализовать доступ из-за параллельного изменения"
mean: "ERROR: could not serialize access due to concurrent update" 
There are many such lines in log :-/ 
[error.log](https://github.com/matrix-org/synapse/files/4874260/error.log)

**Comment by savyajha** [comment]
I can confirm that my postgres log also has many messages about serialization access failure due to concurrent updates/deletes as well. They occur very regularly with no errors in my synapse logs.

**Comment by richvdh** [comment]
ok, so these errors are happening as part of the monthly-active-user tracking, so the first question is whether you actually need that functionality? It is enabled via the `limit_usage_by_mau` (or `mau_stats_only`) configuration options. If you can turn it off, that is an easy fix.

**Comment by savyajha** [comment]
I don't have that option set in my config file. Is it true by default?

**Comment by richvdh** [comment]
@savyajha no. sounds like you have a separate problem. Please file a new bug.

**Comment by clokep** [comment]
Closing due to lack of response.
