### ISSUE TITLE
Failure on worker start - return self.get_push_rules_stream_token() - TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by EldarSagirov** [matrix-org/synapse#7819]
Hi, i'm trying to update server from 1.9.X to 1.15.2 and get error when workers stat.

Stack trace:
--------------------------------------------------------------------------------
2020-07-10 14:06:35,398 - twisted - 192 - INFO - None - Redirected stdout/stderr to logs
2020-07-10 14:06:35,399 - root - 257 - WARNING - None - ***** STARTING SERVER *****
2020-07-10 14:06:35,399 - root - 258 - WARNING - None - Server /usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py version 1.16.1
2020-07-10 14:06:35,399 - root - 259 - INFO - None - Server hostname: ********
2020-07-10 14:06:35,399 - root - 260 - INFO - None - Instance name: synapse.app.synchrotron
2020-07-10 14:06:35,399 - synapse.app.homeserver - 372 - INFO - None - Setting up server
2020-07-10 14:06:35,399 - synapse.server - 275 - INFO - None - Setting up.
2020-07-10 14:06:35,895 - synapse.storage.data_stores - 50 - INFO - None - Preparing database 'master'...
2020-07-10 14:06:36,362 - synapse.storage.prepare_database - 325 - INFO - None - Upgrading schema to v58
2020-07-10 14:06:36,422 - synapse.storage.data_stores - 60 - INFO - None - Starting 'main' data store
2020-07-10 14:06:37,807 - synapse.storage.data_stores.main.event_push_actions - 497 - INFO - None - Searching for stream ordering 1 month ago
2020-07-10 14:06:38,065 - synapse.storage.data_stores.main.event_push_actions - 502 - INFO - None - Found stream ordering 1 month ago: it's 2
2020-07-10 14:06:38,066 - synapse.storage.data_stores.main.event_push_actions - 504 - INFO - None - Searching for stream ordering 1 day ago
2020-07-10 14:06:38,313 - synapse.storage.data_stores.main.event_push_actions - 509 - INFO - None - Found stream ordering 1 day ago: it's 2
2020-07-10 14:06:38,724 - twisted - 192 - ERROR -  - Traceback (most recent call last):
2020-07-10 14:06:38,724 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2020-07-10 14:06:38,725 - twisted - 192 - ERROR -  -     "__main__", mod_spec)
2020-07-10 14:06:38,725 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2020-07-10 14:06:38,725 - twisted - 192 - ERROR -  -     exec(code, run_globals)
2020-07-10 14:06:38,725 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 688, in <module>
2020-07-10 14:06:38,726 - twisted - 192 - ERROR -  -     main()
2020-07-10 14:06:38,726 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 683, in main
2020-07-10 14:06:38,727 - twisted - 192 - ERROR -  -     hs = setup(sys.argv[1:])
2020-07-10 14:06:38,727 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 375, in setup
2020-07-10 14:06:38,728 - twisted - 192 - ERROR -  -     hs.setup()
2020-07-10 14:06:38,728 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/server.py", line 277, in setup
2020-07-10 14:06:38,728 - twisted - 192 - ERROR -  -     self.datastores = DataStores(self.DATASTORE_CLASS, self)
2020-07-10 14:06:38,728 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/__init__.py", line 67, in __init__
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -     self.main = main_store_class(database, db_conn, hs)
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/__init__.py", line 173, in __init__
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -     super(DataStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/events_bg_updates.py", line 36, in __init__
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -     super(EventsBackgroundUpdatesStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,729 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/roommember.py", line 1045, in __init__
2020-07-10 14:06:38,730 - twisted - 192 - ERROR -  -     super(RoomMemberStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,730 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/room.py", line 1044, in __init__
2020-07-10 14:06:38,730 - twisted - 192 - ERROR -  -     super(RoomStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,730 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/room.py", line 832, in __init__
2020-07-10 14:06:38,731 - twisted - 192 - ERROR -  -     super(RoomBackgroundUpdateStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,731 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/room.py", line 79, in __init__
2020-07-10 14:06:38,731 - twisted - 192 - ERROR -  -     super(RoomWorkerStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,731 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/registration.py", line 927, in __init__
2020-07-10 14:06:38,732 - twisted - 192 - ERROR -  -     super(RegistrationStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,732 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/registration.py", line 801, in __init__
2020-07-10 14:06:38,732 - twisted - 192 - ERROR -  -     super(RegistrationBackgroundUpdateStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,732 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/registration.py", line 40, in __init__
2020-07-10 14:06:38,733 - twisted - 192 - ERROR -  -     super(RegistrationWorkerStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,733 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/stream.py", line 254, in __init__
2020-07-10 14:06:38,733 - twisted - 192 - ERROR -  -     super(StreamWorkerStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,733 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/transactions.py", line 50, in __init__
2020-07-10 14:06:38,733 - twisted - 192 - ERROR -  -     super(TransactionStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,734 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/state.py", line 467, in __init__
2020-07-10 14:06:38,734 - twisted - 192 - ERROR -  -     super(StateStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,734 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/state.py", line 58, in __init__
2020-07-10 14:06:38,734 - twisted - 192 - ERROR -  -     super(StateGroupWorkerStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,735 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/state.py", line 326, in __init__
2020-07-10 14:06:38,735 - twisted - 192 - ERROR -  -     super(MainStateBackgroundUpdateStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,735 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/event_federation.py", line 632, in __init__
2020-07-10 14:06:38,735 - twisted - 192 - ERROR -  -     super(EventFederationStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,736 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/media_repository.py", line 38, in __init__
2020-07-10 14:06:38,736 - twisted - 192 - ERROR -  -     super(MediaRepositoryStore, self).__init__(database, db_conn, hs)
2020-07-10 14:06:38,736 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/media_repository.py", line 22, in __init__
2020-07-10 14:06:38,736 - twisted - 192 - ERROR -  -     database, db_conn, hs
2020-07-10 14:06:38,737 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/push_rule.py", line 99, in __init__
2020-07-10 14:06:38,737 - twisted - 192 - ERROR -  -     max_value=self.get_max_push_rules_stream_id(),
2020-07-10 14:06:38,737 - twisted - 192 - ERROR -  -   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/push_rule.py", line 759, in get_max_push_rules_stream_id
2020-07-10 14:06:38,738 - twisted - 192 - ERROR -  -     return self.get_push_rules_stream_token()[0]
2020-07-10 14:06:38,738 - twisted - 192 - ERROR -  - TypeError: 'int' object is not subscriptable

What's wrong?

**Comment by erikjohnston** [comment]
This looks like you're trying to start a worker with as a master process, how are you starting it?

**Comment by benbz** [comment]
I just ran into this. In my case I was running `python -m synapse.app.homeserver ...` rather than `python -m synapse.app.generic_worker ...` for my workers

**Comment by clokep** [comment]
> I just ran into this. In my case I was running `python -m synapse.app.homeserver ...` rather than `python -m synapse.app.generic_worker ...` for my workers

Ideally running workers with `python -m synapse.app.homeserver ...` would work, but it is not expected to at the moment. Using `python -m synapse.app.generic_worker ...` is the proper thing to do here.

@EldarSagirov -- does this help to solve your issue?

**Comment by richvdh** [comment]
seems like this probably got solved
