### ISSUE TITLE
Starting homeserver fails on debian at 1.17.0

### ISSUE THREAD

**Issue by bendschs** [matrix-org/synapse#7841]
### Description

After installing newest version 1.17 matrix-synapse refuses to start on debian buster. 

### Steps to reproduce
- install update via "pip install -U matrix-synapse" 
- start the bridge with "/opt/synapse/bin/python3.7 -m synapse.app.homeserver --config-path=/opt/synapse/homeserver.yaml"
- starting fails with the following error-message

`
Traceback (most recent call last):   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code     exec(code, run_globals)   File "/opt/synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 30, in <module>     from twisted.application import service   File "/opt/synapse/lib/python3.7/site-packages/twisted/application/service.py", line 21, in <module>     from twisted.persisted import sob   File "/opt/synapse/lib/python3.7/site-packages/twisted/persisted/sob.py", line 21, in <module>     from twisted.python import log, runtime ImportError: cannot import name 'log' from 'twisted.python' (unknown location)
`

### Version information

- **Homeserver**
- **Version**: 1.17.0
- **Install method**: pip
- **Platform**: debian buster

**Comment by richvdh** [comment]
https://xkcd.com/979/
