### ISSUE TITLE
RoomMessageListRestServlet raises exception with emoji unicodes in room v1 event IDs

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/synapse#7911]
### Description

```
2020-07-20 18:08:56,188 - synapse.http.server - 109 - ERROR - GET-1703714- Failed handle request via 'RoomMessageListRestServlet': <XForwardedForRequest at 0x7f7740883940 method='GET' uri='/_matrix/client/r0/rooms/!redacted%3Aponies.im/messages?from=t1234&limit=100&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [a massive json dump]

Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 81, in wrapped_request_handler
    await h(self, request)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/http/server.py", line 345, in _async_render
    callback_return = await callback_return
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/rest/client/v1/room.py", line 534, in on_GET
    msgs = await self.pagination_handler.get_messages(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/handlers/pagination.py", line 367, in get_messages
    events, next_key = await self.store.paginate_room_events(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/stream.py", line 969, in paginate_room_events
    events = yield self.get_events_as_list(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/events_worker.py", line 311, in get_events_as_list
    event_entry_map = yield self._get_events_from_cache_or_db(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/events_worker.py", line 458, in _get_events_from_cache_or_db
    missing_events = yield self._get_events_from_db(
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/synapse/storage/data_stores/main/events_worker.py", line 615, in _get_events_from_db
    d = json.loads(row["json"])
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/synapse/synapse/env/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid \X escape sequence '\\': line 1 column 785 (char 784)
2020-07-20 18:08:56,217 - synapse.access.http.8008 - 291 - INFO - GET-1703714- 69.247.95.13 - 8008 - {@andrewm:amorgan.xyz} Processed request: 0.042sec/0.000sec (0.006sec, 0.013sec) (0.001sec/0.003sec/3) 67B 500 "GET /_matrix/client/r0/rooms/!redacted%3Aponies.im/messages?from=t1234&limit=100&dir=b&filter=%7B%22lazy_load_members%22%3Atrue%7D HTTP/1.1" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Element(Riot)/1.7.0 Chrome/83.0.4103.100 Electron/9.0.3 Safari/537.36" [98 dbevts]
```

This is happening in a v1 room. The room contains the following event IDs:

`$2458-5-6-2T10266.929474|Jes\\303\\272s_Pezu\\303\\261a\'s_Combative_Penguin_Persuades_Calvin_&_Theo\'s_Bored_Pigeon:ponies.im`

`$2458-5-6-2T12114.766113|Mr._Jackalope\'s_Alive_Mosquito_Admits_33\\u2153-LP\'s_Cooperative_Okapi:ponies.im`

which I believe are causing the error. As far as I can tell, [the spec](https://matrix.org/docs/spec/appendices#room-ids-and-event-ids) allows these IDs in v1 rooms.

This error is currently being spamming nonstop in my HS logs.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->

### Version information

v1.17.0

**Comment by richvdh** [comment]
a lot of me feels like the answer is just to drop support for v1 and v2 rooms...

**Comment by anoadragon453** [comment]
@richvdh writing up a plan for that at some point would be great, as at the moment I think most of the team think it entirely unfeasible with the amount of v1 rooms out there, and the current bugs with unsupported room versions.

**Comment by clokep** [comment]
@anoadragon453 I'd be curious if this still happens with 1.19.1 now that we've switched to the stdlib JSON library?

**Comment by anoadragon453** [comment]
@clokep I am still routinely getting this exception on 1.19.1rc1, yes.

**Comment by DMRobertson** [comment]
Two years on: no-one else has complained, and we're not going to go out of our way to support v1 and v2 rooms (selecting arbitrary event IDs is a bug, not a feature).

Suggest we close as WONTFIX.
