### ISSUE TITLE
Internal Server Errors when joining rooms over federation

### ISSUE THREAD

**Issue by dbkr** [matrix-org/synapse#816]
Giom tried to join #test:matrix.org from vector.im:

See vector.im's homeserver.log from 2016-06-02, grep for "POST-12316". Snippets:

```
2016-06-02 12:34:22,745 - synapse.federation.federation_base - 147 - WARNING - POST-12316- Signature check failed for $1416420704503jrxrp:localhost:8481
2016-06-02 12:34:22,990 - synapse.federation.federation_base - 138 - WARNING - POST-12316- Event content has been tampered, redacting $1416420704625hsLuD:matrix.org: {'origin': 'matrix.org', 'signatures': {'matrix.org': {'ed25519:auto': 'qSA4QiZjsjlW5ZW8TC7n6bYKsISfXO5+wGIVINoaMSvPGuRYdTEyTYxtNaZYB/8IfAVIQS5Bo53ZKu2aTL3eAA'}}, 'origin_server_ts': 1410159370035, 'sender': '@ursderbaer:matrix.org', 'event_id': '$1416420704625hsLuD:matrix.org', 'stream_ordering': 4506, 'prev_events': [['$1416420704612IkviZ:matrix.org', {'sha256': 'JurDUmwQf0hEuFzSJIKZNKSl1EoT8qj3sY3ljbJEpMU'}]], 'membership': 'join', 'state_key': '@ursderbaer:matrix.org', 'unsigned': {'age': 48446555362}, 'content': {'membership': 'join', 'avatar_url': None, 'displayname': 'ursderbaer'}, 'depth': 125, 'prev_state': [], 'room_id': '!vfFxDRtZSSdspfTSEr:matrix.org', 'auth_events': [['$1416420703388cqcZV:matrix.org', {'sha256': '9PYeDlXl6JpGYaLtVC4HxE2VJUsuDiIgrmOr+DX0/rM'}]], 'hashes': {'sha256': '3Y8V+6z7w4uECtHQYSDRlno1pFZ+QejGcQWXEQA4xFc'}, 'type': 'm.room.member'}
```

```
2016-06-02 12:34:23,469 - synapse.crypto.keyring - 123 - ERROR - - Got Exception when downloading keys for rwxs.tk: AlreadyCalledError 
Traceback (most recent call last):
  File "synapse/crypto/keyring.py", line 109, in handle_key_deferred
  File "/home/vectorhs/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "synapse/crypto/keyring.py", line 260, in do_iterations
  File "/home/vectorhs/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/home/vectorhs/.synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 494, in _startRunCallbacks
    raise AlreadyCalledError
```

```
2016-06-02 12:34:33,644 - synapse.handlers.federation - 1206 - WARNING - POST-12316- Rejecting $1416420704258naUvN:matrix.org because @harish:matrix.org
 not in room !vfFxDRtZSSdspfTSEr:matrix.org.
2016-06-02 12:34:33,652 - synapse.handlers.federation - 1206 - WARNING - POST-12316- Rejecting $14166628431555oJMlm:matrix.org because @furze99:matrix.o
rg not in room !vfFxDRtZSSdspfTSEr:matrix.org.
```

```
2016-06-02 12:34:33,666 - synapse.http.server - 135 - ERROR - POST-12316- Failed handle request synapse.http.server._async_render on <synapse.rest.Clien
tRestResource object at 0x33dbe50>: <XForwardedForRequest at 0xc17c488 method=POST uri=/_matrix/client/r0/join/#test:matrix.org?access_token=<redacted> 
clientproto=HTTP/1.1 site=8010>
Traceback (most recent call last):
  File "synapse/http/server.py", line 114, in wrapped_request_handler
IndexError: list index out of range
```

**Comment by richvdh** [comment]
I think these have probably been fixed
