### ISSUE TITLE
Populate user directory - temp_populate... does not exist

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/synapse#8209]
[edited for legibility]

Hello,
I'm trying to enable search_all_user and I followed these steps (https://github.com/matrix-org/synapse/blob/master/synapse/storage/databases/main/schema/delta/53/user_dir_populate.sql)

Unfortunately searching doesn't work and there is an error in the log:

```
2020-08-30 04:21:45,968 - synapse.storage.background_updates - 227 - INFO - background_updates-0 - Starting update batch on background update 'populate_user_directory_process_users'
2020-08-30 04:21:45,974 - synapse.storage.background_updates - 114 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 110, in run_background_updates
    result = await self.do_next_background_update(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 222, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 258, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/user_directory.py", line 300, in _populate_user_directory_process_users
    users_to_work_on = await self.db_pool.runInteraction(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 520, in runInteraction
    result = yield self.runWithConnection(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 574, in runWithConnection
    result = yield make_deferred_yieldable(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 572, in inner_func
    return func(conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 416, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/user_directory.py", line 284, in _get_next_batch
    txn.execute(sql)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 208, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 234, in _do_execute
    return func(sql, *args)
psycopg2.errors.UndefinedTable: relation "_temp_populate_user_directory_users" does not exist
LINE 1: SELECT user_id FROM _temp_populate_user_directory_users LIMI...
```

I'm using PostGreSQL and an LDAP auth provider and the newest version you can get via apt-get for Ubuntu 20.04 

As it says 
` _temp_populate_user_directory_users` does not exist, I wonder if I've forgotten something, but there is no INSERT command for an _temp...table?!

**Comment by clokep** [comment]
I'm not finding any reference to that in our code. There is a `_temp_populate_user_directory` table however. What version of Synapse is this running?

**Comment by Paule2020** [comment]
version-info:
    "python_version": "3.8.2",
    "server_version": "1.19.1"

**Comment by Paule2020** [comment]
Hm...I'ven't changed anything...I rebootet the server and everything works fine...sorry
