### ISSUE TITLE
federation not working: synapse.federation.sender.per_destination_queue - ERROR - federation_transaction_transmission_loop TX [domain.tld] Failed to send transaction

### ISSUE THREAD

**Issue by tvo6** [matrix-org/synapse#8298]
### Description

Federation stopped working a few days ago.
(I'm sorry if this is support, but I tried to join the matrix room and got an error…)

With another account, I can send messages to accounts on this server, but answers don't work.

### Version information

- **Homeserver**: ensimag.fr

- **Version**:
  - server_version | "1.5.0"
  - python_version | "3.7.5"

- **Install method**: through https://github.com/spantaleev/matrix-docker-ansible-deploy

- **Platform**: runs on a Debian 10.5 host with docker

### Log from matrix-synapse

Log message is quite similar to issue #4419, except indexes on tables looks good, and the message at the end is not the same:
```
Sep 11 20:49:31 pouzin matrix-synapse[1582]: 2020-09-11 18:49:31,710 - synapse.federation.sender.per_destination_queue - 326 - ERROR - federation_transaction_transmission_loop-104 - TX [distant-domain.tld] Failed to send transaction
Sep 11 20:49:31 pouzin matrix-synapse[1582]: Traceback (most recent call last):
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/federation/sender/per_destination_queue.py", line 196, in _transaction_transmission_loop
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     yield self._get_device_update_edus(limit)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = result.throwExceptionIntoGenerator(g)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return g.throw(self.type, self.value, self.tb)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/federation/sender/per_destination_queue.py", line 363, in _get_device_update_edus
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     self._destination, last_device_list, limit=limit
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = result.throwExceptionIntoGenerator(g)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return g.throw(self.type, self.value, self.tb)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/devices.py", line 183, in get_devices_by_remote
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     destination, from_stream_id, query_map
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = result.throwExceptionIntoGenerator(g)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return g.throw(self.type, self.value, self.tb)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/devices.py", line 233, in _get_device_update_edus_by_remote
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     include_deleted_devices=True,
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = result.throwExceptionIntoGenerator(g)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return g.throw(self.type, self.value, self.tb)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/_base.py", line 507, in runInteraction
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     **kwargs
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = result.throwExceptionIntoGenerator(g)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return g.throw(self.type, self.value, self.tb)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/_base.py", line 555, in runWithConnection
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     self._db_pool.runWithConnection(inner_func, *args, **kwargs)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = inContext.theWork()
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return func(*args,**kw)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     compat.reraise(excValue, excTraceback)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/python/compat.py", line 464, in reraise
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     raise exception.with_traceback(traceback)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     result = func(conn, *args, **kw)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/_base.py", line 552, in inner_func
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return func(conn, *args, **kwargs)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/_base.py", line 424, in _new_transaction
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     r = func(txn, *args, **kwargs)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/logging/opentracing.py", line 709, in _trace_inner
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     return func(*args, **kwargs)
Sep 11 20:49:31 pouzin matrix-synapse[1582]:   File "/usr/local/lib/python3.7/site-packages/synapse/storage/data_stores/main/end_to_end_keys.py", line 154, in _get_e2e_device_keys_txn
Sep 11 20:49:31 pouzin matrix-synapse[1582]:     ).setdefault(row["user_id"], {})[row["key_id"]] = row["signature"]
Sep 11 20:49:31 pouzin matrix-synapse[1582]: AttributeError: 'NoneType' object has no attribute 'setdefault'
```

Thanks for any clue!

**Comment by clokep** [comment]
Looks like you're running quite an old version (1.5.0). This code has changed a bit since then, the first thing I'd suggest is upgrading!

**Comment by tvo6** [comment]
OK, I'll try to do that tomorrow. May I install a fresh new matrix-synapse server and copy the current databases and media files in there, or it will probably fail due to database structure changes?

Thanks!

**Comment by clokep** [comment]
The database migrations should get applied, but I'm not sure we have it documented exactly what needs to be done to move things to a new server.

**Comment by tvo6** [comment]
Indeed, I migrated from the ansible-docker install to a basic matrix-synapse homeserver, everything looks good.
Thanks!
