### ISSUE TITLE
newclient.ResponseNeverReceived, cannot write to or leave a room

### ISSUE THREAD

**Issue by verymilan** [matrix-org/synapse#8303]
Hi there, i have got a recommendation to report this as an issue, so here we go:

I am unable to write anything or leave the Synapse Admins room. In terms of reproducing, i only recall changing my password.

Element-web returns `User @user:server.de not in room !mjbDjyNsRXndKLkHIe:matrix.org (<FrozenEventV3 event_id='$vt-UGr7...tqwT-QSov6-I', type='m.room.member', state_key='@user:server.de'>)` when trying to write anything.

If i cought the right moment (i am quite confident as i can also reproduce this on leave attempts), this could be the related error, even though the eventid is different... : 
````
2020-09-12 15:10:01,418 - synapse.federation.federation_server - 309 - ERROR - PUT-552761-, $ETv4AU0...Qmr_vatd6NrO-EnTmfvhAykgQ - Failed to handle PDU , $ETv4AU0...Qmr_vatd6NrO-EnTmfvhAykgQ
Traceback (most recent call last):
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 298, in process_pdus_for_room
    await self._handle_received_pdu(origin, pdu)
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/federation/federation_server.py", line 683, in _handle_received_pdu
    await self.handler.on_receive_pdu(origin, pdu, sent_to_us_directly=True)
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/handlers/federation.py", line 418, in on_receive_pdu
    await self._process_received_pdu(origin, pdu, state=state)
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/handlers/federation.py", line 701, in _process_received_pdu
    context = await self._handle_new_event(origin, event, state=state)
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/handlers/federation.py", line 1901, in _handle_new_event
    [(event, context)], backfilled=backfilled
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/handlers/federation.py", line 2918, in persist_events_and_notify
    backfilled=backfilled,
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/replication/http/_base.py", line 196, in send_request
    result = await request_func(uri, data, headers=headers)
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/http/client.py", line 430, in post_json_get_json
    "POST", uri, headers=Headers(actual_headers), data=json_str
  File ", synapse/.synapse/env/lib/python3.7/site-packages/synapse/http/client.py", line 332, in request
    response = await make_deferred_yieldable(request_deferred)
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
2020-09-12 15:10:01,420 - synapse.logging.context - 396 - WARNING - PUT-552761-$ETv4AU0...Qmr_vatd6NrO-EnTmfvhAykgQ - Re-starting finished log context PUT-552761-$ETv4AU0...Qmr_vatd6NrO-EnTmfvhAykgQ
````
However there are more of those errors in my log, so either more users and rooms are affected or this is something else...

I have also noticed various DataLoss errors and am not sure if this could be related to this and/or mistakes in my worker setup... .
````
2020-09-12 15:19:16,273 - twisted - 231 - CRITICAL - -
twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure builtins.ValueError: write to closed file>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]
````

I am running the latest Synapse installed with pip.

**Comment by erikjohnston** [comment]
That seems quite strange. Can you send over the full logs please (at INFO level)?

**Comment by verymilan** [comment]
It appears that recent updates have fixed this issue, at least i was able to send again, so there is no further info i can provide. :)
