### ISSUE TITLE
Unable to login to homeserver

### ISSUE THREAD

**Issue by danger89** [matrix-org/synapse#8469]
### Description

Suddenly I was **not** able to login to my own homeserver any more. While I worked just before, no issues at all...

Federation test seems to be fine: https://federationtester.matrix.org/#melroy.org
And the server is just up and running: https://matrix.melroy.org

Dockers are running fine as well:

![image](https://user-images.githubusercontent.com/628926/95143874-90fe0000-0777-11eb-8d21-7e0cc6e89217.png)
### Steps to reproduce

- Try to login with Element desktop client
- Client goes to 'offline'
- Eventually I get (and other users that use my Synape server):

![image](https://user-images.githubusercontent.com/628926/95143844-79bf1280-0777-11eb-9fec-2a3ee5a90241.png)

Of-course I expect to be able to login. At ALL times.

### Version information

- **Homeserver**: matrix.melroy.org

If not matrix.org:

- **Version**: v1.20.1 (latest version of matrixdotorg/synapse)
And python version: 3.7.9

- **Install method**: Docker

- **Platform**: Docker container on Debian Buster (10)

When I enabled debug in the logging, I get some errors.

```
2020-10-05 23:50:56,954 - synapse.storage.txn - 415 - DEBUG - _maybe_retry_device_resync-2 - [TXN START] {get_user_ids_requiring_device_list_resync-51}
2020-10-05 23:50:56,956 - synapse.storage.txn - 504 - DEBUG - _maybe_retry_device_resync-2 - [TXN END] {get_user_ids_requiring_device_list_resync-51} 0.002342 sec
2020-10-05 23:50:56,957 - synapse.handlers.device - 730 - DEBUG - _maybe_retry_device_resync-2 - Attempting to resync the device list for @verifirs:brickshop.io
2020-10-05 23:50:56,959 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - --- Logging error ---
2020-10-05 23:50:56,959 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - Traceback (most recent call last):
2020-10-05 23:50:56,960 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
2020-10-05 23:50:56,960 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     msg = self.format(record)
2020-10-05 23:50:56,961 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
2020-10-05 23:50:56,961 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     return fmt.format(record)
2020-10-05 23:50:56,961 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/logging/__init__.py", line 611, in format
2020-10-05 23:50:56,961 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     s = self.formatMessage(record)
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/logging/__init__.py", line 580, in formatMessage
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     return self._style.format(record)
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/logging/__init__.py", line 422, in format
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     return self._fmt % record.__dict__
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - KeyError: 'request'
2020-10-05 23:50:56,962 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - Call stack:
2020-10-05 23:50:56,963 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2020-10-05 23:50:56,963 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     "__main__", mod_spec)
2020-10-05 23:50:56,963 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     exec(code, run_globals)
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 687, in <module>
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     main()
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 683, in main
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     run(hs)
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/app/homeserver.py", line 674, in run
2020-10-05 23:50:56,964 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     logger=logger,
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/app/_base.py", line 132, in start_reactor
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     run()
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/app/_base.py", line 116, in run
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     run_command()
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
2020-10-05 23:50:56,965 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     self.mainLoop()
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     self.runUntilCurrent()
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/metrics/__init__.py", line 517, in f
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     ret = func(*args, **kwargs)
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/base.py", line 886, in runUntilCurrent
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     f(*a, **kw)
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 460, in callback
2020-10-05 23:50:56,966 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     self._startRunCallbacks(result)
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     self._runCallbacks()
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     current.result = callback(current.result, *args, **kw)
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     _inlineCallbacks(r, g, status)
2020-10-05 23:50:56,967 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     result = g.send(result)
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 205, in run
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     result = await result
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/logging/opentracing.py", line 743, in _trace_inner
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     return await func(*args, **kwargs)
2020-10-05 23:50:56,968 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/device.py", line 693, in _maybe_retry_device_resync
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     user_id=user_id, mark_failed_as_stale=False,
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/handlers/device.py", line 735, in user_device_resync
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     result = await self.federation.query_user_devices(origin, user_id)
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/logging/utils.py", line 69, in wrapped
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     _log_debug_as_f(f, "Invoked '%(func_name)s' with args: %(args)s", msg_args)
2020-10-05 23:50:56,969 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -   File "/usr/local/lib/python3.7/site-packages/synapse/logging/utils.py", line 42, in _log_debug_as_f
2020-10-05 23:50:56,970 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 -     logger.handle(record)
2020-10-05 23:50:56,970 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - Message: "Invoked '%(func_name)s' with args: %(args)s"
2020-10-05 23:50:56,970 - twisted - 231 - ERROR - _maybe_retry_device_resync-2 - Arguments: {'func_name': 'query_user_devices', 'args': 'self=<synapse.federation.federation_client.FederationCl..., destination=brickshop.io, user_id=@verifirs:brickshop.io, timeout=30000'}
```

**The full log file:**
[matrix_log.txt.tar.gz](https://github.com/matrix-org/synapse/files/5330706/matrix_log.txt.tar.gz)

Thx!

Ps. restarting the server won't help either. I tried everything I could.

Regards,
Melroy van den Berg

**Comment by danger89** [comment]
Ah, misconfigured server. But it was noway found in the checks.

I create a new issue, for this specific check. And closing this.
