### ISSUE TITLE
Can't start Synapse after upgrade to Ubuntu 20.04

### ISSUE THREAD

**Issue by mwllgr** [matrix-org/synapse#8490]
### Description

After upgrading my LXC container from Ubuntu 18.04 to 20.04.1, matrix-synapse won't start anymore.

### Steps to reproduce

- Upgrade from Ubuntu Server 18.04 to 20.04.1

```
Oct  7 19:18:26 srv-ic-sec systemd[1]: Starting Synapse Matrix homeserver...
Oct  7 19:18:27 srv-ic-sec systemd[1]: Started Synapse Matrix homeserver.
Oct  7 19:18:29 srv-ic-sec python3[1589]: Traceback (most recent call last):
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Oct  7 19:18:29 srv-ic-sec python3[1589]:     return _run_code(code, main_globals, None,
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
Oct  7 19:18:29 srv-ic-sec python3[1589]:     exec(code, run_globals)
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/app/homeserver.py", line 639, in <module>
Oct  7 19:18:29 srv-ic-sec python3[1589]:     main()
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/app/homeserver.py", line 634, in main
Oct  7 19:18:29 srv-ic-sec python3[1589]:     hs = setup(sys.argv[1:])
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/app/homeserver.py", line 318, in setup
Oct  7 19:18:29 srv-ic-sec python3[1589]:     config = HomeServerConfig.load_or_generate_config(
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/config/_base.py", line 638, in load_or_generate_config
Oct  7 19:18:29 srv-ic-sec python3[1589]:     obj.parse_config_dict(
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/config/_base.py", line 657, in parse_config_dict
Oct  7 19:18:29 srv-ic-sec python3[1589]:     self.invoke_all(
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/config/_base.py", line 276, in invoke_all
Oct  7 19:18:29 srv-ic-sec python3[1589]:     res[name] = getattr(config, func_name)(*args, **kwargs)
Oct  7 19:18:29 srv-ic-sec python3[1589]:   File "/usr/lib/python3/dist-packages/synapse/config/server.py", line 436, in read_config
Oct  7 19:18:29 srv-ic-sec python3[1589]:     self.limit_remote_rooms = LimitRemoteRoomsConfig(
Oct  7 19:18:29 srv-ic-sec python3[1589]: TypeError: type object argument after ** must be a mapping, not NoneType
Oct  7 19:18:29 srv-ic-sec systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Oct  7 19:18:29 srv-ic-sec systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Oct  7 19:18:30 srv-ic-sec prosody[1198]: c2s55939449c570: Traceback[c2s]: /usr/lib/prosody/util/cache.lua:66: table index is nil#012stack traceback:#012#011/usr/lib/prosody/util/cache.lua:66: in function 'set'#012#011/usr/lib/prosody/modules/muc/mod_muc.lua:176: in function 'track_room'#012#011/usr/lib/prosody/modules/muc/mod_muc.lua:204: in function </usr/lib/prosody/modules/muc/mod_muc.lua:191>#012#011(...tail calls...)#012#011/usr/lib/prosody/modules/muc/mod_muc.lua:433: in function '?'#012#011/usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>#012#011(...tail calls...)#012#011/usr/lib/prosody/core/stanza_router.lua:180: in function 'core_post_stanza'#012#011/usr/lib/prosody/core/stanza_router.lua:127: in function 'core_process_stanza'#012#011/usr/lib/prosody/modules/mod_c2s.lua:275: in function 'func'#012#011/usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
```

### Version information

- **Version**: 1.11.0 according to `/usr/lib/python3/dist-packages/synapse/__init__.py`

- **Install method**: matrix.org Ubuntu packages

- **Platform**: Ubuntu 20.04.1

- **Postgres version**: 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1)
- Running in LXC container/Proxmox

**Comment by mwllgr** [comment]
Fixed by removing package sources, `apt remove`ing matrix and readding/reinstalling the server again.
