### ISSUE TITLE
Issue federating with matrix.org

### ISSUE THREAD

**Issue by evilham** [matrix-org/synapse#8581]
### Description

Hello, in some rooms shared with users from `@X:matrix.org`, they have noticed some missing bits of conversations, it looks as if `matrix.org` is refusing to federate with `unchat.cat`.
If, e.g. I try to start a a conversation with a user on the `matrix.org` server, the traceback below is produced.

Since this is happening *exclusively* with Matrix.org (federation tester is alright), I wonder whether whether this is something that has been done on purpose on the Ops side of that server?

```
2020-10-17 15:55:05,159 - synapse.http.matrixfederationclient - 581 - WARNING - POST-94 - {GET-O-9} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/query/profile?user_id=%40evilham%3Amatrix.org&field=displayname: HttpResponseException('401: Unauthorized')
2020-10-17 15:55:15,854 - synapse.http.matrixfederationclient - 581 - WARNING - POST-94 - {PUT-O-10} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21cRGCQMIrTOoRKuuRAd%3Aunchat.cat/%24pd2YvXy_Aq_AC6W04v1jbM3VRY6lHIDiZIvRjeTmbss: HttpResponseException('401: Unauthorized')
2020-10-17 15:55:15,871 - synapse.http.server - 85 - ERROR - POST-94 - Failed handle request via 'RoomCreateRestServlet': <XForwardedForRequest at 0x8090ad550 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 230, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/server.py", line 407, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.7/site-packages/synapse/rest/client/v1/room.py", line 98, in on_POST
    requester, self.get_room_config(request)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/room.py", line 779, in create_room
    content=content,
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/room_member.py", line 349, in update_membership
    require_consent=require_consent,
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/room_member.py", line 589, in _update_membership
    require_consent=require_consent,
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/room_member.py", line 246, in _local_membership_update
    requester, event, context, extra_users=[target], ratelimit=ratelimit,
  File "/usr/local/lib/python3.7/site-packages/synapse/util/metrics.py", line 88, in measured_func
    r = await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 923, in handle_new_client_event
    requester, event, context, ratelimit=ratelimit, extra_users=extra_users
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/message.py", line 1086, in persist_and_notify_client_event
    invitee.domain, event
  File "/usr/local/lib/python3.7/site-packages/synapse/handlers/federation.py", line 1312, in send_invite
    pdu=event,
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/federation_client.py", line 743, in send_invite
    content = await self._do_send_invite(destination, pdu, room_version)
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/federation_client.py", line 777, in _do_send_invite
    "invite_room_state": pdu.unsigned.get("invite_room_state", []),
  File "/usr/local/lib/python3.7/site-packages/synapse/federation/transport/client.py", line 311, in send_invite_v2
    destination=destination, path=path, data=content, ignore_backoff=True
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 706, in put_json
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 292, in _send_request_with_optional_trailing_slash
    response = await self._send_request(request, **send_request_args)
  File "/usr/local/lib/python3.7/site-packages/synapse/http/matrixfederationclient.py", line 536, in _send_request
    raise e
synapse.api.errors.HttpResponseException: 401: Unauthorized
```

### Version information

https://federationtester.matrix.org/api/report?server_name=unchat.cat

- **Install method**: FreeBSD ports

- **Platform**: FreeBSD jail on a physical host

**Comment by richvdh** [comment]
your domain has dnssec errors: https://dnsviz.net/d/unchat.cat/dnssec/

**Comment by evilham** [comment]
Mmm, that's likely an issue with the dnsviz.net tool not being updated for dnsflagday.net/2020/ and should not be used as a conclusive argument to "there is a DNSSEC issue with that domain":

- https://dnssec-analyzer.verisignlabs.com/unchat.cat
- https://www.zonemaster.net/result/d530cb253298b56c
- `dig +dnssec matrix.unchat.cat +short +multi @8.8.8.8` works just fine as well

This is not an issue with the domain.
Is it worth it to look into this more? Or should I start living with matrix.org not federating (other DNSSEC-enabled servers have no issues federating)?

**Comment by richvdh** [comment]
well, matrix.org is seeing dns failures of some sort. let me have a closer look.

**Comment by evilham** [comment]
Maybe running this against the resolver that is being used could spot an issue: https://dnsflagday.net/2020/#action-dns-resolver-operators

**Comment by richvdh** [comment]
I don't think it's related to that.

```
richardv@hippogriff:~$ dig +short test.knot-resolver.cz. TXT
"Davku ve me o pln uvitani stari s tvuj neda? Tik kufr u traslo uf tabuli znaky mesity bimbal vyrvat vydelal pobezi zahajil a tajnosti. By 77 dusic ach prazdna kasari k zac platne potiz. O hon 30 otazek jiz post i rad zeleninu vyhrknu bhutanu nezdalo. I tr" "ida, ptat lzes vypadla newton, utal hm je bas samymi u sobe ukaz kazne medove u placeny ke ah jo zpola o ocich. Sul trimesicni kontrolujte v predstirana po nej mit za devetadevadesati eh mi lezu slava vuz v me smery. Tri akt dlazbu dal lamu, kavkam on zas" "luhy, sad muzikant vek. Paty neme radili trunil docist tech obou zari. My ze 11 tlusti jsemvidel. Podivej i prs kralik at ted o vynahradit ti si ma charakterni nehybny tulak poskytl rad! Muz ztuhla, ci ah propatral misce! Slz eh at? Zenou dilo intuici. Le" "su pud povesti, i jamou tej. V az vdanou zrejmo za ctil 81 kolika u ustrnule malicherny holemi nekradla jinych morfia: pocasi poplaseny zpovidat az dne vyjimecna zidovskem stejny sluzek tajemny hlidat u ruzovym pry jestli vyslychalo zem nerozbrecte farare" " strhla v mem tabule pije a odkraglujem otisky nebot. Ex povidani pusta duse eh zvalel, o pak ma bryle luzka: u posluhovi neudela 30 ze ctverce brovninku. 411 se vi rypaje nova to per ba zchoulostivil remenem. Vaze to lujzou styky, te? Ne me by pazeni tro" "ubil i srovnala dejoveho a prvnich me o zime hlasy nevsimnou. Jejim zajiste za porotam valka sekt. Oni vuli co ryb pruvod. Ode jehoz od lasce ve slouzilo co jektal hryzal lamparny. Zvlastnich ne vybil brejlil uz ah? Husa trit mu straze s zivaje abys chute" " pane ci nepochybujte ubiha k babe ach okoli zle okna deji dverim! Vymyslim do falesne. Pokaceneho leti oka krk. Nohy stejny u vykaslu, rinkotem ondyno, laureat z zabije."
```

Nevertheless there does seem to be something a bit odd with our resolver. I'll ask our supplier if they have any ideas.

**Comment by richvdh** [comment]
@evilham our supplier points out that ns1.unchat.cat is responding with BADCOOKIE to UDP queries:

```
$ dig unchat.cat +nobadcookie  @ns1.unchat.cat

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> unchat.cat +nobadcookie @ns1.unchat.cat
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: BADCOOKIE, id: 36165
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

```

https://dnsflagday.net/2020 says that resolvers should retry over TCP in response to a truncated response, but does not require it for BADCOOKIE.

**Comment by evilham** [comment]
Thank you, will see if I can find something more specific, but AFAICT from [RFC7873](https://tools.ietf.org/html/rfc7873#section-5.3), the client (matrix.org's resolver) SHOULD retry the request using the new Server Cookie from the response. (aka: `+badcookie` behaviour).

**Comment by richvdh** [comment]
AIUI the resolver does retry, but again receives a BADCOOKIE response.

I see the RFC says "If the reply to a retried request with a fresh Server Cookie is BADCOOKIE, the client SHOULD retry using TCP as the transport" but honestly you're in a bit of a weird corner of DNS at this point. Is there a reason for this behaviour?

**Comment by richvdh** [comment]
closing this as it doesn't seem to be a synapse issue.

**Comment by evilham** [comment]
Yes, thank you. If anything it boils it down to potentially an issue with matrix.org's DNS provider, but also it could be something on my side, unclear ATM to me.

Oddly enough I did notice matrix.org federating today, unsure if it was for a short period of time; will totally have to investigate it some more.

**Comment by evilham** [comment]
For posterity in case this gets boosted unnecessarily by search engines, there was a slight non-obvious issue on the Authoritative DNS servers:
https://lists.nic.cz/pipermail/knot-dns-users/2020-October/001879.html

Thank you again for looking into it an providing useful feedback.

**Comment by richvdh** [comment]
interesting, thanks for reporting back, and glad it got resolved. I just learnt a whole bunch about DNS...

**Comment by kuon** [comment]
I have the same error with domain goyman.com (server at im.goyman.com). I tripled checked everything but I cannot find any issue.

**Comment by kuon** [comment]
Apparently it must be an issue on the matrix.org side, because I just re-tried and it works.
