### ISSUE TITLE
Failed to find any key to satisfy VerifyJsonRequest

### ISSUE THREAD

**Issue by plague-doctor** [matrix-org/synapse#8623]
### Description

Not sure when it started to happen... Some time ago everything was working fine...
Trying to explore rooms (invite a user, etc) on matrix.org from my homeserver throws 

```
Failed to find any key to satisfy VerifyJsonRequest(server=matrix.netsi.xyz, key_ids=['ed25519:a_DjGY'], min_valid=1603353281056)
```

logs:

```matrix_synapse    | 2020-10-22 18:54:15,732 - synapse.http.matrixfederationclient - 573 - WARNING - POST-6204 - {PUT-O-79} [matrix.org] Request failed: PUT matrix://matrix.org/_matrix/federation/v2/invite/%21GwyxQuGIQhPdVYyyRW%3Amatrix.netsi.xyz/%24uJgZjGYMDh0v5Z1iQ0VLXATE: HttpResponseException('401: Unauthorized')
matrix_synapse    | 2020-10-22 18:54:15,737 - synapse.http.server - 81 - ERROR - POST-6204 - Failed handle request via 'RoomCreateRestServlet': <XForwardedForRequest at 0x7fe49d143730 method='POST' uri='/_matrix/client/r0/createRoom' clientproto='HTTP/1.0' site=8008>
matrix_synapse    | Traceback (most recent call last):
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 230, in _async_render_wrapper
matrix_synapse    |     callback_return = await self._async_render(request)
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 407, in _async_render
matrix_synapse    |     callback_return = await raw_callback_return
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v1/room.py", line 97, in on_POST
matrix_synapse    |     info, _ = await self._room_creation_handler.create_room(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room.py", line 773, in create_room
matrix_synapse    |     _, last_stream_id = await self.room_member_handler.update_membership(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 313, in update_membership
matrix_synapse    |     result = await self._update_membership(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 554, in _update_membership
matrix_synapse    |     return await self._local_membership_update(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 224, in _local_membership_update
matrix_synapse    |     stream_id = await self.event_creation_handler.handle_new_client_event(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/util/metrics.py", line 92, in measured_func
matrix_synapse    |     r = await func(self, *args, **kwargs)
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/message.py", line 920, in handle_new_client_event
matrix_synapse    |     stream_id = await self.persist_and_notify_client_event(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/message.py", line 1086, in persist_and_notify_client_event
matrix_synapse    |     returned_invite = await federation_handler.send_invite(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/federation.py", line 1291, in send_invite
matrix_synapse    |     pdu = await self.federation_client.send_invite(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 745, in send_invite
matrix_synapse    |     content = await self._do_send_invite(destination, pdu, room_version)
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/federation/federation_client.py", line 772, in _do_send_invite
matrix_synapse    |     content = await self.transport_layer.send_invite_v2(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/federation/transport/client.py", line 310, in send_invite_v2
matrix_synapse    |     response = await self.client.put_json(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 702, in put_json
matrix_synapse    |     response = await self._send_request_with_optional_trailing_slash(
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 292, in _send_request_with_optional_trailing_slash
matrix_synapse    |     response = await self._send_request(request, **send_request_args)
matrix_synapse    |   File "/usr/local/lib/python3.8/site-packages/synapse/http/matrixfederationclient.py", line 534, in _send_request
matrix_synapse    |     raise e
matrix_synapse    | synapse.api.errors.HttpResponseException: 401: Unauthorized
matrix_synapse    | 2020-10-22 18:54:51,208 - synapse.http.matrixfederationclient - 573 - WARNING - POST-6240 - {GET-O-80} [matrix.org] Request failed: GET matrix://matrix.org/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=20: HttpResponseException('401: Unauthorized')
```
### Version information

- **Homeserver**: matrix.netsi.xyz 

 What version of Synapse is running?
```
{
    "python_version": "3.8.6",
    "server_version": "1.21.0"
}
```

**Comment by anoadragon453** [comment]
matrix.org is trying to query your server key to validate your request. It looks like matrix.org is unable to GET `https://synapse.netsi.xyz/_matrix.netsi.xyz/_matrix/key/v2/server/ed25519%3Aa_DjGY`:

```
2020-10-22 07:54:15,589 - synapse.http.federation.matrix_federation_agent - 261 - INFO - PUT-6130904- - Failed to connect to synapse.netsi.xyz:443: HostnameAddress(hostname=b'synapse.netsi.xyz', port=443)
2020-10-22 07:54:15,590 - synapse.http.matrixfederationclient - 544 - INFO - PUT-6130904- - {GET-O-10024} [matrix.netsi.xyz] Request failed: GET matrix://matrix.netsi.xyz/_matrix/key/v2/server/ed25519%3Aa_DjGY: ConnectingCancelledError(HostnameAddress(hostname=b'synapse.netsi.xyz', port=443))
2020-10-22 07:54:15,591 - synapse.crypto.keyring - 773 - WARNING - PUT-6130904 - Error looking up keys {'ed25519:a_DjGY': 1603353242159} from matrix.netsi.xyz: Failed to send request: ConnectingCancelledError: HostnameAddress(hostname=b'synapse.netsi.xyz', port=443)
2020-10-22 07:54:15,592 - synapse.federation.transport.server - 312 - WARNING - PUT-6130904 - authenticate_request failed: 401: Failed to find any key to satisfy VerifyJsonRequest(server=matrix.netsi.xyz, key_ids=['ed25519:a_DjGY'], min_valid=1603353242159)
```

I'm actually unable to contact your server from either matrix.org or my personal machine. 

```
~$ ping synapse.netsi.xyz
PING synapse.netsi.xyz (103.51.114.217) 56(84) bytes of data.
^C
--- synapse.netsi.xyz ping statistics ---
120 packets transmitted, 0 received, 100% packet loss, time 680ms

~$ 
```

I would double-check your homeserver's box is accessible from outside your network.

As this seems to be a network problem rather than a problem with Synapse, I'm going to close this issue. Do note you can get free-form support in [#synapse:matrix.org](https://matrix.to/#/#synapse:matrix.org) (though you may need to join via another homeserver, such as matrix.org).

Feel free to reopen this issue if you find something else :)
