### ISSUE TITLE
Test suite fails on Python 3.9

### ISSUE THREAD

**Issue by callahad** [matrix-org/synapse#8637]
I ran the test suite on the current `develop` branch with Python 3.9.

The following three assertions failed:

- https://github.com/matrix-org/synapse/blob/054a6b95389ebe34072998fa7b07f4b33c5a1cdb/tests/rest/media/v1/test_url_preview.py#L256
- https://github.com/matrix-org/synapse/blob/054a6b95389ebe34072998fa7b07f4b33c5a1cdb/tests/rest/media/v1/test_url_preview.py#L223
- https://github.com/matrix-org/synapse/blob/054a6b95389ebe34072998fa7b07f4b33c5a1cdb/tests/rest/media/v1/test_url_preview.py#L289

Test output:

```
[FAIL]
Traceback (most recent call last):
  File "/Users/dan/Projects/Element/synapse/tests/rest/media/v1/test_url_preview.py", line 256, in test_non_ascii_preview_content_type
    self.assertEqual(channel.code, 200)
  File "/Users/dan/Projects/Element/synapse/.venv/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 500 != 200

tests.rest.media.v1.test_url_preview.URLPreviewTests.test_non_ascii_preview_content_type
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/dan/Projects/Element/synapse/tests/rest/media/v1/test_url_preview.py", line 223, in test_non_ascii_preview_httpequiv
    self.assertEqual(channel.code, 200)
  File "/Users/dan/Projects/Element/synapse/.venv/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 500 != 200

tests.rest.media.v1.test_url_preview.URLPreviewTests.test_non_ascii_preview_httpequiv
===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/dan/Projects/Element/synapse/tests/rest/media/v1/test_url_preview.py", line 289, in test_overlong_title
    self.assertEqual(channel.code, 200)
  File "/Users/dan/Projects/Element/synapse/.venv/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 831, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/ns1s5kfa6i11fy4z82dhwxsy50wlkkqd-python3-3.9.0/lib/python3.9/unittest/case.py", line 824, in _baseAssertEqual
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: 500 != 200

tests.rest.media.v1.test_url_preview.URLPreviewTests.test_overlong_title
```

All tests pass using the same checkout with Python 3.8.

Will look into this later.

**Comment by callahad** [comment]
Running Trial with `--debug` shows each of those tests raising `unknown encoding: 'b'windows-1251'` from lxml:

```
tests.rest.media.v1.test_url_preview
  URLPreviewTests
    test_overlong_title ... Jumping into debugger for post-mortem of exception 'unknown encoding: 'b'windows-1251''':
> /Users/dan/Projects/Element/synapse/_trial_temp/src/lxml/parser.pxi(837)lxml.etree._BaseParser.__init__()
(Pdb) bt
  /Users/dan/Projects/Element/synapse/.venv/lib/python3.9/site-packages/twisted/internet/defer.py(1418)_inlineCallbacks()
-> result = g.send(result)
  /Users/dan/Projects/Element/synapse/synapse/rest/media/v1/preview_url_resource.py(308)_do_preview()
-> og = decode_and_calc_og(body, media_info["uri"], encoding)
  /Users/dan/Projects/Element/synapse/synapse/rest/media/v1/preview_url_resource.py(683)decode_and_calc_og()
-> parser = etree.HTMLParser(recover=True, encoding=request_encoding)
  /Users/dan/Projects/Element/synapse/_trial_temp/src/lxml/parser.pxi(1709)lxml.etree.HTMLParser.__init__()
> /Users/dan/Projects/Element/synapse/_trial_temp/src/lxml/parser.pxi(837)lxml.etree._BaseParser.__init__()
```

**Comment by callahad** [comment]
Maybe something's weird with my Python 3.9 or lxml?

```
>>> from lxml import etree
>>> etree.HTMLParser(encoding="utf-8")
<lxml.etree.HTMLParser object at 0x1093df040>
>>> etree.HTMLParser(encoding="windows-1251")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/lxml/parser.pxi", line 1709, in lxml.etree.HTMLParser.__init__
  File "src/lxml/parser.pxi", line 837, in lxml.etree._BaseParser.__init__
LookupError: unknown encoding: 'b'windows-1251''
>>> "hello world".encode("windows-1251")
b'hello world'
```

**Comment by callahad** [comment]
Closing as invalid. I blame my weirdo package manager (Nix).

Root cause: lxml 4.6.1 does not publish wheels for Python 3.9 on macOS, so I have to build my own there.

When doing so, libxml2 doesn't find iconv, so most encodings are unavailable.

**Comment by callahad** [comment]
In case anyone needs this (they won't, this is more for my future self), my `shell.nix` for working on Synapse looks a bit like this:

```nix
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "synapseDevEnv";
  src = null;
  buildInputs = [
    python39Full

    # for psycopg2:
    postgresql openssl

    # for lxml:
    (libxml2.overrideAttrs (oldAttrs: rec {
      propagatedBuildInputs = oldAttrs.propagatedBuildInputs ++ [ libiconv ];
    }))
    libxslt
  ];

  shellHook = ''
    SOURCE_DATE_EPOCH=$(date +%s)  # Necessary for using Python wheels
    export DYLD_LIBRARY_PATH=${pkgs.file}/lib
    export PIP_DISABLE_PIP_VERSION_CHECK=1

    python3 -m venv ./.venv
    source ./.venv/bin/activate
    pip install wheel
  '';
}
```
