### ISSUE TITLE
Trying to run synapse out of deb fails

### ISSUE THREAD

**Issue by yuvipanda** [matrix-org/synapse#864]
On a debian jessie setup, using the latest deb (0.16-1):

```
root@matrix-01:~# synctl start
Starting ...
2016-06-10 02:37:12,917 - synapse.python_dependencies - 107 - INFO - - Using 'bcrypt' version None from '/usr/lib/python2.7/dist-packages/bcrypt/__init__.pyc' to satisfy 'py-bcrypt'
2016-06-10 02:37:12,917 - synapse.python_dependencies - 107 - INFO - - Using 'frozendict' version None from '/usr/lib/python2.7/dist-packages/frozendict/__init__.pyc' to satisfy 'frozendict>=0.4'
2016-06-10 02:37:12,917 - synapse.python_dependencies - 107 - INFO - - Using 'OpenSSL' version '0.15.1' from '/usr/lib/python2.7/dist-packages/OpenSSL/__init__.pyc' to satisfy 'pyopenssl>=0.14'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'pydenticon' version None from '/usr/lib/python2.7/dist-packages/pydenticon/__init__.pyc' to satisfy 'pydenticon'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'pymacaroons' version '0.9.0' from '/usr/lib/python2.7/dist-packages/pymacaroons/__init__.pyc' to satisfy 'pymacaroons-pynacl'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'service_identity' version '1.0.0' from '/usr/lib/python2.7/dist-packages/service_identity/__init__.pyc' to satisfy 'service_identity>=1.0.0'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'signedjson' version '1.0.0' from '/usr/lib/python2.7/dist-packages/signedjson/__init__.pyc' to satisfy 'signedjson>=1.0.0'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'blist' version '1.3.6' from '/usr/lib/python2.7/dist-packages/blist/__init__.pyc' to satisfy 'blist'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'yaml' version '3.11' from '/usr/lib/python2.7/dist-packages/yaml/__init__.pyc' to satisfy 'pyyaml'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'unpaddedbase64' version '1.1.0' from '/usr/lib/python2.7/dist-packages/unpaddedbase64.pyc' to satisfy 'unpaddedbase64>=1.1.0'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'ujson' version '1.33' from '/usr/lib/python2.7/dist-packages/ujson.x86_64-linux-gnu.so' to satisfy 'ujson'
2016-06-10 02:37:12,918 - synapse.python_dependencies - 107 - INFO - - Using 'nacl' version '0.3.0' from '/usr/lib/python2.7/dist-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'nacl.bindings' version '0.3.0' from '/usr/lib/python2.7/dist-packages/nacl/__init__.pyc' to satisfy 'pynacl==0.3.0'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'daemonize' version None from '/usr/lib/python2.7/dist-packages/daemonize.pyc' to satisfy 'daemonize'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'canonicaljson' version '1.0.0' from '/usr/lib/python2.7/dist-packages/canonicaljson.pyc' to satisfy 'canonicaljson>=1.0.0'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'twisted' version '15.2.1' from '/usr/lib/python2.7/dist-packages/twisted/__init__.pyc' to satisfy 'Twisted>=15.1.0'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'saml2' version None from '/usr/lib/python2.7/dist-packages/saml2/__init__.pyc' to satisfy 'pysaml2>=3.0.0,<4.0.0'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'pyasn1' version '0.1.7' from '/usr/lib/python2.7/dist-packages/pyasn1/__init__.pyc' to satisfy 'pyasn1'
2016-06-10 02:37:12,919 - synapse.python_dependencies - 107 - INFO - - Using 'PIL' version None from '/usr/lib/python2.7/dist-packages/PIL/__init__.pyc' to satisfy 'pillow'
2016-06-10 02:37:12,944 - synapse.app.homeserver - 290 - INFO - - Server hostname: wikimedia.matrix.wmflabs.org
2016-06-10 02:37:12,945 - synapse.app.homeserver - 291 - INFO - - Server version: Synapse/0.16.0
2016-06-10 02:37:12,948 - synapse.app.homeserver - 310 - INFO - - Preparing database: sqlite3...
2016-06-10 02:37:12,950 - synapse.storage.prepare_database - 212 - INFO - - Upgrading schema to v32
2016-06-10 02:37:12,951 - synapse.app.homeserver - 328 - INFO - - Database prepared in sqlite3.
2016-06-10 02:37:12,951 - synapse.server - 135 - INFO - - Setting up.
2016-06-10 02:37:12,955 - synapse.storage.event_push_actions - 273 - INFO - - Searching for stream ordering 1 month ago
2016-06-10 02:37:12,956 - synapse.storage.event_push_actions - 279 - INFO - - Found stream ordering 1 month ago: it's 1
2016-06-10 02:37:12,958 - synapse.server - 137 - INFO - - Finished setting up.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 460, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 455, in main
    hs = setup(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 331, in setup
    hs.start_listening()
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 205, in start_listening
    self._listener_http(config, listener)
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 161, in _listener_http
    resources[WEB_CLIENT_PREFIX] = build_resource_for_web_client(self)
  File "/usr/lib/python2.7/dist-packages/synapse/app/homeserver.py", line 92, in build_resource_for_web_client
    % {"dep": DEPENDENCY_LINKS["matrix-angular-sdk"]}
KeyError: 'matrix-angular-sdk'
error starting (exit code: 1); see above for logs
root@matrix-01:~# 
```

This was the issue with running it off the default systemd unit as well. Started happening after I set 'web_client: True'

**Comment by erikjohnston** [comment]
This should have displayed a better error message, but looks like it was broken in `0.16.0-1`. As of `0.16.0-2` it should inform you to install the `matrix-synapse-angular-client` package.
