### ISSUE TITLE
creating a federation_sender worker does not seem to work.

### ISSUE THREAD

**Issue by dkowis** [matrix-org/synapse#8745]
### Description

I tried to set up a federation_sender worker, and was met with no federation functionality, and errors in the federation sender log:

One example is this:
```
2020-11-11 13:57:40,147 - synapse.http.matrixfederationclient - 196 - INFO - federation_transaction_transmission_loop-4- {PUT-O-2} [jabber.dk] Completed request: 200 OK in 1.05 secs - PUT matrix://jabber.dk/_matrix/federation/v1/send/1605124656317
2020-11-11 13:57:40,147 - synapse.federation.sender.transaction_manager - 163 - INFO - federation_transaction_transmission_loop-4- TX [jabber.dk] {1605124656317} got 200 response
2020-11-11 13:57:40,548 - synapse.app.generic_worker - 879 - ERROR - _save_and_send_ack-3- Error updating federation stream position
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/generic_worker.py", line 871, in _save_and_send_ack
    await self.store.update_federation_out_pos(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/stream.py", line 962, in update_federation_out_pos
    await self.db_pool.simple_update_one(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1612, in simple_update_one
    await self.runInteraction(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 627, in runInteraction
    result = await self.runWithConnection(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in runWithConnection
    return await make_deferred_yieldable(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 702, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 505, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1632, in simple_update_one_txn
    raise StoreError(404, "No row found (%s)" % (table,))
synapse.api.errors.StoreError: 404: No row found (federation_stream_position)
```

### Steps to reproduce

- Create a federation_sender worker, as described in the documentation and enable it.
- watch the federation_sender worker log, and see that it errors
- also note that you cannot send federation events in a matrix client.
    - interacting with users on my homeserver worked fine, but not with anything on any other homeserver.

### Version information

- **Homeserver**: synapse.light.kow.is

If not matrix.org: 

Package: matrix-synapse-py3
Version: 1.22.1+focal1

- **Platform**: It's running in a VM on Ubuntu 20.04

**Comment by dkowis** [comment]
I get this error message at start of the worker:

```
2020-11-11 14:36:07,119 - synapse.app.generic_worker - 879 - ERROR - _save_and_send_ack-0- Error updating federation stream position
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/generic_worker.py", line 871, in _save_and_send_ack
    await self.store.update_federation_out_pos(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/stream.py", line 962, in update_federation_out_pos
    await self.db_pool.simple_update_one(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1612, in simple_update_one
    await self.runInteraction(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 627, in runInteraction
    result = await self.runWithConnection(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in runWithConnection
    return await make_deferred_yieldable(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 702, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 505, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1632, in simple_update_one_txn
    raise StoreError(404, "No row found (%s)" % (table,))
synapse.api.errors.StoreError: 404: No row found (federation_stream_position)
2020-11-11 14:36:07,131 - synapse.app.generic_worker - 879 - ERROR - _save_and_send_ack-1- Error updating federation stream position
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/generic_worker.py", line 871, in _save_and_send_ack
    await self.store.update_federation_out_pos(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/stream.py", line 962, in update_federation_out_pos
    await self.db_pool.simple_update_one(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1612, in simple_update_one
    await self.runInteraction(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 627, in runInteraction
    result = await self.runWithConnection(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in runWithConnection
    return await make_deferred_yieldable(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 702, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 505, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1632, in simple_update_one_txn
    raise StoreError(404, "No row found (%s)" % (table,))
synapse.api.errors.StoreError: 404: No row found (federation_stream_position)
```

**Comment by dkowis** [comment]
Here's one event to matrix.org that I caught from the logs:

```
2020-11-11 14:37:03,373 - synapse.http.matrixfederationclient - 196 - INFO - federation_transaction_transmission_loop-2904- {PUT-O-1616} [matrix.org] Completed request: 200 OK in 0.25 secs - PUT matrix://matrix.org/_matrix/federation/v1/send/1605126968557
2020-11-11 14:37:03,374 - synapse.federation.sender.transaction_manager - 163 - INFO - federation_transaction_transmission_loop-2904- TX [matrix.org] {1605126968557} got 200 response
2020-11-11 14:37:03,388 - synapse.metrics.background_process_metrics - 210 - ERROR - process_event_queue_for_federation-6- Background process 'process_event_queue_for_federation' threw an exception
Traceback (most recent call last):
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 206, in run
    result = await result
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/federation/sender/__init__.py", line 180, in _process_event_queue_loop
    last_token = await self.store.get_federation_out_pos("events")
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/databases/main/stream.py", line 948, in get_federation_out_pos
    return await self.db_pool.simple_select_one_onecol(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1311, in simple_select_one_onecol
    return await self.runInteraction(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 627, in runInteraction
    result = await self.runWithConnection(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in runWithConnection
    return await make_deferred_yieldable(
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 702, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 505, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1364, in simple_select_one_onecol_txn
    raise StoreError(404, "No row found")
synapse.api.errors.StoreError: 404: No row found
```

**Comment by erikjohnston** [comment]
Huh. What does your config look like? Particularly the `send_federation`, `federation_sender_instances` and `worker_name` options in the various configs?

**Comment by erikjohnston** [comment]
Aha, was just pointed at your messages in one of the support channels. The config was:

homeserver.yaml:
```yaml
# Enable the HTTP replication port
  - port: 9093
    bind_address: '127.0.0.1'
    type: http
    resources:
      - names: [replication]

#Enable the use of redis
redis:
  enabled: true
```

worker.yaml:
```yaml
worker_app: synapse.app.federation_sender
worker_name: federation_sender1

# The replication listener on the main synapse process.
worker_replication_host: 127.0.0.1
worker_replication_http_port: 9093

worker_log_config: /etc/matrix-synapse/workers/federation_sender1_log.yaml
```

Which doesn't mention `send_federation`? Though I believe if you try and start up a federation sender without setting send_federation` it should bail, so I'm guessing you did set that correctly.

During start up we fiddle the `federation_stream_position` to ensure that the federation sender instances have entries in it. What seems to be happening here is that the federation sender is trying to send federation, but somehow doesn't have entries in that table. We recently changed the logic here to support sharding federation senders, so I can imagine there is a subtle bug here.

The code in question is:

https://github.com/matrix-org/synapse/blob/c059413001cd2ff7c6104cfcd323ed115245ae90/synapse/storage/databases/main/stream.py#L941-L1028

**Comment by dkowis** [comment]
This bit of config? Yeah, I had that set up to make sure that it would use the worker to do the sending. It was in a different part of the config file.

```yaml
send_federation: false
federation_sender_instances:
  - federation_sender_worker1
```

My table entries for that table:
```
type,stream_id,instance_name
federation,-1,master
events,2069733,master
```
If I understand you correctly, that means there's not a row added, that should've been added for each worker?

**Comment by erikjohnston** [comment]
Aha, yeah, looks to be because `federation_sender_worker1` isn't what you've named your worker, `federation_sender1`. We should probably fail if `federation_sender_instances` is set and you try and start a `synapse.app.federation_sender` worker whose name doesn't appear in that list

**Comment by dkowis** [comment]
Ohhhh, man lemme double check my config and make sure I didn't paste the wrong thing.

...

Yep. that's totally it! Those names differ!

**Comment by erikjohnston** [comment]
It's such an easy thing to do! Annoyingly it's hard to validate that sort of stuff on startup, as the master doesn't know what workers are actually configured
