### ISSUE TITLE
breaking change for SAML providers in 1.23

### ISSUE THREAD

**Issue by artooro** [matrix-org/synapse#8778]
There is nothing noted in the 1.23 release notes regarding a change in the SAML system, but our custom module is now causing a fatal error forcing us to revert back to 1.22.1 for the time being.

The traceback when synapse 1.23 starts is.

```
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]: Traceback (most recent call last):
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     "__main__", mod_spec)
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     exec(code, run_globals)
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 512, in <module>
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     main()
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 507, in main
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     hs = setup(sys.argv[1:])
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/app/homeserver.py", line 342, in setup
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     "Synapse Homeserver", config_options
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/config/_base.py", line 722, in load_or_generate_config
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     config_dict, config_dir_path=config_dir_path, data_dir_path=data_dir_path
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/config/_base.py", line 744, in parse_config_dict
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     data_dir_path=data_dir_path,
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/config/_base.py", line 369, in invoke_all
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     res[name] = getattr(config, func_name)(*args, **kwargs)
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/synapse/config/saml2_config.py", line 165, in read_config
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     self.saml2_sp_config.load(saml2_config_dict)
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/saml2/config.py", line 333, in load
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     self.load_complex(cnf)
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:   File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/saml2/config.py", line 272, in load_complex
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]:     policy_conf = spec.get("policy")
Nov 18 18:15:55 matrix-s01 matrix-synapse[3078]: AttributeError: 'str' object has no attribute 'get'
Nov 18 18:15:55 matrix-s01 systemd[1]: matrix-synapse.service: Main process exited, code=killed, status=15/TERM
```

In /etc/matrix-synapse/homeserver.yaml I have the following SAML config

```yaml
saml2_config:
  sp_config:
   allow_unknown_attributes: true
   metadata:
      local: ["/etc/matrix-synapse/saml2/idp.xml"]
   service:
      name_form: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      sp:
        allow_unsolicited: true
  user_mapping_provider:
    #module: mapping_provider.SamlMappingProvider
    module: googlesamlhandler.googlemapping.GoogleSamlMappingProvider
    config:
      mxid_mapping: email2user
```

At the path `/opt/venvs/matrix-synapse/lib/python3.7/site-packages/googlesamlhandler/googlemapping.py` I have the following python module that I wrote based on the stock module.

```py
import logging
import saml2
import saml2.response
import attr
import re
from typing import Tuple
from synapse.module_api import ModuleApi
from synapse.api.errors import SynapseError
from synapse.config import ConfigError

logger = logging.getLogger(__name__)

def map_email_to_mxid_localpart(username: str) -> str:
    username = username.lower()
    username = username.split("@")[0]

    # regular mxids aren't allowed to start with an underscore either
    username = re.sub("^_", "", username)
    return username

MXID_MAPPER_MAP = {
    "email2user": map_email_to_mxid_localpart,
}

@attr.s
class SamlConfig(object):
    mxid_source_attribute = attr.ib()
    mxid_mapper = attr.ib()

class GoogleSamlMappingProvider(object):
    __version__ = "0.0.1"

    def __init__(self, parsed_config: SamlConfig, module_api: ModuleApi):
        """The Google SAML user mapping provider
        Args:
            parsed_config: Module configuration
            module_api: module api proxy
        """
        self._mxid_source_attribute = parsed_config.mxid_source_attribute
        self._mxid_mapper = parsed_config.mxid_mapper

        self._grandfathered_mxid_source_attribute = (
            module_api._hs.config.saml2_grandfathered_mxid_source_attribute
        )

    def get_remote_user_id(
        self, saml_response: saml2.response.AuthnResponse, client_redirect_url: str
    ):
        """Extracts the remote user id from the SAML response"""
        try:
            return saml_response.ava["uid"][0]
        except KeyError:
            logger.warning("SAML2 response lacks a 'uid' attestation")
            raise SynapseError(400, "'uid' not in SAML2 response")

    def saml_response_to_user_attributes(
        self,
        saml_response: saml2.response.AuthnResponse,
        failures: int,
        client_redirect_url: str,
    ) -> dict:
        """Maps some text from a SAML response to attributes of a new user
        Args:
            saml_response: A SAML auth response object
            failures: How many times a call to this function with this
                saml_response has resulted in a failure
            client_redirect_url: where the client wants to redirect to
        Returns:
            dict: A dict containing new user attributes. Possible keys:
                * mxid_localpart (str): Required. The localpart of the user's mxid
                * displayname (str): The displayname of the user
        """
        try:
            mxid_source = saml_response.ava[self._mxid_source_attribute][0]
        except KeyError:
            logger.warning(
                "SAML2 response lacks a '%s' attestation", self._mxid_source_attribute,
            )
            raise SynapseError(
                400, "%s not in SAML2 response" % (self._mxid_source_attribute,)
            )

        # Use the configured mapper for this mxid_source
        base_mxid_localpart = self._mxid_mapper(mxid_source)

        # Append suffix integer if last call to this function failed to produce
        # a usable mxid
        localpart = base_mxid_localpart + (str(failures) if failures else "")

        # Retrieve the display name from the saml response
        # If displayname is None, the mxid_localpart will be used instead
        displayname = saml_response.ava.get("displayName", [None])[0]

        return {
            "mxid_localpart": localpart,
            "displayname": displayname,
        }

    @staticmethod
    def parse_config(config: dict) -> SamlConfig:
        """Parse the dict provided by the homeserver's config
        Args:
            config: A dictionary containing configuration options for this provider
        Returns:
            SamlConfig: A custom config object for this module
        """
        # Parse config options and use defaults where necessary
        mxid_source_attribute = config.get("mxid_source_attribute", "uid")
        mapping_type = config.get("mxid_mapping", "email2user")

        # Retrieve the associating mapping function
        try:
            mxid_mapper = MXID_MAPPER_MAP[mapping_type]
        except KeyError:
            raise ConfigError(
                "saml2_config.user_mapping_provider.config: '%s' is not a valid "
                "mxid_mapping value" % (mapping_type,)
            )

        return SamlConfig(mxid_source_attribute, mxid_mapper)

    @staticmethod
    def get_saml_attributes(config: SamlConfig) -> Tuple[set, set]:
        """Returns the required attributes of a SAML
        Args:
            config: A SamlConfig object containing configuration params for this provider
        Returns:
            tuple[set,set]: The first set equates to the saml auth response
                attributes that are required for the module to function, whereas the
                second set consists of those attributes which can be used if
                available, but are not necessary
        """
        return {"uid", config.mxid_source_attribute}, {"displayName"}
```

In case you're wondering, the reason for the custom module is it's the only way I could have the username provided by Google Workspace SAML which is a full email address to be mapped to just the portion before the @ symbol to be used as the matrix username.

This was working up until 1.22.1 and from the documentation I could find this is the most official method of accomplishing our needs, I'm not sure it should break like this at least without there being a release note about a change that could break users custom modules.

I'm sure I could update the module to be compatible, but I imagine this will also break for other users using a custom mapper, so not sure if me modifying it is the correct approach?

**Comment by gtbuchanan** [comment]
Similar issue here with 1.23 and SAML except I don't use a custom module:

```
2020-11-18T19:23:49.555981849Z Traceback (most recent call last):
2020-11-18T19:23:49.556044907Z   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2020-11-18T19:23:49.556069757Z     return _run_code(code, main_globals, None,
2020-11-18T19:23:49.556088783Z   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2020-11-18T19:23:49.556107377Z     exec(code, run_globals)
2020-11-18T19:23:49.556125376Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 512, in <module>
2020-11-18T19:23:49.556144354Z     main()
2020-11-18T19:23:49.556163096Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 507, in main
2020-11-18T19:23:49.556181776Z     hs = setup(sys.argv[1:])
2020-11-18T19:23:49.556199902Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 341, in setup
2020-11-18T19:23:49.556218634Z     config = HomeServerConfig.load_or_generate_config(
2020-11-18T19:23:49.556237507Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 721, in load_or_generate_config
2020-11-18T19:23:49.556256343Z     obj.parse_config_dict(
2020-11-18T19:23:49.556274721Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 740, in parse_config_dict
2020-11-18T19:23:49.556293342Z     self.invoke_all(
2020-11-18T19:23:49.556311235Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 369, in invoke_all
2020-11-18T19:23:49.556330272Z     res[name] = getattr(config, func_name)(*args, **kwargs)
2020-11-18T19:23:49.556348609Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/saml2_config.py", line 165, in read_config
2020-11-18T19:23:49.556367192Z     self.saml2_sp_config.load(saml2_config_dict)
2020-11-18T19:23:49.556385239Z   File "/usr/local/lib/python3.8/site-packages/saml2/config.py", line 333, in load
2020-11-18T19:23:49.556403256Z     self.load_complex(cnf)
2020-11-18T19:23:49.556421081Z   File "/usr/local/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
2020-11-18T19:23:49.556439178Z     policy_conf = spec.get("policy")
2020-11-18T19:23:49.556474849Z AttributeError: 'list' object has no attribute 'get'
```

I compared my config with the sample config but I don't see any differences that would indicate my config is malformed. Reverting back to 1.22.1 fixes the problem for me too.

**Comment by localguru** [comment]
I was about to upgrade when I read this. @gtbuchanan Taylor, did you keep your old homeserver.yaml and didn't change anything in your configs?

**Comment by clokep** [comment]
How are you all deploying? apt / pip / Docker? I'm wondering if pysaml2 got upgraded...

**Comment by gtbuchanan** [comment]
@localguru Yes, I tried first with my existing config. After I realized Synapse was failing to start, I then merged in changes from the sample config just to see if it would help. I didn't see any config changes related to SAML that might have caused this, though.

@clokep I'm using Docker.

**Comment by gtbuchanan** [comment]
To add some additional information, I mount some 3rd party modules as volumes like this:
```
# Shared Secret Authenticator: https://github.com/devture/matrix-synapse-shared-secret-auth
- ${DOCKER_STORAGE}/synapse-modules/shared_secret_authenticator.py:/usr/local/lib/python3.7/site-packages/shared_secret_authenticator.py:ro

# ma1sd: https://github.com/ma1uta/ma1sd/blob/master/docs/features/authentication.md
- ${DOCKER_STORAGE}/synapse-modules/rest_auth_provider.py:/usr/local/lib/python3.7/site-packages/rest_auth_provider.py:ro
```
I tried changing the paths to python3.8 but it didn't seem to make a difference. Same error as I previously posted.

**Comment by clokep** [comment]
Also see devture/matrix-synapse-shared-secret-auth#7.

**Comment by artooro** [comment]
I see @clokep that issue was a result of the path moving to python3.8 from python3.7  
Whether that's also the problem here as well I can't say as I've reverted, but will try again tonight in case somebody beats me to it.

**Comment by gtbuchanan** [comment]
I've discovered that commenting out all of the following nodes under `saml2_config.sp_config.service` configuration allows me to run Synapse v1.23 without the error so I'm guessing there is something related to pysaml2 as @clokep mentioned:

```yaml
description: ["Buchanan Chat Matrix Server", "en"]
name: ["Buchanan Chat", "en"]

contact_person:
  - given_name: George
    sur_name: Buchanan
    email_address": ["snipped"]
    contact_type": technical
```

If I uncomment `description`, `name`, or `contact_person` individually, I start getting the error again. The OP doesn't have these nodes specifically but I'm guessing it's the same underlying problem.

**Comment by localguru** [comment]
@gtbuchanan which pysaml2 version is installed?

**Comment by gtbuchanan** [comment]
@localguru Running `pip freeze | grep pysaml2` in the container indicates 6.3.1

**Comment by localguru** [comment]
Is this only problem, if using docker or does it effect debian/ubuntu packages too?

**Comment by artooro** [comment]
@localguru my case was using debian packages, not using docker for synapse here.

**Comment by callahad** [comment]
@artooro's traceback ended:

```
  File "/opt/venvs/matrix-synapse/lib/python3.7/site-packages/saml2/config.py", line 272, in load_complex
    policy_conf = spec.get("policy")
AttributeError: 'str' object has no attribute 'get'
```

@gtbuchanan's traceback ended:

```
  File "/usr/local/lib/python3.8/site-packages/saml2/config.py", line 272, in load_complex
    policy_conf = spec.get("policy")
AttributeError: 'list' object has no attribute 'get'
```

So something is going weird with the structure that pysaml2 is trying to work with. For one, `spec` is a string, for the other, it's a list. And in both cases, it looks like it should be a dict-like object. The lines in question are at https://github.com/IdentityPython/pysaml2/blob/v6.3.1/src/saml2/config.py#L271-L273

Now to work back through the traceback and see what we're passing that causes it to go off the rails...

**Comment by richvdh** [comment]
it's looking at the contents of the `service` setting. In particular:

```
   service:
      name_form: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
```

`name_form` is not valid here afaik. pysaml2 6.3.1 attempts to parse it, where it was ignored before.

What is the reason for setting it?

**Comment by richvdh** [comment]
likewise, `description`, `name` and `contact_person` are not valid things to put under `service`. The only valid entries are `idp`, `sp`, and `aa` - of which `sp` is likely the only useful one for Synapse.

Possibly attempting to populate them is a misreading of the sample config file.

**Comment by gtbuchanan** [comment]
@richvdh That was it. Thank you! I must have goofed that a while ago [when the service node had double-comments](https://github.com/matrix-org/synapse/commit/8f1aefa694bb860dd1485ec95054c699b1667e96#diff-48ee4f3967bc96bc276a51fc2e69ea6a2ddbf2dbdbef59752f94f1e33e736e50L1547).

**Comment by clokep** [comment]
I think @richvdh's answer here solves this for all the reporters. I'm going to closes this, but please give a shout if there's still an issue.

**Comment by artooro** [comment]
Thanks @clokep I was able to upgrade by removing `name_form`. I'm not sure why I had that in the config but probably from when I was trying to figure how how to map the user part of an email address to the MXID.

Thanks guys, hopefully other people with this problem will see this issue.

**Comment by Legogris** [comment]
> I think @richvdh's answer here solves this for all the reporters. I'm going to closes this, but please give a shout if there's still an issue.

It seems these are two different issues; one specific for SAML providers (addressed by @richvdh). Then, separately, there's https://github.com/devture/matrix-synapse-shared-secret-auth/issues/7.

Using provided dockerfiles and the following config subset has been working fine until 1.23/1.24:
```
password_providers:
  - module: "shared_secret_authenticator.SharedSecretAuthenticator"
    config:
        [...]
```

Now it yields `ModuleNotFoundError: No module named 'shared_secret_authenticator'`. So it seems the dockerfiles have broken in that they don't provide this lib in the right path anymore.
