### ISSUE TITLE
Background update fails with: UniqueViolation `e2e_cross_signing_keys_stream_idx`

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/synapse#8781]
The background update to add a unique index to `e2e_cross_signing_keys.stream_id` (introduced in #8694) fails on some servers due to duplicated stream IDs.

This shouldn't be causing any issues as its just a background job that is failing, and I don't think we don't rely on uniqueness, but it's not ideal. (The reason for adding the index was to speed up start time)

It's not immediately clear to me how that has happened, since we should only be inserting one row per stream ID:

https://github.com/matrix-org/synapse/blob/1eb9de90c0dbb99a28304a295a0f6ebb0b8d1c6c/synapse/storage/databases/main/end_to_end_keys.py#L955-L963

Stack trace:

```
UniqueViolation: could not create unique index "e2e_cross_signing_keys_stream_idx"
DETAIL:  Key (stream_id)=(388318) is duplicated.

  File "synapse/storage/background_updates.py", line 107, in run_background_updates
    result = await self.do_next_background_update(
  File "synapse/storage/background_updates.py", line 219, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "synapse/storage/background_updates.py", line 255, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "synapse/storage/background_updates.py", line 411, in updater
    await self.db_pool.runWithConnection(runner)
  File "synapse/storage/database.py", line 712, in runWithConnection
    return await make_deferred_yieldable(
  File "twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "synapse/storage/database.py", line 707, in inner_func
    return func(db_conn, *args, **kwargs)
  File "synapse/storage/background_updates.py", line 372, in create_index_psql
    c.execute(sql)
  File "synapse/storage/database.py", line 271, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "synapse/storage/database.py", line 297, in _do_execute
    return func(sql, *args)
```

(c.f. https://sentry.matrix.org/sentry/synapse-modular/issues/192410/ )

**Comment by richvdh** [comment]
we've had problems in the past which turned out to be due to running two masters at once, which I guess could cause this sort of duplication?

**Comment by jaywink** [comment]
Both concerned hosts are of the legacy stack, so yes that is possible.

**Comment by richvdh** [comment]
... in which case it might be unlikely enough that the right fix is just to manually drop the duplicate rows?

**Comment by erikjohnston** [comment]
Looks to be safe to drop the rows with duplicate stream IDs **if** they're for remote users (as the server will refetch the missing keys). I think deleting rows with local users will actually be a user visible change, in that those users will no longer have cross signing keys.

**Comment by erikjohnston** [comment]
Given this seems like something that likely only effects EMS (and a small number of hosts there as well) I'm going to close this.

If anyone else sees this then please shout!

**Comment by n1trux** [comment]
*shouts*

```
synapse_1   | 2020-12-15 11:45:28,776 - synapse.storage.background_updates - 111 - ERROR - background_updates-0- Error doing update
synapse_1   | Traceback (most recent call last):
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 107, in run_background_updates
synapse_1   |     result = await self.do_next_background_update(
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 219, in do_next_background_update
synapse_1   |     await self._do_background_update(desired_duration_ms)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 255, in _do_background_update
synapse_1   |     items_updated = await update_handler(progress, batch_size)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 411, in updater
synapse_1   |     await self.db_pool.runWithConnection(runner)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 712, in runWithConnection
synapse_1   |     return await make_deferred_yieldable(
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
synapse_1   |     result = inContext.theWork()
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
synapse_1   |     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
synapse_1   |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
synapse_1   |     return func(*args,**kw)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
synapse_1   |     compat.reraise(excValue, excTraceback)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
synapse_1   |     raise exception.with_traceback(traceback)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
synapse_1   |     result = func(conn, *args, **kw)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in inner_func
synapse_1   |     return func(db_conn, *args, **kwargs)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 372, in create_index_psql
synapse_1   |     c.execute(sql)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 271, in execute
synapse_1   |     self._do_execute(self.txn.execute, sql, *args)
synapse_1   |   File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 297, in _do_execute
synapse_1   |     return func(sql, *args)
synapse_1   | psycopg2.errors.UniqueViolation: could not create unique index "e2e_cross_signing_keys_stream_idx"
synapse_1   | DETAIL:  Key (stream_id)=(435) is duplicated.
```

Nearly exact same error – only that I have so many errors that I have to grep for all of them to see if the `stream_id`s are on other servers. Just wanted to chime in to tell you this is not only appearing on hosts of Element Matrix Services (EMS).
