### ISSUE TITLE
membership transitions are incorrectly ratelimited

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse#8791]
`_local_membership_update` seems to ratelimit join requests, even when ratelimit is set to `False`. In particular this means that room creation can fail halfway through, and seems to affect server-notices rooms particularly.

**Comment by richvdh** [comment]
```
2020-11-21 07:27:56,407 - synapse.metrics.background_process_metrics - 216 - ERROR - replication-USER_IP-120- Background process 'replication-USER_IP' threw an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 212, in run
    result = await result
  File "/usr/local/lib/python3.8/site-packages/synapse/replication/tcp/handler.py", line 392, in _handle_user_ip
    await self._server_notices_sender.on_user_ip(cmd.user_id)
  File "/usr/local/lib/python3.8/site-packages/synapse/server_notices/server_notices_sender.py", line 58, in on_user_ip
    await sn.maybe_send_server_notice_to_user(user_id)
  File "/usr/local/lib/python3.8/site-packages/synapse/server_notices/resource_limits_server_notices.py", line 75, in maybe_send_server_notice_to_user
    room_id = await self._server_notices_manager.get_or_create_notice_room_for_user(
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.8/site-packages/synapse/server_notices/server_notices_manager.py", line 149, in get_or_create_notice_room_for_user
    info, _ = await self._room_creation_handler.create_room(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room.py", line 728, in create_room
    last_stream_id = await self._send_events_for_new_room(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room.py", line 882, in _send_events_for_new_room
    await self.room_member_handler.update_membership(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 310, in update_membership
    result = await self.update_membership_locked(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 555, in update_membership_locked
    return await self._local_membership_update(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/room_member.py", line 215, in _local_membership_update
    raise LimitExceededError(
synapse.api.errors.LimitExceededError: 429: Too Many Requests
```

**Comment by clokep** [comment]
Related to #8735 / #8736, I think. Not sure it is a direct duplicate of either though.

**Comment by ulope** [comment]
We've been running into this recently. This seems to leave the room in a broken state:
What we've noticed:

- No powerlevels are set (although the room owner can set them later on).
- Public rooms are not public, users are denied from joining with a "You are not invited to this room" response.

**Comment by richvdh** [comment]
I think this is a dup of #8309
