### ISSUE TITLE
Provide list of all caches with default limits numbers

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/synapse#8811]
**Description:**
In `homeserver.yaml` we have `caches` section, where can fill cache factors - global, or per_cache.
But I can't find the way to lookup list of all cache names (best with short description) that use Synapse, and default values in numbers.

For example, what is default number for `get_users_who_share_room_with_user` - 100, 1000, or 10000? If we will have the default numbers, we will can calculate result using simple math.

And separate question about root parameter `event_cache_size` - is `caches.global_factor` value applies to it, or not?

Also in current `homeserver.yaml` template parameter `event_cache_size` located in root, not inside `cache` category,  - is this right? 

Regarding this change https://github.com/matrix-org/synapse/pull/6391/files/2619891343cc55b307ae36e6dda6247b2d6a5f73#diff-bfb2b1823a1f152109d0007dc9c8c6e83a99ea81ffa6edc08ecca5fc8b3475daR75 - `event_cache_size` variable in must be moved from the root to `caches` subcategory, right?

**Comment by callahad** [comment]
It could be nice to implement this as a CLI command that prints the current defaults for everything, just to ensure it's always up-to-date.

We'd gladly review PRs that do this, but we're not sure we'll be able to implement that on this side in the near future.

**Comment by MurzNN** [comment]
Also I got strange behavior, when trying to pick up right value for _event_auth_cache
I added key `caches.per_cache_factors._event_auth_cache = 5.0` and with this key Synapse stops starting, without any understandable record in logs! Here is log content:
```
2020-12-01 21:17:56,723 - twisted - 254 - INFO -  - (TCP Port 9092 Closed)
2020-12-01 21:17:57,163 - twisted - 254 - INFO -  - (TCP Port 9093 Closed)
2020-12-01 21:17:57,497 - twisted - 254 - INFO -  - (TCP Port 8008 Closed)
2020-12-01 21:17:59,065 - twisted - 254 - ERROR -  - ----------------------------------------
2020-12-01 21:17:59,065 - twisted - 254 - ERROR -  - Exception happened during processing of request from ('127.0.0.1', 36864)
2020-12-01 21:17:59,070 - twisted - 254 - ERROR -  - Traceback (most recent call last):
2020-12-01 21:17:59,070 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/socketserver.py", line 650, in process_request_thread
2020-12-01 21:17:59,071 - twisted - 254 - ERROR -  -     self.finish_request(request, client_address)
2020-12-01 21:17:59,071 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
2020-12-01 21:17:59,071 - twisted - 254 - ERROR -  -     self.RequestHandlerClass(request, client_address, self)
2020-12-01 21:17:59,071 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -     self.handle()
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/http/server.py", line 427, in handle
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -     self.handle_one_request()
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -     method()
2020-12-01 21:17:59,076 - twisted - 254 - ERROR -  -   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/metrics/_exposition.py", line 211, in do_GET
2020-12-01 21:17:59,077 - twisted - 254 - ERROR -  -     self.wfile.write(output)
2020-12-01 21:17:59,077 - twisted - 254 - ERROR -  -   File "/usr/lib/python3.8/socketserver.py", line 799, in write
2020-12-01 21:17:59,077 - twisted - 254 - ERROR -  -     self._sock.sendall(b)
2020-12-01 21:17:59,077 - twisted - 254 - ERROR -  - BrokenPipeError: [Errno 32] Broken pipe
2020-12-01 21:17:59,077 - twisted - 254 - ERROR -  - ----------------------------------------
```

**Comment by MurzNN** [comment]
I have found the list of cache names and per-cache limits in Synapse prometheus metrics, here is cli command to lookup:
```
curl -s http://localhost:9102/_synapse/metrics | grep synapse_util_caches_cache_max_size | sed 's/[^"]*"\([^"]*\)"\}\(.*\)/\1\2/'
```
where `http://localhost:9102/` is configured address for metrics in Synapse YAML:
```
  - type: metrics
    port: 9102
    bind_addresses:
      - '127.0.0.1'
```
Here are default values (with `caches.global_factor: 1.0`):
```
regex_push_cache 50000.0
client_ip_last_seen 50000.0
*getEvent* 10240.0
device_id_exists 10000.0
_event_auth_cache 500000.0
*stateGroupCache* 50000.0
*stateGroupMembersCache* 500000.0
token_cache 10000.0
get_monthly_active_count 1000.0
user_last_seen_monthly_active 1000.0
get_monthly_active_count_by_service 1000.0
_get_server_verify_key 1000.0
_get_bare_e2e_cross_signing_keys 1000.0
get_user_by_access_token 1000.0
is_guest 1000.0
get_user_by_id 1000.0
get_user_filter 1000.0
is_support_user 1000.0
get_rooms_for_user_with_stream_ordering 500000.0
_get_presence_for_user 1000.0
get_room_version_id 10000.0
_get_state_group_for_event 50000.0
get_state_group_delta 10000.0
_get_rules_for_room 1000.0
get_push_rules_for_user 5000.0
get_push_rules_enabled_for_user 5000.0
_get_joined_users_from_context 100000.0
_get_joined_profile_from_event_id 10000.0
is_ignored_by 5000.0
get_global_account_data_by_type_for_user 5000.0
get_latest_event_ids_in_room 5000.0
matches_user_in_member_list 1000.0
get_users_in_room 100000.0
get_aliases_for_room 5000.0
_get_joined_hosts 10000.0
_get_joined_hosts_cache 10000.0
_get_linearized_receipts_for_room 1000.0
get_users_who_share_room_with_user 500000.0
count_e2e_one_time_keys 10000.0
get_e2e_unused_fallback_key_types 10000.0
is_room_blocked 10000.0
get_event_reference_hash 1000.0
is_user_erased 1000.0
get_retention_policy_for_room 1000.0
get_last_receipt_event_id_for_user 1000.0
get_unread_event_push_actions_by_room_for_user 5000.0
get_current_state_ids 100000.0
is_host_joined 10000.0
get_receipts_for_room 1000.0
get_receipts_for_user 1000.0
get_users_with_read_receipts_in_room 1000.0
get_device_list_last_stream_id_for_remote 10000.0
_get_cached_user_device 1000.0
get_cached_devices_for_user 1000.0
get_relations_for_event 1000.0
get_aggregation_groups_for_event 1000.0
get_invited_rooms_for_local_user 1000.0
get_room_summary 100000.0
get_earliest_token_for_stats 1000.0
get_user_in_directory 1000.0
get_forgotten_rooms_for_user 1000.0
get_applicable_edit 1000.0
get_account_data_for_room_and_type 5000.0
get_event_ordering 5000.0
get_account_data_for_user 1000.0
get_account_data_for_room 1000.0
generate_room_entry 1000.0
get_ratelimit_for_user 10000.0
```

**Comment by MurzNN** [comment]
Also will be good to lookup memory usage size for each cache type, but this info seems missed in Prometheus metrics.

**Comment by MurzNN** [comment]
Seems here https://github.com/matrix-org/synapse/pull/9881 is implemented memory measurement for caches.
