### ISSUE TITLE
Providing avatar_url in PUT /_synapse/admin/v2/users/<user_id> will cause the request to fail

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#8871]
```
2020-12-03 17:54:46,740 - synapse.http.server - 79 - ERROR - PUT-4829- Failed handle request via 'UserRestServletV2': <XForwardedForRequest at 0x7fea0361d880 method='PUT' uri='/_synapse/admin/v2/users/%40demo2_fake%3Ahs-mi1-staging.ems.host' clientproto='HTTP/1.1' site=8008>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 228, in _async_render_wrapper
    callback_return = await self._async_render(request)
  File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 405, in _async_render
    callback_return = await raw_callback_return
  File "/usr/local/lib/python3.8/site-packages/synapse/rest/admin/users.py", line 321, in on_PUT
    await self.profile_handler.set_avatar_url(
  File "/usr/local/lib/python3.8/site-packages/synapse/handlers/profile.py", line 264, in set_avatar_url
    if not self.hs.is_mine(target_user):
  File "/usr/local/lib/python3.8/site-packages/synapse/server.py", line 297, in is_mine
    return domain_specific_string.domain == self.hostname
AttributeError: 'str' object has no attribute 'domain'
```

https://github.com/matrix-org/synapse/blob/f737368a26bb9eea401fcc3a5bdd7e0b59e91f09/synapse%2Frest%2Fadmin%2Fusers.py#L219-L222

Synapse 1.23.0

**Comment by clokep** [comment]
I think it should be using `user_id` instead of `target_user`. Seems that line 193 might also have that issue.

**Comment by clokep** [comment]
> I think it should be using `user_id` instead of `target_user`. Seems that line 193 might also have that issue.

Oops. I read this code backwards, seems that the caller on line 220 is correct, and the one on 321 is wrong. 😄
