### ISSUE TITLE
Error loop: psycopg2.errors.UniqueViolation: could not create unique index "e2e_cross_signing_keys_stream_idx" DETAIL:  Key (stream_id)=(3547) is duplicated.

### ISSUE THREAD

**Issue by nivekuil** [matrix-org/synapse#8904]
Had a working synapse install, but since a reboot/synapse image update synapse seems to have broken (clients cannot connect, nivekuil.com times out on federation tester) and synapse logs are filled with this, repeating periodically forever:

```
2020-12-09 12:16:27,575 - synapse.storage.background_updates - 111 - ERROR - background_updates-0 - Error doing update
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 107, in run_background_updates
    result = await self.do_next_background_update(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 219, in do_next_background_update
    await self._do_background_update(desired_duration_ms)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 255, in _do_background_update
    items_updated = await update_handler(progress, batch_size)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 411, in updater
    await self.db_pool.runWithConnection(runner)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 712, in runWithConnection
    return await make_deferred_yieldable(
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 707, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/background_updates.py", line 372, in create_index_psql
    c.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 271, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 297, in _do_execute
    return func(sql, *args)
psycopg2.errors.UniqueViolation: could not create unique index "e2e_cross_signing_keys_stream_idx"
DETAIL:  Key (stream_id)=(3547) is duplicated.
```

**Comment by clokep** [comment]
Seems to be the same as #8781? That gives some ideas of how to fix this.

**Comment by nivekuil** [comment]
Ah, yeah it is. I deleted the offending rows and the error logs went away, but my server still appears to be unreachable, so I guess that was a red herring. Thanks for pointing that out
