### ISSUE TITLE
Pusher Exception processing notifs

### ISSUE THREAD

**Issue by vsatmydynipnet** [matrix-org/synapse#8967]
### Description

The pusher has a problem while pushing notifies to Gotify. Partially a few notifies coming through but always these exceptions. Gotify to Web and Mobile Clients works fine and wget sending messages too.

### Steps to reproduce

- 
- Homeserver running Synapse 1.24.0 and Postgres on FreeBSD 12.2
- Gotify from today with Matrix Plugin using SQLite on Extra FreeBSD 12.2 Server

### Log
```
2020-12-17 19:05:19,833 - synapse.http.client - 410 - INFO - httppush.process-12 - Received response to POST https://gotify.mydom.com:63555/plugin/2/custom/P_E7Q236437820sAEpm/hook: 200
2020-12-17 19:05:19,835 - synapse.push.httppusher - 177 - ERROR - httppush.process-12 - Exception processing notifs
Traceback (most recent call last):
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/push/httppusher.py", line 175, in _process
    await self._unsafe_process()
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/push/httppusher.py", line 213, in _unsafe_process
    processed = await self._process_one(push_action)
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/push/httppusher.py", line 300, in _process_one
    rejected = await self.dispatch_push(event, tweaks, badge)
  File "/usr/home/synapse/env/lib/python3.6/site-packages/synapse/push/httppusher.py", line 408, in dispatch_push
    rejected = resp["rejected"]
TypeError: string indices must be integers
```
I do not want to publish different URL's here, but if somebody wants a test account on the Gotify Server, let me know.

**Comment by clokep** [comment]
FYI that URLs like that will break in the future -- see #8865.

It would be interesting to see what the response coming from the Gotify serve is. I'm surprised that `resp` isn't a dict at that point though?

**Comment by vsatmydynipnet** [comment]
The URL:

https://gotify.mydom.com:63555/plugin/2/custom/P_E7Q236437820sAEpm/hook

comes from the Matrix-Gotify Plugin. I will send Sorunome a message.

**Comment by Sorunome** [comment]
As gotify plugins are not capable of adding listeners to root paths, only to namespaced paths, this change sadly makes the gotify plugin completely useless. Instead of being just a plugin for gotify a completely new gateway will have to be developed :/

**Comment by Sorunome** [comment]
A possible solution for this would be to only require `/_matrix/...` to be at the **end** of the path, not the full one. Of course this would require a new MSC, but would it have a chance to see adoption?

**Comment by richvdh** [comment]
Let's take the discussion of acceptable paths to https://github.com/matrix-org/matrix-doc/issues/2721.

**Comment by richvdh** [comment]
I'm going to assume this is due to the gotify hook not returning a valid response for the push API.
