### ISSUE TITLE
user_directory.notify_new_event - there is no unique or exclusion constraint matching the ON CONFLICT specification

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/synapse#9282]
I migrated my database to a new postgres RDS, and it seems to mostly have survived except for this exception being spammed over and over in my logs. I presume I must be missing something on this table, but i couldn't figure it out from reading the code.

Version: `1.26.0`
Installed from git

```
2021-02-01 10:34:59,849 - synapse.metrics.background_process_metrics - 210 - ERROR - user_directory.notify_new_event-93178- Background process 'user_directory.notify_new_event' threw an exception
Traceback (most recent call last):
  File "/opt/synapse/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/opt/synapse/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 110, in process
    await self._unsafe_process()
  File "/opt/synapse/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 167, in _unsafe_process
    await self._handle_deltas(deltas)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 229, in _handle_deltas
    await self._handle_profile_change(
  File "/opt/synapse/lib/python3.8/site-packages/synapse/handlers/user_directory.py", line 427, in _handle_profile_change
    await self.store.update_profile_in_user_dir(user_id, new_name, new_avatar)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/databases/main/user_directory.py", line 471, in update_profile_in_user_dir
    await self.db_pool.runInteraction(
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 656, in runInteraction
    result = await self.runWithConnection(
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 739, in runWithConnection
    return await make_deferred_yieldable(
  File "/opt/synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/synapse/lib/python3.8/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/synapse/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/synapse/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 306, in _runWithConnection
    compat.reraise(excValue, excTraceback)
  File "/opt/synapse/lib/python3.8/site-packages/twisted/python/compat.py", line 464, in reraise
    raise exception.with_traceback(traceback)
  File "/opt/synapse/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 297, in _runWithConnection
    result = func(conn, *args, **kw)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 734, in inner_func
    return func(db_conn, *args, **kwargs)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 534, in new_transaction
    r = func(cursor, *args, **kwargs)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/databases/main/user_directory.py", line 384, in _update_profile_in_user_dir_txn
    new_entry = self.db_pool.simple_upsert_txn(
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 981, in simple_upsert_txn
    self.simple_upsert_txn_native_upsert(
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 1103, in simple_upsert_txn_native_upsert
    txn.execute(sql, list(allvalues.values()))
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 288, in execute
    self._do_execute(self.txn.execute, sql, *args)
  File "/opt/synapse/lib/python3.8/site-packages/synapse/storage/database.py", line 314, in _do_execute
    return func(sql, *args)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification
```

**Comment by Half-Shot** [comment]
Looks like some indexes didn't apply during migration. Have applied manually and now it looks better.
