### ISSUE TITLE
signedjson.sign.SignatureVerifyException with Mascarene Homeserver

### ISSUE THREAD

**Issue by njouanin** [matrix-org/synapse#9349]
Hi,
I'm using a local synapse instance (1.26) running inside a docker container to test federation API with [Mascarene](https://gitlab.com/mascarene/mascarene).
Everything runs on localhost; I'm currently faced with Synapse raising a SignatureVerifyException when verifying signatures sent back by Mascarene when called at `GET matrix://mascarene.dev.mascarene.org/_matrix/key/v2/server/ed25519%3A86DpZCI` (mascarene.dev.mascarene.org is localhost).

Here is the synapse trace:
```
synapse_dev      | 2021-02-08 16:17:04,148 - synapse.crypto.keyring - 667 - INFO - POST-0 - Requesting keys dict_items([('mascarene.dev.mascarene.org', {'ed25519:86DpZCI': 1612801024145})]) from notary server matrix.org
synapse_dev      | 2021-02-08 16:17:04,150 - synapse.http.federation.well_known_resolver - 254 - INFO - POST-0 - Fetching https://matrix.org/.well-known/matrix/server
synapse_dev      | 2021-02-08 16:17:04,993 - synapse.http.federation.well_known_resolver - 191 - INFO - POST-0 - Response from .well-known: {'m.server': 'matrix-federation.matrix.org:443'}
synapse_dev      | 2021-02-08 16:17:06,422 - synapse.http.matrixfederationclient - 209 - INFO - POST-0 - {POST-O-1} [matrix.org] Completed request: 200 OK in 2.27 secs - POST matrix://matrix.org/_matrix/key/v2/query
synapse_dev      | 2021-02-08 16:17:06,440 - synapse.http.federation.well_known_resolver - 254 - INFO - POST-0 - Fetching https://mascarene.dev.mascarene.org/.well-known/matrix/server
synapse_dev      | 2021-02-08 16:17:06,478 - synapse.http.federation.well_known_resolver - 191 - INFO - POST-0 - Response from .well-known: {'m.server': 'mascarene.dev.mascarene.org:443'}
synapse_dev      | 2021-02-08 16:17:06,595 - synapse.http.matrixfederationclient - 209 - INFO - POST-0 - {GET-O-2} [mascarene.dev.mascarene.org] Completed request: 200 OK in 0.16 secs - GET matrix://mascarene.dev.mascarene.org/_matrix/key/v2/server/ed25519%3A86DpZCI
synapse_dev      | 2021-02-08 16:17:06,596 - synapse.crypto.keyring - 807 - ERROR - POST-0 - Error getting keys {'ed25519:86DpZCI': 1612801024145} from mascarene.dev.mascarene.org
synapse_dev      | Traceback (most recent call last):
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/signedjson/sign.py", line 131, in verify_signed_json
synapse_dev      |     verify_key.verify(message, signature)
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/nacl/signing.py", line 112, in verify
synapse_dev      |     return nacl.bindings.crypto_sign_open(smessage, self._key)
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/nacl/bindings/crypto_sign.py", line 111, in crypto_sign_open
synapse_dev      |     raise exc.BadSignatureError("Signature was forged or corrupt")
synapse_dev      | nacl.exceptions.BadSignatureError: Signature was forged or corrupt
synapse_dev      | 
synapse_dev      | During handling of the above exception, another exception occurred:
synapse_dev      | 
synapse_dev      | Traceback (most recent call last):
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/synapse/crypto/keyring.py", line 800, in get_key
synapse_dev      |     keys = await self.get_server_verify_key_v2_direct(server_name, key_ids)
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/synapse/crypto/keyring.py", line 868, in get_server_verify_key_v2_direct
synapse_dev      |     response_keys = await self.process_v2_response(
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/synapse/crypto/keyring.py", line 560, in process_v2_response
synapse_dev      |     verify_signed_json(response_json, server_name, key.verify_key)
synapse_dev      |   File "/usr/local/lib/python3.8/site-packages/signedjson/sign.py", line 133, in verify_signed_json
synapse_dev      |     raise SignatureVerifyException(
synapse_dev      | signedjson.sign.SignatureVerifyException: Unable to verify signature for mascarene.dev.mascarene.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
synapse_dev      | 2021-02-08 16:17:06,597 - synapse.federation.transport.server - 312 - WARNING - POST-0 - authenticate_request failed: 401: Failed to find any key to satisfy VerifyJsonRequest(server=mascarene.dev.mascarene.org, key_ids=['ed25519:86DpZCI'], min_valid=1612801024145)
```

and Mascarene response to `GET matrix://mascarene.dev.mascarene.org/_matrix/key/v2/server/ed25519%3A86DpZCI`:
```
{
  "server_name" : "mascarene.dev.mascarene.org",
  "verify_keys" : {
    "ed25519:86DpZCI" : {
      "key" : "ar1aHWXhPwC49MGv8rpm1RRU4SPBGu2WUxVH97jWa3o"
    }
  },
  "old_verify_keys" : {
    
  },
  "signatures" : {
    "mascarene.dev.mascarene.org" : {
      "ed25519:86DpZCI" : "rl8L9ibLwWyDB1MGrzBlSFYHXzY-WZgdS74nRJDX486ABBFSn_MNXyPSousErMGlYaOiDKA7TOui7j0Pjpl_Dg"
    }
  },
  "valid_until_ts" : 1613407314773
}
```

According to [this test page](http://ed25519.herokuapp.com/) signatures look valid:

![image](https://user-images.githubusercontent.com/728898/107252260-997c8500-6a4e-11eb-9fc7-2639c4f04fca.png)

So I don't understant why synapse complains about this signature. Any help welcome.

**Comment by richvdh** [comment]
I think the problem might be with `"signatures": null`. See https://matrix.org/docs/spec/appendices#signing-details: `signatures` should be absent.

**Comment by njouanin** [comment]
It seems to work, I see `200 OK` in `GET /_matrix/key/v2/server/ed25519%3A86DpZCI`:
```
synapse_dev      | 2021-02-09 16:00:07,023 - synapse.crypto.keyring - 667 - INFO - POST-0 - Requesting keys dict_items([('mascarene.dev.mascarene.org', {'ed25519:86DpZCI': 1612886407020})]) from notary server matrix.org
synapse_dev      | 2021-02-09 16:00:07,026 - synapse.http.federation.well_known_resolver - 254 - INFO - POST-0 - Fetching https://matrix.org/.well-known/matrix/server
synapse_dev      | 2021-02-09 16:00:08,490 - synapse.http.federation.well_known_resolver - 191 - INFO - POST-0 - Response from .well-known: {'m.server': 'matrix-federation.matrix.org:443'}
synapse_dev      | 2021-02-09 16:00:09,877 - synapse.http.matrixfederationclient - 209 - INFO - POST-0 - {POST-O-1} [matrix.org] Completed request: 200 OK in 2.85 secs - POST matrix://matrix.org/_matrix/key/v2/query
synapse_dev      | 2021-02-09 16:00:09,889 - synapse.http.federation.well_known_resolver - 254 - INFO - POST-0 - Fetching https://mascarene.dev.mascarene.org/.well-known/matrix/server
synapse_dev      | 2021-02-09 16:00:09,918 - synapse.http.federation.well_known_resolver - 191 - INFO - POST-0 - Response from .well-known: {'m.server': 'mascarene.dev.mascarene.org:443'}
synapse_dev      | 2021-02-09 16:00:09,995 - synapse.http.matrixfederationclient - 209 - INFO - POST-0 - {GET-O-2} [mascarene.dev.mascarene.org] Completed request: 200 OK in 0.11 secs - GET matrix://mascarene.dev.mascarene.org/_matrix/key/v2/server/ed25519%3A86DpZCI
synapse_dev      | 2021-02-09 16:00:10,007 - synapse.federation.transport.server - 312 - WARNING - POST-0 - authenticate_request failed: 401: Invalid signature for server mascarene.dev.mascarene.org with key ed25519:86DpZCI: Unable to verify signature for mascarene.dev.mascarene.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
synapse_dev      | 2021-02-09 16:00:10,008 - synapse.http.server - 74 - INFO - POST-0 - <SynapseRequest at 0x7fd5ec14efd0 method='POST' uri='/_matrix/federation/v1/publicRooms' clientproto='HTTP/1.1' site='8448'> SynapseError: 401 - Invalid signature for server mascarene.dev.mascarene.org with key ed25519:86DpZCI: Unable to verify signature for mascarene.dev.mascarene.org: <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
synapse_dev      | 2021-02-09 16:00:10,008 - synapse.access.https.8448 - 295 - INFO - POST-0 - ::ffff:127.0.0.1 - 8448 - {None} Processed request: 2.989sec/-0.000sec (0.014sec, 0.003sec) (0.003sec/0.018sec/6) 257B 401 "POST /_matrix/federation/v1/publicRooms HTTP/1.1" "mascarene/0.3.0-SNAPSHOT" [0 dbevts]
``` 
I still get a 401 error due to authentication failure, now I need to investigate this. Thanks
