### ISSUE TITLE
Entries in homeserver.log: Background process 'user_directory.notify _new_event' threw an exception

### ISSUE THREAD

**Issue by happenpappen** [matrix-org/synapse#9467]
### Description

Since the upgrade to 1.27.0 the homeserver.log of my server is constantly filled with this exception:

```
2021-02-22 22:51:09,884 - synapse.metrics.background_process_metrics - 211 - ERROR - user_directory.notify_new_event-284907 - Background process 'user_directory.notify
_new_event' threw an exception
Traceback (most recent call last):
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 110, in process
    await self._unsafe_process()
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/handlers/user_directory.py", line 159, in _unsafe_process
    self.pos, room_max_stream_ordering
  File "/home/synapse/synapse/env/lib/python3.7/site-packages/synapse/storage/databases/main/state_deltas.py", line 51, in get_current_state_deltas
    prev_stream_id = int(prev_stream_id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Besides this i can't see that this message is affecting any server function.

### Steps to reproduce

- Configure metrics like described in docs/metrics-howto.md (i used the listener method of step 2.)
- start the server

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from _homeserver.log_, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.
-->
There should be no exceptions in the logfile...

### Version information

<!-- IMPORTANT: please answer the following questions, to help us narrow down the problem -->

<!-- Was this issue identified on matrix.org or another homeserver? -->
- **Homeserver**: My own homeserver

If not matrix.org: stop.pe

<!--
 What version of Synapse is running?

You can find the Synapse version with this command:

$ curl http://localhost:8008/_synapse/admin/v1/server_version

(You may need to replace `localhost:8008` if Synapse is not configured to
listen on that port.)
-->
- **Version**: {"server_version":"1.27.0","python_version":"3.7.3"}

- **Install method**: pip in venv
<!-- examples: package manager/git clone/pip  -->

- **Platform**: Debian 10, virtual Server, 24GB RAM, 6 Cores, >400GB free HDD Space.
<!--
Tell us about the environment in which your homeserver is operating
distro, hardware, if it's running in a vm/container, etc.
-->

**Comment by happenpappen** [comment]
Just saw, that this has already been handled in Issue #9420
