### ISSUE TITLE
Exception in logs

### ISSUE THREAD

**Issue by chagai95** [matrix-org/synapse#9673]
```
2021-03-23 13:39:55,838 - synapse.metrics.background_process_metrics - 210 - ERROR - prune_old_user_ips-124834 - Background process 'prune_old_user_ips' threw an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/client_ips.py", line 404, in _prune_old_user_ips
    await self.db_pool.runInteraction(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 668, in runInteraction
    result = await self.runWithConnection(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 751, in runWithConnection
    return await make_deferred_yieldable(
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    conn = self.connectionFactory(self)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 35, in __init__
    self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 72, in reconnect
    self._connection = self._pool.connect()
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 413, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

2021-03-23 13:39:55,839 - synapse.metrics.background_process_metrics - 210 - ERROR - update_client_ips-124834 - Background process 'update_client_ips' threw an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/synapse/metrics/background_process_metrics.py", line 208, in run
    return await maybe_awaitable(func(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/databases/main/client_ips.py", line 486, in _update_client_ips_batch
    await self.db_pool.runInteraction(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 668, in runInteraction
    result = await self.runWithConnection(
  File "/usr/local/lib/python3.8/site-packages/synapse/storage/database.py", line 751, in runWithConnection
    return await make_deferred_yieldable(
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 282, in _runWithConnection
    conn = self.connectionFactory(self)
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 35, in __init__
    self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 72, in reconnect
    self._connection = self._pool.connect()
  File "/usr/local/lib/python3.8/site-packages/twisted/enterprise/adbapi.py", line 413, in connect
    conn = self.dbapi.connect(*self.connargs, **self.connkw)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

```

**Comment by chagai95** [comment]
I'll clear the database I guess
