### ISSUE TITLE
Matrix service won't start on clean install of Ubuntu server 20.04.2

### ISSUE THREAD

**Issue by MasterJubei** [matrix-org/synapse#9683]
EDIT: The answer for me appears to be yes. Using the manual install it seems to work fine via `sudo apt install -y lsb-release wget apt-transport-https
`
The default package is broken? Is this even maintained? Or is it just broken on my end.
Original post:
------------------------------
Installed via apt install synapse-server
I ran the installer, put my server's name

Now when trying to start the service and getting the status I only get:
```
root@matrix:~# systemctl status matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2021-03-25 01:26:42 UTC; 1min 44s ago
    Process: 17375 ExecStartPre=/usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserve>
    Process: 17389 ExecStart=/usr/bin/python3 -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.y>
   Main PID: 17389 (code=exited, status=0/SUCCESS)

Mar 25 01:26:42 matrix synapse[17389]: synapse.storage.data_stores.main.event_push_actions: [None] Searching for strea>
Mar 25 01:26:42 matrix synapse[17389]: synapse.storage.data_stores.main.event_push_actions: [None] Found stream orderi>
Mar 25 01:26:42 matrix synapse[17389]: synapse.storage.data_stores: [None] Starting 'state' data store
Mar 25 01:26:42 matrix synapse[17389]: synapse.storage.data_stores: [None] Database 'master' prepared
Mar 25 01:26:42 matrix synapse[17389]: synapse.server: [None] Finished setting up.
Mar 25 01:26:42 matrix synapse[17389]: synapse.app.homeserver: [None] Scheduling stats reporting for 3 hour intervals
Mar 25 01:26:42 matrix synapse[17389]: synapse.app.homeserver: [] Running
Mar 25 01:26:42 matrix synapse[17389]: synapse.app.homeserver: [] Set file limit to: 524288
Mar 25 01:26:42 matrix synapse[17389]: synapse.config.tls: [] Loading TLS key from /etc/matrix-synapse/homeserver.tls.>
Mar 25 01:26:42 matrix systemd[1]: matrix-synapse.service: Succeeded.
```

Is the default installation broken on Ubuntu?
If I try to curl 127.0.0.1:8008 I simply get Connection refused
I did not change any configuration settings, this is a clean install.
Trying to make a new user results in:
```
root@matrix:~# register_new_matrix_user -c /etc/matrix-synapse/homeserver.yaml http://localhost:8008
New user localpart [root]: admin
Password:
Confirm password:
Make admin [no]: yes
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f21361a0520>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8008): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21361a0520>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/register_new_matrix_user", line 22, in <module>
    main()
  File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 224, in main
    register_new_user(
  File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 137, in register_new_user
    request_registration(
  File "/usr/lib/python3/dist-packages/synapse/_scripts/register_new_matrix_user.py", line 47, in request_registration
    r = requests.get(url, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8008): Max retries exceeded with url: /_matrix/client/r0/admin/register (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f21361a0520>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by theAeon** [comment]
Are you using the matrix hosted repository or the default one? I'm having issues myself with the matrix repository.

**Comment by MasterJubei** [comment]
@theAeon 
I am using their repository for it to work, the one in Ubuntu does not work. It looks for a key like you are experiencing in the config file and it does not work.

**Comment by theAeon** [comment]
Oh to be entirely clear I never installed the default repo. I suppose what this means is that unless I'm being stupid this is a different bug.  Weirdly enough the macaroon_secret_key isn't set and according to the config file

```

**Comment by richvdh** [comment]
> ```
> Mar 27 22:41:41 dendrite matrix-synapse[9458]: Config is missing macaroon_secret_key
> ```

this is a warning, not an error. It is unrelated to your problem.

Can you try running synapse directly from the commandline using the same command that systemd would use, to see what happens?

**Comment by richvdh** [comment]
> I got it. No issue.

so can I close this issue?

**Comment by MasterJubei** [comment]
> 
> 
> > I got it. No issue.
> 
> so can I close this issue?

The default configuration for Ubuntu 20.04 is still broken, so I think it is best left open. Their issue seems to have been different.

**Comment by richvdh** [comment]
@MasterJubei I'm afraid I'm very confused about what your issue is; please don't make me pick it out of a reddit thread.

If Synapse won't start, then the same question applies to you:

> Can you try running synapse directly from the commandline using the same command that systemd would use, to see what happens?

**Comment by MasterJubei** [comment]
@richvdh 
`2021-03-29 21:32:14,671 - root - 257 - WARNING - None- ***** STARTING SERVER *****
2021-03-29 21:32:14,671 - root - 258 - WARNING - None- Server /usr/lib/python3/dist-packages/synapse/app/homeserver.py version 1.11.0
2021-03-29 21:32:14,671 - root - 259 - INFO - None- Server hostname: matrix2.mydomain.net
2021-03-29 21:32:14,672 - synapse.app.homeserver - 340 - INFO - None- Setting up server
2021-03-29 21:32:14,672 - synapse.server - 240 - INFO - None- Setting up.
2021-03-29 21:32:14,674 - synapse.storage.data_stores - 48 - INFO - None- Preparing database 'master'...
2021-03-29 21:32:16,419 - synapse.storage.prepare_database - 309 - INFO - None- Upgrading schema to v55
2021-03-29 21:32:16,419 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 55/access_token_expiry.sql
2021-03-29 21:32:16,421 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 55/track_threepid_validations.sql
2021-03-29 21:32:16,421 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 55/users_alter_deactivated.sql
2021-03-29 21:32:16,423 - synapse.storage.prepare_database - 309 - INFO - None- Upgrading schema to v56
2021-03-29 21:32:16,423 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/add_spans_to_device_lists.sql
2021-03-29 21:32:16,425 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/current_state_events_membership.sql
2021-03-29 21:32:16,426 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/current_state_events_membership_mk2.sql
2021-03-29 21:32:16,426 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/delete_keys_from_deleted_backups.sql
2021-03-29 21:32:16,426 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/destinations_failure_ts.sql
2021-03-29 21:32:16,428 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/device_stream_id_insert.sql
2021-03-29 21:32:16,428 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/devices_last_seen.sql
2021-03-29 21:32:16,432 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/drop_unused_event_tables.sql
2021-03-29 21:32:16,432 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/event_expiry.sql
2021-03-29 21:32:16,433 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/event_labels.sql
2021-03-29 21:32:16,433 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/event_labels_background_update.sql
2021-03-29 21:32:16,433 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/fix_room_keys_index.sql
2021-03-29 21:32:16,434 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/hidden_devices.sql
2021-03-29 21:32:16,435 - synapse.storage.prepare_database - 393 - INFO - None- Applying engine-specific schema 56/hidden_devices_fix.sql.sqlite
2021-03-29 21:32:16,440 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/nuke_empty_communities_from_db.sql
2021-03-29 21:32:16,441 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/public_room_list_idx.sql
2021-03-29 21:32:16,441 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/redaction_censor.sql
2021-03-29 21:32:16,443 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/redaction_censor2.sql
2021-03-29 21:32:16,444 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/redaction_censor4.sql
2021-03-29 21:32:16,444 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/remove_tombstoned_rooms_from_directory.sql
2021-03-29 21:32:16,444 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/room_key_etag.sql
2021-03-29 21:32:16,446 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/room_membership_idx.sql
2021-03-29 21:32:16,446 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/room_retention.sql
2021-03-29 21:32:16,447 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/signing_keys.sql
2021-03-29 21:32:16,448 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/signing_keys_nonunique_signatures.sql
2021-03-29 21:32:16,448 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/state_group_room_idx.sql
2021-03-29 21:32:16,448 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/stats_separated.sql
2021-03-29 21:32:16,450 - synapse.storage.prepare_database - 378 - INFO - None- Running script 56/unique_user_filter_index.py
2021-03-29 21:32:16,488 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/user_external_ids.sql
2021-03-29 21:32:16,489 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 56/users_in_public_rooms_idx.sql
2021-03-29 21:32:16,489 - synapse.storage.prepare_database - 309 - INFO - None- Upgrading schema to v57
2021-03-29 21:32:16,489 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 57/delete_old_current_state_events.sql
2021-03-29 21:32:16,490 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 57/device_list_remote_cache_stale.sql
2021-03-29 21:32:16,490 - synapse.storage.prepare_database - 378 - INFO - None- Running script 57/local_current_membership.py
2021-03-29 21:32:16,490 - synapse.storage.prepare_database - 389 - INFO - None- Applying schema 57/rooms_version_column.sql
2021-03-29 21:32:16,492 - synapse.storage.prepare_database - 393 - INFO - None- Applying engine-specific schema 57/rooms_version_column_2.sql.sqlite
2021-03-29 21:32:16,502 - synapse.storage.data_stores - 58 - INFO - None- Starting 'main' data store
2021-03-29 21:32:16,504 - synapse.storage.data_stores.main.event_push_actions - 499 - INFO - None- Searching for stream ordering 1 month ago
2021-03-29 21:32:16,505 - synapse.storage.data_stores.main.event_push_actions - 503 - INFO - None- Found stream ordering 1 month ago: it's 0
2021-03-29 21:32:16,505 - synapse.storage.data_stores.main.event_push_actions - 506 - INFO - None- Searching for stream ordering 1 day ago
2021-03-29 21:32:16,505 - synapse.storage.data_stores.main.event_push_actions - 510 - INFO - None- Found stream ordering 1 day ago: it's 0
2021-03-29 21:32:16,507 - synapse.storage.data_stores - 68 - INFO - None- Starting 'state' data store
2021-03-29 21:32:16,507 - synapse.storage.data_stores - 81 - INFO - None- Database 'master' prepared
2021-03-29 21:32:16,508 - synapse.server - 243 - INFO - None- Finished setting up.
2021-03-29 21:32:16,515 - synapse.app.homeserver - 110 - INFO - - Running
2021-03-29 21:32:16,515 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 524288
2021-03-29 21:32:16,516 - synapse.config.tls - 517 - INFO - - Loading TLS key from /etc/matrix-synapse/homeserver.tls.key
2021-03-29 21:32:28,026 - root - 257 - WARNING - None- ***** STARTING SERVER *****
2021-03-29 21:32:28,026 - root - 258 - WARNING - None- Server /usr/lib/python3/dist-packages/synapse/app/homeserver.py version 1.11.0
2021-03-29 21:32:28,026 - root - 259 - INFO - None- Server hostname: matrix2.3dslice.net
2021-03-29 21:32:28,026 - synapse.app.homeserver - 340 - INFO - None- Setting up server
2021-03-29 21:32:28,027 - synapse.server - 240 - INFO - None- Setting up.
2021-03-29 21:32:28,028 - synapse.storage.data_stores - 48 - INFO - None- Preparing database 'master'...
2021-03-29 21:32:28,030 - synapse.storage.prepare_database - 309 - INFO - None- Upgrading schema to v57
2021-03-29 21:32:28,032 - synapse.storage.data_stores - 58 - INFO - None- Starting 'main' data store
2021-03-29 21:32:28,034 - synapse.storage.data_stores.main.event_push_actions - 499 - INFO - None- Searching for stream ordering 1 month ago
2021-03-29 21:32:28,034 - synapse.storage.data_stores.main.event_push_actions - 503 - INFO - None- Found stream ordering 1 month ago: it's 0
2021-03-29 21:32:28,034 - synapse.storage.data_stores.main.event_push_actions - 506 - INFO - None- Searching for stream ordering 1 day ago
2021-03-29 21:32:28,035 - synapse.storage.data_stores.main.event_push_actions - 510 - INFO - None- Found stream ordering 1 day ago: it's 0
2021-03-29 21:32:28,036 - synapse.storage.data_stores - 68 - INFO - None- Starting 'state' data store
2021-03-29 21:32:28,037 - synapse.storage.data_stores - 81 - INFO - None- Database 'master' prepared
2021-03-29 21:32:28,037 - synapse.server - 243 - INFO - None- Finished setting up.
2021-03-29 21:32:28,044 - synapse.app.homeserver - 110 - INFO - - Running
2021-03-29 21:32:28,044 - synapse.app.homeserver - 30 - INFO - - Set file limit to: 524288
2021-03-29 21:32:28,045 - synapse.config.tls - 517 - INFO - - Loading TLS key from /etc/matrix-synapse/homeserver.tls.key`

This is a clean install of matrix-synapse on Ubuntu's repository version. The default config does not allow it to start since it looking for a key that is not there.

**Comment by richvdh** [comment]
> This is a clean install of matrix-synapse on Ubuntu's repository version.

sigh. When you file an issue, please make it clear which version of the software you are talking about, to avoid wasting everyone's time.

We are not responsible for Ubuntu, nor its decision to ship broken packages. You may like to upvote https://bugs.launchpad.net/ubuntu/+source/matrix-synapse/+bug/1848709.

**Comment by josteink** [comment]
I had a similar issue after dist-upgrading from Ubuntu 18.04 to Ubuntu 20.04.

This involved a change in both Python-version and in PostgreSQL version in my setup, and Matrix-synapse failed to start after the upgrade.

After manually completing the PostegreSQL upgrade, the matrix-synapse service still failed to start and kept on auto-restarting.

However after re-enabling the matrix.org apt-repo, the following commands solved this issue for me:

````
sudo pip3 install psycopg2 --upgrade
sudo apt reinstall matrix-synapse-py3
````

Hopefully this can help others too :smile:
